### PR TITLE
docs(Layout): update demo style to `sticky`

### PR DESCRIPTION
**Pull request by ZCY-G**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ZZZCNY** [comment]
@li-jia-nan 好了

**Comment by li-jia-nan** [comment]
CI挂了，你 snap 文件是手动更新的吗？这个有命令行的自动更新的，可以参考一下 package.json 里面的命令行

**Comment by ZZZCNY** [comment]
> CI挂了，你 snap 文件是手动更新的吗？这个有命令行自动更新的，可以参考一下 package.json 里面的命令行

我尝试了几次，都不能生成 snapshot，都是错误。

**Comment by li-jia-nan** [comment]
`npm run test:update components/layout/__tests__/`

我这边试了一下是可以的

**Comment by ZZZCNY** [comment]
> `npm run test:update components/layout/__tests__/`
> 
> 我这边试了一下是可以的

我的命令错了😭

**Review by afc163 — APPROVED** [review]

**Pull request merged**
