### PR TITLE
feat: add support to it_IT locale in forms, images and page headers b…

### PR DESCRIPTION
**Pull request by fedeolto**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

I saw that italian translations for form validation were missing (like for example when a field is required)

### 💡 Background and solution
I added them 

### 📝 Changelog
Now italian is available for forms, images and page headers components

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     x      |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by xrkffgg** [comment]
master branch

**Comment by afc163** [comment]
ping @fedeolto

**Comment by fedeolto** [comment]
Sorry @afc163 but time is never enough, I saw that there is a warning in a test about Menu component, do you have any hints to fix it?

**Comment by afc163** [comment]
You can recreate a new PR to master branch.

**Comment by afc163** [comment]
Closing for no response.

**Pull request closed without merging**
