### PR TITLE
docs: add icon for title

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      -     |
| 🇨🇳 Chinese |     -      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
为啥要改这个

**Comment by afc163** [comment]
国旗更准确

图片

**Comment by li-jia-nan** [comment]
> 为啥要改这个

啊，原来是国旗，那就是我浏览器的问题了，我这边没看到国旗

**Comment by li-jia-nan** [comment]
> 为啥要改这个

那我close掉

**Comment by li-jia-nan** [comment]
> 国旗更准确
> 
> 图片

QQ截图20221010230638

可能是windows的原因？

**Pull request closed without merging**
