### PR TITLE
feat: input number support prefix

### LINKED ISSUE #14284: Allow prefix/suffix and addonBefore/addonAfter on InputNumber just like Input component
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I was working on a custom input that formats the entered data into monetary value.

Something like: `9876.12` => `9,876.12` and also wanted to add a `$` prefix into the input without being part of the input value.

I noticed we can do that with the `Input` component but in order to format the entered value to the format I wanted I realized it was not going to be as easy as `InputNumber` with `formatter` and `parser` props.

I ended up wrapping up an `InputNumber` into another component which accepts all the same props as `InputNumber` plus the `prefix` option and made it look exactly as `Input`.

The render method looks something like

```jsx
render() {
  const { prefix, ...inputNumberProps } = this.props;

  return (
    <span className="my-custom-component">
      <span className="prefix">{prefix}</span>
      <InputNumber {...inputNumberProps} />
    </span>
  );
}
```

I think it would be useful if `InputNumber` accepts a `prefix` prop for cases like this.

### What does the proposed API look like?
The use and result should be exactly as `Input`.

`<InputNumber prefix="$" />`

`<InputNumber prefix={<span>$</span>} />`

### PR DESCRIPTION
**Pull request by Austaras**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature

### 🔗 Related issue link

closes #14284

Maybe we could add postfix too, just make number handler cover it when focused? @afc163 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     add `prefix` to `InputNumber`      |
| 🇨🇳 Chinese |      `InputNumber` 增加 `prefix` 属性支持     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
这个预览怎么一直是 building。

**Comment by Austaras** [comment]
> 这个预览怎么一直是 building。

可能是我之前把 fork 仓库 的 Github Action 关了

**Review by afc163 — APPROVED** [review]

**Comment by nuintun** [comment]
@afc163 既然支持了前缀，建议把后缀也支持~

**Comment by afc163** [comment]
后缀会和 +- 按钮冲突，设计上比较难搞。

**Comment by nuintun** [comment]
@afc163 +- 不隐藏了，一直显示就 ok 了，得稍微调整下以前的设计~

**Pull request merged**
