### PR TITLE
Add 2.11.1 changelog

### PR DESCRIPTION
**Pull request by yesmeck**

### CODE REVIEW

**Comment by afc163** [comment]
- [ ] https://github.com/ant-design/ant-design/commit/dde8df5612f543231e178fae52488bf8ab27a662
- [ ] https://github.com/ant-design/ant-design/commit/61d67f4563aaffb523e6605afe6862f9bc0c684d

**Comment by yesmeck** [comment]
61d67f4 这个没看懂修了啥

**Comment by afc163** [comment]
RangePicker 底部多了一条边框。

image

**Comment by yesmeck** [comment]
Updated.

**Comment by afc163** [comment]
https://ant.design/changelog 

Next 在英文版下还在。

**Pull request merged**
