### PR TITLE
improvement: improve Slider component handle style

### LINKED ISSUE #19073: Slider: custom styles for handle
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/slider-t9sp9)

### Steps to reproduce
1. Change handle width and height to 25px (for example)
2. Focus ant slider and change value from default
3. Change tab in browser or just use alt-tab
4. See that slider value changes

### What is expected?
Slider's value shouldn't change

### What is actually happening?
I dont really understand what is happening, but the same styles on rc-slider works well and considering that ant slider uses rc-slider probably problem is in  ant styles, but i'm not sure

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | react 16.8.6 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 76.0.3809.100 |

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Fixed #19073 
Ref: https://github.com/ant-design/ant-design/pull/19119

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  -   |
| 🇨🇳 Chinese | 修复 Slider 组件设置 `handle` 大小后定位错误的问题。  |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
和升级 rc-slider 关系不大，就是 Slider 本身的问题。

**Comment by shaodahong** [comment]
> 和升级 rc-slider 关系不大，就是 Slider 本身的问题。

嗯，相对于 `feature` 来说是 fix，因为 feature 分支的 slider 默认情况下就是坏的，对于 master 来说不是，算是 bug 或者优化吧

**Comment by afc163** [comment]
changelog 要针对已发布版本的角度来说，分支上当前的情况不是用户面临的真实问题。

**Comment by afc163** [comment]
image

提交 PR 时自检一下，勾掉所有的勾。

**Comment by shaodahong** [comment]
Done.

**Review by afc163 — APPROVED** [review]

**Pull request merged**
