### PR TITLE
fix: Upload pass UploadList prefixCls

### PR DESCRIPTION
**Pull request by swchen**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Upload `prefixCls` don't work on file list.          |
| 🇨🇳 Chinese | 修复 Upload `prefixCls` 对列表不生效的问题。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
解决什么问题

**Comment by swchen** [comment]
> 解决什么问题

自定义 Upload 样式, 如 `@upload-prefix-cls: 'custom-upload';`
https://github.com/ant-design/ant-design/blob/master/components/upload/style/index.less#L4

使用方式: `<Upload prefixCls="custom-upload">`

问题: `<UploadList>` 的 `prefixCls` 仍是 `ant-upload`

**Comment by afc163** [comment]
可以加个测试用例。

**Comment by afc163** [comment]
CI 挂了，检查一下

**Comment by afc163** [comment]
图片

请按模板填写内容。

**Comment by afc163** [comment]
ping @swchen

**Pull request merged**
