### PR TITLE
fix Menu selected change error

### PR DESCRIPTION
**Pull request by Jack-Ye**
protect none parameter[openKeys, defaultOpenKeys] Menu

### CODE REVIEW

**Comment by Jack-Ye** [comment]
https://github.com/react-component/menu/pull/75

**Comment by afc163** [comment]
Could you provide a codepen demo about the issue that this change for?

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Jack-Ye** [comment]
http://codepen.io/anon/pen/oBWGKv?editors=0010

**Comment by afc163** [comment]
Also fixed it in rc-menu@5.0.9, retry to reinstall `antd@2.6.4`.

**Comment by mmacedoeu** [comment]
I have a similar problem with undefined openKeys:
http://codepen.io/mmacedoeu/pen/EZrpdX

How can I test your solution ?

**Comment by afc163** [comment]
Menu'children don't support HOC for now, you try try like this: http://codepen.io/anon/pen/KaYwRN?editors=1010

**Comment by afc163** [comment]
http://codepen.io/anon/pen/zNXxap?editors=1010 @mmacedoeu you should pass through all props to SubMenu.

**Pull request merged**
