### PR TITLE
Add position prop for Layout.Sider to set the position of zero-width-trigger

### LINKED ISSUE #9644: Right-side Sider Trigger
### What problem does this feature solve?
Enables a collapsible sider for the right side.

Currently, if the sider is on the right hand side of the screen, the trigger is positioned as if the sider was on the left hand side:

https://codesandbox.io/s/73j86r15x0

### What does the proposed API look like?
```
<Sider
  collapseRight
</Sider>
```

### PR DESCRIPTION
**Pull request by dengfuping**
Fix #9644.

### CODE REVIEW

**Comment by afc163** [comment]
There is a `reverseArrow` for this feature.

**Comment by dengfuping** [comment]
@afc163 It's a special trigger that always on Sider's right side When `collapsedWidth="0"`. The PR allows to set the special trigger on Sider's left side. Maybe `reverseArrow` should be set automatically according to `position` prop. 

image

**Comment by dengfuping** [comment]
The demo https://codesandbox.io/s/14xm3onk6l shows the problem.

**Comment by afc163** [comment]
```css
.ant-layout-sider:last-child .ant-layout-sider-zero-width-trigger {
  ...
}
```

We can try to fix position of collapse trigger by this way.

**Comment by dengfuping** [comment]
Yeah, but adding a prop like `position` will make it easier.

**Comment by afc163** [comment]
I think a extra `position` prop is unneccessary.

**Comment by yesmeck** [comment]
Try to fix the issue with CSS.

**Pull request closed without merging**
