### PR TITLE
add transitionName from message.config

### PR DESCRIPTION
**Pull request by muzea**
#9388 

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

On the outside is difficult to get messageInstance,if can add a getMessageInstance method, write unit test will be much simpler.

### CODE REVIEW

**Comment by afc163** [comment]
We can make `transitionName` configable but don't document it, because we don't encourage people to override the default animation.

**Comment by muzea** [comment]
done.

**Comment by avalanche1** [comment]
> because we don't encourage people to override the default animation.

I wonder why?

**Comment by afc163** [comment]
Like you don't want to override the Material Design default animation.

**Comment by ke1vin666** [comment]
@afc163 But I really don't want a zoom animation when Modal show,  any suggestions?

**Pull request merged**
