### PR TITLE
fix: demo bug of draggable modal

### PR DESCRIPTION
**Pull request by chutaozh**
该值默认false时，弹出窗口，鼠标不经过modal 的header（即绕过header，从左/右/下方进入modal的body）,鼠标左键在body区域按下=着不放并移动，modal也会跟着移动，有时需要选中复制body内文字时，modal一直跟着移动而造成无法选择文字

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix: After Modal opened, if the mouse does not pass through the header, selecting the body content will move the Modal         |
| 🇨🇳 Chinese | 修复：弹出Modal后，如果鼠标未经header，选择body内容时会移动modal   |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at ac2b83a</samp>

Fixed a modal rendering bug by disabling drag and resize by default. Changed the initial state of `disabled` in `components/modal/demo/modal-render.tsx`.

### <samp>🤖 Generated by Copilot at ac2b83a</samp>

* Disable modal drag and resize by default to fix rendering bug ([link](https://github.com/ant-design/ant-design/pull/41630/files?diff=unified&w=0#diff-809373ca4d89e35286dbd5d0aa3b26e07e7211e45de8dd0dc171d31b9f778730L8-R8))

### CODE REVIEW

**Comment by li-jia-nan** [comment]
不过 `disabled` 设置初始值设置为 `true` 似乎也合理

**Comment by li-jia-nan** [comment]
麻烦把 PR title 改成英文，并且填一下 PR body 中的 ChangeLog

**Review by li-jia-nan — APPROVED** [review]

**Comment by chutao-zhang** [comment]
> 按照你提供的重现步骤尝试了一下，并没有这个问题，可以录个视频看看吗？

演示

**Comment by chutao-zhang** [comment]
> 按照你提供的重现步骤尝试了一下，并没有这个问题，可以录个视频看看吗？

演示

**Comment by chutao-zhang** [comment]
Zhang ChuTao 将撤回邮件“[ant-design/ant-design] 该示例代码存在一些体验上的缺陷 (PR #41630)”。

**Pull request merged**
