### PR TITLE
Update variable.less

### PR DESCRIPTION
**Pull request by tangjinzhou**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Promote @base-primary to the top level for easy replacement of theme colors      |
| 🇨🇳 Chinese |    提升 @base-primary 到顶层，方便替换主题色       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by tangjinzhou** [comment]
方便统一更改主题色

**Comment by afc163** [comment]
具体解决什么问题？

**Comment by nichtsam** [comment]
> 具体解决什么问题？

現在@base-primary因作用域無法被覆蓋，導致variable.less提供的css變數在客製主題色時，只會生成以@blue-6為基準的變數。
把@base-primary提升為全域變數，才能在使用時設定variable.less生成變數的基準。

**Comment by tangjinzhou** [comment]
@afc163 楼上正解

**Comment by nichtsam** [comment]
Is this going to be merged any time soon?

**Comment by smshuja** [comment]
Will this be merged? Very important for us. Want to avoid using a fork.

**Comment by poechiang** [comment]
> Will this be merged? Very important for us. Want to avoid using a fork.

+1

**Comment by li-jia-nan** [comment]
Hey! Conflicting files, and it seems this is now really outdated. If this is something that still makes sense to the latest master version of antd, please send a new PR with this change :)

**Pull request closed without merging**
