### PR TITLE
Fix Affix flickering when scrolling

### PR DESCRIPTION
**Pull request by ztplz**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your pull request, thank you!

* [ ] Make sure that you propose pull request to right branch: bugfix for `master`, feature for branch `feature`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a pull request to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you pull request.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by ztplz** [comment]
Fix #13662

**Comment by ztplz** [comment]
这个问题的原因是 mousewheel 事件和 js不在一个线程里 鼠标快速滑动的时候，因为初始style没有fixed，所以affix会滑动，然后js监听到affix滑动，开始给元素设置fixed，但是这些包括setState都是异步的，等设置好了fixed后affix已经滑动了，然后把它位置重置回来就会看到闪烁
如果设置bottom应该会有同样闪烁情况   这个以后改

**Comment by afc163** [comment]
这个解决方案是什么原理。

**Comment by ztplz** [comment]
image
这个是判断有没有位移然后设置fixed的，逻辑没问题，检测到有位移就是这里 > 0, 但是因为性能的问题，因为浏览器mousewheel事件不是由js控制的，你检测到移动之后再设置fixed，这个时候元素已经滑动。 我开始是牺牲1 px 的误差来处理这个问题，但是好像不需要。
image
其实 >= 就行了

**Comment by ztplz** [comment]
如果它符合fixed的要求就给他设置个fixed，不用等它移了之后再给它设置fixed

**Review by afc163 — APPROVED** [review]

**Pull request merged**
