### PR TITLE
fix: import type in calendar

### PR DESCRIPTION
**Pull request by zeunny**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

nothing

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix: import type in calendar  |
| 🇨🇳 Chinese | 日历中的 "import type" |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Comment by afc163** [comment]
Why change this?

**Comment by ee2e** [comment]
> Why change this?

This causes a 'next build error'.

**Comment by afc163** [comment]
Could you upgrade TypeScript version in your application?

**Comment by ee2e** [comment]
> Could you upgrade TypeScript version in your application?

Currently using version 4.4.4. The same symptom occurs after upgrading to version 4.9.5.

**Comment by li-jia-nan** [comment]
I don’t know why ci fail, I changed it in another PR #40538

**Pull request closed without merging**
