### PR TITLE
test: and pull_request_target branches-ignore

### PR DESCRIPTION
**Pull request by shaodahong**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Maybe resolve https://github.com/ant-design/ant-design/commit/c3f6a38c65344665c1ea27d6b6cffaad2e018686#commitcomment-44082697

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
忘了 squash 了

**Comment by yoyo837** [comment]
揪他猫耳朵

**Comment by shaodahong** [comment]
其实是 squash 的，merge 应该会产生一条 merge 信息，但是不知道为啥没 squash 掉

**Comment by yoyo837** [comment]
应该是手误了😁。squash不掉应该是大bug。

**Pull request merged**
