### PR TITLE
Continue works on #12667

### PR DESCRIPTION
**Pull request by zombieJ**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

#12667

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Why just merge https://github.com/ant-design/ant-design/pull/12667

**Comment by zombieJ** [comment]
> Why not just merge #12667

Need user to merge master to fix CI broken.

**Comment by afc163** [comment]
Miss https://github.com/ant-design/ant-design/pull/12667/files#diff-f8c0a607a738cdc5c31fbe3e05e57841R11

**Comment by zombieJ** [comment]
> https://github.com/ant-design/ant-design/pull/12667/files#diff-f8c0a607a738cdc5c31fbe3e05e57841R11 lost

This change added by another commit: https://github.com/yueyes/ant-design/commit/cf1f511af8c26a5e9d4158c91ea5476b073ec0a2

**Pull request merged**
