### PR TITLE
doc: sort api following some rule

### LINKED ISSUE #7856: doc: api sorting follow some rule
### What problem does this feature solve?
We can find what api we need quickly.

#### Option 1 

Following the alphabetical order.

The part of the [Table API](https://ant.design/components/table-cn/#Table)

* rowSelection
* pagination

we can change this to 

* pagination
* rowSelection

#### Option 2

Classify the API, property, event...

Also the part of the Table API

* onChange
* loading
* ...
* onRowMouseLeave

we can change this to 

* loading 
* ...
* onChange
* onRowMouseLeave

### PR DESCRIPTION
**Pull request by monkindey**
fix https://github.com/ant-design/ant-design/issues/7856

sorting script at ~~https://github.com/monkindey/antd-api-sort~~  https://github.com/ant-design/ant-design/pull/7896/commits/841acca006c9c7eb66cb91f2576380588f4d99d9

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [ ] ~~Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).~~
* [ ]  ~~Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.~~
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.
* [ ] ~~Update API docs for the component.~~
* [ ] ~~Update/Add demo to demonstrate new feature.~~
* [ ] ~~Update TypeScript definition for the component.~~
* [ ] ~~Add unit tests for the feature.~~

Oops, too many modified markdown. 

Any feedback will welcome.

### CODE REVIEW

**Comment by benjycui** [comment]
Where is the scripts.. I cannot find it.

**Comment by monkindey** [comment]
Not in ant-design project, it was extracted at https://github.com/monkindey/antd-api-sort

**Comment by yesmeck** [comment]
Simple script file can put in https://github.com/ant-design/ant-design/tree/master/scripts :smile:

**Comment by monkindey** [comment]
Concerns:

1. How do we run it? Also configure the `scripts` key in package.json?
2. Can I make dir for the api-sort script?

**Comment by yesmeck** [comment]
It's only about 100 LOC, I thinks it's simple to put it all in `scripts/sort-api-table.js` and run it with `node ./scripts/sort-api-table.js`.

**Comment by monkindey** [comment]
I think maybe we can make another PR to add sort-api-table into the ant-design repo. What do you think of ? And any idea to resolve the conflict ?

**Comment by yesmeck** [comment]
You don't need create another PR, since all these changes are made by the script, so it's safe to reset these changes and rebase the master then re-format these markdowns again.

**Comment by afc163** [comment]
Can we make a `npm run lint:markdown` to avoiding bad format markdown of API table.

**Comment by monkindey** [comment]
Thanks, @yesmeck 

I think should keep an eye on the conflicted file `components/table/index.en-US.md` and `components/table/index.zh-CN.md`, maybe I miss something.cc @afc163 because of this [commit](https://github.com/ant-design/ant-design/commit/fda3f6ddcd37356b7ff875823a0518e71d2a9872).

**Comment by monkindey** [comment]
@afc163  Any idea about `npm run lint:markdown` ?

**Comment by afc163** [comment]
Something like `npm run lint` but check the style of markdown table.

**Comment by monkindey** [comment]
This one https://github.com/wooorm/remark-lint ?

**Comment by monkindey** [comment]
`Tag` test breaks the ci, more information https://travis-ci.org/ant-design/ant-design/jobs/288891423#L4665-L4674 . I didn't modify the `Tag` test. What happens?

**Comment by yesmeck** [comment]
If remark-lint is introduced, we create a custom rule like  [remark-lint-alphabetize-lists](https://github.com/vhf/remark-lint-alphabetize-lists/blob/master/lib/alphabetical-list-items.js).

**Comment by monkindey** [comment]
yeah, if you all like it, I am glad to make another PR.

**Comment by yesmeck** [comment]
dingtalk20171023123850

This table looks wired, I think size props group together will be better.

**Comment by monkindey** [comment]
yeah, agreed. There are two options about it.

### Option 1

also following the alphabet

```
lg
md
sm
xl
xs
```

### Option 2

following size order

```
 xs: '480px',
 sm: '768px',
 md: '992px',
 lg: '1200px',
 xl: '1600px'
```

**Comment by afc163** [comment]
Option 2

**Comment by monkindey** [comment]
Hi all, I add the size props group sorting feature. 

And can we review this PR as soon as possible? 😂  Because there are always some file that should resolve the conflict.

**Comment by yesmeck** [comment]
@monkindey You don't need commit markdown files, I will run the script after this PR get merged.

**Comment by monkindey** [comment]
Thanks, now can I reset the markdown files in this PR ? I have no idea about how to do.

**Comment by monkindey** [comment]
Any test lands at [this](https://github.com/monkindey/antd-api-sort/tree/master/test)

**Comment by benjycui** [comment]
> Thanks, now can I reset the markdown files in this PR ? I have no idea about how to do.

https://www.google.com/search?q=git+reset+file+commit&oq=git+reset+file&aqs=chrome.2.69i57j0l5.5661j0j7&sourceid=chrome&ie=UTF-8

**Comment by yesmeck** [comment]
😄 Merged, @monkindey  great work!

**Comment by monkindey** [comment]
Thanks.

**Pull request merged**
