### PR TITLE
Arabic Documentation

### LINKED ISSUE #41641: Arabic Documentation
### What problem does this feature solve?

This feature will help the Arabic users to be more comfortable using your tool and checking your recommendation.

A lot of languages noticed in the readme, but Arabic is not there, so let's add it!

### What does the proposed API look like?

There is no API in this feature.

### PR DESCRIPTION
**Pull request by RihamSalman**
Thanks! close #41641

### CODE REVIEW

**Comment by li-jia-nan** [comment]
Please revert irrelevant changes

**Comment by li-jia-nan** [comment]
Please revert irrelevant changes，other people's commits should not appear here~

**Comment by li-jia-nan** [comment]
You can commit to `master branch`.

**Review by abenhamdine — CHANGES_REQUESTED** [review]
there are some changes unrelated to translation

**Comment by RihamSalman** [comment]
Those irrelevant commits appeared only after I did PR, shall I try PR to Master branch? I have no idea about the new irrelevant commits

**Comment by li-jia-nan** [comment]
lint error

**Comment by afc163** [comment]
ping @RihamSalman @abenhamdine

**Comment by afc163** [comment]
Please keep the PR template as content and fill it.

**Comment by afc163** [comment]
ping @RihamSalman @abenhamdine

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/41963

**Pull request closed without merging**
