### PR TITLE
site: optimize the website arrow style

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### before:

https://github.com/ant-design/ant-design/assets/49217418/ecaee6a4-4a33-4769-9c39-5858506706b0

### after:

https://github.com/ant-design/ant-design/assets/49217418/e49bf004-1ca1-40c4-abd1-8da4a86d3dd7

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | site: optimize the website arrow style |
| 🇨🇳 Chinese | 优化官网箭头样式，无需纳入 ChangeLog |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 62fa80f</samp>

Refactor and improve `ComponentTokenTable` component. Use `@emotion/react` for styling and add collapsible sub-tables. Remove unused code.

### <samp>🤖 Generated by Copilot at 62fa80f</samp>

*  Import `css` function from `@emotion/react` to style components with `css` prop ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L1-R1))
*  Define `useStyle` hook to generate `css` objects for table title and arrow icon based on `open` state ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93R28-R73))
*  Convert `SubTokenTable` and `ComponentTokenTable` components to function expressions with `React.FC` type annotation ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L34-R88), [link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L105-R151))
*  Add `open` state and `setOpen` function to `SubTokenTable` component to control table visibility ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L34-R88))
*  Replace `details` and `summary` elements with `div` and `i` elements for table title and arrow icon in `SubTokenTable` component ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L69-R145))
*  Add `onClick` handler to table title in `SubTokenTable` component to toggle `open` state ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L69-R145))
*  Wrap table in conditional rendering based on `open` state in `SubTokenTable` component ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L69-R145))
*  Remove `as any` cast from `value` property of data source in `SubTokenTable` component ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L69-R145))
*  Simplify `filter` callback to use `Boolean` as a shorthand for truthy values in `SubTokenTable` component ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L69-R145))
*  Remove commented out code and fragment element from `.dumi/theme/builtins/ComponentTokenTable/index.tsx` file ([link](https://github.com/ant-design/ant-design/pull/42591/files?diff=unified&w=0#diff-377ed68f4e882f6438c31331026bdb11548e6b62be65727a5793cda37badfa93L127-R174))

### CODE REVIEW

**Comment by afc163** [comment]
感觉箭头偏下，偏远。

图片

**Comment by li-jia-nan** [comment]
> 感觉箭头偏下，偏远。

水平位置可以调整一下，垂直位置不太好改，现在展开之后是剧中的，未展开状态是有点偏下，如果往上调一点的话，未展开剧中了，展开之后又会偏上了

**Comment by afc163** [comment]
那这个可能不太适用，默认不展开时的效果看着不太好。

**Comment by li-jia-nan** [comment]
我换成 antd icon 库里面的图标吧

**Comment by li-jia-nan** [comment]
@afc163 改成这样了：

https://github.com/ant-design/ant-design/assets/49217418/ba7369e0-80e2-4868-80af-4a7ab0f2980e

**Comment by afc163** [comment]
图片
这个有点隐晦，不容易发现是能展开的。

用这个图标好点。https://ant.design/components/collapse-cn 
或者这个：https://ant.design/components/table-cn#components-table-demo-expand

**Comment by li-jia-nan** [comment]
换成 `<RightOutlined />` 这个了

**Comment by li-jia-nan** [comment]
>  这个有点隐晦，不容易发现是能展开的。

加了个 `cursor: pointer`

**Review by afc163 — APPROVED** [review]

**Pull request merged**
