### PR TITLE
style: increase @text-color contrast

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/22343

### 💡 Background and solution

- PASS AA：https://contrast-ratio.com/#rgba%280%2C0%2C0%2C.65%29-on-white

image

- PASS AAA：https://contrast-ratio.com/#rgba%280%2C0%2C0%2C.85%29-on-white

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Darker @text-color for WCAG 2.0 on contrast ratio |
| 🇨🇳 Chinese | 加深默认文本色彩以满足 WCAG 2.0 对比度的规范。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by xrkffgg — APPROVED** [review]

**Comment by afc163** [comment]
@shaodahong 怎么更新 UI snapshot？

**Comment by shaodahong** [comment]
> @shaodahong 怎么更新 UI snapshot？

Docker 启动后，`npm run test-image -- -u`

**Pull request merged**
