### PR TITLE
fix(DatePicker): PopupClassName does not exist

### LINKED ISSUE #38294: DatePicker.RangePicker缺少popupClassName声明
### Reproduction link

[https://localhost.com](https://localhost.com)

### Steps to reproduce

DatePicker.RangePicker缺少popupClassName声明

### What is expected?

DatePicker.RangePicker缺少popupClassName声明

### What is actually happening?

DatePicker.RangePicker缺少popupClassName声明

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 17 |
| System | window edge |
| Browser | 100 |

### PR DESCRIPTION
**Pull request by AdonLee**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #38294 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix DatePicker.RangePicker `popupClassName` ts error.          |
| 🇨🇳 Chinese |  修复 DatePicker.RangePicker `popupClassName` TS 定义报错的问题。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Could you add a type test case in type.test.tsx?

**Comment by AdonLee** [comment]
@afc163 抱歉，没看懂怎么写， 期待学习下~~

**Comment by afc163** [comment]
在 https://github.com/ant-design/ant-design/blob/master/components/date-picker/__tests__/type.test.tsx 里，写一个原来会报错的用法，修改之后应该就能通过。

**Comment by afc163** [comment]
另外，ci 挂了，请检查

**Comment by afc163** [comment]
ping

**Pull request merged**
