### PR TITLE
Update locale es_ES (Spanish)

### PR DESCRIPTION
**Pull request by ginodeis**
Hi,

First of all, thanks and congratulations for this great project. I apologize in advance if i'm wrong and if I'm putting my hands where I should not.

I have found some translation problems using the package with es_ES locale. Continuing with the PR [#1471](https://github.com/ant-design/ant-design/issues/1471), I have tried to correct them.

Due to the rc-pagination don't have es_ES locale file (I will try to add a PR to correct this), I have added a Pagination variable with the translations to fix this until the package update.

Again, sorry if I am wrong and if I have wasted your time.

### CODE REVIEW

**Comment by benjycui** [comment]
👍 Thanks.

But you should PR to branch `feature-2.10`, for this is a new feature. Thanks.

**Comment by benjycui** [comment]
https://github.com/react-component/pagination/pull/73#issuecomment-297228832

Please update your code, thanks.

**Comment by ginodeis** [comment]
I don't know if I done the base branch change and the rebase well, sorry for the inconveniences.

**Comment by benjycui** [comment]
Oops....

If you are not familiar with git, you can just close this PR and create a new one. Because you should not mix others' commits into your PR.

**Comment by ginodeis** [comment]
I'm sorry for my lack of knowledge and for wasting your time. I close this PR and I create a new one. 
Thank you for your patience and your help

**Pull request closed without merging**
