### PR TITLE
fix(menu): inlineCollapsed props is overridden by siderContext

### PR DESCRIPTION
**Pull request by nia3y**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
当在 `Sider` 组件中使用 `Menu` 时,Menu 中的 `inlineCollapsed` 属性失效
Demo: [codesandbox](https://codesandbox.io/s/cold-architecture-9zxqm?file=/src/App.js)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |fixed inlineCollapsed props is overridden by siderContext|
| 🇨🇳 Chinese |修复 menu 中的  inlineCollapsed props 被 siderContext 覆盖的问题 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
来个用例？

**Comment by nia3y** [comment]
https://codesandbox.io/s/cold-architecture-9zxqm?file=/src/App.js
当 sider 的 collapsed 属性和 menu 的inlineCollapsed 不一致,外层的会覆盖掉内层的,导致menu不受控了

**Comment by afc163** [comment]
补个测试用例

**Comment by nia3y** [comment]
看到源码里面有warn提示,仔细看了下没有问题,是我想法错误了

**Pull request closed without merging**
