### PR TITLE
fix: hideAdd not work

### LINKED ISSUE #24617: Tabs hideAdd not working
https://ant.design/components/tabs/#components-tabs-demo-custom-add-trigger

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #24617

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Tabs `hideAdd` not working.       |
| 🇨🇳 Chinese |    修复 Tabs `hideAdd` 无效的问题。      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
例子里可以把 hideAdd 删掉，默认还是把所有能力都展现出来。

**Comment by zombieJ** [comment]
> 例子里可以把 hideAdd 删掉，默认还是把所有能力都展现出来。

两个例子都有的：
https://preview-24621-ant-design.surge.sh/components/tabs-cn/#components-tabs-demo-editable-card
https://preview-24621-ant-design.surge.sh/components/tabs-cn/#components-tabs-demo-custom-add-trigger

**Comment by jonnywang** [comment]
啥时候发布新版本

**Comment by yoyo837** [comment]
周五、六，日，一中某天

**Comment by afc163** [comment]
今天就发。

**Comment by yoyo837** [comment]
已发

**Pull request merged**
