### PR TITLE
style: 优化calendar若干样式

### PR DESCRIPTION
**Pull request by xrkffgg**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
https://next.ant.design/components/calendar-cn/
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |  1. 优化基本样式月份下拉框宽度；2. 优化通知事项的文字顺序；3. 优化卡片模式，选择框的尺寸 |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
是不是固定调宽一丢丢就好了？仍然保持固定宽度如何？

**Comment by xrkffgg** [comment]
@yoyo837 我看 3.26 是用的 `min-width`

**Comment by xrkffgg** [comment]
用`width` 好一些吗？

**Review by zombieJ — APPROVED** [review]

**Comment by zombieJ** [comment]
> 用`width` 好一些吗？

目前看没啥问题，有问题可以再改回来。

**Pull request merged**
