### PR TITLE
fix(date-picker): small fontHeight token

### LINKED ISSUE #50595: Incorrect date-picker small Token
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/date-picker/style/index.ts#L170-L172](https://github.com/ant-design/ant-design/blob/master/components/date-picker/style/index.ts#L170-L172)

### Steps to reproduce

components/date-picker/style/index.ts
```code
        // Size
        '&-large': {
          ...genPickerPadding(token, controlHeightLG, fontHeightLG, paddingInline),

          [`${componentCls}-input > input`]: {
            fontSize: fontSizeLG,
            lineHeight: lineHeightLG,
          },
        },

        '&-small': {
          ...genPickerPadding(token, controlHeightSM, fontHeight, paddingInlineSM),
        },
```

'&-small' genPickerPadding 没对应用用fontHeightSM Token , 覆写 >input 也没用 fontSizeSM和lineHeightSM Token 

### What is expected?

...genPickerPadding(token, controlHeightSM, fontHeightSM, paddingInlineSM),

### What is actually happening?

...genPickerPadding(token, controlHeightSM,fontHeight, paddingInlineSM),

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by coding-ice**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues
fix https://github.com/ant-design/ant-design/issues/50595

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix small fontHeight token          |
| 🇨🇳 Chinese | 修正错误的 small fontHeight token    |

### CODE REVIEW

**Comment by afc163** [comment]
看截图貌似不太对？

**Comment by coding-ice** [comment]
如果指的是，`DatePicker` 下方的元素出现了 `diff` ，是没问题的，因为整体的高度变高了 从`24px -> 26px`

**Comment by coding-ice** [comment]
不过我仔细看了下，没垂直居中了，我在修一下

**Comment by afc163** [comment]
小号的输入框高度应该是 24px，不应该是 26px。

**Comment by coding-ice** [comment]
看来这块，需要重新写下了，`padding` 那块实现需要改进下，已经有对应的组件 `token` 了，`fontSize` 应该也有问题，应该拿`inputFontSize`

**Pull request closed without merging**
