### PR TITLE
feat: Select support responsive `maxTagCount`

### LINKED ISSUE #28271: Select maxTagCount responsive support
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
云凤蝶用户反馈多 Tag 下折行的布局问题，需要支持响应式支持。

### What does the proposed API look like?
```tsx
<Select maxTagCount="responsive" />
```

ref #28234

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #28271

### 💡 Background and solution

* 底层使用 `rc-overflow` 实现响应式
* 部分样式抽成了 `margin-inline-start|end` 以移除 rtl 相关 less

预览 https://preview-28520-ant-design.surge.sh/components/select-cn/#components-select-demo-responsive

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Select `maxTagCount` support `responsive` in `multiple` mode.      |
| 🇨🇳 Chinese |     Select 多选模式下 `maxTagCount` 支持 `responsive`。       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/select/demo/big-data.md](https://github.com/ant-design/ant-design/blob/overflow/components/select/demo/big-data.md)
[View rendered components/select/demo/responsive.md](https://github.com/ant-design/ant-design/blob/overflow/components/select/demo/responsive.md)
[View rendered components/select/index.en-US.md](https://github.com/ant-design/ant-design/blob/overflow/components/select/index.en-US.md)
[View rendered components/select/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/overflow/components/select/index.zh-CN.md)

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
体积炸了。

**Comment by zombieJ** [comment]
嗯，`rc-select` 发完正式版后，`rc-tree-select` 跟进。

**Comment by zombieJ** [comment]
升级完后还是超了，`rc-overflow` gzip 后排出依赖本身代码 3KB，蛋疼。

**Comment by zombieJ** [comment]
align `rc-resize-observer` 后省了 0.5 KB。

**Comment by zombieJ** [comment]
`rc-overflow` 再压缩代码代码就要不好读了。不改了。

@afc163, sorry，俺又要把包大小调回来了 = =

**Comment by afc163** [comment]
@zombieJ master 啥也没干，也超了 270 kB。

**Comment by zombieJ** [comment]
底层的 `rc-resize-observer` 版本问题，问了 @chenshuai2144  说是 `0.x` 的版本不会自动 bump。所以我统一升级到了 `1.x` 这个月发 minor 就回归了。

**Pull request merged**
