### PR TITLE
fix: UploadList style (#20001)

### LINKED ISSUE #19790: Upload listType="picture-card" url loaded images doesn't work like uploaded images
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-oxwdb)

### Steps to reproduce
First 3 images are preloaded by url, in the fourth one upload a image with the same size as the first one, and it will work, but the first one will not

### What is expected?
Preloaded url images works like uploaded images, and option buttons are always visible.

### What is actually happening?
Preloaded and uploaded images work differently, and option buttons aren't visible in small height images.

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.11.0 |
| System | Windows 7 |
| Browser | Chrome |

### LINKED ISSUE #20001: Upload 组件，使用 fileList 属性预览已有的图片时，样式错误
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/eloquent-austin-8oq9r)

### Steps to reproduce
Upload 组件，使用 fileList 属性预览已有的图片时，样式错误。打开控制台可以发现，预览已有图片比上传图片，DOM结构中多了一个div，导致样式错误。

### What is expected?
Upload 组件，使用 fileList 属性预览已有的图片时，能正确显示图片

### What is actually happening?
Upload 组件，使用 fileList 属性预览已有的图片时，样式错误。

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | chrome |

---
请看一下图片：
image
image

### PR DESCRIPTION
**Pull request by maxmeng93**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
ref: #19689 
fix #20001
fix #19790

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
Pls update the snapshot.

**Comment by yoyo837** [comment]
@qq645381995 PTAL

**Comment by qq645381995** [comment]
#20008

**Comment by yoyo837** [comment]
Move to #20008

**Pull request closed without merging**
