### PR TITLE
feat/lang_tk

### PR DESCRIPTION
**Pull request by richxcame**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

Turkmen language were missing

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Added turkmen language |
| 🇨🇳 Chinese | 添加土库曼语 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by richxcame** [comment]
@afc163 @zombieJ @MadCcc @xrkffgg please help for this PR. It's important for me and for my project. As quickly as possible. 🙏🙏🙏

**Comment by yoyo837** [comment]
See https://github.com/ant-design/ant-design/pull/35060#issuecomment-1100371867 and wait upstream release new version include that what you want.

**Comment by richxcame** [comment]
> See [#35060 (comment)](https://github.com/ant-design/ant-design/pull/35060#issuecomment-1100371867) and wait upstream release new version include that what you want.

@yoyo837 in docs written translate `rc-picker` and `rc-pagination` and upgrade their versions in package.json. That's all i did. It's translation PR. No one will translate in turkmen. It's important 🙏

**Comment by zombieJ** [comment]
@richxcame ,do not modify `.github` folder content. CI will auto close for this. Revert related code first.

**Comment by yoyo837** [comment]
#35061

**Pull request closed without merging**
