### PR TITLE
fix: fix issue #19740

### LINKED ISSUE #19740: the prev and next button not work as expected when carousel stay in another carousel in some case
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/wizardly-hawking-cp0e3)

## one
1. open the link https://codesandbox.io/s/wizardly-hawking-cp0e3
2. click next button once at the top carousel 
3. click next or prev button at first child carousel

## another:
1. open the link https://codesandbox.io/s/wizardly-hawking-cp0e3
2. click prev button once at the top carousel
3. click next or prev button at second child carousel

### What is expected?
when click prev or next button of child carousel, it should slide

### What is actually happening?
not slide, nothing happen

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.7.0 |
| System | macOS Catalina 10.15.1 |
| Browser | 78.0.3904.87 (64) |

### PR DESCRIPTION
**Pull request by terminatorheart**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
fix #19740

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by terminatorheart** [comment]
经过测试处于alpha阶段的4.0版本也有此问题

**Comment by zombieJ** [comment]
ref #13215

**Comment by zombieJ** [comment]
Seems like slicker bug. When next page, the display content do not have the active className.

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/19740#issuecomment-554206529

**Pull request closed without merging**
