### PR TITLE
chore: update rc-rate

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 💡 Background and solution
没有实际的变化，一些 dep 依赖的更新

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  -         |
| 🇨🇳 Chinese |     -      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by ycjcl868 — APPROVED** [review]

**Comment by ycjcl868** [comment]
changelog 里不用提及 rc-rate 相关的更新吧

**Comment by xrkffgg** [comment]
> changelog 里不用提及 rc-rate 相关的更新吧

不用

**Comment by xrkffgg** [comment]
减了 500B 还可以 😂😂

**Comment by ycjcl868** [comment]
> 减了 500B 还可以 😂😂

500KB 的话可以提下😂

**Comment by xrkffgg** [comment]
这 CI 怎么一直 Pending 😂

**Comment by ycjcl868** [comment]
看起来卡住了

**Comment by ycjcl868** [comment]
重新 trigger 下？

**Comment by afc163** [comment]
image

**Comment by ycjcl868** [comment]
要充钱了

**Comment by afc163** [comment]
squash merge please..

**Pull request merged**
