### PR TITLE
feat(table): add disableAutoConfirm for filters

### LINKED ISSUE #31209: In table column make filter-confirm possible when dropdown becomes hidden
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It could make the end-user experience consistent.

If we have multiple columns in our table and we have mixed `filters` and `filterDropdown`s from column to column then the user experience is that there are some filers that don't need to be confirmed, only clicking away is enough and there are some that need to be.

### What does the proposed API look like?
Two options come in mind:

**1.**
```javascript
// FilterDropdown.tsx
const onVisibleChange = (newVisible: boolean) => {
[...]
  // add a new flag that will force confirmation on hide
  if (!newVisible && (!column.filterDropdown || column.confirmOnHide)) {
    onConfirm();
  }
```

now we can use it like this
```javascript
<Table.Column
  filterDropdown={<CustomComponent />}
  confirmOnHide
/>
```

**2.**
```javascript
// FilterDropdown.tsx
const triggerVisible = (newVisible: boolean) => {
  setVisible(newVisible);
  /* pass the confirmation function to
   * onFilterDropdownVisibleChange param, so user can call it when needed
   */
  onFilterDropdownVisibleChange?.(newVisible, onConfirm);
};
```

so we can use it like this
```javascript
<Table.Column
  filterDropdown={<CustomComponent />}
  onFilterDropdownVisibleChange={(newVisible, confirm) => {
    if (!newVisible) {
      confirm();
    }
  }}
/>
```

### PR DESCRIPTION
**Pull request by ifjGery**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

* close #31209
* confrom #17833

### 💡 Background and solution

When we use `filterDropdown` the blurring of the component won't trigger `onChange` like in the case of `filters`, this results in an inconsistent user experience. In this PR I added a flag to disable-auto-confirming on blur, this way we can use this not only on `filterDropdown` but on `filters` also as an added feature.

Now we can use `disableAutoConfirm` on columns.

usage:
```javascript
const columns = [
  {
    title: 'Type',
    dataIndex: 'type',
    key: 'type',
    disableAutoConfirm
  }
];

<Table columns={columns} />
```
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | adding `disableAutoConfirm` to column filtering, `filterDropdown` will trigger confirming by default on blur |
| 🇨🇳 Chinese | 将 `disableAutoConfirm` 添加到列过滤，`filterDropdown` 将在模糊时默认触发确认 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated ~~/provided or not needed~~
- [x] Demo is updated/provided ~~or not needed~~
- [x] TypeScript definition is updated ~~/provided or not needed~~
- [x] Changelog is provided ~~or not needed~~

### CODE REVIEW

**Comment by afc163** [comment]
Conflicting

**Comment by ifjGery** [comment]
Fixed, please approve workflows.

**Comment by afc163** [comment]
冲突了

**Comment by li-jia-nan** [comment]
Hey! I'm sorry we never got back to you about this but it seems this is now really outdated. If this is something that still makes sense to the latest master version of antd, please send a new PR with this change :)

**Pull request closed without merging**
