### PR TITLE
(enhance): improve translations

### PR DESCRIPTION
**Pull request by Zukhrik**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    improve uz_UZ translations        |
| 🇨🇳 Chinese |      优化 uz_UZ 国际化      |

### CODE REVIEW

**Comment by Zukhrik** [comment]
Guys help me this PR merge to master. My project need this enhances

**Comment by Zukhrik** [comment]
@yoyo837 can you help me?

**Comment by yoyo837** [comment]
> @yoyo837 can you help me?

Please remove lockfile and `node_modules` then reinstall it, and run `npm run test -- -u`, push all changed files to remote.

**Comment by Zukhrik** [comment]
> > @yoyo837 can you help me?
> 
> Please delete lockfile and `node_modules` then reinstall it, and run `npm run test -- -u`. After completion, push all changed files to the remote.

Done! What should i do then?

**Comment by yoyo837** [comment]
> > > @yoyo837 can you help me?
> > 
> > 
> > Please delete lockfile and `node_modules` then reinstall it, and run `npm run test -- -u`. After completion, push all changed files to the remote.
> 
> Done! What should i do then?

That's all, thanks.

**Review by yoyo837 — APPROVED** [review]

**Pull request merged**
