### PR TITLE
chore: update rc-table

### PR DESCRIPTION
**Pull request by yoyo837**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
`support other placement` 测试不通过

**Comment by afc163** [comment]
写一下 https://github.com/react-component/table/pull/450 和 https://github.com/react-component/table/pull/448 的 changelog 和关联的 Ant Design 仓库 issue。

**Comment by afc163** [comment]
#22832

**Comment by yoyo837** [comment]
来迟了！

**Pull request closed without merging**
