### PR TITLE
perf(Upload): prevent multiple render

### PR DESCRIPTION
**Pull request by liuzi6612**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [x] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
When dragging the visible area will cause multiple renders

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Optimize multiple renders when files are dragged and dropped         |
| 🇨🇳 Chinese |  优化文件拖放时多次render         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
来个用例？

**Comment by jameslahm** [comment]
这个应该不影响吧，如果`dragState`没变，`setState`之后，`react`还是会优化掉。

**Comment by xjh22222228** [comment]
> 这个应该不影响吧，如果`dragState`没变，`setState`之后，`react`还是会优化掉。

每次 setState 都会导致重新Render触发没必要的计算，通常拖拽上传不会停留很长时间，但我觉得还是有必要控制一下。

**Comment by jameslahm** [comment]
https://github.com/facebook/react/blob/933880b4544a83ce54c8a47f348effe725a58843/packages/react-reconciler/src/ReactFiberHooks.old.js#L1896-L1994
这个计算量可以忽略不计吧

**Pull request closed without merging**
