### PR TITLE
feat: add ga_IE locale

### PR DESCRIPTION
**Pull request by yoyo837**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Same as #24789
close #24789
close #24819

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      🇮🇪 Add Irish(ga_IE) locale.      |
| 🇨🇳 Chinese |     🇮🇪 添加爱尔兰语国际化支持。      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
image

**Comment by yoyo837** [comment]
👌

**Review by xrkffgg — APPROVED** [review]

**Comment by AbhijeetGaware** [comment]
@yoyo837 is it ready to use ??

**Comment by yoyo837** [comment]
> @yoyo837 is it ready to use ??

No, you need to wait for new next 3.x release.

**Comment by AbhijeetGaware** [comment]
> > @yoyo837 is it ready to use ??
> 
> No, you need to wait for the next new 3.x version release.

@yoyo837  okay Thanks.

**Comment by yoyo837** [comment]
@AbhijeetGaware v3.26.18 is out!

**Comment by AbhijeetGaware** [comment]
> @AbhijeetGaware v3.26.18 is out!

@yoyo837 Thank you so Much !! its working Great 🙏

**Pull request merged**
