### PR TITLE
chore: upgrade rc-menu

### LINKED ISSUE #36152: Layout的Sider折叠时Menu闪烁
### Reproduction link

[https://codesandbox.io/s/antd-reproduction-template-forked-447gqm?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-forked-447gqm?file=/index.js)

### Steps to reproduce

展开2级目录后，收起Sider

### What is expected?

不出现2级目录闪烁

### What is actually happening?

2级目录闪烁

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | Ubuntu |
| Browser | Firefox |

---
menu

antd@4.21.3

_Originally posted by @juneszh in https://github.com/ant-design/ant-design/issues/35343#issuecomment-1161392675_

### LINKED ISSUE #37083: React18.2.0导致menu收缩的时候会有hover浮窗
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-b1h7to?file=/index.js)

### Steps to reproduce

点开二级菜单，选中具体的item，
点击侧边栏的收缩按钮
再点击展开按钮

### What is expected?

侧边栏收缩
不会出现hover的浮窗

### What is actually happening?

收缩时闪现出item  hover时的浮窗

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 18.2.0 |
| System | win11 |
| Browser | Chrome 104.0.5112.81 |

---
相同代码，在react 17.0.2版本下不会出现item的hover浮窗

### LINKED ISSUE #38304: menu组件搭配React18出现菜单闪烁
### Reproduction link

[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce

暂无

### What is expected?

搭配React17就不会出现

### What is actually happening?

搭配React18会出现菜单闪烁

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18 |
| System | w10 |
| Browser | 谷歌 |

### LINKED ISSUE #38787: 含有内嵌菜单的Sider收缩时，Menu组件会闪动
### Reproduction link

[https://ant.design/components/menu-cn#components-menu-demo-inline-collapsed](https://ant.design/components/menu-cn#components-menu-demo-inline-collapsed)

### Steps to reproduce

1. 展开二级菜单； 2.点击收缩Sider按钮；

### What is expected?

没有Menu的多余闪动画面

### What is actually happening?

Menu组件快速闪动后消失

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2 |
| System | MacOS 13 Ventura |
| Browser | Chrome v107.0.5304.110 |

### LINKED ISSUE #38867: layout.sider 使用默认的trigger收起时，sider内submenu闪烁问题
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-wsin9i)

### Steps to reproduce

1. 点击submenu展开（必须要submenu为展开状态）
2. 点击layout.sider底步默认触发器 收起sidebar
3. 发现sider中的submenu会有一个闪烁的动画

### What is expected?

在submenu不管是展开还是收起时，在点击sider底部收缩触发器进行收缩sider时，都不应该出现submenu的动画闪烁

### What is actually happening?

submenu展开时，在点击sider底部收缩触发器进行收缩sidebar时，出现submenu的动画闪烁

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome 107 |

---
使用layout.sider布局
sider内嵌menu mode=inline
展开layout.sider.menu.submenu
点击sider底部trigger收起
出现submenu闪烁

### PR DESCRIPTION
**Pull request by JarvisArt**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/38534
close #38867
close #36152 
close #37083
close #38304  
close #38787 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix react18 use createRoot to render Submenu will flicker |
| 🇨🇳 Chinese | 修复 React18 中使用 createRoot 渲染 Submenu 会闪烁 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
补一下 🔗 Related issue link

**Comment by JarvisArt** [comment]
> 补一下 🔗 Related issue link

done!

**Comment by afc163** [comment]
加 close 或 fix

**Comment by JarvisArt** [comment]
done!

**Review by afc163 — APPROVED** [review]

**Pull request merged**
