### PR TITLE
feat: upgrade trigger to 4.2.1(#19536)

### PR DESCRIPTION
**Pull request by kerm1it**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

[#19536](https://github.com/ant-design/ant-design/issues/19536)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | 			 |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/tooltip/demo/destroy-tooltip-on-hide.md](https://github.com/Kermit-Xuan/ant-design/blob/upgrade-rc-tooptip-feature/components/tooltip/demo/destroy-tooltip-on-hide.md)

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
@afc163 更新快照的时候发现`local-privider`的快照被更新了，我就提上来了，你看看有没有问题?

**Review by yoyo837 — APPROVED** [review]

**Comment by afc163** [comment]
用例挂了，看上去不需要更新 snapshot。

**Comment by yoyo837** [comment]
@Kermit-Xuan 本地重装一下依赖

**Comment by Kermit-Xuan** [comment]
OK,我再试试

**Comment by Kermit-Xuan** [comment]
> @Kermit-Xuan 本地重装一下依赖

还是不行，我把用例取消了

**Comment by Kermit-Xuan** [comment]
@afc163  我安装依赖的时候发现有几个组件会有好几个不同的版本比如`rc-trigger`和`rc-menu`，我们如果把这些组件版本统一一下，是不是能减少不少包体积？

**Comment by yoyo837** [comment]
image

@ant-design/bisheng-plugin 里的不会打进来

**Comment by Kermit-Xuan** [comment]
> image
> 
> @ant-design/bisheng-plugin 里的不会打进来

OK，明白了

**Comment by yoyo837** [comment]
还是深色样式bundle问题

**Comment by Kermit-Xuan** [comment]
多了0.25KB

**Comment by yoyo837** [comment]
我觉得可以先合入，不理会那个。

**Comment by Kermit-Xuan** [comment]
昨天偏右说了这个问题，应该正在解决。

**Pull request merged**
