### PR TITLE
chore: split previewer

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
image
拆出去 umi.js 能降到 1.44MB (gzip)

before 1.75MB:
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   -        |
| 🇨🇳 Chinese |     -      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at ccc1727</samp>

The Previewer component in `.dumi/theme/builtins/Previewer` was refactored to support code splitting and lazy loading. This can reduce the bundle size and loading time of the documentation site.

### <samp>🤖 Generated by Copilot at ccc1727</samp>

* Split and lazily load the Previewer component to reduce bundle size and loading time ([link](https://github.com/ant-design/ant-design/pull/44310/files?diff=unified&w=0#diff-d4c2b096e898ee55c192cd1d13952ec5c5be4c1ff563d0ccaba74d8555e19adaL1-R10), [link](https://github.com/ant-design/ant-design/pull/44310/files?diff=unified&w=0#diff-b597cbad3ff89d0f9699d810a04aeb976676d58757183aacecce6aa5279566edR1-R21))

### CODE REVIEW

**Review by yoyo837 — APPROVED** [review]

**Comment by afc163** [comment]
这 1.44MB 里还有啥？还是大

**Comment by MadCcc** [comment]
image

**Comment by MadCcc** [comment]
其中 components 本身引用是按需的，但是 demo 都打进去了。
Meta 是 dumi 收集的，也需要拆 chunk。
cc @PeachScript

**Comment by MadCcc** [comment]
这个先合了

**Pull request merged**
