### PR TITLE
chore: remove version popover code

### PR DESCRIPTION
**Pull request by itwanggj**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Issue #31685

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix ci errors      |
| 🇨🇳 Chinese |    fix ci errors       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片

**Comment by afc163** [comment]
不需要重新开 PR，继续提交就可以了。

**Comment by itwanggj** [comment]
您好，确认下，我需要如何操作？

**Comment by afc163** [comment]
https://github.com/zeke/semantic-pull-requests#example-scenario

**Comment by itwanggj** [comment]
代码已提交到我自己分支的远端分支，辛苦看下。

**Comment by itwanggj** [comment]
您好，麻烦问下，现在还有什么问题吗？我现在修改下。

**Comment by yoyo837** [comment]
你稍等

**Comment by itwanggj** [comment]
好的，辛苦辛苦。

**Comment by yoyo837** [comment]
image
还是它

**Comment by itwanggj** [comment]
再确认下

**Pull request merged**
