### PR TITLE
Fix image ru_RU locale

### LINKED ISSUE #29145: Missing Russian localization for Image component
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-4wwd5?file=/index.js)

### Steps to reproduce
- Create an Image component
- Wrap it in a ConfigProvider and set a Russian locale 
- Hover over Image component

It is necessary to translate the "Preview" text into a similar one in Russian (as an example, "Превью")

### What is expected?
"Preview" should be localized to the Russian word

### What is actually happening?
The string is only translated into Chinese and English

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.8.6 |
| System | Windown 10 Pro 2004 |
| Browser | Google Chrome 88.0.4324.104 |

### PR DESCRIPTION
**Pull request by qramilq**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix #29145

### 💡 Background and solution
Added `Image` key with `preview` prop with `Превью` value

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |Added Image component's preview word translation|
| 🇨🇳 Chinese |添加了Image 組件的預覽詞翻譯|

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/drawer/index.en-US.md](https://github.com/qramilq/ant-design/blob/fix-image-locale-ru/components/drawer/index.en-US.md)
[View rendered components/drawer/index.zh-CN.md](https://github.com/qramilq/ant-design/blob/fix-image-locale-ru/components/drawer/index.zh-CN.md)

### CODE REVIEW

**Comment by yoyo837** [comment]
`master` is ok I think.

**Comment by yoyo837** [comment]
> @yoyo837 you mean I should change target branch from `feature` to `master`

Yep.

**Comment by qramilq** [comment]
> > @yoyo837 you mean I should change target branch from `feature` to `master`
> 
> Yep.

done

**Comment by yoyo837** [comment]
Rebase and `push -f`.

**Comment by yoyo837** [comment]
Mixed with other commits.

**Comment by mumiao** [comment]
> Mixed with other commits.
我顺手提了 ：https://github.com/ant-design/ant-design/pull/29271
这个可以关了

**Pull request closed without merging**
