### PR TITLE
fix config-provide prefixCls props for modal

### LINKED ISSUE #15260: Modal.info / success / confirm 无法继承 ConfigProvider 中prefixCls的属性
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/93m9pv2mlo)

### Steps to reproduce
--

### What is expected?
--

### What is actually happening?
--

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.4 |
| System | Mac |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by yoyo837**
close #15260

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

1. Describe the source of requirement, like related issue link.

2. Describe the problem and the scenario.

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from user side, and list all potential break changes or other risks.

1. English description

2. Chinese description (optional)

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
rebase 一下 master

**Comment by afc163** [comment]
为啥你们 rebase 都会成这样。。。

**Comment by yoyo837** [comment]
我也不知道，我是rebase的

**Comment by yoyo837** [comment]
我重开PR吧

**Comment by zy410419243** [comment]
试试 `rebase -i`，这还能救

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/4700#issuecomment-275305452

**Comment by yoyo837** [comment]
好像可以了

**Comment by zombieJ** [comment]
这样修没用的，ReactDOM.render 没有上下文的：
kapture 2019-03-08 at 15 19 57

**Comment by yoyo837** [comment]
`import { Provider } from 'react-redux';`

```jsx
ReactDOM.render(
  <Provider store={store}>
    <div className="datatable">{form}</div>
  </Provider>,
  formContainer
);
```

这里的`Provider`都可以哒。

**Comment by yoyo837** [comment]
没加`ConfigContext.Provider` .  :(

**Comment by yoyo837** [comment]
`getPrefixCls` 有默认实现呀，App 不使用`ConfigProvider`是App 自己的事儿吧，哥.

**Comment by yoyo837** [comment]
`ant-design` 依赖安装不了，全盲改，测都不能测试。/尴尬

https://github.com/ant-design/ant-design/issues/13307#issuecomment-470790491

**Pull request closed without merging**
