### PR TITLE
docs: add most design token meta info

### PR DESCRIPTION
**Pull request by arvinxx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

none

### 💡 Background and solution

使用 gpt-3.5-turbo 实现自动补全

httpschatbot arvinx appsystemRole=eNrdUt9LwlAUft9fcZ59yPd6CSqKiAi

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      add most alias token meta info     |
| 🇨🇳 Chinese |      补全 token 的类型提示和说明     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Comment by li-jia-nan** [comment]
有点东西🐮

**Review by MadCcc — APPROVED** [review]

**Comment by kiner-tang** [comment]
🐮🐸

**Comment by Yuiai01** [comment]
🐮🍺

**Comment by yoyo837** [comment]
🐮🍵

**Pull request merged**
