### PR TITLE
chore(Descriptions): 组件表格内容过长时显示

### LINKED ISSUE #19373: Descriptions组件 内容过长 右边内容不可见
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
内容过长或低分辨率，该组件无法展示全内容

### What does the proposed API look like?
增加横向滚动，提高适配性

### PR DESCRIPTION
**Pull request by xrkffgg**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close #19373

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese | 修复Descriptions组件表格内容过长时显示 |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
有改动 #17049 的内容 @chenshuai2144

**Comment by afc163** [comment]
自适应好还是固定分配宽度好， @chenshuai2144 来判断一下。

**Comment by chenshuai2144** [comment]
感觉还是不要预设的好，使用 table的原生逻辑即可，有需求可以可以包裹一个 Typography 来实现更好的体验

**Comment by yoyo837** [comment]
ref: #19584

**Comment by dengfuping** [comment]
- @xrkffgg Should reserve previous logic and not to preset the style of `word-break: break-word;`.

**Comment by PearpearS** [comment]
我这的需求就是label和value宽度一致，并且value过长时宽度也不会改变，但实际上Descriptions组件宽度是自适应的，看了题主的解决方案，非常感谢，解决了我的问题，本来都打算不用Descriptions组件了。。。

**Pull request closed without merging**
