### PR TITLE
chore: Remove deprecated prop

### PR DESCRIPTION
**Pull request by ztplz**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

- English Changelog:
- Chinese Changelog (optional):

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design/blob/d839135ad066151c9527bc90457f3a0147b8bd2a/CHANGELOG.zh-CN.md
2.x就已经移除了这个属性

**Comment by afc163** [comment]
We should add deprecated message.

**Comment by afc163** [comment]
图片

**Comment by ztplz** [comment]
https://github.com/react-component/table/blob/fe68e445e639f696495de3e569339c09e2d46254/src/Table.js#L88
`rc-table` 里有

**Comment by afc163** [comment]
codesandbox 里怎么没生效：https://codesandbox.io/s/xlzwy3080q

**Comment by ztplz** [comment]
image

**Comment by afc163** [comment]
这是个 breaking change，现在不着急移除。

**Comment by ztplz** [comment]
image
早就break change了 一个移了5个 我觉得当时可能遗漏了这个

**Comment by afc163** [comment]
没 break 的，一直都能用，只是不推荐，这个类型删了可能直接编译不过了。

**Pull request closed without merging**
