### PR TITLE
MenuItem: avoid rendering Tooltip unless necessary

### PR DESCRIPTION
**Pull request by whtsky**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

### CODE REVIEW

**Comment by yesmeck** [comment]
@whtsky What issue does this PR resolve? Could you add a test case?

**Comment by whtsky** [comment]
Right now `MenuItem` is always wrapped in `Tooltip`, which is only useful when user set `inlineCollapsed=true` and MenuItem's level is `1`.  Since `Tooltip` does not implement `shouldComponentUpdate`, this results in a lot of unnecessary React Node & updates. ( And a lot of complaining message when using [why-did-you-update](https://github.com/maicki/why-did-you-update) )
IMO we can have slight performance improvement ( and better DX w/ why-did-you-update ) by not wrapping `MenuItem` in `Tooltip` when possible.

Since it's not a bug fix nor new feature, I don't know how to write a precise test case. any ideas?

**Comment by yesmeck** [comment]
Thanks!

**Comment by yesmeck** [comment]
@whtsky I have to revert this change due to it breaks the menu transition animation. After adding this conditional rendering, React will create new DOM node when `inlineCollapsed` changges.

**Pull request merged**
