### PR TITLE
feat: desc support root level label & content style

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Descriptions support `labelStyle` & `contentStyle` directly.      |
| 🇨🇳 Chinese |    Descriptions 上可以统一设置 labelStyle 和 contentStyle。      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/descriptions/demo/style.md](https://github.com/ant-design/ant-design/blob/root-desc/components/descriptions/demo/style.md)
[View rendered components/descriptions/index.en-US.md](https://github.com/ant-design/ant-design/blob/root-desc/components/descriptions/index.en-US.md)
[View rendered components/descriptions/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/root-desc/components/descriptions/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
支持全局设置？

**Comment by zombieJ** [comment]
就是 Desc 上设置后，Item 不用设置。换个词儿？

**Comment by afc163** [comment]
Descriptions 上可以统一设置 labelStyle 和 contentStyle

**Comment by afc163** [comment]
labelWidth 需要么？

**Comment by zombieJ** [comment]
> labelWidth 需要么？

`labelStyle` 里可以写 width，应该不用额外添加了。

**Comment by afc163** [comment]
云凤蝶那边用 labelStyle 方便不。

**Comment by zombieJ** [comment]
> 云凤蝶那边用 labelStyle 方便不。

这个是基于之前云凤蝶需要的 `Item.labelStyle` 的拓展，之前表示让用户一个个设置太蛋疼。我 double confirm 一下。

**Review by xrkffgg — APPROVED** [review]

**Pull request merged**
