### PR TITLE
fix: long submenu title display

### LINKED ISSUE #22609: Long Submenu Title Being Overlayed By Arrow Icon
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/johnzhou/pen/NWqENOY](https://codepen.io/johnzhou/pen/NWqENOY)

### Steps to reproduce
Create a SubMenu with a long title.

### What is expected?
The SubMenu title and arrow icon should be clearly separated.

### What is actually happening?
The submenu arrow icon is being overlayed over the title.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | Microsoft Windows 10 Pro Version	10.0.17763 Build 17763 |
| Browser | Chrome 80.0.3987.132 |

---
I know that this can fixed in multiple ways, either adding a fixed width to the SubMenu component or removing the width property from the icon but I would prefer a fix in ant.design because I don't think having a long title is out of the ordinary.

### PR DESCRIPTION
**Pull request by wwyx778**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close #22609

### 💡 Background and solution
Long Submenu Title Being Overlayed By Arrow Icon
Add style : padding-right

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix long Submenu title being overlayed by arrow icon      |
| 🇨🇳 Chinese |  修复SubMenu标题过长而导致被箭头图标部分覆盖的问题         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by xrkffgg — CHANGES_REQUESTED** [review]
RTL 的 也帮忙加一下吧

**Comment by xrkffgg** [comment]
changelog 写一下， self check 勾一下~

**Comment by wwyx778** [comment]
> changelog 写一下， self check 勾一下~

done. 这个CI总是其他的组件跑不通过是为啥？

**Comment by xrkffgg** [comment]
rebase 下 master ，   push 的时候 记得加 --force 就行

不过也没事

**Review by xrkffgg — APPROVED** [review]

**Pull request merged**
