### PR TITLE
feat: Introduce storybook

### PR DESCRIPTION
**Pull request by fa93hws**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
To run storybook: `npm run storybook:start`.

Storybook has done a great job on ui library displaying. It allows the consumer to see the result of the component with different set of properties directly.
Take `Button` component as an example, I can preview a native button with `ghost` and `round` directly.
image

Some other benefits are:
- It can be easily combined with visual regression test tools such as Percy (https://percy.io/)
- Page url to storybook build can be integrated to CI, so that PR reviewers can click the link and play with the UI without running the whole stack locally.
- I believe it would be a better experience for library consumers to play with the storybook instead of reading the documentation sometimes.
- I believe it would be a better experience for developer as well.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by fa93hws** [comment]
Would you mind take a look on this? @afc163

**Comment by yoyo837** [comment]
#24003 has been merged, what more can we add in this PR?

**Comment by afc163** [comment]
Although it did have same amazing features, we have no plan to introduce another demo development workflow, just duplicated with our demo system.

**Comment by afc163** [comment]
@fa93hws Thx anyway, good job!

**Comment by romu70** [comment]
@afc163 : where can I find the "official" Ant demo development tool? Thx.

**Pull request closed without merging**
