### PR TITLE
chore: Adjust picker logic

### LINKED ISSUE #25120: rangepicker 建议参考 airbnb datepicker 交互
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
升级了 ant4 后，rangepicker 在已选时间的情况下，每次选择会关闭筛选框

### What does the proposed API look like?
可参考： http://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default
期望点两次才会关闭

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #25120

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Adjust RangePicker logic that any picker selection will popup another picker panel.       |
| 🇨🇳 Chinese |    调整 RangePicker 逻辑当任意面板选择完毕后，另一个面板会自动弹出。      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
- [ ] MonthPicker 和 YearPick 的选择逻辑也要相应修改一下。

**Comment by zombieJ** [comment]
> MonthPicker 和 YearPick 的选择逻辑也要相应修改一下。

RangePicker 内部是同一套逻辑，都会按照新的来~

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
changelog 要改改了

**Comment by zombieJ** [comment]
done

**Pull request merged**
