### PR TITLE
type: export QRPropsSvg type

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | type: export QRPropsSvg type Ref-#42570 |
| 🇨🇳 Chinese | 导出类型，补充#42570，无需纳入 ChangeLog |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at d58f538</samp>

This pull request adds a new feature to support rendering QR codes as SVG elements, and improves the code style and readability of the `qrcode` component and its related modules. It introduces a new type `QRPropsSvg` and a new component `QRCodeSVG`, and refactors some existing code.

### <samp>🤖 Generated by Copilot at d58f538</samp>

*  Export new type `QRPropsSvg` for SVG QR code props ([link](https://github.com/ant-design/ant-design/pull/42605/files?diff=unified&w=0#diff-075e1c19c8285cbf6d738c6bc0388fbc6feca473adc7ffd97b5ac5d70598e267L97-R97))
*  Simplify ternary expression for rendering QR code components ([link](https://github.com/ant-design/ant-design/pull/42605/files?diff=unified&w=0#diff-99175e9424e53dc9d08dd9c77c57c2ac26a0aff2f9b4eb0f6cf34d1709ab5662L96-R96))
*  Add semicolons to object declarations in `components/qrcode/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/42605/files?diff=unified&w=0#diff-99175e9424e53dc9d08dd9c77c57c2ac26a0aff2f9b4eb0f6cf34d1709ab5662L48-R48), [link](https://github.com/ant-design/ant-design/pull/42605/files?diff=unified&w=0#diff-99175e9424e53dc9d08dd9c77c57c2ac26a0aff2f9b4eb0f6cf34d1709ab5662L56-R57))
*  Add blank lines between type declarations in `components/qrcode/interface.ts` ([link](https://github.com/ant-design/ant-design/pull/42605/files?diff=unified&w=0#diff-51a08ab3cfcd9c949cdb0008a7999563efd617f54458e798d427f5fd373c32ddL24-R26))
*  Reorder import statements in `components/qrcode/style/index.ts` ([link](https://github.com/ant-design/ant-design/pull/42605/files?diff=unified&w=0#diff-c28bb5ec7db2367f9a8fc9a679a69ea65773bf6fe6ec03b78cadc5bee44864dfL1-R3))

### CODE REVIEW

**Comment by sy296565890** [comment]
@li-jia-nan 大佬 git fetch --all 之后没看见分支【type-export】这个是需要重新fork一下吗

**Comment by li-jia-nan** [comment]
> @li-jia-nan 大佬 git fetch --all 之后没看见分支【type-export】这个是需要重新fork一下吗

嗯？你要拉这个分支干嘛？我已经改好了

**Comment by sy296565890** [comment]
> > @li-jia-nan 大佬 git fetch --all 之后没看见分支【type-export】这个是需要重新fork一下吗
> 
> 嗯？你要拉这个分支干嘛？我已经改好了

误会了，上午跟大佬 @zombieJ 聊到了【ref.current.saveAs({ type: 'png' });】 ，误以为单独开pr我来继续~~  哈哈

**Comment by li-jia-nan** [comment]
> 误会了，上午跟大佬 @zombieJ 聊到了【ref.current.saveAs({ type: 'png' });】 ，误以为单独开pr我来继续~~ 哈哈

这里只是导出类型

**Review by afc163 — APPROVED** [review]

**Pull request merged**
