### PR TITLE
chore: Replace `rc-animation/lib/CSSMotion` to `rc-motion`

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### CODE REVIEW

**Comment by zombieJ** [comment]
还有几个组件用的还是 Animate。 collaborator 们看看有没有空哈~~

**Comment by zombieJ** [comment]
删了点 TS definition code cov 降了 = =

**Comment by Kermit-Xuan** [comment]
剩下的我来换

**Comment by afc163** [comment]
好像大了 5kb。

**Comment by Kermit-Xuan** [comment]
这个里面好像小了3kb。
https://github.com/ant-design/ant-design/pull/26049

**Pull request merged**
