### PR TITLE
fix: text ellipsis

### PR DESCRIPTION
**Pull request by Lpmvb**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/19219

### 💡 Background and solution

在不同浏览器上 line-height * row 和 height 并不一定相等，如果不相等则取单行文字 height 作为 line-height

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
看看测试用例。

**Comment by afc163** [comment]
rebase 一下最新的 master。

**Comment by zombieJ** [comment]
加个测试用例?

**Comment by afc163** [comment]
测试覆盖率的 ci 丢了。

**Review by zjn9011 — CHANGES_REQUESTED** [review]
函数

**Comment by Lpmvb** [comment]
> 函数

？啥意思

**Comment by afc163** [comment]
rebase 一下最新的 master。

**Comment by afc163** [comment]
测试覆盖率掉了。

**Comment by afc163** [comment]
ping @Lpmvb

**Comment by afc163** [comment]
closing for no response, feel free to recreate another PR.

**Comment by afc163** [comment]
看上去 https://github.com/ant-design/ant-design/pull/30777 是更简单的解决方案。

**Pull request closed without merging**
