### PR TITLE
 Autocomplete async bug

### PR DESCRIPTION
**Pull request by RaoHai**
+ ref https://github.com/react-component/select/pull/177
 + getInputDOMNode cannot get correct input element, so `document.activeElement
 === this.getInputDOMNode())` will always false.
 + add scheme of `getInputElement`: if getInputElement returns an `React.Element`, the element must implemented `refs.input` to point to its real input element.

### CODE REVIEW

**Comment by benjycui** [comment]
> add scheme of getInputElement: if getInputElement returns an React.Element, the element must implemented refs.input to point to its real input element.

所以这里是引入了一个规则么。。以后开发者自定义输入元素都必须遵循这个规则？

**Comment by RaoHai** [comment]
@benjycui 这里有讨论 https://github.com/react-component/select/pull/177

**Comment by msathis** [comment]
Any known work-around for this? I tried rendering twice with same `dataSource`. But that doesnt seem to work. :(

**Comment by JesperWe** [comment]
@msathis I described a workaround about mid-page on https://github.com/ant-design/ant-design/issues/5601

**Comment by RaoHai** [comment]
https://github.com/react-component/select/pull/177 is merged, so this PR can close directly. The bug #5601 will be fixed after new version of rc-select published.

**Comment by yesmeck** [comment]
A new version of rc-select has released, try reinstall node_modules.

**Pull request closed without merging**
