### PR TITLE
support `autoAdjustOverflow` prop, in another way.

### PR DESCRIPTION
**Pull request by jdz321**
the same to #6652 but no change in `rc-tooltip`

### CODE REVIEW

**Comment by jdz321** [comment]
related discuss :  https://github.com/react-component/tooltip/pull/88#issuecomment-311852520

**Comment by afc163** [comment]
1. CI breaks.
2. we should update documentation for `Popover`, `Popconfirm` too.

**Comment by jdz321** [comment]
1.  CI 报错是其他地方的问题, 不在这次commit修
2. `Popover` & `Popconfirm` 已经提示了 `更多属性请参考 Tooltip` , 没必要再单列这个prop

**Comment by afc163** [comment]
👍

**Comment by benjycui** [comment]
Rebase 一下

**Comment by jdz321** [comment]
@benjycui   done.

**Comment by afc163** [comment]
close #6625

**Pull request merged**
