### PR TITLE
fix: update getContainer to props before

### PR DESCRIPTION
**Pull request by jljsj33**
### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |    更新 modal 的 confirm 不能使用 getContainer 的问题      |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
有关联 issue 么？

**Comment by zombieJ** [comment]
来自直接的反馈……

**Comment by jljsj33** [comment]
邵帅的反馈。。。他们在用 confirm 时要跨 iframe 的弹出。。。

**Comment by jljsj33** [comment]
getContainer 放前面也是对的，，可配置。。。

**Pull request merged**
