### PR TITLE
refactor(timeline): rewrite with hook

### PR DESCRIPTION
**Pull request by hengkx**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  refactor with hook         |
| 🇨🇳 Chinese |  用 react hook 重构         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by hengkx** [comment]
https://codecov.io/gh/ant-design/ant-design/pull/23631/diff?src=pr&el=tree#D1-22

这一行我加了color 为什么还覆盖不到...

**Comment by hengkx** [comment]
color 有defaultProps

**Comment by hengkx** [comment]
@afc163 请教个问题
https://github.com/ant-design/ant-design/blob/5183592ece7498145803f3c96283aed6be168b07/components/slider/__tests__/index.test.js#L43-L48

`Tooltip` 改为func的话，没有`instance`方法了，设置属性好像也不能给子组件设置，有什么好的方法吗？单独测试`SliderTooltip`?

**Comment by afc163** [comment]
用具体交互来测试吧，交互不行可以删用例。

**Pull request merged**
