### PR TITLE
feat(date-picker): improve hovering experience

### PR DESCRIPTION
**Pull request by kerm1it**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close [#25050](https://github.com/ant-design/ant-design/issues/25050)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | improve DatePicker hovering experience, the placeholder will change to format value of target-date when hovering a date cell. (#25050) |
| 🇨🇳 Chinese | 提升日期组件悬停体验，当悬停在某个日期上时占位符将变为对应的日期格式化后的值。(#25050) |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
Jul-23-2020 20-57-06

**Comment by zombieJ** [comment]
Changelog 里需要写的更详细些，比如悬停时间时输入框会同步展示对应时间之类的。

**Review by zombieJ — APPROVED** [review]

**Comment by Kermit-Xuan** [comment]
> Changelog 里需要写的更详细些，比如悬停时间时输入框会同步展示对应时间之类的。

看看现在呢？

**Comment by afc163** [comment]
image

这种已选的情况能支持么，hover 修改为 placeholder 样式，离开恢复。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/25050 里的下面两个图。

**Comment by Kermit-Xuan** [comment]
你意思是已经选择了值后，这时候再悬停的时候还想要变成目标日期，然后离开后恢复为原值？

**Comment by afc163** [comment]
对

**Comment by Kermit-Xuan** [comment]
有道理，这种体验确实更好，晚上我再改改。

**Pull request merged**
