### PR TITLE
修复 issues 11042 提出的 table 组件嵌套表格配置单选标题的问题并添加相关的文档

### PR DESCRIPTION
**Pull request by littleLane**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by yesmeck** [comment]
可以设置下 git author 吗，这样 github 能把 commit 跟人关联起来。

**Comment by yesmeck** [comment]
- [ ] git author
- [ ] 添加测试
- [ ] 英文文档

**Comment by littleLane** [comment]
关于 table 组件可以添加新的 demo 吗？

**Comment by yesmeck** [comment]
这个简单的属性，感觉没必要单独 demo 说明吧。

**Comment by yesmeck** [comment]
@littleLane 可以加个测试吗？

**Comment by littleLane** [comment]
不好意思，忙忘了，测试已经加上了！！

**Comment by yesmeck** [comment]
需要 PR 到 feature-3.8.0

**Pull request closed without merging**
