### PR TITLE
feat(Drawer): support extra for Drawer

### PR DESCRIPTION
**Pull request by Yangzhedi**
## 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

for [#15669](https://github.com/ant-design/ant-design/issues/15669)

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description

2. Chinese description (optional)

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by Yangzhedi** [comment]
```
 console.error dist/antd.js:127633
      Warning: [antd: Table] `expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.

  ● renders ./components/table/demo/drag-sorting.md correctly

    TypeError: React.memo is not a function

      10 | 使用自定义元素，我们可以集成 react-dnd 来实现拖拽排序。
      11 | 
    > 12 | ## en-US
         |                 ^
      13 | 
      14 | By using custom components, we can integrate table with react-dnd to implement drag sorting.
      15 | 

      at Object.<anonymous> (node_modules/react-dnd/lib/cjs/DragPreviewImage.js:7:30)
      at Object.<anonymous> (node_modules/react-dnd/lib/cjs/index.js:13:26)
      at Object.<anonymous> (components/table/demo/drag-sorting.md:12:17)
      at Object.require (tests/shared/demoTest.js:52:20)
```
table的tests挂了？

**Comment by zombieJ** [comment]
唔，不知道是不是有哪个依赖用了 memo……

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/a462c2ddf4c9b40b840900735983a111ebfdfd48

rebase

**Comment by afc163** [comment]
多了一个 commit

**Comment by Yangzhedi** [comment]
😥rebase不太会操作 用的cherry-pick 
但是也是改了一行代码- - 为什么 Button 的test会挂
尴尬...

**Comment by zy410419243** [comment]
你这个情况

``` bash
git checkout master
git pull --rebase upstream master
git checkout feat-drawer-extra
git rebase master
git push origin feat-drawer-extra -f
```
完事

**Comment by afc163** [comment]
多了很多 commits

**Comment by afc163** [comment]
建议重提 PR

**Comment by Yangzhedi** [comment]
@afc163 好的

**Pull request closed without merging**
