### PR TITLE
refactor: 🆙 upgrade rc-progress

### LINKED ISSUE #24116: 使用script标签全局引入antd报错
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://kk4e3.csb.app/](https://kk4e3.csb.app/)

### Steps to reproduce
查看控制台即可

### What is expected?
正常写入window对象

### What is actually happening?
未写入window对象

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.8  |
| System | win |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #24116

### 💡 Background and solution

Refactor rc-progress: https://github.com/react-component/progress/commit/9e6160fe7817f852236d082b886b12ed35e16115

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Refactor rc-progress to resolve `h3g is not defined` error in `<script src"antd.min.js" />`. |
| 🇨🇳 Chinese | 重构 rc-progress 以解决 `<script src"antd.min.js" />` 会抛出 `h3g is not defined` 的问题。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
为啥你的CI 不报错

**Comment by afc163** [comment]
你本地 node_modules 是旧的。

**Comment by yoyo837** [comment]
我确定我每次都删过，本地能通

**Comment by yoyo837** [comment]
我换cnpm试试

**Comment by afc163** [comment]
bundle size 降低了近 1 kB。

**Comment by afc163** [comment]
package-lock.json 或者 yarn.lock

**Comment by yoyo837** [comment]
失算了。😳

**Pull request merged**
