### PR TITLE
[WIP]refactor(locale-provider): rewrite with hook

### PR DESCRIPTION
**Pull request by hengkx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by hengkx** [comment]
https://github.com/ant-design/ant-design/blob/9d4d6f5402d9bc99699d720e50867d853611bbfe/components/typography/Base.tsx#L472-L478

`config`里面有locale 为什么要充这里面取

**Comment by afc163** [comment]
ci 挂了不少。

**Comment by afc163** [comment]
ci broken

**Comment by hengkx** [comment]
最近 有点事 看看 改改 能用不 不能用 关掉把

**Pull request closed without merging**
