### PR TITLE
chore: try to fix puppeteer screenshot

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
Puppeteer 默认给 body 改了高度，这里强制改回 auto 试试，还不行就换 cypress 的 e2e 测试

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 803891b</samp>

Fix iframe height in `tests/index.html` to display test results better. This is part of a pull request to enhance testing for ant-design.

### <samp>🤖 Generated by Copilot at 803891b</samp>

* Fix the height of the test report iframe with a CSS rule ([link](https://github.com/ant-design/ant-design/pull/44760/files?diff=unified&w=0#diff-90b511c392b35b916f8651ba3b27fea4341761dd54aedaec91c52a757e545667R10))

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
图片

这个 diff，看上去很对。

**Comment by yoyo837** [comment]
试试改点其他布局?

**Comment by MadCcc** [comment]
> 图片
> 这个 diff，看上去很对。

是的，预期变化

**Comment by MadCcc** [comment]
> 试试改点其他布局?

指什么？

**Comment by MadCcc** [comment]
先合了试试

**Pull request merged**
