### PR TITLE
feat: Add ref to Collapse and Panel component

### PR DESCRIPTION
**Pull request by linhf123**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
#39628

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |       Add ref to Collapse and Panel componen    |
| 🇨🇳 Chinese |      为 Collapse 和 Panel 添加 ref     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
- [ ] CI broken, please check it.
- [ ] Could you add some test case about ref?

**Comment by any1024** [comment]
> * [ ]  CI broken, please check it.
> * [ ]  Could you add some test case about ref?

好的，我后面改一下

**Comment by Sagie501** [comment]
Should the `rc-collapse` library add support to the ref too?

**Comment by any1024** [comment]
> Should the `rc-collapse` library add support to the ref as well?
Do you want to get the DOM of the `rc-colorlapse`?

**Comment by any1024** [comment]
> Should the `rc-collapse` library add support to the ref as well?

Do you want to get the DOM of the `rc-colorlapse`?

**Comment by Sagie501** [comment]
> > Should the `rc-collapse` library add support to the ref as well?
> 
> Do you want to get the DOM of the `rc-colorlapse`?

You are passing ref to the `RcCollpase` and `RcCollapse.Panel` components, so shouldn't it be added to the library as well?

**Comment by any1024** [comment]
> > > Should the `rc-collapse` library add support to the ref as well?
> > 
> > 
> > Do you want to get the DOM of the `rc-colorlapse`?
> 
> You are passing ref to the `RcCollpase` and `RcCollapse.Panel` components, so shouldn't it be added to the library as well?
The`ref` is now obtained as follows, is this what you expect?

image

**Comment by Sagie501** [comment]
@any1024 Actually I need to get a ref to the root element of the component. 
`ant-collapse` is the Collapse
`ant-collapse-item` is the Panel
image

**Comment by any1024** [comment]
> 

ok，I'm going to transform rc-colorlapse first

**Comment by any1024** [comment]
@Sagie501 Wait for [react-component/collapse#287](https://github.com/react-component/collapse/pull/287) merge

**Comment by any1024** [comment]
Ref content

image

image

**Comment by any1024** [comment]
@afc163 有空可以帮忙 cr 一下

**Review by Wxh16144 — APPROVED** [review]

**Comment by afc163** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
