### PR TITLE
chore: Edited Belarusian locale

### PR DESCRIPTION
**Pull request by bielarusajed**
### 🤔 This is a ...

- [x] Internationalization

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Updated locale and fixed some mistakes |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
Please update snapshot.

**Comment by belarusaed** [comment]
So?

**Comment by yoyo837** [comment]
Please:
1. Remove `node_modules` and lock file(`package-lock.json` or `yarn.lock`).
2. Reinstall.
3. Run `npm run test -- -u`
4. Push all files changed.

**Comment by belarusaed** [comment]
IDK why, but it exits shell and, I think, running not all tests.
It generated `components/locale-provider/__tests__/__snapshots__/index.test.js.snap` and I'm not sure that there are no more files that should be generated.

**Comment by yoyo837** [comment]
Anyway, please try to fix the CI failure of the test case at first.

**Pull request closed without merging**
