### PR TITLE
fix: site overflow cause sticky invalid

### LINKED ISSUE #28737: Table的sticky在官方文demo中不生效
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-sticky](https://ant.design/components/table-cn/#components-table-demo-sticky)

### Steps to reproduce
官方的demo中无效https://ant.design/components/table-cn/#components-table-demo-sticky
sandbox中的链接是正常的：https://codesandbox.io/s/puhej?file=/index.js:1410-1416

### What is expected?
官方的demo跟codesandbox中效果一致

### What is actually happening?
官方的demo中无效

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | ^17.0.1 |
| System | windows 10 |
| Browser |  80.0.3987.132（正式版本） （64 位） |

---
可能是dumi的bug

### PR DESCRIPTION
**Pull request by shaodahong**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 🔗 Related issue link
Fixes https://github.com/ant-design/ant-design/issues/28737

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by shaodahong** [comment]
@afc163 https://preview-28741-ant-design.surge.sh/components/table-cn/#components-table-demo-drag-sorting-handler

去掉了感觉没啥影响

**Comment by afc163** [comment]
主要屏幕小时候经常出现横向滚动条挺烦的。

**Comment by shaodahong** [comment]
> 主要屏幕小时候经常出现横向滚动条挺烦的。

嗯，就个别拉小点会出超出

https://preview-28741-ant-design.surge.sh/components/table-cn/#components-table-demo-nested-table

**Comment by afc163** [comment]
可以看看 https://github.com/ant-design/ant-design/issues/27623 还有没有别的解法。

**Comment by shaodahong** [comment]
这个 BUG 怎么操作的，没实验出来

https://user-images.githubusercontent.com/14831261/103856837-4a120480-50f0-11eb-80d6-a55f160df11f.mp4

**Comment by afc163** [comment]
body 上要加上 `overflow-x: hidden;`。

**Comment by shaodahong** [comment]
Done.

**Pull request merged**
