### PR TITLE
feat(Drawer): support extra for Drawer

### PR DESCRIPTION
**Pull request by Yangzhedi**
## 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

for [#15669](https://github.com/ant-design/ant-design/issues/15669)

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description

2. Chinese description (optional)

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/drawer/index.en-US.md](https://github.com/Yangzhedi/ant-design/blob/feature-drawer/components/drawer/index.en-US.md)
[View rendered components/drawer/index.zh-CN.md](https://github.com/Yangzhedi/ant-design/blob/feature-drawer/components/drawer/index.zh-CN.md)

### CODE REVIEW

**Comment by Yangzhedi** [comment]
Modal的Snapshot坏了

**Comment by afc163** [comment]
rebase 一下 feature 分支。

**Comment by afc163** [comment]
ping @Yangzhedi

**Comment by afc163** [comment]
close for no response

**Pull request closed without merging**
