### PR TITLE
feat: Hide Calendar mode switch in header

### PR DESCRIPTION
**Pull request by bombillazo**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

1. Add a new prop to the Calendar component to hide the mode switch on the calendar header.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Add a new prop to the Calendar component to hide the mode switch on the calendar header. |
| 🇨🇳 Chinese |      向 Calendar 组件添加一个新的 prop 以隐藏日历标题上的模式开关。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at b9fbcea</samp>

This pull request adds two new props to the `Calendar` component: `selectable` and `hideModeSwitch`. The `selectable` prop allows customizing the selection behavior of the calendar, and the `hideModeSwitch` prop allows hiding the mode switch button. The pull request also updates the `generateCalendar` function, the `CalendarHeader` component, the test cases, and the documentation to support these new props.

### <samp>🤖 Generated by Copilot at b9fbcea</samp>

*  Add `selectable` prop to `Calendar` component to control which types of selection can trigger the `onSelect` callback ([link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2R77-R78), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2R120-R121), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2L331-R338), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2L341-R349))
*  Add `hideModeSwitch` prop to `Calendar` component to control the visibility of the mode switch button in the header ([link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2R77-R78), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2R120-R121),   [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-8fab8ed47a3daf0635a3eb887b1fd4fdb984ec4daba5af51505fea4a5d87051bR59), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-58e290dfe67aeb90a9d97d4e3e8a790c9aa964113593229b7f2637b66f0c8a50R64))
*  Modify `onChange` prop of `CalendarHeader` component to accept `selectType` parameter of type `CalendarSelectable` to indicate which type of selection was made by the user ([link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-fbade99cf5fe70d3001d5570bf707ff05eaa054eb251848d924e7f65e789b807L21-R21), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-fbade99cf5fe70d3001d5570bf707ff05eaa054eb251848d924e7f65e789b807L71-R71), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-fbade99cf5fe70d3001d5570bf707ff05eaa054eb251848d924e7f65e789b807L113-R113), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2L39-R43))
*  Rename `onChange` prop of `CalendarHeader` component to `triggerChange` and wrap it with a check for `selectable` prop in `generateCalendar` function ([link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2R120-R121), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2L331-R338), [link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2L341-R349))
*  Set `picker` prop of `DatePanel` component to match `panelMode` prop in `generateCalendar` function ([link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2L341-R349))
*  Add test cases for `selectable` prop in `components/calendar/__tests__/index.test.tsx` file ([link](https://github.com/ant-design/ant-design/pull/42456/files?diff=unified&w=0#diff-0a5821c1b32fdf9bf1d3bb55702937aead9206b6762df0497ff7b030f405a21aR89-R348))

### CODE REVIEW

**Comment by zombieJ** [comment]
Seems this can be done by hide with style of `ant-picker-calendar-mode-switch`

**Comment by bombillazo** [comment]
> Seems this can be done by hide with style of `ant-picker-calendar-mode-switch`

Hey, that would hide the mode switches for all Calendars. And I'm not a fan of modifying component behavior via CSS classes, especially if one wants to do it programmatically/dynamically.

**Comment by li-jia-nan** [comment]
```tsx
export default () => {
  return <Calendar className="my-xxxx" />;
};
```

```css
.my-xxxx .ant-picker-calendar-mode-switch {
  display: none;
}
```

**Comment by bombillazo** [comment]
> ```tsx
> export default () => {
>   return <Calendar className="my-xxxx" />;
> };
> ```
> 
> ```css
> .my-xxxx .ant-picker-calendar-mode-switch {
>   display: none;
> }
> ```

I guess if that is the Ant-Design approach to this, I'll make it work.

**Comment by li-jia-nan** [comment]
> I guess if that is the Ant-Design approach to this, I'll make it work.

Yes, this is what I recommend and I use in my own work.

**Comment by zombieJ** [comment]
Yes. You can do this. We've try to avoid API work to close with interactive UI design. New API need careful consideration since it can not remove easily which may be a breaking change.

**Comment by bombillazo** [comment]
Ok, thanks for clearing it up, I will close this feature PR!

**Pull request closed without merging**
