### PR TITLE
feat: Add skeleton button 

### PR DESCRIPTION
**Pull request by 0xPoe**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#18237 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |Add skeleton button|
| 🇨🇳 Chinese |新增骨架按钮|

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/skeleton/demo/button.md](https://github.com/Rustin-Liu/ant-design/blob/rustin-button-skeleton/components/skeleton/demo/button.md)
[View rendered components/skeleton/index.en-US.md](https://github.com/Rustin-Liu/ant-design/blob/rustin-button-skeleton/components/skeleton/index.en-US.md)
[View rendered components/skeleton/index.zh-CN.md](https://github.com/Rustin-Liu/ant-design/blob/rustin-button-skeleton/components/skeleton/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
Should we add this into 4.0? @zombieJ

**Comment by Rustin-Liu** [comment]
ping~

**Comment by zombieJ** [comment]
Yes. Move into `4.0-prepare` branch please.

**Comment by shaodahong** [comment]
Closed via #19699

**Pull request closed without merging**
