### PR TITLE
update card grid prop type to extend div

### LINKED ISSUE #33264: CardGridProps should expose Div Properties like onClick
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-7unx7?file=/index.js)

### Steps to reproduce
Type Definition is missing basic things like onClick - they still work

### What is expected?
Type Definition to include basic things like onClick

### What is actually happening?
Type Definition is missing basic things like onClick

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17 |
| System | any |
| Browser | any |

### PR DESCRIPTION
**Pull request by wodka**
fixes #33264

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Card grid cannot use div properties even though they do work

### 💡 Background and solution

card grid props should extend div props similar to card props

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  add div props to card grid  |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Fxied in https://github.com/ant-design/ant-design/pull/33563

**Comment by wodka** [comment]
@afc163 yes, out of curiosity - why would you ask for PR's if it is then committed by some existing contributor (@LongHaoo)?

**Comment by afc163** [comment]
@wodka Check the timeline https://github.com/ant-design/ant-design/issues/33264

**Comment by LongHaoo** [comment]
@wodka https://github.com/ant-design/ant-design/issues/33264

**Comment by LongHaoo** [comment]
@wodka I seen you haven't modified pr for a long time.
I thought you might be busy so I solved it.  Your last pr was on December 12.

**Comment by wodka** [comment]
> Check the timeline #33264

exactly - I provided a PR with the fix one day after opening the issue.

> I seen you haven't modified pr for a long time.

when you mention not modifying it - what should be updated after providing the fix?


it's not really a problem - just discourages adding PR's in the future

**Pull request closed without merging**
