### PR TITLE
Modified the 'this month' button in RangePicker

### PR DESCRIPTION
**Pull request by fikyair**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your pull request, thank you!

* [x] Make sure that you propose pull request to right branch: bugfix for `master`, feature for branch `feature`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a pull request to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you pull request.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

Comments:  I modified the logic for the 'this month' button in RangePicker: from the first day of the month to today. My reason is that for 'this month' people are concerned with the information in the current month, not from the day to the end of the month.
This is my first PR. If there is something wrong, please advise.

### CODE REVIEW

**Comment by fikyair** [comment]
I modified the logic for the 'this month' button in RangePicker: from the first day of the month to today. My reason is that for 'this month' people are concerned with the information in the current month, not from the day to the end of the month.
This is my first PR. If there is something wrong, please advise.

**Comment by afc163** [comment]
close #13327

**Comment by ycjcl868** [comment]
there're some resolve conflicts,

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13327#issuecomment-442735657

**Pull request closed without merging**
