### PR TITLE
refactor(Button): base style use flex

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 🔗 Related issue link
Fixes https://github.com/ant-design/ant-design/issues/20210

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by shaodahong** [comment]
## Old
image

## New
image

**Comment by zombieJ** [comment]
`vertical-align` must be `baseline` or it will breaks align with other components.

#20210 should adjust line-height from `21px` to `22px` instead.

**Comment by shaodahong** [comment]
Use `line-height` not a good idea, and in the doc, `vertical-align` use `middle` better than `baseline `

**Comment by zombieJ** [comment]
Should test with DatePicker Select Cascader Input to check whether `inline-flex` will affect align position.

**Comment by shaodahong** [comment]
looks okay, but `Picker` height is low than other components 

image

**Comment by shaodahong** [comment]
这个 line-height 的容错太低了，导致其他组件的高度也变了，我建议是放弃 line-height, 然后使用 flex 自检其他组件

把 input 的三个大小再向上抽一层

```less
@input-height-base: 32px;
@input-height-lg: 40px;
@input-height-sm: 24px;
```
->

```less
@component-height-base: 32px;
@component-height-lg: 40px;
@component-height-sm: 24px;
```

然后统一 `flex` 或者 `inline-flex`

**Comment by zombieJ** [comment]
在 Form 里更新一下这个 demo：
https://github.com/ant-design/ant-design/blob/4.0-prepare/components/auto-complete/demo/form-debug.md

把 Input 下的合到一个 demo 里： https://github.com/ant-design/ant-design/blob/master/components/input/demo/align.md 

然后比一下，Button 没问题就先合掉。然后其他对不齐的一个个改过来。

**Review by zombieJ — APPROVED** [review]

**Review by MrHeer — APPROVED** [review]

**Pull request merged**
