### PR TITLE
Master3

### PR DESCRIPTION
**Pull request by UsamaMahboob**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/33289

### 💡 Background and solution

The table renders the title area even if the control function returns null for the title
So you check if null is being returned if it is then you do not send it t the RC component

### 📝 Changelog

None 

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     x      |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x ] Doc is updated/provided or not needed
- [x ] Demo is updated/provided or not needed
- [x ] TypeScript definition is updated/provided or not needed
- [ x] Changelog is provided or not needed

### CODE REVIEW

**Comment by UsamaMahboob** [comment]
Hi,
I am a bit curious on how to check if the title function is returning null, can someone provide some guidance?

**Comment by afc163** [comment]
1. Rebase  master
2. Please add a test case

**Comment by afc163** [comment]
图片

**Comment by afc163** [comment]
ping @UsamaMahboob

**Comment by afc163** [comment]
closing for no response.

**Pull request closed without merging**
