### PR TITLE
fix: fix Input component combination using misplaced style problem

### LINKED ISSUE #39619: Input 组件组合使用错位
### Reproduction link

[https://ant.design/components/input-cn](https://ant.design/components/input-cn)

### Steps to reproduce

在Windows 10 系统，2K显示器，使用系统推荐缩放 125% 下 ，浏览器缩放 100%，导致 Input 组件组合使用错位，系统缩放 100% 正常，但是字太小
微信截图_20221217212913
微信截图_20221217213004

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | React 18.2.0 |
| System | Windows |
| Browser | Chrome 103 |

### PR DESCRIPTION
**Pull request by heiyu4585**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
fix https://github.com/ant-design/ant-design/issues/39619

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Input.Group misplace style when zoom up page in windows   |
| 🇨🇳 Chinese |    修复 Input.Group 在 windows 下缩放屏幕时的错位问题。    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
这是 4.x 的解法么？

**Comment by heiyu4585** [comment]
> 这是 4.x 的解法么？

不清楚跟4.x的关系

**Comment by heiyu4585** [comment]
1672195227884_65A11A73-EBA5-4138-BEAF-D9C6DBA6E9B3

这个可以 approve 么

**Comment by heiyu4585** [comment]
> approve

approved

**Comment by afc163** [comment]
Changelog 写完整，具体修复了什么问题。

**Comment by heiyu4585** [comment]
> Changelog 写完整，具体修复了什么问题。

done

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
@heiyu4585 https://github.com/ant-design/ant-design/issues/39619 这个 issue 里好像是 Input.Group 的问题，我看这里改的是 addon 的，是否修的是同一个问题。

**Comment by hihuangwei** [comment]
这问题依然还是没有解决，正常高度是32px，在系统缩放是125%时，变成31.6px，而按钮正常32px @afc163 
360截图20230128124943166

**Pull request merged**
