### PR TITLE
fix: Carousel GoTo is ignored if animation is in progress

### LINKED ISSUE #32293: Carousel GoTo is ignored if animation is in progress
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/reproduce-issue-whereby-calling-carousel-goto-during-animation-ignores-the-command-49o45?file=/index.js)

### Steps to reproduce
Create an antd Carousel component with multiple pages.  Send multiple goTo commands (without setting dontAnimate=true) to it in quick succession, and you will find that any goTo commands that reach the component while an animation in progress will be ignored.  

### What is expected?
Each goTo command should be processed, even if an animation is in progress.

### What is actually happening?
goTo commands that reach the component during animation are ignored.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Ubuntu 21.04 |
| Browser | Version 92.0.4515.131 (Official Build) (64-bit) |

### PR DESCRIPTION
**Pull request by guan404ming**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

1. fix #32293

### 💡 Background and solution

- Carousel GoTo is ignored if animation is in progress.
   -  By setting the ```waitForAnimate = false``` by default, it won't wait the animation and thus perform GoTo mostly.
   - refer to @theGOTOguy and @afc163 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      add waitForAnimate in Carousel     |
| 🇨🇳 Chinese |    在 Carousel 组件中添加"waitForAnimate" 属性    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 3e44a86</samp>

Add a new prop `waitForAnimate` to the `Carousel` component and document it in both English and Chinese. This prop allows users to control the slide switching animation behavior.

### <samp>🤖 Generated by Copilot at 3e44a86</samp>

*  Add a new prop `waitForAnimate` to the Carousel component that controls whether the component waits for the animation to finish when switching slides ([link](https://github.com/ant-design/ant-design/pull/41969/files?diff=unified&w=0#diff-1c7149c47863e64c7c50329eb74007c831fe6de5311ca65b52a6d691c8227bb5R34), [link](https://github.com/ant-design/ant-design/pull/41969/files?diff=unified&w=0#diff-1158da0914c171fa74b4fa496bef7272ca0776317fb5e222bebdf11477b191fbR21), [link](https://github.com/ant-design/ant-design/pull/41969/files?diff=unified&w=0#diff-571c29e796a3a85fdd7797d5f7732f3b1f0fc65908889f05deccd8e44ff298c3R35))
* Set the default value of `waitForAnimate` to `false` in the `Carousel` component function in `index.tsx` ([link](https://github.com/ant-design/ant-design/pull/41969/files?diff=unified&w=0#diff-1158da0914c171fa74b4fa496bef7272ca0776317fb5e222bebdf11477b191fbR38))
* Forward the `waitForAnimate` prop to the underlying `rc-carousel` component in `index.tsx` ([link](https://github.com/ant-design/ant-design/pull/41969/files?diff=unified&w=0#diff-1158da0914c171fa74b4fa496bef7272ca0776317fb5e222bebdf11477b191fbR114))

### CODE REVIEW

**Comment by guan404ming** [comment]
> Can some new test case cover this?

I would try to write it !

**Comment by guan404ming** [comment]
> Can some new test case cover this?

I have done ~~ Need your review ~~

**Comment by yoyo837** [comment]
> > Can some new test case cover this?
> 
> I have done ~~ Need your review ~~

In the upstream `waitForAnimate` defaults is `true`, I think this needs to send this PR to the `feature` branch, let's release this change in the next minor. Thanks for your contribution.

**Review by yoyo837 — APPROVED** [review]

**Comment by zombieJ** [comment]
@guan404ming , do you have interested to join antd Dingding group?

image

**Comment by guan404ming** [comment]
> @guan404ming , do you have interested to join antd Dingding group?
> 
> 



> @guan404ming , do you have interested to join antd Dingding group?
> 
> 

Definitely yes! I would be honored to join this group.

**Pull request merged**
