### PR TITLE
fix: Button icon with loading animation

### LINKED ISSUE #23070: Button icon with loading animation weird
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-grucr?file=/index.js)

### Steps to reproduce

Kapture 2020-04-09 at 10 36 21

Kapture 2020-04-09 at 10 37 11

### What is expected?
animation normal

### What is actually happening?
animation weird

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.0 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Resolve #23070 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |fix Button `icon` with `loading` animation|
| 🇨🇳 Chinese | 修复 Button `icon` 结合 `loading`  的动画|

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
image

这样找个 click me 宽度会直接弹开，预期是 transition 变宽。

**Comment by shaodahong** [comment]
改动主要在有 `Icon` 的情况下

## Before
Kapture 2020-04-09 at 15 47 40
Kapture 2020-04-09 at 15 48 53

## After
Kapture 2020-04-09 at 15 50 14
Kapture 2020-04-09 at 15 49 36

**Comment by afc163** [comment]
没图标的情况最好也能回到 3.x 的动画。

**Comment by shaodahong** [comment]
> 没图标的情况最好也能回到 3.x 的动画。

@zombieJ @afc163 

和 React 的更新调度有点关系，3.0 的组件类似

```jsx
<Button><span>{loading ? 1 : 2}</span>Click</Button>
```

4.0 类似这种

```jsx
<Button>{loading ? <span>1</span> : <sub>2</sub>}Click</Button>
```

在组件销毁再创建的时候（transition）的时候，附加的样式（margin-left）变了，导致明显的**先收缩再膨胀**

**Pull request closed without merging**
