### PR TITLE
feat: Avatar.Group support `shape`

### LINKED ISSUE #36691: Ant Avatar.Group overflow item seems to be hardcoded to a circle shape and cannot be changed to square
### What problem does this feature solve?

When making all Avatar Square in `Avatar.Group`, the overflow component renders as a `circle` and cannot be changed to a `square` as needed by providing the `shape` property to the Group. 

In the screenshot below we can see that the `ant-avatar ant-avatar-circle` classnames are being applied to the overflow component.

The end user experience would be to maintain the consistency of the shape of Avatars across the .Group component

image

### What does the proposed API look like?

Provide a property to specify the `shape` of the overflow to `Avatar.Group`. The `shape` property of `Avatar.Group` would accept `circle | square `

### PR DESCRIPTION
**Pull request by zty42**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Avatar.Group support `shape` |
| 🇨🇳 Chinese | Avatar.Group 支持 `shape` |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
Please change base to feature branch。

**Comment by tianyuan233** [comment]
> 
已修改 顺便我想问一下 我更新了 demo/group.md 后 运行`npm run test-image` 会有下面的报错,大佬知道如何解决吗...

OS: win 11
NodeJsVersion: v16.13.2
096DFAB9-B821-46ca-97B2-E083626CD4FC

**Comment by tianyuan233** [comment]
> Please change base to feature branch.

已修改 我这里`feat-avatar.group-support-shape`分支 是从master 拉出来的 会有影响吗

**Comment by MadCcc** [comment]
可以 cherry-pick 一下，看起来是污染了

**Comment by RiteshMakan** [comment]
I will update my PR here:
https://github.com/ant-design/ant-design/pull/36731

**Pull request closed without merging**
