### PR TITLE
chore: do not update @ant-design/cssinjs

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/discussions/48139
same as https://github.com/ant-design/ant-design/pull/48141

### 💡 Background and solution

@ant-design/cssinjs 依赖太精确容易导致应用上层有两份 @ant-design/cssinjs，dependabot 里忽略掉。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   --        |
| 🇨🇳 Chinese |   --        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by Wxh16144 — APPROVED** [review]
+1

**Comment by crazyair** [comment]
我现在是应用不安装  icons 了，避免出现 2 份

**Comment by afc163** [comment]
@crazyair 这样会有幽灵依赖问题。

**Comment by crazyair** [comment]
> @crazyair 这样会有幽灵依赖问题。

那很多白都有，不能都安装了，所以我关闭了 `shamefully-hoist=true`

**Comment by MadCcc** [comment]
这样不太好吧，有重要变化的时候是需要精确 cssinjs 版本的，至少要把 minor 提上来

**Comment by MadCcc** [comment]
把 cssinjs 变成 peer，安装 antd 时要求用户同时声明 cssinjs 依赖？
`npm i antd @ant-design/cssinjs`

**Pull request merged**
