### PR TITLE
Fix:去除相同月份相同时，结束月加1的操作

### PR DESCRIPTION
**Pull request by alex89lj**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

1.https://github.com/react-component/calendar/pull/478
2.https://github.com/ant-design/ant-design/issues/13302

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description
Fixed an issue about the component(RangePicker)  could not select the same month
2. Chinese description (optional)

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
也更新一下 package.json 里 rc-calendar 的版本。

**Comment by afc163** [comment]
feature 分支

**Comment by alex89lj** [comment]
我需要切换到feature分支 重新改一下再提交到feature分支吗？

**Comment by alex89lj** [comment]
我刚做了一次对feature分支的提交  不知道我是否正确理解了@afc163 的意思

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/15427

**Pull request closed without merging**
