### PR TITLE
docs: fix ssr issue

### LINKED ISSUE #39832: Spec docs displays a blank screen
### Reproduction link

[https://ant.design/docs/spec/introduce](https://ant.design/docs/spec/introduce)

### Steps to reproduce

Visit https://ant.design/docs/spec/introduce 
or click "Design" menu on https://ant.design

### What is expected?

The spec design documentation is displayed

### What is actually happening?

A blank page is shown.

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | NA |
| System | NA |
| Browser | Latest Firefox and Edge |

---
I think it started happening when v5.1.1 was deployed.

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close: https://github.com/ant-design/ant-design/issues/39832

### 💡 Background and solution
- [x] 修复 SSR 注水问题。由于 Layout 更新状态后也更新了 context，导致 Suspense 中的页面注水失败。这个问题目前似乎无解，只能按照警告中的加上 `startTransition` 来降低 `setState` 的优先级来防止注水中断。
- [x] 修复生成色板工具无法打开的问题
- [x] 修复 loading 消失的问题
- [x] 修复英文设计页白屏
- [x] 修复英文设计页目录错误

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |       -    |
| 🇨🇳 Chinese |       -    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
👍 高级啊

Skeleton 丢失的问题一并修一下？

**Comment by MadCcc** [comment]
> 👍 高级啊
> 
> Skeleton 丢失的问题一并修一下？

我看看，之前都没注意骨架屏没了

**Comment by MadCcc** [comment]
等 dumi 发个版

**Review by li-jia-nan — APPROVED** [review]

**Comment by afc163** [comment]
> Skeleton 丢失的问题一并修一下？

好像问题还在

**Pull request merged**
