### PR TITLE
chore: publish to github-package when released

### PR DESCRIPTION
**Pull request by orzyyyy**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    publish to github-package when released       |
| 🇨🇳 Chinese |     发布新版本时自动发布到 github package      |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by orzyyyy** [comment]
我这看不出这 repo 开没开出 github package。如果有的话劳烦抬一手加下 token，没排到的话我到时候关了就是

**Comment by afc163** [comment]
👍

**Comment by afc163** [comment]
image

要等

**Comment by orzyyyy** [comment]
那先关了吧，合了不知道会不会出问题，到时候再加

**Comment by orzyyyy** [comment]
package 看上去已经开了

**Comment by shaodahong** [comment]
> image
> 
> 要等

现在是 beta 版本
image

**Comment by ycjcl868** [comment]
任意一个 branch publish 都会触发，不指定 master？

**Comment by orzyyyy** [comment]
我理解是，创建 release 不分 branch，默认就是 master，所以就去掉 `branches` 了

**Comment by ycjcl868** [comment]
https://github.com/ant-design/ant-design/runs/224753173

@orzyyyy  deploy Github package failed.

**Comment by shaodahong** [comment]
> https://github.com/ant-design/ant-design/runs/224753173
> 
> @orzyyyy deploy Github package failed.

token 是不是没有权限 release package

**Comment by orzyyyy** [comment]
是环境错了，install 的时候要从 `https://registry.npmjs.org` 下，发布到 github package 的时候要发布到 `https://npm.pkg.github.com`。当然这个改一下就完了，现在问题是要不要检查 github package 的版本冲突 https://github.com/ant-design/ant-design/pull/18851

**Pull request merged**
