### PR TITLE
fix(Typography): editable onChange behavior

### PR DESCRIPTION
**Pull request by denghuacc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#36382

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix `editable.onChange` behavior for Typography component |
| 🇨🇳 Chinese |   修复 Typography 组件 `editable.onChange` 的异常行为     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
行为有变化，放 feature 分支吧。

**Comment by alanhaledc** [comment]
这个 PR 还需要改进吗？@afc163
这里的 Codecov Report 应该是出问题了

**Comment by afc163** [comment]
冲突了

**Comment by alanhaledc** [comment]
冲突已处理，但是这里有个 CI 没有通过，原因不明。
```bash
Run npm run check-ts-demo

> antd@[4](https://github.com/ant-design/ant-design/actions/runs/3080347360/jobs/4977593834#step:5:5).23.0 check-ts-demo
> node ./scripts/check-ts-demo


> antd@4.23.0 tsc
> tsc --noEmit

components/~tmp/input-number-out-of-range.tsx(11,[5](https://github.com/ant-design/ant-design/actions/runs/3080347360/jobs/4977593834#step:5:6)1): error TS2322: Type 'Dispatch<SetStateAction<string | number>>' is not assignable to type '(value: ValueType | null) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'ValueType | null' is not assignable to type 'SetStateAction<string | number>'.
      Type 'null' is not assignable to type 'SetStateAction<string | number>'.
Execution...: 31.2[7](https://github.com/ant-design/ant-design/actions/runs/3080347360/jobs/4977593834#step:5:8)[9](https://github.com/ant-design/ant-design/actions/runs/3080347360/jobs/4977593834#step:5:10)s
💥 OPS! Seems some tsx demo not pass tsc...
Error: Process completed with exit code 2.
```

**Comment by li-jia-nan** [comment]
Hey! Conflicting files, and it seems this is now really outdated. If this is something that still makes sense to the latest master version of Antd, please send a new PR with this change :)

**Pull request closed without merging**
