### PR TITLE
Update index.zh-CN.md

### PR DESCRIPTION
**Pull request by tianlizhao**
rowKey如果是方法的话，我看源码里返回了rowKey(record, index)，但是在文档里没有体现出来。

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by yesmeck** [comment]
因为这里的 index  会有歧义，是不推荐用的。Ref https://github.com/ant-design/ant-design/pull/4185#issuecomment-266634958

**Comment by tianlizhao** [comment]
那如果数据源里本身没有唯一的key值，应该拿什么做为key合适呢？

**Comment by yesmeck** [comment]
如果你的 Table 不变化的话（不需要 filter，不用 expand 之类的功能）是可以用 index 做 key 的。不然必须要有个唯一稳定的 key，这是 React  的机制。

**Comment by benjycui** [comment]
或者源码应该加个注释。

**Pull request closed without merging**
