### PR TITLE
Compatible with non-image format file preview in UploadList

### PR DESCRIPTION
**Pull request by zswang**
## Before

snip20180311_3

## After

snip20180310_1

## Checklist

* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Add some descriptions and refer relative issues for you PR.

*isNewFeature*

* [x] Add unit tests for the feature.

### CODE REVIEW

**Comment by afc163** [comment]
Great job! @zswang

**Comment by lee813** [comment]
@zswang Sorry to report, but this could cause some problem, for example, the image url I use is /api/Resources/Image/1/Preview, so your regex cannot detect it, and automatically recognize it as a file. Maybe we can add a switch to turn on this feature or disable it.

Thanks.

**Comment by zswang** [comment]
@lee813

Have try

`/api/Resources/Image/1/Preview?1.png`

or 

`/api/Resources/Image/1/Preview#1.png`

Thanks

**Comment by lee813** [comment]
@zswang So you suggest me to modify the api response? what if I can't modify the api service?

**Comment by yutingzhao1991** [comment]
@lee813 not need to modify the api response, Just modify your image url. append `#1.png` or `?1.png` to your url.

---

But... Maybe should add a property for this.

**Pull request merged**
