### PR TITLE
docs: reduce layout demo

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   none        |
| 🇨🇳 Chinese | none          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/layout/demo/basic.md](https://github.com/ant-design/ant-design/blob/layout-demo/components/layout/demo/basic.md)

### CODE REVIEW

**Comment by xrkffgg** [comment]
@shaodahong 大佬，这个 UI_test 肿么了

**Comment by shaodahong** [comment]
> @shaodahong 大佬，这个 UI_test 肿么了

看起来是字体不一致导致报的错

**Pull request merged**
