### PR TITLE
feat: Skeleton add round prop

### LINKED ISSUE #24130: Skeleton round border radius style
```jsx
<Skeleton round />
```

image

live sample：https://codesandbox.io/s/basic-ant-design-demo-xlw1b?file=/index.css

### PR DESCRIPTION
**Pull request by xilihuasi**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #24130

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Skeleton add `round` prop to enable paragraph and title show radius |
| 🇨🇳 Chinese | Skeleton 添加 `round` 属性，允许段落和标题显示圆角 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/skeleton/index.en-US.md](https://github.com/xilihuasi/ant-design/blob/feature/components/skeleton/index.en-US.md)
[View rendered components/skeleton/index.zh-CN.md](https://github.com/xilihuasi/ant-design/blob/feature/components/skeleton/index.zh-CN.md)
[View rendered docs/react/introduce.zh-CN.md](https://github.com/xilihuasi/ant-design/blob/feature/docs/react/introduce.zh-CN.md)

### CODE REVIEW

**Comment by yoyo837** [comment]
混入了其他东西

**Comment by xilihuasi** [comment]
只修改了 Skeleton 模块文件，其他文件是 upstream 之后 pr 混入的，需要重发 pr 吗

**Comment by yoyo837** [comment]
rebase 操作不对

**Comment by xilihuasi** [comment]
现在 file change 是对的，本地 run test 通过。但是 push 到线上会报 error。
看了下日志报的是 ellipsis-custom-tooltip.md demo test snapshot 不匹配，但是本地是正常的，请问要怎么解决。

**Comment by afc163** [comment]
```
rm package-lock.json yarn.lock && npm i && npm test -- -u
git commit -am 'fix snapshot'
git push origin feature
```

**Review by afc163 — APPROVED** [review]

**Pull request merged**
