### PR TITLE
fix: Select mutilple config token don't work

### PR DESCRIPTION
**Pull request by CooperHash**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

#48043

### 💡 Background and solution

with configprovider provide controlHeight, select component multiple dont' work 
like

image

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix: Select mutilple config token don't work        |
| 🇨🇳 Chinese | 修复多项选择器configprovider高度不生效         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by CooperHash** [comment]
ref: #48043

**Comment by afc163** [comment]
看截图不太对。

**Comment by CooperHash** [comment]
> 看截图不太对。

我从issue复现链接截的https://stackblitz.com/edit/react-dqxc6p?file=index.tsx,App.tsx

**Comment by afc163** [comment]
我意思是这个：https://antd-visual-diff.oss-cn-shanghai.aliyuncs.com/pr-48051/visualRegressionReport/report.html

**Comment by CooperHash** [comment]
恩，我再看一下，确实不太对

**Comment by CooperHash** [comment]
image



image

本地修改完后好像没问题，这些都是改完后的
之前改动了原来的`position: relative`，现在改回去没有上一次preview的那些偏差了，貌似这一次的preview还是跟上一次一样

**Comment by CooperHash** [comment]
修了issue这个问题，但是影响到了datepicker：size变化不起作用

**Comment by CooperHash** [comment]
I am stuck with this bug, which is not reproducible consistently. If someone else can solve it, I will close this pull request.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/48574

**Pull request closed without merging**
