### PR TITLE
feat: remove shallowequal

### PR DESCRIPTION
**Pull request by yoyo837**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
Waiting for upstream to merge and release a new version:
- [ ] https://github.com/react-component/textarea/pull/28
- [ ] https://github.com/react-component/table/pull/914 https://github.com/react-component/table/pull/917
- [ ] https://github.com/react-component/slider/pull/857
- [ ] https://github.com/react-component/picker/pull/554
- [ ] https://github.com/react-component/menu/pull/572
- [ ] https://github.com/ant-design/cssinjs/pull/65
- [ ] https://github.com/react-component/collapse/pull/285

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     remove shallowequal       |
| 🇨🇳 Chinese |     删除 shallowequal     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/cssinjs/pull/64/files

这里也用了。

**Comment by afc163** [comment]
可以试试类似 https://www.npmjs.com/package/webpack-restrict-import-loader 这种插件来探测某些依赖是否存在。

**Comment by yoyo837** [comment]
> https://github.com/ant-design/cssinjs/pull/64/files
> 
> 这里也用了。

有个 PR https://github.com/ant-design/cssinjs/pull/65

**Review by zombieJ — APPROVED** [review]

**Comment by afc163** [comment]
是不是先得把 rc-* 的合并一遍先。

**Comment by yoyo837** [comment]
> 是不是先得把 rc-* 的合并一遍先。

可能是打算后面慢慢发patch.

**Comment by afc163** [comment]
没必要啊。

**Comment by yoyo837** [comment]
@zombieJ 是这样的不?

**Pull request merged**
