### PR TITLE
docs: add Arabic documentation

### LINKED ISSUE #41641: Arabic Documentation
### What problem does this feature solve?

This feature will help the Arabic users to be more comfortable using your tool and checking your recommendation.

A lot of languages noticed in the readme, but Arabic is not there, so let's add it!

### What does the proposed API look like?

There is no API in this feature.

### PR DESCRIPTION
**Pull request by guan404ming**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

1. close #41641

### 💡 Background and solution
- refer to @RihamSalman's translation to finish this PR

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     add Arabic documentation      |
| 🇨🇳 Chinese |      新建阿拉伯语文档     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at f30c622</samp>

This pull request adds the Arabic documentation of ant-design to the `README-ar_EG.md` file and updates the links to the other language options in the existing README files. This enhances the internationalization and accessibility of the ant-design project.

### <samp>🤖 Generated by Copilot at f30c622</samp>

*  Add Arabic language option to the documentation ([link](https://github.com/ant-design/ant-design/pull/41963/files?diff=unified&w=0#diff-f3ab76cc94b9ffa09503219c83db5072c8ac395eb19943ad57d8e70f39272a02R1-R155))
*  Update links to the Arabic documentation in other language files ([link](https://github.com/ant-design/ant-design/pull/41963/files?diff=unified&w=0#diff-e15f8df5924bb67d24949dc71b9d3b1c2d8f49a20b1c775462da1e5cccb2af7dL48-R48), [link](https://github.com/ant-design/ant-design/pull/41963/files?diff=unified&w=0#diff-35d936a7cefe6fe1b8f472c19ca57cdf86521e852dc0586fa45624e5346c7a9bL48-R48), [link](https://github.com/ant-design/ant-design/pull/41963/files?diff=unified&w=0#diff-9163f2de90e1e6c37cd4604a00b40a2267490a2c75dc34261fdb48d8ccb43673L48-R48), [link](https://github.com/ant-design/ant-design/pull/41963/files?diff=unified&w=0#diff-dde303a2f426826a7f9845b94221d8685f88c2f9956a42e7d179c6b471e75b50L48-R48), [link](https://github.com/ant-design/ant-design/pull/41963/files?diff=unified&w=0#diff-099beda0196f3588b806c1d7ace4d054b6a1caf09bfede3b0c1a9ac7cfb74473L48-R48))

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

**Comment by yoyo837** [comment]
README.md should add this Arabic link. @guan404ming

**Comment by guan404ming** [comment]
> README.md should add this Arabic link. @guan404ming

So so sorry! I have fixed it. Should I PR again or what should I do to let you know.

**Comment by yoyo837** [comment]
Yes please, a new PR is ok.

**Comment by RihamSalman** [comment]
Thank you @guan404ming for helping in this.
Excuse me @yoyo837 , seems now my name is not in the contributing, can you help me with this please?

**Comment by RihamSalman** [comment]
Thanks for your reply.
But I did the translation (which is the main of the task). I had some issues completing it in the end in doing the template, I need to be a contributor here (it's kinda university task), so can you help me please? or tell me what to do for that?

**Comment by RihamSalman** [comment]
ok,I'll do a new pr, thank you very much.

**Pull request merged**
