### PR TITLE
fix: upload-picture-card-style-error

### LINKED ISSUE #19776: [BUG] Bad bug fix from #19689 on 3.25.2
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
# 3.25.2
[Edit on CodeSandbox](https://codesandbox.io/s/beautiful-shape-301y1)
# 3.25.1
[Edit on CodeSandbox](https://codesandbox.io/s/dazzling-chaum-98xtx)

### Steps to reproduce
# 3.25.2
https://codesandbox.io/s/beautiful-shape-301y1

# 3.25.1
https://codesandbox.io/s/dazzling-chaum-98xtx

### What is expected?
upload or remove uploaded file, style works correctly.

### What is actually happening?
upload or remove uploaded file, style works badly.

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | latest |
| System | mac os 10.14.4 |
| Browser | chrome 78 |

### PR DESCRIPTION
**Pull request by crazyair**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
fix #19776

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix picture-card type each delete style error       |
| 🇨🇳 Chinese |     修复 picture-card 类型下，挨个删除列表出现样式问题   |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
本行项删除时本行后面的是往左靠的动画，第二行的项有向上的动画，这是预期的吗？

**Comment by yoyo837** [comment]
[Nov-18-2019 17-55-09.mp4.zip](https://github.com/ant-design/ant-design/files/3857983/Nov-18-2019.17-55-09.mp4.zip)
换行位置闪动。

**Comment by qq645381995** [comment]
> [Nov-18-2019 17-55-09.mp4.zip](https://github.com/ant-design/ant-design/files/3857983/Nov-18-2019.17-55-09.mp4.zip)
> 换行位置闪动。

https://stackblitz.com/edit/react-4dp8ht 3.25.1 也是

**Comment by qq645381995** [comment]
> [Nov-18-2019 17-55-09.mp4.zip](https://github.com/ant-design/ant-design/files/3857983/Nov-18-2019.17-55-09.mp4.zip)
> 换行位置闪动。

这个旧版本，width=200px，从第二个开始删除，也是闪一下。

**Pull request merged**
