### PR TITLE
style: Demo Component overflow use auto

### PR DESCRIPTION
**Pull request by MARKX97**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [X] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Demo Component overflow use auto    |
| 🇨🇳 Chinese |   Demo组件overflow用auto替换scroll        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Tabs 那个 demo 要看一下，这样改会挂掉。

**Comment by MARKX97** [comment]
> Tabs 那个 demo 要看一下，这样改会挂掉。

好的大佬

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/41454
https://github.com/ant-design/ant-design/issues/41438

副作用蛮多

**Comment by li-jia-nan** [comment]
这个需要回滚一下，影响到很多demo

**Comment by yoyo837** [comment]
> 这个需要回滚一下，影响到很多demo

没人动手我来了 #41467

**Pull request merged**
