### PR TITLE
Use new Argos CLI

### PR DESCRIPTION
**Pull request by gregberge**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 💡 Background and solution

The legacy argos-cli is deprecated. As Argos principal maintainer, I made the migration for you to use the new `@argos-ci/cli`. Read more about that on our [documentation website](https://docs.argos-ci.com/).

We are very glad that you use Argos, feel free to join our [Discord](https://discord.gg/WjzGrQGS4A).

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by gregberge** [comment]
@afc163 @MadCcc @xrkffgg @zombieJ I understand why it is closed but I think it could help you!

**Comment by zombieJ** [comment]
CI failed

**Comment by zombieJ** [comment]
@gregberge Seems CI not show argos diff result.

**Comment by gregberge** [comment]
@zombieJ it seems it blocks before Argos: https://github.com/ant-design/ant-design/runs/8240764448?check_suite_focus=true

**Comment by zombieJ** [comment]
I rerun the job but seems still not trigger: https://github.com/ant-design/ant-design/runs/8240777003?check_suite_focus=true

**Comment by gregberge** [comment]
> I rerun the job but seems still not trigger: https://github.com/ant-design/ant-design/runs/8240777003?check_suite_focus=true

I think it is another problem not relative to Argos. Probably a problem of GitHub Actions orchestration, job renamed or something like that.

**Comment by zombieJ** [comment]
@shaodahong Please help check this.

**Comment by shaodahong** [comment]
> Please help check this.
@zombieJ I remember the github action code only trigger when the master branch, and i found snapshot the latest is two days ago, is this right? https://app.argos-ci.com/ant-design/ant-design/builds

**Comment by gregberge** [comment]
@shaodahong as I understand it, it should run "UI Upload" workflow

https://github.com/ant-design/ant-design/blob/986bd02d6d28f821e11c6fd9dbb221b4633e28b2/.github/workflows/ui-upload.yml#L4-L8

But I don't see it in the list, maybe it is a problem with the name?

**Comment by gregberge** [comment]
In this PR you can see the job also does not run https://github.com/ant-design/ant-design/pull/37396

**Comment by gregberge** [comment]
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.

I think we could simplify by doing everything in the same job, what do you think?

**Comment by gregberge** [comment]
@zombieJ @shaodahong I simplified the process by running everything into a single job. I think it is easier. Tell me if it is good for you.

**Comment by gregberge** [comment]
@zombieJ can you reopen it please? I should have fixed permissions issue.

**Comment by shaodahong** [comment]
> completed

@gregberge yep, it's related to completed event, look like not trigger

**Comment by gregberge** [comment]
@shaodahong @zombieJ it is a permission issue, probably because it is build in Docker and not the same user.. I tried to create another directory but still a problem of permission. Could you give a look?

**Comment by zombieJ** [comment]
Hmmm... retry the CI but still failed. Why the Permission issue.

**Comment by gregberge** [comment]
Let's try using `cp` instead of `mv`.

**Comment by gregberge** [comment]
@zombieJ please reopen

**Comment by gregberge** [comment]
OK it works, last step, I was wrong in `depth` vs `fetch-depth`. @MadCcc could you reopen please?

**Comment by gregberge** [comment]
@zombieJ @shaodahong the Argos token seems wrong. It is weird.. You should check the secret, you can find the token here: https://app.argos-ci.com/ant-design/ant-design/settings (if logged on Argos).

**Comment by zombieJ** [comment]
> @zombieJ @shaodahong the Argos token seems wrong. It is weird.. You should check the secret, you can find the token here: https://app.argos-ci.com/ant-design/ant-design/settings (if logged on Argos).

It's strange since origin action work as expect. But OK, I've refresh this.

**Comment by gregberge** [comment]
> It's strange since origin action work as expect. But OK, I've refresh this.

Yeah very strange!

**Comment by gregberge** [comment]
> Yeah very strange!

Maybe it was "space" tolerant and now it is not, I don't know...

**Comment by shaodahong** [comment]
@gregberge Argos auto set commit and branch from env?

**Comment by gregberge** [comment]
> @gregberge Argos auto set commit and branch from env?

yeah. Still a problem of token, are you sure that there is no line return? It should be exactly 40 characters.

**Comment by gregberge** [comment]
As you can see the ARGOS_TOKEN is empty: 
Screenshot 2022-09-08 at 15 20 43

It should not be empty, see on Argos repository:
Screenshot 2022-09-08 at 15 21 20

**Comment by shaodahong** [comment]
> 

@gregberge need set ARGOS_TOKEN to env

> As you can see the ARGOS_TOKEN is empty: Screenshot 2022-09-08 at 15 20 43
> 
> It should not be empty, see on Argos repository: Screenshot 2022-09-08 at 15 21 20

@zombieJ Help check this.

**Comment by gregberge** [comment]
The only difference I see with the other job is:

```
permissions:
  contents: read
```

But in my experience, reading secret is not subject to permissions.. 

So I don't understand. Maybe it is because the PR is from outside? Weird too. But who knows!

**Comment by zombieJ** [comment]
> So I don't understand. Maybe it is because the PR is from outside? Weird too. But who knows!

Maybe you are right. Hmm... seems we need fork this PR in antd repo.

**Comment by gregberge** [comment]
> Maybe you are right. Hmm... seems we need fork this PR in antd repo.

Yeah you should try it! I think it is a protection because in my script I could display the secret, so it is possible that GitHub prevents it by default. Can you fork it?

**Comment by zombieJ** [comment]
> Yeah you should try it! I think it is a protection because in my script I could display the secret, so it is possible that GitHub prevents it by default. Can you fork it?

👌 Let me handle this after finish another task : )

**Pull request closed without merging**
