### PR TITLE
fix: Tree switcherIcon prop not working when showLine

### LINKED ISSUE #18810: Ant Tree switcherIcon prop not working
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/festive-hermann-w82n2?fontsize=14)

### Steps to reproduce
Check the sandbox 

### What is expected?
on passing custom icon to switcherIcon prop expand and collapse icons to be changed

### What is actually happening?
On passing custom icon to switcherIcon there is no change

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.9 |
| System | all |
| Browser | all |

### PR DESCRIPTION
**Pull request by MrHeer**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #18810
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   :bug: Fix Tree `switcherIcon` prop not working when `showLine` is `true`         |
| 🇨🇳 Chinese |     :bug: 修修复当 `showLine` 设置后 Tree 组件的 `switcherIcon` 属性没有正常工作   |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
来个用例？

**Comment by afc163** [comment]
close #18717 too

**Comment by MrHeer** [comment]
I just fix this bug, no feature for #18717

**Comment by ywy94ywy** [comment]
修复了吗？我什么我还是无法更改，我希望是这样子的

**Pull request merged**
