### PR TITLE
transfer support disabled & readOnly

### PR DESCRIPTION
**Pull request by zombieJ**
ref: https://github.com/ant-design/ant-design/issues/12066

Not sure `readOnly` is necessary or not. Pls help check on this.

### CODE REVIEW

**Comment by yesmeck** [comment]
`readOnly` 没啥用，其他组件也没这个属性

**Comment by zombieJ** [comment]
`readOnly` 去掉了

**Comment by afc163** [comment]
feature 分支

**Comment by zombieJ** [comment]
done

**Comment by afc163** [comment]
应该从 feature 切出来。

**Pull request merged**
