### PR TITLE
Fix #4039

### LINKED ISSUE #4039: Another issue about hardcoded styles
ref: #2424
I've got the same problem with him and I fixed some of them.

### PR DESCRIPTION
**Pull request by cathayandy**
Replace background-color: #fff with background: @body-background

---

Edit: close: #4039

### CODE REVIEW

**Comment by benjycui** [comment]
Next time, you should add `close: #4039` and something like this to close issue automatically.

Thanks.

**Comment by afc163** [comment]
No, `@body-background` is use for `<body>` only.

**Comment by benjycui** [comment]
So, we need a new variable?

**Comment by afc163** [comment]
Maybe `@component-background` ?

**Comment by benjycui** [comment]
OK.

**Pull request merged**
