### PR TITLE
feat: expose all Dropdown props of BreadcrumbItem

### PR DESCRIPTION
**Pull request by paranoidjk**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Expose all Dropdown props in Breadcrumb.Item       |
| 🇨🇳 Chinese |     暴露 Breadcrumb.Item 组件的所有 Dropdown 的可配置属性     |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/breadcrumb/index.en-US.md](https://github.com/ant-design/ant-design/blob/bread-visible/components/breadcrumb/index.en-US.md)
[View rendered components/breadcrumb/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/bread-visible/components/breadcrumb/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
需求是什么？

**Comment by zombieJ** [comment]
云凤蝶需要控制面包屑下拉状态。

**Comment by afc163** [comment]
云凤蝶没升 antd，加了短期内也用不上。

**Comment by paranoidjk** [comment]
@afc163 没升级是啥意思？master 已经是 V4 了吗？那我可以往 V3 pick 吗？

**Comment by yoyo837** [comment]
master 已经 v4。

**Comment by zombieJ** [comment]
感觉还是应该弄到 v4 来，v3 理论上不接受新的 feature 了。

**Review by afc163 — APPROVED** [review]

**Pull request merged**
