### PR TITLE
升级rc-progress到2.1.0版本；支持仪表盘

### PR DESCRIPTION
**Pull request by qiaolb**
升级rc-progress到2.1.0版本；支持仪表盘。
#5225

### CODE REVIEW

**Review by benjycui — APPROVED** [review]

**Comment by benjycui** [comment]
But you had better to update your commit message to English..

**Comment by qiaolb** [comment]
> But you had better to update your commit message to English..

@benjycui 需要重新Commit吗？

**Comment by benjycui** [comment]
本地 `git commit --amend` , 然后 `git push --force`

**Comment by benjycui** [comment]
Oops.... If you are not familiar with git, just close this PR and create a new one.

PR to branch feature-2.9.

**Comment by qiaolb** [comment]
@benjycui Sorry, this is my first PR. I had committed again, please check it.

**Comment by afc163** [comment]
rebase 一下，有多余的 commit 。

**Comment by qiaolb** [comment]
OK, 我重新PR一下，关闭这个

**Pull request closed without merging**
