### PR TITLE
style: fix BackTop not hidden completely

### PR DESCRIPTION
**Pull request by jesse3mh9a**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Backtop still interactive when it is hidden.    |
| 🇨🇳 Chinese |     修复 Backtop 隐藏时仍然影响布局, 尤其是容易触发光标样式     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Try

```
.ant-back-top:empty {
  display: none;
}
```

**Comment by jesse3mh9a** [comment]
> Try
> 
> ```
> .ant-back-top:empty {
>   display: none;
> }
> ```

 嗯 用:empty伪类 会更好 我修改下

**Comment by jesse3mh9a** [comment]
@afc163 谢谢你的建议, 已经修改完成

**Comment by fireairforce** [comment]
🤔这个lint挂的好奇怪。。

**Pull request merged**
