### PR TITLE
chore: remove unnecessary code

### PR DESCRIPTION
**Pull request by hoho2017**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/transfer/demo/basic.md](https://github.com/hoho2017/ant-design/blob/zhanghaoqiang/components/transfer/demo/basic.md)

### CODE REVIEW

**Comment by xrkffgg** [comment]
rebase 下

**Comment by Kermit-Xuan** [comment]
This is the unnecessary modification.

**Comment by hoho2017** [comment]
> This is unnecessary modification.

same style with others

**Comment by Kermit-Xuan** [comment]
Everyone's code style is different, although we modify it to a unified style now, the same problem will still occur in subsequent submissions.
Unless we specify a standard to regulate everyone's code style, it is obvious that your modification is logically unified, and this logically unified style is very difficult.

**Comment by 07akioni** [comment]
原先那么写确实有点费解

**Pull request closed without merging**
