### PR TITLE
✨ Renew TypeScript start documentation ✨

### LINKED ISSUE #12878: Use create-react-app in typescript guideline documentation
https://github.com/facebook/create-react-app/releases/tag/v2.1.0

https://ant.design/docs/react/use-in-typescript

### LINKED ISSUE #14085: Cannot find module react-scripts/config/webpack.config.dev, during antd theme customisation
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Ok. I've my create-react-app project as a typescript project via `--typescript` flag.

Now following this [guide][1] 

I started making modification for scripts. 

Here is what it looks like

```
"scripts": {
    "start": "react-app-rewired start && node scripts/start.js",
    "build": "react-app-rewired build  && node scripts/build.js",
    "test": "react-app-rewired test --env=jsdom && scripts/test.js"
},
```
and my config-overrides.js is below

```
const tsImportPluginFactory = require('ts-import-plugin')
const { getLoader } = require("react-app-rewired");
const rewireLess = require('react-app-rewire-less');

module.exports = function override(config, env) {
  const tsLoader = getLoader(
    config.module.rules,
    rule =>
      rule.loader &&
      typeof rule.loader === 'string' &&
      rule.loader.includes('ts-loader')
  );

  tsLoader.options = {
    getCustomTransformers: () => ({
      before: [ tsImportPluginFactory({
        libraryDirectory: 'es',
        libraryName: 'antd',
        style: 'true',
      }) ]
    })
  };
  config = rewireLess.withLoaderOptions({
    javascriptEnabled: true,
    modifyVars: { "@primary-color": "#1DA57A" },
  })(config, env);

  return config;
}
```
  [1]: https://ant.design/docs/react/use-in-typescript

### What is expected?
Yarn start gives an error as stated in issue title

### What is actually happening?
yarn start should run the project

---
So basically, I'm not sure if I'm writing the scripts correctly, it was just a guess work as no formal guide for create-react-app ts version is available for it. Please note I don't want to use `antd-ts-demo` repo as it threw me an error upfront on `yarn start` in `tsconfig.json` saying `config/.env should be in root of project`. I've filed this separately [here](https://github.com/imzengyang/antd-demo-ts/issues/1)

But I prefer not to use that I've almost done everything.  I was using `antd` fine via webpack.config .js before I hit the point to customisation need to override less variables and follow use in Typescript guide of yours in docs. 

Looking forward to tweak for help. Thanks!

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.2 alpha |
| System | MacOs High Sierra |
| Browser | Chrome 71.0.3578.98 |

### LINKED ISSUE #14151: 【在 TypeScript 中使用】页面按教程来，修改package.json文件react-app-rewired start --scripts-version react-scripts-ts   启动不了
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
"scripts": {
-   "start": "react-scripts-ts start",
    "start": "react-app-rewired start --scripts-version react-scripts-ts",
-   "build": "react-scripts-ts build",
    "build": "react-app-rewired build --scripts-version react-scripts-ts",
-   "test": "react-scripts-ts test --env=jsdom",
    "test": "react-app-rewired test --env=jsdom --scripts-version react-scripts-ts",
}
修改后yarn  start报错Cannot find module '/Users/XXX/react_demo/antd-demo-ts/node_modules/react-scripts-ts/config/webpack.config'

### What is expected?
解决，并修改教程

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | xx |
| System | mac  10.12.6 |
| Browser | xx |

### PR DESCRIPTION
**Pull request by afc163**
close https://github.com/ant-design/ant-design/issues/12878
close #14085
close #14151

I currently stuck at import [ts-import-plugin](https://github.com/Brooooooklyn/ts-import-plugin) in react-app-rewired@2.1 and [customize-cra](https://github.com/arackaf/customize-cra). @Brooooooklyn Could you help me finish this?

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
let me see what happened in create-react-app

**Comment by Brooooooklyn** [comment]
It seems like `create-react-app` not using `ts-loader`/`awsome-typescript-loader` any more.
So you can just using `babel-import-plugin` with `create-react-app`

With `create-react-app` eject command, you can find configuration in `config/webpack.config.js`: 

```js
            // Process application JS with Babel.
            // The preset includes JSX, Flow, TypeScript, and some ESnext features.
            {
              test: /\.(js|mjs|jsx|ts|tsx)$/,
              include: paths.appSrc,
              loader: require.resolve('babel-loader'),
              options: {
                customize: require.resolve(
                  'babel-preset-react-app/webpack-overrides'
                ),
                
                plugins: [
                  [
                    require.resolve('babel-plugin-named-asset-import'),
                    {
                      loaderMap: {
                        svg: {
                          ReactComponent:
                            '@svgr/webpack?-prettier,-svgo![path]',
                        },
                      },
                    },
                  ],
                ],
                // This is a feature of `babel-loader` for webpack (not Babel itself).
                // It enables caching results in ./node_modules/.cache/babel-loader/
                // directory for faster rebuilds.
                cacheDirectory: true,
                cacheCompression: isEnvProduction,
                compact: isEnvProduction,
              },
            },
```

So, you will not need `ts-import-plugin` if you are using `create-react-app`

**Comment by abenhamdine** [comment]
@afc163 you could also mention alternatives to customize-cra, as https://github.com/sharegate/craco + https://github.com/FormAPI/craco-antd.
It works very well.

**Comment by woow-wu** [comment]
but it still can't work properly

**Comment by woow-wu** [comment]
g

**Comment by woow-wu** [comment]
thanks

**Pull request merged**
