### PR TITLE
docs: improve umi create project

### PR DESCRIPTION
**Pull request by hengkx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
可以看看为啥文档里 craco-less 不生效了，我还是更愿意用 craco-less 而不是 craco-antd。

https://github.com/ant-design/ant-design/pull/29442

**Comment by hengkx** [comment]
> #29442

我创建一个项目看看

**Comment by hengkx** [comment]
> 可以看看为啥文档里 craco-less 不生效了，我还是更愿意用 craco-less 而不是 craco-antd。
> 
> #29442

我刚试了 没有问题🤣

**Comment by hengkx** [comment]
image
这个算问题吗？

**Comment by afc163** [comment]
不算，这个 warning 下个版本会去掉。

**Pull request merged**
