### PR TITLE
chore: adjust color trans

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

ref https://github.com/ant-design/ant-design/issues/42333#issuecomment-1546688494

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      -     |
| 🇨🇳 Chinese |     -      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 1be6a16</samp>

This pull request refactors the color picker style to use a utility function `getTransBg` for creating transparent backgrounds with dots. This affects the `components/color-picker/style/color-block.ts` and `components/color-picker/style/picker.ts` files.

### <samp>🤖 Generated by Copilot at 1be6a16</samp>

*  Add a utility function `getTransBg` to generate a transparent background with dots for the color picker components ([link](https://github.com/ant-design/ant-design/pull/42355/files?diff=unified&w=0#diff-c24d0ab998b998a6a5cfd4d77148aad78198e1fe93395501020c8bbee7ebfc1cR4-R13))
* Use `getTransBg` to replace the hardcoded background properties of the color block style in `color-block.ts` and the alpha slider style in `picker.ts` ([link](https://github.com/ant-design/ant-design/pull/42355/files?diff=unified&w=0#diff-c24d0ab998b998a6a5cfd4d77148aad78198e1fe93395501020c8bbee7ebfc1cL14-R24), [link](https://github.com/ant-design/ant-design/pull/42355/files?diff=unified&w=0#diff-34b89f88ff38f571cda106c0e4980f0487a530c9c21623a0fd1695bb0b132a58L3-R3), [link](https://github.com/ant-design/ant-design/pull/42355/files?diff=unified&w=0#diff-34b89f88ff38f571cda106c0e4980f0487a530c9c21623a0fd1695bb0b132a58L61-R61))

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Comment by afc163** [comment]
图片

这个是符合预期的么，看着有点怪。

**Comment by zombieJ** [comment]
不是，我调整一下

**Comment by afc163** [comment]
> 不是，我调整一下

啥也没改？

**Comment by li-jia-nan** [comment]
> 啥也没改？

- #42361

**Pull request merged**
