### PR TITLE
chore: RM circle ci

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### CODE REVIEW

**Comment by afc163** [comment]
下面这些额外的任务目前依赖 circleci，需要迁移：

- [ ] 覆盖率上报：https://github.com/ant-design/ant-design/blob/bb60e2ef5805312b727ce0dc1c7e998c3ee74f97/.circleci/config.yml#L143-L144
- [ ] bundlesize：https://github.com/ant-design/ant-design/blob/bb60e2ef5805312b727ce0dc1c7e998c3ee74f97/.circleci/config.yml#L78
- [ ] check-demo：https://github.com/ant-design/ant-design/blob/e5e44d2aae60411ac6915392c6f3b77a0f032491/.circleci/config.yml#L159

**Comment by zombieJ** [comment]
奇怪。 。 。github action 怎么没了

**Comment by afc163** [comment]
覆盖率的评论没出来？

**Pull request merged**
