### PR TITLE
type: demo type enhance

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | type: demo type enhance |
| 🇨🇳 Chinese | type: demo 类型增强 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

**Comment by li-jia-nan** [comment]
大佬好快，CI 还没跑完就 merge 了👍

**Comment by yoyo837** [comment]
> 大佬好快，CI 还没跑完就 merge 了👍

我感觉你在内涵大佬,但我没有证据 [忍者]

**Comment by li-jia-nan** [comment]
> > 大佬好快，CI 还没跑完就 merge 了👍
> 
> 我感觉你在内涵大佬,但我没有证据 [忍者]😏

没有没有，字面意思😄

**Comment by afc163** [comment]
人肉 CI 已过

**Pull request merged**
