### PR TITLE
Feature: uk_UA locale

### PR DESCRIPTION
**Pull request by anxolerd**
Add uk_UA locale to antd in order to provide better user experience for Ukrainian users. See (feat #8168). In order to do this, provide local locale files alongside with updating the rc-calendar dependency to the version which adds Ukrainian localization there.

This PR also adds uk_UA locale to locale-provider test-suite.

when merged this will resolve #8169

### CODE REVIEW

**Comment by anxolerd** [comment]
I wouldn't mind help with fixing the falling build at appVeyor, which I cannot reproduce locally.

**Review by vladholubiev — APPROVED** [review]

**Comment by afc163** [comment]
@benjycui Need to patch this in rc-calendar@9.0.5 but the tag of 9.0.4 is not found.

**Comment by benjycui** [comment]
Just PR to antd@3.0

**Comment by anxolerd** [comment]
@benjycui, should I open a new PR or change the target branch of this one?

**Comment by afc163** [comment]
@anxolerd Yes, master no longer accept new features now.

**Comment by anxolerd** [comment]
@afc163 @benjycui: I have rebased my changes onto `antd-3.0` branch and change the target branch for this PR.

**Comment by anxolerd** [comment]
Tests failed, because snapshot for uk_UA locale was not found. Should I also commit a modified snapshot file to the feature branch?

/cc @afc163 @benjycui

**Comment by benjycui** [comment]
Yep, run `npm test -- -u` to update it, thanks.

**Comment by anxolerd** [comment]
I've added the missing testsuite

**Comment by anxolerd** [comment]
@afc163 @benjycui: thanks for guiding me through the contribution process.

**Pull request merged**
