### PR TITLE
chore: replace theme.useToken with useInternalToken

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: replace `theme.useToken` with `useInternalToken` |
| 🇨🇳 Chinese | 把 `theme.useToken`  替换成内部的 `useInternalToken` |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at a28a5d3</samp>

This pull request refactors several components and demo files to use the internal theme hook `useToken` more consistently and directly. It also improves the code style and readability by reordering imports, simplifying destructuring, and adding type annotations. The main files affected are `ColorPicker.tsx`, `Dropdown.tsx`, `QRCode.tsx`, `Tooltip.tsx`, `Tour.tsx`, `Watermark.tsx`, and `TreeTransfer.tsx`.

### <samp>🤖 Generated by Copilot at a28a5d3</samp>

*  Annotate `TokenChecker` and `TreeTransfer` components with `React.FC` type to avoid implicit `any` type ([link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL47-R47), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-5d2a9fbb1586f5058bfd77d20e281f359ce068ed333ccc4375ee0ef1961342cbL23-R23))
* Import `useToken` hook from `../theme/internal` module instead of `../theme` module to avoid circular dependencies and follow internal convention ([link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fL20-R20), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-8d2a305db0c4945017603df77e97b2bf27dbde09aef2a8e2c2f7d10e67a3a822L38-R39), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beL18-R19), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-30eea37f943f85a55da5ca1786ff308fcbc33e8fc744029eedf600e8577bf2eaL11-R17), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L22-R27), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L30-R31), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-add08763825dd36ecf1bf3482c1f2e331f8b6c9d83eff23a5fd55a2a25fd2e19L52-R51))
* Destructure `token` object from `useToken` hook without the `token` property name, since the hook returns an array of `[setToken, token]` instead of an object ([link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fL104-R104), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-8d2a305db0c4945017603df77e97b2bf27dbde09aef2a8e2c2f7d10e67a3a822L71-R73), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beL176-R177), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-30eea37f943f85a55da5ca1786ff308fcbc33e8fc744029eedf600e8577bf2eaL11-R17), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L211-R210), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L30-R31), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-add08763825dd36ecf1bf3482c1f2e331f8b6c9d83eff23a5fd55a2a25fd2e19L52-R51))
* Access `token.colorBgElevated` property directly from `token` object instead of destructuring it, to make the code more concise and consistent ([link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-8d2a305db0c4945017603df77e97b2bf27dbde09aef2a8e2c2f7d10e67a3a822L71-R73))
* Reorder imports to follow the convention of importing React and types first, then external dependencies, then internal modules, and then styles ([link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-8d2a305db0c4945017603df77e97b2bf27dbde09aef2a8e2c2f7d10e67a3a822L1-R10), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beL1-R3), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beL7-R12), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-30eea37f943f85a55da5ca1786ff308fcbc33e8fc744029eedf600e8577bf2eaL1-R5), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L1-R12), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L1-R11), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-5d2a9fbb1586f5058bfd77d20e281f359ce068ed333ccc4375ee0ef1961342cbL2-R2), [link](https://github.com/ant-design/ant-design/pull/44670/files?diff=unified&w=0#diff-add08763825dd36ecf1bf3482c1f2e331f8b6c9d83eff23a5fd55a2a25fd2e19L2-R5))

### CODE REVIEW

**Review by zombieJ — APPROVED** [review]

**Comment by afc163** [comment]
> 把 theme.useToken 替换成内部的 useInternalToken

这个是解决什么问题？

**Comment by li-jia-nan** [comment]
389733aa3e6ea9630137136b46fb3ff2

**Comment by li-jia-nan** [comment]
image

**Comment by afc163** [comment]
所以开发者无需关心？

**Comment by li-jia-nan** [comment]
> 所以开发者无需关心？

是的！

**Pull request merged**
