### PR TITLE
fix: fix Checkbox.Group type

### PR DESCRIPTION
**Pull request by crazyair**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/49058

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Optimize CheckboxGroup type constraints       |
| 🇨🇳 Chinese |     优化 CheckboxGroup 类型约束      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by zombieJ — APPROVED** [review]

**Comment by li-jia-nan** [comment]
breaking change

**Comment by li-jia-nan** [comment]
@crazyair @zombieJ 优化类型的时候不应该把已经 export 的类型删掉

**Comment by crazyair** [comment]
ts 对用户影响弱些。不会导致线上 bug

**Comment by li-jia-nan** [comment]
> ts 对用户影响弱些。不会导致线上 bug

- #50000

**Pull request merged**
