### PR TITLE
feat: Support zIndexContext to manage popup's zIndex in Pop-up container

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [X] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

- https://github.com/ant-design/ant-design/discussions/45154

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Support zIndexContext to manage popup's zIndex in Pop-up container |
| 🇨🇳 Chinese | 支持 zIndexContext 管理在弹出容器中的弹出层的 z-index |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at bceb2e2</samp>

This pull request adds a new custom hook `useZIndex` that returns the appropriate zIndex value and context value for different components that need to be stacked on top of each other. It applies the hook to various components, such as `Modal`, `Select`, `Dropdown`, `Popover`, `Tooltip`, and others, that use zIndex to control their visibility and positioning. It also adds a new demo file for nested modals that shows the use case and the effect of the hook. The purpose of this pull request is to solve the issue of zIndex conflicts and inconsistencies among various components and improve the consistency and compatibility of the zIndex management.

### <samp>🤖 Generated by Copilot at bceb2e2</samp>

*  Add the useZIndex hook to `components/_util/hooks/useZIndex.tsx`, which returns the appropriate zIndex value and context value for different components ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-2a902ec0f175b29920c300ea9a4023433a9a9720749632f5ac132e73694b1f71R1-R43))
*  Create and export a React context for zIndex values in `components/_util/zindexContext.ts`, which is used by the useZIndex hook and the components that consume it ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-0f41c7c229ef54fe09c53f519e935ab2de4480c2baf2379bf9ac78f82eef314cR1-R5))
*  Import and apply the useZIndex hook to the following components that need to get the correct zIndex value for their dropdown, popover, or panel elements: AutoComplete ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-c55203058d3a4064d8f52a5b4e7d7770153d215966d276d6814011d99268f76dR21), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-c55203058d3a4064d8f52a5b4e7d7770153d215966d276d6814011d99268f76dR132-R134), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-c55203058d3a4064d8f52a5b4e7d7770153d215966d276d6814011d99268f76dR142-R145)), Cascader ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804R37), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804R292-R294), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804R331-R334)), ColorPicker ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR35), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR234-R236), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR257)), RangePicker ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34R30), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34R115-R117), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34R157-R160)), DatePicker and TimePicker ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bR31), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bR142-R143), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bR188-R191)), Drawer ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-10ffbf23ed7075c38649dfd0776998a514a56e42e09a91306f89b25e67e07d30R8), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-10ffbf23ed7075c38649dfd0776998a514a56e42e09a91306f89b25e67e07d30R19), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-10ffbf23ed7075c38649dfd0776998a514a56e42e09a91306f89b25e67e07d30L146-R191)), Dropdown ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beR10), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beR16), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beL264-R295)), SubMenu ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-78ccc41cf5d14904062e19511837d0f4b6c9926376efc52facefc386c21bac84L1-R6), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-78ccc41cf5d14904062e19511837d0f4b6c9926376efc52facefc386c21bac84R70-R72), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-78ccc41cf5d14904062e19511837d0f4b6c9926376efc52facefc386c21bac84R83-R85)), Modal ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-a3edcd43b644d0539a67f65e68ba30d6acb77a12531a6a71d1e26a008a9d752cR10), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-a3edcd43b644d0539a67f65e68ba30d6acb77a12531a6a71d1e26a008a9d752cR18), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-a3edcd43b644d0539a67f65e68ba30d6acb77a12531a6a71d1e26a008a9d752cL116-R155)), Popconfirm ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-36878e30875e0d3ac3e1c9a9d6bebbcb023b8197cddd259fb7bc00976d795285L1-R7)), Popover ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-8255c20b0fc82fa28472ee578129241aab0b6c6d3f2cdafba5f74fa2614a92f0L1-R3), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-8255c20b0fc82fa28472ee578129241aab0b6c6d3f2cdafba5f74fa2614a92f0R53-R54)), Select ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0R10), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0L25-R27), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0R244-R246), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0R273-R276)), Tooltip ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966R14), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966R21), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L295-R303), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L321-R330))
*  Import and use the zIndexContext in the following components that need to provide the context zIndex value to their children components: Drawer ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-10ffbf23ed7075c38649dfd0776998a514a56e42e09a91306f89b25e67e07d30R19), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-10ffbf23ed7075c38649dfd0776998a514a56e42e09a91306f89b25e67e07d30L146-R191)), Dropdown ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beR16), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beL264-R295)), Modal ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-a3edcd43b644d0539a67f65e68ba30d6acb77a12531a6a71d1e26a008a9d752cR10), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-a3edcd43b644d0539a67f65e68ba30d6acb77a12531a6a71d1e26a008a9d752cL116-R155)), Tooltip ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966R21), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L295-R303), [link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L321-R330))
*  Add a condition to the Tooltip component to check if the zIndex value is injected from the Popover component, which is a special case that needs to use the original zIndex value instead of the one from the hook ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L295-R303))
*  Reorder the import statements in the Select component to follow the convention of importing React first, then other modules, then local files ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0L25-R27))
*  Import the React types and hooks from the 'react' module in the test file for the useZIndex hook ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5R1-R320))
*  Add a new demo file `components/modal/demo/nested.md` that shows an example of using nested modals with the useZIndex hook ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-fa6c244a20ffd0c68780b5a5579d6f78f9e344b64c9b764de2301a291e5a9f79R1-R7))
*  Add a new demo file `components/modal/demo/nested.tsx` that contains the code for the nested modals example ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-740d231aa0062e7ab64fb1c11b1a82f487d219f392ddcbf2be01b45a8538e1e6R1-R89))
*  Add a new code block to the 'Examples' section of the `components/modal/index.en-US.md` file that references the nested modals demo file ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-0868ee605478aef1b7a7e4508dce443964207f1dd966d82be9bf7e9b16a31aa5R38))
*  Add a new code block to the '代码演示' section of the `components/modal/index.zh-CN.md` file that references the nested modals demo file ([link](https://github.com/ant-design/ant-design/pull/45512/files?diff=unified&w=0#diff-7a204621cc9425007680c097ad01151df377979692bbc09eb2796025b85043f3R39))

### CODE REVIEW

**Comment by kiner-tang** [comment]
**注意：这个分支是多个 feature 分支的合集，合并时不要 squash，不要 squash，不要 squash**

**Comment by yoyo837** [comment]
> **注意：这个分支是多个 feature 分支的合集，合并时不要 squash，不要 squash，不要 squash**

我个人觉得这个分支合并到feature可以squash吧?

**Comment by yoyo837** [comment]
揉成一个得了

**Comment by kiner-tang** [comment]
> > **注意：这个分支是多个 feature 分支的合集，合并时不要 squash，不要 squash，不要 squash**
> 
> 我个人觉得这个分支合并到feature可以squash吧?

我们在进行 z-index 的相关改造时，由于涉及的组件过多，跟 @zombieJ  讨论的方案是基于 feature 分支建一个 refactor-z-index-context 作为本次改造的主分支，我们其他组件的改造都先往这个分支上合（合并时已经 squash），目前 refactor-z-index-context 中的提交记录为各个组件升级的最小单位，为了方便后期故障溯源和回滚等，觉得这个分支不需要 squash 比较好。因为这个分支本身就是作为临时 feature 的作用用来承载 z-index 改动的，所以普通直接合并过去就好。

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
