### PR TITLE
fix: RangePicker panel style & picker 2.4.0

### LINKED ISSUE #27798: [RangePicker] Missing border style when hover range starts from first day of a month
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker](https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker)

### Steps to reproduce
- Enter the link and find the date type RangePicker
- Select a start date
- Select last day of the month as end date
- Click the end date in input, then hover over next month

### What is expected?
The first cell of the hover range has left border style
4C39F6A7-466C-4512-A730-547E953ED162

### What is actually happening?
The first cell of the hover range miss left border style
282C9D94-99AD-4F9F-9232-D8B8936A6F84

| Environment | Info |
|---|---|
| antd | 4.8.3 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/27798

### 💡 Background and solution
close https://github.com/ant-design/ant-design/pull/27828

https://github.com/react-component/picker/pull/175

起初给 picker 加 start end 觉得有点消耗性能。
装到 antd 上，感觉有点卡顿，大家预览看一下，也许是我错觉。同时这样可以完美解决样式问题。

大家什么看法？或者 picker 再优化优化，我的想法如果卡顿解决不了，这个最好不加。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix the RangePicker panel interaction style.   |
| 🇨🇳 Chinese | 修复 RangePicker 面板交互样式。           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by xrkffgg** [comment]
snap 没更新报错先不管

**Comment by xrkffgg** [comment]
看预览比我本地好多了。。。本地有点卡。。。

**Comment by AlanCutFlim** [comment]
我这里不卡，好像没有问题

**Comment by yoyo837** [comment]
我这里不卡

**Comment by xrkffgg** [comment]
OK  那我完善一下

**Comment by yoyo837** [comment]
@AlanCutFlim 来验证这个修复感觉会比较全面 😂

**Comment by AlanCutFlim** [comment]
`ltr` 下我看着是没啥问题

**Comment by xrkffgg** [comment]
电脑好卡，看来得换 M1 了 😎

**Pull request merged**
