### PR TITLE
refactor(badge): 🛠 improve code

### PR DESCRIPTION
**Pull request by hengkx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by hengkx** [comment]
image
是又gai改什么东西了吗

**Comment by afc163** [comment]
https://github.com/react-component/field-form/commit/a7e3373051f73289dd7c1c8fc79be2129917b912#r39550472

**Comment by hengkx** [comment]
我还需要处理吗

**Comment by afc163** [comment]
覆盖率下降了，请检查。

**Comment by hengkx** [comment]
好奇怪 我没动过的 文件 也降低了

**Comment by afc163** [comment]
还好，只有一行：https://codecov.io/gh/ant-design/ant-design/pull/24601/diff?src=pr&el=tree#D2-50

**Comment by hengkx** [comment]
嗯嗯 刚才 没刷新过来 还有其它文件

**Pull request merged**
