### PR TITLE
refactor: locale files reference path

### PR DESCRIPTION
**Pull request by chunsch**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
- [issues: ReferenceError: window is not defined after upgrading from v4 to v5 in Next.js](https://github.com/ant-design/ant-design/issues/37893)
- [[RFC] Provide commonjs locale file in v5](https://github.com/ant-design/ant-design/discussions/38107)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | modify locale files reference path |
| 🇨🇳 Chinese | 调整语言包引用路径 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
@ant-design/tools@15.2.0-alpha.0 published

**Comment by MadCcc** [comment]
`locale-provider/` 下会引用 locale 做测试，如果 es 里的删掉了的话可能会影响 es 的测试结果

**Comment by chunsch** [comment]
@MadCcc 源码是没有删除 locale，应该没问题。但看到一些组件（如 Upload、Image 等），引用了 `locale/default` 或 `locale/en_US`。看来 es 还是得保留一个 `locale/default`，同时把 `locale/en_US` 改成 `locale/default`。

**Comment by chunsch** [comment]
@MadCcc 昨晚调整过程中，发现 `Calendar`、`DatePicker`、`TimePicker` 这三个组件的 `locale` 默认使用的 `en_US` ， `locale/default` 那边都有依赖，这个本身也是导入的  `en_US`。[目前构建 es 产物做了如下调整](https://github.com/ant-design/antd-tools/pull/260)：
1. 保留 `/**/locale/en_US`，让相关组件的 `locale`可正常引用
2. 忽略 `/locale-provider` 目录相关语言文件（都是从 `/locale` 目录引用）

现在打包后的 es 构建产物，相关组件的 `locale` 依赖，暂时没有发现其他问题了。

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
