### PR TITLE
fix: input-group display type

### PR DESCRIPTION
**Pull request by SpaNb4**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

**Problem**: When I use a screen reader and focus on inputs with css class ```input-group```, screen reader announces _"table"_ and then reads the content of the field.
image

I think this behavior might be confusing to some users.

**Solution**: I changed some styles from using ```display: table / table-cell``` to ```display: flex```.
Note:  

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Replace ```display: table``` with ```display: flex``` for input-group          |
| 🇨🇳 Chinese | 将 ```display: table``` 替换为 ```display: flex``` 用于输入组          |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
It will be a breaking change.

**Comment by mellis481** [comment]
@afc163 How is this a breaking change? No interfaces are affected.

How do you suggest this issue being addressed?  The issue being screen readers announcing input groups (eg. pre/post tab, search box, input group, etc.) as a table.

**Comment by zombieJ** [comment]
`Input.Group` is deprecated and removed in official site. Latest one is `Space.Compact` which use `flex` layout : )

**Comment by mellis481** [comment]
@afc163 @MadCcc @zombieJ Need your input here.

**Pull request closed without merging**
