### PR TITLE
chore: bump rc-checkbox to 3.0.0

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  -         |
| 🇨🇳 Chinese |  -         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
哇，小了这么多。

**Comment by li-jia-nan** [comment]
大佬需要更新一下 snap

**Comment by li-jia-nan** [comment]
不用了大佬，我更新了

**Comment by MadCcc** [comment]
ref 变了，去 feature 合了。

**Comment by li-jia-nan** [comment]
直接把 target branch 切换成 feature 就好了吧？

**Comment by yoyo837** [comment]
> 直接把 target branch 切换成 feature 就好了吧？

基线不同, 直接开新分支新PR最省力

**Pull request closed without merging**
