### PR TITLE
docs: ⚡️ add D2 forum promote link

### PR DESCRIPTION
**Pull request by zhangmengxue**
add d2 block

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ✔️ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
@ant-design/ant-design-collaborators 看看要不要搞一个免费的 headless CMS，这样以后不用提交重新部署了。

**Comment by Kermit-Xuan** [comment]
觉得可以在 gist 里面搞个 json 去存储。

**Comment by Rustin-Liu** [comment]
> 看看要不要搞一个免费的 headless CMS，这样以后不用提交重新部署了。

资持 👍

**Comment by afc163** [comment]
@Rustin-Liu 帮忙找找

**Comment by Rustin-Liu** [comment]
> @Rustin-Liu 帮忙找找

好 明天找找

**Comment by Rustin-Liu** [comment]
建了个issue跟踪，后面我调研后跟大家讨论： https://github.com/ant-design/ant-design/issues/27389

@ant-design/ant-design-collaborators

**Pull request merged**
