### PR TITLE
site: optimization site style

### PR DESCRIPTION
**Pull request by li-jia-nan**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | site: optimization site style |
| 🇨🇳 Chinese | site: optimization site style |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
这个解决什么问题？

**Comment by li-jia-nan** [comment]
只保留数字，不显示完整链接：

image

**Comment by li-jia-nan** [comment]
这里：

image

**Comment by MadCcc** [comment]
那不应该改的，github 对于其他仓库的 PR 也不会省略到只有 PR 号码

**Comment by li-jia-nan** [comment]
> 那不应该改的，github 对于其他仓库的 PR 也不会省略到只有 PR 号码

那我先关了

**Pull request closed without merging**
