### PR TITLE
chore: Merge master into feature

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [x] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered CHANGELOG.en-US.md](https://github.com/ant-design/ant-design/blob/master/CHANGELOG.en-US.md)
[View rendered CHANGELOG.zh-CN.md](https://github.com/ant-design/ant-design/blob/master/CHANGELOG.zh-CN.md)
[View rendered components/rate/demo/clear.md](https://github.com/ant-design/ant-design/blob/master/components/rate/demo/clear.md)
[View rendered components/table/demo/resizable-column.md](https://github.com/ant-design/ant-design/blob/master/components/table/demo/resizable-column.md)

### CODE REVIEW

**Comment by afc163** [comment]
Need approve

**Review by zombieJ — APPROVED** [review]

**Review by Chastrlove — COMMENTED** [review]
image
master分支，在FormItem包裹下的upload组件如果将listType设置为picture-card，按钮将无法点击

**Comment by Chastrlove** [comment]
@afc163

**Comment by zombieJ** [comment]
@Chastrlove 给个 issue 地址我看看~

**Comment by Chastrlove** [comment]
上面的截图是拉master分支，本地起的站点。。本来想开个codesandbox的，但里面只能选择3.20.5这个版本，master的代码选不到。
@zombieJ

**Pull request merged**
