### PR TITLE
fix: Table Expand Icon 在设置@font-size-base后错位

### LINKED ISSUE #24719: Table Expand Icon 在设置@font-size-base后错位
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/pensive-snowflake-p2eo5)

### Steps to reproduce
1. 设置@font-size-base为12px（在Sandbox中，手动设置了ant-table-row-expand-icon）
2. 图标错位

### What is expected?
图标不错位

### What is actually happening?
图标错位

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.1 |
| System | Win10 |
| Browser | Chrome 83.0.4103.61 |

---
Expand Icon的宽度和高度随@font-size-base变化，当设置为12px时，ant-table-row-expand-icon的高和宽均为14px：

.ant-table-row-expand-icon {
  height: 14px;
  width: 14px;
}

但是内部模拟 ，-的绝对定位并未随@font-size-base变化。

1. 可使Expand Icon的宽度和高度固定，固定为17px时不错位。
2. 或修改内部绝对定位

### PR DESCRIPTION
**Pull request by weiguozhu**
Expand Icon

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #24719

### 💡 Background and solution

1. Calculate expand-icon-height
2. Calculate top & left of before/after pseudo elements

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |  修复当font-size-base不等于14px时，Table组件的Expand Icon错位的问题  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
请面向用户填写一下Changelog

**Comment by afc163** [comment]
ci 挂了

**Comment by afc163** [comment]
ping

**Comment by afc163** [comment]
closing for no response

**Pull request closed without merging**
