### PR TITLE
<Input /> addon have spacing when in table

### PR DESCRIPTION
**Pull request by ystarlongzi**
[view demo](http://codepen.io/ystarlongzi/pen/qqyddN)

image

### CODE REVIEW

**Comment by afc163** [comment]
:+1:

**Comment by afc163** [comment]
English commit message should be better.

**Comment by ystarlongzi** [comment]
ok. Next time try to use English.

**Comment by afc163** [comment]
How about this time?

**Comment by ystarlongzi** [comment]
OK. When I got home, I will modify commit message.



发自网易邮箱大师
在2016年12月09日 21:51，偏右 写道:

How about this time?

**Pull request merged**
