### PR TITLE
feat: avatar.group support shape

### PR DESCRIPTION
**Pull request by zty42**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

###  This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

###  Changelog

| Language   | Changelog |
| ---------- | --------- |
|  English | Avatar.Group support `shape` |
|  Chinese | Avatar.Group 支持 `shape` |

###  Self-Check before Merge

 Please check all items below before review. 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by tianyuan233** [comment]
有人知道 test 这种报错怎么处理吗?
```
FAIL components/drawer/__tests__/demo.test.js
  ● renders ./components/drawer/demo/render-in-current.md correctly

    expect(received).toMatchSnapshot()

    Snapshot name: `renders ./components/drawer/demo/render-in-current.md correctly 1`

    - Snapshot  - 0
    + Received  + 1

    @@ -25,10 +25,11 @@
            style="width:0;height:0;overflow:hidden;outline:none;position:absolute"
            tabindex="0"
          />
          <div
            class="ant-drawer-content-wrapper"
    +       style="width:378px"
          />
          <div
            aria-hidden="true"
            data-sentinel="end"
            style="width:0;height:0;overflow:hidden;outline:none;position:absolute"

      105 |           ariaConvert(wrapper);
      106 |
    > 107 |           expect(wrapper).toMatchSnapshot();
          |                           ^
      108 |         }
      109 |
      110 |         MockDate.reset();

      at Object.toMatchSnapshot (tests/shared/demoTest.tsx:107:27)
```

**Comment by tianyuan233** [comment]
在我本地开发环境是好的
```js
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Tr
y running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
Test Suites: 295 passed, 295 total
Tests:       13 skipped, 3625 passed, 3638 total
Snapshots:   2193 passed, 2193 total
Time:        194.89 s
Ran all test suites.

```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/36772 修复了，重新 rebase 一下 feature

**Comment by tianyuan233** [comment]
> #36772 修复了，重新 rebase 一下 feature

我傻逼了 我在网页端 点了 Fetch Upstream 又把 master 合到 feat-avatar-shape 了

**Pull request closed without merging**
