### PR TITLE
fix(select): label with paragraph overflow tooltips error

### LINKED ISSUE #46636: Select嵌套Typography.Text 开启缩略，版本4 5 的表现不一样，v5展示不出来tooltip
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/typography-text-4-l78t3j?file=%2Fsrc%2FApp.tsx%3A30%2C69)

### Steps to reproduce

https://codesandbox.io/p/sandbox/typography-text-4-l78t3j?file=%2Fsrc%2FApp.tsx%3A30%2C69

https://codesandbox.io/p/sandbox/typography-text-5-qfv2nq?file=%2Fsrc%2FApp.tsx%3A10%2C19

### What is expected?

v5可以展示出来

### What is actually happening?

-

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | react |
| System | macos |
| Browser | chrome最新 |

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix: #46636 

### 💡 Background and solution

不确定是不是一个合理的解法，但是看起来没啥问题，需要看看 PR Preview~

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |       fix(select): label with paragraph overflow tooltips error    |
| 🇨🇳 Chinese |      修复 label 中 paragraph 的溢出提示不工作错误      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Wxh16144** [comment]
坏了，视觉回归怎么这么多 diff

**Comment by afc163** [comment]
看下 https://github.com/ant-design/ant-design/pull/46697#issuecomment-1871843640 ，有些变动是不符合预期的。

**Comment by Wxh16144** [comment]
2024/03/13 update，本地跑了一下视觉回归，感觉符合预期。 ci 再跑一遍看看  cc @vagusX

image

**Comment by Wxh16144** [comment]
Stubbornly holding my own opinion, I believe that this PR solution must be correct.

**Comment by Wxh16144** [comment]
很难搞，想用 inline-flex 一把梭，但是看起来还是很奇怪... 修不了


这是我的 debug 代码

```tsx

import React from 'react';
import { Cascader, Select, Space, TreeSelect, Typography, Segmented, Badge, Tag } from 'antd';

const options = [
  { value: 'long', label: <Typography>long, long, long piece of text</Typography> },
  { value: 'short', label: <Typography>short</Typography> },
  { value: 'normal', label: <div>normal</div> },
  {
    value: 'issue-46636',
    label: (
      <Typography.Text
        ellipsis={{
          tooltip: {
            overlay: 'https://github.com/ant-design/ant-design/issues/46636',
            overlayInnerStyle: {
              maxHeight: '50vh',
              maxWidth: '40vw',
            },
            mouseEnterDelay: 0.5,
          },
        }}
      >
        {String('Issue #46636 ').repeat(10)}
      </Typography.Text>
    ),
  },
  {
    value: 'badge',
    label: <Badge color='green' text="Hello" />,
  },
  {
    value: 'Tag',
    label: <Tag color="orange">orange</Tag>,
  },
];

const App: React.FC = () => {
  const values = options.map((item) => item.value);
  const [value, setValue] = React.useState(values.at(0));

  return (
    <>
      <Segmented options={values} onChange={setValue as any} />
      <br />
      <Space wrap key={value}>
        <Select defaultValue={value} style={{ width: 120 }} allowClear options={options} />

        <Select
          defaultValue={value}
          placeholder="Select a option"
          style={{ width: 120, height: 60 }}
          allowClear
          options={options}
        />

        <Select
          defaultValue={value}
          placeholder="Select a option"
          style={{ width: 120 }}
          allowClear
          options={options}
        />

        <Select
          defaultValue={[value]}
          mode="multiple"
          placeholder="Select a option"
          style={{ width: 120 }}
          allowClear
          options={options}
        />

        <Select
          mode="multiple"
          defaultValue={[value]}
          placeholder="Select a option"
          style={{ width: 120, height: 60 }}
          allowClear
          options={options}
        />

        <Cascader
          placeholder="Select a option"
          style={{ width: 120, height: 60 }}
          allowClear
          defaultValue={value as any}
          options={options}
        />

        <TreeSelect
          showSearch
          style={{ width: 120, height: 60 }}
          placeholder="Please select"
          allowClear
          popupMatchSelectWidth={false}
          treeDefaultExpandAll
          defaultValue={value}
          treeData={[
            {
              value: 'parent 1',
              title: 'parent 1',
              children: options,
            },
          ]}
        />
      </Space>
    </>
  );
};

export default App;


```

**Comment by Wxh16144** [comment]
Outdated... 

see: https://github.com/ant-design/ant-design/issues/46636#issuecomment-2225168584

**Pull request closed without merging**
