### PR TITLE
chore: Feature merge master

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [x] Branch merge
- [ ] Other (about what?)

ref https://github.com/ant-design/ant-design/issues/24401

-----
[View rendered components/select/index.en-US.md](https://github.com/ant-design/ant-design/blob/feature-merge-master/components/select/index.en-US.md)
[View rendered components/select/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/feature-merge-master/components/select/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
ci 挂了

**Comment by zombieJ** [comment]
嗯， coverage 我顺道修一下

**Comment by afc163** [comment]
好像 bundle size 也超了？

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/24407  这个 PR 改了文件名字没发现，结果 bisheng 挂了。

**Comment by afc163** [comment]
我擦，真的很难发现啊！

**Review by afc163 — APPROVED** [review]

**Comment by zombieJ** [comment]
找了一圈没找到为啥 ConfigProvider 会影响测试用例，这个我先合了。然后再开一个找原因。

**Comment by afc163** [comment]
bundle size 超了一点。

**Pull request merged**
