### PR TITLE
docs: code hide button sticky

### PR DESCRIPTION
**Pull request by linxianxi**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

收起固定在页面下方
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |     -      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by zombieJ — APPROVED** [review]

**Comment by MadCcc** [comment]
圆角要调整一下吧，两侧边框都露出来了

**Comment by linxianxi** [comment]
> 圆角要调整一下吧，两侧边框都露出来了

是说蓝色的？那好像底部只能改成没圆角的了

**Comment by linxianxi** [comment]
> 圆角要调整一下吧，两侧边框都露出来了

下面改成没圆角的话，没展开时也没有圆角了。现在这样感觉还能接受

**Comment by MadCcc** [comment]
image
这样观感确实还可以

**Pull request merged**
