### PR TITLE
site: add source code btn

### LINKED ISSUE #44319: add github source code link
图片

这个 import 和 View source code 挺好的，我们也可以加一个。

### PR DESCRIPTION
**Pull request by kovsu**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

close #44319

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Add a 'View Source Code' button and optimize the layout.    |
| 🇨🇳 Chinese |     添加查看源码按钮，并优化布局      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at ca522ad</samp>

Improved the documentation pages by adding a `ViewSourceCode` button and reorganizing the `ComponentChangelog` section. Simplified the code of `ComponentChangelog` and `Timeline` components.

### <samp>🤖 Generated by Copilot at ca522ad</samp>

*  Add `ViewSourceCode` component to render a button that links to the GitHub source code of the current component page ([link](https://github.com/ant-design/ant-design/pull/44610/files?diff=unified&w=0#diff-2c4f389cb4abf379d2eea689e3c81282328a5057624b3717b63c1f729986131cR1-R25))
* Import `ViewSourceCode` component in the `Content` slot component, which renders the main content of the documentation pages ([link](https://github.com/ant-design/ant-design/pull/44610/files?diff=unified&w=0#diff-1533ad458dddb5cacbf24062cc5d262ca684a57e2754bf4777f24f37411d5f82R15))
* Move `ComponentChangelog` component from the top to the bottom of the `Content` slot component, after the `API` component, to improve the readability and usability of the documentation pages ([link](https://github.com/ant-design/ant-design/pull/44610/files?diff=unified&w=0#diff-1533ad458dddb5cacbf24062cc5d262ca684a57e2754bf4777f24f37411d5f82L249))
* Wrap `ComponentChangelog` and `ViewSourceCode` components in a `Space` component, which adds some margin between them, and conditionally render `ViewSourceCode` component only for component pages that are not the overview page ([link](https://github.com/ant-design/ant-design/pull/44610/files?diff=unified&w=0#diff-1533ad458dddb5cacbf24062cc5d262ca684a57e2754bf4777f24f37411d5f82R278-R281))
* Remove `history` style from the `ComponentChangelog` component, as it was no longer needed after moving the changelog to the bottom of the page ([link](https://github.com/ant-design/ant-design/pull/44610/files?diff=unified&w=0#diff-baac8f9e495ebe8f121c468c0b4576693b0f2998d1c333d48059c5ef385692c1L11-L16))
* Remove `className` prop from the `Timeline` component, as it was using the `history` style that was removed ([link](https://github.com/ant-design/ant-design/pull/44610/files?diff=unified&w=0#diff-baac8f9e495ebe8f121c468c0b4576693b0f2998d1c333d48059c5ef385692c1L161))

### CODE REVIEW

**Comment by li-jia-nan** [comment]
这布局有点丑……

**Comment by kovsu** [comment]
> 这布局有点丑……

等下重新弄一下。

**Comment by afc163** [comment]
关联一下原始 issue？

**Comment by kovsu** [comment]
@afc163 好的

**Comment by kovsu** [comment]
@li-jia-nan 没地方放这个按钮，想了好久感觉缩小点放到这个标题下也还能看。

**Comment by afc163** [comment]
可以参考一下 https://procomponents.ant.design/components/layout/ 的 UI 风格。

**Pull request closed without merging**
