### PR TITLE
demo: update Select demo

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

05ff7b2b2bc42952471574eff9da5ca

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | demo: update Select demo |
| 🇨🇳 Chinese | demo: update Select demo |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Wxh16144** [comment]
感觉有点偏业务逻辑，不必放入组件 dmeo 中吧🤔

**Comment by li-jia-nan** [comment]
> 感觉有点偏业务逻辑，不必放入组件 dmeo 中吧🤔

感觉是挺常见的一个场景呢，@MadCcc @zombieJ 大佬们怎么看？

**Comment by MadCcc** [comment]
demo 用来展示 API 的用法的，复杂用例感觉是没必要都写上去

**Comment by li-jia-nan** [comment]
> demo 用来展示 API 的用法的，复杂用例感觉是没必要都写上去

OK，先 close 了

**Comment by Wxh16144** [comment]
你看看我这个 demo 怎么样, 是不是更像业务了 🤔

```tsx
import { Select, Space } from 'antd';
import * as React from 'react';

const SELECT_ACTIONS = {
  SELECT_OPTION: 'SELECT_OPTION',
  RESET_OPTIONS: 'RESET_OPTIONS',
};

const selectReducer = (state, action) => {
  switch (action.type) {
    case SELECT_ACTIONS.SELECT_OPTION:
      return {
        ...state,
        [action.selectId]: action.payload,
      };
    case SELECT_ACTIONS.RESET_OPTIONS:
      return {};
    default:
      return state;
  }
};

interface Config {
  disableSelected?: boolean;
  hideSelected?: boolean;
}

function useMultiSelects(initialOptions) {
  const [state, dispatch] = React.useReducer(selectReducer, {});

  const registerSelect = (selectId, config: Config = {}) => {
    const { disableSelected, hideSelected } = config;

    const selectedValues = new Set(
      Object.entries(state)
        .reduce((acc, [key, value]) => {
          if (key !== selectId && value) {
            acc.push(value);
          }
          return acc;
        }, [])
        .flat(),
    );

    const realOptions = (function () {
      if (disableSelected) {
        return initialOptions.map((option) => ({
          ...option,
          disabled: selectedValues.has(option.value),
        }));
      }
      if (hideSelected) {
        return initialOptions.filter((option) => {
          return !selectedValues.has(option.value);
        });
      }
      return initialOptions;
    })();

    return {
      value: state[selectId],
      onChange: (selected) => {
        dispatch({
          type: SELECT_ACTIONS.SELECT_OPTION,
          selectId,
          payload: selected,
        });
      },
      options: realOptions,
    };
  };

  const resetOptions = () => {
    dispatch({
      type: SELECT_ACTIONS.RESET_OPTIONS,
    });
  };

  return [
    state,
    {
      registerSelect,
      resetOptions,
    },
  ] as const;
}

export interface IndexProps {
  slogan?: React.ReactNode;
}

function Index(props: React.PropsWithChildren<IndexProps>) {
  const { children } = props;

  const [state, { registerSelect }] = useMultiSelects([
    { value: 'Ava Swift', label: <span>Ava Swift</span> },
    { value: 'Cole Reed', label: <span>Cole Reed</span> },
    { value: 'Mia Blake', label: <span>Mia Blake</span> },
    { value: 'Jake Stone', label: <span>Jake Stone</span> },
    { value: 'Lily Lane', label: <span>Lily Lane</span> },
    { value: 'Ryan Chase', label: <span>Ryan Chase</span> },
    { value: 'Zoe Fox', label: <span>Zoe Fox</span> },
    { value: 'Alex Grey', label: <span>Alex Grey</span> },
    { value: 'Elle Blair', label: <span>Elle Blair</span> },
  ]);

  globalThis.console.log({
    state,
  });

  return (
    <div>
      <pre>{JSON.stringify(state, null, 2)}</pre>
      <Space>
        <Select
          {...registerSelect('team-leader', { disableSelected: true })}
          style={{ width: 180 }}
          allowClear
        />
        <Select
          {...registerSelect('teacher', { hideSelected: true })}
          style={{ width: 180 }}
          allowClear
        />
        <Select
          {...registerSelect('director', { hideSelected: true })}
          style={{ width: 180 }}
          allowClear
        />
        <Select
          {...registerSelect('student', { disableSelected: true })}
          style={{ width: 180 }}
          mode="multiple"
        />
      </Space>
    </div>
  );
}

export default Index;

```

**Comment by li-jia-nan** [comment]
> 你看看我这个 demo 怎么样, 是不是更像业务了 🤔

纯业务代码了属于是

**Comment by Wxh16144** [comment]
> > 你看看我这个 demo 怎么样, 是不是更像业务了 🤔
> 
> 纯业务代码了属于是

哈哈哈，但是和你的需求实现应该是匹配的

**Pull request closed without merging**
