### PR TITLE
Fix Upload #17397

### LINKED ISSUE #17397: Upload component allows multiple upload when `multiple` is set to false
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/agYJxE?editors=0010](https://codepen.io/anon/pen/agYJxE?editors=0010)

### Steps to reproduce
1. in props, set `multiple` to `false`
2. drag and drop multiples onto the Upload zone
3. uploaded successfully

### What is expected?
There should be a validation (like a warning message) for the single upload when user is trying to upload multiple files

### What is actually happening?
Users can successfully upload multiple files when `multiple` is set to `false`

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.5 |
| System | Windows |
| Browser | Chrome |

---
It will be nice to add a validation for the `onFileDrop` function to detect whether the `fileList` length is not greater than 1 when the `multiple` props is set to `false`

### PR DESCRIPTION
**Pull request by susiwen8**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

Check fileList length before upload when multiple value is false.

Close #17397

### CODE REVIEW

**Comment by afc163** [comment]
来个用例。

**Comment by susiwen8** [comment]
#17397

**Comment by afc163** [comment]
用例和修复的例子不是一回事。

**Comment by InsaLili** [comment]
There are some occasions we only allow user to upload a single file (ex. upload the identity card).  The current Dragger component doesn't provide a validation for that. Since we already have this `multiple` props, it can be a good candidate for being a validator for single/multiple uploads, which is also the goal this PR can achieve. 

We've also tried to only accept a single file through Dragger on our end, but it's hard to prevent the animation that showing the uploaded file list. Really looking forward to seeing this be resolved in antd.

**Comment by yoyo837** [comment]
添加个test case 抓紧合并 @susiwen8

**Comment by yoyo837** [comment]
@InsaLili This PR is waiting for add a test case.

**Comment by zombieJ** [comment]
ping @susiwen8

**Comment by yoyo837** [comment]
直接另起PR 吧，估计村里断网了... 🙃

**Comment by afc163** [comment]
ping @susiwen8

**Comment by zombieJ** [comment]
我 fork 一下好了 🚜

**Pull request closed without merging**
