### PR TITLE
Added Bulgarian translation

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Add Bulgarian bg_BG translation.

Translations for rc-pagination and calendar are added as pull requests in their repos.

### CODE REVIEW

**Comment by benjycui** [comment]
CI failed.

**Comment by dimitrov-adrian** [comment]
Yeah, that's because rc-pagination and rc-calendar. After the merge it should pass.

**Comment by benjycui** [comment]
Even lint is failed https://travis-ci.org/ant-design/ant-design/jobs/237504823

And try to rebase.

**Comment by benjycui** [comment]
Waiting for rc-pagination.

**Comment by benjycui** [comment]
4e75347

**Pull request merged**
