### PR TITLE
fix: hidden arrow when collapsed

### PR DESCRIPTION
**Pull request by nuintun**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

修复菜单折叠时鼠标滑过会显示箭头的问题，否者设置 Icon 大字体时会出现遮挡。

企业微信截图_20210525111532

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
如何重现？

**Comment by nuintun** [comment]
@afc163 

https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed

收缩鼠标滑上带子菜单的选项，这里不会重叠，但 less vars 自定义大字体后就出现了！

**Comment by afc163** [comment]
> 但 less vars 自定义大图标后就出现了！

怎么定义的？

**Comment by nuintun** [comment]
@afc163 

```less
@menu-icon-size: 20px;
@menu-icon-size-lg: 20px;
```

**Comment by afc163** [comment]
图片

还是无法重现。

**Comment by afc163** [comment]
先关了，提供重现后再说。

**Pull request closed without merging**
