### PR TITLE
chore: migrate to vitest

### PR DESCRIPTION
**Pull request by Dunqing**
This reverts commit 7322aa6f5f99425635442ddb2439c05339247c80.

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [x] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 80a4b45</samp>

This pull request migrates the test framework from `jest` to `vitest`, which is a faster and lighter alternative. It updates the mock files, the eslint configuration, and the test commands to use `vitest` instead of `jest`. It also deletes some files and folders that are no longer needed for testing.

### <samp>🤖 Generated by Copilot at 80a4b45</samp>

*  Migrate the test framework from jest to vitest ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-a0fdacd2ade87c5238dde44378f574f7e123e669acdf8b740878b14b33b20275L24), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L6-R6), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L15), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L162-R172), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L189-R203), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L194-R194), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L350-R350), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-ffa4c0fb47c4578613f9ee25ab4b2dc2fb2bb33afec257e5844e01689f1b621e), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-6dc98a965c38d41d2ecabb09c6a6842bef943e69bcd6da63d9371efa466f2ca4), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-eb8a53657741a837a16095ba45d5db1c2fc2bc2a687b774221ed85f137fbdd9c), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-b932d97ccda3e738a77a69c1a081df264e7504792c95345e6b03c6e3aeb1668e))
  * Replace the jest plugin and rules with the vitest plugin and rules in the `.eslintrc.js` file ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L6-R6), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L189-R203))
  * Remove the `jest: true` line from the `.eslintrc.js` file to avoid linting errors related to jest ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L15))
  * Remove the `--maxWorkers=2` option from the `npm test` commands in the `.github/workflows/test.yml` file to improve the test performance and speed ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L194-R194), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L350-R350))
  * Delete the `.jest.image.js`, `.jest.js`, `.jest.node.js`, and `.jest.site.js` files, which were configuration files for jest ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-ffa4c0fb47c4578613f9ee25ab4b2dc2fb2bb33afec257e5844e01689f1b621e), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-6dc98a965c38d41d2ecabb09c6a6842bef943e69bcd6da63d9371efa466f2ca4), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-eb8a53657741a837a16095ba45d5db1c2fc2bc2a687b774221ed85f137fbdd9c), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-b932d97ccda3e738a77a69c1a081df264e7504792c95345e6b03c6e3aeb1668e))
  * Remove the `jest-stare` folder from the `.eslintignore` file, which was a tool for generating reports from jest tests ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-a0fdacd2ade87c5238dde44378f574f7e123e669acdf8b740878b14b33b20275L24))
  * Add some patterns to the `ignorePatterns` array in the `.eslintrc.js` file to exclude some files that are not relevant for linting, such as mock files and vitest configuration files ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L162-R172))
* Move the mock files to the `__mocks__` folder in the root directory, following the convention of vitest ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-cfe52d20f6f637b021228fd62ecaba912f32cb9953acdde6b25335cbae222a33L2-R8), [link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-fc55b9eb351c61cd879608fdfce96f8329eee71361512a9228ab01fa5ebbd40f))
  * Rename the `tests/__mocks__/@rc-component/trigger.tsx` file to `__mocks__/@rc-component/trigger.tsx` ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-cfe52d20f6f637b021228fd62ecaba912f32cb9953acdde6b25335cbae222a33L2-R8))
  * Rename the `tests/__mocks__/copy-to-clipboard.ts` file to `__mocks__/copy-to-clipboard.ts` ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-fc55b9eb351c61cd879608fdfce96f8329eee71361512a9228ab01fa5ebbd40f))
* Use the `globalThis` object instead of the type-casted `global` object in the `ForwardTrigger` function in the `__mocks__/@rc-component/trigger.tsx` file, which is more reliable and consistent ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-cfe52d20f6f637b021228fd62ecaba912f32cb9953acdde6b25335cbae222a33L13-R14))
* Sort the plugins array and add a line break in the `.eslintrc.js` file, which improves the code style and readability ([link](https://github.com/ant-design/ant-design/pull/44246/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L28-R35))

### CODE REVIEW

**Comment by SnowingFox** [comment]
Could you provide a basic framework and have the community migrate together to complete it

**Comment by Dunqing** [comment]
> Could you provide a basic framework and have the community migrate together to complete it

We tried to migrate to `vitest` and merge a few months ago, but it didn't work on some low-performance computers so we revert.

This time we're trying again the migration because `vitest` released the feature [experimentalVmThreads](https://vitest.dev/config/#experimentalvmthreads)(but not yet enabled) so we want to try again if it works well on low-performance computers.

All tests have passed locally so far, just need the CI to pass as well. the reason for the CI failure looks like it's due to a different react version. If you're interested you can help out with that.

**Comment by SnowingFox** [comment]
i will try to fix it.

**Review by kiner-tang — COMMENTED** [review]
这个不先在 feature 试运行一段时间么，直接合到 master 会不会有点冒险

**Comment by afc163** [comment]
大量冲突，重发 PR 吧

**Pull request closed without merging**
