### PR TITLE
update reset styles

### LINKED ISSUE #4331: Global CSS included with component CSS import
Thanks for this great library!

I tried to use `babel-plugin-import` to do modular CSS imports, but along with the css for an individual component, there is a lot of global css being imported that interferes with my existing styles. Is it possible to import the CSS for an individual component without global CSS being included?

Thanks!

### LINKED ISSUE #6162: Default typography of Ant Design is not so well
### Version
2.10.0

### Environment
Windows 7, Chrome 57.0.2987.133 (64-bit)

### Reproduction link
[http://codepen.io/onlyice/pen/oWMXad](http://codepen.io/onlyice/pen/oWMXad)

### Steps to reproduce
See the Codepen link above.

看 Codepen 的链接。

### What is expected?
Should have similar rendering like [bootstrap](http://getbootstrap.com/css/#type) or [typo.css](https://typo.sofi.sh/).

能有类似 [Bootstrap](http://getbootstrap.com/css/#type) 或 [typo.css](https://typo.sofi.sh/) 的展示效果。

### What is actually happening?
The space between headers, paragraphs are not optimal. And the `list-style` of `<li>` is set to `none` that cause the dot / number is not displaying.

Headers、各个 `<p>` 之间间距不佳；对于 `<ul>` `<ol>` 的 `<li>`，前面的小圆点和数字直接没有了。

### PR DESCRIPTION
**Pull request by afc163**
close #4331

~~A lot of changes. Reset styles is not global after 3.0, you have to import it individually.~~

---

Reverted the `reset.less` idea. It will be a break change. The solution would be:

- [x] Remove annoying reset styles like `margin:0;padding:0;` for every tags.
- [x] better typography to resolve #6162
- [x] Remove some unneccessary reset styles like `label` in Form.

### CODE REVIEW

**Comment by benjycui** [comment]
And this will be a breaking change which should be noted in upgrade instructions.

**Comment by afc163** [comment]
Make css usage complex...

**Comment by benjycui** [comment]
> Remove annoying reset styles like margin:0;padding:0; for every tags.

But it will break current systems' styles.. which had depended on these reset rules..

**Comment by afc163** [comment]
I will document it in upgrade note.

**Comment by AleksandrZhukov** [comment]
@afc163 These changes make a lot of problems for using global css styles with the same specificity. For example it is impossible to set margin via global class that has same specificity `.mb-10 { margin-bottom: 10px }` 
image
Is it possible to avoid of reseting such values? 
Thanks in advance!

**Pull request merged**
