### PR TITLE
chore: bump trigger to move click to mouseDown

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Adjust the closing trigger of Tour, Dropdown, Menu, Tabs, Mentions, Picker, Select, TreeSelect, Cascader, Tooltip, and Popover pop-ups from `click` to `mouseDown` to uniformly solve some event timing issues related to pop-up interactions.      |
| 🇨🇳 Chinese |    调整 Tour、Dropdown、Menu、Tabs、Mentions、Picker、Select、TreeSelect、Cascader、Tooltip、Popover 弹层点击外部的关闭时机，从 `click` 调整至 `mouseDown` 以统一解决一些与弹窗相关交互中，事件时序问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — DISMISSED** [review]

**Comment by yoyo837** [comment]
Tour 的minor 还有其他编号，log没写

**Comment by zombieJ** [comment]
> Tour 的minor 还有其他变化，log没写

这个在 feature 里，patch 版本里不透出。trigger 这个太底层只能一次性全部提掉，比较尴尬。

**Review by li-jia-nan — DISMISSED** [review]

**Review by kiner-tang — DISMISSED** [review]

**Review by li-jia-nan — DISMISSED** [review]

**Review by li-jia-nan — DISMISSED** [review]

**Review by li-jia-nan — APPROVED** [review]

**Comment by nanxiaobei** [comment]
从此次更新后，在 Popover 里就不能使用 [emoji-mart ](https://github.com/missive/emoji-mart) 了

**Comment by li-jia-nan** [comment]
> 从此次更新后，在 Popover 里就不能使用 [emoji-mart ](https://github.com/missive/emoji-mart) 了

具体什么问题？给个重现吗？

**Comment by jueinin** [comment]
@li-jia-nan 我也复现了这个Bug，popover里点emoji会自动触发close事件

**Pull request merged**
