### PR TITLE
Make Modal closeIcon customizable

### PR DESCRIPTION
**Pull request by MrBr**
### 🤔 This is a ...

- [x] New feature

### 👻 What's the background?

Just want to be able to customize Modal Close icon.

### 💡 Solution

Added `closeIcon` prop to Modal. It's basically just a proxy prop.

### 📝 Changelog

- English Changelog:
No breaking changes!
Modal has new `closeIcon` prop.

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Could you add it to feature branch?

**Comment by MrBr** [comment]
Updated.

**Review by abenhamdine — CHANGES_REQUESTED** [review]
Api docs update is missing

**Comment by afc163** [comment]
image

**Comment by afc163** [comment]
conflicted

**Comment by afc163** [comment]
Supported in #18309

**Pull request closed without merging**
