### PR TITLE
Bump up rc-notification version to 3.1.0

### PR DESCRIPTION
**Pull request by yevhen-hryhorevskyi**
Bump up `rc-notification` version to 3.1.0 which supports notification updates by key.

### CODE REVIEW

**Comment by yesmeck** [comment]
Please PR to `feature-3.5.0`

**Review by afc163 — CHANGES_REQUESTED** [review]
Mixed other commits.

**Comment by PengJiyuan** [comment]
I'm waiting for this pr merged ...

**Comment by yevhen-hryhorevskyi** [comment]
Created a new one [PR](https://github.com/ant-design/ant-design/pull/10161) to remove mixed commits.

**Pull request closed without merging**
