### PR TITLE
not render content until walk is done

### PR DESCRIPTION
**Pull request by tonny008**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ..

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/37998

### 💡 Background and solution

Ellipse shows expanded content before collapse causing flick

ellipse should show collapsed at first time without showing the expanded content

not render content until walk is done

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix Ellipse show expanded content causing flick      |
| 🇨🇳 Chinese |     修复  Ellipse Render 时先显示展开的内容导致的闪烁     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
@MadCcc Help to check this.

**Comment by MadCcc** [comment]
Please provide a test case for this change.

**Comment by afc163** [comment]
@tonny008 ping

**Comment by afc163** [comment]
@tonny008 ping

**Comment by afc163** [comment]
Could you add a test case?

**Comment by afc163** [comment]
Please rebase master to rerun ci .

**Comment by vaakian** [comment]
any progress?

**Comment by zombieJ** [comment]
Sorry for delay. But it's must have since no render any thing for the mount will cause SSR return empty content which is not friendly for SEO.
So the full content render is by design.

**Pull request closed without merging**
