### PR TITLE
fix: Descriptions.Item ts define

### PR DESCRIPTION
**Pull request by Nokecy**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
不是的  `ReactNode` 包括了很多东西

**Comment by Nokecy** [comment]
children 是string typescript 就会报错了

**Comment by ztplz** [comment]
太广了  我猜设计的就是只接收 string number element之类的作为children  `ReactChild`吧  
@chenshuai2144

**Comment by chenshuai2144** [comment]
@ztplz   string 都不行就让我很难受
其实都支持的。所以我放开了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/pull/17049

**Pull request closed without merging**
