### PR TITLE
Added support for Romanian locale

### PR DESCRIPTION
**Pull request by stefy**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 💡 Background and solution

1. Added Romanian locale support

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Added Romanian locale support   |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered docs/react/i18n.en-US.md](https://github.com/stefy/ant-design/blob/master/docs/react/i18n.en-US.md)
[View rendered docs/react/i18n.zh-CN.md](https://github.com/stefy/ant-design/blob/master/docs/react/i18n.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
feature branch

**Review by afc163 — CHANGES_REQUESTED** [review]
feature branch please

**Comment by stefy** [comment]
> feature branch please

Changed the base branch from `master` to `feature`.

**Comment by afc163** [comment]
Please keep commit history clean.

**Comment by stefy** [comment]
@afc163 , thanks for your comments! I'm kind of new to this so what do you mean by 'Please keep commit history clean?'? I tried to find in the docs if there are some conventions for naming the commits but could not find anything.

In the meantime I amended my commit and added `ro_RO.tsx` to the `locale-provider` component.

Thank you!

**Comment by afc163** [comment]
image

**Comment by stefy** [comment]
@afc163 , this is because I edited the PR to merge into `feature` branch, right? Is there a way for me to create a branch on this repository?

Or should I have been made the changes on a separate branch on my fork? 

Thank you!

**Comment by afc163** [comment]
- If you need to send PR to master, you should check out new branch from master.
- If you need to send PR to feature, you should check out new branch from feature.
- Don't check out branch from master and send it to feature, it will mix those commits already existed in master.

**Comment by stefy** [comment]
Oh, right. Got it now. So I'm guessing I should close this PR and create a new one once I make the changes.

Thanks for the clarification!

**Pull request closed without merging**
