### PR TITLE
feat: add Modal.confirm options: footer to hide or modify

### PR DESCRIPTION
**Pull request by moonrailgun**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Add footer option into `Modal.confirm`

### 💡 Background and solution

I just wanna hide operation button in `Modal.confirm`

by the way `maskClosable` default value is incorrect in api docs

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  add footer option into `Modal.confirm`  |
| 🇨🇳 Chinese | `Modal.confirm` 增加了 footer 属性 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
`Modal.confirm` without footer and comfirm buttons won't be a "comfirm" dialog, please use `<Modal />` instead of comfirm function.

**Comment by moonrailgun** [comment]
> `Modal.confirm` without footer and comfirm buttons won't be a "comfirm" dialog, please use `<Modal />` instead of comfirm function.

@afc163 Thanks for your reply,

I know its not a `confirm` but `<Modal />` allow to modify footer...

Why API must be have a footer?

**Comment by Serkey** [comment]
> `Modal.confirm` without footer and comfirm buttons won't be a "comfirm" dialog, please use `<Modal />` instead of comfirm function.

but sometimes I use the Modal.info(), the footer is always shown too, use <Modal /> is an option, but it add the complexity of  my code, life will be much easier if API can hide footer too
@afc163

**Comment by SightStudio** [comment]
i tried to figure out this work... and add this comment for record.

this feature added in
https://github.com/ant-design/ant-design/pull/39048

**Pull request closed without merging**
