### PR TITLE
feat: 优化 gitee 初始化

### PR DESCRIPTION
**Pull request by crazyair**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Optimize gitee initialization    |
| 🇨🇳 Chinese |     优化 gitee 初始化      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
datepicker的 UI 咋不一样了. 🤔

**Comment by crazyair** [comment]
isZhCN 还是二次render 才知道

**Comment by crazyair** [comment]
先合了吧，我看 Preview 还是会闪一下，但是本地不会了，不知道是不是 Preview 版本对不对

**Comment by afc163** [comment]
#32163 重复了

**Pull request closed without merging**
