### PR TITLE
docs: fix getFieldDecorator param

### PR DESCRIPTION
**Pull request by zenonux**
api更新，demo里面的api没有更新

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by afc163** [comment]
看着怪怪的。

**Comment by yesmeck** [comment]
这个 normalize 应该是一开始就写错了？而不是 API 的变化。

**Comment by benjycui** [comment]
这种情况是应该用 `getValueFromEvent` 的

**Comment by afc163** [comment]
`getValueFromEvent: this.normFile`

Is `normFile` should changed to another name?

**Pull request merged**
