### PR TITLE
style: fix Avatar src Image style

### LINKED ISSUE #27690: Set Avatar `size` is not working
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/skeleton-fyltt)

### Steps to reproduce
When I use `<Avatar shape="circle" size={32} src={profileImg} />`,  
then I see the `<span />` is styled `width` and `height` are `32px`.
But the `` tag not

### What is expected?
Avatar size should be set

### What is actually happening?
Avatar size cannot set

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | React |
| System | CodeSandbox |
| Browser | Chrome 86.0.4240.183 |

### PR DESCRIPTION
**Pull request by hengkx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   fix Avatar src Image style.        |
| 🇨🇳 Chinese |   修复 Avatar src 为 Image 时的样式。        |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://ant.design/components/avatar-cn/#components-avatar-demo-type

这个例子看着是好的，是哪里出了问题？

**Comment by hengkx** [comment]
这个例子 没有设置 size number吧

**Comment by afc163** [comment]
有的 
image

**Comment by afc163** [comment]
另外右边的头像有点偏下，顺手一起修一下吧。

image

**Comment by hengkx** [comment]
image
这个里面 不是图片

**Comment by afc163** [comment]
图片的也没问题，你可以试试。

**Comment by hengkx** [comment]
https://codesandbox.io/s/skeleton-forked-m84ii?file=/src/index.js

**Comment by hengkx** [comment]
他没 加样式。。。。。。。。。。。。。

**Comment by afc163** [comment]
那就修一下 https://github.com/ant-design/ant-design/pull/27691#issuecomment-725214915 吧。。

**Comment by afc163** [comment]
PR 内容改改

**Comment by hengkx** [comment]
> PR 内容改改

改过了🤣

**Comment by afc163** [comment]
和 #27690 没关系了。

**Comment by afc163** [comment]
#27690 去回复一下直接关掉吧。

**Comment by hengkx** [comment]
done

**Pull request merged**
