### PR TITLE
fix(descriptions): text style elp

### PR DESCRIPTION
**Pull request by coding-ice**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/49704

### 📝 Changelog

- Use a developer-oriented tone and narrative style.
- Describe the user's first-hand experience of the issue and its impact on developers, rather than your solution approach.
- Refer to: ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   overflow hidden        |
| 🇨🇳 Chinese | 溢出隐藏          |

### CODE REVIEW

**Comment by afc163** [comment]
最好不要默认加 overflow hidden。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/49704 这个问题是由于用户用了长连续文本，antd 的方案是默认不解决，让用户自定义 overflow 或 break word 的样式。

**Comment by jddxf** [comment]
> #49704 这个问题是由于用户用了长连续文本，antd 的方案是默认不解决，让用户自定义 overflow 或 break word 的样式。

没太理解，这个问题的 demo 里不管是 `.ant-descriptions-item-content` 还是 `.ant-typography` 都自带 `word-break: break-word;` 的样式。根本原因还是没能保证 `.ant-descriptions-item-content` 的宽度为  `.ant-descriptions-item-container` 除去 `.ant-descriptions-item-label` 的剩余宽度吧。

**Comment by coding-ice** [comment]
大佬，我看又`open`了，那还是默认给个吗？

**Comment by afc163** [comment]
@coding-ice 改成默认把 min-width: 0 加上试试，`overflow: hidden` 有副作用的。

**Pull request closed without merging**
