### PR TITLE
feat: Form & ConfigProvider support component size

### LINKED ISSUE #17570: 在ConfigProvider或Form中增加对输入组件size的配置
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
很多输入组件都有 size 属性，large default small，但是要一个一个去配置，希望可以有统一配置的地方
也有一些组件没有size属性，希望4.0中统一下

### What does the proposed API look like?
```jsx
<Form size="small" />  
<ConfigProvider size="small" />
```

### LINKED ISSUE #20174: 4.0 Form support top level config
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Support:
* disabled
* ~readOnly~
* size

### What does the proposed API look like?
```tsx
<Form size="large" readOnly disabled>
  <Form.Item>
    ...
  </Form.Item>
</Form>
```

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #17570
close #20174

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Form & ConfigProvider support component size       |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/config-provider/demo/size.md](https://github.com/ant-design/ant-design/blob/form-sizing/components/config-provider/demo/size.md)
[View rendered components/config-provider/index.en-US.md](https://github.com/ant-design/ant-design/blob/form-sizing/components/config-provider/index.en-US.md)
[View rendered components/config-provider/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/form-sizing/components/config-provider/index.zh-CN.md)
[View rendered components/form/demo/size.md](https://github.com/ant-design/ant-design/blob/form-sizing/components/form/demo/size.md)
[View rendered components/form/index.en-US.md](https://github.com/ant-design/ant-design/blob/form-sizing/components/form/index.en-US.md)
[View rendered components/form/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/form-sizing/components/form/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
感觉会和 https://github.com/ant-design/ant-design/pull/19380 有大量冲突，最好把 https://github.com/ant-design/ant-design/pull/19380 合并了再由我们自己在这个 PR 里解决冲突。

**Comment by zombieJ** [comment]
Merge `4.0-prepare`. Please help to check.

**Comment by afc163** [comment]
Table 和 Card 要不要支持一下，不过要注意这两默认大小情况不太一样。

**Comment by zombieJ** [comment]
Card 可以，和 Switch 一样只有 `default` 和 `small`。Table 的话比较蛋疼，默认就是 `large`。如果是这样的话，那 `componentSize` 就不是 `large` | `default` | `small`。而是 `large` | 'middle' | 'small'。默认什么都不填，跟着组件自己走。如果设置了就跟着设置走，即 `size='middle'` 的时候，设置 Table 也为 `middle`。这样如何？

**Comment by afc163** [comment]
> 如果设置了就跟着设置走，即 size='middle' 的时候，设置 Table 也为 middle。这样如何？

是这样的。

**Comment by afc163** [comment]
will close #20174 too

**Review by afc163 — APPROVED** [review]

**Pull request merged**
