### PR TITLE
fix: cascader typescript definition

### PR DESCRIPTION
**Pull request by linxianxi**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   fix Cascader typescript definition       |
| 🇨🇳 Chinese |  修改 Cascader typescript        |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
解决什么问题，能加个用例么

**Comment by linxianxi** [comment]
就是我对 Cascader 进行封装的时候 CascaderProps 必须要有一个泛型，这样修正后可以不需要，然后把 any 改掉了。

**Comment by afc163** [comment]
加个用例

**Comment by afc163** [comment]
1. 冲突了
2. 加个 TS 的用例

**Pull request closed without merging**
