### PR TITLE
Resolved type name collisions

### PR DESCRIPTION
**Pull request by GauravV-02**
#8478
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by yesmeck** [comment]
I think you should rebase master.

**Comment by GauravV-02** [comment]
I did rebase master and when i tried to push the branch, git displayed everything is up-to-date
capture1

**Comment by yesmeck** [comment]
There are two commits in this PR, you need update master before rebasing.

**Comment by GauravV-02** [comment]
@yesmeck I mess up something here, closing this PR, will open a new one. Once everything is sorted out

**Pull request closed without merging**
