### PR TITLE
docs: update docs

### PR DESCRIPTION
**Pull request by yangxiuxiu1115**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]
增加自定义style功能
 [Menu组件没有dropdownStyle这个api，可否像Select组件一样加一个](https://github.com/ant-design/ant-design/issues/42763)
#441 

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at af8bfe3</samp>

This pull request adds a new prop `subMenuStyle` to the `Menu` component, which lets users customize the style of the submenu. The prop is documented in both English and Chinese in the files `index.en-US.md` and `index.zh-CN.md`.

### <samp>🤖 Generated by Copilot at af8bfe3</samp>

* Add a new prop `subMenuStyle` to the `Menu` component to customize the style of the submenu ([link](https://github.com/ant-design/ant-design/pull/42802/files?diff=unified&w=0#diff-828769053a8b1778087d71bae0aac43832c3178ec10cad3dccaa5ac5f2efd996R59), [link](https://github.com/ant-design/ant-design/pull/42802/files?diff=unified&w=0#diff-362ed369b7134257625ca5a93f591eeb91be48bb2826959e84850cb065c56b9cR60))
* Update the English and Chinese documentation files `index.en-US.md` and `index.zh-CN.md` to reflect the new prop and its usage ([link](https://github.com/ant-design/ant-design/pull/42802/files?diff=unified&w=0#diff-828769053a8b1778087d71bae0aac43832c3178ec10cad3dccaa5ac5f2efd996R59), [link](https://github.com/ant-design/ant-design/pull/42802/files?diff=unified&w=0#diff-362ed369b7134257625ca5a93f591eeb91be48bb2826959e84850cb065c56b9cR60))

### CODE REVIEW

**Comment by 97702573** [comment]
嗨@RicardoErii，antd5.5.2版本的文档确实新增了subMenuStyle这个api，但是不好用，因为Merging is blocked吗？

**Comment by RicardoErii** [comment]
antd5.5.2版本的文档新增了subMenuStyle这个api嘛，看起来和我的PR并没有确切的关系。

**Comment by 97702573** [comment]
那我们antd5.5.2版本Menu组件的subMenuStyle这个api现在还不能使用是吗

**Comment by RicardoErii** [comment]
popupClassName不能满足你的需求嘛

**Comment by RicardoErii** [comment]
popupClassName就是给下拉根元素绑定classname

**Pull request closed without merging**
