### PR TITLE
[preact] fix: focus doesn't shift to Dropdown menu

### LINKED ISSUE #4086: [preact/compat] ant-design - Focus doesn't shift to Dropdown menu
- [ ] Check if updating to the latest Preact version resolves the issue

**Describe the bug**
Some time ago I found and reported a bug in antd: https://github.com/ant-design/ant-design/issues/42979

Antd maintainers fixed that bug in version 5.6.2. So the bug is no longer reproducible when I use `react`: https://codesandbox.io/s/antd-reproduction-template-forked-3kmffs

But when I use `preact`, the bug is still exists: https://codesandbox.io/s/fervent-edison-cvw247

Note: antd fix adds `React.forwartRef` to some component. Maybe this will help to fix the bug https://github.com/ant-design/ant-design/pull/43002/files#diff-fab289ecf381929ccfd1ab5e53c7170d3e249910d5774f13f2a76eca26bb6630R18-R21

**To Reproduce**
https://codesandbox.io/s/fervent-edison-cvw247

1. Click on the three dot icon to open the menu
2. Try to navigate through the menu using the keyboard, use the arrow keys to select a menu item

**Expected behavior**
The focus shifts to the menu and I can select a menu item

**What is actually happening?**
The focus doesn't shift to the menu and I can't select a menu item

### PR DESCRIPTION
**Pull request by SpaNb4**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
1. fix https://github.com/preactjs/preact/issues/4086

### 💡 Background and solution
I found and reported a bug related to using preact in combination with antd dropdown https://github.com/preactjs/preact/issues/4086
The issue is that when I open the dropdown menu, the focus doesn't shift to it. Which makes the dropdown menu keyboard inaccessible
Since I'm not sure how to demonstrate that this fix actually works, I recorded a video that first shows the current behavior, and then the behavior after the fix

https://github.com/ant-design/ant-design/assets/69504277/00bd6d77-2c89-470b-a272-2c4f5ccbfd2f

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    [preact] fix focus doesn't shift to dropdown menu      |
| 🇨🇳 Chinese |   [preact]修复焦点无法转移到下拉菜单的问题         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 80b2431</samp>

Added `autoFocus` feature to `Dropdown` component and improved type definitions for `Menu` component and context.

### <samp>🤖 Generated by Copilot at 80b2431</samp>

*  Add `autoFocus` prop to `Dropdown` component to enable focusing the menu on open ([link](https://github.com/ant-design/ant-design/pull/44135/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beR115), [link](https://github.com/ant-design/ant-design/pull/44135/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beR221-R228), [link](https://github.com/ant-design/ant-design/pull/44135/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beR284))
*  Import and use `MenuRef` type from `../menu` to access `Menu` methods in `Dropdown` and `OverrideProvider` components ([link](https://github.com/ant-design/ant-design/pull/44135/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beL14-R14), [link](https://github.com/ant-design/ant-design/pull/44135/files?diff=unified&w=0#diff-fab289ecf381929ccfd1ab5e53c7170d3e249910d5774f13f2a76eca26bb6630R4), [link](https://github.com/ant-design/ant-design/pull/44135/files?diff=unified&w=0#diff-fab289ecf381929ccfd1ab5e53c7170d3e249910d5774f13f2a76eca26bb6630L19-R20))
*  Simplify `Placement` type by removing unnecessary parentheses ([link](https://github.com/ant-design/ant-design/pull/44135/files?diff=unified&w=0#diff-978b29ecd5429963a073f5adfa7ded79d88d23850853c9fb6d453a82047365beL31-R31))

### CODE REVIEW

**Comment by mellis481** [comment]
This is an important bug fix. What do we need to do to get it merged/released? @MadCcc @afc163

**Comment by MadCcc** [comment]
`autoFocus` is handled is `rc-dropdown`, and shouldn't be duplicate in `antd`.
Could you find what's wrong in `rc-dropdown`?

**Comment by nino-det** [comment]
Bumping this PR!

**Comment by SpaNb4** [comment]
@MadCcc Turns out the issue was in rc-util, created a PR with the fix https://github.com/react-component/util/pull/477

**Pull request closed without merging**
