### PR TITLE
fix: Revert change to sticky z-index calc

### PR DESCRIPTION
**Pull request by bconnorwhite**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#26800 looks to have been reverted by accident, this should add back the change

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
#30636 @chenshuai2144

**Comment by afc163** [comment]
What is problem you meet? Is it any errors?

**Comment by bconnorwhite** [comment]
It is the same error as in #26800 (when trying to customize LESS variables):
```
@table-sticky-zindex: @zindex-table-fixed + 1;
^
Operation on an invalid type
```

**Comment by afc163** [comment]
@bconnorwhite Could you provide a reproduce repo?

**Comment by afc163** [comment]
ping @bconnorwhite

**Comment by bconnorwhite** [comment]
It looks like this is specifically when using non-numeric values (ex: `auto`), here is a repo to reproduce:
https://github.com/bconnorwhite/antd-custom-less-zindex

Maybe there's a reason using `auto` doesn't make sense here, `calc` seems to at least allow both `auto` or numeric values

**Pull request merged**
