### PR TITLE
设计模式：表格展开

### PR DESCRIPTION
**Pull request by liqi07**
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!
- [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
- [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
- [x] Rebase before creating a PR to keep commit history clear.
- [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by benjycui** [comment]
这个 demo 其实是要放在 table 下面的。。

**Comment by benjycui** [comment]
设计稿放错位置了

**Comment by afc163** [comment]
建议可以把设计稿截图贴到 PR 上，review 的时候有点依据。

**Comment by liqi07** [comment]
http://ant.design/docs/pattern/list   列表嵌入示例1

**Comment by afc163** [comment]
http://ant.design/components/table/#demo-expand

感觉一毛一样。。。

**Comment by liqi07** [comment]
对！我也有同样的疑惑~~

**Pull request merged**
