### PR TITLE
chore: update icon docs template, affix icon search input to top

### PR DESCRIPTION
**Pull request by cw1997**
feature: update IconDisplay component in Icon docs template, affix icon search input box to the top of page

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
None

### 💡 Background and solution
在文档的“图标”页面中，将搜索栏置顶将有助于快速搜索图标
image
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Update 'Icon' docs template, affix icon search input to top |
| 🇨🇳 Chinese | 更新“图标”文档模板，将搜索文本框固定在顶部 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
@zombieJ 看起来有点奇怪，这个需要和设计师讨论一下吧

**Comment by afc163** [comment]
我参考 https://mui.com/material-ui/material-icons/ 的效果改一版。

**Comment by afc163** [comment]
图片

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/40002

**Pull request closed without merging**
