### PR TITLE
feat✨(transfer):Add a new direction parameter for filterOption function

### PR DESCRIPTION
**Pull request by Zian502**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      feat✨(transfer):Add a new direction parameter for filterOption function     |
| 🇨🇳 Chinese |      transfer 组件的 filterOption 函数新增 direction 入参     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at f377ef1</samp>

Enhanced the `filterOption` prop and function of the `Transfer` component to support custom filtering based on the column direction. Updated the documentation and the code interface to reflect this change.

### <samp>🤖 Generated by Copilot at f377ef1</samp>

*  Add `direction` parameter to `filterOption` prop in `Transfer` component to allow custom filtering logic based on column direction ([link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-c165dbeb24339c042fcc975a9b661af8947ea942457cf8935f29817ac86033a9L46-R46), [link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-16f601b16a2f3b1d448af36a6b569c1d47bf9e2c351318a3b986c42fcbc5b7fdL93-R93), [link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-f25eb82686b163c8fb19e3d453b3c168ce5311046d76e7b3a1192173b676ea97L49-R49), [link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-c6feaf8f7f09d7e3901905a89bc11ecd461a7340d5a8e8ea4dbc994a77bdc415L51-R51), [link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-c6feaf8f7f09d7e3901905a89bc11ecd461a7340d5a8e8ea4dbc994a77bdc415L131-R131))
*  Update `index.en-US.md` and `index.zh-CN.md` to document the new `direction` parameter in `filterOption` prop ([link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-c165dbeb24339c042fcc975a9b661af8947ea942457cf8935f29817ac86033a9L46-R46), [link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-f25eb82686b163c8fb19e3d453b3c168ce5311046d76e7b3a1192173b676ea97L49-R49))
*  Pass `direction` value from `Transfer` component to `TransferList` component and use it for filtering in `list.tsx` ([link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-c6feaf8f7f09d7e3901905a89bc11ecd461a7340d5a8e8ea4dbc994a77bdc415L51-R51), [link](https://github.com/ant-design/ant-design/pull/44413/files?diff=unified&w=0#diff-c6feaf8f7f09d7e3901905a89bc11ecd461a7340d5a8e8ea4dbc994a77bdc415L131-R131))

### CODE REVIEW

**Comment by Zian502** [comment]
https://github.com/ant-design/ant-design/issues/44324

**Comment by yoyo837** [comment]
`feature` branch please.

**Comment by Zian502** [comment]
> `feature` branch please.

是 feature 分支呀
image

**Comment by Zian502** [comment]
> image

那我重新提个 PR 吧

**Pull request closed without merging**
