### PR TITLE
perf: reduce bundle size by reuse icons

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Reduce bundle size by removing some built-in icons.         |
| 🇨🇳 Chinese |  减少内建图标使用以降低打包体积。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Comment by yoyo837** [comment]
改 RightOutlined 的实现内部使用Left ratote能达到一样的效果吗?

**Comment by yoyo837** [comment]
内部改, 外部的 files change就少很多.

**Comment by yoyo837** [comment]
不过file path上有区别

**Comment by afc163** [comment]
得改 https://github.com/ant-design/ant-design-icons/tree/master/packages 的 workflow，稍微会麻烦一点。

**Comment by afc163** [comment]
@yoyo837 的方式确实更合理一点，这里改太 hack 了，先关了。

**Pull request closed without merging**
