### PR TITLE
fix: get label should use childrenKeyName for arrayTreeFilter when us…

### PR DESCRIPTION
**Pull request by 405go**
…e customer fieldNames otherwise It can not get correct label array

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by yesmeck** [comment]
Could you add a test case?

**Comment by 405go** [comment]
OK, I add it @yesmeck

**Comment by yesmeck** [comment]
@405go ci failed.

**Comment by 405go** [comment]
I should to say the script 'antd-tools run ts-lint' can not run when i run it on windows, so I change it run in mac, anyway i have fix cli fail @yesmeck

**Comment by yesmeck** [comment]
Great, thanks!

**Pull request merged**
