### PR TITLE
Correct type

### PR DESCRIPTION
**Pull request by ztplz**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.
  
### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/pull/12799

**Comment by ztplz** [comment]
image
@Bloss 是这个错吗

**Comment by ztplz** [comment]
@Bloss  
你这个跟这个是一样的 你加了个没用的泛型
`<T extends number>(value: any): value is T` === `(value: any): value is number`
is 关键字在ts里 比如按你这样  如果isNumeric判定为true的话  它会在它的作用域里 把value这个类型强制为number这个类型  所以
image这里你不会出现问题 
但是它有个缺点 
image
如果是这样  编译期是不会报错的 但是会有运行错误

**Comment by ztplz** [comment]
image

**Comment by ztplz** [comment]
is 在ts里的应用场景 一般是减少断言的使用 
比如
``````
if (isNumeric(value)) {
    在这个块状作用域内 ts都会把value当做number类型，如果isNumeric返回的是个boolean类型的话，你要用value，你就需要自己断言  比如 value as string
}
``````

**Comment by Bloss** [comment]
我试了一下，原来的方法也有这个问题啊

image

**Comment by yesmeck** [comment]
@Bloss 这个方法，不是判断一个值的类型是不是 `number`，而是判断一个值是不是数字，字符串的 `'123'` 也会被当成数字。

**Pull request merged**
