### PR TITLE
new language lithuanian

### PR DESCRIPTION
**Pull request by mslotvinskij**
Added lithuanian language

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

☑️ Self Check before Merge

### CODE REVIEW

**Comment by yoyo837** [comment]
`rc-picker@^2.0.2`
`rc-pagination@^3.0.1`

`feature` branch Pls.

**Comment by afc163** [comment]
ping @mslotvinskij

**Comment by afc163** [comment]
ping @mslotvinskij again.

**Comment by mslotvinskij** [comment]
> /rebase

Please explain what you mean, im new at github contribution

**Comment by yoyo837** [comment]
Pls rebase from `upstream/feature`

**Comment by zombieJ** [comment]
hi @mslotvinskij , here is the git rebase related doc. Wish this will help:
https://git-scm.com/docs/git-rebase

**Comment by mslotvinskij** [comment]
@zombieJ @yoyo837 probably i did it

**Comment by yoyo837** [comment]
Seems to be mixed with other things, Commits should be clean.

**Comment by mslotvinskij** [comment]
Remaking fork

**Pull request closed without merging**
