### PR TITLE
fix table onChange pagination type

### PR DESCRIPTION
**Pull request by weidapao**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by afc163** [comment]
Table pagination could be `false`.

**Comment by weidapao** [comment]
when pagination is false
,in function onChange,
param pagination is Null Object

**Comment by afc163** [comment]
@weidapao What is the problem of that? You can report it by using http://new-issue.ant.design/

**Comment by weidapao** [comment]
table.tsx
line 63
```
const emptyObject = {};
```
line  182 
```
return { pagination: nextProps.pagination !== false ? newPagination : emptyObject };
```
so there is no boolean type 
@afc163

**Comment by weidapao** [comment]
In table source code,when pagination is false,it will be translate into 
```
{}
```
@afc163

**Pull request merged**
