### PR TITLE
chore: 🔀 merge master into feature

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [x] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered CHANGELOG.en-US.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/CHANGELOG.en-US.md)
[View rendered CHANGELOG.zh-CN.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/CHANGELOG.zh-CN.md)
[View rendered components/button/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/button/index.zh-CN.md)
[View rendered components/comment/demo/basic.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/comment/demo/basic.md)
[View rendered components/config-provider/demo/size.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/config-provider/demo/size.md)
[View rendered components/form/demo/control-hooks.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/form/demo/control-hooks.md)
[View rendered components/form/demo/form-context.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/form/demo/form-context.md)
[View rendered components/form/demo/register.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/form/demo/register.md)
[View rendered components/modal/index.en-US.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/modal/index.en-US.md)
[View rendered components/page-header/index.en-US.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/page-header/index.en-US.md)
[View rendered components/page-header/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/page-header/index.zh-CN.md)
[View rendered components/progress/demo/dashboard.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/progress/demo/dashboard.md)
[View rendered components/progress/demo/segment.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/progress/demo/segment.md)
[View rendered components/progress/index.en-US.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/progress/index.en-US.md)
[View rendered components/progress/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/master-to-merge-feature/components/progress/index.zh-CN.md)

### CODE REVIEW

**Review by yoyo837 — APPROVED** [review]

**Comment by afc163** [comment]
@zombieJ dist 构建报错了。

- https://unpkg.com/rc-picker@1.4.1/es/generate/moment.js
- https://unpkg.com/rc-picker@1.4.0/es/generate/moment.js

**Comment by afc163** [comment]
image

**Comment by shaodahong** [comment]
`uglify` 不支持 ES6+，babel 转下或者换 `webpack-plugin-terser`，推荐用 `webpack-plugin-terser`

把这个换下 https://github.com/ant-design/antd-tools/blob/b24334b97cc4797309d68a4780e828d38a06d687/lib/getWebpackConfig.js#L239

**Comment by zombieJ** [comment]
> @zombieJ dist 构建报错了。
> 
> * https://unpkg.com/rc-picker@1.4.1/es/generate/moment.js
> * https://unpkg.com/rc-picker@1.4.0/es/generate/moment.js

1.4.0 是错的，1.4.1 是修好的。这个没错。

**Comment by zombieJ** [comment]
要看看为什么 rc-picker 不行

**Pull request merged**
