### PR TITLE
fix: update ConfigProvider context to  use globalConfig 

### PR DESCRIPTION
**Pull request by sirajulm**
- Move global config functions to seperate file
- Reuse global config prefixCls for the context
- Move types to seperate file

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- https://github.com/ant-design/ant-design/issues/32961

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | `ConfigProvider.config({...})` can now be used to globally set the `prefixCls` for the components.  |
| 🇨🇳 Chinese | # Need help in translation 🙂 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by crazyair** [comment]
ConfigProvider.config  是为了静态方法使用的（可能 antd v5 会把静态方法类移除掉就不需要 ConfigProvider.config 了）。

组件类推荐 <ConfigProvider prefixCls ...

**Comment by sirajulm** [comment]
@crazyair Thank you for the reply. 
Does that mean once the static method `ConfigProvider.config`, there would be no other way to change the `prefixCls` statically?
`<ConfigProvider prefixCls="" />` does help to change the prefix dynamically, having a static configuration is good to have, in cases of creating a customized component library on top of antd. It look simpler to call the static `config()` once instead of wrapping each exposed component with `<ConfigProvider ... />

Let me know your thoughts. 🙂

**Comment by crazyair** [comment]
组件库的话，也不需要配置`prefixCls`，而是在使用的项目去配置。

**Comment by sirajulm** [comment]
The solution would work with simple and medium scale projects, but would not scale for complex projects using multiple packages/micro-frontends which in turn uses different versions of antd.

That would not help  in  projects where the host application uses a different version of `antd` compared to the one the custom component library uses, adding up to style conflicts. It would be quite difficult to keep all the projects running with same version of `antd` throughout its lifecycle.

Also,
```javascript
import {Button} from '@org/components'; // seperate repo with customization over antd components.
import {ConfigProvider, Input} from 'antd';
<ConfigProvider prefixCls="custom">
  <Input {...props} />
  <Button {...props} />
</ConfigProvider>
```
The above code would render
```html
<input class="custom-input" />
<button class="ant-btn"> 
```
with no effect of ConfigProvider on the button (as expected)

Which would require the `@org/components` to wrap each exposed component with a `ConfigProvider`

**Comment by sirajulm** [comment]
I'm interested to know if there is any public accessible roadmap on antd v5? 🙂

**Comment by crazyair** [comment]
```tsx
import {ConfigProvider, Input} from 'antd';
import {OrgConfigProvider, Button} from '@org/components';

<ConfigProvider prefixCls="ant">
    <OrgConfigProvider prefixCls="custom">
      <Input  />
      <Button />
    </OrgConfigProvider>
</ConfigProvider>
```

**Comment by sirajulm** [comment]
@crazyair Hmm... That also should be working. It was my mistake that I didn't expose the ConfigProvider from the custom library. This should be working for me Though I see that the host application is made responsible for setting the context of a customized library, I think that is fine.

We can close this PR and the related issue raised 🙂

**Pull request closed without merging**
