### PR TITLE
type: type optimization

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | type: type optimization |
| 🇨🇳 Chinese | 无需纳入 ChangeLog |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 3320419</samp>

Fixed a bug in the graph component by locking the dependency version of `@antv/g6` in `package.json`. This prevents breaking changes from affecting the component's rendering.

### <samp>🤖 Generated by Copilot at 3320419</samp>

* Fix graph component rendering bug by fixing dependency version of `@antv/g6` to `4.8.5` ([link](https://github.com/ant-design/ant-design/pull/42312/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L160-R160))

### CODE REVIEW

**Comment by yoyo837** [comment]
写一下原因不?

**Comment by afc163** [comment]
https://unpkg.com/@antv/g6@4.8.12/package.json 里 dependencies 多了个 webpack 依赖。

图片

**Comment by li-jia-nan** [comment]
求+1

**Comment by li-jia-nan** [comment]
合完还要同步到 feature

**Review by kiner-tang — APPROVED** [review]

**Pull request merged**
