### PR TITLE
Don't directly import Component, use React.Component.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is another step towards making the code internally consistent.

### CODE REVIEW

**Comment by afc163** [comment]
What benefit?

**Comment by benjycui** [comment]
To make code style more consistent.

**Comment by waywardmonkeys** [comment]
What @benjycui said. I'd been doing some changes by via 'git grep "extends React.Component" components' and didn't notice for a while that I'd missed these classes as a result.

**Comment by benjycui** [comment]
Code convention updated: https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd#extends-reactcomponent-instead-of-component

**Pull request merged**
