### PR TITLE
fix: Tree search demo type error

### PR DESCRIPTION
**Pull request by AshishKapoor**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a bug fix in the Tree example with search, where the onExpand prop is throwing a type error.

- [x] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   NA      |
| 🇨🇳 Chinese |   NA      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Why change this?

**Comment by AshishKapoor** [comment]
> Why change this?

`Getting this type error otherwise.`

```
(property) onExpand?: ((expandedKeys: Key[], info: {
    node: EventDataNode<DataNode>;
    expanded: boolean;
    nativeEvent: MouseEvent;
}) => void) | undefined
Type '(newExpandedKeys: string[]) => void' is not assignable to type '(expandedKeys: Key[], info: { node: EventDataNode<DataNode>; expanded: boolean; nativeEvent: MouseEvent; }) => void'.
Translation: I was expecting a type matching A, but instead you passed B.
```

**Comment by afc163** [comment]
It is a falsy fix, onExpand will not be triggered now.

**Comment by AshishKapoor** [comment]
> It is a falsy fix, onExpand will not be triggered now.

Good catch! pushing the correct fix!

**Review by afc163 — APPROVED** [review]

**Pull request merged**
