### PR TITLE
Use ES2015 classes instead of React.createClass.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Make `Affix`, `Alert`, `Badge`, `Breadcrumb`, `Button`, `Carousel`,
`Checkbox` and `Dropdown` components use ES2015 classes rather
than `React.createClass`.

This is a start on addressing issue #1179.

This includes:
- `getDefaultProps` method becomes a `defaultProps` value on the
  constructor.
- `propTypes` becomes a value on the constructor.
- `getInitialState` becomes a constructor function that initializes
  `this.state` directly.
- Event callbacks have to have `this` bound.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This has raised a number of questions:

* Is `master` the right branch to do this work? Or should it be against `develop-1.0.0`?
* Should I use `.bind(this)` on every event binding? Or should we iterate through the methods in the constructor and set them to the bound versions? This was done previously in `components/cascader/index.jsx`, but all other usages were binding at the time of setting the event handler.
* Some classes weren't named previously and just `export default`. I've added names for them now.
* Some components use `module.exports = ` rather than `export default`. Is this just a legacy issue that can / should be corrected?
* Some components have names that overlap with the underlying `react-component` component. In these cases, sometimes the ant-design component is named `AntWhatever` while in other cases the underlying component is renamed to `RcWhatever`. Is there a preferred way of doing this that is consistent?

**Comment by waywardmonkeys** [comment]
Also, is it better to submit this in pieces or to try to do it all in one shot? This introduces a lot of small changes, so it may be difficult to maintain if there is a lot of other activity.

**Comment by waywardmonkeys** [comment]
Finally, I am sorry, but I do not speak or read Chinese. I hope that my language doesn't cause too many difficulties or inconvenience.

**Comment by afc163** [comment]
Thanks for great work!

1. `develop-1.0.0` will be a better branch.
2. You can do binding like this: https://github.com/react-component/cascader/blob/master/src/Cascader.jsx#L56-L62
3. Leave `demo` to `React.createClass` for now, because we like demo code keep simple. `binding mess`
4. All `module.exports` should be corrected.
5. `RcXxxx` and `AntXxxx` issues...eh, just ignore it. Something naming is hard.

**Comment by yiminghe** [comment]
do not bind this way, it's unefficient and easy to forget for future method, use es7 binding(still not efficient as react.createClass):

```
class X {
 x = () => {
 }
}
```

**Comment by afc163** [comment]
https://github.com/zenparsing/es-function-bind

**Comment by afc163** [comment]
Would you please create new PR for `develop-1.0.0`, I close this now.

**Pull request closed without merging**
