### PR TITLE
feat: MenuItem support `danger`

### LINKED ISSUE #23663: Menu.Item support `danger` style
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

截屏2020-04-27 下午4 01 07

截屏2020-04-27 下午4 01 44

### What does the proposed API look like?

```tsx
<Menu.Item danger />
```

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #23663

### 💡 Background and solution

Preview: https://preview-23785-ant-design.surge.sh/components/dropdown-cn/#components-dropdown-demo-basic

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Menu.Item support `danger` prop.        |
| 🇨🇳 Chinese |    Menu.Item 支持 `danger` 属性。       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/dropdown/demo/basic.md](https://github.com/ant-design/ant-design/blob/menu-danger/components/dropdown/demo/basic.md)
[View rendered components/menu/demo/theme.md](https://github.com/ant-design/ant-design/blob/menu-danger/components/menu/demo/theme.md)
[View rendered components/menu/index.en-US.md](https://github.com/ant-design/ant-design/blob/menu-danger/components/menu/index.en-US.md)
[View rendered components/menu/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/menu-danger/components/menu/index.zh-CN.md)

### CODE REVIEW

**Comment by zombieJ** [comment]
#22758 之后在其他 PR 里搞一下。

**Comment by ztplz** [comment]
单独一个属性不考虑以后的扩展吗？ 万一以后又来了success fail之类的怎么办。

**Comment by zombieJ** [comment]
> 单独一个属性不考虑以后的扩展吗？ 万一以后又来了success fail之类的怎么办。

MenuItem 的属性应该比较纯粹，不会有太多状态。

**Comment by xrkffgg** [comment]
对比一下，普通的 hover 是不是有点淡了

**Comment by xrkffgg** [comment]
要不要再加一个 primary 的 和 danger 对应 

效果和 github 的一样

image

**Comment by xrkffgg** [comment]
要不要再加一个 primary 的 和 danger 对应 

效果和 github 的一样

image

**Review by afc163 — APPROVED** [review]

**Comment by zombieJ** [comment]
嗯，在和设计师对一下。看看需不需要拓展。

**Comment by zombieJ** [comment]
和设计师对了一下，暂时只需要 danger 就够了。有需求以后再加。

**Pull request merged**
