### PR TITLE
refactor: forward-ref-usage

### PR DESCRIPTION
**Pull request by zheeeng**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Refactor the usages of `React.forwardRef` and the code style of mounting the static components on the exported component |
| 🇨🇳 Chinese | 统一 React.forwardRef 与挂载组件到主组件静态属性上的写法 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zheeeng** [comment]
覆盖率之前是 100%，现在报降低了，点进去看是还是 100%

**Comment by afc163** [comment]
冲突了

**Comment by zheeeng** [comment]
> 冲突了

fixed

**Comment by afc163** [comment]
冲突更多了，先关了，欢迎建一个新 PR。

**Pull request closed without merging**
