### PR TITLE
Move binding to the constructor.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Move existing uses of ".bind(this)" to the constructor of the class.

This makes all existing ES2015 class usages in components use the
same mechanism for binding and avoids the need to call bind at each
site where it is passed along as an event handler.

### CODE REVIEW

**Comment by afc163** [comment]
Maybe we should enable `es7.functionBind` in antd development. @benjycui 

https://babeljs.io/blog/2015/05/14/function-bind

https://babeljs.io/docs/plugins/transform-function-bind/

**Comment by waywardmonkeys** [comment]
I understand the appeal of that idea. It is more concise for sure. However, it isn't standard syntax yet and would be a burden for anyone approaching the ant-design code. If we used it in demos, it would also be a bit confusing, and it would be nice if the demos and the core code itself were consistent in how they did things.

**Comment by benjycui** [comment]
There are no difference between *binding in JSX* and compiled *es7.functionBind*

```jsx
<button onClick={this::handleClick}>Hello</button>

// Will be compiled to 

React.createElement(
  "button",
  { onClick: handleClick.bind(this) },
  "Hello"
);
```

See: [online demo](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Ces2015-loose%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=false&loose=false&spec=false&code=class%20Something%20extends%20React.Component%20%7B%0A%20%20handleClick()%20%7B%7D%0A%20%20%0A%20%20render()%20%7B%0A%20%20%20%20return%20%3Cbutton%20onClick%3D%7Bthis%3A%3AhandleClick%7D%3EHello%3C%2Fbutton%3E%0A%20%20%7D%0A%7D)

**Comment by yiminghe** [comment]
I oppose this way, it's ugly.

use this if you have to

```js
x: ()=>{};
```

please

**Comment by waywardmonkeys** [comment]
@yiminghe Do you mean something like this:

```javascript
export default class Button extends React.Component {
  constructor(props) {
    super(props);
  }
  handleClick: (...args) => {
    ... code elided ...
    this.props.onClick(...args);
  }
```

If so, that fails lint with:

```
  35:14  error  Parsing error: Unexpected token :
```

**Comment by yiminghe** [comment]
```javascript
export default class Button extends React.Component {
  constructor(props) {
    super(props);
  }
  handleClick = (...args) => {
    ... code elided ...
    this.props.onClick(...args);
  }
```

**Comment by waywardmonkeys** [comment]
That fails also, but not the unexpected token is ``=``.

**Comment by waywardmonkeys** [comment]
Getting that to work would mean having babel do the es7 stuff.

**Comment by yiminghe** [comment]
[demo](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact%2Cstage-1%2Cstage-2&code=class%20x%20extends%20y%20%7B%0A%20%20z%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20%0A%20%20%7D%3B%0A%7D)

**Comment by yiminghe** [comment]
http://leonshi.com/2016/03/16/babel6-es6-inherit-issue-in-ie10/

**Comment by waywardmonkeys** [comment]
My errors are actually from ``eslint`` before we even get to babel.

**Comment by benjycui** [comment]
If we want to use ES7 features, we must modify .eslintrc.json at the same time.

**Comment by plandem** [comment]
i'm sure it's ES6 to use it like this:
```
<inputNumber onChange={(value) => this.handleChange(value)}
```

p.s.: i almost don't use 'bind', mostly as i wrote above.

**Comment by waywardmonkeys** [comment]
What @plandem said is one path forward.

If we're going to go with @yiminghe's suggestion of using ES7 features, then that's fine too. There are a couple of advantages to ES7 features:

* They're also how you do the same thing in TypeScript.
* They would allow us to use static class properties to put `propTypes` and other things into the class definition rather than after it. We could also use it for things like `static Panel = RcCollapse.Panel` which would make some of the code look nicer.

**Comment by waywardmonkeys** [comment]
Once / If #1272 lands, then I'll rework it to use ES7 stuff as @yiminghe wants.

**Comment by waywardmonkeys** [comment]
This has been updated now to use the ES7 features. If this is good, then I can move on to converting the remaining usages of `React.createClass` over to extending `React.Component`.

**Comment by benjycui** [comment]
LGTM，and it seems that we are going to use ES7 feature in antd.

**Comment by waywardmonkeys** [comment]
Getting closer to where just using TypeScriot and TSX would be a simplification. :)

**Comment by afc163** [comment]
Need rebase...

**Comment by waywardmonkeys** [comment]
Rebased.

**Comment by benjycui** [comment]
Code convention updated https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd#bind-this-in-class-definition-with-es7-syntax

**Pull request merged**
