### PR TITLE
fix(Checkbox): clicking on the label tag will cause the event to bubble, causing the parent div click event to be triggered.

### PR DESCRIPTION
**Pull request by edc-hui**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
#38926 

### 💡 Background and solution
checkbox 组件中的label标签，没有进行阻止事件冒泡，这样就导致在表格中，点击label标签先冒泡触发表格行的onClick事件，然后触发label标签包裹的input聚焦导致input的onChange事件也被执行。故此处选择的解决方案为阻止label标签的点击事件冒泡行为

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fixed clicking on the label tag will cause the event to bubble, causing the parent div click event to be triggered       |
| 🇨🇳 Chinese |     修复点击label标签导致事件冒泡，造成父div点击事件被触发的问题      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
截屏2022-12-15 11 51 47

点击 Detail 可以看到报错的具体 test case 哈：

```
2022-12-14T02:08:31.5301287Z FAIL components/table/__tests__/Table.rowSelection.test.tsx (29.28 s)
2022-12-14T02:08:31.5302140Z   ● Table.rowSelection › should keep item even if in filter
2022-12-14T02:08:31.5302697Z 
2022-12-14T02:08:31.5302997Z     expect(received).toBe(expected) // Object.is equality
2022-12-14T02:08:31.5303520Z 
2022-12-14T02:08:31.5303752Z     Expected: 1
2022-12-14T02:08:31.5304690Z     Received: 4
2022-12-14T02:08:31.5304977Z 
2022-12-14T02:08:31.5305569Z       916 |     // Check Jack
2022-12-14T02:08:31.5305943Z       917 |     clickFilter([0]);
2022-12-14T02:08:31.5306734Z     > 918 |     expect(container.querySelectorAll('tbody tr').length).toBe(1);
2022-12-14T02:08:31.5307204Z           |                                                           ^
2022-12-14T02:08:31.5366505Z       919 |     clickItem();
2022-12-14T02:08:31.5367046Z       920 |     expect(onChange.mock.calls[0][0].length).toBe(1);
2022-12-14T02:08:31.5367739Z       921 |     expect(onChange.mock.calls[0][1].length).toBe(1);
2022-12-14T02:08:31.5368066Z 
2022-12-14T02:08:31.5368685Z       at Object.toBe (components/table/__tests__/Table.rowSelection.test.tsx:918:59)
```

**Comment by edc-hui** [comment]
> 截屏2022-12-15 11 51 47
> 
> 点击 Detail 可以看到报错的具体 test case 哈：
> 
> ```
> 2022-12-14T02:08:31.5301287Z FAIL components/table/__tests__/Table.rowSelection.test.tsx (29.28 s)
> 2022-12-14T02:08:31.5302140Z   ● Table.rowSelection › should keep item even if in filter
> 2022-12-14T02:08:31.5302697Z 
> 2022-12-14T02:08:31.5302997Z     expect(received).toBe(expected) // Object.is equality
> 2022-12-14T02:08:31.5303520Z 
> 2022-12-14T02:08:31.5303752Z     Expected: 1
> 2022-12-14T02:08:31.5304690Z     Received: 4
> 2022-12-14T02:08:31.5304977Z 
> 2022-12-14T02:08:31.5305569Z       916 |     // Check Jack
> 2022-12-14T02:08:31.5305943Z       917 |     clickFilter([0]);
> 2022-12-14T02:08:31.5306734Z     > 918 |     expect(container.querySelectorAll('tbody tr').length).toBe(1);
> 2022-12-14T02:08:31.5307204Z           |                                                           ^
> 2022-12-14T02:08:31.5366505Z       919 |     clickItem();
> 2022-12-14T02:08:31.5367046Z       920 |     expect(onChange.mock.calls[0][0].length).toBe(1);
> 2022-12-14T02:08:31.5367739Z       921 |     expect(onChange.mock.calls[0][1].length).toBe(1);
> 2022-12-14T02:08:31.5368066Z 
> 2022-12-14T02:08:31.5368685Z       at Object.toBe (components/table/__tests__/Table.rowSelection.test.tsx:918:59)
> ```

好的  明白了  我再检查下

**Comment by edc-hui** [comment]
@zombieJ 
#38926所描述的问题在Transfer组件中也是可以复现出来。

想要彻底解决这个问题，我目前想到的方案是设置Checkbox组件中label标签的line-height为0，目的是让label标签和Checkbox组件中的input等高。这样在Table中选中Checkbox，点击label标签事件冒泡触发Table的click事件的问题就不会出现。

但是line-height为0这个样式的变更会导致Transfer组件，Checkbox与文字对不齐的问题，故我这边修改了Transfer组件的样式。

这种解决方案您认可么？

**Comment by edc-hui** [comment]
另外我还有个疑问就是，这次github ci未通过，看着像快照需要被更新，但是我此次修改的变动自认为可能会导致UI有细微的变化。
“ Checkbox中原先设置给.antd-checkbox的top: 0.2em样式被移除了，其父元素.antd-checkbox-wrapper设置transform: translateY(0.2em)” ，  我觉得我的这个更改应该会导致UI变化。

所以我不知道是应该执行 npm test -- -u  还是应该执行  npm run test-image -- -u

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/41519

**Pull request closed without merging**
