### PR TITLE
refactor: Update rc-slider

### LINKED ISSUE #34020: Slider not working correctly when min prop has decimals
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/heuristic-leavitt-wk3s0?file=/src/App.js)

### Steps to reproduce
1. Create a slider component with props ```min={0.05} max={2} step={1}```
2. Try moving the slider

### What is expected?
It should be possible to reach the max value while dragging

### What is actually happening?
- Impossible to set the value to the max, it doesn't move further than 1
- The minimum value sets to 0, should be 0.05.

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome/98.0.4758.82 |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #34020

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
体积居然变大了。

**Comment by zombieJ** [comment]
又小了，未解之谜 👻

**Comment by afc163** [comment]
> 又小了，未解之谜 👻

真爽。

**Review by fireairforce — APPROVED** [review]

**Comment by afc163** [comment]
梳理一波 Slider 现有的 open issues，看看哪些被解决了，或者已解决。

**Comment by afc163** [comment]
图片

身首分离了。

**Comment by afc163** [comment]
图片

@Madcc Firefox 下这条白线还是很醒目。

**Review by vagusX — APPROVED** [review]

**Comment by ZainChen** [comment]
> > 又小了，未解之谜 👻
> 
> 真爽。又有这样的担心：『这里怎么多出个螺丝？肯定是多余的』

这个版本的 rc-slider 不支持鼠标按下拖动滑块了。音视频播放器的进度条和滚动条都在用这个组件，无法按下拖动超难受。
"antd": "version": "4.19.2", "rc-slider": "~10.0.0-alpha.4"

**Comment by fancyvip** [comment]
> 图片
> 
> @madcc Firefox 下这条白线还是很醒目。


**从4.18.9更新slider之后，绑定ref无法获取到componentenhancer导致无法操作dom属性**

image

**现在只能获取到这两个事件**

image

**Pull request merged**
