### PR TITLE
fix(Form): label width not correct when screen less than xs

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Ref: https://github.com/ant-design/ant-design/pull/20836#issuecomment-581754619

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
当前仓库分支 `/rebase` 才会生效。

**Comment by zombieJ** [comment]
不应该直接 100%，用户设置了 col 的时候应该按照设置的来：

截屏2020-02-08上午11 42 19

截屏2020-02-08上午11 42 43

ref: https://preview-21222-ant-design.surge.sh/components/form-cn/#components-form-demo-basic

**Comment by shaodahong** [comment]
> 不应该直接 100%，用户设置了 col 的时候应该按照设置的来：
> 
> 截屏2020-02-08上午11 42 19
> 
> 截屏2020-02-08上午11 42 43
> 
> ref: https://preview-21222-ant-design.surge.sh/components/form-cn/#components-form-demo-basic

以前的逻辑就是 XS 下 label 独占一行，不过以前是通过 `display:block` 来控制的

**Comment by shaodahong** [comment]
image

**Comment by zombieJ** [comment]
Get 了，那下面的应该也撑满：
截屏2020-02-10上午10 32 25

**Comment by shaodahong** [comment]
Done.

**Comment by zombieJ** [comment]
截屏2020-02-11下午5 16 54

Preview seems no effect.

**Pull request merged**
