### PR TITLE
refactor: improve typescript module declare

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    improve typescript module declare       |
| 🇨🇳 Chinese | 改进 typescript 模块声明 |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
@shaodahong , `npm run compile` failed by `cnpm install`. Please help to check.

**Comment by shaodahong** [comment]
> @shaodahong , `npm run compile` failed by `cnpm install`. Please help to check.

I try `cnpm install` it's ok , Please rm `lock` and `node_modules` file and retry install...

**Comment by shaodahong** [comment]
```bash

~/Workspace/github/ant-design master
❯ cnpm i
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

> fsevents@1.2.9 install /Users/shaodahong/Workspace/github/ant-design/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/shaodahong/Workspace/github/ant-design/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> iltorb@2.4.3 install /Users/shaodahong/Workspace/github/ant-design/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

info looking for cached prebuild @ /Users/shaodahong/.npm/.cache/cnpm/_prebuilds/db4ff3-iltorb-v2.4.3-node-v64-darwin-x64.tar.gz
http request GET https://github.com/MayhemYDG/iltorb/releases/download/v2.4.3/iltorb-v2.4.3-node-v64-darwin-x64.tar.gz
http 200 https://github.com/MayhemYDG/iltorb/releases/download/v2.4.3/iltorb-v2.4.3-node-v64-darwin-x64.tar.gz
info downloading to @ /Users/shaodahong/.npm/.cache/cnpm/_prebuilds/db4ff3-iltorb-v2.4.3-node-v64-darwin-x64.tar.gz.3021-035de6cfed7fa.tmp
info renaming to @ /Users/shaodahong/.npm/.cache/cnpm/_prebuilds/db4ff3-iltorb-v2.4.3-node-v64-darwin-x64.tar.gz
info unpacking @ /Users/shaodahong/.npm/.cache/cnpm/_prebuilds/db4ff3-iltorb-v2.4.3-node-v64-darwin-x64.tar.gz
info unpack resolved to /Users/shaodahong/Workspace/github/ant-design/node_modules/iltorb/build/bindings/iltorb.node
info unpack required /Users/shaodahong/Workspace/github/ant-design/node_modules/iltorb/build/bindings/iltorb.node successfully
info install Successfully installed iltorb binary!

> husky@3.0.9 install /Users/shaodahong/Workspace/github/ant-design/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> core-js@2.6.10 postinstall /Users/shaodahong/Workspace/github/ant-design/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> @ant-design/tools@8.0.4 postinstall /Users/shaodahong/Workspace/github/ant-design/node_modules/@ant-design/tools
> node lib/init.js


> full-icu@1.3.0 postinstall /Users/shaodahong/Workspace/github/ant-design/node_modules/full-icu
> node postinstall.js

npm install icu4c-data@64l (Node 10.16.3 and small-icu 64.2) -> icudt64l.dat
full-icu$ /Users/shaodahong/.nvm/versions/node/v10.16.3/bin/node /Users/shaodahong/.nvm/versions/node/v10.16.3/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@64l
npm notice created a lockfile as package-lock.json. You should commit this file.
+ icu4c-data@0.64.2
added 1 package from 1 contributor in 5.6s
 √ icudt64l.dat (link)
Node will use this ICU datafile if the environment variable NODE_ICU_DATA is set to “node_modules/full-icu”
or with node --icu-data-dir=node_modules/full-icu YOURAPP.js
 For package.json:
{"scripts":{"start":"node --icu-data-dir=node_modules/full-icu YOURAPP.js"}}

By the way, if you have full data, running this in node:
> new Intl.DateTimeFormat('es',{month:'long'}).format(new Date(9E8));
... will show “enero”. If it shows “January” you don't have full data.
News: Please see https://github.com/icu-project/full-icu-npm/issues/6

> husky@3.0.9 postinstall /Users/shaodahong/Workspace/github/ant-design/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate


> preact@10.0.0 postinstall /Users/shaodahong/Workspace/github/ant-design/node_modules/preact
> node -e "console.log('\u001b[35m\u001b[1mLove Preact? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/preact/donate\u001b[0m')"

Love Preact? You can now donate to our open collective:
 > https://opencollective.com/preact/donate
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> antd@3.24.1 prepublish /Users/shaodahong/Workspace/github/ant-design
> antd-tools run guard

antd-tools run guard
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN url-loader@0.5.9 requires a peer of file-loader@* but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@15.2.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN preact-compat@3.19.0 requires a peer of preact@<10 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-declaration-block-no-ignored-properties@2.1.0 requires a peer of stylelint@^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@2.2.0 requires a peer of file-loader@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of @typescript-eslint/parser@^1.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-react@^7.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN preact-context@1.1.4 requires a peer of preact@^8.2.7 but none is installed. You must install peer dependencies yourself.

added 2609 packages from 1358 contributors in 171.068s

~/Workspace/github/ant-design master 2m 52s
❯ npm run compile

> antd@3.24.1 compile /Users/shaodahong/Workspace/github/ant-design
> antd-tools run compile

antd-tools run compile
[Parallel] Compile to es...
[Parallel] Compile to js...
[Compile] Finalization...
Wrote version into lib/version/index.js
Wrote version into lib/version/index.d.ts
```

**Comment by shaodahong** [comment]
@zombieJ have fail message?

**Comment by yoyo837** [comment]
```
antd-tools run compile
[Parallel] Compile to es...
[Parallel] Compile to js...
components/config-provider/context.ts(33,14): error TS2742: The inferred type of 'ConfigConsumer' cannot be named without a reference to '_@types_react-lifecycles-compat@3.0.1@@types/react-lifecycles-compat/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
components/config-provider/context.ts(33,14): error TS2742: The inferred type of 'ConfigConsumer' cannot be named without a reference to '_@types_react-lifecycles-compat@3.0.1@@types/react-lifecycles-compat/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
TypeScript: 1 declaration error
TypeScript: emit failed
```

**Comment by shaodahong** [comment]
@zombieJ @yoyo837 我这边死活复现不了，麻烦 https://github.com/ant-design/ant-design/blob/5bd3d4a33bc1bdb60d8fcc03be2e6bf92505f882/components/config-provider/context.ts#L24 这一行加个返回类型试试

**Comment by shaodahong** [comment]
转战 windows 也没复现，像是少了个类型……

```bash
$ node -v
v10.15.0

$ npm run compile

> antd@3.24.1 compile D:\workspace\ant-design
> antd-tools run compile

antd-tools run compile
[Parallel] Compile to es...
[Parallel] Compile to js...
[Compile] Finalization...
Wrote version into lib/version/index.js
Wrote version into lib/version/index.d.ts
```

**Comment by shaodahong** [comment]
@yoyo837 麻烦 `npm ls @types/react` 看下，怀疑是包冲突了

```bash
$ npm ls @types/react
antd@3.24.1 D:\workspace\ant-design
+-- @types/react@16.9.9
+-- @types/react-dom@16.9.2
| `-- @types/react@16.9.9  deduped
+-- @types/react-lifecycles-compat@3.0.1
| `-- @types/react@16.9.9  deduped
+-- @types/react-slick@0.23.4
| `-- @types/react@16.9.9  deduped
`-- react-dnd@9.4.0
  `-- @types/hoist-non-react-statics@3.3.1
    `-- @types/react@16.9.9  deduped
```

**Comment by shaodahong** [comment]
@yoyo837 麻烦发下 cnpm 的版本

**Comment by zombieJ** [comment]
>$ cnpm -v
cnpm@6.0.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.4.1 (/usr/local/lib/node_modules/cnpm/node_modules/_npm@6.4.1@npm/lib/npm.js)
node@10.16.3 (/usr/local/Cellar/node@10/10.16.3/bin/node)
npminstall@3.16.0 (/usr/local/lib/node_modules/cnpm/node_modules/_npminstall@3.16.0@npminstall/lib/index.js)
prefix=/usr/local
darwin x64 19.0.0
registry=https://registry.npm.taobao.org

**Comment by zombieJ** [comment]
我这边实验下来是它尝试寻找 `_@types_react-lifecycles-compat@3.0.1@@types/react-lifecycles-compat/node_modules/@types/react` 的包，但是实际上被提升了。看了一下 `package.json`，`@types/react-lifecycles-compat` 和 `@types/react-dom` 看起来没啥区别。怪异。

**Comment by yoyo837** [comment]
```
tanghui@tanghuideMacBook-Pro ~ % cnpm --version
cnpm@6.1.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.12.0 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@12.12.0 (/usr/local/Cellar/node/12.12.0/bin/node)
npminstall@3.23.0 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local 
darwin x64 19.0.0 
registry=https://r.npm.taobao.org
```

**Pull request merged**
