### PR TITLE
[WIP] fix: Input clear icon poisition

### LINKED ISSUE #30138: Change Input clear icon visibility hidden to display none while hidden
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/jibenshiyong-antd4151-forked-0hjs2?file=/index.js

With allowClear, the input length is seem not enough, the placeholder will show ellipses. 
image

But there are actually enough space to display full text. 
image
 
Is that possible to change clear icon `visibility:hidden` to `display:none` ? 

| Environment | Info |
|---|---|
| antd | undefined |
| React | React |
| System | Mac |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #30138

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Display Input `placeholder` as long as possible when clear icon is hidden. |
| 🇨🇳 Chinese | 修复 Input `placeholder` 显示不全的问题。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
@zombieJ 看看能不能动 https://github.com/ant-design/ant-design/commit/02d729257699a053178d1322541afce894af98f5#r49549312

**Comment by zombieJ** [comment]
会有影响 https://github.com/ant-design/ant-design/issues/22562

**Comment by zombieJ** [comment]
感觉是可以做成 `display: none` + `padding-right` 保留空间。

**Comment by afc163** [comment]
图片

图片

对不上。

**Comment by afc163** [comment]
> 感觉是可以做成 display: none + padding-right 保留空间。

不太好搞。

**Pull request closed without merging**
