### PR TITLE
Add en-GB, it-IT, fr-FR + nl_BE locales

### PR DESCRIPTION
**Pull request by damiangreen**
Add four new locales:
 en-GB, it-IT, fr-FR + nl_BE locales.

The package.json dependency versions are updated to pull in the 2 new version of rc- packages

### CODE REVIEW

**Comment by damiangreen** [comment]
I missed 'fr-FR', have pushed to the pagination package: 
Just waiting for https://github.com/react-component/pagination/pull/88 to be merged

**Comment by afc163** [comment]
test cases

**Comment by afc163** [comment]
image

**Comment by damiangreen** [comment]
sure, ill look at adding test cases now

**Comment by damiangreen** [comment]
I added my other email to my account profile

**Pull request merged**
