### PR TITLE
feat: App support style props

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | feat: App support style props |
| 🇨🇳 Chinese | feat: App 支持自定义 style |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by luo3house** [comment]
要不要也加上 forward ref ？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: codecov[bot] ***@***.***>
发送时间: Monday, February 13, 2023 4:57:10 PM
收件人: ant-design/ant-design ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [ant-design/ant-design] feat: App support style props and export props type (PR #40708)


Codecov<https://codecov.io/gh/ant-design/ant-design/pull/40708?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design> Report

Base: 100.00% // Head: 100.00% // No change to project coverage 👍

Coverage data is based on head (a791fc0)<https://codecov.io/gh/ant-design/ant-design/pull/40708?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design> compared to base (0fed01f)<https://codecov.io/gh/ant-design/ant-design/commit/0fed01f47bd69606e2bd74b53813f257ab4be837?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design>.
Patch coverage: 100.00% of modified lines in pull request are covered.

Additional details and impacted files

@@            Coverage Diff            @@

##            master    #40708   +/-   ##

=========================================

  Coverage   100.00%   100.00%

=========================================

  Files          606       606

  Lines        10289     10289

  Branches      2790      2790

=========================================

  Hits         10289     10289

Impacted Files<https://codecov.io/gh/ant-design/ant-design/pull/40708?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design>    Coverage Δ
components/app/index.tsx<https://codecov.io/gh/ant-design/ant-design/pull/40708?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design#diff-Y29tcG9uZW50cy9hcHAvaW5kZXgudHN4>    100.00% <100.00%> (ø)

Help us with your feedback. Take ten seconds to tell us how you rate us<https://about.codecov.io/nps?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design>. Have a feature suggestion? Share it here.<https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design>

☔ View full report at Codecov<https://codecov.io/gh/ant-design/ant-design/pull/40708?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design>.
📢 Do you have feedback about the report comment? Let us know in this issue<https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design>.

**Comment by li-jia-nan** [comment]
没必要吧，这个组件一般是最外层的，通常情况不会单独拿来转发吧

**Comment by afc163** [comment]
为啥要支持 style？

**Comment by li-jia-nan** [comment]
用了 App 之后，整个应用高度塌了，给 App 设置了 height: 100% 就好了

**Comment by luo3house** [comment]
> 为啥要支持 style？

https://github.com/ant-design/ant-design/pull/40458#discussion_r1104120810

**Comment by afc163** [comment]
发到 feature 分支吧

**Comment by li-jia-nan** [comment]
求+1

**Review by MadCcc — APPROVED** [review]

**Comment by MadCcc** [comment]
Conflict

**Pull request merged**
