### PR TITLE
removed deprecated --dev

### PR DESCRIPTION
**Pull request by eldyvoon**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

### CODE REVIEW

**Comment by afc163** [comment]
Please update `use-with-create-react-app.zh-CN.md` too.

**Comment by paranoidjk** [comment]
why open  dulplicate PR ? https://github.com/ant-design/ant-design/pull/7013

**Comment by afc163** [comment]
You should update it in the same PR.

**Comment by paranoidjk** [comment]
> If you are used to using npm you might be expecting to use --save or --save-dev. These have been replaced by yarn add and yarn add --dev. For more information, see the yarn add documentation.

https://yarnpkg.com/en/docs/cli/install

**Pull request closed without merging**
