### PR TITLE
Fix moment require

### PR DESCRIPTION
**Pull request by yesmeck**
Fix #9502

### CODE REVIEW

**Comment by dengfuping** [comment]
@yesmeck This PR makes `npm run test-all` failed and new version could not be released.

**Comment by dengfuping** [comment]
@yesmeck How to solve it?

**Comment by yesmeck** [comment]
已经好了，等 CI 跑完。

**Comment by juliocanares** [comment]
guys when will this be released 🙏 😄 ?

**Comment by juliocanares** [comment]
awesome 🙌 @yutingzhao1991

**Comment by KevinBon** [comment]
I'm having the same issue with TimePicker.

bugantd

**Comment by yutingzhao1991** [comment]
@KevinBon what your antd version? try to reinstall node_modules for use antd@3.3.0.

**Comment by KevinBon** [comment]
@yutingzhao1991 I use antd@3.3.0

**Comment by yesmeck** [comment]
@KevinBon My fault, forgot TimePicker. Will be fixed in next release(this weekend)

**Comment by klujanrosas** [comment]
@yesmeck I think we'd need to also update `LocaleProvider`, it's currently calling

```js
function setMomentLocale(locale: Locale) {
  if (locale && locale.locale) {
    moment.locale(locale.locale);
  } else {
    moment.locale('en');
  }
}
```

Change it to use the `interopDefault` safe caller, like

```js
function setMomentLocale(locale: Locale) {
  if (locale && locale.locale) {
    interopDefault(moment).locale(locale.locale);
  } else {
    interopDefault(moment).locale('en');
  }
}
```

**Pull request merged**
