### PR TITLE
Add mode in getDerivedStateFromProps

### PR DESCRIPTION
**Pull request by susiwen8**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

Change mode at father component did't change mode in child component
### 💡 Solution
Add mode in getDerivedStateFromProps

### 📝 Changelog

- English Changelog: Fix DatePicker mode didn't change
- Chinese Changelog (optional):

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by susiwen8** [comment]
This PR is trying to fix this bug. 
https://github.com/ant-design/ant-design/issues/16492

**Comment by zombieJ** [comment]
Need test case for this.

**Comment by susiwen8** [comment]
@zombieJ This is embarrassed cause I found out this PR is not a solution, cause real problem is in rc-calendar, and I'm working on it, but I do have one question need you to answer, RangePicker need support time mode? Right now it seems not support it yet.

**Comment by susiwen8** [comment]
@zombieJ https://github.com/react-component/calendar/pull/571 new PR

**Pull request closed without merging**
