### PR TITLE
type(select): supplementary mode type

### PR DESCRIPTION
**Pull request by thinkasany**
### 🤔 This is a ...

- [x] TypeScript definition update

### 💡 Background and solution
下面的代码将使用对象解构将 props.mode 的值分配给变量 m, 其实可以补充一下 `combobox` ,感觉比用any好
image
image

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at a12b172</samp>

Enhanced `Select` component to support `'combobox'` mode and improved code quality in `components/select/index.tsx`.

### <samp>🤖 Generated by Copilot at a12b172</samp>

* Add a combobox mode to the `Select` component, which combines a single-select and an input box ([link](https://github.com/ant-design/ant-design/pull/43413/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0L46-R46), [link](https://github.com/ant-design/ant-design/pull/43413/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0L121-R121),                                         F1L243

### CODE REVIEW

**Comment by yoyo837** [comment]
#18658 @zombieJ

**Review by yoyo837 — APPROVED** [review]

**Comment by afc163** [comment]
不推荐用 combobox 了，combobox 模式可以直接用 AutoComplete 组件。

**Comment by thinkasany** [comment]
> combobox
但是InternalSelectProps似乎只是内部的ts类型，不影响对外部的提示
image

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
你说得对。

**Pull request merged**
