### PR TITLE
test:  📦 use ESBUILD in codesandbox ci

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/pull/24666#issuecomment-637306521

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
还是爆栈..

**Comment by afc163** [comment]
无解。

**Comment by xrkffgg** [comment]
😂

**Comment by zombieJ** [comment]
好像也没有配置 node 版本的地方

**Comment by hengkx** [comment]
` --max_old_space_size=4096` 加上这个 行不

**Comment by yoyo837** [comment]
node好像和java一样，运行初始化时根据实际物理内存分开各种需要的内存空间以物理内存的占比。

**Comment by shaodahong** [comment]
换掉 `uglifyjs-webpack-plugin` 试试

**Comment by shaodahong** [comment]
换掉 `uglifyjs-webpack-plugin` 试试

**Comment by afc163** [comment]
搞定了，加大块就行了：#24687

**Pull request merged**
