### PR TITLE
docs: typo of Typography

### LINKED ISSUE #24882: Wrong spelling in the doc
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/typography/demo/basic.md](https://github.com/ant-design/ant-design/blob/master/components/typography/demo/basic.md)

### Steps to reproduce
In the typography demo part, it should be Press <Text keyboard>Esc</Text> to exit...not to exist. 

### What is expected?
So please change "exist" to "exit"

### What is actually happening?
wrong spelling

| Environment | Info |
|---|---|
| antd | undefined |
| React | any |
| System | any |
| Browser | any |

### PR DESCRIPTION
**Pull request by fireairforce**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix #24882

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   None        |
| 🇨🇳 Chinese |      无     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/typography/demo/basic.md](https://github.com/fireairforce/ant-design/blob/docs-change/components/typography/demo/basic.md)

### CODE REVIEW

**Comment by yoyo837** [comment]
更新snap

**Comment by fireairforce** [comment]
done~wait for ci.

**Review by 0xPoe — APPROVED** [review]
CI 应该是因为其他原因挂了，LGTM.

**Review by xrkffgg — APPROVED** [review]

**Comment by fireairforce** [comment]
rebase了一下

**Comment by fireairforce** [comment]
等ci跑完吧～

**Pull request merged**
