### PR TITLE
feat: Add "tooltipProps" prop to slider props

### PR DESCRIPTION
**Pull request by MorisR**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#33298
#18016

### 💡 Background and solution
Explained in the issues above 

### 📝 Changelog

Add "tooltipProps" prop to "slider" component.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MorisR** [comment]
@afc163 can you approve/review?

**Comment by afc163** [comment]
Please add a test case.

**Comment by MorisR** [comment]
@afc163 good enough?

**Comment by afc163** [comment]
We need to deperacate `tooltipPlacement` and `tooltipVisible` too.

Maybe rename `tooltipProps` to `tooltip`.

**Comment by afc163** [comment]
We need to deperacate `tooltipPlacement` and `tooltipVisible` too.

Maybe rename `tooltipProps` to `tooltip`.

**Comment by afc163** [comment]
ping @MorisR

**Comment by MorisR** [comment]
I'll do it, just need more time, work and all + holidays

**Comment by afc163** [comment]
ping @MorisR

**Comment by afc163** [comment]
ping @MorisR

**Comment by afc163** [comment]
ping @MorisR

**Comment by MorisR** [comment]
I know.. I know...
I'll get to it when/if I can..
Believe me.. didn't have ANY free time on my hands lately...
From working 14 hours a day to trying to maintain/squeeze in some personal time

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/37043

**Pull request closed without merging**
