### PR TITLE
[WIP] [5.0] feat(theme): Design Token support gradient color

### PR DESCRIPTION
**Pull request by dengfuping**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

- Support gradient color for potential business scenarios:
    - [x] Background gradient color: `backgroundColor` => `background`.
    - [ ] TODO: Border gradient color
    - [ ] TODO: Font gradient color

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | 🔥 Design Token support gradient color. #38644        |
| 🇨🇳 Chinese | 🔥 Design Token 支持渐变色。#38644          |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
冲突了，重提一个？

**Comment by dmytro-machulskyi** [comment]
any progress or maybe fixing the conflicts and merge?...

**Comment by afc163** [comment]
先关了，欢迎重新创建新 PR。

**Comment by momargoh** [comment]
@dengfuping can you open this PR again to try to get it merged, it seems it failed because it has "WIP" in the title, so rename and try again. I'd love to see this feature implemented!

**Pull request closed without merging**
