### PR TITLE
am_ET

### PR DESCRIPTION
**Pull request by henoktsegaye**
this would be a local string for amharic language in Ethiopia

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [yes ] Other (about what?)
this is another local language for internationalization feature , this language is amharic which is the official language of Ethiopia 

### 👻 What's the background?

1. Describe the source of requirement, like related issue link.
i make this to just add amharic , as also i am using this library , hope others can found it helpful
2. Describe the problem and the scenario.
there was no amharic language string to get started with , so i just added that
### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.
i just copied other languages and changed only the language strings with the name of the local that is it!
2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description
users can use amharic language for their react application by just stating the local as they would do normally
2. Chinese description (optional)

### ☑️ Self Check before Merge

- [ yes] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Please send this to feature branch and add test case like other locales.

**Comment by afc163** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 60c7276e610e66f7979c6b8a6dfd20c68a2657a6 into 102c342e6e4c12f653a58b6b277a4f66837c9159 - [view on LGTM.com](https://lgtm.com/projects/g/ant-design/ant-design/rev/pr-5987ac0c46c3d01da04c4f766e63ab62fb7f90b1)

**new alerts:**

* 1 for Potentially inconsistent state update

**fixed alerts:**

* 1 for Potentially inconsistent state update

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by afc163** [comment]
Please clean unrelated commits.

**Review by afc163 — CHANGES_REQUESTED** [review]
Please clean unrelated commits.

**Comment by dengfuping** [comment]
@henoktsegaye ping ~

**Comment by henoktsegaye** [comment]
i don't understand you guys , what am i supposed to do here

**Comment by henoktsegaye** [comment]
i already stated that this is just another language support , not a feature in the list above

**Comment by afc163** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 5f95a89cfc879c72d2f3f829648ffcbddb3dcc6b into addc7bd26608e6057076708e6af00c37c732dbeb - [view on LGTM.com](https://lgtm.com/projects/g/ant-design/ant-design/rev/pr-ec3c8150683617af2af4894af37f8f3fba533b77)

**new alerts:**

* 1 for Potentially inconsistent state update

**fixed alerts:**

* 1 for Potentially inconsistent state update

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request closed without merging**
