### PR TITLE
up minimal version scroll-into-view-if-needed

### LINKED ISSUE #41665: add typedoc support
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/peaceful-violet-p9iwxy?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A26%2C%22endLineNumber%22%3A22%2C%22startColumn%22%3A26%2C%22startLineNumber%22%3A22%7D%5D)

### Steps to reproduce

add typedoc to your ts project with antd
add `typedoc.json`
```json
{
  "entryPoints": ["./index.tsx"],
  "excludeExternals": true,
  "out": "docs"
}
```
*Note* Don't forgot set entry points if it's different
add in `package.json` script
```json
"docs":  "typedoc",
```
execute
```shell
npm run docs
```

### What is expected?

typedoc without error

### What is actually happening?

```javascript
node_modules/antd/es/config-provider/context.d.ts:3:30 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("scroll-into-view-if-needed")' call instead.

3 import type { Options } from 'scroll-into-view-if-needed';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/antd/es/config-provider/index.d.ts:3:30 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("scroll-into-view-if-needed")' call instead.

3 import type { Options } from 'scroll-into-view-if-needed';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/antd/es/form/Form.d.ts:4:30 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("scroll-into-view-if-needed")' call instead.

4 import type { Options } from 'scroll-into-view-if-needed';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/antd/es/form/interface.d.ts:2:47 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("scroll-into-view-if-needed")' call instead.

2 export type { Options as ScrollOptions } from 'scroll-into-view-if-needed';
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | Kubuntu 22.04 |
| Browser | Chrome 108.0.0.0 |

### PR DESCRIPTION
**Pull request by long76**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
fix #41665

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |fix typedoc compile|
| 🇨🇳 Chinese |修复typedoc编译|

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 1fd4bbb</samp>

Updated `scroll-into-view-if-needed` dependency to fix a scrolling bug in `TreeSelect`. Improved the visibility of selected nodes in the tree.

### <samp>🤖 Generated by Copilot at 1fd4bbb</samp>

* Update the `scroll-into-view-if-needed` dependency to fix a scrolling bug in the `TreeSelect` component ([link](https://github.com/ant-design/ant-design/pull/41716/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L156-R156))

### CODE REVIEW

**Comment by long76** [comment]
> * 🚨 Please fill changelog in the PR
>   
>   * Write with a **developer-oriented perspective** and **narrative method**, without describing the details of the repair
>   * **Describing the problem and the impact on the developer**
>   * **describing the user-first site problem**, not your solution
>   * Refer: https://ant.design/changelog#501
> * 🚨 请填写 PR 中的 changelog
>   
>   * 请用**面向开发者的角度**和**叙述方式撰写**，不描述修复细节
>   * **描述问题和对开发者的影响**
>   * **描述用户第一现场的问题**，而非你的解决方式
>   * 参考：https://ant.design/changelog-cn#501

done

**Comment by li-jia-nan** [comment]
patch 本来就没锁，这里默认安装的就是 3.0.8，这么改是没有意义的

**Comment by li-jia-nan** [comment]
- #41715 重复了，这里已经在修了

**Comment by long76** [comment]
@li-jia-nan for fix `test-argos-ci-workflow` possible need https://github.com/ant-design/ant-design/pull/41716#issuecomment-1501051216

**Comment by long76** [comment]
@li-jia-nan for fix `test-argos-ci-workflow` possible need https://github.com/ant-design/antd-tools/pull/272

**Comment by long76** [comment]
obsolete

**Pull request closed without merging**
