### PR TITLE
feat(FloatButtonGroup): onClick prop

### PR DESCRIPTION
**Pull request by Riyad-Arafat**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix: missing onClick in FloatButtonGroup    |
| 🇨🇳 Chinese |       修復：在浮動按鈕組中缺少單擊    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Wxh16144** [comment]
The documentation does not indicate that `FloatButton.Group` has click as a props, is this a new props api? Need to participate in the discussion. Also need to add a unit test.

**Comment by riyadelberkawy** [comment]
> The documentation does not indicate that `FloatButton.Group` has click as a props, is this a new props api? Need to participate in the discussion. Also need to add a unit test.

Sure, I understand your concern regarding the new `onClick` prop. The reason I added this prop is to enable the ability to update the `open` prop when clicking on the button. In some cases, this behavior may be required, and the `onClick` prop provides a convenient way to handle it.

**Comment by riyadelberkawy** [comment]
I have added tests for the FloatButton.Group component and updated the documentation to include the new onClick prop. The tests ensure that the prop is functioning correctly. Please let me know if there are any other changes needed.

**Comment by yoyo837** [comment]
`feature` branch Pls.

**Comment by yoyo837** [comment]
Commits should be clean.

**Comment by riyadelberkawy** [comment]
How can I do that?. May you suggest?

**Comment by yoyo837** [comment]
Rebase from upstream/feature and push it force.

**Comment by riyadelberkawy** [comment]
@yoyo837 
Hi, I'm just checking out why it closed, did I do something wrong or did the workflow cause it?

**Comment by riyadelberkawy** [comment]
@afc163 @zombieJ @MadCcc @xrkffgg @yoyo837 
Could you please help with this PR?

**Comment by yoyo837** [comment]
Please open a new one for this.

**Pull request closed without merging**
