### PR TITLE
feat: Table summary support align

### LINKED ISSUE #26866: Add align prop for Summary.Cell
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to customise the text-align of every `Summary.Cell`. For example, some is center, some is right.

### What does the proposed API look like?
<Summary.Cell align="right" />

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

close #26866
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #26866

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Table.Summary.Cell support `align` prop.        |
| 🇨🇳 Chinese |    Table.Summary.Cell 支持 `align` 配置。     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
最好把 https://github.com/react-component/table/pull/503 一起搞了，这个更实用。

**Review by xrkffgg — APPROVED** [review]

**Comment by zombieJ** [comment]
> 最好把 [react-component/table#503](https://github.com/react-component/table/pull/503) 一起搞了，这个更实用。

`rc-table` 发过版了，这个先合了。那个我瞅瞅再发个版本。

**Review by hengkx — APPROVED** [review]

**Comment by hengkx** [comment]
close #26866

**Comment by dongxiaoyong009** [comment]
顶一个，今天刚遇到这个 Summary 不能设置 align 的问题， 最好可以默认继承 table的 columns里的 align 配置。 因为单独在配置一遍有些繁琐

**Comment by ps2qwert** [comment]
> > 最好把 [react-component/table#503](https://github.com/react-component/table/pull/503) 一起搞了，这个更实用。
> 
> `rc-table` 发过版了，这个先合了。那个我瞅瞅再发个版本。

问下这个合了嘛，Summary定位不起作用啊

**Pull request merged**
