### PR TITLE
test(affix): migrate tests to testing-library

### PR DESCRIPTION
**Pull request by RexSkz**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
@zombieJ @afc163 大佬麻烦review一下

**Comment by RexSkz** [comment]
That's weird, the test cases is passed:

```ts
updateCalled.mockReset();
triggerResize(affixMounterWrapper.container);
await sleep(20);

expect(updateCalled).toHaveBeenCalled();
```

This means the `updateCalled` should be called DURING THE RESIZING. But codecov said these lines won't be covered:

image

**Comment by afc163** [comment]
一 rebase CI 就不跑了。。。

**Comment by afc163** [comment]
最好重发一个 PR 看看覆盖率

**Comment by RexSkz** [comment]
ok

**Comment by RexSkz** [comment]
New PR: https://github.com/ant-design/ant-design/pull/37299

**Pull request closed without merging**
