### PR TITLE
feat: update  @ant-design/icons@4.0.0-alpha.13

### PR DESCRIPTION
**Pull request by vagusX**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (update @ant-design/icons@4.0.0-alpha.13)

### 💡 Background and solution
根据 https://github.com/ant-design/ant-design-icons/blob/91c5ff8d587a6ee8d197c8971c8e9fedd0c3ec04/packages/icons-svg/build/strategies.ts#L46 描述，需要对测试用例的 snap 进行更新，这一块的更新也是 icons 本身[这 7 个图标](https://github.com/ant-design/ant-design-icons/blob/91c5ff8d587a6ee8d197c8971c8e9fedd0c3ec04/packages/icons-svg/build/constants.ts#L2)的 breaking changes

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    none       |
| 🇨🇳 Chinese |    无       |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by vagusX** [comment]
ping @HeskeyBaozi 可以帮忙补充下breaking change的原因嘛

**Comment by vagusX** [comment]
image

image

**Comment by HeskeyBaozi** [comment]
be88393df5358c4e7c40bf2a4b321905
主要影响树形控件和表格表头排序。这些图标都是 `3.9` 以前的旧图标。现在调整至和其他图标一致的`path box / svg box` 比率，即`viewBox`修正为`64 64 896 896`，使得这些旧图标与其他已经在线上广泛使用的图标保持一致。
> 为什么是 `64 64 896 896`? [相关issue](https://github.com/ant-design/ant-design/issues/12053#issuecomment-418971714)

**Comment by afc163** [comment]
> 主要影响树形控件和表格表头排序

那这些地方的 fontSize 要相应调整一下。

**Comment by zombieJ** [comment]
`@ant-design/icons@4.0.0-alpha.13` 已经对 `4.0-prepare` snapshot 产生影响了。先合了。再开个 PR 来修一下部分图标的大小。 @vagusX

**Pull request merged**
