### PR TITLE
refactor(rate): improve code

### PR DESCRIPTION
**Pull request by hengkx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by hengkx** [comment]
image
@shaodahong 这个我怎么解决

**Comment by afc163** [comment]
image

这个链接是不是应该是 jest-image-snapshot 的那个链接。

**Comment by hengkx** [comment]
我都没发现 失败了 这也是pass

**Comment by hengkx** [comment]
这个代码应该是没问题的把。。。。

**Comment by shaodahong** [comment]
> 
> 这个链接是不是应该是 jest-image-snapshot 的那个链接。

只有失败的时候才会连接到 report 链接，看 azure 的 log 是通过的

**Comment by shaodahong** [comment]
晚上我优化下，不管失败还是成功都把 report 链接出来

**Comment by shaodahong** [comment]
找到问题了，azure 链接导致的重试，这个 failed 是第一次的 failed

image

**Pull request merged**
