### PR TITLE
fix: Styling issue where all spans next to a checkbox wrapper get a padding

### LINKED ISSUE #17714: Checkbox and Input with prefix together will make a position bug.
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/embed/antd-checkbox-searchinput-bug-yb79c)

### Steps to reproduce
 There are some simple code:
```js
    <Checkbox>我创建的</Checkbox>
    <Input
      placeholder="搜索"
      prefix={<Icon type="search" />}
      style={{ width: 206 }}
    />
```
[This](https://codesandbox.io/embed/antd-checkbox-searchinput-bug-yb79c) is complete code.

image

The icon has a wrong position because of some CSS code:

image

Although I can provide this problem use following code, I hope you can fix this as quickly as possible, thanks.

```js
    <span>
      <Checkbox>我创建的</Checkbox>
    </span>
    <Input
      placeholder="搜索"
      prefix={<Icon type="search" />}
      style={{ width: 206 }}
    />
```

### What is expected?
image

### What is actually happening?
image

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.8.6 |
| System | mac |
| Browser | 75.0.3770.100  |

### PR DESCRIPTION
**Pull request by inovux**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

closes #17714

### 💡 Background and solution

- See issue #17714 for background
- Removed padding for ```.ant-checkbox-wrapper + span```, since I don't see it being used anywhere. This style should be only available on the ```.ant-checkbox + span``` class.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片

It will break https://deploy-preview-17752--ant-design.netlify.com/components/table/#components-table-demo-reset-filter

**Comment by inovux** [comment]
> 图片
> 
> It will break https://deploy-preview-17752--ant-design.netlify.com/components/table/#components-table-demo-reset-filter

Yep, you are right. I think it would be good to handle this particular case only instead of giving all spans after the ```.ant-checkbox-wrapper``` a padding. 

What about giving the span in that table a class and only style it with extra padding when it's preceded by a checkbox?

**Comment by afc163** [comment]
> What about giving the span in that table a class and only style it with extra padding when it's preceded by a checkbox?

Fair enough, could you update your PR for this?

**Comment by inovux** [comment]
It automatically merged? I still wanted to add one more change.

**Comment by afc163** [comment]
You can create another pull request.

**Comment by inovux** [comment]
> You can create another pull request.

Ahh okay thabks, sorry im new to this. Like to learn from it :)

**Pull request merged**
