### PR TITLE
Fix icon shake in site

### PR DESCRIPTION
**Pull request by ztplz**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

1. Describe the source of requirement, like related issue link.
https://github.com/ant-design/ant-design/issues/15485

2. Describe the problem and the scenario.

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description

2. Chinese description (optional)

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
h2的默认size就是24px

**Comment by ztplz** [comment]
image
我把h2元素删掉 它就正常了  很玄学。。。

**Comment by zombieJ** [comment]
这样治标不治本的，应该是 dom-align 对齐的像素带小数的问题。

**Comment by zombieJ** [comment]
https://codesandbox.io/s/p5q05wx1kx

**Comment by ztplz** [comment]
应该是一个问题  在x.5 ~ x + 1之间就有问题

**Comment by ztplz** [comment]
确实是浮点数的问题

**Comment by ztplz** [comment]
刚看了下dom-align  里面有些代码是为了ie9- 的  感觉没必要了 @zombieJ  
image

**Comment by zombieJ** [comment]
> 刚看了下dom-align 里面有些代码是为了ie9- 的 感觉没必要了 @zombieJ
> image

dom-align 不只是 antd 在用，它是个基础库。兼容要求和我们不太一样。

**Comment by zombieJ** [comment]
我们先 close 这个 issue 吧，免得不小心合了 @ztplz

**Pull request closed without merging**
