### PR TITLE
feat: added badge custom overflow count descriptor

### PR DESCRIPTION
**Pull request by Surm4**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a feature

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    added custom `overflowCount` descriptor in the Badge component  |
| 🇨🇳 Chinese |    在 Badge 组件中添加了自定义的 `overflowCount` 描述符       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Please rebase feature branch.

**Comment by Surm4** [comment]
> Please rebase feature branch.

ok @afc163, rebased

**Comment by afc163** [comment]
What `overflowCountDescriptor`is used for? Could you describe a real situation?

**Comment by Surm4** [comment]
> What `overflowCountDescriptor`is used for? Could you describe a real situation?

I just want to create another step of displaying count in my application eg. 
```jsx
// count < 10 has no "+"
// count > 10  has "+"
// count > 100 has "+"

...
const count = 100
const overflowCountDescriptor = count > 100 ? '+ 🔥' : '+'
const overflowCount = count > 100 ? 10 : 99

<Badge overflowCount={overflowCount} overflowCountDescriptor={overflowCountDescriptor} count={count}>
    <Avatar shape="square" size="large" />
</Badge>
...
```
image

**Comment by afc163** [comment]
冲突了

**Comment by li-jia-nan** [comment]
Hey! Conflicting files, and it seems this is now really outdated. If this is something that still makes sense to the latest master version of antd, please send a new PR with this change :)

**Pull request closed without merging**
