### PR TITLE
docs: fix Import in Browser link not found

### PR DESCRIPTION
**Pull request by yoyo837**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/24116#issuecomment-642450269

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fix "import in browser" not found       |
| 🇨🇳 Chinese |     修复“在浏览器种使用”文档链接不可用     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered docs/react/faq.en-US.md](https://github.com/ant-design/ant-design/blob/fix-Import-in-Browser-link/docs/react/faq.en-US.md)
[View rendered docs/react/faq.zh-CN.md](https://github.com/ant-design/ant-design/blob/fix-Import-in-Browser-link/docs/react/faq.zh-CN.md)

### CODE REVIEW

**Comment by yoyo837** [comment]
@shaodahong UI test 通过但仍然收到失败邮件

**Comment by shaodahong** [comment]
这个是什么，circleci ?

**Comment by yoyo837** [comment]
> 这个是什么，circleci ?

是

**Comment by shaodahong** [comment]
嗯，那不是 UI_TEST 报的，我只在 azure 里面设置了

**Comment by shaodahong** [comment]
你这个失败的原因是你分支已经合并并且被删除了，测试的时候拉取不到报的错

**Comment by yoyo837** [comment]
> 你这个失败的原因是你分支已经合并并且被删除了，测试的时候拉取不到报的错

恍然大悟。

**Pull request merged**
