### PR TITLE
fix: The 'indentSize' in the Table component couldn't be zero value

### PR DESCRIPTION
**Pull request by OmriGM**
- Changed to indentSize prop logic of the Table component to also include zero values

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/25798

### 💡 Background and solution

Before:
```javascript
 mergedExpandable.indentSize = mergedExpandable.indentSize || indentSize || 15; 
```
After:
```javascript
  if (mergedExpandable.indentSize === null || mergedExpandable.indentSize === undefined) {
    mergedExpandable.indentSize = indentSize !== null && indentSize !== undefined ? indentSize : 15;
  }
```

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
CI failed, please check it.

**Comment by OmriGM** [comment]
> CI failed, please check it.

@afc163 It fails due to snapshot mismatch but when I'm running: ```npm test -- -u``` and ```npm run test-node -- -u``` locally, none of the snapshots updating and all the tests passes.

**Comment by afc163** [comment]
Please rebase antd master branch, remove `node_modules`, `package-lock.json`, `yarn.lock` and then reinstall.

**Comment by OmriGM** [comment]
I've removed a test that tries to simulate a click on the expand icon when no children is rendered for a row because of this commit: https://github.com/react-component/table/commit/ffdedc23342b97f8b2de6cfbf44bc9fe61acc62f in `rc-table` (which is included in the version that ant-design uses). The code in this commit avoids rendering of the expand icon when there are no children so there is no option to simulate a click on it in the Table's tests.

**Comment by zombieJ** [comment]
hi @OmriGM, eslint updated which get this error. You can hold a while since we are working on master branch to fix it.

**Comment by afc163** [comment]
Please resolve conflicts.

**Comment by zombieJ** [comment]
`4.5.0` released. You can rebase now : )

**Comment by afc163** [comment]
oops

**Pull request closed without merging**
