### PR TITLE
fix: Fix crash when mismatch placement

### LINKED ISSUE #23541: Fatal exception thrown when tooltip is shown after upgrading to antd 4.1.4
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/basic-ant-design-demo-jk4qn?file=/index.js

### Steps to reproduce
https://ant.design/components/tooltip/

### What is expected?
Tooltip to be shown. This was working in ant design version 3.x

### What is actually happening?
This exception is thrown:
```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Tooltip._this.onPopupAlign (index.js:149)
    at Popup._this.onAlign (Popup.js:87)
    at Align.js:77
    at trigger (useBuffer.js:12)
    at Object.forceAlign (Align.js:152)
    at Popup.<anonymous> (Popup.js:79)
    at callCallback (react-dom.development.js:12490)
    at commitUpdateQueue (react-dom.development.js:12511)
    at commitLifeCycles (react-dom.development.js:19858)
    at commitLayoutEffects (react-dom.development.js:22803)

react-dom.development.js:19527 The above error occurred in the <Popup> component:
    in Popup (created by Trigger)
    in Portal (created by Trigger)
    in Trigger (created by ForwardRef(Tooltip))
    in ForwardRef(Tooltip) (created by Context.Consumer)
    in Tooltip (created by HCTooltip)
    in div (created by storyFn)
    in div (created by storyFn)
    in storyFn
    in ErrorBoundary

```

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | OSX 10.14.5 |
| Browser | Chrome Version 81.0.4044.113  |

### PR DESCRIPTION
**Pull request by yoyo837**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
close #23541

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix crash when mismatch placement      |
| 🇨🇳 Chinese |    修复 `Tooltip` 的 `align` 未匹配到支持的 `placement` 时异常的问题      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
加个 测试用例，今天准备发 minor，争取这次就合进来。

**Comment by yoyo837** [comment]
npm cnpm 都不行，跑不过。

**Comment by yoyo837** [comment]
应该是切换分支3.x-stable编译的jsx干扰了。

**Comment by zombieJ** [comment]
`git clean -fdx` 后，npm install 应该就好了。

**Pull request merged**
