### PR TITLE
Added Mongolian locale provider and tested.

### PR DESCRIPTION
**Pull request by digz6666**
Added Mongolian locale provider and tested.
Translated calender, date-picker, time-picker components.

Also added Mongolian translation of rc-calender and rc-pagination components.
https://github.com/react-component/calendar/pull/411
https://github.com/react-component/pagination/pull/144

### CODE REVIEW

**Comment by zombieJ** [comment]
Hi,
CI failed, pls check

**Comment by digz6666** [comment]
@zombieJ When I check the test output it matches with my defined values.
It says following in the log and I don't understand :)
```
  ● Locale Provider › should display the text as mn-mn
    expect(value).toMatchSnapshot()
    New snapshot was not written. The update flag must be explicitly passed to write a new snapshot.
    This is likely because this test is run in a continuous integration (CI) environment in which snapshots are not written by default.
```

**Comment by zombieJ** [comment]
test case will check current code match snapshot or not. Since this locale is first added. Just run follow code to update snapshot:
```bash
npm test -- -u
```

**Comment by digz6666** [comment]
@zombieJ I ran the npm test -- -u and npm test on my local clone and it passes.

Result of npm test -- -u:
local_test

Result of npm test:
local_test_2

What can I do?

**Comment by digz6666** [comment]
Seems like people experiencing similar issues: https://github.com/facebook/jest/issues/5270

**Comment by zombieJ** [comment]
Let me handle this : )

**Comment by digz6666** [comment]
@zombieJ thank you, you rock!

**Pull request merged**
