### PR TITLE
[WIP]feat: Replace classnames with cnbuilder

### PR DESCRIPTION
**Pull request by xobotyi**
### 🤔 This is a ...

- [x] Performance improvement

Replace `classnames` package with `cnbuilder`, it is faster at least 3-5 times (benchmarks can be found [here](https://github.com/xobotyi/cnbuilder/tree/master/benchmark)).

### 💡 Background and solution

Ofcourse it won't drastically improve the performance, but it is worth of changing because used in every render.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Render performance improvement      |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/20301#issuecomment-569003081

**Comment by xobotyi** [comment]
@yoyo837 the idea is to have more performant code.
I have opened performance [PR](https://github.com/JedWatson/classnames/pull/197) to classnames, but they're hang there for more than half a year and looks like wont be merged.

It's not a problem to update deps if this PR will be merged.

**Comment by zombieJ** [comment]
Thanks for PR. Currently we do not have plan for replace `classnames`.
But I see your [PR](https://github.com/JedWatson/classnames/pull/197) for `classnames` which is a better way. Let's ping the maintainer again : )

**Comment by hc-codersatlas** [comment]
If there's going to be a replacement, it would be good to compare it to other solutions e.g. [cslx](https://github.com/lukeed/clsx) too.

**Comment by xobotyi** [comment]
@hc-codersatlas it is in benchmarks. cnbuilder is faster.

**Comment by hc-codersatlas** [comment]
@xobotyi which benchmarks are you referring to? The 1 that was run with nodejs 13 as linkedin in cnbuilder? Please run an actual frontend benchmark that runs in a browser. There could be differences.

**Pull request closed without merging**
