### PR TITLE
fix: input verification failed style when mouse hover

### PR DESCRIPTION
**Pull request by Fog3211**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
补充 [#30294](https://github.com/ant-design/ant-design/issues/30294)  

gif

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix the hover background color problem after the input component verification fails in the disabled state   |
| 🇨🇳 Chinese |  修复disabled状态下Input组件校验失败后hover背景色问题 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/30298

@DerrickTel @Fog3211 你俩的修复哪个更完整一点？

**Comment by Fog3211** [comment]
> #30298
> 
> @DerrickTel @Fog3211 你俩的修复哪个更完整一点？

两个都不完整，我的是在他的上面补充了一种情况

**Comment by afc163** [comment]
你这里合并一下吧。

**Comment by Fog3211** [comment]
@afc163 [https://github.com/ant-design/ant-design/pull/30302](https://github.com/ant-design/ant-design/pull/30302)

**Pull request closed without merging**
