### PR TITLE
refactor: Upload ListItem timeout optimization

### PR DESCRIPTION
**Pull request by linxianxi**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |     -      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at d1714a8</samp>

Refactored the progress bar logic in `ListItem.tsx` to use `setTimeout` instead of `useRef` and avoid memory leaks.

### <samp>🤖 Generated by Copilot at d1714a8</samp>

*  Removed `progressRafRef` and `useRef` hook to avoid memory leaks and simplify code ([link](https://github.com/ant-design/ant-design/pull/42915/files?diff=unified&w=0#diff-958fc631d437799c784b9bd5b685e7e31d2a365e4eb2a3d8424c970e8d037862L85-R90))
*  Replaced `progressRafRef` with `timer` and `setTimeout` to create and clear delay for progress bar ([link](https://github.com/ant-design/ant-design/pull/42915/files?diff=unified&w=0#diff-958fc631d437799c784b9bd5b685e7e31d2a365e4eb2a3d8424c970e8d037862L85-R90))

### CODE REVIEW

**Comment by li-jia-nan** [comment]
为啥要改这个？有什么问题吗？

**Comment by linxianxi** [comment]
> 为啥要改这个？有什么问题吗？

没问题。只是正好看到了，优化一下，不需要使用 useRef

**Comment by yoyo837** [comment]
> > 为啥要改这个？有什么问题吗？
> 
> 没问题。只是正好看到了，优化一下，不需要使用 useRef

哥们儿应该是有轻微代码洁癖的哈, (褒义词)

**Comment by linxianxi** [comment]
昨天用 4.x 的 Upload 上传进度条遇到问题，看了下源码研究问题，就看到了

**Review by yoyo837 — APPROVED** [review]

**Comment by li-jia-nan** [comment]
理论上来说这里不用改的， 在 hook 中封装定时器用 useRef 才是最佳实践

**Comment by yoyo837** [comment]
> 理论上来说这里不用改的， 在 hook 中封装定时器用 useRef 才是最佳实践

只在一个mounted effect 里的timer用 useRef 也是最佳实践?

**Comment by linxianxi** [comment]
应该不是的，看 react 最新文档。https://react.dev/learn/synchronizing-with-effects#putting-it-all-together

**Comment by li-jia-nan** [comment]
英文有点差，晚点翻译一下学习学习☹️

**Comment by yoyo837** [comment]
rebase to fix CI.

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
