### PR TITLE
fix(document): select Chinese and then jump to English in faq page

### LINKED ISSUE #42296: 在5.4.7版本中选择中文后，点击其他文章会从中文跳英文
### Reproduction link

[https://ant.design/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-ant-design-%E7%9A%84%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98](https://ant.design/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-ant-design-%E7%9A%84%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98)

### Steps to reproduce

https://ant.design/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-ant-design-%E7%9A%84%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98这个链接进入，切换成中文，点击定制主题，跳转英文

### What is expected?

期望跳转中文

### What is actually happening?

实际跳转英文

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 17.0.2 |
| System | mac |
| Browser | Google |

### PR DESCRIPTION
**Pull request by Ylg12345**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix https://github.com/ant-design/ant-design/issues/42296

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at c874ffe</samp>

Improved the user experience for Chinese readers of the FAQ document by linking to relevant Chinese pages. Changed the `href` attributes of two links in `docs/react/faq.zh-CN.md`.

### <samp>🤖 Generated by Copilot at c874ffe</samp>

* Updated the links to the customize theme and use custom date library pages to point to the Chinese versions in the FAQ document ([link](https://github.com/ant-design/ant-design/pull/42299/files?diff=unified&w=0#diff-d24a54fb235784b2741dc29b3c94dbb9fc2396e2837d68a5ae3f36dd5705d524L46-R46), [link](https://github.com/ant-design/ant-design/pull/42299/files?diff=unified&w=0#diff-d24a54fb235784b2741dc29b3c94dbb9fc2396e2837d68a5ae3f36dd5705d524L66-R66))

### CODE REVIEW

**Review by zombieJ — APPROVED** [review]

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/pull/42298 看看这个, 还有个地方可修改

**Comment by Ylg12345** [comment]
> #42298 看看这个, 还有个地方可修改



> #42298 看看这个, 还有个地方可修改

okay

**Comment by li-jia-nan** [comment]
`See: https://ant.design/docs/react/customize-theme`

这行代码也可以改成：

`See: [customize-theme](/docs/react/customize-theme).`

和中文格式保持一致

**Review by li-jia-nan — APPROVED** [review]

**Comment by zombieJ** [comment]
这个在 dumi 插件侧做转换，Bisheng 以前也是这么做的。人工总会不小心漏掉的。

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
