### PR TITLE
Add missing translation for id and jp

### PR DESCRIPTION
**Pull request by edikurniawan-dev**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     --      |
| 🇨🇳 Chinese |     --      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
So, is this overturning the previous PR #48287 ?

**Comment by edikurniawan-dev** [comment]
> So, is this overturning the previous PR #48287 ?

Yes, because many user say it's better like the original, namely 'OK'.
So the snapshot will be as before

**Comment by yoyo837** [comment]
Personally, it is better to split it into two PRs.

**Comment by edikurniawan-dev** [comment]
What do you mean, Indonesian and Japanese PR are separated?

**Comment by yoyo837** [comment]
> What do you mean, Indonesian and Japanese PR are separated?

Yes.

**Pull request closed without merging**
