### PR TITLE
chore(badge): modify the status of zero

### PR DESCRIPTION
**Pull request by Dreamerryao**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

a==='0' can't handle '00'

### CODE REVIEW

**Comment by xrkffgg** [comment]
CI 挂了

**Comment by Dreamerryao** [comment]
image
测试已通过

**Comment by afc163** [comment]
解决什么问题，请提供重现。

**Comment by Dreamerryao** [comment]
image

**Comment by afc163** [comment]
这应该是预期行为，组件库不应该做过多事情。

**Pull request closed without merging**
