### PR TITLE
fix(docs): add note about prefixCls styles

### PR DESCRIPTION
**Pull request by jyash97**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

 #21036 

### 💡 Background and solution
Add a note about `prefixCls` styles

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/config-provider/index.en-US.md](https://github.com/jyash97/ant-design/blob/patch-1/components/config-provider/index.en-US.md)

### CODE REVIEW

**Comment by yoyo837** [comment]
Please help us to update Chinese docs also.

注意：这将不会应用由antd提供的默认样式。

**Comment by jyash97** [comment]
Hey @yoyo837 I have added the content on Chinese docs as well. Do let me know if this is correct.

**Comment by Witee** [comment]
什么是  "这将不会应用由 antd 提供的默认样式" ?

> Please help us to update Chinese docs also.
> 
> 注意：这将不会应用由antd提供的默认样式。

**Comment by yoyo837** [comment]
比如table组件样式是ant-table，你添加prefixCls为abc, 变成abc-table, css需要你自己定义出来，dom上只有相关class.

**Comment by Witee** [comment]
> 比如table组件样式是ant-table，你添加prefixCls为abc, 变成abc-table, css需要你自己定义出来，dom上只有相关class.

哦, 原来是这样, 刚发现样式丢了. Thx

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/29ef3f74dd538dcc2212bd1faf7ac88470581d31

**Comment by Witee** [comment]
> [29ef3f7](https://github.com/ant-design/ant-design/commit/29ef3f74dd538dcc2212bd1faf7ac88470581d31)

感谢大佬们的回复, 以下是我的实践, 希望能帮到后来人:

1. 使用 `ConfigProvider` 增加全局配置, 增加CSS前缀 `prefixCls="my-prefix"`
```
    <ConfigProvider prefixCls="my-prefix">
      <App />
    </ConfigProvider>
```
此时你的样式前缀应该已经由 `ant` 更换为 `my-prefix`;

2. `craco.config.js` 中增加配置如下, 自动修改样式中的前缀
注意 `plugins` 与 `webpack` 在同一级别.
```
const CracoLessPlugin = require('craco-less');

module.exports = {
  webpack: {
    ...
  },
  plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: {
              '@ant-prefix': 'my-prefix',
            },
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
};
```

3.  修改文件名及导入
    - `App.css` 修改为 `App.less` 并将其中引入 antd 样式 由 `@import '~antd/dist/antd.css';` 更换为 `@import '~antd/dist/antd.less';`

    - `index.css` 只修改文件名为 `index.less` 即可

**Pull request merged**
