### PR TITLE
Table sticky not working RTL

### PR DESCRIPTION
**Pull request by edrmsgl**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/35478

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Does the table sticky feature have rtl support? Cannot scroll left unless you are at the bottom of the page with the scrollbar. |
| 🇨🇳 Chinese | 表格粘性功能是否支持 rtl？ 除非您位于带有滚动条的页面底部，否则无法向左滚动 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片

**Comment by afc163** [comment]
And none of commits from you? @edrmsgl

**Comment by MadCcc** [comment]
Maybe a mistake, closing.

**Comment by edrmsgl** [comment]
Has a fixed been found for this bug?

**Comment by edrmsgl** [comment]
Is there anyone who can answer?

**Pull request closed without merging**
