### PR TITLE
docs: add Space for demo

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | docs: add Space for demo |
| 🇨🇳 Chinese | docs: add Space for demo |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
argos 跑了一晚上，不知道为啥

**Comment by yoyo837** [comment]
`waiting for your decision`

**Comment by li-jia-nan** [comment]
> `waiting for your decision`

唉？这个是要点什么 approve 之类的吗？

**Comment by afc163** [comment]
为啥要改这个。

**Comment by li-jia-nan** [comment]
> 为啥要改这个。

这里贴在一起了，没间距

image

**Review by afc163 — APPROVED** [review]

**Comment by li-jia-nan** [comment]
after:

image

**Pull request merged**
