### PR TITLE
Feature  onTag api on Tag

### PR DESCRIPTION
**Pull request by zheeeng**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

In using Typescript, Tag Component doest receive DOM attributes but these attributes indeed be passed down as properties to the inner div element. onTag do the same thing as onRow does in Table Component. If this PR is accepted, plz consider remove spreading div props in inner div in next break change version.

### CODE REVIEW

**Comment by yesmeck** [comment]
`export interface TagProps extends React.HTMLAttributes<HTMLDivElement>`

**Comment by zheeeng** [comment]
@yesmeck Have thought of that, It is likely to mix up the DOM attributes with TagProps, make the editor/IDE intelligence hints a lot of trivial available props.
Another problem is that If we hoist the DOM attributes to the Component Props' root, may cause some naming conflicts between DOM Attributes and Component. This is why we have to drop props such as `onChange`, `onClick`, `value`.

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/commit/82b721a432f8814ed1ae35362bb7cdb6d378dedc

We can omit `onChange`、`onClick`

`TagProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange' | 'onClick'>`

**Comment by yesmeck** [comment]
I don't fully understand how does `onTag` solve the problem, you still can not pass your own `onClick` to `CheckableTag` after introducing `onTag`.

**Comment by zheeeng** [comment]
onTag prop usage:
```
const t = <Tag onTag={{ onClick (e) { console.log(e.altKey) }}} />
```

Advantage 1: Not pollute TagProps.
if use `TagProps extends TagProps extends React.DOMAttributes<HTMLDivElement>`:
image
There are too many useless props(defined generic React.DOMAttributes) to prevent us find Tag props.

Advantage 2: CheckableTag's `onChange` passes us `true` or `false`, its `onTag.onChange` passes use the synthetic event. It is for designing/extend some complicated features.

**Comment by yesmeck** [comment]
I don't think typing system should affect the API design.

> its onTag.onChange passes us the synthetic event.

`div` don't have `onChange` event right?

**Comment by zheeeng** [comment]
I second your point. But in using TS, if we don't define `onClick`, `onDoubleClick`, 'role' such things, we will never get TS passing if using these props, but javascript could handle it. If use interface extending, we can't precisely be hinted with the Tag own props. Sometimes, Antd hicked `onChange`, `onSubmit`,  in these situations, we indeed cant access synthetic event by `onChange`(as I mentioned with `CheckableTag.onChange` example).

**Comment by zheeeng** [comment]
The main problem is that if we want to add event handlers to like 'click', 'doubleClick', 'touch', 'mouseover', in writing in TS, we have on efficient ways.

The current workaround is wrap Tag with a div element and appending event handler on it:
```
<div onClick={this.handleClickTag} onDoubleClick={this.handleDoubleClickTag} onMouseOver={this.handleMouseOverTag}>
    <Tag onDoubleClick={???} />  // In Typescript, it is not allowed.
</div>
```

It brings reduent div element, moreover, it is not a generic solution. If the Component props are spreading on inner deep elements.

One day, if we want to spread props to part elements of a component, 'onXXX' api designing could be used as
```
const Card = ({ onHeader, onFooter, onBody }) => 
    <div>
        <div {...onHeader} />
        <div {...onBody} />
        <div {...onFooter} />
    </div>
```
devlopers can expend more awesome features.

**Comment by yesmeck** [comment]
1. Can not pass other HTML attributes `Tag` in TypeScript, because of `TagProps` didn't define them.

We can make `TagProps` extends `React.DOMAttributes<HTMLDivElement>`.

2. Extending `React.DOMAttributes<HTMLDivElement>` will introduce many insignificant props to intelligence hints, so we should introduce another prop `onTag` to pass HTML attributes.

I don't think typing system should affect the API design.

3. Can not access `event` in `onChange`.

We can pass `event` as a second parameter to `onChange`.


Hope I clarified my option.

**Comment by zheeeng** [comment]
@yesmeck Yes, your opinion is clarified.

If we use `TagProps` extends `React.DOMAttributes<HTMLDivElement>`, how can we take the advantage of TypeScript intelligence to find the Tag' own props, such as `onClose`, 'afterClose', 'closable' efficiently? Do we have to look up the usage doc every time? The potential problem I have screenshotted above.

If there are new demands that access DOM events on Card/Modal/List/Table's header, content, footer, how will we add these new APIs? I admit such demands is over-designed, but it indeed can re-leverage the onXXX API designing).

**Comment by afc163** [comment]
Is it any way we can highlight or stick up Tag own props without adding new props?

**Comment by zheeeng** [comment]
I afraid there is no an elegant more/typing friendly way to achieve this goal.

IMO, 'onXXX'  APIs run on collecting -> spreading procedure, it is easy to managing/expanding/maintaining /implementing monkey patches.

And more, in the old API design way, we already have some potential problems.
For instance, `InputNumber` receives prop `onChange: function(value: number | string)`. What if the official API `onChange` is added after some developers had already used  the `InputNumber` like:
```
<InputNumber onChange={e => console.log(e.target.value) }
```
New API may brings back compatibility issues, right?

The more users passing DOM attributes in the old way, the fewer chance we have that adding new high-level APIs like `EmailInput::onChange as function(value: EmailStructureTuple)`, `Greeting::onClick as function(value: string)`, `RandomNumGenertor::onClick as function(value: number)`

**Comment by yesmeck** [comment]
> <InputNumber onChange={e => console.log(e.target.value) } />

Can you find any exists API may encounter this situation?

**Comment by zheeeng** [comment]
@yesmeck For instance, look at `<TextArea onChange={e => console.log(e.target.value) } />`, for prevent backward compatibility issues, we can't update its signature to `onChange: (value: string) => void`.

No matter whether my solution is will be accepted, I think we should keep a consistent API designing style and siganture application. 

Let's compare these inconsistencies:
1. DOM attributes spreading vs Dom attributes collecting to spreading: 
```
// CheckableTag.tsx
const { ...restProps } = this.props
<div {...restProps as any} className={cls} onClick={this.handleClick} />
```
vs
```
// rc-table/TableRow.js
const { onRow } = this.props
const rowProps = this.props.onRow(record, index)         // <-- We have used such onXXX api
<BodyRow  {...rowProps} /> // 
``` 

I perfer the latter one for its typing-friendly, and expected such changes keep going on.
Should note that according to the Antd Changelog, the synetic API `onRow` comes from 'onRowClick' -- the singualr responsiblity API 

2. props extends vs naked props definition 
```
// col.tsx
interface ColProps extends React.HTMLAttributes<HTMLDivElement> {}
```
vs
```
interface interface IconProps {}
```

Col Componet is nice for typing, but we encounterd the overwhelming props hints:
image
We lost the advantage that typing is self-documented.

The IconProps limited we setting DOM attributes in TS, need more enhances.

**Comment by zheeeng** [comment]
@KagamiChan 

    after typing something on the list will be narrowed

Actually it is a beatiful assumption, we don't know how to narrow hints if we don't rember these Component APIs.

**Pull request closed without merging**
