### PR TITLE
Feature theme ux optimize

### PR DESCRIPTION
**Pull request by iamyoki**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/31642

### 💡 Background and solution
1. 暗色主题下刷新白屏且主题过渡延迟问题的解决
#### After 🤗

2. 暗色主题下系统主题color-scheme未切换问题的解决
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           Entering or refreshing the `dark mode` page by default will now not cause `white screen` and `animation delay` problems|
| 🇨🇳 Chinese |          默认进入或刷新`暗色主题`页面现在不会导致`白屏`和`动画延迟`问题 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
master branch is fine.

**Comment by iamyoki** [comment]
> master branch please~

@afc163 What's that mean? 😂

**Comment by yoyo837** [comment]
> > master branch please~
> 
> @afc163 What's that mean? 😂

Please send the PR to the master branch.

**Comment by afc163** [comment]
Please send this PR to master branch.

**Comment by iamyoki** [comment]
> Please send this PR to master branch.

Got it! Thank you!

**Comment by iamyoki** [comment]
It seems that feature branch brings `default.less` which is unacceptable for master. What should I do next? 😮

**Comment by afc163** [comment]
You should checkout branch from master and commit your changes in it.

**Comment by iamyoki** [comment]
> You should checkout branch from master and commit your changes in it.

Got it, I'll do it again, thanks.

**Comment by iamyoki** [comment]
Re PR in: https://github.com/ant-design/ant-design/pull/31816

**Pull request closed without merging**
