### PR TITLE
Fix: Table - Column filters are not keyboard operable/focusable

### PR DESCRIPTION
**Pull request by dartamonov-vertex**
- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Issue - https://github.com/ant-design/ant-design/issues/37508

### 💡 Background and solution

1. Column filter buttons are not keyboard focusable (because they have a tabindex of -1).
2. To reproduce go to https://ant.design/components/table/#components-table-demo-head
Hit "tab" key, navigating through focusable table elements.
3. How to fix the problem - Change tabIndex to 0, add autoFocus and onKeyDown handler.

### 📝 Changelog

Like sortable columns, column filter buttons are keyboard focusable now. Once the filter is opened, the contents of the filter popover is focusable. Hitting ESC closes the opened filter.

### ☑️ Self-Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Ke1sy** [comment]
@dartamonov-vertex the code looks fine, but while testing it locally I noticed a weird thing, after I click to open the filter, the page scrolls to the top, could you please look at it. I recorded the video: https://drive.google.com/file/d/1JoYxlp4nEPVcH28YzflLfUQliXVjb5_A/view?usp=sharing

**Comment by Ke1sy** [comment]
@dartamonov-vertex 
When I have a submenu and it is open I move focus with "tab" to previos nodes or next, the main menu closes, but the submenu stil visible and keyboard accessible:
https://drive.google.com/file/d/1LsRC8AVt0h0qTdDuHg3MWBlmflXo8FfI/view?usp=sharing


Also, is it possible to reach the buttons "ok" and "reset" with keyboard? I tried but haven't succedded in it, focus doesn't move to them

**Comment by afc163** [comment]
Is it still in progress?

**Comment by afc163** [comment]
ping~

**Review by AbdullahWins — APPROVED** [review]
good job!

**Comment by afc163** [comment]
ping~

**Comment by spoilerdo** [comment]
Is this PR still going??

**Comment by afc163** [comment]
ping~

**Comment by afc163** [comment]
Closing for no response.

**Pull request closed without merging**
