### PR TITLE
Modal.confirm support zIndex prop

### PR DESCRIPTION
**Pull request by Alex1990**
#6722

### CODE REVIEW

**Comment by benjycui** [comment]
Please fix CI, thanks.

**Comment by Alex1990** [comment]
Some other lint errors occured.

```
antd-tools run ts-lint
ERROR: components/carousel/index.tsx[7, 39]: Shadowed name: 'matchMediaPolyfill'
ERROR: components/layout/layout.tsx[12, 11]: Shadowed name: 'Basic'
ERROR: components/layout/Sider.tsx[4, 39]: Shadowed name: 'matchMediaPolyfill'
```

**Comment by afc163** [comment]
rebase master

**Comment by Alex1990** [comment]
Sorry to disturb everybody. Running `git rebase master` in modal-confirm-zindex branch which is checked out from `feature-2.12` branch results this bad behavior.

**Pull request closed without merging**
