### PR TITLE
Added Dutch locale and bumped dep versions so they include Dutch locales

### PR DESCRIPTION
**Pull request by corneyl**
* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style. (N/A)
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Added Dutch locale and bumped dep versions so they include Dutch locales to:
- rc-calendar to ~7.6.2
- rc-pagination to ~1.6.6

### CODE REVIEW

**Review by benjycui — APPROVED** [review]

**Comment by benjycui** [comment]
Sorry, could you PR to branch `feature-2.8`?

**Comment by corneyl** [comment]
Sure, I do not have to rebase right? `feature-2.8` is even with `master`.

**Comment by afc163** [comment]
You can add test case for it.

https://github.com/ant-design/ant-design/blob/master/components/locale-provider/__tests__/index.test.js#L58

**Comment by afc163** [comment]
@corneyl

**Comment by corneyl** [comment]
I will, but need some time, sorry.

**Comment by corneyl** [comment]
Like this? Well that was quite easy...

**Comment by afc163** [comment]
Yep, that make sure our coverage rate won't downgrade. 😸

**Pull request merged**
