### PR TITLE
refactor(color): @ctrl/tinycolor to color2k

### PR DESCRIPTION
**Pull request by guoyunhe**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

@ctrl/tinycolor 的大小为 6.4KB，而 color2k 为 2.9KB，理论上可以让总体积减少 3.5KB

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | refactor(color): replace @ctrl/tinycolor with color2k to reduce bundle size by 3.5KB (minified + gzipped) |
| 🇨🇳 Chinese | refactor(color): 将 @ctrl/tinycolor 替换为 color2k 以减少 3.5KB 打包体积 (minified + gzipped)  |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
还有上游包使用的 @ctrl/tinycolor 。

**Comment by yoyo837** [comment]
不能单纯直接改，而且不能master修改。

**Comment by Wxh16144** [comment]
感觉不错，但是 color2k 的文档说只能将颜色输出 rgba 和 hsla 🤔，并且 antd 暴露出去的方法支持更多的 format 。会不会 break change 呢

两者下载趋势：https://npmtrends.com/@ctrl/tinycolor-vs-color2k

对我来说可以试试能不能把我的 dumi-plugin-color-chunk 重构一下。

**Comment by Wxh16144** [comment]
> 还有上游包使用的 @ctrl/tinycolor 。

ref: https://github.com/react-component/color-picker/blob/b1fa571f7ddaf9d6b6112e42dac6986abf40f13a/src/color.ts#L1

**Comment by afc163** [comment]
我们现在准备更换为 https://github.com/ant-design/fast-color 了。

**Pull request closed without merging**
