### PR TITLE
chore: add diff report

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

follow up #41264

### 💡 Background and solution

Add more info about failure build deps diff

截屏2023-03-20 18 25 41

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |      -     |

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Review by PeachScript — APPROVED** [review]
+1

**Comment by afc163** [comment]
PR body 里没有背景信息？

**Comment by zombieJ** [comment]
> PR body 里没有背景信息？

Updated

**Comment by afc163** [comment]
1. https://github.com/tychota/yarn-lock-diff 这个还好看点。
2. 直接回复一个 comment 到 PR？

**Comment by zombieJ** [comment]
> 1. https://github.com/tychota/yarn-lock-diff 这个还好看点。
> 2. 直接回复一个 comment 到 PR？

cron job 没有对应的 commit or PR 实体，所以没有地方去 comment。github action log 页面宽度比较小，特地做了个竖直展示的格式。

**Pull request merged**
