### PR TITLE
fix: suppress warning while testing, close: #5345

### PR DESCRIPTION
**Pull request by benjycui**
Close: #5345 

cc @aaronplanell

### CODE REVIEW

**Comment by benjycui** [comment]
Updated.

**Comment by aaronplanell** [comment]
Great work! But,... What about the `package.json` & `scripts\test-all.sh` files? Don't they need to specify the `NODE_ENV=test` parameter?

**Comment by benjycui** [comment]
I just ... don't care this warning while testing..

But you can PR to suppress it.

**Comment by aaronplanell** [comment]
OK! Once I finished the #5318 PR I will make another for suppress it. 

Meanwhile, I ran:
```
$ rm -Rf node_modules/
$ yarn install
```
And I'm using the `"antd": "^2.8.2"` version but I cannot see the code you have fixed :cry:

**Comment by benjycui** [comment]
This will be published at weekend.

**Comment by benjycui** [comment]
https://ant.design/changelog#Release-Schedule

**Comment by aaronplanell** [comment]
OK! Thanks a lot @benjycui !

**Pull request merged**
