### PR TITLE
fix: react 18 test fixing

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |     -      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/34852 支持 React 18 了。

**Comment by zombieJ** [comment]
> #34852 支持 React 18 了。

看来它 alpha 也没有很久 😎

**Comment by afc163** [comment]
ci 能跑过，但是组件用不了？

**Comment by zombieJ** [comment]
> ci 能跑过，但是组件用不了？

非严格模式也能跑，严格模式下 effect 挂掉：https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

**Comment by afc163** [comment]
要加严格模式都跑一遍用例

**Pull request merged**
