### PR TITLE
update Select getPopupContainer type define error

### PR DESCRIPTION
**Pull request by SunshineH2**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
为啥会有null null会直接挂吧

**Comment by chj-damon** [comment]
@ztplz getPopupContainer在文档里面写的是：
getPopupContainer={triggerNode => triggerNode.parentNode}
但是triggerNode.parentNode的类型是ParentNode，不是HTMLElement，所以要改成
getPopupContainer={triggerNode => triggerNode.parentElement}，
但是parentElement的定义是HTMLElement | null

**Comment by ztplz** [comment]
@chj-damon  你是按照文档字面意思理解的吗   其实就是要你指定一个元素 然后这个popup放你指定的那个元素下面 现在的类型严格意义上来说确实是错的 不光是react的虚拟dom还是真实的dom元素都可以

**Comment by ztplz** [comment]
但是不会是null啊 
image
要是null 代码都挂了

**Comment by chj-damon** [comment]
@ztplz 我更新到3.18.2，发现已经解决了，现在的定义是：getPopupContainer?: (triggerNode: HTMLElement) => HTMLElement;

**Pull request closed without merging**
