### PR TITLE
refactoring: rewrite useLocale return value

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | refactoring: rewrite useLocale return |
| 🇨🇳 Chinese | 重写 useLocale 方法，对外暴露 localeCode |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
咋会分开提交

**Comment by li-jia-nan** [comment]
image

大佬临时决定

**Comment by yoyo837** [comment]
要改这个文件名, 还有些其他的地方要改, 测试和script脚本

**Comment by li-jia-nan** [comment]
> 要改这个文件名, 还有些其他的地方要改, 测试和script脚本

我回滚了，有第三方库用到了，到时候先去给第三方库提 PR，然后再回来改

**Comment by Wxh16144** [comment]
如此改动，感觉应该往 feature 发合并请求🤔

**Comment by li-jia-nan** [comment]
> 如此改动，感觉应该往 feature 发合并请求🤔

- #40870 
之前已经改过一次了，这条是补充

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
