### PR TITLE
feat: Allow avatar group popover on click

### PR DESCRIPTION
**Pull request by RiteshMakan**
Based on this issue, #31924. Here is a proposal to allow 'click' or 'hover' to trigger the popover instead

Hi, As per comment I am opening a new PR

https://github.com/ant-design/ant-design/pull/31928#issuecomment-912397025

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by RiteshMakan** [comment]
Hi, As per the comment in Closed PR I am opening a new PR

https://github.com/ant-design/ant-design/pull/31928#issuecomment-912397025

**Comment by RiteshMakan** [comment]
Hi @afc163, @xrkffgg, or @zombieJ, Please could you assist. This is my first big PR for ant design

I have no idea why this PR keeps getting closed automatically

**Comment by yoyo837** [comment]
Try rebase and `push -f`.

**Comment by RiteshMakan** [comment]
It appears that the `github-actions` bot does not like me updating the Changelog files. I resubmit the PR here without changelog and it no longer automatically closes:
https://github.com/ant-design/ant-design/pull/32197

**Pull request closed without merging**
