### PR TITLE
[WIP] upgrade(menu):  bump to 8.9.0

### PR DESCRIPTION
**Pull request by kerm1it**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | -  |
| 🇨🇳 Chinese | -  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
等 preview 出来了，建一个 codesandbox，试试 https://github.com/ant-design/ant-design/issues/26979 和 https://github.com/ant-design/ant-design/issues/26970 这两个

**Comment by Kermit-Xuan** [comment]
`ignore-emit-webpack-plugin` 这个 webpack 插件昨晚发了新版本挂了，https://github.com/mrbar42/ignore-emit-webpack-plugin/issues/17

**Comment by yoyo837** [comment]
先锁个版本？

**Comment by Kermit-Xuan** [comment]
> 先锁个版本？

只能先这样了

**Comment by yoyo837** [comment]
单独发个PR 来lock吧？

**Comment by Kermit-Xuan** [comment]
> 单独发个PR 来lock吧？

是的，刚才那个只是临时锁了，要用 preview 来测 bug 😂

**Comment by Kermit-Xuan** [comment]
这个暂时先不要合，还有点问题呢。

**Comment by ycjcl868** [comment]
> 这个暂时先不要合，还有点问题呢。

先不上车，下个版本吧

**Comment by kerm1it** [comment]
Trace in https://github.com/ant-design/ant-design/pull/27663

**Pull request closed without merging**
