### PR TITLE
Fix calendar internal select source type

### PR DESCRIPTION
**Pull request by bombillazo**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Pass the `panelMode` as the select source type to the internal select trigger callback to use the correct source type when called      |
| 🇨🇳 Chinese |    将 `panelMode` 作为选择源类型传递给内部选择触发器回调，以便在调用时使用正确的源类型       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 5183963</samp>

Fix calendar panel mode bug when selecting date in year or month panel. Change the argument of `onInternalSelect` in `components/calendar/generateCalendar.tsx`.

### <samp>🤖 Generated by Copilot at 5183963</samp>

* Fix calendar panel mode bug when selecting date in year or month panel ([link](https://github.com/ant-design/ant-design/pull/42459/files?diff=unified&w=0#diff-841e97dfb23daba72a34ee15810c8b36da6464eba16e120739ec6c9636f94fb2L342-R342))

### CODE REVIEW

**Comment by yoyo837** [comment]
Need fix test case.

**Comment by bombillazo** [comment]
> Need fix test case.

Im not very familiar with testing but I tried to implement one.

**Comment by hbatalhaStch** [comment]
@bombillazo  there is a [separate test file](https://github.com/ant-design/ant-design/blob/feature/components/calendar/__tests__/select.test.tsx) that contains all the tests relating to this new feature, you should the test there instead.
I believe the test you need to add is [similar to this](https://github.com/ant-design/ant-design/blob/feature/components/calendar/__tests__/select.test.tsx#L83) or even change this test.

**Comment by li-jia-nan** [comment]
@zombieJ need help~

**Comment by bombillazo** [comment]
Any help to proceed is welcomed.

**Comment by afc163** [comment]
图片

**Review by li-jia-nan — APPROVED** [review]

**Pull request merged**
