### PR TITLE
fix: Input width change automatically when allowClear

### LINKED ISSUE #22562: Form inline模式 Input allowClear 宽度闪烁
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/daiyichutubiao-ant-design-demo-0q1us)

### Steps to reproduce
输入任意字符

### What is expected?
宽度不变

### What is actually happening?
input宽度会增加清除小图标的宽度

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13 |
| System | mac13 |
| Browser | chrome 80 |

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Resolve https://github.com/ant-design/ant-design/issues/22562

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix Input width change automatically when allowClear |
| 🇨🇳 Chinese | 修复 Input 宽度在 `allowClear` 时自动变化  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
image

这样会导致内容默认就带上 padding-right。

**Comment by shaodahong** [comment]
不应该啊，默认是没有 suffix 的，allowClear 的时候 icon 是一直出现的

Kapture 2020-03-25 at 10 56 06

**Comment by afc163** [comment]
试试长 placeholder。

**Comment by afc163** [comment]
Any progress?

**Comment by shaodahong** [comment]
改了一圈还是要改回到 `position` 🤦‍♂️

**Comment by shaodahong** [comment]
> 试试长 placeholder。

发现 3.0 的也有这个坑……

**Comment by shaodahong** [comment]
暂时没想到完美的解决方案，先关了

**Pull request closed without merging**
