### PR TITLE
refactor: color-picker panel dom logic

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

ref: https://github.com/ant-design/ant-design/pull/45527#discussion_r1378507278

### 💡 Background and solution

将原来 `.ant-color-picker-inner-content` 类名 拆为 2 个，分别 `.ant-color-picker-inner` 和 `.ant-color-picker-inner-content`

**.ant-color-picker-inner**: 表示这个面板容器，与面板有关的样式写这个类名下。
**.ant-color-picker-inner-content**： 默认为 antd 颜色选择器面板容器。该类名只存在覆写 antd 内部样式。

如果开发者通过 `panelRender` 完全自定义内容时，默认插入到 `.ant-color-picker-inner` 容器下，而不是 `.ant-color-picker-inner-content`.(这样就可以避免样式冲突。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Refactoring `ColorPicker` popup panel dom tree logic       |
| 🇨🇳 Chinese |    重构 `ColorPicker` 弹出面板 dom tree 逻辑       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by MadCcc — APPROVED** [review]
LGTM

**Review by MadCcc — APPROVED** [review]

**Comment by MadCcc** [comment]
compact 主题下有 diff

**Comment by Wxh16144** [comment]
### 稍等，是有点问题！！！

**Comment by Wxh16144** [comment]
> compact 主题下有 diff

本地跑了一下视觉回归，这个变动是符合预期的。（该 PR 的 demo 相比于之前少了一个 `<Row >` 的嵌套）

image

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
