### PR TITLE
test: Image js => ts

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog
test: Image js => ts

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
都合并成一个 PR 好了，这类修改都雷同，合并后 review 成本也比较低。

**Comment by li-jia-nan** [comment]
> 都合并成一个 PR 好了，这类修改都雷同，合并后 review 成本也比较低。

OK

**Comment by li-jia-nan** [comment]
> 都合并成一个 PR 好了，这类修改都雷同，合并后 review 成本也比较低。

那这些要全部close掉吗？

**Comment by afc163** [comment]
关吧。

**Comment by afc163** [comment]
麻烦手动 cherry-pick 吧。

**Comment by li-jia-nan** [comment]
> 麻烦手动 cherry-pick 吧。

OK

**Comment by li-jia-nan** [comment]
> 麻烦手动 cherry-pick 吧。

- done #37375

**Pull request closed without merging**
