### PR TITLE
Update Sider.tsx default theme

### PR DESCRIPTION
**Pull request by ianzone**
to match other components' default theme

[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [X] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | change sider default theme to light |
| 🇨🇳 Chinese | 将sider组件的默认主题改为light |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ianzone** [comment]
> It is by designed.

其他组件的默认主题都是亮色的，为啥sider默认主题是暗色的？

**Comment by afc163** [comment]
Layout 默认风格，侧边栏是暗色的，需要突出内容区域。

直接修改这个默认值会是一个 break change。

**Comment by ianzone** [comment]
> Layout 默认风格，侧边栏是暗色的，需要突出内容区域。
> 
> 直接修改这个默认值会是一个 break change。

好吧，但在编程的时候不合直觉，我持保留意见

**Comment by afc163** [comment]
可以考虑在下一个大版本修正回 light。

**Pull request closed without merging**
