### PR TITLE
style: 🏷 static tags

### PR DESCRIPTION
**Pull request by ztplz**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

1. Describe the source of requirement, like related issue link.
https://github.com/ant-design/ant-design/issues/15114
2. Describe the problem and the scenario.

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from user side, and list all potential break changes or other risks.

1. English description

2. Chinese description (optional)

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
本来想用`static`的, 但是它是关键字

**Comment by zombieJ** [comment]
```
| pure | 纯静态标签，没有动画效果也不能触发点击事件 |
```

这个属性挺怪异的，改成没有鼠标事件直接不出动画吧。

**Comment by jljsj33** [comment]
动画都要删掉了。。。

**Comment by zombieJ** [comment]
> @jljsj33  动画都要删掉了。。。

那这个 #15114 在你那里 #15233 关？

**Comment by ztplz** [comment]
感觉这个属性名不好  想个名字

**Comment by afc163** [comment]
不需要属性：

image

**Comment by ztplz** [comment]
默认静态tag  不带任何效果？

**Comment by afc163** [comment]
是的，Tag 默认不应该带 hover 效果，有跳转或者 link 才应该带。

**Comment by ztplz** [comment]
在 https://github.com/ant-design/ant-design/pull/15233 弄吧 效果差不多

**Comment by afc163** [comment]
和 #15233 不是一回事。

**Comment by ztplz** [comment]
等他把动画移除了

**Comment by afc163** [comment]
ping~

**Comment by zombieJ** [comment]
> @afc163 默认移除点击效果 那用户要点击效果怎么办？

有鼠标事件时还是保留动画的，没有的时候就是静态的

**Comment by afc163** [comment]
有 `onClick` 或者 children 为链接的还是需要保留 wave。

**Comment by 7Charlotte** [comment]
> 有 `onClick` 或者 children 为链接的还是需要保留 wave。
> 
> https://ant.design/components/tag/#components-tag-demo-basic

tag控件的demo页里，默认点击还是有wave动画呀，请问静态标签这个属性改好了么？

**Comment by afc163** [comment]
@7Charlotte 抱歉，这周会发布。

**Pull request merged**
