### PR TITLE
chore: remove useless tsx support

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [x] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: remove useless tsx support |
| 🇨🇳 Chinese | chore: remove useless tsx support |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
其实我感觉改的意义不大，tsx 和 ts 混用也不会有什么问题。

**Comment by li-jia-nan** [comment]
> 其实我感觉改的意义不大，tsx 和 ts 混用也不会有什么问题。

混用确实没啥问题，那后面剩下的我就不改了

这个要close掉吗？

**Comment by yoyo837** [comment]
上个PR都接受了, 这个PR一次性弄完吧.

**Comment by yoyo837** [comment]
剩下的全弄上来. 搞完收工.

**Comment by li-jia-nan** [comment]
> 剩下的全弄上来. 搞完收工.

没办法一次性弄完，我电脑不行，改太多 diff 编辑器会卡死qaq

**Comment by yoyo837** [comment]
我的意思是一个PR弄完剩下的, 随便你提交几次.

**Comment by li-jia-nan** [comment]
> 我的意思是一个PR弄完剩下的, 随便你提交几次.

明白了，我多提交几次

**Comment by li-jia-nan** [comment]
@yoyo837 搞完了，找到一个批量修改文件名的 vscode 插件……

**Comment by li-jia-nan** [comment]
cov掉了，我来补一下

**Review by afc163 — APPROVED** [review]

**Pull request merged**
