### PR TITLE
chore: 🔀 merge master into feature 

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [x] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/form/index.en-US.md](https://github.com/ant-design/ant-design/blob/master/components/form/index.en-US.md)
[View rendered components/form/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/master/components/form/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
@AshoneA 一大波冲突又来了。

**Review by yoyo837 — APPROVED** [review]

**Comment by xrkffgg** [comment]
RTL 基本改造完毕。
剩下的优化 和 改bug，应该不会再有很大的变动了。
@AshoneA

**Comment by AshoneA** [comment]
> @AshoneA 一大波冲突又来了。

表示情绪稳定。

**Comment by AshoneA** [comment]
> RTL 基本改造完毕。
> 剩下的优化 和 改bug，应该不会再有很大的变动了。
> @AshoneA

Awesome!

**Pull request merged**
