### PR TITLE
feat: validated should be reset when trigger reset event

### LINKED ISSUE #41053: onValuesChange 收集到的数据不准确
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/sad-flower-8jnwx6?file=/src/App.tsx)

### Steps to reproduce

使用 form.list 组件，使用 add 方法添加 2 个元素，在使用 remove 方法删除 1 个元素，使用 onValuesChange 的第二个参数收集数据，fields 数组依然存在 2 个元素，被删除的元素在 fields 的下标位置存在为 undefined

### What is expected?

我理解的 onValuesChange 第二个参数收集数据，如复现步骤操作，被删除元素的在 onValuesChange 收集到的数据下标中不应该存在，

### What is actually happening?

被删除的元素在 fields 的下标位置存在为 undefined

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

### LINKED ISSUE #41966: antd Form 调用resetFields后hasFeedback的图标并没有重置
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/biao-dan-fang-fa-diao-yong-antd-5-4-5-forked-o1dgef?file=/demo.tsx)

### Steps to reproduce

输入Note后点击reset

### What is expected?

校验图标重置，不显示

### What is actually happening?

校验图标仍然显示

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 9.6.4 |
| System | win11 |
| Browser | 当前浏览器版本 |

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

- fix https://github.com/ant-design/ant-design/issues/41966
- fix https://github.com/ant-design/ant-design/issues/41053

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | - Resolve issue about the feedback icon was not reset after a reset event had been triggered <br />  - Fixed inaccurate data collected by onValuesChange |
| 🇨🇳 Chinese |  - 修复触发重置事件后反馈图标未重置的问题  <br /> - 修复 onValuesChange 收集到的数据不准确的问题 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 8a3f75a</samp>

Updated `rc-field-form` dependency and improved form demo. The changes enhance the functionality and appearance of the form component and its examples.

### <samp>🤖 Generated by Copilot at 8a3f75a</samp>

* Update rc-field-form dependency to 1.30.0 for form validation and management ([link](https://github.com/ant-design/ant-design/pull/41976/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L129-R129))
* Add Space component to import and wrap submit and reset buttons for better layout ([link](https://github.com/ant-design/ant-design/pull/41976/files?diff=unified&w=0#diff-60162065407f047d6fa0b6cb87e9524b8e80bab29b205a4678517644a564cde8L14-R17), [link](https://github.com/ant-design/ant-design/pull/41976/files?diff=unified&w=0#diff-60162065407f047d6fa0b6cb87e9524b8e80bab29b205a4678517644a564cde8L184-R190))
* Add reset button to `validate-other.tsx` demo to clear form fields ([link](https://github.com/ant-design/ant-design/pull/41976/files?diff=unified&w=0#diff-60162065407f047d6fa0b6cb87e9524b8e80bab29b205a4678517644a564cde8L184-R190))
* Remove unnecessary React import from `validate-other.tsx` ([link](https://github.com/ant-design/ant-design/pull/41976/files?diff=unified&w=0#diff-60162065407f047d6fa0b6cb87e9524b8e80bab29b205a4678517644a564cde8L1))

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/41053 的 changelog 是不是也要体现一下。

**Comment by kiner-tang** [comment]
> #41053 的 changelog 是不是也要体现一下。

这个要怎么加？直接在 changelog 里面用 & 将两个 pr 的改动连在一起吗

**Comment by afc163** [comment]
用 `<br />` 换行就行。

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | - changelog 1<br />- changelog 2 |
| 🇨🇳 Chinese |  - changelog 1<br />- changelog 2 |

**Comment by kiner-tang** [comment]
> 用 `<br />` 换行就行。
> 
> Language	Changelog
> 🇺🇸 English	- changelog 1
> - changelog 2
> 🇨🇳 Chinese	- changelog 1
> - changelog 2

ok

**Pull request merged**
