### PR TITLE
fix: Menu lost state when collapsedWidth is 0

### LINKED ISSUE #18825: When sider set collapsedWidth to 0 will cause the inside menu's selectedKeys lost.
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/StArRy5211/pen/xxKjwXy?editors=0010#anon-signup](https://codepen.io/StArRy5211/pen/xxKjwXy?editors=0010#anon-signup)

### Steps to reproduce
1. Change sub menu.
2. Toggle sider.
3. Menu selectedKey will be set to defaultValue.

### What is expected?
When toggle the sider, the inside menu keep it's selectedKeys.

### What is actually happening?
When toggle the sider, the inside menu lost selectedKeys and set to the defaultValue.

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.6 |
| System | MacOS 10.14.6 |
| Browser | Chrome 76 |

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #18825

related issue #8587

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Menu lost state when being collapsed to `0px`. |
| 🇨🇳 Chinese | 修复 Menu 当 `collapsedWidth={0}` 折叠时丢失 `selectedKeys` 状态的问题。  |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by GGCarry** [comment]
#18907 Menu 当 collapsedWidth={0} 折叠时丢失 selectedKeys 状态的问题。
问题又重现了，麻烦排查一下

**Comment by Kermit-Xuan** [comment]
4.7.0 之前是好使的么？

**Comment by GGCarry** [comment]
> 4.7.0 之前是好使的么？

4.6.3就不行了，一直在找原因，希望尽快修复，谢谢

**Comment by Kermit-Xuan** [comment]
看看是不是这个问题？https://github.com/ant-design/ant-design/issues/26905

**Comment by GGCarry** [comment]
> 看看是不是这个问题？#26905

image
感觉不是，我的问题是当sider的collapsedWidth={0}时出现的bug，可以加个微信或者QQ录个视频给你看

**Comment by Kermit-Xuan** [comment]
那就开个新 issue 给个 codesandbox 复现。

**Pull request merged**
