### PR TITLE
fix duplicate css variable

### PR DESCRIPTION
**Pull request by tonny008**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/32529

### 💡 Background and solution

less files in themes should contains less variables only. cause it is imported from all components.

move css variable to style/variables.less so it is imported only once 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by j3r0lin** [comment]
有进展吗？挺期待这个更新的。现在一堆重复 html 类定义看着真纠结。

**Review by yoyo837 — APPROVED** [review]

**Comment by zombieJ** [comment]
https://preview-43003-ant-design.surge.sh/components/config-provider-cn/

All the color is gone:
截屏2023-08-16 09 55 52

**Comment by afc163** [comment]
ping~

**Comment by afc163** [comment]
ping

**Pull request closed without merging**
