### PR TITLE
feat: ConfigProvider support Tabs `indicatorSize`

### PR DESCRIPTION
**Pull request by MadCcc**
- feat: ConfigProvider support tabs.indicatorLength
- feat: ConfigProvider support card.tabProps

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/44419

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Tabs `indicatorSize` can be configured global with ConfigProvider.        |
| 🇨🇳 Chinese |    Tabs 组件 `indicatorSize` 支持通过 ConfigProvider 全局配置       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 70eaa22</samp>

This pull request adds a new feature to the `tabs` component, which allows the user to customize the width of the active tab indicator. It also updates the `ConfigProvider` component and the related tests and types to support this feature.

### <samp>🤖 Generated by Copilot at 70eaa22</samp>

*  Add `indicatorLength` prop to `Tabs` component and `ConfigProvider` component to allow customizing the width of the active tab indicator ([link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-f7a3a5082a18fdd0627b75fb4f13fa559a2e5a5a781e381b8ba8c98b13318ccaR14), [link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-f7a3a5082a18fdd0627b75fb4f13fa559a2e5a5a781e381b8ba8c98b13318ccaL146-R147), [link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-0a9895a32672ec55a084aa7165fc8666008942903b8e51e30b662e9e1ecffb56R46), [link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-0a9895a32672ec55a084aa7165fc8666008942903b8e51e30b662e9e1ecffb56L183-R184), [link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-29d06a1647b854ac9e4eff3f5e9f5b25dca5e02a92ddde121a1af24940c767adR51), [link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-29d06a1647b854ac9e4eff3f5e9f5b25dca5e02a92ddde121a1af24940c767adR111))
*  Remove unnecessary eslint comment from `components/config-provider/__tests__/components.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-8e729604931fbfd516e8911f74c3cca0529812b4c15f9c886d09f3ab663b367fL42))
*  Add test case for `Tabs` component with `indicatorLength` prop and `ConfigProvider` context in `components/tabs/__tests__/index.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-c50585f574b49573435d32ae58afde8daafdc96f158d0187efc35a193ff60f5dR7), [link](https://github.com/ant-design/ant-design/pull/44517/files?diff=unified&w=0#diff-c50585f574b49573435d32ae58afde8daafdc96f158d0187efc35a193ff60f5dR129-R142))

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
突然想到为啥是 indicatorLength 不是 indicatorSize？

Length 感觉是数量枚举，不是像素值。

**Comment by MadCcc** [comment]
> 突然想到为啥是 indicatorLength 不是 indicatorSize？
> 
> Length 感觉是数量枚举，不是像素值。

size 确实更好些，我改改

**Comment by afc163** [comment]
- [ ] 可以给一个演示 demo
- [ ] 是否有配置 indicator 高度的需求？

**Comment by MadCcc** [comment]
> * 可能也会配置 indicator 高度/色彩（甚至渐变）/圆角的需求，需要看看怎么配合一起演示

这个就考虑加 classNames 和 token 了，另开 PR 做吧

**Pull request merged**
