### PR TITLE
chore: update ignore

### PR DESCRIPTION
**Pull request by yoyo837**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 1f3a62f</samp>

Update Dependabot configuration and enable updates for `rc-*` components. This will improve the dependency management and quality of ant-design.

### <samp>🤖 Generated by Copilot at 1f3a62f</samp>

* Update the documentation URL for Dependabot configuration options ([link](https://github.com/ant-design/ant-design/pull/44710/files?diff=unified&w=0#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L4-R4))
* Remove the ignore list for npm dependencies to allow updates for rc-* components ([link](https://github.com/ant-design/ant-design/pull/44710/files?diff=unified&w=0#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L12-L41))

### CODE REVIEW

**Comment by afc163** [comment]
我意思不是这个，我是想解决 rc-xxx 依赖 rc-util 低版本的问题。

**Comment by afc163** [comment]
这里加上机器人 PR 就太多了。

**Comment by yoyo837** [comment]
> 我意思不是这个，我是想解决 rc-xxx 依赖 rc-util 低版本的问题。

我是想发布时每个rc-*都处于当前minor的最新版本, 你是想只处理rc-util处于最新.

**Comment by MadCcc** [comment]
> 我意思不是这个，我是想解决 rc-xxx 依赖 rc-util 低版本的问题。

这只能更新依赖版本了吧

**Comment by yoyo837** [comment]
> > 我意思不是这个，我是想解决 rc-xxx 依赖 rc-util 低版本的问题。
> 
> 这只能更新依赖版本了吧

要不要把`rc-util` 从ignore放出来

**Comment by MadCcc** [comment]
> 要不要把`rc-util` 从ignore放出来?

要 rc 更新依赖，antd 更新不够

**Comment by yoyo837** [comment]
> 

OK

**Review by afc163 — APPROVED** [review]

**Pull request merged**
