### PR TITLE
feat: show line in Tree first level

### LINKED ISSUE #25950: Tree组件，第一层子节点之间缺少连接线
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree组件，第一层子节点之间缺少连接线。

### What does the proposed API look like?
Tree组件，第一层子节点之间是否也应该加上连接线啊。

image

### PR DESCRIPTION
**Pull request by zhangchen915**
# 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #25950 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Tree lost line between top level nodes when enable `showLine`.  |
| 🇨🇳 Chinese |     修复 Tree 开启 `showLine` 时顶级节点间缺少连接线的问题。      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
image

最后一个节点不应该有，只有节点间有连接线。

**Comment by zhangchen915** [comment]
最后一个节点没有的话，现在的Demo会看不出效果，是否需要更新一下？

**Comment by afc163** [comment]
是的，你可以改改 demo。

**Comment by zhangchen915** [comment]
这个还需要 rc-tree 先发个版本 https://github.com/react-component/tree/pull/360

**Pull request merged**
