### PR TITLE
type: add type null

### LINKED ISSUE #37412: Incorrect type for InputNumber's onChange
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/hopeful-danilo-tk9lum?file=/src/App.tsx)

### Steps to reproduce

1. Use `InputNumber` component
2. Inspect the parameter type of `onChange`

### What is expected?

The parameter type of `onChange` should be `string | number | null`. 

### What is actually happening?

The parameter type is `ValueType`, which is `string | number`. It's missing `null` from the parameter type.

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | react v18.2.0 |
| System | MacOS |
| Browser | - |

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- close #37412 

### 📝 Changelog
type: add type null

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | add type null |
| 🇨🇳 Chinese | 新增类型null |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
ci 挂了是因为 rc 还没发

**Comment by zheeeng** [comment]
这个有兼容性变更，应该发 minor 版本，input number 好像也没有传递 null 的情况

**Comment by zheeeng** [comment]
@li-jia-nan @zombieJ  @afc163

**Comment by li-jia-nan** [comment]
> 这个有兼容性变更，应该发 minor 版本，input number 好像也没有传递 null 的情况，这个变更对下游的影响蛮大的，加了一堆 null 判断。是否可以考虑改回来。

可以给个复现吗？

**Comment by zheeeng** [comment]
tsconfig 开 strict null checking 就会有：

```ts
const handleChange = (value: number) => {}

<InputNumber onChange={handleChange} />
```

这段代码之前可以运行，现在就不行了。得 `const handleChange = (value: number | null) => {}`

**Comment by houxd1992** [comment]
是的，升个版本 要改好多地方。。。

**Pull request merged**
