### PR TITLE
remove th background, Inherit the header

### LINKED ISSUE #17190: Bordered的可伸缩列在firefox/IE11丢失部分边框
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-resizable-column](https://ant.design/components/table-cn/#components-table-demo-resizable-column)

image

### Steps to reproduce
site demo

### What is expected?
边框兼容

### What is actually happening?
边框丢失部分

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | latest |
| System | MacOS latest |
| Browser | Firefox latest |

### PR DESCRIPTION
**Pull request by yoyo837**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?
fix #17190

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |   修复`th` `position: relative;` 后不能显示边框的问题 in firefox / IE11        |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
这样 background 就没了。

**Comment by yoyo837** [comment]
或者改到tr上也行

**Comment by yoyo837** [comment]
ant-table-header 上有哒 https://deploy-preview-17191--ant-design.netlify.com， 或者改到tr上也行。你的截图是哪个场景？

**Comment by yoyo837** [comment]
我去，怎么diff差异这么大

**Comment by yoyo837** [comment]
@zombieJ https://github.com/ant-design/ant-design/pull/16957/files#diff-e2a536684ed8b2684e0ae68f0ef1ffe9R233
```less
  &-thead > tr:hover {
    background: none;
  }
```
这里这个是考虑啥

**Comment by yoyo837** [comment]
#16957 之前 `background` 是在`tr` 上，来review下...

**Comment by yoyo837** [comment]
#17198

**Pull request closed without merging**
