### PR TITLE
chore: upgrade rc-menu to 9.7.2

### LINKED ISSUE #36636: menu 收缩 hover 会导致 浮层闪一下
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-4-21-7-forked-5q9539?file=/demo.js:444-1018)

### Steps to reproduce

1. 选中最深层菜单
2. 收缩菜单
3. hover 到选中菜单
4. 展开菜单
5. 收缩菜单

发现 再次收缩会发现浮层闪一下

### What is expected?

浮层不显示

### What is actually happening?

浮层闪一下

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.0.47 |
| System | mac |
| Browser | chrome |

### LINKED ISSUE #38241: Dropdown多级菜单有相邻的submenu时，hover到相邻的菜单时，当前的submenu不会关闭
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/duo-ji-cai-dan-antd-4-23-6-forked-ftn6r1?file=/demo.tsx)

### Steps to reproduce

在sub menu和sub menu2来回hover切换

### What is expected?

hover离开当前菜单时隐藏当前submenu

### What is actually happening?

hover离开当前菜单时多数时候不会隐藏当前submenu并且同时弹出下一个submenu

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.0.0 |
| System | win10 |
| Browser | Chrome 版本 106.0.5249.119（正式版本） （64 位） |

### PR DESCRIPTION
**Pull request by JarvisArt**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/38241
close https://github.com/ant-design/ant-design/issues/36636

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | upgrade rc-menu to 9.7.2 |
| 🇨🇳 Chinese | 升级 rc-menu 到 9.7.2 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/actions/runs/3450312500/jobs/5758851274

https://app.circleci.com/pipelines/github/ant-design/ant-design/19946/workflows/3d4d4086-2b38-42f0-80dc-304bf9ea6e6b/jobs/250180

图片

**Comment by JarvisArt** [comment]
> https://github.com/ant-design/ant-design/actions/runs/3450312500/jobs/5758851274
> 
> https://app.circleci.com/pipelines/github/ant-design/ant-design/19946/workflows/3d4d4086-2b38-42f0-80dc-304bf9ea6e6b/jobs/250180
> 
> 图片

https://github.com/react-component/mentions/pull/163

**Comment by afc163** [comment]
https://github.com/react-component/mentions/releases/tag/v1.11.0

**Review by li-jia-nan — APPROVED** [review]

**Comment by yoyo837** [comment]
changelog是不是太简单了点，应该写minor版本具体内容吧

**Pull request merged**
