### PR TITLE
fix: text ellipsis case

### LINKED ISSUE #46241: Text 组件，溢出省略，悬停显示tooltip，但是一些情况下溢出省略了，悬停并没有tooltip
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qyhmdp?file=%2Findex.js%3A17%2C3)

### Steps to reproduce

省略了，但是悬停不显示悬停的tooltip

### What is expected?

省略和悬停显示tooltip

### What is actually happening?

省略了，悬停不显示tooltip

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react18 |
| System | * |
| Browser | * |

---
原因：滚动宽度的小数是四舍五入的，实际宽度是存在小数，页面是根据样式，所以会判断为溢出省略，但是判断是否悬停显示tooltip时是判断的四舍五入后的数，舍去后比较就会不符合悬停显示tooltip了，导致页面出现有省略号悬停不显示tooltip的bug情况

### PR DESCRIPTION
**Pull request by elevensky**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #46241 

### 💡 Background and solution

Chrome 下 Text 文本当 scrollWidth 等于 offsetWidth 时 html 表现溢出，但是判断的逻辑是大于时才判真

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix text element is ellipsis attr active  |
| 🇨🇳 Chinese |    修复文本溢出检测逻辑       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by hzw177** [comment]
这个是已经发布了吗？哪个版本？

**Comment by yoyo837** [comment]
PR 冲突，Rebase一下。

**Comment by elevensky** [comment]
> 这个是已经发布了吗？哪个版本？

@hzw177  你可以临时调整下宽度+1像素，触发原来的判断

**Comment by elevensky** [comment]
> PR 冲突，Rebase一下。

@yoyo837 有空帮忙看下

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/50315

**Pull request closed without merging**
