### PR TITLE
Translate into Polish

### PR DESCRIPTION
**Pull request by kocielnik**
Translated 4 UI files

### CODE REVIEW

**Comment by afc163** [comment]
1. should pull to`feature-2.11`
2. Add test case in: https://github.com/ant-design/ant-design/blob/85d813750682bda986bfa8e614001472b9cc2a97/components/locale-provider/__tests__/index.test.js#L24

**Comment by longersson** [comment]
@afc163 Thanks for your feedback!

**Comment by afc163** [comment]
Mix up some unrelated commits.

**Comment by benjycui** [comment]
Oops....

**Comment by afc163** [comment]
You can create another PR from `feature-2.11`.

**Pull request closed without merging**
