### PR TITLE
feat: migrate less to token for Radio

### PR DESCRIPTION
**Pull request by Yuiai01**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

ref https://github.com/ant-design/ant-design/issues/41884
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Migrate Radio less variables         |
| 🇨🇳 Chinese | 迁移 `Radio` less 变量           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 514c4d6</samp>

This pull request refactors the `Radio` component style hook and updates the documentation for migrating the less variables to the component tokens. It introduces a new `RadioToken` interface to customize the focus shadow styles and simplifies some imports and interfaces. It also adds the migration guide for the `Radio` component to the English and Chinese versions of the `docs/react/migrate-less-variables.md` file.

### <samp>🤖 Generated by Copilot at 514c4d6</samp>

*  Refactor the Radio component to use component tokens instead of less variables ([link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-a741439225c8413e967262511dad718192a7a5154ee037fa3c679681b95372afL2-R16), [link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-a741439225c8413e967262511dad718192a7a5154ee037fa3c679681b95372afR28-R32), [link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-a741439225c8413e967262511dad718192a7a5154ee037fa3c679681b95372afL483-R546))
  - Reorder the imports alphabetically and simplify the `ComponentToken` interface by moving some properties to the `RadioToken` interface ([link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-a741439225c8413e967262511dad718192a7a5154ee037fa3c679681b95372afL2-R16))
  - Add the `RadioToken` interface to extend the `FullToken` interface and define the `radioFocusShadow` and `radioButtonFocusShadow` properties ([link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-a741439225c8413e967262511dad718192a7a5154ee037fa3c679681b95372afR28-R32))
  - Separate the token calculation logic from the style generation logic in the `genComponentStyleHook` function and use a second argument function to return an object with the token values ([link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-a741439225c8413e967262511dad718192a7a5154ee037fa3c679681b95372afL483-R546))
* Add documentation for migrating the less variables to the component tokens for the Radio component in both English and Chinese versions of the file ([link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-999566baa64628c49813370e7cb13c3c8f5e0c99ef8fe9cec7c5052985c10d9aR39-R60), [link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-dff3e0a0a5fae848621e55da4e2adaf0ec6c57d5e29d3f601799c8898c280739R39-R60))
  - Show the mapping between the less variables and the component tokens in a table and the notes for the deprecated or changed variables in `docs/react/migrate-less-variables.en-US.md` and `docs/react/migrate-less-variables.zh-CN.md` ([link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-999566baa64628c49813370e7cb13c3c8f5e0c99ef8fe9cec7c5052985c10d9aR39-R60), [link](https://github.com/ant-design/ant-design/pull/42050/files?diff=unified&w=0#diff-dff3e0a0a5fae848621e55da4e2adaf0ec6c57d5e29d3f601799c8898c280739R39-R60))

### CODE REVIEW

**Comment by MadCcc** [comment]
argos 的 diff 增加了，等这个 minor 发布之后再检查下～

**Comment by Yuiai01** [comment]
> argos 的 diff 增加了，等这个 minor 发布之后再检查下，现在的 diff 太多不知道哪个影响的

好～

**Review by MadCcc — APPROVED** [review]

**Comment by li-jia-nan** [comment]
Conflicting

**Comment by Yuiai01** [comment]
> Conflicting

好 看到了～

**Pull request merged**
