### PR TITLE
fix: import BuildInPlacements type

### LINKED ISSUE #29015: Typescript compile error regression in 4.11.1
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nrayburn-tech/antd-ts-error ](https://github.com/nrayburn-tech/antd-ts-error )

### Steps to reproduce
1. Clone repo
2. Run `npx tsc`.

### What is expected?
No compile error.

### What is actually happening?
Error when compiling.

```
node_modules/antd/lib/tooltip/placements.d.ts:16:73 - error TS2307: Cannot find module '_rc-trigger@5.2.1@rc-trigger' or its corresponding type declarations.

16 export default function getPlacements(config: PlacementsConfig): import("_rc-trigger@5.2.1@rc-trigger").BuildInPlacements;
```

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 17 |
| System | macOS Big Sur |
| Browser | Chromium 88 |

---
This comes from using `skipLibChecks: false` in the tsconfig file.  I don't really know what it does, but I believe it was the default from `vite` and is how I ran into this issue.  `skipLibChecks: true` can be used to avoid the error, if necessary.

### PR DESCRIPTION
**Pull request by kianfang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #29015

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix rc-trigger `placements` TypeScript compile error. |
| 🇨🇳 Chinese | 修复 rc-trigger `placements` TypeScript 编译错误。   |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by waiwaiku** [comment]
#29015

**Comment by afc163** [comment]
同一个坑踩进去两次：

- https://github.com/ant-design/ant-design/pull/27761/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L150

**Comment by waiwaiku** [comment]
> 同一个坑踩进去两次：
> 
> * https://github.com/ant-design/ant-design/pull/27761/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L150

看了下历史提交，当初改用 `typeof Placements`主要是解决lin检查错误，而这个错误的本质原因是 `rc-trigger` 依赖是丢在package.json里的`devDependencies`而不是`dependencies`里。

**Comment by afc163** [comment]
因为用了 cnpm install 安装。

**Comment by waiwaiku** [comment]
> 因为用了 cnpm install 安装。

soga~

**Pull request merged**
