### PR TITLE
chore: fix nested style

### LINKED ISSUE #39183: Descriptions 嵌套 Descriptions 时，内部的 Descriptions 样式异常
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-57i7nq?file=/index.js)

### Steps to reproduce

无

### What is expected?
image

### What is actually happening?
image

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | react@18.2.0 |
| System | macOS 13 |
| Browser | chrome 107.0.5304.110 |

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #39183 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix `Descriptions ` nested style      |
| 🇨🇳 Chinese |     修复 Descriptions 嵌套样式      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Wxh16144** [comment]
改 bug 改着改着，发现改不了，结果加了一些 feature 进去。麻烦看看合不合适吧，嵌套使用的问题有点麻烦

**Comment by afc163** [comment]
Is it done?

**Comment by Wxh16144** [comment]
> Is it done?

Not finished yet, give me some more time. 😂

**Comment by afc163** [comment]
冲突了

**Comment by Wxh16144** [comment]
> 冲突了

保持草稿状态, 这块儿社区反馈也不是很明显, 有点搁置了

**Comment by Wxh16144** [comment]
Duplicate of #43454

**Pull request closed without merging**
