### PR TITLE
feat: ColorPicker implement `disabledAlpha` API

### LINKED ISSUE #43253: ColorPicker `disabledAlpha` prop does not work
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-5-6-3-colorpicker-disabledalpha-not-working-drytyw?file=/demo.tsx)

### Steps to reproduce

1. Have a ColorPicker with `disabledAlpha`.
2. Open it

### What is expected?

The slider and value box for the alpha value should not be visible

image

### What is actually happening?

They are visible and can be interacted with, changing the value.

image

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome 114 |

---
The props are typed to accept several props from the rc-color-picker but not all props are actually being relayed.

See:
https://github.com/ant-design/ant-design/blob/master/components/color-picker/ColorPicker.tsx#L29-L79

Not spreading the `...rest` props might lead to other issues as well (e.g. `data-` attributes and others not being relayed)

### PR DESCRIPTION
**Pull request by RedJue**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
- close #43253

### 💡 Background and solution
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   ColorPicker implement `disabledAlpha` API      |
| 🇨🇳 Chinese |    颜色选择器实现 `disabledAlpha` API       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 0f80144</samp>

Added a new feature to the `ColorPicker` component to allow disabling the alpha channel of the color picker. This feature is controlled by a new prop `disabledAlpha` that is passed to the `ColorPicker` and its subcomponents. Updated the documentation, demo, styles, and tests to reflect this change.

### <samp>🤖 Generated by Copilot at 0f80144</samp>

*  Add `disabledAlpha` prop to `ColorPicker` component and its subcomponents to allow users to disable the alpha channel of the color picker ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fL33-R33), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR54), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-92ce74ec7f4cf4bb67a1fe8516714a57233367553933dd62c59ae8806fe43146L14-R14), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-a04e15c33ec6c3cfe7d1f5772c30cd22e640b5f00500f1404d652d83f825e8c9L12-R15), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-83dba3026e7dc41ad64d3a2f4d484eeb085f0c3798dc2316fbb90d23520fca6eR31))
*  Pass `disabledAlpha` prop to `RcColorPickerPanel` and `ColorInput` components in `PanelPicker` component to disable the alpha slider and input in the panel and the input box ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-a04e15c33ec6c3cfe7d1f5772c30cd22e640b5f00500f1404d652d83f825e8c9R28), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-a04e15c33ec6c3cfe7d1f5772c30cd22e640b5f00500f1404d652d83f825e8c9L47-R61))
*  Destructure `disabledAlpha` prop from the `props` object in `ColorPicker`, `PanelPicker`, and `ColorInput` components to use it later ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR85), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-92ce74ec7f4cf4bb67a1fe8516714a57233367553933dd62c59ae8806fe43146L25-R25), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-a04e15c33ec6c3cfe7d1f5772c30cd22e640b5f00500f1404d652d83f825e8c9R28))
*  Add conditional rendering to `ColorInput` component to hide the `ColorAlphaInput` component if the `disabledAlpha` prop is true ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-92ce74ec7f4cf4bb67a1fe8516714a57233367553933dd62c59ae8806fe43146L64-R66))
*  Add margin bottom styles to the hue slider and the slider group in the `genPickerStyle` function to avoid overlapping and create some space between the sliders and the input box ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-34b89f88ff38f571cda106c0e4980f0487a530c9c21623a0fd1695bb0b132a58L61-R61), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-34b89f88ff38f571cda106c0e4980f0487a530c9c21623a0fd1695bb0b132a58L67-R77))
*  Add a new style rule to the slider group with the `disabledAlpha` modifier to adjust the layout of the sliders when the alpha slider is disabled ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-34b89f88ff38f571cda106c0e4980f0487a530c9c21623a0fd1695bb0b132a58L67-R77))
*  Add a new test case to check if the `disabledAlpha` prop works as expected in the `ColorPicker` component ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-aa06460351e8630f305cf6509e8137984e0f167ab2560da22874033189234fb4R400-R406))
*  Add a new example link and a new API entry to the `ColorPicker` documentation in Chinese and English to describe the `disabledAlpha` prop ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-819859f3d30fc8ec12a8ef1b55ac1d75b4b1d600eb1cee989efd5af57255b560R27), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-819859f3d30fc8ec12a8ef1b55ac1d75b4b1d600eb1cee989efd5af57255b560R48), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-9d1ff106a032e484c8f982279c4e1295d23f69904a26e020e99310c446e93249R28), [link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-9d1ff106a032e484c8f982279c4e1295d23f69904a26e020e99310c446e93249R49))
*  Omit the `disabledAlpha` prop from the `ColorPickerProps` type to avoid passing it to the underlying `RcColorPicker` component, which does not support it ([link](https://github.com/ant-design/ant-design/pull/43355/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fL33-R33))

### CODE REVIEW

**Review by kiner-tang — APPROVED** [review]

**Comment by kiner-tang** [comment]
ci 挂了

**Comment by kiner-tang** [comment]
好像是 cssinjs 那个问题搞挂的

**Comment by RedJue** [comment]
> 好像是 cssinjs 那个问题搞挂的

在看了👌

**Comment by MadCcc** [comment]
如果用户传了一个带透明度的颜色，会不会帮用户把透明度去掉？

**Comment by RedJue** [comment]
> 如果用户传了一个带透明度的颜色，会不会帮用户把透明度去掉？

代码里没做限制，感觉需要做一下限制，因为可能有复合使用的场景，我补充一下。

**Review by li-jia-nan — APPROVED** [review]

**Comment by li-jia-nan** [comment]
Conflicting

**Comment by MadCcc** [comment]
> > 如果用户传了一个带透明度的颜色，会不会帮用户把透明度去掉？
> 
> 代码里没做限制，感觉需要做一下限制，因为可能有复合使用的场景，我补充一下。

处理的时候应该把透明度变为 1，并且给出警告

**Comment by RedJue** [comment]
> > > 如果用户传了一个带透明度的颜色，会不会帮用户把透明度去掉？
> > 
> > 
> > 代码里没做限制，感觉需要做一下限制，因为可能有复合使用的场景，我补充一下。
> 
> 处理的时候应该把透明度变为 1，并且给出警告

ok 我加一下

**Comment by li-jia-nan** [comment]
Conflicting

**Comment by yuriholyhigh** [comment]
> > > > 如果用户传了一个带透明度的颜色，会不会帮用户把透明度去掉？
> > > 
> > > 
> > > 代码里没做限制，感觉需要做一下限制，因为可能有复合使用的场景，我补充一下。
> > 
> > 
> > 处理的时候应该把透明度变为 1，并且给出警告
> 
> ok 我加一下

看了下源码, 当未传入 value 时, 内部会默认按照 alpha 为 0 处理, 即抛出开发环境 warning; 这里建议改为: 仅当 value 有值时才去校验提示, 会好些? 否则按照目前逻辑, 新建表单中会存在很多 warning

**Pull request merged**
