### PR TITLE
add onClick prop for MenuItem

### PR DESCRIPTION
**Pull request by SylvanasGone**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your pull request, thank you!

* [x] Make sure that you propose pull request to right branch: bugfix for `master`, feature for branch `feature`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a pull request to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you pull request.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

In the latest version, menuItem starts to have a specific definition for props, which means I will get a warning if I use onClick function on MenuItem. So I add the prop to make it match the  performance.

### CODE REVIEW

**Comment by zy410419243** [comment]
Update your branch, [this commit](https://github.com/ant-design/ant-design/commit/bc704c3af458cb21f980da965e5d4a3b14a5738e) fixed snapshot problem.

**Comment by SylvanasGone** [comment]
@zy410419243 Thx for reply, but is there any snapshot related problem in my commit?

**Comment by zy410419243** [comment]
When your local snapshots is different from ci, test will fail.

So you need update snapshots even if it's not your matter.

**Comment by SylvanasGone** [comment]
@zy410419243 got it, cheers

**Pull request merged**
