### PR TITLE
Fixes #13007

### LINKED ISSUE #13007: typo: interation -> interaction
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
N/A

### Reproduction link
[https://ant.design/components/icon-cn/](https://ant.design/components/icon-cn/)

### Steps to reproduce
N/A

### What is expected?
N/A

### What is actually happening?
N/A

---
<Icon type="interation" theme="outlined" />
should be:
<Icon type="interaction" theme="outlined" />

related: https://github.com/ant-design/ant-design-icons/pull/32

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #13007

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your pull request, thank you!

* [x] Make sure that you propose pull request to right branch: bugfix for `master`, feature for branch `feature`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a pull request to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you pull request.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by afc163** [comment]
488f5a1

**Comment by aashutoshrathi** [comment]
@afc163 I should also, add changes as per commit you mentioned so that there are no compatibility issues.
Right?

**Comment by aashutoshrathi** [comment]
ping @afc163 
Can you tell me where It went wrong?

**Comment by afc163** [comment]
waiting for https://github.com/ant-design/ant-design-icons/pull/32

**Pull request closed without merging**
