### PR TITLE
chore: add PR template in Hindi

### PR DESCRIPTION
**Pull request by jaideepghosh**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Git Doc changes

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Added PR template in Hindi language     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
Commits should be clean.

**Comment by jaideepghosh** [comment]
Hey @yoyo837 
Please check now. I've reverted the unrelated commits from this PR.

**Review by xrkffgg — CHANGES_REQUESTED** [review]
No Recommendation

**Comment by xrkffgg** [comment]
这不加了吧，有人用这个模板填，我们谁能看得懂？

**Comment by yoyo837** [comment]
那应该只保留英文模版。

**Comment by xrkffgg** [comment]
> 那应该只保留英文模版。

我觉得现在挺好，主语言和通用语

**Comment by zombieJ** [comment]
Agree with @xrkffgg, none of collaborator can view PR with hindi lang.

**Pull request closed without merging**
