### PR TITLE
Fix quote rendering

### PR DESCRIPTION
**Pull request by ashearer**
Use curly quotes from the current font, removing an override that switched to a Chinese font just for the four curly quote characters. On all platforms, this caused the quotes to differ in size and weight from the surrounding text. On Linux, it also caused text to fall back to a serif font rather than the intended sans-serif font. On Windows, it used a full-width Chinese character, making it look like there were extra spaces in the document. Typographic apostrophes in the middle of words, in particular, appeared to have two or more spaces after them.

### This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
Version 3.1.2 (Jan 2018) included a change titled "Optimize Chinese quotes displaying". The commit (c6fcc3121758dfe6ac5b50c1b55790eb42b805c5) wasn't clear on the rationale, but it affected only characters that would be displayed in a non-Chinese font, switching just the curly quote characters into a Chinese font. Presumably this looked slightly better than the standard rendering if curly quotes were embedded in Chinese text while the primary font was non-Chinese. However, this destroyed the rendering of quotes in non-Chinese text, making them not match the surrounding font's weight, style, or size. On Windows, it added significant amounts of unwanted horizontal whitespace due to being rendered as full-width Chinese characters. On Linux, there was a report that this broke the CSS font fallback mechanism.
> 3. Related issue link.
https://github.com/ant-design/ant-design/issues/13095

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
Fix curly quote rendering and spacing in non-Chinese text by reverting a change to display these characters in a Chinese font
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by afc163** [comment]
You can remove https://github.com/ant-design/ant-design/commit/c6fcc3121758dfe6ac5b50c1b55790eb42b805c5#diff-5b1fdddf2d322caecaae14289b15c3edR17 too.

**Comment by zombieJ** [comment]
Remove https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less#L10 also.

**Comment by ashearer** [comment]
> You could remove [c6fcc31#diff-5b1fdddf2d322caecaae14289b15c3edR17](https://github.com/ant-design/ant-design/commit/c6fcc3121758dfe6ac5b50c1b55790eb42b805c5#diff-5b1fdddf2d322caecaae14289b15c3edR17) too.

I looks like commit 43abea3212564dad4ba523702f133456b2d3fdeb removed the original `font-family-no-number` line, and folded it into the line I modified. Is there another place I should be looking?

**Comment by ashearer** [comment]
> Remove https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less#L10 also.

Thanks! I meant to get that one on the first try, but didn't commit it properly. I pushed up a fix.

**Pull request merged**
