### PR TITLE
style: fix dropdown menu icon

### PR DESCRIPTION
**Pull request by xrkffgg**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

补充 https://github.com/ant-design/ant-design/pull/21768

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fixed Dropdown content and icons overlapping          |
| 🇨🇳 Chinese | 修正 Dropdown  内容和图标重叠问题          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
要不，背景写一下因为啥补充！？

**Comment by xrkffgg** [comment]
我写在 changelog 里了，话说我 @ 他，你怎么在一个 closed PR 发现啦

**Comment by yoyo837** [comment]
Watch repo anything activity.

**Review by zombieJ — APPROVED** [review]

**Comment by xrkffgg** [comment]
just 666

**Comment by afc163** [comment]
把这个优先级提起来：https://github.com/ant-design/ant-design/pull/21768/files#diff-1afa51859d202927a0eb117e03ac1413R192

不要改外面的 padding。

**Comment by xrkffgg** [comment]
等下，RTL 还有点问题

**Pull request merged**
