### PR TITLE
style: revert Menu easing functions

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/pull/27565#issuecomment-723808483

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |    -       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/menu/index.en-US.md](https://github.com/ant-design/ant-design/blob/revert-menu-easing/components/menu/index.en-US.md)
[View rendered components/menu/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/revert-menu-easing/components/menu/index.zh-CN.md)
[View rendered components/select/demo/search-sort.md](https://github.com/ant-design/ant-design/blob/revert-menu-easing/components/select/demo/search-sort.md)
[View rendered components/select/index.en-US.md](https://github.com/ant-design/ant-design/blob/revert-menu-easing/components/select/index.en-US.md)
[View rendered components/select/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/revert-menu-easing/components/select/index.zh-CN.md)
[View rendered docs/react/i18n.en-US.md](https://github.com/ant-design/ant-design/blob/revert-menu-easing/docs/react/i18n.en-US.md)
[View rendered docs/react/i18n.zh-CN.md](https://github.com/ant-design/ant-design/blob/revert-menu-easing/docs/react/i18n.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
@jljsj33 就是 css 体积会大一点。

**Comment by afc163** [comment]
argos 慢一拍：https://www.argos-ci.com/ant-design/ant-design/builds/367 里显示的其实是 https://github.com/ant-design/ant-design/pull/27650 的结果。

**Comment by yoyo837** [comment]
> argos 慢一拍：https://www.argos-ci.com/ant-design/ant-design/builds/367 里显示的其实是 #27650 的结果。

@shaodahong

**Comment by afc163** [comment]
来个 approve

**Review by yoyo837 — APPROVED** [review]

**Pull request merged**
