### PR TITLE
fix: Don't non-null assertion

### LINKED ISSUE #22094: Table - FilterDropdown - TypeError: Cannot read property 'map' of undefined
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/collinbarrett/FilterLists/tree/ant4](https://github.com/collinbarrett/FilterLists/tree/ant4)

### Steps to reproduce
Sorry, I know this is not using the minimal reproduction antd repo, but I am not sure how to reproduce in that repo.

This is trying to update a working antd@3 to antd@4. I have already run the codemod tool on this branch.

- Checkout branch `ant4` of https://github.com/collinbarrett/FilterLists.git.
- `cd web/`
- `npm run start`

### What is expected?
The app compiles and loads.

### What is actually happening?
The app compiles successfully, but I see at runtime:

```
renderFilterItems
C:/src-git/FilterLists/web/table/hooks/useFilter/FilterDropdown.jsx:15
  12 |     return filters.some(({ children }) => children);
  13 | }
  14 | function renderFilterItems(filters, prefixCls, filteredKeys, multiple) {
> 15 |     return filters.map((filter, index) => {
  16 |         if (filter.children) {
  17 |             return (<SubMenu key={filter.value || index} title={filter.text} popupClassName={`${prefixCls}-dropdown-submenu`}>
  18 |           {renderFilterItems(filter.children, prefixCls, filteredKeys, multiple)}

TypeError: Cannot read property 'map' of undefined
```

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 80.0.3987.132 |

---
I am not sure if this is a bug, but it seems to maybe at least be a breaking API change of v4 that I didn't see in the v3 to v4 upgrade guide.

I am thinking it _may_ be related to the non-null assertion operator [here](https://github.com/ant-design/ant-design/blob/72a7ba618fe58884707d1a41b0465792025916aa/components/table/hooks/useFilter/FilterDropdown.tsx#L193), but I am not sure.

Any help resolving this would be much appreciated. Thanks!

### PR DESCRIPTION
**Pull request by yoyo837**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #22094
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |   修复 Table 筛选功能抛出 Cannot read property 'map' of undefined 的问题。       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Changelog 按用户视角写一下。

**Comment by yoyo837** [comment]
> Changelog 按用户视角写一下。

改了下

**Comment by afc163** [comment]
> 修复table筛选功能，对filters的使用可能未赋值的运行时错误

修复 Table 筛选功能抛出 `Cannot read property 'map' of undefined` 的问题。

**Comment by yoyo837** [comment]
> > 修复table筛选功能，对filters的使用可能未赋值的运行时错误
> 
> 修复 Table 筛选功能抛出 `Cannot read property 'map' of undefined` 的问题。

👌

**Comment by collinbarrett** [comment]
Wow, that was fast. Looking forward to testing this fix in the next release. Thanks.

**Pull request merged**
