### PR TITLE
style: add @text-color in dark

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

补充 https://github.com/ant-design/ant-design/pull/25630

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  -         |
| 🇨🇳 Chinese |  -         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by 07akioni — COMMENTED** [review]
image

why not `65%`?

**Comment by xrkffgg** [comment]
feature 的 default 已经改成 85 % 啦 https://github.com/ant-design/ant-design/pull/25630/files

**Comment by 07akioni** [comment]
> feature 的 default 已经改成 85 % 啦 https://github.com/ant-design/ant-design/pull/25630/files

那看来是缺乏同步，没问题了hhh

**Comment by xrkffgg** [comment]
来个 approve

**Review by kerm1it — APPROVED** [review]

**Pull request merged**
