### PR TITLE
Typography component add suffix attribute

### PR DESCRIPTION
**Pull request by zouxiaomingya**
### 🤔 这个变动的性质是？

- [x] 新特性提交
- [x] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 组件样式改进
- [ ] TypeScript 定义更新
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 💡 需求背景和解决方案

1. title 覆盖问题 [例子](https://codesandbox.io/s/clever-microservice-ots1f)
2. 增加中间省略，添加后缀

### 📝 更新日志怎么写？

> 

| 语言    | 更新描述                                   |
| ------- | ------------------------------------------ |
| 🇺🇸 英文 | typography 组件增加 suffix 属性            |
| 🇨🇳 中文 | Typography component adds suffix attribute |

- 中文（可选）:

### ☑️ 请求合并前的自查清单

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

-----
[View rendered components/typography/demo/ellipsis-debug.md](https://github.com/zouxiaomingya/ant-design/blob/master/components/typography/demo/ellipsis-debug.md)
[View rendered components/typography/demo/suffix.md](https://github.com/zouxiaomingya/ant-design/blob/master/components/typography/demo/suffix.md)
[View rendered components/typography/index.en-US.md](https://github.com/zouxiaomingya/ant-design/blob/master/components/typography/index.en-US.md)
[View rendered components/typography/index.zh-CN.md](https://github.com/zouxiaomingya/ant-design/blob/master/components/typography/index.zh-CN.md)

### CODE REVIEW

**Comment by zombieJ** [comment]
feature branch please. And #19750 safe to close?

**Comment by yoyo837** [comment]
You need to `checkout` the `feature` branch before making changes.

**Comment by yoyo837** [comment]
You need to `checkout` the `feature` branch before making changes.

**Comment by zouxiaomingya** [comment]
> You need to `checkout` the `feature` branch before making changes.

OK,I got it. Thx

**Pull request closed without merging**
