### PR TITLE
fix: Table miss border-raidus in Firefox

### LINKED ISSUE #16933: Table header lost border radius in Firefox
image

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

fix #16933

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Table miss `border-raidus` in Firefox. |
| 🇨🇳 Chinese | 修复 Firefox 的 Table 丢失 `border-raidus` 样式问题。 |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
Revert 了 #16174 代码，新写的就这些：https://github.com/ant-design/ant-design/pull/16957/files#diff-e2a536684ed8b2684e0ae68f0ef1ffe9R711

**Comment by afc163** [comment]
bordered 的时候还有问题 https://github.com/ant-design/ant-design/issues/17611

**Comment by afc163** [comment]
改回 `border-collapse: separate;` 就行了，见鬼。

**Comment by ztplz** [comment]
https://www.endyourif.com/css3s-border-radius-property-and-border-collapsecollapse-dont-mix/
这两个东西不能混合

**Comment by zombieJ** [comment]
搜到一个脑洞的解法：https://codesandbox.io/s/autumn-tree-usv18

**Comment by afc163** [comment]
@zombieJ Awesome，直接上一个 Firefox hack css 好了。

**Comment by afc163** [comment]
不行，这个例子会差一像素，固定列里面会有更多问题。

image

**Pull request merged**
