### PR TITLE
fix 12810 Pagination itemRender Typescript error

### PR DESCRIPTION
**Pull request by hengkx**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for branch `feature`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by zy410419243** [comment]
Maybe you are supposed to rebase brach again, [something has changed](https://github.com/ant-design/ant-design/commit/bd0ba8ce921584c35307fee6a6464e9118837829)

**Comment by hengkx** [comment]
imageoperation is wrong

**Comment by zy410419243** [comment]
[You can try this.](https://github.com/ant-design/ant-design/pull/4700#issuecomment-275305452)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/c6eef86f83adc28044546259ffb4d5a787d5193d

**Pull request closed without merging**
