### PR TITLE
export components interface

### PR DESCRIPTION
**Pull request by newraina**
#6593 

只在各个组件的根目录下暴露了 interface。

没有找到 feature 开头的分支，因此直接 PR 到 master。

* [ ] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by benjycui** [comment]
Please PR to `antd-3.0` and fix CI.

**Review by BANG88 — COMMENTED** [review]
LGTM

But i think some of them are useless or unnecessary, if we export all interfaces that means we will spend more time on maintenance and should ensure the next version don't  make breaking changes for TypeScript users.

**Comment by newraina** [comment]
@benjycui see: #7654

**Comment by newraina** [comment]
@bang88 

大家写下 `import {...} from 'antd/lib/...` 这样的代码的时候，应该就知道他引用的是「内部 API」，这个 PR 并没有把本来没有 export 的东西 export 出来，只是把所有的 export 同时暴露在 `lib/index` 里，方便 TS 使用者，不用再手动进到各个组件的目录下找自己需要的 interface 定义在哪个文件里。

所以我觉得并不会带来更大的维护成本，毕竟之前我也会引用那些 interface :)

**Comment by bang88** [comment]
我一般使用 自动导入，所以感觉没啥关系哈。

**Pull request closed without merging**
