### PR TITLE
Fix hoist-non-react-statics compilation error

### PR DESCRIPTION
**Pull request by ztplz**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

close #16397 

### 📝 Changelog

- English Changelog:
- Chinese Changelog (optional):

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
ref: https://github.com/ant-design/ant-design/issues/16396

**Comment by zombieJ** [comment]
We need `@types/hoist-non-react-statics` in deps since Form use it to calculate. ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/package.json

**Comment by ztplz** [comment]
这个问题产生的原因是  用户有其他库也依赖了这个hoist-non-react-statics  而且是3.0前的版本  而且比antd先安装  hoist-non-react-statics会装在node_module的root里  但是antd也依赖了这个  以为已经安装hoist-non-react-statics  所以我们这个是在antd这个文件夹里  它会找不到

**Comment by zombieJ** [comment]
> 这个问题产生的原因是 ……

给力! 👍

**Comment by ztplz** [comment]
这就是解决方案啊  把 hoist-non-react-statics 也装进来  但是我觉得额外多个库没必要

**Comment by zombieJ** [comment]
我指的是把 ts 里计算的定义拷贝过来，Form 里其实只是用它来减去不需要的 props。hoist-non-react-statics 我们没有实际用到。

**Comment by ztplz** [comment]
那这个库就不用吧  我把hoist-non-react-statics里相关的定义搬过来

**Pull request merged**
