### PR TITLE
fix: active skeleton safari problem

### PR DESCRIPTION
**Pull request by slotDumpling**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

屏幕录制2023-02-12 16 04 20

Safari has some rendering problems with elements (especially those in large sizes) animated with the css-transform.
面积比较大的元素如果在transform属性应用CSS动画来移动的话，在Safari里有渲染问题（会闪一下），这个问题在Safari里持续好几年了。

### 📝 Changelog

Apply css animation on background instead.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix active skeleton animation in Safari  |
| 🇨🇳 Chinese | 修复Safari下的active skeleton的动画问题 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/36444 这个问题不好解。

**Comment by slotDumpling** [comment]
> #36444 这个问题不好解。
这是因为之前为了优化性能改用伪元素transform移动实现了，现在改回对background作用动画就可以了。

**Comment by afc163** [comment]
不是动画的问题，是圆角丢失的问题。看下 https://github.com/ant-design/ant-design/issues/36444

**Comment by slotDumpling** [comment]
Safari下圆角和动画的问题都是因为我之前的这个pr改用了伪元素做动画 [#35836](https://github.com/ant-design/ant-design/pull/35836)，改回去就好了。

**Review by afc163 — APPROVED** [review]

**Comment by yoyo837** [comment]
> Safari下圆角和动画的问题都是因为我之前的这个pr改用了伪元素做动画 [#35836](https://github.com/ant-design/ant-design/pull/35836)，改回去就好了。

改回去了, 之前PR想改的问题还会回来吗?

**Comment by slotDumpling** [comment]
> > Safari下圆角和动画的问题都是因为我之前的这个pr改用了伪元素做动画 [#35836](https://github.com/ant-design/ant-design/pull/35836)，改回去就好了。
> 
> 改回去了, 之前PR想改的问题还会回来吗?

可以等Safari以后正常了再改 :)

**Pull request merged**
