### PR TITLE
feat: Divider Component Token

### PR DESCRIPTION
**Pull request by hms181231**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
ref #41884

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Add Divider Component Token.      |
| 🇨🇳 Chinese |     添加 Divider 的 Component Token。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 62ec5bf</samp>

Refactored the `Divider` component to use a new component token for the vertical gutter margin and updated the documentation in both English and Chinese to reflect this change. Deprecated the less variables related to the `Divider` component.

### <samp>🤖 Generated by Copilot at 62ec5bf</samp>

*  Rename and move `dividerVerticalGutterMargin` property to `verticalGutterMargin` in `ComponentToken` interface ([link](https://github.com/ant-design/ant-design/pull/42627/files?diff=unified&w=0#diff-fad8d9edfb171ce694f460f4376e63930dcd7283793d0c7bb3faeee2d0d619b5L9-R12))
*  Update `genSharedDividerStyle` function to use `verticalGutterMargin` property instead of `dividerVerticalGutterMargin` property ([link](https://github.com/ant-design/ant-design/pull/42627/files?diff=unified&w=0#diff-fad8d9edfb171ce694f460f4376e63930dcd7283793d0c7bb3faeee2d0d619b5L32-R32))
*  Remove `dividerVerticalGutterMargin` property from `genDefaultComponentToken` function ([link](https://github.com/ant-design/ant-design/pull/42627/files?diff=unified&w=0#diff-fad8d9edfb171ce694f460f4376e63930dcd7283793d0c7bb3faeee2d0d619b5L158))
*  Modify `genDefaultComponentToken` function to return a function that takes global token as argument and returns an object with `verticalGutterMargin` and `sizePaddingEdgeHorizontal` properties ([link](https://github.com/ant-design/ant-design/pull/42627/files?diff=unified&w=0#diff-fad8d9edfb171ce694f460f4376e63930dcd7283793d0c7bb3faeee2d0d619b5L164-R166))
*  Add new section for `Divider` component in English documentation with new component token and deprecated less variables (`docs/react/migrate-less-variables.en-US.md`, [link](https://github.com/ant-design/ant-design/pull/42627/files?diff=unified&w=0#diff-999566baa64628c49813370e7cb13c3c8f5e0c99ef8fe9cec7c5052985c10d9aL106-R115))
*  Add new section for `Divider` component in Chinese documentation with new component token and deprecated less variables (`docs/react/migrate-less-variables.zh-CN.md`, [link](https://github.com/ant-design/ant-design/pull/42627/files?diff=unified&w=0#diff-dff3e0a0a5fae848621e55da4e2adaf0ec6c57d5e29d3f601799c8898c280739L104-R113))

### CODE REVIEW

**Comment by kiner-tang** [comment]
@hms181231 可以参考这个 pr 添加一个 component token 的  debug demo
- https://github.com/ant-design/ant-design/pull/42342

**Comment by kiner-tang** [comment]
CI 挂了，可以本地运行 `test:update components/divider/` 更新一下快照

**Comment by hms181231** [comment]
@MadCcc 大佬空了看看这个  有需要更改的 我这边及时调整

**Comment by MadCcc** [comment]
这边拖了比较久不好意思，我直接收尾了哈，感谢贡献

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
