### PR TITLE
Add support for the icon prop to the Tag component

### PR DESCRIPTION
**Pull request by vtsybulin**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] TypeScript definition update
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

Hi. Faced a need of including icons within tags for my current project, didn't find any built-in way of doing this, despite of putting icons manually withing tags. 
Updated Tag component to support 'icon' prop in alignment with what the Button component currently offers.

Final demo:
Screenshot 2020-01-09 at 14 52 41

Usage example:

`import { Tag } from 'antd';`
`...`
`<Tag icon="twitter" color="#55acee">Twitter</Tag>`

Let me know if that makes sense, so I can migrate that to v4 accordingly. Thanks!
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

PS. This is my first attempt contributing to the antd, so please don't judge me badly. I didn't find a mention of the desired branch to address PR to if I wanna update antd of version 3 as the feature branch already contains codebase for v4, so I addressed current PR to the 3.x-stable. Any guidance and support for the correct way of doing things will be much appreciated!

-----
[View rendered components/tag/demo/icon.md](https://github.com/vtsybulin/ant-design/blob/feature-support-tag-icon-prop/components/tag/demo/icon.md)
[View rendered components/tag/index.en-US.md](https://github.com/vtsybulin/ant-design/blob/feature-support-tag-icon-prop/components/tag/index.en-US.md)
[View rendered components/tag/index.zh-CN.md](https://github.com/vtsybulin/ant-design/blob/feature-support-tag-icon-prop/components/tag/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
Could you send this PR to master or feature branch?

3.x will not accept new feature after 4.0.0-rc.0 released.

**Comment by vtsybulin** [comment]
@afc163 Hi. Thanks for the reply. Got it. Sounds good, going to push one to the v4 soon.

**Comment by afc163** [comment]
ping

**Comment by vtsybulin** [comment]
@afc163 Hi. Sorry, it's been a while. Pushed a new one for the v4 
https://github.com/ant-design/ant-design/pull/22418

**Comment by afc163** [comment]
trace #22418

**Pull request closed without merging**
