### PR TITLE
docs: optimize site of docs

### PR DESCRIPTION
**Pull request by xrkffgg**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
- 优化官网中 “文档” 菜单的 RTL 显示
- 隐藏 gitee 的 “国内镜像” 菜单

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |          none |
| 🇨🇳 Chinese |  none         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered docs/react/contributing.zh-CN.md](https://github.com/ant-design/ant-design/blob/opt-doc/docs/react/contributing.zh-CN.md)

### CODE REVIEW

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/23645#issuecomment-619737705

**Comment by xrkffgg** [comment]
@afc163 @zombieJ 

还有啥办法能 判断 是不是 gitee 呢？

**Comment by hengkx** [comment]
@xrkffgg #23658

**Comment by xrkffgg** [comment]
这样啊，我还以为不让用 document 呢

**Comment by yoyo837** [comment]
再改一次

**Comment by xrkffgg** [comment]
他不是都改了吗?

**Pull request merged**
