### PR TITLE
chore: back of bisheng webpack4

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 💡 Background and solution

v5 使用 memory cache 太慢了。回滚了……

#### V5

image

#### V4

截屏2021-05-27 下午6 44 07

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
@Amour1688 挂了……

**Comment by afc163** [comment]
我这里貌似没这么慢。

**Comment by Amour1688** [comment]
antd-tools 的版本看看要不要也降一下，不然依赖里面会出现两个 webpack 的版本

**Comment by zombieJ** [comment]
@afc163，
关闭 file cache 后走的 memory cache，开一个 docker or sketch 后 16GB 内存就不够用了。

@Amour1688 ，
`@ant-design/tools` 的 webpack5 是 alpha 版本，一直没实装过。

**Pull request merged**
