### PR TITLE
use data url instead of importing svg

### PR DESCRIPTION
**Pull request by yesmeck**
First of all, thank you for your contribution! 😄

Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?
  
Importing svg directly requires the host project has a proper svg loader.

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog provided

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by chenshuai2144** [comment]
代码突然变得很丑。。

**Review by zombieJ — APPROVED** [review]

**Comment by afc163** [comment]
可以在打包时把 svg inline 进来。

**Comment by zombieJ** [comment]
> 可以在打包时把 svg inline 进来。

直接 import 单个组件的时候，用户需要自己配置 svg loader。直接 data url 对用户影响最小。

**Comment by yesmeck** [comment]
可以试试 https://github.com/Andarist/data-uri.macro

**Comment by afc163** [comment]
我是说，compile 的时候 inline，代码里还是 import svg。

**Comment by zombieJ** [comment]
> 我是说，我们 compile `lib` `es` `dist` 的时候 inline，代码里还是 import svg。

可以，我改一下 antd-tools

**Comment by zombieJ** [comment]
webpack 默认有配置 svg loader， babel 找了一个这个：https://www.npmjs.com/package/babel-plugin-inline-import-data-uri  我实验一下。

**Pull request merged**
