### PR TITLE
feat(theme): extract theme-js file for supprt mixin theme

### PR DESCRIPTION
**Pull request by AshoneA**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/22815

https://github.com/umijs/umi/issues/4315

### 💡 Background and solution

Extract dark-theme.js and compact-theme.js  file, every theme.js file only includes their less-var, also extract default-them.js.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     extract theme-js file for supprt mixin theme      |
| 🇨🇳 Chinese |    抽取主题模式文件为了支持混合主题       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by AshoneA** [comment]
自己本地 build 试了一下，umi 那边也不用改动其他东西。

**Comment by zcSkr** [comment]
image
image
我的还是报错，不能同时开启暗黑和紧凑

**Comment by AshoneA** [comment]
@afc163 umi 那边之前好像加了个 schema 阻止了配置。

**Comment by yoyo837** [comment]
是这个 https://github.com/umijs/plugins/pull/131

**Comment by AshoneA** [comment]
> 是这个 [umijs/plugins#131](https://github.com/umijs/plugins/pull/131)

👌，我提个 Pr

**Comment by cszo** [comment]
我怎么感觉这个改了之后子菜单展现的时候 有明显的延迟   你们感觉到了吗

**Pull request merged**
