### PR TITLE
Feat: button block prop to make button fit container

### PR DESCRIPTION
**Pull request by ilanus**
I think it would be nice to have this prop and users will not have to specify manually style width: 100% which results in mixing css with inline styles

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

### CODE REVIEW

**Comment by afc163** [comment]
How about `<Button block />`?

**Comment by ilanus** [comment]
Sounds good to me 👍

**Comment by afc163** [comment]
Please fix the ci.

**Comment by ilanus** [comment]
The branch is rebased and button tests are updates, not sure why CI is failing, I think not due to my code.

**Comment by afc163** [comment]
ci fixed in https://github.com/ant-design/ant-design/commit/0156fef1658a6a6db75ad384ceefdbde52f13741, try rebase feature-3.8.0 again.

**Comment by ilanus** [comment]
@afc163 should be good now 😄

**Pull request merged**
