### PR TITLE
Japanese locale

### PR DESCRIPTION
**Pull request by novi**
Hello,

I added Japanese locale `ja_JP` and translations. It comes with [pagination/#66](https://github.com/react-component/pagination/pull/66).

### CODE REVIEW

**Comment by afc163** [comment]
I think you should upgrade rc-pagination version.

**Comment by novi** [comment]
Thank you for merging. I have just updated.

**Comment by afc163** [comment]
You can update test case like this: https://github.com/ant-design/ant-design/pull/5266/files#diff-52e85eb6b25a706f4e5d5dc78dfa04acL63

**Comment by afc163** [comment]
@novi

**Pull request merged**
