### PR TITLE
docs: Add width attr to the table's grouping columns demo

### PR DESCRIPTION
**Pull request by zjffun**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

The body of table can't align it's header in grouping columns demo

### 💡 Solution

Add wdith attr

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/table/demo/grouping-columns.md](https://github.com/zjffun/ant-design/blob/patch-2/components/table/demo/grouping-columns.md)

### CODE REVIEW

**Comment by afc163** [comment]
What's problem this PR will resolve?

**Comment by zjffun** [comment]
[表格 Table - Ant Design](https://ant.design/components/table-cn/#components-table-demo-grouping-columns)

before
图片


after
图片

**Comment by zjffun** [comment]
@afc163 I will update Snapshot if this shold accept

**Comment by afc163** [comment]
Ok, it is acceptted.

**Comment by zjffun** [comment]
There are lots of base64 code of img changed when I update Snapshot, I didn't commit them.

**Comment by afc163** [comment]
Please try rebase master.

**Comment by zjffun** [comment]
delete this branch by accident 😵, there is a new request [docs: Add width attr to the table's grouping columns demo by zjffun · Pull Request #16961 · ant-design/ant-design](https://github.com/ant-design/ant-design/pull/16961)

**Pull request closed without merging**
