### PR TITLE
feat: Cascader show checked strategy

### PR DESCRIPTION
**Pull request by heiyu4585**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/34193

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   add `showCheckedStrategy `  to `'parent'\|'child''`  for value type       |
| 🇨🇳 Chinese |   添加 `showCheckedStrategy` 为 `'parent'\|'child'` 选择返回值方式      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by heiyu4585** [comment]
我没有修改样式呢 帮忙看下

**Comment by heiyu4585** [comment]
done

**Comment by MadCcc** [comment]
麻烦 base feature 吧，属于新功能了，应该放在 4.20 的

**Comment by heiyu4585** [comment]
> 麻烦 base feature 吧，属于新功能了，应该放在 4.20 的

[rc-cascader v3.3.0 发布完了，后续在 antd master 分支上进行吧。](https://github.com/react-component/cascader/pull/255#issuecomment-1063745597 )
可以确定下么,大佬  [手动吐血].jpg

**Pull request closed without merging**
