### PR TITLE
fix: Upload types for pass generic

### PR DESCRIPTION
**Pull request by woochanleee**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

Merged. https://github.com/ant-design/ant-design/pull/16360

I think, should pass generic to `UploadChangeParam` in `UploadProps`

https://codesandbox.io/s/antd-typescript-forked-2fr1u?file=/index.tsx

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Check https://github.com/ant-design/ant-design/runs/4701602372?check_suite_focus=true

**Comment by woochanleee** [comment]
@afc163 Ok. Checked it.

**Comment by afc163** [comment]
Could you add a test case like https://github.com/ant-design/ant-design/blob/master/components/form/__tests__/type.test.tsx

**Comment by woochanleee** [comment]
Of course. My mistake.

**Pull request merged**
