### PR TITLE
type: params type support generic

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | type: type optimization |
| 🇨🇳 Chinese | type: 优化 params 类型，支持泛型 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 1013537</samp>

Refactored `Breadcrumb` and `BreadcrumbItem` components to use React hooks and TypeScript, and improved the type safety and consistency of the `Breadcrumb` props. Exposed `Item` and `Separator` as subcomponents of `Breadcrumb`.

### <samp>🤖 Generated by Copilot at 1013537</samp>

*  Refactor `Breadcrumb` and `BreadcrumbItem` components to use React hooks and TypeScript, and add static properties for subcomponents ([link](https://github.com/ant-design/ant-design/pull/43211/files?diff=unified&w=0#diff-f2426e3ced2642a4e369433c0c19b385fca436f57ad4620b4bd2bfcd7ab9254dL83-R82), [link](https://github.com/ant-design/ant-design/pull/43211/files?diff=unified&w=0#diff-a6c84736ab41b111c92cd33d3ae19e5b651015b5d09876c4295859d2abc323d0L106-R114), [link](https://github.com/ant-design/ant-design/pull/43211/files?diff=unified&w=0#diff-a6c84736ab41b111c92cd33d3ae19e5b651015b5d09876c4295859d2abc323d0L40-R40))
*  Improve TypeScript support for `Breadcrumb` component by adding a generic type parameter `T` for `params` prop and using type inference for `itemRender` and `getPath` functions ([link](https://github.com/ant-design/ant-design/pull/43211/files?diff=unified&w=0#diff-f2426e3ced2642a4e369433c0c19b385fca436f57ad4620b4bd2bfcd7ab9254dL49-R51), [link](https://github.com/ant-design/ant-design/pull/43211/files?diff=unified&w=0#diff-f2426e3ced2642a4e369433c0c19b385fca436f57ad4620b4bd2bfcd7ab9254dL63-R69), [link](https://github.com/ant-design/ant-design/pull/43211/files?diff=unified&w=0#diff-f2426e3ced2642a4e369433c0c19b385fca436f57ad4620b4bd2bfcd7ab9254dL116-R115))
*  Remove unnecessary type assertions and annotations from `Breadcrumb` component and pass `itemRenderRoutes` with non-null assertion ([link](https://github.com/ant-design/ant-design/pull/43211/files?diff=unified&w=0#diff-f2426e3ced2642a4e369433c0c19b385fca436f57ad4620b4bd2bfcd7ab9254dL171-R170))

### CODE REVIEW

**Comment by afc163** [comment]
得补用例。

**Comment by afc163** [comment]
ping

**Comment by li-jia-nan** [comment]
> ping

来了来了

**Comment by li-jia-nan** [comment]
> 得补用例。

done

**Review by afc163 — APPROVED** [review]

**Pull request merged**
