### PR TITLE
refactor: reduce empty cycling deps

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Refactor ConfigProvider removing default `renderEmpty` to resolve dist circle deps.     |
| 🇨🇳 Chinese |    重构 ConfigProvider 移除默认的 `renderEmpty` 方法以解决打包循环依赖的问题。      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
感觉如果让每个组件自己维护 empty 的话，`defaultEmpty` 这个方法就不太需要了，反而会有点过度抽象的感觉，里面还要传个 ComponentName

**Comment by zombieJ** [comment]
> 感觉如果让每个组件自己维护 empty 的话，`defaultEmpty` 这个方法就不太需要了，会有点过度抽象，里面还要传个 `ComponentName` 来 switch case

它其实还是统一的，只是因为循环依赖的问题不得不打散到组件里而已。如果是自己搞的，之后如果有新的组件就不会发现原来 Empty 是有规范的。

**Comment by MadCcc** [comment]
> 其实还是统一的

那不如在 provider 里给进去？现在循环依赖还是因为 context 初始化时用到了 `defaultEmpty`

**Comment by zombieJ** [comment]
> 那不如在 provider 里给进去？

开发者不一定会报 ConfigProvider

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
