### PR TITLE
feat: DatePicker & Calendar export generate function directly

### LINKED ISSUE #41749: Calendar with date-fns not styled properly with NextJS
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/wispy-fast-ywg1ty)

### Steps to reproduce

Click Default tab: works correctly. Click Date Fns tab: styling is incorrect (`colorPrimary` is ignored).

### What is expected?

Colored items should be the correct color (`colorPrimary`).

### What is actually happening?

Colored items show as default color (blue).

| Environment | Info |
| --- | --- |
| antd | 5.4.1 |
| React | 18.2.0 |
| System | Windows Professional 21H2 |
| Browser | Chrome Version 112.0.5615.50 (Official Build) (64-bit) |

---
I tried changing calendar.tsx imports from "antd/lib" to "antd/es", which is what the documentation says to do, but this does not compile with NextJS.

I believe this bug also applies to `generatePicker`.

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #41749

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     DatePicker & Calendar export generate function directly now.        |
| 🇨🇳 Chinese |  DatePicker 与 Calendar 直接导出生成自定义日期库组件方法，不再需要通过 module 路径引入使用。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at e1fff21</samp>

This pull request adds support for custom date libraries in the `DatePicker` and `Calendar` components. It introduces the `generatePicker` and `generateCalendar` methods as static properties on the components, which allow users to create custom components with different date libraries and configurations. It also updates the documentation and tests for these features.

### <samp>🤖 Generated by Copilot at e1fff21</samp>

*  Add `generatePicker` and `generateCalendar` methods as static properties of `DatePicker` and `Calendar` components respectively, to allow users to create custom components with different date libraries ([link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-013735da2a9e27cd090e2a7b89864881fcab5e33ff74b538079f42b82ccd3d24L8-R15), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-78eb7aa1662e48dc14665cbcead280795a60503742024dd031b87311186be5eeL18-R32), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-0a5821c1b32fdf9bf1d3bb55702937aead9206b6762df0497ff7b030f405a21aR541-R546), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-7fdce5d71fac3793bf16cbc035559eeb8d5565c0db96d0b9399b5265a8c471b4R292-R297))
*  Update the import of the `generatePicker` and `generateCalendar` functions in the test files and the documentation files to use the methods from the `DatePicker` and `Calendar` components instead ([link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-7fdce5d71fac3793bf16cbc035559eeb8d5565c0db96d0b9399b5265a8c471b4L5-R12), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-7d7f99f1d1ed3ea033947dc9c52dd79eaa41231f99f065da31ba79f01daaaf10L23-R29), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-7d7f99f1d1ed3ea033947dc9c52dd79eaa41231f99f065da31ba79f01daaaf10L62-R68), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-7d7f99f1d1ed3ea033947dc9c52dd79eaa41231f99f065da31ba79f01daaaf10L122-R127), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-7d7f99f1d1ed3ea033947dc9c52dd79eaa41231f99f065da31ba79f01daaaf10L139-R145), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-7d7f99f1d1ed3ea033947dc9c52dd79eaa41231f99f065da31ba79f01daaaf10L173-R175), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-e506cd45013ef022ee1e0e5d855ee37b6d91d4019e2f32a73c758df5441b108eL21-R27), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-e506cd45013ef022ee1e0e5d855ee37b6d91d4019e2f32a73c758df5441b108eL60-R66), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-e506cd45013ef022ee1e0e5d855ee37b6d91d4019e2f32a73c758df5441b108eL120-R125), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-e506cd45013ef022ee1e0e5d855ee37b6d91d4019e2f32a73c758df5441b108eL137-R143), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-e506cd45013ef022ee1e0e5d855ee37b6d91d4019e2f32a73c758df5441b108eL171-R173))
*  Update the import of the `luxonGenerateConfig` from the `rc-picker` library in the documentation files to use the `lib` directory instead of the `es` directory, for consistency with the other date library imports ([link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-7d7f99f1d1ed3ea033947dc9c52dd79eaa41231f99f065da31ba79f01daaaf10L162-R162), [link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-e506cd45013ef022ee1e0e5d855ee37b6d91d4019e2f32a73c758df5441b108eL160-R160))
*  Reorder the import of the types from the `generatePicker` module in the `components/date-picker/index.ts` file, to group the types together and follow the alphabetical order ([link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-78eb7aa1662e48dc14665cbcead280795a60503742024dd031b87311186be5eeL5-R7))
*  Move the assignment of the `_InternalPanelDoNotUseOrYouWillBeFired` and `_InternalRangePanelDoNotUseOrYouWillBeFired` properties to the `DatePicker` component after the type casting, to avoid type errors ([link](https://github.com/ant-design/ant-design/pull/41773/files?diff=unified&w=0#diff-78eb7aa1662e48dc14665cbcead280795a60503742024dd031b87311186be5eeL18-R32))

### CODE REVIEW

**Review by MadCcc — APPROVED** [review]

**Comment by devuxer** [comment]
@zombieJ said features are released at the end of the month, but it's now 5 days into May, and I still don't see this. When will this be released?

I just want my theme to work properly in NextJS when using Date Picker and Calendar.

**Comment by zombieJ** [comment]
@devuxer, I still work with DatePicker `changeOnBlur` feature which may need additional days. Sorry for delay.

**Comment by devuxer** [comment]
@zombieJ, I understand. Thanks for the update!

**Comment by devuxer** [comment]
Hi @zombieJ ,

Sorry to message again, but do you think this feature will be released by the end of the month?

Or do you have a workaround?

This is a blocker for me.

Thank you!

**Comment by yoyo837** [comment]
> Hi @zombieJ ,
> 
> Sorry to message again, but do you think this feature will be released by the end of the month?
> 
> Or do you have a workaround?
> 
> This is a blocker for me.
> 
> Thank you!

https://github.com/ant-design/ant-design/pull/42276 It is on the way.

**Pull request merged**
