### PR TITLE
demo: remove react-dnd, use dnd-kit

### PR DESCRIPTION
**Pull request by linxianxi**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      -     |
| 🇨🇳 Chinese |      -     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
@SocketSecurity ignore core-js@3.27.1
@SocketSecurity ignore core-js@3.27.2
@SocketSecurity ignore core-js-pure@3.27.2
@SocketSecurity ignore esbuild@0.15.18
@SocketSecurity ignore esbuild@0.16.17

**Comment by li-jia-nan** [comment]
image

截图快照为啥会变？

**Comment by linxianxi** [comment]
> image
> 
> 截图快照为啥会变？

image
原来的 demo 外面加了个 div 导致 Tab 间隔没了，然后手动加了间隔。现在是 cloneElement，保持了 Tabs 默认样式。

**Comment by linxianxi** [comment]
原来的 demo 外面加了个 div 导致 Tab 间隔没了，然后手动加了间隔。现在是 cloneElement，保持了 Tabs 默认样式。

**Review by li-jia-nan — APPROVED** [review]

**Pull request merged**
