### PR TITLE
Adds support for custom styles in Transfer and Transfer operation.

### PR DESCRIPTION
**Pull request by eduludi**
The `Transfer` component can't be completely customized through style props. This PR adds a wrapper style (at  for the wrapping `ant-transfer`) and another one for the 'Operation` component.

* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Update API docs for the component.
* [x] Update TypeScript definition for the component.

### CODE REVIEW

**Comment by afc163** [comment]
Could you add test case?

**Comment by eduludi** [comment]
I don't see any test for `Transfer`'s `listStyle` property. Do you have an example on how to tests for custom styles?

**Comment by afc163** [comment]
Just make sure `style` and `operationStyle` (or listStyle we missed) can be rendered to the correct dom node.

**Comment by afc163** [comment]
Nice job! @eduludi

**Pull request merged**
