### PR TITLE
docs(theme): improve built-in component style

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      --     |
| 🇨🇳 Chinese |     改进内置组件样式      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
样式和官方组件不太一样：https://ant.design/components/alert-cn#components-alert-demo-icon

**Comment by Wxh16144** [comment]
> https://ant.design/components/alert-cn#components-alert-demo-icon

我无脑 copy 了， 晚点我重新搞一下~

**Comment by Wxh16144** [comment]
> 样式和官方组件不太一样：https://ant.design/components/alert-cn#components-alert-demo-icon

看了一下，官方的 demo 中 ， 标题和 文本颜色都没有根据 type 改变样式。如果去掉的话在文档中感觉差点意思。 看其他几个组件库文档都是跟随 type 改变颜色的。

**Comment by afc163** [comment]
ci 挂了

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
