### PR TITLE
add missing translation in mn_MN.ts

### PR DESCRIPTION
**Pull request by ariunbatb**
added OK text translation in MN

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | add missing translation in mn_MN.ts |
| 🇨🇳 Chinese | 在 mn_MN.ts 中添加缺失的翻译 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 2fea754</samp>

Improved Mongolian translations for some components. Updated the `mn_MN` locale file to use 'Тийм' instead of 'OK' for confirmation buttons.

### <samp>🤖 Generated by Copilot at 2fea754</samp>

*  Localize confirmation buttons for Mongolian language and culture ([link](https://github.com/ant-design/ant-design/pull/42512/files?diff=unified&w=0#diff-a31622e25c204e1c6947c35d39d8e18e564a2c7f0fa7c3d3e6629305e37a241cL15-R15), [link](https://github.com/ant-design/ant-design/pull/42512/files?diff=unified&w=0#diff-a31622e25c204e1c6947c35d39d8e18e564a2c7f0fa7c3d3e6629305e37a241cL21-R26))
*  Change `filterConfirm` property of `Table` component from 'OK' to 'Тийм' ([link](https://github.com/ant-design/ant-design/pull/42512/files?diff=unified&w=0#diff-a31622e25c204e1c6947c35d39d8e18e564a2c7f0fa7c3d3e6629305e37a241cL15-R15))
*  Change `okText` and `justOkText` properties of `Modal` and `Popconfirm` components from 'OK' to 'Тийм' ([link](https://github.com/ant-design/ant-design/pull/42512/files?diff=unified&w=0#diff-a31622e25c204e1c6947c35d39d8e18e564a2c7f0fa7c3d3e6629305e37a241cL21-R26))

### CODE REVIEW

**Comment by yoyo837** [comment]
Please fill changelog in the PR

**Comment by ariunbatb** [comment]
add missing translation in mn_MN.ts

**Comment by yoyo837** [comment]
In here:
image

**Review by li-jia-nan — APPROVED** [review]

**Comment by li-jia-nan** [comment]
> In here

我给他加上了

**Comment by li-jia-nan** [comment]
update snap pls.

**Comment by ariunbatb** [comment]
> update snap pls.

what means update snap? Can you elaborate more

**Comment by li-jia-nan** [comment]
image

**Comment by ariunbatb** [comment]
> image

done

> > > update snap pls.
> > 
> > 
> > what does update snap means? Can you elaborate more
> 
> CI failed because the snapshot changed, you need execute `npm run test:update components/locale` to update snapshot

done

**Comment by ariunbatb** [comment]
All checks have passed

**Comment by ariunbatb** [comment]
failed in commit. it says "Some checks were not successful". Sorry it's my first time

**Comment by li-jia-nan** [comment]
> failed in commit. it says "Some checks were not successful". Sorry it's my first time

You can ignore it, thanks for your contribution

**Pull request merged**
