### PR TITLE
docs: update demo

### LINKED ISSUE #41530: 官方示例Select选择器没有设置宽度并带搜索框时样式异常
### Reproduction link

[https://3bgn3i.csb.app/](https://3bgn3i.csb.app/)

### Steps to reproduce

1.点击select选择器，先选择一个选项（必须）
2.在select选择器进行输入即可复现

bug32901

### What is expected?

宽度显示正常

### What is actually happening?

宽度异常

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome 111.0.5563.147 |

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

- close #41530

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | docs: update demo |
| 🇨🇳 Chinese | - |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
看了一下确实是 bug，现在所有的 demo 都有宽度，看起来 Select 需要一个 min-width

**Comment by li-jia-nan** [comment]
我单独开一个 PR 修吧

**Review by dnalcudia-ksquare — APPROVED** [review]
LGTM!

**Review by MadCcc — APPROVED** [review]

**Comment by li-jia-nan** [comment]
加上 min-width 会有问题，还是只能改 demo，宽度让用户自己加

**Comment by yoyo837** [comment]
要revert?

**Comment by yoyo837** [comment]
噢, 说的是组件, 不是demo

**Comment by li-jia-nan** [comment]
不用 revert，加上 min-width 那个 PR 还没合呢，我加到一半发现有问题就关了

**Pull request merged**
