### PR TITLE
added nameFormatter for routes

### PR DESCRIPTION
**Pull request by plandem**
https://github.com/ant-design/ant-design/issues/1999

### CODE REVIEW

**Comment by plandem** [comment]
fixed case when linkRender must accept raw paths, e.g. when each route has a full path already, i.e.: paths will be like:
```
['/a', '/a/b', '/a/b/c']
```

with previous behaviour we would have **/a/a/b/a/b/c**. now linkRender accept array of paths, so custom render can override this behaviour correctly, e.g.:
```
<Breadcrumb 
   routes={breadcrumb}
   linkRender={(paths, name) => { return <a href={`#/${paths.pop() || ''}`}>{name}</a>} }
/>

```

**Comment by afc163** [comment]
Thx! I move `nameFormatter` into `nameRender`, by adding two arguments.

```js
nameRender(breadcrumbName, route, params) {
}
```

**Comment by plandem** [comment]
Maybe you missed, but I also changed linkedRender - know it gets 'paths', not 'href'.

**Comment by afc163** [comment]
oh~ that would break old `linkRender`.

**Comment by afc163** [comment]
The current Breadcrumb API (`linkRender` & `nameRender`) is ugly and redundant, it should  be changed to `itemRender`  in `2.0`.

**Pull request merged**
