### PR TITLE
style: 💄 @info-color should be @primary-color defaultly

### PR DESCRIPTION
**Pull request by kaoding**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5442

**Comment by kaoding** [comment]
> #5442

我觉得 info 色默认跟随是更合理的，success，error等有明确的指示状态，默认定义为状态色，info默认不一定是佛晓蓝，跟随自定义的主题会更好一些，就算跟随主题，用户也还是可以自定义的。

**Comment by afc163** [comment]
主色是绿色/红色/黄色就会比较麻烦。

**Comment by kaoding** [comment]
image
对比
image
可以问一问设计的同学

**Comment by kaoding** [comment]
> 主色是绿色/红色/黄色就会比较麻烦。

这也是一个问题，碰到这种情况就要修改 info 色了。

**Comment by afc163** [comment]
@pasturn

**Pull request merged**
