### PR TITLE
chore: fix timeline TimelineItemProps typo

### PR DESCRIPTION
**Pull request by mgcrea**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

`TimelineItemProps` had a typo

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix `TimeLineItemProps` typo to `TimelineItemProps`. |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by hengkx** [comment]
Will it affect users

**Comment by mgcrea** [comment]
@hengkx it will only impact development (typescript error) of users that did rely on importing this `TimelineItemProps`. Which you would only do if you are deeply extending the antd component. Maybe a couple of users will notice an error in vscode but I think it is pretty safe to merge.

**Comment by afc163** [comment]
image

**Comment by hengkx** [comment]
@mgcrea I'm very sorry that my error caused the branch to be disordered. Please re submit a PR. If you don't have time, please let me know that I will reopen a new PR. thank you very much for your feedback.

**Comment by hengkx** [comment]
ref #27001

**Pull request closed without merging**
