### PR TITLE
i18n: add new locale

### PR DESCRIPTION
**Pull request by richxcame**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

Turkmen language were missing

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Added turkmen language |
| 🇨🇳 Chinese | 添加土库曼语 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by richxcame** [comment]
## IMPORTANT
Please, upgrade versions of dependencies "rc-pagination": "~3.1.15", "rc-picker": "~2.6.7" in `package.json`. Because the packages were localized in this versions

**Comment by afc163** [comment]
- https://github.com/react-component/pagination/releases/tag/v3.1.16
- https://github.com/react-component/picker/releases/tag/v2.6.8

**Comment by richxcame** [comment]
Can anyone help?

**Comment by yoyo837** [comment]
Follow the steps described in https://ant.design/docs/react/i18n#Adding-new-language to continue with the rest of the PR. Thanks.

**Comment by richxcame** [comment]
> Follow the steps described in https://ant.design/docs/react/i18n#Adding-new-language to continue with the rest of the PR. Thanks.

First of all thank you for all your replies. I think shown errors because of `rc-picker` and `rc-pagination` versions, like @afc163 said [here](https://github.com/ant-design/ant-design/pull/35061#issuecomment-1111946742)
I can't touch package.json [(PR)](https://github.com/ant-design/ant-design/pull/35060#issue-1205862213). So can you upgrade those packages to latest for me?

**Comment by richxcame** [comment]
I fully read the [docs](https://ant.design/docs/react/i18n#Adding-new-language)

**Comment by yoyo837** [comment]
Please switch to the feature branch, and rebase.

**Comment by afc163** [comment]
feature branch please

**Comment by richxcame** [comment]
Switched to `feature` branch

**Comment by afc163** [comment]
Mixed other commits.

**Comment by afc163** [comment]
ping @richxcame

**Comment by richxcame** [comment]
> ping @richxcame

I'm here

**Comment by yoyo837** [comment]
Rebase again please.

**Comment by richxcame** [comment]
> Rebase again please.

Is it related with me?)

**Comment by afc163** [comment]
Rebase feature to fix broken test cases.

**Comment by richxcame** [comment]
> Rebase feature to fix broken test cases.

I did it

**Comment by afc163** [comment]
截屏2022-05-16 上午10 02 19

**Comment by richxcame** [comment]
> 截屏2022-05-16 上午10 02 19

Thanx, error resolved.

**Comment by richxcame** [comment]
ping @afc163 @yoyo837. I stupidly did some mistakes and rewrite my features to another PR.
#35603

**Pull request closed without merging**
