### PR TITLE
fix: type incompatibility in strict mode

### LINKED ISSUE #36122: Error: node_modules/antd/lib/tree-select/index.d.ts(18,18) | Error: node_modules/antd/lib/tree/Tree.d.ts(86,18)
### Reproduction link

[https://github.com/maifeeulasad/react-pipeline/tree/8521b5638e3634d0dadb63196acbb31abc3fa165](https://github.com/maifeeulasad/react-pipeline/tree/8521b5638e3634d0dadb63196acbb31abc3fa165)

### Steps to reproduce

```
clone
yarn
yarn build
```

### What is expected?

A proper build

### What is actually happening?

Getting the following error:
```
Run yarn build
  yarn build
  shell: /usr/bin/bash -e {0}
yarn run v1.22.19
$ tsc && vite build
Error: node_modules/antd/lib/tree-select/index.d.ts(18,18): error TS2430: Interface 'TreeSelectProps<ValueType, OptionType>' incorrectly extends interface 'Omit<TreeSelectProps<ValueType, OptionType>, "mode" | "getInputElement" | "inputIcon" | "backfill" | "showTreeIcon" | "treeMotion" | "treeLine">'.
  Types of property 'switcherIcon' are incompatible.
    Type 'SwitcherIcon' is not assignable to type 'IconType'.
      Type '(props: { expanded: boolean; }) => ReactNode' is not assignable to type 'IconType'.
        Type '(props: { expanded: boolean; }) => ReactNode' is not assignable to type '(props: TreeNodeProps<DataNode>) => ReactNode'.
          Types of parameters 'props' and 'props' are incompatible.
            Type 'TreeNodeProps<DataNode>' is not assignable to type '{ expanded: boolean; }'.
              Types of property 'expanded' are incompatible.
                Type 'boolean | undefined' is not assignable to type 'boolean'.
                  Type 'undefined' is not assignable to type 'boolean'.
Error: node_modules/antd/lib/tree/Tree.d.ts(86,18): error TS2430: Interface 'TreeProps<T>' incorrectly extends interface 'Omit<TreeProps<T>, "direction" | "draggable" | "prefixCls" | "showLine">'.
  Types of property 'icon' are incompatible.
    Type 'ReactNode | ((nodeProps: AntdTreeNodeAttribute) => ReactNode)' is not assignable to type 'IconType'.
      Type '(nodeProps: AntdTreeNodeAttribute) => ReactNode' is not assignable to type 'IconType'.
        Type '(nodeProps: AntdTreeNodeAttribute) => ReactNode' is not assignable to type '(props: TreeNodeProps<DataNode>) => ReactNode'.
          Types of parameters 'nodeProps' and 'props' are incompatible.
            Type 'TreeNodeProps<DataNode>' is not assignable to type 'AntdTreeNodeAttribute'.
              Types of property 'eventKey' are incompatible.
                Type 'Key | undefined' is not assignable to type 'string'.
                  Type 'undefined' is not assignable to type 'string'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 2.
```

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.1.0 |
| System |  ubuntu-latest |
| Browser | node 14 |

---
https://github.com/maifeeulasad/react-pipeline/runs/6949098925?check_suite_focus=true

### PR DESCRIPTION
**Pull request by Dunqing**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix: #36122

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix type incompatibility    |
| 🇨🇳 Chinese |     修复类型不兼容      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Could you add a type test for this?

**Comment by Dunqing** [comment]
> Could you add a type test for this?

I'm getting a lot of errors when I enable strict in the `antd` project. I don't know how to test it.

**Comment by afc163** [comment]
We need to add a `type.strict.test.ts` file under `__tests__`, that should run in strict mode.

**Comment by Dunqing** [comment]
> We need to add a `type.strict.test.ts` file under `__tests__`, that should run in strict mode.
> 
> @Dunqing Could you help to add this workflow?

Of course, I would love to do this!

**Comment by AMINE1921** [comment]
I still have same error! @Dunqing 

`
node_modules/antd/lib/tree-select/index.d.ts:18:18 - error TS2430: Interface 'TreeSelectProps<ValueType, OptionType>' incorrectly extends interface 'Omit<TreeSelectProps<ValueType, OptionType>, "mode" | "getInputElement" | "inputIcon" | "backfill" | "showTreeIcon" | "treeMotion" | "treeLine">'.
  Types of property 'switcherIcon' are incompatible.
    Type 'SwitcherIcon' is not assignable to type 'IconType'.
      Type '(props: { expanded: boolean; }) => ReactNode' is not assignable to type 'IconType'.
        Type '(props: { expanded: boolean; }) => ReactNode' is not assignable to type '(props: TreeNodeProps<DataNode>) => ReactNode'.
          Types of parameters 'props' and 'props' are incompatible.
            Type 'TreeNodeProps<DataNode>' is not assignable to type '{ expanded: boolean; }'.
              Types of property 'expanded' are incompatible.
                Type 'boolean | undefined' is not assignable to type 'boolean'.
                  Type 'undefined' is not assignable to type 'boolean'.

18 export interface TreeSelectProps<ValueType = any, OptionType extends BaseOptionType | DefaultOptionType = DefaultOptionType> extends Omit<RcTreeSelectProps<ValueType, OptionType>, 'showTreeIcon' | 'treeMotion' | 'inputIcon' | 'mode' | 'getInputElement' | 'backfill' | 'treeLine'> {
                    ~~~~~~~~~~~~~~~

node_modules/antd/lib/tree/Tree.d.ts:86:18 - error TS2430: Interface 'TreeProps<T>' incorrectly extends interface 'Omit<TreeProps<T>, "direction" | "draggable" | "prefixCls" | "showLine">'.
  Types of property 'icon' are incompatible.
    Type 'ReactNode | ((nodeProps: AntdTreeNodeAttribute) => ReactNode)' is not assignable to type 'IconType'.
      Type '(nodeProps: AntdTreeNodeAttribute) => ReactNode' is not assignable to type 'IconType'.
        Type '(nodeProps: AntdTreeNodeAttribute) => ReactNode' is not assignable to type '(props: TreeNodeProps<DataNode>) => ReactNode'.
          Types of parameters 'nodeProps' and 'props' are incompatible.
            Type 'TreeNodeProps<DataNode>' is not assignable to type 'AntdTreeNodeAttribute'.
              Types of property 'eventKey' are incompatible.
                Type 'Key | undefined' is not assignable to type 'string'.
                  Type 'undefined' is not assignable to type 'string'.

86 export interface TreeProps<T extends BasicDataNode = DataNode> extends Omit<RcTreeProps<T>, 'prefixCls' | 'showLine' | 'direction' | 'draggable'> {  
                    ~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  node_modules/antd/lib/tree-select/index.d.ts:18
     1  node_modules/antd/lib/tree/Tree.d.ts:86
`

**Comment by Dunqing** [comment]
> I still have same error! @Dunqing So because of that I can't build my npm package 

Not yet released

**Pull request merged**
