### PR TITLE
fix: DatePicker style in cssVar mode

### LINKED ISSUE #46525: date-picker   样式全错乱
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

https://ant.design/components/date-picker-cn

image

image

image

### What is expected?

https://ant.design/components/date-picker-cn

### What is actually happening?

https://ant.design/components/date-picker-cn

| Environment | Info |
| --- | --- |
| antd | 5.12.3 |
| React | 18 |
| System | windows 10 |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/46525

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Fix DatePicker style in `cssVar` mode.     |
| 🇨🇳 Chinese |      修复 DatePicker 组件在 CSS 变量模式下的样式问题。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
要不要加用例 😳

**Comment by MadCcc** [comment]
> 要不要加用例 😳

image diff 能测

**Comment by yoyo837** [comment]
> Congrats! No visual-regression diff found

Congrats! No visual-regression diff found

**Comment by afc163** [comment]
为啥 visual diff 没发现这个问题？

**Review by kiner-tang — APPROVED** [review]

**Pull request merged**
