### PR TITLE
fix: table loading css error when sticky is true

### LINKED ISSUE #32649: Table loading css error when sticky is true
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/gu-ding-lie-antd-4-17-0-alpha-7-forked-kjhne?file=/index.js)

### Steps to reproduce
Scroll to the bottom 

### What is expected?
css have no error

### What is actually happening?
css error

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | >=16.9.0 |
| System | MacOS Big Sur 11.1 |
| Browser | Chrome90.0.4430.93（正式版本） (x86_64) |

---
Follow the header

Oct-26-2021 16-43-30

### PR DESCRIPTION
**Pull request by miloudbelaabed**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/32649

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Table `loading` jumpy style when set `sticky`.         |
| 🇨🇳 Chinese |  修复 Table 当设置 `sticky` 的时候  `loading` 样式跳动。         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/4951df182be5642d3387ee6b681cd581e9ce42f0

**Comment by afc163** [comment]
#5937 won't happend when remove `overflow: hidden` in `.ant-spin-blur`!

**Comment by miloudbelaabed** [comment]
aaaa i got it man

**Comment by miloudbelaabed** [comment]
First of all i just fix what the issue said, and secondly why you want to let the user change the page index when loading is true , loading is true means you will get new data, so i think its not important to make it possible ?

**Pull request merged**
