### PR TITLE
feat(actions): Automatic Rebase

### PR DESCRIPTION
**Pull request by orzyyyy**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

Comment `/rebase`, it would rebase automatically.

Related  to https://github.com/cirrus-actions/rebase#github-action-to-automatically-rebase-prs

### CODE REVIEW

**Comment by shaodahong** [comment]
要是有大量的 actions 需求建议是找 @afc163 create 一个 actions 仓库，集中起来，体验了下 actions 确实很好用，代码简洁，利用官方的 sdk 很快速就能实现一些自动化

**Comment by orzyyyy** [comment]
还没必要吧，等正式版再说，现在假假爽一下还是可以的。目前要是出问题了，很难找到合适的解决方案

**Comment by orzyyyy** [comment]
https://github.com/sdras/awesome-actions

**Pull request merged**
