### PR TITLE
docs: update contributors list in site

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
|  | Preview|
|-- | --|
| Before |  image |
| After |  image |

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  -         |
| 🇨🇳 Chinese |    -       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
直接用 https://ant.design/components/avatar/#components-avatar-demo-group ？

**Comment by xrkffgg** [comment]
目前用的这个https://github.com/chenshuai2144/github-contributors-list。
Avatar 是放到了 a 标签里，实际上是 a 标签决定了这个间距。
如果用 Avatar.Group 只能获得一个 border 的样式，这个间距还是需要 a 来设置

**Comment by xrkffgg** [comment]
要加 Avatar.Group 吗？

**Comment by afc163** [comment]
直接改 https://github.com/chenshuai2144/github-contributors-list 比较好

**Comment by xrkffgg** [comment]
我先试试

**Comment by xrkffgg** [comment]
😂  循序在他的里面，看来只能去那里面了。

**Comment by xrkffgg** [comment]
@chenshuai2144 😉

**Pull request closed without merging**
