### PR TITLE
feat: Add a new prop breakpointMap in Sider to allow configuration of breakpoints

### PR DESCRIPTION
**Pull request by atanasgeorgiev93**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

**Please note:** I raised this PR against `master` branch because there was no `feature` branch open. I'm happy to adapt the PR if that is required.

### 🔗 Related issue link

[Allow Configuration of breakpoints in Layout Component](https://github.com/ant-design/ant-design/issues/19694)

### 💡 Background and solution

1. Allow a new property `breakpointMap` to be passed which can define new values for the breakpoints.
2. If that property is not passed, then breakpointMap will get the default value which is hardcoded at the moment in the component.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/layout/demo/customBreakpoints.md](https://github.com/atanasgeorgiev93/ant-design/blob/feat/Sider-customBreakpointMap/components/layout/demo/customBreakpoints.md)
[View rendered components/layout/index.en-US.md](https://github.com/atanasgeorgiev93/ant-design/blob/feat/Sider-customBreakpointMap/components/layout/index.en-US.md)

-----
[View rendered components/layout/demo/customBreakpoints.md](https://github.com/atanasgeorgiev93/ant-design/blob/feat/Sider-customBreakpointMap/components/layout/demo/customBreakpoints.md)
[View rendered components/layout/index.en-US.md](https://github.com/atanasgeorgiev93/ant-design/blob/feat/Sider-customBreakpointMap/components/layout/index.en-US.md)

### CODE REVIEW

**Comment by zombieJ** [comment]
It's may not work as expect since there still exist media query in `antd.css`.

**Comment by wildmanas66** [comment]
Not sure what I am supposed to do

**Comment by afc163** [comment]
conflicted

**Comment by afc163** [comment]
feature branch please~

**Comment by afc163** [comment]
close for no response

**Pull request closed without merging**
