### PR TITLE
update onRow Table properties documentation

### PR DESCRIPTION
**Pull request by woolfi182**

### CODE REVIEW

**Comment by afc163** [comment]
Could you help us update Chinese documentaton?

**Review by yutingzhao1991 — APPROVED** [review]

**Comment by afc163** [comment]
Could you help us update **the same code part** in Chinese documentation?

**Comment by woolfi182** [comment]
yes, I will do it

**Comment by woolfi182** [comment]
Updated

**Review by afc163 — APPROVED** [review]

**Pull request merged**
