### PR TITLE
demo: fixed the avatars are all the same picture

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

img 的 src 路径一样，不会重复发送请求，会读缓存，所以需要给 url 加上唯一标识

### before:
image

### after:
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | demo: fixed the avatars are all the same picture |
| 🇨🇳 Chinese | demo: 修复了 demo 中的头像都是同一个的问题（不用写进 changeLog） |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
靠，用 `Math.random()` 之后，每次快照都会变，导致ci过不了

**Comment by li-jia-nan** [comment]
看来只能写死1234了

**Comment by yoyo837** [comment]
这样这个snap会每次都更新吧?

**Comment by li-jia-nan** [comment]
> 这样这个snap会每次都更新吧?

是的，我改成常量了

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
