### PR TITLE
chore: split chunks

### PR DESCRIPTION
**Pull request by MadCcc**
- chore: split chunks
- chore: update bisheng version

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/24788

https://github.com/ant-design/ant-design/issues/35090

### 💡 Background and solution
https://github.com/benjycui/bisheng/pull/253
**原本的包分析**

image

**解决方案**

image

1. components 单独拆了一个 chunk
2. @ant-design/icon 里设置了 maxSize，自动分 chunk

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      -     |
| 🇨🇳 Chinese |     -      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片

走 ES Module 的话，不应该有 lib 吧。

**Comment by MadCcc** [comment]
> 图片
> 
> 走 ES Module 的话，不应该有 lib 吧。

这个包现在是全量引的，我看看能不能把 lib 摇了

**Comment by MadCcc** [comment]
image
大小没变，还得再看下

**Comment by afc163** [comment]
下手前可以把一些计划和进展都回复到 https://github.com/ant-design/ant-design/issues/35090

**Comment by afc163** [comment]
https://preview-35222-ant-design.surge.sh/index-299ba5e1.js 貌似没压缩。

**Review by afc163 — APPROVED** [review]

**Pull request merged**
