### PR TITLE
feat: add Typography.Text type success

### LINKED ISSUE #26127: Provide Typography.Text type=success?
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now `type` can be `secondary`, `warning` and `danger`. It would be nice to provide `success` as well, so that a colored icon can be easily implemented via `<Typography.Text type="success"><CheckCircleFilled /></Topography.Text>`, instead of defining a class for it every time.

### What does the proposed API look like?
Add `type=success` to `<Topography.Text>`

### PR DESCRIPTION
**Pull request by llwslc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [x] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #26127

### 💡 Background and solution

Add type=success to <Topography.Text>

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  add Typography.Text type success  |
| 🇨🇳 Chinese | 新增 Typography.Text success 类型。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/typography/demo/text.md](https://github.com/llwslc/ant-design/blob/text-type/components/typography/demo/text.md)
[View rendered components/typography/index.en-US.md](https://github.com/llwslc/ant-design/blob/text-type/components/typography/index.en-US.md)
[View rendered components/typography/index.zh-CN.md](https://github.com/llwslc/ant-design/blob/text-type/components/typography/index.zh-CN.md)

### CODE REVIEW

**Review by xrkffgg — APPROVED** [review]

**Comment by afc163** [comment]
primary text is similar to Link, I prefer not adding this for now.

**Comment by llwslc** [comment]
> Primary text is similar to Link, I prefer not adding this for now.

<Link> 会渲染为 <a>, 和 <span> 不一样

**Comment by afc163** [comment]
That is Why I use "similar".

**Comment by llwslc** [comment]
哦哦, 那 Primary text 该怎么弄呢, 如果写 css 的话, 其实所有 type 也都没必要了

**Comment by afc163** [comment]
『主文本』这个语义很奇怪的，文本的重要程度应该是由加粗/高亮来定义的。

**Comment by llwslc** [comment]
嗯嗯, 晚上我改一下

**Pull request merged**
