### PR TITLE
chore: site static js use contentHash

### LINKED ISSUE #15925: index.js need a hash in filename
Screen Shot 2019-04-08 at 14 02 22

Cloudflare uses `max-age` to cache the static resources, `index.js` need a hash to expire the cache.

### PR DESCRIPTION
**Pull request by ycjcl868**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

Close #15925 .

### 💡 Solution

[bisheng](https://github.com/benjycui/bisheng) add hash when just run in `build` mode.

image

Depends on 
- benjycui/bisheng#188
- benjycui/bisheng#189
- benjycui/bisheng#190
- benjycui/bisheng#191
- benjycui/bisheng#192
- ant-design/bisheng-plugin-antd#19

### CODE REVIEW

**Review by yesmeck — APPROVED** [review]

**Comment by ycjcl868** [comment]
wait, I'm solving css hash files.

**Review by zombieJ — APPROVED** [review]

**Review by ztplz — APPROVED** [review]

**Comment by afc163** [comment]
https://deploy-preview-15976--ant-design.netlify.com/

样式没了。

**Review by afc163 — CHANGES_REQUESTED** [review]
https://deploy-preview-15976--ant-design.netlify.com/

样式没了。

**Comment by afc163** [comment]
Depends on https://github.com/benjycui/bisheng/pull/191

**Comment by ycjcl868** [comment]
Preview url: https://deploy-preview-15976--ant-design.netlify.com/index-cn

**Comment by ycjcl868** [comment]
@afc163 [bisheng-plugin-antd](https://github.com/ant-design/bisheng-plugin-antd) should update.

**Comment by afc163** [comment]
image

这个发布后，缓存时间可以改到 1 个月了。@yesmeck

**Comment by yesmeck** [comment]
已改

**Pull request merged**
