### PR TITLE
feat: Georgian translation

### PR DESCRIPTION
**Pull request by PrimulaX**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
Georgian translation were missing.

### 📝 Changelog
Added Georgian translation.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Add Georgian locale      |
| 🇨🇳 Chinese |    添加格鲁吉亚语言环境      |
| 🇬🇪  Georgian |    დაემატა ქართული ენის ლოკალი    |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
You need add `rc-picker/lib/locale/ka_GE` first.

#ref https://github.com/react-component/picker/pull/164

**Comment by PrimulaX** [comment]
Hi @yoyo837,
Ah okay, I didn't notice that, thanks.

**Comment by PrimulaX** [comment]
@yoyo837 I made the PR on rc-picker.

**Comment by yoyo837** [comment]
Waiting for upstream release.

**Comment by PrimulaX** [comment]
@yoyo837 Thanks.

**Comment by afc163** [comment]
@yoyo837 We should add documentation about how to add a new language step by step.

**Comment by yoyo837** [comment]
> @yoyo837 We should add documentation about how to add a new language step by step.

Ok i will do this in my free time.

**Comment by PrimulaX** [comment]
Hi @yoyo837, 

Can we merge this one?

**Comment by yoyo837** [comment]
Please rebase and update `rc-picker` > 2.5.16

**Comment by yoyo837** [comment]
Docs and test case needed.

**Comment by PrimulaX** [comment]
@yoyo837 I did rebase and update rc-picker or I did something wrong.

**Comment by yoyo837** [comment]
After rebase, please `push -f`

**Comment by PrimulaX** [comment]
@yoyo837 Okay, I did force push.

**Comment by yoyo837** [comment]
I can not reopen this, please create a new PR.

**Comment by PrimulaX** [comment]
@yoyo837 Okay I did create a new PR. #32106

**Pull request closed without merging**
