### PR TITLE
SK Localization

### PR DESCRIPTION
**Pull request by Kamahl19**
Hi, here is the SK localization. Thanks!

### CODE REVIEW

**Comment by benjycui** [comment]
CI failed..

**Comment by benjycui** [comment]
Make sure that you had add locale to dependencies:

```bash
Module not found: Error: Cannot resolve module 'rc-pagination/lib/locale/sk_SK'
```

**Comment by minsungryu** [comment]
rc-pagination#64(https://github.com/react-component/pagination/pull/64) and rc-calender#226(https://github.com/react-component/calendar/pull/226) is waiting to be merged.

**Comment by Kamahl19** [comment]
@benjycui Hi, both pagination and calendar translation have been merged so it should work fine now.

**Comment by benjycui** [comment]
Actually.. rc-calendar need to update..

**Comment by Kamahl19** [comment]
@benjycui Hi, I see you updated calendar to 7.7.0 already.

**Comment by afc163** [comment]
Dependencies of antd should be update.

**Comment by afc163** [comment]
@Kamahl19

**Comment by Kamahl19** [comment]
@afc163 should i just update rc-calendar version in package.json?

**Comment by afc163** [comment]
Yes, but I already update it in `feature-2.9`, I think you just need to rebase it.

**Comment by Kamahl19** [comment]
@afc163 Thanks, I just did that

**Pull request merged**
