### PR TITLE
fix: Button Multiple Children Package span

### PR DESCRIPTION
**Pull request by crazyair**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

解决当 Button 的 children 为多元素，导致激活 gap 样式

image

如上图，第一个 Button 增加了间距

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Button Multiple Children Package span       |
| 🇨🇳 Chinese |     Button 多 children 包 span     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
解决啥问题？

**Comment by crazyair** [comment]
> 解决啥问题？

补充了问题原因

**Comment by crazyair** [comment]
> master

这图不太对啊，我在这个分支看的 search 是有间距的
image

**Comment by afc163** [comment]
包了这个会让下面的代码丢失间距。

```jsx
<Button>
  <Icon />
  <span>提交</span>
</Button>
```

**Comment by crazyair** [comment]
> 包了这个会让下面的代码丢失间距。
> 
> ```js
> <Button>
>   <Icon />
>   <span>提交</span>
> </Button>
> ```

但是会让这里每个 test 都增加间距
```tsx
<Button>
   <span>test</span>
   <span>test</span>
   <span>test</span>
</Button>
```

**Comment by crazyair** [comment]
暂时本地改样式 `gap: 0`

**Pull request closed without merging**
