### PR TITLE
(antd 3.0.0) English as a default language, Chinese via local-provider

### PR DESCRIPTION
**Pull request by kvetoslavnovak**
* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Following our discussion https://github.com/ant-design/ant-design/issues/3501 
> @benjycui But this cannot be done before next major version, even it is accepted.

here is the R
- to have English as a default languague
- use Chinese with local-provider

(I did not delete the original https://github.com/ant-design/ant-design/blob/master/components/locale-provider/en_US.tsx )

### CODE REVIEW

**Comment by benjycui** [comment]
Thanks, but this is a breaking change, and we are not going to publish `3.0.0`.

Actually, we want `antd` to be stable for at least half year...

**Comment by kvetoslavnovak** [comment]
@benjycui I know, I have mentioned the same condition in the comment. 
The PR was ment to go with next major versivon release and to have this PR opened untill that step.

**Comment by benjycui** [comment]
Actually..you can create PR when `3.0.0` is in progress.. Otherwise, you need to rebase it again and again.

**Comment by afc163** [comment]
I think `Transfer` default Chinese text could be removed or moved to demo, which are useless like `defaultTitles` and `unit`.

**Pull request closed without merging**
