### PR TITLE
perf: update ease-in-out

### PR DESCRIPTION
**Pull request by tangjinzhou**
menu测试 动画更流畅
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
不能改变量，影响的组件不止 menu。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/27565#issuecomment-723808483

**Comment by tangjinzhou** [comment]
贝塞尔曲线应该只是对动画缓动效果有影响
其他组件经过测试，视觉体验上基本无差别

**Comment by afc163** [comment]
没看出有什么不同。

**Comment by afc163** [comment]
暂时不动了。

**Pull request closed without merging**
