### PR TITLE
feat: add Franch(Canada):fr_CA locale

### PR DESCRIPTION
**Pull request by liufenghua808**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     add fr_CA locale     |
| 🇨🇳 Chinese |      添加法语（加拿大）     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
需要先给rc-pagination和rc-picker发PR

**Comment by liufenghua808** [comment]
> 需要先给rc-pagination和rc-picker发PR

> 本地install的rc-picker下是不包含fr-CA,您的意思是还需要给rc-picker工程发Pull Requset吗？

**Comment by yoyo837** [comment]
对的，先给它们俩发PR并发布patch后这个PR更新到patch。

**Comment by yoyo837** [comment]
`rc-picker: ~2.5.10`
`rc-pagination: ~3.1.6`

**Comment by yoyo837** [comment]
你的提交似乎混入了其他东西。

**Comment by liufenghua808** [comment]
> 你的提交似乎混入了其他东西。

> 加上最新提交，我改的是9个文件，提交之前pull了一下，按说应该没什么影响呢？

**Comment by yoyo837** [comment]
错误的commit不易于追溯，需要重新rebase然后push -f

**Comment by liufenghua808** [comment]
> 错误的commit不利于追溯，需要重新rebase然后push -f
> 意思我重新再拉取代码，然后只commit我修改的9个文件，直接push么?

**Comment by yoyo837** [comment]
在当前分支rebase upstream的master后 强推就可以了

**Comment by yoyo837** [comment]
分支已经删除，关闭

**Pull request closed without merging**
