### PR TITLE
use ant design icons 4.0

### PR DESCRIPTION
**Pull request by vagusX**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/16911
https://github.com/ant-design/ant-design/pull/18033
https://github.com/ant-design/ant-design/issues/12011

### 💡 Background and solution

use @ant-design/icons v4.0 to replace the icon solution in antd v3

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/alert/demo/custom-icon.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/alert/demo/custom-icon.md)
[View rendered components/auto-complete/demo/certain-category.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/auto-complete/demo/certain-category.md)
[View rendered components/auto-complete/demo/uncertain-category.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/auto-complete/demo/uncertain-category.md)
[View rendered components/avatar/demo/badge.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/avatar/demo/badge.md)
[View rendered components/avatar/demo/basic.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/avatar/demo/basic.md)
[View rendered components/avatar/demo/type.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/avatar/demo/type.md)
[View rendered components/avatar/index.en-US.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/avatar/index.en-US.md)
[View rendered components/avatar/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/avatar/index.zh-CN.md)
[View rendered components/badge/demo/basic.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/badge/demo/basic.md)
[View rendered components/badge/demo/change.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/badge/demo/change.md)
[View rendered components/badge/demo/dot.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/badge/demo/dot.md)
[View rendered components/breadcrumb/demo/withIcon.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/breadcrumb/demo/withIcon.md)
[View rendered components/button/demo/button-group.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/button/demo/button-group.md)
[View rendered components/button/demo/multiple.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/button/demo/multiple.md)
[View rendered components/button/demo/size.md](https://github.com/ant-design/ant-design/blob/feat/use-ant-design-icons-4.0/components/button/demo/size.md)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#12011: Svg icons make bunlde size too large](https://issuehunt.io/repos/34526884/issues/12011)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by vagusX** [comment]
## bundle result anaylsis

demo at https://github.com/vagusX/antd4-bundle-analysis
### Before
before

### After
after

### Icon part
icons-svg

**Comment by vagusX** [comment]
released in https://github.com/ant-design/ant-design/releases/tag/4.0.0-alpha.2

**Comment by sunnylqm** [comment]
A little suggestion:
Can we add 'Icon' prefix or suffix to these exports? It can be quite confusing since these are very common names. For example:
```
import { Left, Right, Home } from '@ant-design/icons';
```
Maybe this seems more clear
```
import { LeftIcon, RightIcon, HomeIcon } from '@ant-design/icons';
```

**Comment by ivalsaraj** [comment]
I am currently using antd 3, how can I use this icon fix in current project?

**Comment by Xezzon** [comment]
@vagusX 你好，我已经升级到了ant design 4.0.0-beta.0，但是在webpack打包时@ant-design/icons-svg依然被全量引入了。

已配置过babel-plugin-import。是不是我还缺少了什么配置？

**Comment by vagusX** [comment]
> @vagusX 你好，我已经升级到了ant design 4.0.0-beta.0，但是在webpack打包时@ant-design/icons-svg依然被全量引入了。
> 
> 已配置过babel-plugin-import。是不是我还缺少了什么配置？

这个是我之前用来做 [bundle analysis](https://github.com/vagusX/antd4-bundle-analysis) 的 demo，你可以尝试升级到最新的 antd alpha 版本再试试看

**Pull request merged**
