### PR TITLE
refactor: Watermark add overflow hidden style to avoid visible show

### PR DESCRIPTION
**Pull request by zombieJ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #48660

### 💡 Background and solution

When Watermark set `height: 0`, it will still show the content in it. Add `overflow: hidden` instead.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Watermark add `overflow: hidden` style to prevent set `height: 0` to hide the watermark case.       |
| 🇨🇳 Chinese |    Watermark 添加 `overflow: hidden` 样式以防止通过设置 `height: 0` 样式达到隐藏水印的效果。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
不是请假么

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
这个 ci 问题要怎么解决？

**Comment by zombieJ** [comment]
> 不是请假么

送孩子上幼儿园，然后就搞点~

**Comment by yoyo837** [comment]
老板，记得绩效打S+啊；

**Comment by zombieJ** [comment]
> 这个 ci 问题要怎么解决？现在 feature 永远是挂的。

发个 minor 同步一下就好了

**Pull request merged**
