### PR TITLE
feat: 🔢 improve default pagination switch experience

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- https://github.com/react-component/pagination/pull/258
- https://github.com/react-component/pagination/pull/260

close https://github.com/ant-design/ant-design/issues/18201

### 💡 Background and solution

- [x] 当 `total` 大于 `50` 时，默认显示切换页数选择器。优化大数据下的默认分页体验。
- [x] 页数选择器的默认选项从 `10,20,30,40` 修改为 `10,20,50,100`。
   image
- [x] 优化 10 页以内的分页器宽度，使其更统一，解决 #18201 的问题。

| 调整前 | 调整后 ✅ |
| --- | --- |
| 截屏2020-03-29下午5 14 20 | 截屏2020-03-29下午5 13 37 |

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  - Pagination will show size changer when `total>50`.<br />- Unify Pagination items  to fixed length.<br />- change default size options to `10, 20, 50, 100`.  |
| 🇨🇳 Chinese | - Pagination 当 `total>50` 时默认显示切换页数选择器。<br />- 统一 Pagination 十页以内的页码个数使其宽度更统一。<br />- Pagination 调整默认页数选项为 `10, 20, 50, 100`。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by zombieJ — APPROVED** [review]

**Comment by afc163** [comment]
用例挂了

**Comment by zombieJ** [comment]
\rebase

**Comment by afc163** [comment]
再调整一些细节ing

**Comment by zombieJ** [comment]
👌 那我再等等

**Comment by afc163** [comment]
可以并行起来，估计我六点前能搞完。

**Comment by afc163** [comment]
done

**Pull request merged**
