### PR TITLE
fix menu collapsed props order

### PR DESCRIPTION
**Pull request by kaysonwu**
For #32240

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    The `inlineCollapsed` props is used preferentially to control the `collapsed` state of the `Menu` under the `Layout.Sider`  component         |
| 🇨🇳 Chinese |   优先使用 `inlineCollapsed` 道具是了能够在 `Layout.Sider` 组件下控制菜单的 `collapsed` 状态  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by kaysonwu** [comment]
The `inlineCollapsed ` props are preferentially used so that they can be controlled under the `Layout.Sider` component

**Comment by afc163** [comment]
Could you add a test case?

**Comment by kaysonwu** [comment]
@afc163 I have added test case, please review.

**Comment by zombieJ** [comment]
It's by design:

截屏2021-09-23 上午10 32 49

**Comment by kaysonwu** [comment]
@zombieJ  这个设计在一定程度上限制了菜单组件的可控性。使用 `Layout.Sider` 包裹 `Menu` 时，默认行为高于自定义行为，这不应该被修正吗？

**Comment by afc163** [comment]
我感觉有问题，应该先尊重 Menu 上的属性。

**Comment by kaysonwu** [comment]
我在实现以下侧边栏导航样式式，发现的这个问题：<br/><br/> image

当菜单需要拆分时，主菜单应该被折叠，子菜单跟随侧边栏。

**Review by blockchainGuru1018 — APPROVED** [review]

**Comment by afc163** [comment]
冲突了

**Comment by li-jia-nan** [comment]
Hey! Conflicting files, and it seems this is now really outdated. If this is something that still makes sense to the latest master version of antd, please send a new PR with this change :)

**Pull request closed without merging**
