### PR TITLE
refactor: 📦 some styles to reduce css bundle size

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

重构部分样式以降低 css 文件体积。

> https://codesandbox.io/s/patient-rain-x4lrh?file=/index.js 重构前 Input.Search 的样式，留档备查。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |    -       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/input/demo/search-input.md](https://github.com/ant-design/ant-design/blob/reduce-css-size/components/input/demo/search-input.md)

### CODE REVIEW

**Comment by afc163** [comment]
省出来 -120 B，真是不容易。

**Comment by xrkffgg** [comment]
- LTR 下，hover focus 少了右边框

image

- RTL 下，右侧少了，左侧多了个 border

image

**Comment by hengkx** [comment]
image
还是y有问题

**Comment by afc163** [comment]
RTL 问题均已修复。

**Comment by hengkx** [comment]
image
rtl对了 正常的 又挂了

**Review by xrkffgg — APPROVED** [review]

**Pull request merged**
