### PR TITLE
docs: clear the description about the key props of Select.Option

### PR DESCRIPTION
**Pull request by itellboy**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/select/index.en-US.md](https://github.com/itellboy/ant-design/blob/dev/components/select/index.en-US.md)
[View rendered components/select/index.zh-CN.md](https://github.com/itellboy/ant-design/blob/dev/components/select/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
Any reason to remove this?

**Comment by itellboy** [comment]
> Any reason to remove this?

@afc163 The key prop is nothing about the value prop, and the value is required that can't be omitted.

**Comment by afc163** [comment]
`value` can be omited if `key` is assigned in loop items situation: https://codesandbox.io/s/nice-shape-2v9ec

**Comment by itellboy** [comment]
@afc163 It's not work out in TypeScript template created by CRA. Sorry because network situation,  I can't give a demo on codesandbox.io.

**Comment by afc163** [comment]
You can provide a GitHub repo.

**Comment by itellboy** [comment]
@afc163 https://codesandbox.io/s/eloquent-colden-bilxn

**Comment by afc163** [comment]
@zombieJ

**Comment by zombieJ** [comment]
It's ok to remove `key` in doc directly instead of leave `key` desc empty.

**Comment by itellboy** [comment]
@zombieJ ok, I will push a new PR.

**Pull request closed without merging**
