### PR TITLE
type: remove type ghost from ButtonTypes

### LINKED ISSUE #43661: `<Button type="ghost" disabled>` has `cursor: pointer;` style
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/disabled-antd-5-7-1-forked-v7xmgt?file=/demo.tsx)

### Steps to reproduce

Set the type to "ghost" and set disabled to true for the Button.

### What is expected?

expected disabled Button to have "cursor: not-allowed;"

### What is actually happening?

disabled Button with the type "ghost" has "cursor: pointer;" style.

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | ^18.0.0 |
| System | Windows 10 |
| Browser | Chrome 115 |

---
The button type in the documentation mismatches with the actual button type.

https://github.com/ant-design/ant-design/blame/5.7.1/components/button/index.en-US.md#L70

https://github.com/ant-design/ant-design/blame/5.7.1/components/button/buttonHelpers.tsx#L67

the same issue has been reported.

https://github.com/ant-design/ant-design/issues/43555

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/43661
ref https://github.com/ant-design/ant-design/issues/43661

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Remove Button type `ghost` from TS definition.   |
| 🇨🇳 Chinese |  移除 Button 无用的 `type="ghost"` 属性定义。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 2ebce09</samp>

Remove `ghost` prop and type from `Button` component and related files. This is to align with the updated design system that does not support `ghost` buttons.

### <samp>🤖 Generated by Copilot at 2ebce09</samp>

* Remove `ghost` prop from `Button` component and its documentation ([link](https://github.com/ant-design/ant-design/pull/43675/files?diff=unified&w=0#diff-47a152d13483d9d39b5d0114d506ba003d0572b4470a94a03f98ef93ae52619cL67-R67),                             F29L

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Comment by omairnabiel** [comment]
Isn't this a breaking change? 🤔

**Comment by RusseII** [comment]
What's the suggested alternative to the ghost button now? Is there somewhere I can read more about that?

**Comment by aaarichter** [comment]
I was wondering about this too - AFAIK there wasn't a deprecation warning. Removing the type is sort of a breaking change @afc163

**Comment by aaarichter** [comment]
nevermind - @RusseII  https://ant.design/components/button#components-button-demo-ghost so it's now a property instead of a type

**Pull request merged**
