### PR TITLE
fix: When affix scrolls horizontally, the left position is different f…

### PR DESCRIPTION
**Pull request by madocto**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
[#29108](https://github.com/ant-design/ant-design/issues/29108)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix that the left position of Affix different from the original dom when scrolling horizontally   |
| 🇨🇳 Chinese |    修复Affix在水平可滚动的容器内fixed时left位置原dom位置不一致     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Could you add test case for it?

**Comment by zyxbb** [comment]
> 您可以为其添加测试用例吗？

Ok i try

**Comment by zyxbb** [comment]
> Could you add test case for it?

Ok i try

**Comment by zyxbb** [comment]
@afc163 https://codesandbox.io/s/antd-affix-left-position-tqsmg
您好，这个demo中，先向下滚动，`affix`为`fixed`时，再水平滚动
1.要保持滚动时和原dom的`left`位置相同，此时应该取消`affix`的`fixed`吗？这样会闪烁后回到原来位置
2.如果不取消的`fixed`，应该要怎么做呢？🙇

**Comment by afc163** [comment]
close by #30775

**Pull request closed without merging**
