### PR TITLE
fix: Increase dependency version: scroll-into-view-if-needed@^2.2.25

### PR DESCRIPTION
**Pull request by ichuyko**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/stipsan/compute-scroll-into-view/issues/676

### 💡 Background and solution

One dependency has IE-specific issue with iFrame access.
The issue was fixed. Please use the latest version of the library.

### 📝 Changelog

No potential break changes or other risks.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      +     |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ichuyko** [comment]
The issue related to the change: https://github.com/ant-design/ant-design/issues/24408

**Comment by afc163** [comment]
不用升，能安装到 2.2.25

**Comment by ichuyko** [comment]
不用升，能安装到 2.2.25

In case a new installation or first usage yes, you are right, the latest version will be installed. But in case you have cached or already installed the old version ... your build could use the old version. Also, you can commit -lock file...

Probably it's better to put the correct version to dependency.

In any case, you guys will make the best decision...

**Comment by afc163** [comment]
There is no harm to upgrade it, of cause.

**Pull request merged**
