### PR TITLE
fix: formItem shaking #32060

### PR DESCRIPTION
**Pull request by tangjinzhou**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by tangjinzhou** [comment]
主要是
```less
margin-top: -@form-item-margin-bottom;
transform: translateY(@form-item-margin-bottom);
```
改完之后组件cssmotion，感觉有点多余了，算是性能有提升吧

**Comment by zombieJ** [comment]
FormItem 设置 `style={{ marginBottom: 0 }}` 会被切掉:

截屏2022-02-28 上午10 25 21

**Comment by tangjinzhou** [comment]
> FormItem 设置 `style={{ marginBottom: 0 }}` 会被切掉:
> 
> 截屏2022-02-28 上午10 25 21

咦，我还以为这是预期行为呢  不过感觉可以判断下 marginBottom，有的话再处理 marginTop、translate

**Comment by tangjinzhou** [comment]
尽可能减少了 breaking 😓

**Comment by yoyo837** [comment]
> 尽可能减少了 breaking 😓

看表情明显不乐意，😂

**Comment by zombieJ** [comment]
我的意思是 FormItem 的 margin: 0 的时候应该生效：

**Comment by tangjinzhou** [comment]
把 margin 动画取消看起来是个更好的选择，只留 errorList 的动画

**Comment by hexwit** [comment]
Could you say, is there any progress on this issue? or eta for completion?

**Comment by KKarai** [comment]
is there any progress on this issue?

**Comment by chengwb53** [comment]
新版问题还是存在哦

**Comment by li-jia-nan** [comment]
Hey! Conflicting files, and it seems this is now really outdated. If this is something that still makes sense to the latest master version of antd, please send a new PR with this change :)

**Pull request closed without merging**
