### PR TITLE
feat: ColorPicker presets should support key

### PR DESCRIPTION
**Pull request by li-jia-nan**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | feat: ColorPicker presets should support key |
| 🇨🇳 Chinese | presets 支持传入 key，支持用户指定组件的唯一值 |

### CODE REVIEW

**Comment by afc163** [comment]
解决啥问题

**Comment by li-jia-nan** [comment]
控制台报错：
Warning: Encountered two children with the same key, `panel-[object Object]`. 
Keys should be unique so that components maintain their identity across updates.

**Review by afc163 — APPROVED** [review]

**Comment by li-jia-nan** [comment]
@afc163 大佬合快了，文档忘记补充

**Comment by afc163** [comment]
再来

**Comment by li-jia-nan** [comment]
- #51806

**Comment by li-jia-nan** [comment]
- #51807

**Comment by li-jia-nan** [comment]
先在 master 分支临时解决：
- #51808

**Pull request merged**
