### PR TITLE
Fix Scrollbar on Modal Confirm

### LINKED ISSUE #19072: Scrollbar is not disabled when opening a Modal
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-modal-reproduction-ddsp8)

### Steps to reproduce
Open the modal

### What is expected?
The scrollbar must be disabled.

### What is actually happening?
The scrollbar is not disabled and we can scroll.

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.8.6 |
| System | Linux 18.04 |
| Browser | Chrome 77.0.3865.90 |

---
I have searched in many issues, there is some tricks.
For example, if you let the settings by default, the scrollbar is hidden, and the body width is resized to simulate a false scrollbar. The problem is that the background image is shifted to the right by 15px (the original scrollbar size) and the visual rendering is not what I expect.
The scrollbars are always displayed in my application.

Sorry for english.

### PR DESCRIPTION
**Pull request by emersonlaurentino**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

closes #19072

### 💡 Background and solution

when opening a modal with confirm method, it makes the scrollbar active

### 📝 Changelog

removing getContainer fixed

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by shaodahong** [comment]
Thanks and Please check CI

**Review by afc163 — CHANGES_REQUESTED** [review]
mix other commits

**Comment by emersonlaurentino** [comment]
@afc163 do you think I better close this PR and open a new one? the modification is very simple!

**Comment by afc163** [comment]
You can create new PR for it, this PR messed up now.

**Pull request closed without merging**
