### PR TITLE
fix: fix vertical handle position

### PR DESCRIPTION
**Pull request by wzhudev**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#22128

同时还解决了 slider handle 和 mark 未对齐的问题

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix handles' position when slider is vertical |
| 🇨🇳 Chinese | 修复垂直情况下 slider handle 的位置 | 

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by wendellhu95** [comment]
Before:

截屏2020-03-1200 23 23

After:

截屏2020-03-1200 52 16

**Comment by afc163** [comment]
1. `<Slider vertical reverse />` still has problem: https://codesandbox.io/s/antd-reproduction-template-ht3em
2. We can change vertical Slider Tooltip placement to `right`.

**Comment by afc163** [comment]
similar issue: https://github.com/ant-design/ant-design/issues/19682

**Comment by afc163** [comment]
rebase master

**Comment by yoyo837** [comment]
3.x 的也顺手改一下？

**Comment by wendellhu95** [comment]
> 3.x 的也顺手改一下？

没问题

**Pull request merged**
