### PR TITLE
fix: Select empty style & default width

### LINKED ISSUE #19889: [4.0] Select loading style not correct
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://next.ant.design/components/select-cn/#components-select-demo-select-users

### What is expected?
style correct

### What is actually happening?
style not correct

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.9 |
| React | 16.3 |
| System | windows 10 |
| Browser | chrome 75.0.3770.100  |

### LINKED ISSUE #20146: [4.0] Select component too long
图片

https://next.ant.design/components/form-cn/

要检查一下有没有兼容性问题。

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #20146
fix #19889

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Select provides default width and not show dropdown when `notFoundContent` is `null`.     |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by shaodahong** [comment]
Missing cursor

Kapture 2019-12-13 at 14 35 52

**Comment by zombieJ** [comment]
@shaodahong , pls help to check again.

**Comment by shaodahong** [comment]
Hover color?

## 3.0
Kapture 2019-12-13 at 16 43 12

## 4.0
Kapture 2019-12-13 at 16 44 21

**Comment by shaodahong** [comment]
Arrow top height not correct

image

**Comment by shaodahong** [comment]
Empty Option when hidden
（隐藏的时候出现了空 Option）

Kapture 2019-12-13 at 17 01 21

**Comment by shaodahong** [comment]
Group indent is missing

image

**Comment by shaodahong** [comment]
Missing input hover bordered

**Comment by zombieJ** [comment]
> Empty Option when hidden
> （隐藏的时候出现了空 Option）
> 
> Kapture 2019-12-13 at 17 01 21

这个开个新的 issue，样式的先合了。

**Comment by shaodahong** [comment]
嗯，我提的有些和 #20229 重复了，可以一起过一下

**Comment by zombieJ** [comment]
嗯，分几个 PR 逐步更新。免得太大合不掉了。

**Review by shaodahong — APPROVED** [review]
LGTM

**Pull request merged**
