### PR TITLE
fix: context issues for Space.Compact

### PR DESCRIPTION
**Pull request by foryuki**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/38655
https://github.com/ant-design/ant-design/issues/38812

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix the style problem when the Space.Compact component wraps Modal, Dropdown, Drawer and other components.      |
| 🇨🇳 Chinese |   修复 Space.Compact 组件嵌套 Modal，Dropdown，Drawer 等组件时的样式问题。        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/issues/38590
这个也看一下？

**Comment by foryuki** [comment]
> #38590 这个也看一下？

好的，我看下针对 「期望Space.Compact 包裹单个子组件时子组件的 border 样式正常显示」这种场景~

**Comment by MadCcc** [comment]
用个测试用例测一下？demo 测试里东西有点多

**Comment by Veveue** [comment]
image
@foryuki

**Comment by chillyistkult** [comment]
Bildschirmfoto 2023-01-03 um 16 36 17

Breaks tabs when `Space` is used there.

**Pull request merged**
