### PR TITLE
Adds Danish locale

### PR DESCRIPTION
**Pull request by michaelkrog**
This PR adds Danish locale to the project.

* [X] Make sure that you propose PR to right branch: bugfix for `master`, feature for branch `feature`.
* [X] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [X] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [X] Rebase before creating a PR to keep commit history clear.
* [X] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [X] Update API docs for the component.
  * [X] Update/Add demo to demonstrate new feature.
  * [X] Update TypeScript definition for the component.
  * [X] Add unit tests for the feature.

### CODE REVIEW

**Comment by afc163** [comment]
Please rebase and run `npm test -- -u` to update locale snapshots.

**Comment by michaelkrog** [comment]
Finally..  

I had some issues doing the rebase, but I hope it turned out ok.. :)

**Comment by afc163** [comment]
It is not... other commits mixed in this PR now.

**Comment by michaelkrog** [comment]
Will recreate...

**Comment by michaelkrog** [comment]
Create new PR here: https://github.com/ant-design/ant-design/pull/12730

**Pull request closed without merging**
