### PR TITLE
feat(notification): support role props

### LINKED ISSUE #39568: Notification component's role="alert" creates accessibility issue for screen reader users
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/e9evzr)

### Steps to reproduce

1. Open example.
2. Click button to open notification box.

### What is actually happening?

Since `role="alert"` is used, the notification interrupt whatever the user is doing. This also stops a screen reader from finishing whatever it was saying before the alert interrupted it (and will not pick up where it left off) which can make a user feel stranded. Toast-style notifications should be used for non-critical, non-interactive content so it's inappropriate to use `role="alert"` which implicitly has an `aria-live` value of `assertive`.

### What is expected?

Instead, `role="status"` is more appropriate as it allows for current screen reader announcements to be read before announcing the non-critical notification content. This requires the notification elements to be with an element with `role="region"` and `aria-live="polite"`.

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | React |
| System | Windows 10 |
| Browser | All |

---
More information:
- https://www.scottohara.me/blog/2019/07/08/a-toast-to-a11y-toasts.html#inclusive-ux-of-a-toast
- https://adrianroselli.com/2020/01/defining-toast-messages.html#NeededFeatures

### PR DESCRIPTION
**Pull request by guan404ming**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

1. close #39568 

### 💡 Background and solution

- ref: #39611

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Adds role props to Notification    |
| 🇨🇳 Chinese |     添加 role props 到 Notification     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 22d6d9d</samp>

Added a `role` prop to the notification component and its API to improve accessibility. Added a test case and sorted imports in some files for code quality. Updated the documentation in both English and Chinese.

### <samp>🤖 Generated by Copilot at 22d6d9d</samp>

*  Add `role` prop to notification component to improve accessibility ([link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-c80bd08ac7a1f6a8ae2046fe84cc562807b2d11b1a63316286546b888a86ed08R32), [link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-8b66e26e1dc3ab97c7faf1e4f2d015c5b42d580fce0dd4c3043b7253bcdb83ccR40), [link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-8b66e26e1dc3ab97c7faf1e4f2d015c5b42d580fce0dd4c3043b7253bcdb83ccR57), [link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-8b66e26e1dc3ab97c7faf1e4f2d015c5b42d580fce0dd4c3043b7253bcdb83ccL71-R73), [link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-fa8b6f08e906ed18759c056ccb358fb0b780b4ffbb0f00ed368b45c3b8efe5dfL108-R108), [link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-fa8b6f08e906ed18759c056ccb358fb0b780b4ffbb0f00ed368b45c3b8efe5dfR121))
* Document `role` prop in the API section of the markdown files for notification component ([link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-9b1700ccbd4da0f60742ae024592c27e0118d7307f5a9ed69a91c560c374749fR59), [link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-9954e364a4a4121f77d3f9f87225ef361d39c004720443dd896bb31cfe3c6d22R60))
* Add test case to check that `role` prop can be passed to the notification open function and rendered correctly ([link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-ed8976c7e832d9befa4199cc192b025c91cb3ff525a3649834d7545fdd89f690R304-R315))
* Sort imports alphabetically in `components/notification/__tests__/index.test.tsx`, `components/notification/PurePanel.tsx`, and `components/notification/useNotification.tsx` to follow the code style guide ([link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-ed8976c7e832d9befa4199cc192b025c91cb3ff525a3649834d7545fdd89f690L1-R5), [link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-8b66e26e1dc3ab97c7faf1e4f2d015c5b42d580fce0dd4c3043b7253bcdb83ccL1-R13), [link](https://github.com/ant-design/ant-design/pull/42482/files?diff=unified&w=0#diff-fa8b6f08e906ed18759c056ccb358fb0b780b4ffbb0f00ed368b45c3b8efe5dfL1-R15))

### CODE REVIEW

**Comment by li-jia-nan** [comment]
新功能需要提交到 feature 分支哦

**Comment by guan404ming** [comment]
> 新功能需要提交到 feature 分支哦

好的！我修改一下

**Comment by li-jia-nan** [comment]
你把 master 分支的 diff 带过来了，master 的 commit 不应该出现在这里

**Comment by guan404ming** [comment]
> 你把 master 分支的 diff 带过来了，master 的 commit 不应该出现在这里

抱歉，好像不太會操作，還是我再重新開個 branch 來 PR呢？還是有其他方法

**Pull request closed without merging**
