### PR TITLE
refactor: 🔨 simplify Popconfirm and Popover dom structure

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

simplify Popconfirm and Popover dom structure

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Simplify Popconfirm and Popover dom structure |
| 🇨🇳 Chinese | 简化 Popconfirm 和 Popover 的 dom 结构。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Approve needed.

**Comment by shaodahong** [comment]
包的体积怎么变大了

**Comment by afc163** [comment]
feature 分支，一点一点蹭超了。我看看哪里能省一点下来。

**Comment by afc163** [comment]
省下来了：https://github.com/ant-design/ant-design/pull/22055

**Review by shaodahong — APPROVED** [review]

**Pull request merged**
