### PR TITLE
add fixed-header demo for Layout

### PR DESCRIPTION
**Pull request by ddcat1115**
relevant issue: #4973

### CODE REVIEW

**Comment by benjycui** [comment]
所以在 travis 恢复之前都没办法合 PR 了么。。

**Comment by afc163** [comment]
Rebase master

**Comment by benjycui** [comment]
And this: http://stackoverflow.com/questions/42345641/antd-fixed-header-in-layout

**Comment by yesmeck** [comment]
Rebase :)

**Pull request merged**
