### PR TITLE
fix: disabled Input addon should not have status style

### PR DESCRIPTION
**Pull request by carla-cn**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/40664

### 📝 Changelog
before：
image
after：
image
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     When Input is disabled, the red style of addonAfter and addonBefore is deleted      |
| 🇨🇳 Chinese |    当 Input 为禁用状态时，删掉了以前 addonAfter 和 addonBefore 的飘红样式       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
snap 需要更新一下

**Comment by carla-cn** [comment]
> snap 需要更新一下

已经更新好啦

**Comment by li-jia-nan** [comment]
禁用状态时，字体颜色是不是也要和中间的保持一致？

**Comment by carla-cn** [comment]
> 禁用状态时，字体颜色是不是也要和中间的保持一致？

谢谢大佬，这样的话小弟就再改一改

**Comment by carla-cn** [comment]
> > 禁用状态时，字体颜色是不是也要和中间的保持一致？
> 
> 谢谢大佬，这样的话小弟就再改一改

image
这个是修改后的图，代码推好啦

**Comment by li-jia-nan** [comment]
image

disabled=true 并且 status="warning" 的时候还有点问题

**Comment by carla-cn** [comment]
> image
> 
> disabled=true 并且 status="warning" 的时候还有点问题

谢谢，已经又改了一波，辛苦啦

**Comment by li-jia-nan** [comment]
image

disabled=false 并且 status="warning" 的时候好像还有点问题，一起修一下？

**Comment by carla-cn** [comment]
> image
> 
> disabled=false 并且 status="warning" 的时候好像还有点问题，一起修一下？
image
小弟最终改成这样了哈

**Comment by li-jia-nan** [comment]
嗯，这样是没问题的，之前的 token 用错了，`warning` 的颜色应该用 `token.colorWarning` 才对

**Comment by li-jia-nan** [comment]
snap 还需要更新一下

**Comment by carla-cn** [comment]
> snap 还需要更新一下

谢谢大佬，小弟刚刚跟新了一波

**Review by li-jia-nan — APPROVED** [review]

**Pull request merged**
