### PR TITLE
docs: update Slider Attributes

### PR DESCRIPTION
**Pull request by 1587315093**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
#43286

### 💡 Background and solution

同步了英文文档属性至中文文档

更新了 `trackStyle` `railStyle` `handleStyle` 的中英文档类型  ` CSSProperties \| CSSProperties[] `

image

删除了 英文文档  的 `(the background)` ，因为railStyle 不只是能改变 `background`

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x ] Doc is updated/provided or not needed
- [x ] Demo is updated/provided or not needed
- [x ] TypeScript definition is updated/provided or not needed
- [x ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 6adcf1f</samp>

Added `autoFocus` prop and updated style props for slider component. These changes enhance the accessibility and customization of the slider component in both Chinese and English documentation.

### <samp>🤖 Generated by Copilot at 6adcf1f</samp>

*  Update `railStyle` and `handleStyle` props to accept arrays of CSSProperties for slider handles and rails ([link](https://github.com/ant-design/ant-design/pull/43297/files?diff=unified&w=0#diff-1923e5c169ac9e00e9733ef60f83f56bdbd01690c370fa8071a0fd2d0e4581c3L53-R54), [link](https://github.com/ant-design/ant-design/pull/43297/files?diff=unified&w=0#diff-6e1f3b862cb377975f6bca16d005791420d2467cb8d47d9bcce69f3bcbf91cb7R54-R56))
*  Add `autoFocus` prop to control slider focus on mount ([link](https://github.com/ant-design/ant-design/pull/43297/files?diff=unified&w=0#diff-6e1f3b862cb377975f6bca16d005791420d2467cb8d47d9bcce69f3bcbf91cb7R36))
*  Update documentation files `index.en-US.md` and `index.zh-CN.md` to reflect the new props and types ([link](https://github.com/ant-design/ant-design/pull/43297/files?diff=unified&w=0#diff-1923e5c169ac9e00e9733ef60f83f56bdbd01690c370fa8071a0fd2d0e4581c3L53-R54), [link](https://github.com/ant-design/ant-design/pull/43297/files?diff=unified&w=0#diff-6e1f3b862cb377975f6bca16d005791420d2467cb8d47d9bcce69f3bcbf91cb7R36), [link](https://github.com/ant-design/ant-design/pull/43297/files?diff=unified&w=0#diff-6e1f3b862cb377975f6bca16d005791420d2467cb8d47d9bcce69f3bcbf91cb7R54-R56))

### CODE REVIEW

**Comment by 1587315093** [comment]
@MadCcc  https://github.com/ant-design/ant-design/issues/43286

**Comment by afc163** [comment]
这些后面要用 styles 属性统一透出，现在就不加文档了吧。https://github.com/ant-design/ant-design/discussions/40221

**Comment by 1587315093** [comment]
> 这些后面要用 styles 属性统一透出，现在就不加文档了吧。#40221

好嘞~

**Comment by MadCcc** [comment]
v4 是不是可以加一下

**Comment by 1587315093** [comment]
> v4 是不是可以加一下

@afc163 
我看这个RFC 都半年了 https://github.com/ant-design/ant-design/discussions/40221

image

我觉得是既然 统一合并需要工作量时间，为啥不先改下文档呢

**Pull request closed without merging**
