### PR TITLE
style: redesign Table header action

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

图片

before | ✅ after
--- | ---
图片 | 图片

before | ✅ after
--- | ---
图片 | 图片

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Redesign Table filter and sorter buttons to clarify current column.  |
| 🇨🇳 Chinese | 重新设计 Table 筛选和排序按钮的位置，使其归属列更明确。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
直接发到 master 好了。

**Comment by afc163** [comment]
https://preview-30651-ant-design.surge.sh/components/table/#components-table-demo-virtual-list 这个例子挂了，还得再看看。

**Comment by nuintun** [comment]
@afc163 @zombieJ 居中居右对齐现在很丑

image

**Comment by 303394539** [comment]
@afc163 这个before在没有排序等元素的时候还显示出来很显眼，与title的位置对比起来比较别扭

**Comment by xyuanbuilds** [comment]
> @afc163 @zombieJ 居中居右对齐现在很丑
> 
> image

这，我强迫症犯了

**Comment by U1in** [comment]
希望平时能够隐藏或者能够有api隐藏

**Pull request merged**
