### PR TITLE
fix: bad position of collapsible submenu in sider when collapsed

### LINKED ISSUE #15321: Bad position of collapsible submenu in sider when collapsed
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout/#components-layout-demo-side](https://ant.design/components/layout/#components-layout-demo-side)

### Steps to reproduce
1. Press on one of the collapsible menu items (User/Team) to view the submenu items.
2. After the submenu has opened collapse the sider by pressing the arrow button on the buttom of the sider.
3. The submenu items will hang to the right of the collapsed sider with a big gap.
4. If you hover the menu again the submenu will pop into its right position.

### What is expected?
The submenu items should stay right beside their menu item parent when sider is collapsed.

### What is actually happening?
The submenu items will hang to the right of the collapsed sider with a big gap.

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | Windows 10 |
| Browser | Chrome / Firefox |

---
This bug didn't occur in version 3.14.

### PR DESCRIPTION
**Pull request by orzyyyy**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

1. Describe the source of requirement, like related issue link.

    To close #15321. 

2. Describe the problem and the scenario.

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

    When migrating to new lifecycle methods, I forget to record the status of context, and caused this bug. Just make it up, and everything goes smoothly.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description

    Fix error rendering of SubMenu when Menu collapsed

2. Chinese description (optional)

    修复 Menu 收缩后，SubMenu 异常渲染的问题

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zy410419243** [comment]
为啥这 ci 不会跑的...

**Comment by ztplz** [comment]
我还以为这是个新的功能，在sider关闭的时候如果有menu打开就继续保持打开。

**Comment by afc163** [comment]
> 我还以为这是个新的功能，在sider关闭的时候如果有menu打开就继续保持打开。

受控的时候应该打开，非受控关闭。

另外现在不仅打开，位置还留在原地。

**Comment by afc163** [comment]
这个有办法加用例么，这个组件细节很多，确实经常搞挂。

**Comment by zy410419243** [comment]
加是加了，应该有点用

~~@afc163 怎么感觉你人设变了，以前应该是更加性冷淡地说句，“来个测试用例。”
现在总觉得哪里不对...~~

**Comment by afc163** [comment]
被彩蛋搞怕了~

**Comment by ouzhou** [comment]
现在似乎会闪烁一下 
https://ant-design.gitee.io/components/layout-cn/#components-layout-demo-side
官方这个例子，你在打开一个子目录的状态下，点击收缩，会突然闪烁一下

**Comment by ouzhou** [comment]
而且现在在slider组件包裹状态下设置menu的inlineCollapsed是无效的

**Comment by UnicornXU** [comment]
关于收缩闪烁还是有问题,更新后的版本3.15.1并没有解决,反而我降到3.15.0没有收缩闪现的状况

**Comment by UnicornXU** [comment]
@ @afc163

**Comment by ouzhou** [comment]
3.15.1并没有解决

**Pull request merged**
