### PR TITLE
fix: add peerDependencies back

### PR DESCRIPTION
**Pull request by chentsulin**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

The react peerDependencies has been unexpectedly removed by this PR:
https://github.com/ant-design/ant-design/pull/50690/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

It breaks pnpm.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Added react peerDependencies |
| 🇨🇳 Chinese |           |

### CODE REVIEW

**Comment by yoyo837** [comment]
Please continue to move it to before `dependencies`.

**Comment by afc163** [comment]
Why do we need `peerDependencies` for react and react-dom in pnpm? Could you describe more about the problem and provide a reproduce?

**Comment by yoyo837** [comment]
> peerDependencies

`peerDependencies` also works fine with npm, may I know why it is removed?

**Comment by chentsulin** [comment]
@afc163 pnpm has a mechanism to resolve dependencies:
- https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory
- https://pnpm.io/how-peers-are-resolved

Unexpectedly importing the `react` package which is not listed in the `dependencies` nor `peerDependencies` will cause the `Cannot find module 'react'` error:

```
 ⨯ Error: Cannot find module 'react'
Require stack:
- /workspace/node_modules/.pnpm/antd@5.21.1_date-fns@2.30.0_luxon@3.3.0_moment@2.29.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/antd/lib/affix/index.js
```

**Review by afc163 — APPROVED** [review]

**Pull request merged**
