### PR TITLE
chore: bump ⬆️  rc-slider  to 9.6.1

### PR DESCRIPTION
**Pull request by kerm1it**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix keep tooltip align with handle when dragging; Fix logic of getting bound value when using `startPoint` prop. |
| 🇨🇳 Chinese | 修复拖拽时提示内容对齐问题；修复当使用 `startPoint`属性时，边界值获取问题。|

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
> 更新 rc-slider 至 9.6.1。

写具体变化。

**Comment by yoyo837** [comment]
changelog 是不是写一下9.6.0 9.6.1 的内容好一些？

**Comment by Kermit-Xuan** [comment]
> > 更新 rc-slider 至 9.6.1。
> 
> 写具体变化。

没有具体变化，就只是版本升级😄，害怕后续版本升级跨度太大，

**Comment by afc163** [comment]
有变化的：https://github.com/react-component/slider/releases

**Comment by Kermit-Xuan** [comment]
> react-component/slider/releases

OK，9.6.1 有变化

**Review by ycjcl868 — APPROVED** [review]

**Pull request merged**
