### PR TITLE
feat(upload): add onDrop prop and remove event stopPropagation

### PR DESCRIPTION
**Pull request by ebonow**
### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/pull/29832
https://github.com/ant-design/ant-design/pull/30120#issuecomment-820954934

### 💡 Background and solution

I was looking for a way to notify the user if any rejected file types were dropped into the Uploader. Further reading into the issue tracker and merge requests led me to another dead end as the event was no longer being propagated as a result of https://github.com/ant-design/ant-design/pull/29832.

While the author did attempt to resolve this by creating a new boolean prop https://github.com/ant-design/ant-design/pull/30120, IMO I feel this is too narrow in scope to be helpful to a wider community.

This PR instead resolves the breaking change by removing stopPropagation from the event handler and introduces a new `onDrop` prop. This callback is passed the drop event so that the original intent of stopping propagation can be fulfilled while also allowing users to determine the dropped files from `event.dataTransfer.files`

```jsx
const onDrop = e => console.log(event.dataTransfer.files)

return <Uploader onDrop={onDrop} {...otherProps />
```

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Uploader fix to undo stopPropagation on drop event.   Add new `onDrop` prop to Uploader component.   |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ebonow** [comment]
@zombieJ Here are the requested changes from https://github.com/ant-design/ant-design/pull/30120#issuecomment-820954934

Can you or anyone else please assist me on how to create a new Changelog entry?

**Comment by ebonow** [comment]
Also worth noting that I came across this while debugging
https://stackoverflow.com/questions/11573710/event-datatransfer-files-is-empty-when-ondrop-is-fired

Apparently if a developer attempts to 
```
console.log(event.dataTransfer)
```
The console will always display `files` an empty array. However, if you console log `event.dataTransfer.files`, the console will return the list of files. Apparently this is a long known and unresolved bug but thought to mention it in case you wanted me to add it to the FAQ section.

**Comment by yoyo837** [comment]
`feature` branch Pls.

**Comment by yoyo837** [comment]
And test case needed.

**Comment by yoyo837** [comment]
Please also include the revert operation for #29832 in the PR.

**Comment by yoyo837** [comment]
rebase and push -f

**Comment by ebonow** [comment]
I've rebased the branch and working on tests now, can this please be re-opened?

**Pull request closed without merging**
