### PR TITLE
feat: add icon to collapsible

### LINKED ISSUE #37379: collapse折叠点击区域是否在header和disable基础上加个icon
### What problem does this feature solve?

有点击icon进行折叠展开的需求，但现在只有两个属性值，不想点击header文字来进行展开折叠

### What does the proposed API look like?

希望增加一个点击折叠icon进行展开折叠， 点击文字不进行折叠

### PR DESCRIPTION
**Pull request by MattinaYang**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

[https://github.com/react-component/collapse/pull/232](https://github.com/react-component/collapse/pull/232)
close #37379

### 💡 Background and solution

I added 'icon' to rc-collapse's 'collapsible' segment several monthes ago, and the pr had been merged two days ago, since version 3.4.0 was released. So I wanna add this to antd Collapse too.

### 📝 Changelog

Add choice 'icon' to 'collapsible', which could only be 'header' or 'disabled' for now.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | support new segment to existing 'collapsible' api  |
| 🇨🇳 Chinese | 为已有api：collapsible提供新字段支持 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片

snapshot 有问题，rc-collapse 还需要改下。

**Comment by afc163** [comment]
ping @Sheepeer

**Comment by Sheepeer** [comment]
> ping @Sheepeer

okkkkkkkkay

**Comment by Sheepeer** [comment]
snapshot报错应该是没有拉取到最新分支的问题，已解决；新增了文档中api部分对 showArrow 字段的说明：
image

**Comment by Sheepeer** [comment]
> 图片

image
全是这种调换引包顺序的情况 ↑ 这是为啥呀 😢

**Comment by Sheepeer** [comment]
@afc163 change this pr to https://github.com/ant-design/ant-design/pull/37566

**Pull request closed without merging**
