### PR TITLE
fix: sticky Table top border disappear when scrolling

### LINKED ISSUE #28093: Sticky table header scrolls one pixel because of disappearing border
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/fixed-header-and-scroll-bar-with-the-page-antd486-forked-sx7i9?file=/index.js)

### Steps to reproduce
Have bordered table with sticky headed and the table with margin around it. When scrolling, the top border disappears and the header moves up 1px

### What is expected?
The header stays at the same place with a border

### What is actually happening?
The border is gone and the header moves

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.13.1 |
| System | Mac 10.15 |
| Browser | Chrome 86.0.4240.198 |

### PR DESCRIPTION
**Pull request by AlanCutFlim**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Resolve #28093 

### 💡 Background and solution
Before:
Kapture 2020-12-04 at 18 23 55
After:
Kapture 2020-12-04 at 18 21 24

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix sticky Table top border disappear when scrolling      |
| 🇨🇳 Chinese |    修复 sticky Table 上边框在滚动时会消失的问题       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片

**Comment by AlanCutFlim** [comment]
@afc163 Updated, please check again.

**Comment by afc163** [comment]
`<Table bordered showHeader={false} />` this will lose border top.

**Comment by AlanCutFlim** [comment]
@afc163 I have updated, please check this PR again.

**Comment by afc163** [comment]
Hmmm...It is very hacky but works.

**Comment by AlanCutFlim** [comment]
Yeah, this is the first sollution that came into my mind. I actually find this hack have some other issues, like the border aren't connected in the edges(pointed in the GIF, have to zoom in a little bit) and it will lose top border too when `<Table bordered showHeader={false} fixedHeader scroll={{ y: 300 }} />`

Kapture 2020-12-09 at 21 56 36

So can i just close this PR, and let others try.

**Pull request closed without merging**
