### PR TITLE
style: fix TextArea custom border style not working when allowClear is enable

### LINKED ISSUE #38068: When I use TextArea with  allowClear. TextArea didn't get styles
### What is expected?
I want when I wrote styles need to work

### What is actually happening?
I tred give styles to TextArea with allowClear atribute, but didn't get styles on atribute styles. If I used without allowCllear styles atribute. it is working

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 18.1.0 |
| System | Windows |
| Browser | Chrome |

---

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #38068

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix TextArea custom border style not working when `allowClear` is enable.         |
| 🇨🇳 Chinese |  修复 TextArea 开启 `allowClear` 时自定义 border 样式无法生效的问题。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by zombieJ — APPROVED** [review]

**Comment by wangmeijian** [comment]
有问题，padding不能加到祖先元素，只能给textarea
```
<TextArea
    showCount
    allowClear
    maxLength={100}
    style={{ height: 120, border: '1px solid red',  padding: 20 }}
    onChange={onChange}
    placeholder="can resize"
  />
```
image

**Comment by afc163** [comment]
我看看

**Comment by afc163** [comment]
这个现在也有问题，不是这个 PR 改出来的：

https://codesandbox.io/s/qian-zhi-hou-zhi-biao-qian-antd-4-23-6-forked-rsjonc?file=/demo.tsx

**Comment by afc163** [comment]
遇到真实业务反馈再说吧，其实都建议用 className 做覆盖。style 不一定会到 input 元素。

**Comment by wangmeijian** [comment]
看看这个PR行不行 @afc163 
https://github.com/ant-design/ant-design/pull/38101#issuecomment-1283504670

**Comment by yuteng-long** [comment]
TextArea 设置allowClear默认的border消失且bordered属性失效

**Pull request merged**
