### PR TITLE
feat: optimize rate defaultValue > .5

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

#### 1. 补充 https://github.com/ant-design/ant-design/pull/24903

将 character 参数扩展为 props，changelog  使用 24903 中内容。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fixed Rate render unexpectedly when `value` is `1.6` or `2.6`.  |
| 🇨🇳 Chinese | 修复 Rate 支持半选时 `value` 被四舍五入的问题。         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/rate/demo/character-function.md](https://github.com/ant-design/ant-design/blob/feat-rate-props/components/rate/demo/character-function.md)
[View rendered components/rate/index.en-US.md](https://github.com/ant-design/ant-design/blob/feat-rate-props/components/rate/index.en-US.md)
[View rendered components/rate/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/feat-rate-props/components/rate/index.zh-CN.md)

### CODE REVIEW

**Comment by xrkffgg** [comment]
😂😂😂  这个 英文的 changelog 不好写啊。。。

**Comment by xrkffgg** [comment]
大佬，英文的 changelog 你来补一下吧

**Comment by xrkffgg** [comment]
PTAL

**Comment by yoyo837** [comment]
标题要不改为rate变化的内容？

**Comment by xrkffgg** [comment]
> 标题要不改为rate变化的内容？

不会翻译了。。。。超过 0.5 的情况初始化，你应该了解我的意思。。。

**Comment by yoyo837** [comment]
先写中文，有大佬不满的话可能会来帮你翻译，如果没人不满，发布的同学也好分辨更新内容。如何？

**Review by afc163 — APPROVED** [review]

**Pull request merged**
