### PR TITLE
feat: add progress status "flow"

### PR DESCRIPTION
**Pull request by xrkffgg**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
`flow` 即 流动，使 progress 颜色 流动

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/progress/demo/gradient-line.md](https://github.com/ant-design/ant-design/blob/feat-progress/components/progress/demo/gradient-line.md)

### CODE REVIEW

**Comment by xrkffgg** [comment]
大家有什么想法  😂😂😂 ？

**Comment by afc163** [comment]
已经有一个 `status="active"` 属性了。

```jsx
<Progress percent={50} status="active" />
```

**Comment by afc163** [comment]
哦看出来了，这个有点炫。

**Comment by afc163** [comment]
能应用到 active 的进度条上最好，单独开一个属性用法不清晰。

**Comment by xrkffgg** [comment]
这个是有点炫，感觉一般的企业网站都不会用 😂😂😂

**Pull request closed without merging**
