### PR TITLE
setting initialValue in select inside form

### PR DESCRIPTION
**Pull request by pawarvijay**
**Adding Documentation**

when we set `defaultValue` in simple select it nicely works
but but
[When we put select inside form and set defaultValue it doesn't work](https://codesandbox.io/s/oqwq8wk786)

then after 5 hours, I found [the `initialValue` prop in `getFieldDecorator`](http://ant.design/components/form/#components-form-demo-register)

so, i thought i should Document this :)

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by afc163** [comment]
No need to add it in Select doc, it is already mentioned in https://ant.design/components/form/#this.props.form.getFieldDecorator(id,-options)

**Comment by afc163** [comment]
Thx any way~

**Comment by pawarvijay** [comment]
## Thats WRONG place for select documentation

If developer is implementing `SELECT` component then documentation should be defined inside `SELECT` section 
and 
NOT somewhere else like `FORM`

Here if developer is implementing `SELECT` component he will have open `FORM` document and he will have to reach [LINE](https://ant.design/components/form/#this.props.form.getFieldDecorator(id,-options))  To make it working - THATS totally wrong

**Comment by afc163** [comment]
If you are using Select without Form, the information provided in http://ant.design/components/select/ is enough.

**Pull request closed without merging**
