### PR TITLE
demo: Add `FormModal` component

### PR DESCRIPTION
**Pull request by crazyair**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
https://github.com/ant-design/ant-design/issues/47573

### 📝 Changelog

增加 `FormModal` 组件，方便用户使用的时候与 `Form` 无异，可查看修改后的代码 https://github.com/ant-design/ant-design/blob/add-form-modal/components/form/demo/form-in-modal.tsx

https://github.com/ant-design/ant-design/assets/7971419/a583637f-db95-4ce8-ab31-9a2f3d12f668

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    demo       |
| 🇨🇳 Chinese |    demo       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
antd 希望保持原子性，这类组件组合的最佳实践放在 pro 系列更合适，或者就是交给社区进行探索。

**Comment by crazyair** [comment]
但是我觉得 pro 封装的不好，所以 andtd 这里还是需要加个示例

**Comment by afc163** [comment]
这个改动已经不是示例了，涉及新的特性，我还是觉得这个特性不宜在 antd 里加。

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/pull/47677

**Pull request closed without merging**
