### PR TITLE
Fix vertical steps with icons are not centered properly

### LINKED ISSUE #14677: Vertical steps with icons are not centered properly
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/pyn96z954m)

### Steps to reproduce
Copy the steps with icon example, but change the direction to vertical

### What is expected?
Icons should be centered (like the default numbers)

### What is actually happening?
They are left aligned

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | latest |
| System | windows 10 |
| Browser | chrome latest |

---
Thanks, I'm not sure if this is a bug or feature request.

### PR DESCRIPTION
**Pull request by ztplz**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
Fix https://github.com/ant-design/ant-design/issues/14677
> 3. Related issue link.
https://github.com/ant-design/ant-design/issues/14677

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
Fix vertical steps with icons are not centered properly
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by ztplz** [comment]
统一下图标的高宽，用户自定义高宽的话可以用在icon的style里设置

**Comment by zombieJ** [comment]
This only works on small size:

**Comment by ztplz** [comment]
@zombieJ 代码我看看

**Comment by zombieJ** [comment]
> @zombieJ 代码我看看

“竖直方向的步骤条” 这个例子，换一个图标

**Comment by ztplz** [comment]
icon默认24 * 24，但是steps里的默认32 * 32
image
改成什么标准？

**Comment by ztplz** [comment]
image

**Comment by zombieJ** [comment]
先居中就行了

**Comment by ztplz** [comment]
@zombieJ 他们不居中是因为step默认的图标大小和引入的图标默认大小不一样 引入的图标可以自己用style改成一样的就居中了

**Comment by zombieJ** [comment]
帮用户处理掉吧，否则这个 PR 合了用户还是要自己处理。

**Comment by ztplz** [comment]
感觉在rc那边改好一点

**Comment by zombieJ** [comment]
@ztplz 看看这样呢？https://github.com/ant-design/ant-design/pull/14797

**Comment by ryantxu** [comment]
Thank you!

**Pull request closed without merging**
