### PR TITLE
fix: when menuitem has seleted, but submenu has not seleted

### PR DESCRIPTION
**Pull request by ghost**
[Click Here](https://codepen.io/atomgao/pen/Yxqbpm/) show demo

### CODE REVIEW

**Comment by benjycui** [comment]
What are you going to fix? Please provide a re-producible demo.

**Comment by atomgao** [comment]
@benjycui Sorry, I forget. I have added a  [demo](https://github.com/atomgao/database/blob/master/shared/ant-design/menu-demo.md) here!

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

An online demo is enough.

**Comment by atomgao** [comment]
@benjycui 
Here is a demo: https://codepen.io/atomgao/pen/Yxqbpm
It's also my first codepen's demo.

**Comment by benjycui** [comment]
@afc163 I am not sure, should we highlight SubMenu if its children are selected?

**Comment by afc163** [comment]
Yes, it is a bug introduced in https://github.com/ant-design/ant-design/commit/6e145bfad3d13df05e59ff26b4c481e61d4bebf2

**Pull request merged**
