### PR TITLE
docs: replace class component with hooks and to TS demo

### PR DESCRIPTION
**Pull request by poyiding**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
42 个 commits 改了两个文件？

**Comment by poyiding** [comment]
> 

PR的title不对，这次就两个文件，其他的commit是之前的，我也不清楚为啥每次PR会显示之前的commit。

**Comment by poyiding** [comment]
不对，跟master 做了一次合并，https://github.com/ant-design/ant-design/pull/35641/commits/3c546c79e5b4df25a4a1fce1fafb2a8a9ca4d42a 还有这些文件的改动

**Comment by afc163** [comment]
不要复用同一个分支，永远切一个新分支。

**Pull request merged**
