### PR TITLE
ODD选择奇数项，Even选择偶数项。

### PR DESCRIPTION
**Pull request by xuya227939**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for branch `feature`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by yesmeck** [comment]
原来的逻辑没错吧。

**Comment by xuya227939** [comment]
原来的逻辑ODD会选择偶数项，Event选择奇数项。

**Comment by yesmeck** [comment]
对普通人来说 index 是从 1 开始算的，没错。

**Comment by xuya227939** [comment]
😂

**Pull request closed without merging**
