### PR TITLE
fix: TreeSelect selected item not fit dropdown width

### LINKED ISSUE #43428: TreeSelect组件样式在 4.x 和 5.x的表现不一致
### Reproduction link

[https://ant.design/components/tree-select-cn](https://ant.design/components/tree-select-cn)

### Steps to reproduce

查看第二个demo即可发现

在 `4.x` 中选中的 `高亮是一整行`,  在 `5.x` 版本中 选中的 `高亮只有具体的文字部分`
image

image

看了代码中发现是样式覆盖的问题
image

### What is expected?

样式和之前的一致

### What is actually happening?

不一致

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 17 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

### PR DESCRIPTION
**Pull request by Ali-ovo**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
fix: #43428

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix TreeSelect selected item not fit dropdown width.       |
| 🇨🇳 Chinese |  修复 TreeSelect 弹层内选中样式未撑满的问题。        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 010fd4d</samp>

Improve tree-select component style and readability. Fix a typo and remove a redundant comment in `genBaseStyle` function in `components/tree-select/style/index.ts`.

### <samp>🤖 Generated by Copilot at 010fd4d</samp>

* Fix a typo in the nested selector of the `${treeCls}-list-holder-inner` class to ensure proper alignment of tree-select items ([link](https://github.com/ant-design/ant-design/pull/43431/files?diff=unified&w=0#diff-c01ae53de3785d9ccea6872587f1ebcf51ff86fd62a8570034d932e7c94baaf3L33-R32))
* Remove an unnecessary comment line from the `genBaseStyle` function ([link](https://github.com/ant-design/ant-design/pull/43431/files?diff=unified&w=0#diff-c01ae53de3785d9ccea6872587f1ebcf51ff86fd62a8570034d932e7c94baaf3L16))

### CODE REVIEW

**Review by MadCcc — APPROVED** [review]

**Comment by MadCcc** [comment]
changelog 填一下

**Comment by Ali-ovo** [comment]
> changelog 填一下

英文也需要填么

**Comment by Ali-ovo** [comment]
> changelog 填一下

done

**Comment by li-jia-nan** [comment]
这标题敢不敢再详细一点？

**Comment by Ali-ovo** [comment]
> 这标题敢不敢再详细一点？

鬼鬼 忘记改了

**Comment by MadCcc** [comment]
Changelog 要从用户角度写一下解决了什么问题

**Comment by Ali-ovo** [comment]
> Changelog 要从用户角度写一下解决了什么问题

好的 现在这样可以么

**Pull request merged**
