### PR TITLE
fix(input): Improve resolveOnChange method

### LINKED ISSUE #31927: Input allowClear works unexpected
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-16-13-forked-3qlng?file=/index.js)

### Steps to reproduce
1、type some character in Input area,just don't let cursor blur(important) 
2、click the clear icon 
3、clear function did not work

### What is expected?
when click the clear icon ,the content was clear at any time

### What is actually happening?
the clear function did not work

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | win 7 |
| Browser | Chrome  92.0.4515.159 |

### PR DESCRIPTION
**Pull request by adaex**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #31927

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Input cannot clear content when focus it.   |
| 🇨🇳 Chinese |   修复 Input focus 时点击清除图标无效的问题。     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by adaex** [comment]
I think it would be better to solve the issue in this way.

**Comment by afc163** [comment]
Could you add test case？

**Comment by adaex** [comment]
> Could you add test case？

Okay, I started to do it right away.

**Comment by adaex** [comment]
@afc163 

I'm done. 🙇

**Pull request merged**
