### PR TITLE
refactor: upgrade rc-dropdown

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [X] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#19169 
https://github.com/react-component/dropdown/pull/87

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
Missing position animation:

### V3
Kapture 2019-10-31 at 18 15 01

### V4
Kapture 2019-10-31 at 18 15 47

**Comment by shaodahong** [comment]
> Missing position animation

Sub Menu enter animation? or Menu Leave animation? in your GIF, I see problems

**Comment by shaodahong** [comment]
if trigger Submenu, Menu be hidden faster than  leave animation, I will debug `rc-dropdown` try reproduce

**Comment by shaodahong** [comment]
In devtools animations 25%

## 3.0


## 4.0

**Comment by shaodahong** [comment]
@zombieJ I find `popupAnimation` deprecated, does this affect?
https://github.com/react-component/trigger/blob/0da83e0b822f71e8d564dbd4167ade706ccf733a/src/index.tsx#L87

**Comment by shaodahong** [comment]
cause by Menu component, and reproduce, @zombieJ Please help me review

### Dropdown Good (Leave without item)


### Dropdown Bad (Leave without item)


### Menu Good (Leave without item)


### Menu Bad (Leave without item)

**Comment by shaodahong** [comment]
v3 Menu Animation

image

v4 Menu Animation

image

like repeated animation in popup

**Comment by shaodahong** [comment]
oh, Popup Inner component have merged extra `className`, cause repeated animation

https://github.com/react-component/trigger/blob/0da83e0b822f71e8d564dbd4167ade706ccf733a/src/Popup.tsx#L340

**Comment by shaodahong** [comment]
I will take some time to fix `rc-trigger` tomorrow.

**Comment by zombieJ** [comment]
Hmmm.... Seems need to check why duplicated className patched. Maybe we need remove one in v4.

**Comment by zombieJ** [comment]
rebase

**Comment by shaodahong** [comment]
LGTM

**Pull request merged**
