### PR TITLE
Fix: fileList should not be updated when beforeUpload return false, close #8946

### LINKED ISSUE #8946: Upload Component upload file success when return false on beforeUpload function
### Version
3.1.1

### Environment
chrome 62.0.3202.75,  win10 

### Reproduction link
[https://codepen.io/w567675/pen/QarVXY](https://codepen.io/w567675/pen/QarVXY)

### Steps to reproduce
1: click button named '上传2'

### What is expected?
filelist no change

### What is actually happening?
filelist has changed

---
button1 named '上传2' is no problem.  The difference between button 1 and button 2 is button2 use "valuePropName" and  "getValueFromEvent" in getFieldDecorator function.

### PR DESCRIPTION
**Pull request by dengfuping**
Fix #8946.

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/626ebf2063c15e151292b9a9dc5b42719f5226df should fix #8946 too.

**Comment by dengfuping** [comment]
Ok 👍

**Comment by dengfuping** [comment]
But the issue still exists for the [demo](https://riddle.alibaba-inc.com/riddles/4491b49e) in the latest `3.2.1` version. Nothing wrong in the previous version.

**Comment by afc163** [comment]
I think it is correct behavior cause when `beforeUpload: () => false`, that means don't upload automaticly and upload manually later. That makes the file should be put in fileList.

You should control the `fileList` in `beforeUpload` if you don't need this file in list at all.

**Comment by dengfuping** [comment]
Uploading manually means that beforeUpload always return false as [the official demo](https://ant.design/components/upload/#components-upload-demo-upload-manually) shows. However, that means there is no much sense for what `beforeUpload` does if we need to set `fileList` every time. For the most situations of not manually uploading, unnecessary update for `fileList` should be more convenient.

**Pull request closed without merging**
