### PR TITLE
feat: inputNumber support customize upIcon/downIcon

### PR DESCRIPTION
**Pull request by heiyu4585**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/33641
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   feat: inputNumber support customize upIcon/downIcon        |
| 🇨🇳 Chinese |  功能:  `inputNumber `组件支持自定义 `向上icon`  `向下icon`       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/33318#discussion_r781017389

**Comment by heiyu4585** [comment]
> [#33318 (comment)](https://github.com/ant-design/ant-design/pull/33318#discussion_r781017389)

`<InputNumber controls={{ upIcon: ReactNode, downIcon: ReactNode,visibility:false}} />`,请问是否显示再加个属性吗

**Comment by afc163** [comment]
controls 本身可以是 boolean 类型或扩展成 object。

**Comment by heiyu4585** [comment]
https://github.com/ant-design/ant-design/pull/33907

**Pull request closed without merging**
