### PR TITLE
add  Belarusian language

### PR DESCRIPTION
**Pull request by StIvan8**
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

-----
[View rendered components/image/demo/placeholder.md](https://github.com/StIvan8/ant-design/blob/master/components/image/demo/placeholder.md)
[View rendered components/input/index.zh-CN.md](https://github.com/StIvan8/ant-design/blob/master/components/input/index.zh-CN.md)
[View rendered components/tabs/demo/extra.md](https://github.com/StIvan8/ant-design/blob/master/components/tabs/demo/extra.md)
[View rendered components/tag/demo/status.md](https://github.com/StIvan8/ant-design/blob/master/components/tag/demo/status.md)

### CODE REVIEW

**Comment by afc163** [comment]
image

Please make commits history clean.

**Comment by afc163** [comment]
Mixed other commits.

**Comment by StIvan8** [comment]
Which file should I add the calendar localization to?

**Review by StIvan8 — COMMENTED** [review]
added Belarusian language

**Review by afc163 — CHANGES_REQUESTED** [review]
image

Mixed other commits.

**Pull request closed without merging**
