### PR TITLE
chore: update rc-image

### PR DESCRIPTION
**Pull request by shaodahong**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Ref: https://github.com/ant-design/ant-design/issues/26996

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix Image style prop not acting on img element.   |
| 🇨🇳 Chinese | 修复 Image style 属性未作用于 img 元素的问题。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ycjcl868** [comment]
argos 需要 approval 一把

**Comment by shaodahong** [comment]
> argos 需要 approval 一把

@ycjcl868 好了，跟车

**Comment by afc163** [comment]
Changelog 不完整。

**Comment by shaodahong** [comment]
Done.

**Comment by afc163** [comment]
> 添加 wrapperStyle 属性

文档中没体现。

**Comment by shaodahong** [comment]
> > 添加 wrapperStyle 属性
> 
> 文档中没体现。

先不暴露，看后期反馈

**Comment by afc163** [comment]
文档中不体现的话，changelog 也别写。

**Comment by shaodahong** [comment]
嗯，那直接就原本的就可以，或者就是常规升级，changlog 留空白

**Comment by afc163** [comment]
> 修复 Image style 未生效

修复 Image `style` 属性未作用于 `img` 元素的问题。

**Comment by shaodahong** [comment]
Done.

**Review by ycjcl868 — APPROVED** [review]

**Pull request merged**
