### PR TITLE
fix: Tooltip not work correctly on disabled Switch

### LINKED ISSUE #17357: Tooltip still visible after mouseLeave in disabled Switch
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/magical-brahmagupta-lgx0m)

### Steps to reproduce
disabled Switch and toggle mouseEnter, then toggle mouseLeave
Kapture 2019-06-28 at 17 10 04

### What is expected?
tooltip disappear

### What is actually happening?
tooltip still visible

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8.6 |
| System | MacOS 10.14.5 |
| Browser | Chrome 77.0.3833.0 & Safari 12.1.1  |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

fix #17357

### 💡 Solution

Add check logic

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Tooltip not work correctly on disabled Switch      |
| 🇨🇳 Chinese |     修复 Tooltip 在 disabled Switch 中工作不正确的问题      |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by arfeo** [comment]
Hey there,

What is the status of this merge? Looks like it hasn't appeared in any stable antd release...

**Comment by damiangreen** [comment]
This is still a bug in the latest 4.2.5 version. This case needs re-opening

**Comment by mikeyshing88** [comment]
Experiencing the same as above^

**Comment by Homingciu** [comment]
antd: 4.16.9, 依旧有问题！

**Comment by clintmilner** [comment]
My app is using 4.15.1 and I'm still seeing this issue.

**Pull request merged**
