### PR TITLE
Add Portuguese locale

### PR DESCRIPTION
**Pull request by taviroquai**
Hello,

This is the pull request to add a new locale: pt_PT

I see that there is dependencies to rc-pagination and rc-calendar. For now, I'm just pointing to "pt_BR" locale files on these repos, until there is the pt_PT locale.

Thanks

### CODE REVIEW

**Comment by benjycui** [comment]
@taviroquai actually, you had better to PR to rc-pagination and rc-calendar first, thanks.

**Comment by benjycui** [comment]
ping~

**Comment by taviroquai** [comment]
@benjycui is it possible to merge without commit to rc-calendar, please?

Thanks

**Comment by taviroquai** [comment]
Hi,

I did pull request to rc-pagination and rc-calendar as requested.

Thank you :)

**Comment by benjycui** [comment]
Rebase, please.

**Comment by benjycui** [comment]
oops......

**Comment by taviroquai** [comment]
What happen? What should I do Next?

Thanks

**Comment by benjycui** [comment]
See: http://makeapullrequest.com/

**Comment by taviroquai** [comment]
@benjycui 

It says all checks passed and there is no concflits.

Please, advise.

**Comment by taviroquai** [comment]
All checks are ok. Please merge. Thanks.

**Comment by benjycui** [comment]
Thanks!

**Pull request merged**
