### PR TITLE
style(DatePicker): fix hover style error when checked again

### PR DESCRIPTION
**Pull request by Yuiai01**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

加上之前：

https://user-images.githubusercontent.com/112228030/219827147-2463ef2d-d410-47b8-a1fe-02db5a7f80a5.mov

加上之后：

https://user-images.githubusercontent.com/112228030/219827164-435749d4-3780-48ef-9686-2cdc07d5a1b2.mov

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix hover style error when checked again           |
| 🇨🇳 Chinese | 修复再次选择日期时错误的 hover 样式          |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片

图片

hover 和选中的位置最好能对齐，注意上面两个 8 月。

**Review by afc163 — APPROVED** [review]

**Comment by Yuiai01** [comment]
> 图片
> 
> 图片
> 
> hover 和选中的位置最好能对齐，注意上面两个 8 月。

大佬，我还在研究咋对齐来着....

**Comment by afc163** [comment]
你继续提 PR，我先合并了发一版。

**Comment by Yuiai01** [comment]
> 你继续提 PR，我先合并了发一版。

好~

**Pull request merged**
