### PR TITLE
Update interface.tsx

### PR DESCRIPTION
**Pull request by davidfurlong**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
I don't think we need `children` in ts props, please provide reproduce.

**Comment by davidfurlong** [comment]
> I don't think we need `children` in ts props, please provide reproduce.

TypeScript was complaining about children when I pass to the Upload.Dragger component. Maybe I'm doing it wrong you would know better

**Comment by afc163** [comment]
please provide reproduce: https://codesandbox.io/

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/pull/18196

**Pull request closed without merging**
