### PR TITLE
chore: add hooks deps check

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [x] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: add hooks deps check |
| 🇨🇳 Chinese | chore: 添加 hooks 依赖项检查 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
127个文件，看样子要挨个手动加 ignore 了

**Comment by MadCcc** [comment]
这条规则不用加，不是必须的

**Comment by li-jia-nan** [comment]
> 这条规则不用加，不是必须的

微信图片_20230104224202

怎么说，要么两位大佬统一一下意见？

**Comment by yoyo837** [comment]
hook deps这个lint作用不大，很多地方就是要那样写，lint又说要加deps

**Comment by yoyo837** [comment]
> > 这条规则不用加，不是必须的
> 
> 微信图片_20230104224202
> 
> 怎么说，要么两位大佬统一一下意见？

他说的是lint不工作，不是加hook的lint吧？

**Comment by li-jia-nan** [comment]
这个先close了

**Pull request closed without merging**
