### PR TITLE
Update loading.md

### PR DESCRIPTION
**Pull request by cjke**
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by yesmeck** [comment]
Thanks.

**Comment by cjke** [comment]
No worries. Quick question, are you happy for quick little changes like the above? As I read through the documentation, its pretty easy to make small changes to English/grammar. Does that work?

Or do you prefer larger documentation changes?

**Comment by benjycui** [comment]
> larger documentation changes

This will be better.

**Comment by cjke** [comment]
Easy - will do from now on - 👍

**Pull request merged**
