### PR TITLE
feat: Added "today" and "previous/next" buttons to Calendar

### PR DESCRIPTION
**Pull request by BenjaVR**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

In the Calendar component, if you quickly want to change to the next or previous month/year, or just want to go to today, there was no easy option to do that. You always had to use the dropdowns to select the date or year you want to go to.

### 💡 Solution

You can now optionally show a today button and/or previous and next navigation buttons in the header of the Calendar component. These are turned off by default, to keep the same behaviour as before this change.

image

image

### 📝 Changelog

- English Changelog: You can now optionally show a today button and/or previous and next navigation buttons in the header of the Calendar component. The default value for both of these props are `false`.
- Chinese Changelog (optional):

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by afc163 — CHANGES_REQUESTED** [review]
Mixed other commits, you should pull and rebase feature branch.

**Comment by faradaytrs** [comment]
any progress on this?

**Comment by afc163** [comment]
closing for no response for a long time.

**Comment by faradaytrs** [comment]
this feature is really nice, anyone who could finish this?

**Comment by faradaytrs** [comment]
@afc163 What is the problem with that pull request now? maybe i could make fixes

**Pull request closed without merging**
