### PR TITLE
perf: 优化Typography.Paragraph, symbol在expandable为false时也可显示

### LINKED ISSUE #41219: 期望Typography.Paragraph在自定义onExpand回调时能够有能力阻止原本的展开事件
### What problem does this feature solve?

在使用时，文字溢出触发省略后，期望能在省略号的末尾自定义添加一个【查看更多】的symbol，点击该symbol以自定义行为（例如弹窗的形式）展示出更多相关的信息且不展开文字，但发现无法对该组件的Expand行为进行阻止。

### **期望可阻止默认展开的行为，例如在ellipsis中添加一个forbidExpand属性值来控制展开行为**

``` js
<Paragraph ellipsis={{ forbidExpand: true }}>{content}</Paragraph>
```

___

### 发现源码中先执行了变更折叠state后触发自定义的onExpand函数，导致无法阻止Expand行为

```js
// >>>>> Expand
const onExpandClick: React.MouseEventHandler<HTMLElement> = (e) => {
  setExpanded(true);
  ellipsisConfig.onExpand?.(e);
};
```

___

### 如果不考虑拓既可展开又可折叠，可先进行简单变更实现控制展开行为
``` js
// >>>>> Expand Function Update
const onExpandClick: React.MouseEventHandler<HTMLElement> = (e) => {
  setExpanded(!!ellipsisConfig?.forbidExpand);
  ellipsisConfig.onExpand?.(e);
};
```

### PR DESCRIPTION
**Pull request by Taylord-Lee**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
fix #41219

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese | 优化Typography.Paragraph, symbol在expandable为false时也可显示 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
Rebase please.

**Comment by Taylord-Lee** [comment]
> Rebase please.

I am sorry. I have no idea to push code after rebase. But I force push it when I rebase upstream/feature, it looks like normal now.

**Comment by yoyo837** [comment]
> > Rebase please.
> 
> I am sorry. I have no idea to push code after rebase. But I force push it when I rebase upstream/feature, it looks like normal now.

You are doing the right thing.

**Comment by Taylord-Lee** [comment]
I have three failing checks, but it looks the same problem. This error isn't caused by me. And what should I do to handle it?
```js
console.error
    Warning: Received `false` for a non-boolean attribute `visible`.
    If you want to write it to the DOM, pass a string instead: visible="false" or visible={value.toString()}.
    If you used to conditionally omit it with visible={condition && value}, pass visible={condition ? value : undefined} instead.
```

**Comment by yoyo837** [comment]
Hold on, rebase `upstream/feature`? But you are requesting a merge into `master`.

**Comment by Taylord-Lee** [comment]
Oh I am sorry, I think I'm fixing a bug, so...

**Comment by yoyo837** [comment]
Looks like other unrelated commits were mixed in it.

**Comment by Taylord-Lee** [comment]
Actually, I'm a little bit confused.

**Comment by yoyo837** [comment]
Close by https://github.com/ant-design/ant-design/issues/41219#issuecomment-1469657821. 
If you still have questions, feel free to open a new issue for that.

**Pull request closed without merging**
