### PR TITLE
Add missing types for tree

### LINKED ISSUE #13123: antd tree onDrop props AntTreeNodeDropEvent has incomplete parameter definition
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
mac chrome

### Reproduction link
[Edit on CodeSandbox](https://wynq54v225.codesandbox.io/)

### Steps to reproduce
antd tree onDrop props AntTreeNodeDropEvent has incomplete parameter definition in Tree.d.ts
AntTreeNodeDropEvent definition in Tree.d.ts is
 `AntTreeNodeDropEvent {
    node: AntTreeNode;
    dragNode: AntTreeNode;
    dragNodesKeys: string[];
    event: React.MouseEventHandler<any>;
}`
but in tree-demo-draggable it has key : dropPosition and dropToGap.
### What is expected?
make AntTreeNodeDropEvent parameter complete, and export this type in antd/lib/tree/index.d.ts

### What is actually happening?
it's difficult to use onDrop props in tsx because of definition uncompleted.
and I can't import AntTreeNodeDropEvent in component tsx file because it is not exported in  antd/lib/tree/index.d.ts.

### PR DESCRIPTION
**Pull request by ztplz**
Close #13123

### CODE REVIEW

**Comment by eyewire** [comment]
> Close #13123

I didn't get any update when update antd using npm, I have checked node_modules/antd/lib/tree.d.ts, I still get four keys in AntTreeNodeDropEvent interface and unable to import AntTreeNodeDropEvent.

**Comment by ztplz** [comment]
@eyewire You need to wait until the PR is merged and the new version is released. When will the next release be released? @afc163

**Comment by ztplz** [comment]
@eyewire  `close` means that if the PR is merged, the issue will be automatically closed without the maintainer having to manually close it. So the maintainer does not have to check which issues have been resolved and needs to be closed.

**Comment by eyewire** [comment]
> @eyewire `close` means that if the PR is merged, the issue will be automatically closed without the maintainer having to manually close it. So the maintainer does not have to check which issues have been resolved and needs to be closed.

ok，thanks~ please release new version asap, thanks a lot~

**Comment by afc163** [comment]
@ztplz About end of this month.

**Comment by afc163** [comment]
@ztplz About end of this month.

https://ant.design/changelog#Release-Schedule

**Pull request merged**
