### PR TITLE
feat: App 增加 style 属性，message 配置， notification 配置支持

### PR DESCRIPTION
**Pull request by nuintun**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |       Add style attribute, message configuration and notification configuration support to the app     |
| 🇨🇳 Chinese |    App 增加 style 属性，message 配置， notification 配置支持      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by nuintun** [comment]
@afc163 看下，有需求

**Comment by afc163** [comment]
什么需求需要加这个，能否详细描述一下？

**Comment by nuintun** [comment]
@afc163 配置全局 `message`, `notification` 参数，比如 `maxCount` 等，算是刚需吧！

`style` 可以定义一些动态默认样式，从 `token` 中读取背景色，字体颜色等。

**Comment by nuintun** [comment]
关闭 https://github.com/ant-design/ant-design/pull/40458

**Pull request closed without merging**
