### PR TITLE
CZ localization

### PR DESCRIPTION
**Pull request by martinnov92**
Hello,

Can you please review my merge request? I have added localization for czech language.
I also created pull request for rc-pagination (https://github.com/react-component/pagination/pull/62)

Thank you.

### CODE REVIEW

**Comment by paranoidjk** [comment]
thanks, this may be in next release

**Comment by yesmeck** [comment]
Thanks @martinnov92 .

1. Could plz PR to branch feature-2.8;
2. [Upload](https://github.com/ant-design/ant-design/blob/feature-2.8/components/locale-provider/en_US.tsx#L39-L44) needs translate on feature-2.8;
3. New locale  should add to [test](https://github.com/ant-design/ant-design/blob/feature-2.8/components/locale-provider/__tests__/index.test.js#L60).

**Comment by martinnov92** [comment]
Hello @yesmeck , it should be done

**Comment by yesmeck** [comment]
Wait https://github.com/react-component/pagination/pull/62

**Comment by martinnov92** [comment]
@yesmeck rc-pagination has been merged

**Comment by afc163** [comment]
You need to fork and modify it from feature-2.8

**Comment by martinnov92** [comment]
Hello, I had to created new pull request (https://github.com/ant-design/ant-design/pull/5169) as I couldn't change the base branch.

Sorry about this and thank you.

Should I close this pull request?

**Pull request closed without merging**
