### PR TITLE
fix: Update docs for normal-login Form to comply with TS definitions

### PR DESCRIPTION
**Pull request by sreetamdas**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

This fixes an error in TypeScript, since in `<Form.Item>` we are assigning a string also to its children. Attaching the relevant TS error below for consideration:

```
Type '{ children: (string | Element)[]; }' is not assignable to type 'FormItemProps'.
  Types of property 'children' are incompatible.
    Type '(string | Element)[]' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | RenderChildren | ReactElement<...>[]'.
      Type '(string | Element)[]' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>[]'.
        Type 'string | Element' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>'.
          Type 'string' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>'.
```

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Updated Docs for Normal Login Foem       |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/form/demo/normal-login.md](https://github.com/sreetamdas/ant-design/blob/patch-1/components/form/demo/normal-login.md)

### CODE REVIEW

**Comment by zombieJ** [comment]
Your PR seems nothing about TS definition. Maybe missing push code?

**Comment by sreetamdas** [comment]
@zombieJ The Typescript code is alright, however when using the example, typescript throws an error which I've mentioned above. So, the _example_ needs to be updated. In my PR, I've simply gone ahead and removed the problematic part of the example in the documentation, but if you'd like, I can try and find a way to preserve it by wrapping it in a compliant wrapper.

**Comment by zombieJ** [comment]
Days ago patch PR with #20963 but not released yet. Is that resolve this issue?

**Comment by sreetamdas** [comment]
Ah. I'm not sure if that'll solve it. But I'll wait until the new release and test it out then. Will close the PR for now, reopen it later if required. Thanks!

**Pull request closed without merging**
