### PR TITLE
feat: add successColor for Progress

### PR DESCRIPTION
**Pull request by fireairforce**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/20770

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Progress support customise filled Progress color      |
| 🇨🇳 Chinese |    Progress组件新增自定义已完成进度条颜色      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/progress/index.en-US.md](https://github.com/fireairforce/ant-design/blob/process-successPercent/components/progress/index.en-US.md)
[View rendered components/progress/index.zh-CN.md](https://github.com/fireairforce/ant-design/blob/process-successPercent/components/progress/index.zh-CN.md)

### CODE REVIEW

**Comment by fireairforce** [comment]
不是很会用jest的快照测试，我看看文档再来补充测试用例~

**Comment by afc163** [comment]
I think we should use `success` as object, instead of adding more successXxx props.

```jsx
success={{
  progress: 30,
  strokeColor: 'red',
}}
```

Then deprecate `successProgress`.

**Comment by fireairforce** [comment]
OK，I will make some adjustments

**Comment by fireairforce** [comment]
done

**Comment by afc163** [comment]
Deprecate `successProgress`: warning when use it.

**Comment by fireairforce** [comment]
done~

**Review by afc163 — APPROVED** [review]

**Comment by fireairforce** [comment]
这个居然没上车吗。。。QuQ

**Pull request merged**
