### PR TITLE
chore: try new version of @rc-component/trigger

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 9212de9</samp>

The pull request upgrades the `trigger` component and fixes a dependency issue. This enhances the performance and usability of various components that rely on `trigger`, such as `tooltip`, `popover`, and `dropdown`.

### <samp>🤖 Generated by Copilot at 9212de9</samp>

* Upgrade the trigger component and its usage in other components ([link](https://github.com/ant-design/ant-design/pull/45360/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L121-R121), [link](https://github.com/ant-design/ant-design/pull/45360/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L339-R340),                                           F

### CODE REVIEW

**Comment by afc163** [comment]
居然还变大了。。

**Comment by yoyo837** [comment]
这是为啥

**Comment by afc163** [comment]
https://github.com/react-component/trigger/pull/429 antd 5 本来就不依赖 dom-align，所以白搞了。

**Comment by yoyo837** [comment]
> [react-component/trigger#429](https://github.com/react-component/trigger/pull/429) antd 5 本来就不依赖 dom-align，所以白搞了。

刚看了一眼, 确实是. :)

**Pull request closed without merging**
