### PR TITLE
refactor: change MenuItem to FC c component

### PR DESCRIPTION
**Pull request by zheeeng**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Change MeneItem to React functional style component |
| 🇨🇳 Chinese | 重构 MenuItem 为函数组件 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
- #38407 这个我在改了

**Comment by zheeeng** [comment]
> * [refactor(Menu): rewrite CC => FC #38407](https://github.com/ant-design/ant-design/pull/38407) 这个我在改了

那我能否向你的这个分支提交这个 pr？它目前的状态是 closed，之后会 reopen 吧

**Comment by li-jia-nan** [comment]
> 

后面不会 reopen 了，因为现在是基于 v4 改的，到时候合并到 v5 的话冲突太多了，我后面打算在 v5 的分支上重新改

**Comment by zheeeng** [comment]
那这个提交应该 close 掉是吗？看了下你的 pr 的实现，感觉 omit 的省略掉更清爽

**Comment by li-jia-nan** [comment]
先close吧，重构FC的工作等v5发布了再搞，现在重构会给merge代码造成压力，这个闲夕大佬反馈多很多次了……

omit 那个感觉问题不大，我后面再斟酌一下

**Pull request closed without merging**
