### PR TITLE
Feature custom icons

### PR DESCRIPTION
**Pull request by chengcyber**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

new props for icon customization of tree-select, select, tree

### API Realization (Optional if not new feature)

expose props for icons

### What's the effect? (Optional if not new feature)

no effect for current users

### Changelog description (Optional if not new feature)

CN EN docs updated

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by afc163** [comment]
I don't think we should support custom icons for these components in every detail, it make design system lost its meaning.

**Comment by kimochg** [comment]
@afc163 Exposing those APIs gives developers more control. There are many customizations of enterprise products. It leads to positive impacts on those of things, meanwhile, no harm to the current design system.

**Comment by afc163** [comment]
I strongly recommend use rc-select instead of antd' Select if every icon need to customize, that is the rc-components are designed for. We should follow antd design system when using antd components.

> no harm to the current design system.

There are too many APIs already, we need to control it.

**Comment by kimochg** [comment]
@afc163 This is a bit of weird that rebuilding a brand new component based on rc-components, just for icon customization. That leads to a totally duplicate work of antd has done. IMO, The icon customization contains the same meaning of style customization from the perspective of the design system. I could not get a clear idea that antd forbidden the icon one and supports style one, just because the number of APIs is getting larger. The number of APIs is exactly the power of antd, rather than the drawback thing. Definitely, I can custom the antd/rc-components on my own to achieve my goal, but contributing the community, making the good things to all users is always the beautiful and charming part of an open source codebase.

**Comment by kimochg** [comment]
any news? Are those changes acceptable, partially acceptable, or even total rejected?

**Comment by afc163** [comment]
IMO `loadingIcon` of Tree maybe useful in some situation that we can add it, ant insist not adding other icon props for our design value.

**Pull request closed without merging**
