### PR TITLE
fix: Image.PreviewGroup typescript definition 

### PR DESCRIPTION
**Pull request by liuchao233**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#28209 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix Image.PreviewGroup typescript definition |
| 🇨🇳 Chinese |    修复    Image.PreviewGroup 类型   |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by hengkx** [comment]
check ci and add changelog

**Review by shaodahong — APPROVED** [review]
Thanks

**Comment by afc163** [comment]
图片

**Comment by liuchao233** [comment]
`PR has only one non-merge commit and it's not semantic; add another commit before squashing`

What should I do to fix this ? Add another commit ?

**Pull request merged**
