### PR TITLE
Fix empty table placehoder style

### PR DESCRIPTION
**Pull request by yesmeck**
1. Fixed header 的时候"暂无数据"会被遮住；
2. small 的时候下面会有两条边框。

http://codepen.io/yesmeck/pen/VPqqZR?editors=0010

Before:

before

After:

after

### CODE REVIEW

**Comment by afc163** [comment]
给 `.ant-table-placeholder` 加一个 `position: relative;`。

**Comment by yesmeck** [comment]
调整了，顺便把边框也调整了下。

**Review by afc163 — APPROVED** [review]

**Comment by coljung** [comment]
Out of curiosity, is there a way to modify the placeholder that results in the table when there is no data?

Currently we get this attribute: 
```
<div class="ant-table-placeholder">No Data</div>
```

I thought there was a way to customize it, but could not find how.

**Comment by yesmeck** [comment]
@coljung See #3822

**Comment by coljung** [comment]
thx!

**Pull request merged**
