### PR TITLE
Remove magic number of style align

### LINKED ISSUE #20831: Input prefix suffix style
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/input-cn/#components-input-demo-presuffix](https://next.ant.design/components/input-cn/#components-input-demo-presuffix)

### Steps to reproduce
Enter large amount of text.Prefix two texts have the same problem.
image

### What is expected?
 normal style

### What is actually happening?
error style 

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

`height` 是罪魁祸首，去掉后全都正常了，magic number 也不用了：

Chrome:
截屏2020-01-13下午5 49 26

FF:
截屏2020-01-13下午5 51 49

Safari:
截屏2020-01-13下午5 52 26

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Fix components style align.     |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
issue 是不是关联错了。

**Comment by zombieJ** [comment]
一起的，这个 Input with affix 也需要调整：
截屏2020-01-13下午6 25 50

**Comment by zombieJ** [comment]
> 一起的，这个 Input with affix 也需要调整：
> 截屏2020-01-13下午6 25 50

Input affix 要做的操作有点多，另开一个。

**Comment by gsaandy** [comment]
this breaks small button padding if `'@font-size-base': '16px'`

**Comment by zombieJ** [comment]
@gsaandy , could you help to create a new issue instead?

**Pull request merged**
