### PR TITLE
Fix the height of the table component + and - the same, and the center display

### PR DESCRIPTION
**Pull request by ssly**

### CODE REVIEW

**Comment by benjycui** [comment]
image

**Comment by benjycui** [comment]
I think it works fine now. If you still meet this issue, you had better provide a online demo, thanks.

**Comment by afc163** [comment]
It would make the `+` a little misplace.

image

**Comment by ssly** [comment]
I looked at the official website and found something different.
In ant.design:
ant.design

In my demo: [http://lius.me/task/](http://lius.me/task/)

my demo

I think this place uses characters + may be affected by external styles, because I have to go to work, and I'll look at the problem at night

**Pull request closed without merging**
