### PR TITLE
feat(table): add some less variables

### LINKED ISSUE #30141: Need more variables to style tables
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Certain aspects of antDesign Tables are not customizable via the existing less variables: header and some cell formatting is not available. For example, I need to style the "thead th" values for font-size, color, line-height, letter-spacing, text-transform. Same for the "tbody td" elements.

### What does the proposed API look like?
@table-header-color: #hhh;
@table-header-font-size: nnpx;
@table-header-line-height: nnpx;
@table-header-letter-spacing: nnpx;
@table-header-text-transform: uppercase;

@table-body-color: #hhh;
@table-body-font-size: nnpx;
@table-body-line-height: nnpx;
@table-body-letter-spacing: nnpx;
@table-body-text-transform: uppercase;

### PR DESCRIPTION
**Pull request by Map1en**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #30141

### 📝 Changelog

add less var:
@table-header-font-size: @font-size-base;
@table-header-letter-spacing: normal;
@table-header-line-height: @line-height-base;
@table-header-text-transform: none;
@table-body-color: @text-color;
@table-body-line-height: @line-height-base;
@table-body-letter-spacing: normal;
@table-body-text-transform: none;

"@table-header-color" already have
"@table-body-font-size" use @table-font-size instead

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      add some less variables to the table component     |
| 🇨🇳 Chinese |     为表格组件添加一些less变量      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
你这不是单纯的加变量，新增的css 需要说明一下意图，解决什么问题。

**Comment by yoyo837** [comment]
或者，最好是分开两个PR更清晰。例如，先改功能，再加变量。

**Comment by Map1en** [comment]
> 你这不是单纯的加变量，新增的css 需要说明一下意图，解决什么问题。

其实只是按照那个issue添加了一些变量，添加css的都是link，没有意图，用的都是默认值。

**Comment by zombieJ** [comment]
设计师在整理色盘，less 变量先等等。应该会有一些变化，免得加了之后又要移除掉。

**Pull request closed without merging**
