### PR TITLE
Remove the polyfill of matchMedia

### PR DESCRIPTION
**Pull request by ztplz**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/18830

### 💡 Background and solution
https://github.com/ant-design/ant-design/issues/18830

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
`enquire.js` 没必要了  里面还和原生的混着用

**Comment by ztplz** [comment]
image
这里又用的native 其他地方又用`enquire.js`

**Comment by zombieJ** [comment]
这段代码是为了过 CI 的，client 端不会跑。

**Comment by afc163** [comment]
可能需要统一挪到 jest 的 setup 里去：https://stackoverflow.com/questions/39830580/jest-test-fails-typeerror-window-matchmedia-is-not-a-function

**Comment by afc163** [comment]
conflicted

**Pull request closed without merging**
