### PR TITLE
fix firefox can't set height smaller than content on flex item

### PR DESCRIPTION
**Pull request by sepehrity**

### CODE REVIEW

**Comment by zombieJ** [comment]
Thanks for contribution. Could you provide a reproduce of current behavior?

**Comment by scharepmc2hr** [comment]
I'm working on my project and everything it's OK until I saw the result on Firefox. The "overflow-y" didn't work for inside content and all page was scrollable. I add these and the problem solved.

**Comment by afc163** [comment]
You can put out some screen shot or gif to help us describle your fix in changelog more accurate.

**Comment by scharepmc2hr** [comment]
@afc163 You can see the differences in Firefox:

Before:
before

After:
after

**Comment by scharepmc2hr** [comment]
For more details, I found [this](https://stackoverflow.com/a/28639686).

**Comment by w1997** [comment]
这个样式产生了一个问题
我的布局是左右布局，左边的高度是539，右边ant-layout-content样式flex:auto后预期的高为539
但是当ant-layout-content内容的高度超出了539, ant-layout-content的高度还是保持了不变

ant-layout-side的高度：
image

加了min-height样式的的ant-layout-content高度：
image

没有加min-height样式的的ant-layout-content高度：
image

**Comment by zombieJ** [comment]
@w1997 能开个新 issue 贴上在线重现吗？

**Comment by w1997** [comment]
@zombieJ 好

**Comment by w1997** [comment]
经过测试 是自己的问题 谢谢了~

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18931

**Comment by afc163** [comment]
cause https://github.com/ant-design/ant-design/issues/18931, @scharepmc2hr could you help to check it?

**Comment by scharepmc2hr** [comment]
https://github.com/ant-design/ant-design/issues/18931#issuecomment-538974324

**Pull request merged**
