### PR TITLE
fix: PageHeader tag ts typo

### LINKED ISSUE #23701: Page-header property tags type issue
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-pageheader-tags-for-typescript-3zk8v?file=/index.tsx)

### Steps to reproduce
on ts compile

### What is expected?
no type error - Type 'Element' is not assignable to type 'TagType | TagType[]'

### What is actually happening?
<PageHeader title="title" tags={<Tag color="blue">service</Tag>} />
tags would throw an error: Type 'Element' is not assignable to type 'TagType | TagType[]' on compile

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.1 |
| System | macOS 10.15.4 |
| Browser | chrome 81.0.4044.122 |

---
related issue? -> https://github.com/ant-design/ant-design/issues/16092 (this has been merged.)
on recent release 4.1.5. typing for tags has changed from ReactElement<Tag> to TagType
please help.

### PR DESCRIPTION
**Pull request by hengkx**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close #23701

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fix: PageHeader tag ts typo       |
| 🇨🇳 Chinese |  修复PageHeader tag属性ts定义错误         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by hengkx** [comment]
```
FAIL components/date-picker/__tests__/RangePicker.test.js
  ● RangePicker › ranges › RangePicker support presetted ranges with Tags
```
其它的ci

**Comment by hengkx** [comment]
image
这个是没用吗？

**Comment by yoyo837** [comment]
先手工rebase吧

**Comment by afc163** [comment]
好像是失效了。

**Comment by hengkx** [comment]
https://github.com/cirrus-actions/rebase
这一行 不一样 不知道是不是
```diff
- uses: cirrus-actions/rebase@1.2
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/d37c16aeaf72901c05cee872a4913551142c797c

**Comment by afc163** [comment]
好了。

**Comment by hengkx** [comment]
哈哈  还是自动好

**Pull request merged**
