### PR TITLE
refactor: Anchor cssinjs

### PR DESCRIPTION
**Pull request by LongHaoo**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    change anchor to cssinjs       |
| 🇨🇳 Chinese |      anchor 转换cssinjs     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by LongHaoo** [comment]
样式对比过没有问题，除了在Fixed状态后可能存在一些宽度高度变化问题需要最后check一下

**Comment by LongHaoo** [comment]
affix的时候宽度是152px，而正确的时候应该是148px，每天在对一下Affix这个宽度怎么取的

**Comment by zombieJ** [comment]
CI 挂了，rebase 一下？

**Comment by zombieJ** [comment]
https://preview-35139-ant-design.surge.sh/components/anchor-cn/  少侠，这个样式完全不对呐。。。

**Pull request merged**
