### PR TITLE
Input.Search 支持不显示suffix

### PR DESCRIPTION
**Pull request by yoyo837**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)
Optional suffix 
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |  Input.Search的 suffix可选         |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
感觉没什么意义，不显示 suffix 就是 Input 本身了。

**Comment by yoyo837** [comment]
想能直接支持触发 onSearch

**Comment by yoyo837** [comment]
同意直接改input 支持 onSearch吗？

**Comment by yoyo837** [comment]
或者叫回车事件

**Comment by afc163** [comment]
Input 已经有 `onPressEnter`。

**Comment by yoyo837** [comment]
啊... 打扰了...

**Pull request closed without merging**
