### PR TITLE
fix: modal fit-content takes multiple line width in sum.

### PR DESCRIPTION
**Pull request by bbb169**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/42732

### 💡 Background and solution

Put title and content in one box

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Put title and content in one box
      |
| 🇨🇳 Chinese |       将title和content放在同一个盒子，icon放在左边    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 1a45318</samp>

This pull request enhances the confirm dialog component by fixing the layout and style issues. It modifies `components/modal/style/index.tsx` and `components/modal/ConfirmDialog.tsx` to adjust the width and alignment of the dialog elements.

### <samp>🤖 Generated by Copilot at 1a45318</samp>

*  Fix confirm dialog layout issue when icon size is large ([link](https://github.com/ant-design/ant-design/pull/43843/files?diff=unified&w=0#diff-d3734257bd9f28b52a331a7cc2fb5a3efd91c2fc71be29356d2fb171768ba9a3L106-R111), [link](https://github.com/ant-design/ant-design/pull/43843/files?diff=unified&w=0#diff-a27b99943336f4a3b470158edbccad703a421adf1b1453c0c006e0794c7db486R180-R183), [link](https://github.com/ant-design/ant-design/pull/43843/files?diff=unified&w=0#diff-a27b99943336f4a3b470158edbccad703a421adf1b1453c0c006e0794c7db486L314-R318), [link](https://github.com/ant-design/ant-design/pull/43843/files?diff=unified&w=0#diff-a27b99943336f4a3b470158edbccad703a421adf1b1453c0c006e0794c7db486L330))

### CODE REVIEW

**Comment by afc163** [comment]
Any backgroud about this PR?

**Comment by bbb169** [comment]
> 
还在调试，调试过了ci再链接可以嘛

**Comment by afc163** [comment]
可以先说明一下原始问题，这样说不定有更好的解法。

**Comment by bbb169** [comment]
> 可以先说明一下原始问题，这样说不定有更好的解法。

https://github.com/ant-design/ant-design/issues/42732
是这个issue，这个解法貌似不行哈哈

**Comment by bbb169** [comment]
> 可以先说明一下原始问题，这样说不定有更好的解法。

这个pr的方案应该是不行，我还试过将icon和title放在一行的div中，content放下面，但是要改动的样式太多了

**Pull request closed without merging**
