### PR TITLE
fix #13648

### LINKED ISSUE #13648: Spin wrapperClassName 设置 padding 图标不居中
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
WIN10 - Chome71 - React 16

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/8kwqrn9p8j)

### Steps to reproduce
`Spin` 的 `wrapperClassName` 设置 `padding`

### What is expected?
图标居中

### What is actually happening?
图标不居中

---
另外页面横向滚动条也出现了，实际不应该出现！

### PR DESCRIPTION
**Pull request by yoyo837**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

fix #13648 
### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by yoyo837** [comment]
`could not find a copy of typescript to link in /Users/tanghui/git/github/ant-design/node_modules/antd-tools/node_modules`

本地跑不了lint, 眯着眼睛蒙了.

**Comment by zombieJ** [comment]
直接加个 left & top  就行了吧？

**Comment by yoyo837** [comment]
@zombieJ 你的更好，我改一下。

**Comment by zombieJ** [comment]
另外，style lint 错误你可以通过 `npm run lint-fix:style` 来修复哈~

**Comment by yoyo837** [comment]
你家`ant-design`依赖安装不上，scripts用不了，所以靠蒙。

**Comment by zombieJ** [comment]
> 你家`ant-design`依赖安装不上，scripts用不了，所以靠蒙。

是网络问题吗？可以试试 cnpm

**Comment by yoyo837** [comment]
目前就是淘宝源，报 https://github.com/ant-design/ant-design/pull/15056#issuecomment-467344588，cnpm找机会试一试。

**Pull request merged**
