### PR TITLE
Common column api

### PR DESCRIPTION
**Pull request by Eating-Eating**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/29389

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      add commonColumn api for Table     |
| 🇨🇳 Chinese |    Table新增commonColumn属性      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by Eating-Eating** [comment]
能不能帮忙看一下这种改法行不行，行的话我再补测试跟其他细节

**Comment by afc163** [comment]
I don't think `commonColumn` is a necessary API.

**Comment by Eating-Eating** [comment]
> I don't think a `commonColumn` property is necessary.
> 
> Beside, `columnDefaultProps` is a better name.

thanks for your comment ,I create this pr because I just saw a issue with label  `feature request`  >.<
Whatever,I'll change name if the feature is necessary.

**Comment by zombieJ** [comment]
Not sure if this is the correct time to add this props since origin #29389 is anim to set `align`. What will other function be for the commonProps?

**Comment by jueinin** [comment]
hope for this props

**Comment by abenhamdine** [comment]
> Beside, columnDefaultProps is a better name.

+1

**Comment by Eating-Eating** [comment]
so whats going on ,to do or not to do?
我的键盘早已饥渴难耐了

**Comment by jueinin** [comment]
> so whats going on ,to do or not to do?
> 
> 我的键盘早已饥渴难耐了

do do do  老哥加油！

**Comment by hengkx** [comment]
`columnDefaultProps` is better. You can set align, width...

**Comment by Eating-Eating** [comment]
> `columnDefaultProps` or `columnProps`. You can set align, width...
ok,I'll try

**Comment by afc163** [comment]
图片

**Pull request closed without merging**
