### PR TITLE
chore: upgrade rc-dialog and rc-drawer

### PR DESCRIPTION
**Pull request by shaodahong**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Related

https://github.com/ant-design/ant-design/issues/28391
https://github.com/ant-design/ant-design/issues/28528
https://github.com/ant-design/ant-design/issues/25972
#28726
#28745

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Refactor Modal and Drawer disable container scroll logic when visible       |
| 🇨🇳 Chinese | 重构 Modal 和 Drawer 显示时禁用容器滚动的逻辑 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by xrkffgg — APPROVED** [review]

**Comment by shaodahong** [comment]
@afc163 看的几个混合多开例子都没问题

**Comment by afc163** [comment]
https://preview-28687-ant-design.surge.sh/components/drawer-cn/#components-drawer-demo-config-provider

这个例子不应该禁用全局滚动。

**Comment by yoyo837** [comment]
#28693 顺带？

**Comment by shaodahong** [comment]
> #28693 顺带？

嗯，重复了

**Comment by afc163** [comment]
补一下关联 issue 和 changelog

**Comment by shaodahong** [comment]
Done.

**Comment by afc163** [comment]
图片

始终显示滚动条时，关闭 Drawer 前会向右跳动一下。

**Comment by afc163** [comment]
好像还是有问题？https://preview-28687-ant-design.surge.sh/components/drawer-cn/#components-drawer-demo-basic-right

**Comment by shaodahong** [comment]
> > 始终显示滚动条时，关闭右侧 Drawer 前会向左跳动一下。
> 
> 好像还是有问题？https://preview-28687-ant-design.surge.sh/components/drawer-cn/#components-drawer-demo-basic-right

嗯，研究了一下发现 Drawer 以前默认用的 width，现在我换成 padding 了，我改下

**Comment by afc163** [comment]
还是有这个问题。

**Comment by afc163** [comment]
包括关闭 Modal 时，也会向左跳动一下。这里要等移出动画结束后再重置滚动条。

**Comment by shaodahong** [comment]
https://preview-28687-ant-design.surge.sh/components/drawer-cn/

这个和老的逻辑应该是一样的，动画结束后再移除也会有新的问题，基于 container 定位的一些元素没办法避免

**Comment by afc163** [comment]
屏幕拖小，对比一下下面两个对话框关闭的时候吧，preview 28687 对话框会向左跳动。

- https://preview-28687-ant-design.surge.sh/components/modal-cn/#components-modal-demo-basic
- https://ant.design/components/modal-cn/#components-modal-demo-basic

**Comment by shaodahong** [comment]
https://3x.ant.design/components/drawer-cn/

3.x 版本一样高

**Comment by afc163** [comment]
Drawer 是一直有这个问题，不过不明显。先看 Modal，是这次改坏的。

**Comment by afc163** [comment]
顺便把 rc-drawer 对 body style 修改的样式都移除吧，应该不需要了。

https://github.com/react-component/drawer/blob/f04ab339d4dc49a0a34e11878f143c7390eb5a05/src/DrawerChild.tsx#L208

**Pull request merged**
