### PR TITLE
Update index.tsx

### PR DESCRIPTION
**Pull request by henrier**
该if代码块永远不会被执行

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/commit/4a81e5584f8483ac21ba845377335c5ca1e05001

**Comment by yoyo837** [comment]
不对哦，下面这个是 RCNotification.newInstance 的回掉里面的，此时messageInstance可能已经变化

**Comment by yoyo837** [comment]
这个是正确的，不能去掉

**Comment by afc163** [comment]
不过这段代码看上去挺啰嗦的，可以优化一下。

**Comment by zombieJ** [comment]
@henrier 开新的 PR 好了，这个我先关了。

**Comment by henrier** [comment]
@zombieJ 好的

**Pull request closed without merging**
