### PR TITLE
fix(upload): props type declaration

### PR DESCRIPTION
**Pull request by kerm1it**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close [#26345](https://github.com/ant-design/ant-design/issues/26345)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Upload type declaration.  |
| 🇨🇳 Chinese | 修复上传组件类型声明。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
> Hey.
> 4.6.0 actually creates another bug (took me the whole day to trace it to here)
> I'm not quite sure what's the deal but it fucks up React.Context state management on onChange callback.

Can you provide a example?

**Comment by illusi03** [comment]
Hello, 
Thanks for develop this theme, but i have a problem with version  >= 4.6.x  on deploye docker version mode.
If i try to build in local (It's NO Error).
But i try to deploy and build in docker container, Has error. 
Downgrade on version <= 4.5.x is solved. But i want to uptodate in this package.
Thank you in advance.
Screenshot from 2020-08-25 14-07-42

**Comment by Kermit-Xuan** [comment]
Are you ensure `antd` is latest in docker container? Maybe the version of `antd` is locked in `yarn.lock`

**Comment by illusi03** [comment]
Awesome, the yarn.lock is also getting commit.
Ill try to remove that yarn.lock, Thanks for the answer. 
Really apreciated bro

**Pull request merged**
