### PR TITLE
feat: make Checkbox work in Checkbox.Group, close: #5645

### PR DESCRIPTION
**Pull request by benjycui**
Close: https://github.com/ant-design/ant-design/issues/5645

### CODE REVIEW

**Comment by benjycui** [comment]
This should be an undocumented feature until `2.10.0`.

**Comment by benjycui** [comment]
Done

**Comment by benjycui** [comment]
Updated.

**Comment by benjycui** [comment]
ping~

**Review by afc163 — APPROVED** [review]

**Comment by benjycui** [comment]
> This should be an undocumented feature until 2.10.0.

@RaoHai you don't need to mention this in change log..

**Pull request merged**
