### PR TITLE
perf: 📦 remove babel-runtime and enable @babel/runtime

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/22698

- https://github.com/react-component/checkbox/pull/193
- https://github.com/react-component/dialog/pull/191

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Remove `babel-runtime` and add `@babel/runtime` in dependencies, reduce gzipped bundle size `18.6KB`.  |
| 🇨🇳 Chinese | 移除 `babel-runtime` 并添加 `@babel/runtime` 依赖，减少 gzipped 包体积 `18.6KB`。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
少了 6KB ....

**Comment by afc163** [comment]
又少了 12KB ....

```diff
- 287.9KB
+ 275.24KB
```

https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A307200%2C%22path%22%3A%22.%2Fdist%2Fantd.min.js%22%2C%22size%22%3A281842%2C%22compression%22%3A%22gzip%22%7D%2C%7B%22maxSize%22%3A66560%2C%22path%22%3A%22.%2Fdist%2Fantd.min.css%22%2C%22size%22%3A63628%2C%22compression%22%3A%22gzip%22%7D%2C%7B%22maxSize%22%3A66560%2C%22path%22%3A%22.%2Fdist%2Fantd.dark.min.css%22%2C%22size%22%3A64924%2C%22compression%22%3A%22gzip%22%7D%2C%7B%22maxSize%22%3A66560%2C%22path%22%3A%22.%2Fdist%2Fantd.compact.min.css%22%2C%22size%22%3A63630%2C%22compression%22%3A%22gzip%22%7D%5D%2C%22repo%22%3A%22ant-design%2Fant-design%22%2C%22branch%22%3A%22remove-babel-runtime%22%2C%22commit_message%22%3A%22%22%2C%22sha%22%3A%22d3025477257bc4f1035cba2febf4e1e262117e45%22%7D

**Comment by zombieJ** [comment]
真是一大笔巨款 😼

**Comment by yoyo837** [comment]
是不是可以把CI的bundle size要求改小？

**Comment by afc163** [comment]
先不动吧，20KB 挥霍起来很快。什么时候改到 200KB 以下再改 limit。

**Pull request merged**
