### PR TITLE
Better collapsed Sider and Menu

### PR DESCRIPTION
**Pull request by afc163**
menu1

menu1

1. Add `inlineCollapsed={true|false}` prop for Menu, handle icon size, text display and submenu inside Menu, and auto tooltip for menu item.
2. Use `context` to pass collapsed prop from `Layout.Sider` to `Menu`. Don't need customized css code anymore.

close https://github.com/ant-design/ant-design/issues/6484

### CODE REVIEW

**Review by yesmeck — APPROVED** [review]

**Comment by benjycui** [comment]
其实这个场景，业务代码处理还好吧，感觉没必要集成进 antd

**Comment by afc163** [comment]
业务代码要处理太多问题，而且细节很难处理好。

**Review by benjycui — APPROVED** [review]

**Comment by dehypnosis** [comment]
Need to turn off this feature specially in touch device.

**Comment by dwgate** [comment]
Is there any way to style these tooltips?

**Comment by dehypnosis** [comment]
still cannot turn off this feature?

**Pull request merged**
