### PR TITLE
refactor: Alert use CSSMotion

### PR DESCRIPTION
**Pull request by 07akioni**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by 07akioni** [comment]
`onLeaveEnd` is not fired in test environment

**Comment by xrkffgg** [comment]
@07akioni 大佬，看看能加点点测试么

**Comment by 07akioni** [comment]
> @07akioni 大佬，看看能加点点测试么

 有一些 transitionend 相关的事件在测试环境没有触发，有啥好的方法吗？我也再想想

**Comment by zombieJ** [comment]
动画测试是一个老大难的问题 😞

**Comment by 07akioni** [comment]
> 动画测试是一个老大难的问题 😞

之前查过 Jest 能不能用 Puppeteer，并不提供这种方法。要测试就只能再配置很复杂的东西，要不就写很多奇怪代码 mock

**Comment by zombieJ** [comment]
嗯，用 domSpy 注动画事件。底层的 `rc-motion` 做一下觉得 ok，上层的也注入测试感觉意义就没那么大了。

**Pull request merged**
