### PR TITLE
feat: replace testing-lib

### PR DESCRIPTION
**Pull request by heiyu4585**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      replace to testing-lib     |
| 🇨🇳 Chinese |      替换test     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
又合并了个空 PR？

**Comment by heiyu4585** [comment]
> 又合并了个空 PR？

没合并,也是推了个空,直接给算merge了

**Comment by yoyo837** [comment]
老不习惯了。[忍者]

**Comment by heiyu4585** [comment]
> 老不习惯了。[忍者]

[忍者]

**Comment by afc163** [comment]
> 也是推了个空

本地怎么操作的？不要再这么操作了

**Pull request merged**
