### PR TITLE
fix(Modal): useModal confirm destory All error

### PR DESCRIPTION
**Pull request by yklydxtt**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a Bug fix

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/31190

### 💡 Background and solution

push the desotryFn into destroyFns
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Modal.destoryAll not working when using useModal call confirm          |
| 🇨🇳 Chinese | 修复了当使用useModal唤起confirm时，Modal.destoryAll不生效的问题          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yklydxtt** [comment]
> 来个用例？

done

**Comment by afc163** [comment]
rebase 一下 feature

**Comment by afc163** [comment]
ping @yklydxtt

**Comment by afc163** [comment]
Closing for no response, feel free to recreate a new PR.

**Pull request closed without merging**
