### PR TITLE
fix: Add type of initialValue prop to Form.List

### PR DESCRIPTION
**Pull request by Debiancc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
Follow rc-from https://github.com/react-component/field-form/blob/master/src/List.tsx#L24
and https://github.com/ant-design/ant-design/pull/27872, ant-design lost the `initialValue` prop type.
Also updated the doc

So just add it!

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |Form.List `initialValue` types are supported|
| 🇨🇳 Chinese |Form.List `initialValue` 增加类型支持|

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
文档上写的string @zombieJ

**Comment by Debiancc** [comment]
@youo837 hi 我刚刚也修了文档，我需要squash吗？

**Comment by yoyo837** [comment]
合并时再squash

**Comment by yoyo837** [comment]
请同步修改en-US

**Pull request merged**
