### PR TITLE
fix IE 11 bug

### PR DESCRIPTION
**Pull request by phoenisx**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

## Context
If `flex-basis` is not set, it is taken as `0px` as default (in IE), breaking the ui in IE 11.

### Bug:
screenshot 2019-01-28 at 3 07 11 pm

### Fix:
image 1

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by chunlea** [comment]
Sadly, this PR has broken `ant-design-list-content` in other browsers! List content with too long content will be overflow the box. Like this:

screenshot 2019-02-10 at 10 12 15 am

but what we expect should be:

screenshot 2019-02-10 at 10 13 30 am

I think maybe the reason broken in IE10 is that the PR owner used the wrong thing about List. Like the <a/>. 

screenshot 2019-02-10 at 10 14 55 am

So I hope @Shub1427 can provide a demo about what he met the bug in IE11, and then we can test it whether it's a bug of List flex or not.

But now, after this PR, all list contents in my app are broken in Chrome : (

I had to override this to `flex: 1 0;`

**Comment by Shub1427** [comment]
@chunlea You are right, I messed this css. My apologies. Will revert this PR.

P.S. - In our code-base some `inline-block` is used as a wrapper around List Meta, which messes, List in IE (when used inside a Drawer (having default `word-wrap: break-word;`)). Found this, while trying to replicate this issue in a sandbox.

**Comment by yoyo837** [comment]
@chunlea How about `flex: 1 1 auto;`

**Comment by chunlea** [comment]
@yoyo837 `flex: 1 1 auto;` works, but I think we should wait for @Shub1427 to provide a sandbox and to replicate this issue, and then we can figure out how to fix this but.

**Pull request merged**
