### PR TITLE
docs(Tag): update tag demo

### LINKED ISSUE #44008: Tag标签组件，文档中的“动态添加和删除”部分的示例代码有误。
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/pzwvfl?file=/demo.tsx)

### Steps to reproduce

Tag标签组件，文档中的“动态添加和删除”部分的示例代码有误。
```js
  useEffect(() => {
    editInputRef.current?.focus();
  }, [inputValue]);
```
示例代码中的以上代码有误，应该将 `useEffect` 依赖项从 `inputValue` 调整为 `editInputValue` ，如下：
```js
  useEffect(() => {
    editInputRef.current?.focus();
  }, [editInputValue]);
```

### What is expected?

双击修改标签，应该直接聚焦input框

### What is actually happening?

双击修改标签，打开input框，并未聚焦

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18 |
| System | Windows |
| Browser | chrome最新版 |

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [X] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #44008

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  update tag demo  |
| 🇨🇳 Chinese |  更新标签组件示例  |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 511db87</samp>

Fixed a focus issue with the tag input element in `components/tag/demo/control.tsx` by updating the `useEffect` dependency array. This resolves issue #32832.

### <samp>🤖 Generated by Copilot at 511db87</samp>

* Fix bug that causes input element to lose focus when adding multiple tags ([link](https://github.com/ant-design/ant-design/pull/44010/files?diff=unified&w=0#diff-71f7311986ed1c781a47dc64541789fc8eac0682d3369908ec75c984f36055e4L24-R24))

### CODE REVIEW

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/issues/44008#issuecomment-1664823754

**Comment by MadCcc** [comment]
这个 demo 还有两个小问题：
1. 双击 tag 不会直接 focus input
2. 缺少 margin
image

另外 input 的高度和 Tag 不一样，看起来也挺怪的

**Comment by kiner-tang** [comment]
> 这个 demo 还有两个小问题：
> 
> 1. 双击 tag 不会直接 focus input
> 2. 缺少 margin
>    image
> 
> 另外 input 的高度和 Tag 不一样，看起来也挺怪的

我一起改一下

**Comment by kiner-tang** [comment]
> > 这个 demo 还有两个小问题：
> > 
> > 1. 双击 tag 不会直接 focus input
> > 2. 缺少 margin
> >    image
> > 
> > 另外 input 的高度和 Tag 不一样，看起来也挺怪的
> 
> 我一起改一下

done.
image

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
