### PR TITLE
Use antd with create-react-app without ejecting

### PR DESCRIPTION
**Pull request by afc163**
pending for https://github.com/timarney/react-app-rewired/pull/68

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/timarney/react-app-rewired/pull/73

**Comment by mitchelldemler** [comment]
Hi @afc163, I am following your [docs](https://ant.design/docs/react/use-with-create-react-app)  in a fresh project.

I am using [react-scripts-ts](https://github.com/wmonk/create-react-app-typescript) (this seems to be recommended by Microsoft) and have got it running but fail to get the babel-plugin-import to load styles for antd components. Are there any steps I'm missing?

This is my `config-overrides.js` file:

```
const { injectBabelPlugin } = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');

module.exports = function override(config, env) {
    // do stuff with the webpack config...
    config = injectBabelPlugin(['import', {
        libraryName: 'antd',
        style: true
    }], config);
    config = rewireLess(config, env, {
        modifyVars: { "@primary-color": "#00ADEF" },
    });
    return config;
};
```

My `package.json` scripts:
```
  "scripts": {
    "start": "react-app-rewired start --scripts-version react-scripts-ts",
    "build": "react-app-rewired build --scripts-version react-scripts-ts",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-app-rewired eject"
  },

**Comment by afc163** [comment]
I don't know much about react-scripts-ts, you can dig into it and [this PR](https://github.com/ant-design/ant-design/pull/6193) may be helpful.

**Comment by WhatAKitty** [comment]
I use react-script to rebuild antd-pro

https://github.com/WhatAKitty/react-script-antd-pro

Wish to help anybody who prefer react-script.

**Comment by qinyang1980** [comment]
(create react app + typescript + antd) without eject and without using Babel.

https://github.com/qinyang1980/create-react-antd-app.git

**Pull request merged**
