### PR TITLE
feat: add en_GB localisations for form

### PR DESCRIPTION
**Pull request by morenyang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/23369

### 💡 Background and solution

I think the validation messages for form in the UK could be the same as the US...

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | add en_GB localisations for form |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by mjfwebb** [comment]
Yep they will be the same.

**Comment by yoyo837** [comment]
fork 出的不支持/rebase

**Comment by yoyo837** [comment]
Should import from en_US?

**Pull request merged**
