### PR TITLE
refactor(Menu): rewrite CC => FC

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | refactor(Menu): rewrite CC => FC |
| 🇨🇳 Chinese | refactor(Menu): rewrite CC => FC |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
- #38407

**Comment by li-jia-nan** [comment]
- 之前改过一版 #38407 当时因为v5还没发布，合并到 next 分支冲突太多了，为了减轻分支合并的压力，所以暂时 close 掉了

**Comment by afc163** [comment]
放到 feature，5.1.0 发。

**Comment by li-jia-nan** [comment]
改了

**Comment by li-jia-nan** [comment]
有点问题……我重新开一个pr

**Pull request closed without merging**
