### PR TITLE
fix: table onChange error (ant-design#33374)

### PR DESCRIPTION
**Pull request by hanclang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
来个测试用例？

**Comment by hanclang** [comment]
> 来个测试用例？

<iframe src="https://codesandbox.io/embed/pensive-leakey-soj61?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="pensive-leakey-soj61"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by afc163** [comment]
测试用例：test case，不是重现。

**Comment by hanclang** [comment]
[https://codesandbox.io/embed/pensive-leakey-soj61?fontsize=14&hidenavigation=1&theme=dark](url)

> 测试用例：test case，不是重现。

好的，我看看怎么写先😹

**Comment by hanclang** [comment]
> 来个测试用例？

加上测试用例了，不知道这么子写对不对

**Comment by afc163** [comment]
用例挂了

**Pull request closed without merging**
