### PR TITLE
fix: The main element must not appear as a descendant of the section element

### PR DESCRIPTION
**Pull request by kantuni**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
N/A

### 💡 Background and solution
The W3C Markup Validation Service returns the following error:
> The `main` element must not appear as a descendant of the `section` element.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by 07akioni** [comment]
I think in most cases, `Layout` means `main` and `LayoutContent` means `div` or `section`. In the pr, `LayoutContent`'s tagName is still `main`.

**Comment by afc163** [comment]
> Maybe change LayoutContent's tagName to div is a solution.

Fine.

**Comment by kantuni** [comment]
Should I make `Layout` use a `main` tag, and `LayoutContent` a `div`?

**Comment by kantuni** [comment]
> Should I make `Layout` use a `main` tag, and `LayoutContent` a `div`?

But in that case the following code

```jsx
<Layout>
  <Header>Header</Header>
  <Layout>
    <Sider>Sider</Sider>
    <Content>Content</Content>
  </Layout>
  <Footer>Footer</Footer>
</Layout>
```

will throw this validation error:
> A document must not have more than one **main** element that does not have the **hidden** attribute specified.

**Comment by 07akioni** [comment]
> > Should I make `Layout` use a `main` tag, and `LayoutContent` a `div`?
> 
> But in that case the following code
> 
> ```js-jsx
> <Layout>
>   <Header>Header</Header>
>   <Layout>
>     <Sider>Sider</Sider>
>     <Content>Content</Content>
>   </Layout>
>   <Footer>Footer</Footer>
> </Layout>
> ```
> 
> will throw this validation error:
> 
> > A document must not have more than one **main** element that does not have the **hidden** attribute specified.

I've read MDN docs and find out that it's better to make Layout a `div`. What I suggested before is **wrong**.  You are right.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

> The content of a <main> element should be unique to the document. Content that is repeated across a set of documents or document sections such as sidebars, navigation links, copyright information, site logos, and search forms shouldn't be included unless the search form is the main function of the page.

In most examples header and footer is in Layout, which shouldn't be a `main` element.

**Review by 07akioni — APPROVED** [review]

**Comment by kantuni** [comment]
@07akioni Should I go ahead and resolve merge conflicts?

**Comment by 07akioni** [comment]
> @07akioni Should I go ahead and resolve merge conflicts?

yes, thanks

**Review by afc163 — APPROVED** [review]

**Comment by 07akioni** [comment]
Please send this pr to feature branch. In case of `section.ant-layout` liked custom css not working anymore. And specified the dom changes in the changelog.

**Comment by afc163** [comment]
ping

**Comment by kantuni** [comment]
Sorry guys, I'm a little bit busy at the moment. Will send the PR as soon as I have a little free time.

**Review by dengfuping — CHANGES_REQUESTED** [review]
- [ ] Need to send this PR to `feature` branch.

**Comment by afc163** [comment]
Closing for no response, feel free to open another PR to feature branch.

**Pull request closed without merging**
