### PR TITLE
docs: remove v3 to v4 migration docs

### PR DESCRIPTION
**Pull request by huangkairan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      docs: remove v3 to v4 migration docs     |
| 🇨🇳 Chinese |     移除v3到v4的迁移文档      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
个人不建议删除掉. 我就还在3.x, 应该还有其他人也还在3.x

**Comment by huangkairan** [comment]
> 个人不建议删除掉. 我就还在3.x, 应该还有其他人也还在3.x
我觉得从 v3 升级至 v4 应该去看 v4 的文档，v5只维护 v4 到 v5 的改动？

**Comment by yoyo837** [comment]
> > 个人不建议删除掉. 我就还在3.x, 应该还有其他人也还在3.x
> 
> 我觉得从 v3 升级至 v4 应该去看 v4 的文档，v5只维护 v4 到 v5 的改动？

我的意思是, 旧版本升级文档在站内还可以访问到吗? 如果还能就没问题, 不应该直接从站内抹掉.

**Comment by huangkairan** [comment]
> > > 个人不建议删除掉. 我就还在3.x, 应该还有其他人也还在3.x
> > 
> > 
> > 我觉得从 v3 升级至 v4 应该去看 v4 的文档，v5只维护 v4 到 v5 的改动？
> 
> 我的意思是, 旧版本升级文档在站内还可以访问到吗? 如果还能就没问题, 不应该直接从站内抹掉.

[从 v4 到 v5](https://ant-design.antgroup.com/docs/react/migration-v5-cn) 中有跳转到 v3 到 v4 迁移文档的链接，但我发现这个链接是不可用的，我一起处理掉吧

**Comment by huangkairan** [comment]
我本地的 啥情况
image

**Pull request closed without merging**
