### PR TITLE
chore: improve ThemeSwitcher implementation

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

- [x] 主题放到 url 上，这样能分享链接。
- [x] 没必要存 localStorage 了。
- [x] 简化了 ThemeSwitcher 的数据流逻辑，直接从 location.search 上拿到具体算法给到 ConfigProvider。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     --      |
| 🇨🇳 Chinese |     --      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by MadCcc — APPROVED** [review]

**Comment by MadCcc** [comment]
dark + compact 丢了

**Comment by afc163** [comment]
我修一下

**Comment by MadCcc** [comment]
感觉可能还是要 localStorage，这个会有个人偏好设置的意味在里面

**Comment by afc163** [comment]
暗色/紧凑主题需要分享给其他人看效果的。

**Comment by MadCcc** [comment]
可以在没有 query 的时候套用 localstorage

**Comment by afc163** [comment]
> 可以在没有 query 的时候套用 localstorage

Single source of truth. 不搞复杂了。

**Comment by afc163** [comment]
> dark + compact 丢了

修改好了。

**Pull request merged**
