### PR TITLE
Radiogroup with `name`

### PR DESCRIPTION
**Pull request by djyde**
Providing a `name` property for `<RadioGroup />`, which will add `name` property to it all `input[type="radio"]` children. It will make browsers recognize the RadioGroup as a real "group".

I had finished the document and a test case.

Cheers. 🍻

### CODE REVIEW

**Comment by yesmeck** [comment]
Seems like this is a new feature, plz pr to feature-2.13.

**Comment by djyde** [comment]
@yesmeck Looks strange, should I checkout from master then PR to feature branch or checkout from feature branch then PR to feature branch?

**Comment by yesmeck** [comment]
Checkout from feature branch then PR to feature branch.

**Comment by djyde** [comment]
@yesmeck okay. It's fine now. 🎉

**Comment by djyde** [comment]
2.12.3 had released. Should I change merge target to the next version? 😅

**Comment by djyde** [comment]
2.12.3 has already to be released. Should I change the merge target to the next version? 😅

**Pull request merged**
