### PR TITLE
fix: optimize arrow style

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
优化箭头样式
1. 调整尺寸，整体宽度（加上圆角）调整为 16px，与设计稿相符
2. 调整阴影，在 placement bottom 时看起来更自然

用 html2sketch 解析后发现和设计稿尺寸差了一点
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Optimize arrow style.        |
| 🇨🇳 Chinese |     优化箭头样式。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Comment by afc163** [comment]
赞细致

**Comment by afc163** [comment]
不是 perf，是 style

**Comment by MadCcc** [comment]
> 不是 perf，是 style

style 应该是指代码格式上的优化，不影响代码运行。感觉应该 fix 更合理些

**Comment by afc163** [comment]
在 antd 里 style 一般我认为就是样式，代码风格我都作为 refactor 或 chore

**Comment by afc163** [comment]
这个语义我们自己可以定义的

**Comment by yoyo837** [comment]
可以明确一下叫`code style`?

**Pull request merged**
