### PR TITLE
fix: gapDegree=0 in Dashboard progress is now working

### PR DESCRIPTION
**Pull request by thisrabbit**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/22347

### 💡 Background and solution

Problem: API defination about `Progress` is partial wrong (the default value), and also gapDegree=0 in `type="dashboard"` won't make effect.
Fix: by polishing the API doc and updating code about `gapDeg`.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix the issue that `Dashboard Progress` won't allow gapDeg to be 0 |
| 🇨🇳 Chinese | 修复仪表盘状进度条传入 gapDeg 为 0 时仍然有缺口的问题 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/progress/demo/segment.md](https://github.com/thisrabbit/ant-design/blob/fix-progress-api/components/progress/demo/segment.md)
[View rendered components/progress/index.en-US.md](https://github.com/thisrabbit/ant-design/blob/fix-progress-api/components/progress/index.en-US.md)
[View rendered components/progress/index.zh-CN.md](https://github.com/thisrabbit/ant-design/blob/fix-progress-api/components/progress/index.zh-CN.md)

### CODE REVIEW

**Comment by thisrabbit** [comment]
Also, the default value in progrss.jsx has changed from `0` to `undefined`.

**Comment by afc163** [comment]
来个用例吧。

**Comment by thisrabbit** [comment]
> 来个用例吧。

OK, I will work on it~

**Comment by thisrabbit** [comment]
> > 来个用例吧。
> 
> OK, I will work on it~

Done. Also a question, it's weird that gapDegree only support up to 295 rather than 359 (or 360), I think it might be some issue within rc-progress. By far I have corrected the default value in API doc, and I will explore this issue in future.

**Pull request merged**
