### PR TITLE
feat(module:popconfirm): support closing based on promise

### PR DESCRIPTION
**Pull request by wzhudev**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#30839

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Popconfirm `onConfirm` supports Promise  |
| 🇨🇳 Chinese | Popconfirm 组件的 `onComfirm` 允许返回一个 Promise |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

Code with this feature to implement the same result of https://ant.design/components/popconfirm-cn/#components-popconfirm-demo-async is much shorter. So I think the issue is worth a PR.

```jsx
import { Button, Popconfirm } from 'antd';

const App = () => {
  const confirm = () =>
    new Promise(resolve => {
      setTimeout(() => resolve(), 3000);
    });

  return (
    <Popconfirm title="Title" onConfirm={confirm}>
      <Button type="primary">Open Popconfirm with Promise</Button>
    </Popconfirm>
  );
};

ReactDOM.render(<App />, mountNode);
```

I will add tests if the PR is necessary.

### CODE REVIEW

**Comment by afc163** [comment]
feature branch?

**Comment by wendellhu95** [comment]
> feature branch?

I have changed the merging target branch. I will add tests later.

**Comment by wendellhu95** [comment]
@afc163 Branch feature seems to have bug https://github.com/ant-design/ant-design/pull/30870.

**Comment by afc163** [comment]
rebase feature

**Comment by wendellhu95** [comment]
@afc163 rebased.

**Review by afc163 — APPROVED** [review]

**Pull request merged**
