### PR TITLE
fix: Affix shake when switching from hide to show

### LINKED ISSUE #37970: Tabs内有携带offsetTop属性的Affix时，切换会有残影抖动
### Reproduction link

[https://stackblitz.com/edit/react-1jxp3p?file=src/App.js](https://stackblitz.com/edit/react-1jxp3p?file=src/App.js)

### Steps to reproduce

Tabs内容项有固钉Affix组件，且Affix组件设置offsetTop，切换Tabs选项，切回该Tab项时，Affix内容在初始化时会发生抖动残影。

### What is expected?

Tabs不使用destroyInactiveTabPane时，消除Affix内容的抖动和残影。

### What is actually happening?

发生抖动残影

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by madocto**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix: #37970 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Affix shake when switching from hide to show.      |
| 🇨🇳 Chinese |   修复当 Affix 隐藏切换到显示时会出现抖动。   |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by imoctopus** [comment]
```tsx
let affixInstance: InternalAffixClass | null = null;
render(
  <AffixMounter
    getInstance={inst => {
      affixInstance = inst;
    }}
    offsetBottom={0}
  />,
);

await waitFakeTimer();
await movePlaceholder(300);

console.log(affixInstance!.state.affixStyle); // { position: 'fixed', bottom: 668, width: undefined, height: undefined }
```
hi，我想写一个测试用例，想对比滚动前后 affixStyle 的变化，但是发现 width 和 height 都是 undefined，能指导下我吗？

**Comment by afc163** [comment]
jsdom 里元素尺寸和位置都是 0，需要对相关 dom 操作方法做 mock：https://github.com/ant-design/ant-design/blob/master/components/affix/__tests__/Affix.test.tsx#L75-L81

**Comment by imoctopus** [comment]
麻烦帮忙 review 看看，该测试用例是否有意义

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
图片

**Comment by imoctopus** [comment]
done

**Pull request merged**
