### PR TITLE
Locale fa

### PR DESCRIPTION
**Pull request by amiralitaheri**
### 🤔 This is a ...

- [x] Bug fix
- [x] Internationalization

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |Fix typo in `locale/fa_IR.tsx` and add missing translations to it|
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
Please update snapshot.

**Comment by yoyo837** [comment]
And rebase pls.

**Comment by amiralitaheri** [comment]
> And rebase pls.

I used Webstorm **Rebase my github fork**  option and I think it went sideways 😅, And I don't know how to fix it. Ops...
Feel free to close the PR.

**Comment by yoyo837** [comment]
Commits should be clean.  

push -f

**Comment by amiralitaheri** [comment]
@yoyo837 I Think it's fixed now.

**Pull request merged**
