### PR TITLE
feat: add placeholder option for multiple datepicker

### LINKED ISSUE #48461: DatePicker placeholder option doesn't work in multiple mode
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/datepicker-reproduction-example-forked-y7r3lw?file=%2Findex.js)

### Steps to reproduce

Set DatePicker component multiple attribute to be true, you'll find that the placeholder doesn't display.

### What is expected?

The placeholder display normally.

### What is actually happening?

The placeholder didn't display.

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18.2.0 |
| System | MACOS 14.4.1 |
| Browser | Edge 123.0.2420.97  |

### PR DESCRIPTION
**Pull request by nova1751**
### 🤔 This is a ...

- [x] New feature
- [x] Component style update

### 🔗 Related issue link

resolve #48461

### 💡 Background and solution

The placeholder option doesn't work for multiple datepicker. I achieved this function in `rc-picker` component. Please refer to the https://github.com/react-component/picker/pull/768 This PR add some revelant style code for this feature.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix DatePicker with `multiple` to support `placeholder`.        |
| 🇨🇳 Chinese |    修复 DatePicker 配置 `multiple` 时 `placeholder` 不展示的问题。    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by nova1751** [comment]
The following video shows the effect after the code change, however I don't know how to complete this PR, becasue the dependency `rc-picker` is related to another repo. Could anyone provide some advice?

https://github.com/ant-design/ant-design/assets/97817985/14ab5831-e210-4f8f-a374-9971b88bb9f3

**Comment by nova1751** [comment]
@zombieJ @afc163 This issue has been existing for a while. Could you take a look if you have time?

**Comment by zombieJ** [comment]
> The following video shows the effect after the code change, however I don't know how to complete this PR, becasue the dependency rc-picker is related to another repo. Could anyone provide some advice?

Let me check for this.

**Comment by nova1751** [comment]
> > The following video shows the effect after the code change, however I don't know how to complete this PR, becasue the dependency rc-picker is related to another repo. Could anyone provide some advice?
> 
> Let me check for this.

Could you check this PR https://github.com/react-component/picker/pull/768 first, please?

**Comment by zombieJ** [comment]
@nova1751  I've update your PR deps. Let's wait for CI : )

**Comment by nova1751** [comment]
@zombieJ Please check this preview example, seems to be fine! https://preview-48387-ant-design.surge.sh/components/date-picker-cn#components-date-picker-demo-multiple

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
