### PR TITLE
feat: Mentions support deleting an entire item with a single delete key press

### LINKED ISSUE #47968: 1.mentions组件删除at的人可以整体删除而不是删除字
### What problem does this feature solve?

产品设计 @人名  的为整体性 删除时应整体删除

### What does the proposed API look like?

无

### PR DESCRIPTION
**Pull request by CooperHash**
…ey press

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [X] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

#47968

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  add a new props to delete item in Mention   |
| 🇨🇳 Chinese |  新增Mention组件的props         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by CooperHash** [comment]
props的命名不太规范

**Comment by CooperHash** [comment]
> 新增feat的props的命名不规范，待反馈

@afc163 pls take a look

**Comment by yoyo837** [comment]
请Rebase和解决CI报错

**Comment by yoyo837** [comment]
-f 推送

**Comment by yoyo837** [comment]
先推送，我再reopen

**Comment by CooperHash** [comment]
-f推送后，没有给这个pr新增commit，而是这样...
image

**Comment by yoyo837** [comment]
你checkout的是不是feature分支？

**Comment by CooperHash** [comment]
g..记不太清了，好像是master

**Comment by yoyo837** [comment]
那rebase时就应该 rebase upstream/master;

但是作为新增功能，你应该检出feature来修改；

**Comment by Cloud-Yao** [comment]
这个特性大概什么时候发布呢？

**Comment by CooperHash** [comment]
> 这个特性大概什么时候发布呢？

https://github.com/ant-design/ant-design/pull/48389/files#diff-70d5a1401a2836d63ffd091fbcd5e9f43de05c2f404265a51a366862e1e157b6

**Pull request closed without merging**
