### PR TITLE
translated tab's doc

### PR DESCRIPTION
**Pull request by xueqingxiao**

### CODE REVIEW

**Comment by xueqingxiao** [comment]
@afc163 @benjycui Please take a look. tslint check was failed, I have no idea about this.

**Comment by afc163** [comment]
I fixed it in master, you can rebase it.

And I can't find any demo translations in this PR.

https://github.com/ant-design/ant-design/tree/master/components/tabs/demo

**Comment by xueqingxiao** [comment]
@afc163 ok, I will add some demos

**Comment by afc163** [comment]
You don't need to open new PR, just push commits to here.

**Comment by afc163** [comment]
You can translate demos like https://github.com/ant-design/ant-design/pull/2555/files

**Comment by xueqingxiao** [comment]
ok, working on it.

**Comment by benjycui** [comment]
It seems that you create this branch on `1.x-stable`...

Could you rebase onto `master`? Thanks.

**Pull request closed without merging**
