### PR TITLE
fix(Table): Add warning when Table current is negative number

### PR DESCRIPTION
**Pull request by billfeller**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

current传值有误，出现异常结果，提供统告警提示。

current=0, pageSize=5, [1,2,3,4,5].slice(-5, 0) = []
current=-1, pageSize=5, [1,2,3,4,5].slice(-10, -5) = []

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Add warning when Table `current` is negative number. |
| 🇨🇳 Chinese | Table 当 `current` 为负数时将显示控制台警告。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
请完善Changelog，发版的时候自动化工具会读取。

**Comment by wadezhan** [comment]
已补充Changelog @yoyo837

**Comment by afc163** [comment]
Please write PR title in English.

**Comment by wadezhan** [comment]
@afc163 ok

**Pull request merged**
