### PR TITLE
feat(Input): add input ref prop

### PR DESCRIPTION
**Pull request by Tymek**
#5489

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/5489

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Add `inputRef` prop on `Input` component |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
Why need `inputRef`? Could you provides the usage case?

**Comment by Tymek** [comment]
In an library that prefers uncontrolled inputs for performance reason. Use case, with an example here: https://github.com/react-hook-form/react-hook-form/issues/271#issuecomment-525804589

**Comment by zombieJ** [comment]
antd v4 will provide high performance form management. Use ref to control input with perf consideration should be avoid since it will out of React control.

**Comment by Tymek** [comment]
I agree it should be avoided, but not forbidden. Library I referenced earlier is useful. Using `className` to import input from framework is even less "React way". Opinionated nature of antd forms will force that.

**Comment by zombieJ** [comment]
For Component level, export internal node should be avoid since it makes Component coupling and hard to refactor. In some component we provides api that can access node as event callback param or some subComponent className define to handle some edge case but its value is less than harm. For Component that not provides the api yet need to be careful. At least avoid to do that on current version since code may be refactor and internal node may change also.
In current form case, I don't think should provides `inputRef` since it already not controlled in React way, user can use `findDOMNode` to get input element.

**Comment by Tymek** [comment]
`findDOMNode` is deprecated. Should I work on introducing this feature to new version, or is it going to be rejected?

**Comment by zombieJ** [comment]
There have a [proposal](https://github.com/reactjs/rfcs/pull/97)  to replace the `findDOMNode`. Before it finalize, you can safe to use `findDOMNode`.

For this `inputRef` requirement, currently closed til if some other use case force need that.

**Comment by ManAnRuck** [comment]
@Tymek @zombieJ i am also very interested to have some kind of ref to form elements (also for TextArea) 

i want to control my nice looking antd form also with react-hook-form

**Comment by mgcrea** [comment]
I'm in the same boat, ref are an important part of the react API and I don't think a general-purpose UI library should obfuscate it. I don't see any downsides in exposing an `inputRef` prop, most other UI-library do this as well (eg. [material-ui](https://material-ui.com/api/input/)).

@zombieJ many advanced devs can't wait for v4/field-form to be production ready and want to use hooks today, not sure you should turn them away by blocking core react API usage of the lib.

**Comment by WPaczula** [comment]
I'd love to use `inputRef`/`innerRef` to focus my input as a side effect. I really don't want to add technical debt by using `findDOMnode`.

**Pull request closed without merging**
