### PR TITLE
feat: Add support for uzbek latin language

### PR DESCRIPTION
**Pull request by jonybekov**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog
Add support for uzbek latin language

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
Please contribute i18n like #21387

**Comment by jonybekov** [comment]
> Please contribute i18n like #21387

Should I update rc-pagination and rc-picker ony?

**Comment by yoyo837** [comment]
> > Please contribute i18n like #21387
> 
> Should I update rc-pagination and rc-picker ony?

https://github.com/ant-design/ant-design/pull/27028#issuecomment-705308990

**Comment by afc163** [comment]
ping @jonybekov

**Pull request closed without merging**
