### PR TITLE
fix: fix the ellipsis bug for pre element

### LINKED ISSUE #48953: Typography.Paragraph ellipsis is not expandable if used inside <pre> for multiline text
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-ellipsis-gkf7pp)

### Steps to reproduce

- create a <pre> element
- add a typography.paragraph inside with ellipsis: { rows: 2, expandable: true }
- render a long text inside the typography with multiple lines set by \n

### What is expected?

the text shows ellipsis after 2 lines and a button to expand the text

### What is actually happening?

ellipsis doesn't work

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | react 18 |
| System | macos |
| Browser | chrome |

---
If the expandable is removed, then the text has the ellipsis but there's no way to expand it.

Not sure if this should even be a new component. Use case: from a Input.TextArea, allow the user to create a multiline text. Save that on DB, and when fetching and rendering, be able to render that text in multiline as well, but be able to use an expandable ellipsis if the content is too long

### PR DESCRIPTION
**Pull request by nova1751**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #48953

### 💡 Background and solution

The css property `white-space: normal` will cause the `\n`  to not work in `pre` tag when the text is used as `MeasureText`. Removing it may be a good solution.🤔

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix the bug where the ellipsis option of `Typography` component doesn't work normally in `pre` tag        |
| 🇨🇳 Chinese |    修复 `Typography` 组件的 `ellipsis`选项在 `pre` 标签中没有正常工作的问题       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by nova1751** [comment]
After fixed:


https://github.com/ant-design/ant-design/assets/97817985/08303f78-ba04-4106-aa24-9b54e4f586ad

**Comment by nova1751** [comment]
Any progress in this PR? @zombieJ @afc163

**Comment by zombieJ** [comment]
This broken the debug demo:
截屏2024-05-31 10 43 16

**Comment by nova1751** [comment]
Oops, I rebase the master branch, which cause the PR to be closed forcely. ☹️

**Comment by zombieJ** [comment]
Seems the branch has been removed? I can not reopen the  PR.

**Comment by nova1751** [comment]
> Seems the branch has been removed? I can not reopen the PR.

Sorry for the misoperation, I opened a new one. See #49168.

**Pull request closed without merging**
