### PR TITLE
feat: adding variant props to divider

### PR DESCRIPTION
**Pull request by pinaki-08**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

There is no issue related to this. But wanted to add this feature enhancement as it resolves having to define the style of Divider. Since the css of `borderStyle` already provides `dotted` and `dashed`, it felt like a genuine use case to me.

### 💡 Background and solution

Instead of a boolean, adding a type of variant to the divider can allow the use to define the border style. The divider border style can be either solid, dashed or dotted based on the variant props. The default value is solid.

### 📝 Changelog

- This will allow user to add the divider style of `dashed`, `dotted` or `solid`. Will need to deprecate the `dashed` boolean as it provides a redundant feature to this one. (Kind of my initial contribution so open to path forward for the change log.)

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    This will allow user to add the divider style of `dashed`, `dotted` or `solid`. Will need to deprecate the `dashed` boolean |
| 🇨🇳 Chinese |  这将允许用户添加 `dashed`（虚线）、`dotted`（点线）或 `solid`（实线）的分割线样式。将需要弃用 `dashed` 布尔值。  |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by afc163 — DISMISSED** [review]

**Comment by afc163** [comment]
Could you send this PR to featurn branch?

**Comment by pinaki-08** [comment]
> Could you send this PR to featurn branch?

I changed it to be against feature branch, but since this is based on the master there are some unrelated changes as well. Let me know if I need to rebase this PR to the feature branch or not.
Thanks for the review. :)

**Comment by afc163** [comment]
Mixed other commits

**Comment by pinaki-08** [comment]
> Mixed other commits

@afc163 Do I need to change this ?

**Comment by afc163** [comment]
Yes, PR commits should be clean.

**Review by afc163 — APPROVED** [review]

**Pull request merged**
