### PR TITLE
refactor: replace deprecated `onKeyPress` with `onKeyDown` in Collapse

### LINKED ISSUE #42503: Collapse Panel is getting close on click of Enter
### What problem does this feature solve?

Normally also the collapse is getting close on click of Enter. In my Case , I have Editable Paragraph in header prop of Panel and that should be saved on click of Enter. Its getting saved also but along with that the collapse Panel is also getting closed . So here the collapse Panel should not get close on click of Enter

### What does the proposed API look like?

it Should prevent the Collapse from closing on press of Enter

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [X] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/42503

### 💡 Background and solution

Use `onKeyDown` instead of `onKeyPress` to change collapse panel active state

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | - Use `onKeyDown` instead of `onKeyPress` to change collapse panel active state <br />- Collapse support items |
| 🇨🇳 Chinese | - 使用 `onKeyDown` 替代 `onKeyPress` 来改变折叠面板的激活状态  <br /> - 折叠面板支持 items |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 7b47264</samp>

Updated `rc-collapse` dependency to fix a bug in `Collapse` component. This improves the animation and accessibility of the collapsible panels in the UI framework.

### <samp>🤖 Generated by Copilot at 7b47264</samp>

* Update the `rc-collapse` dependency to fix a bug related to the collapse animation and accessibility ([link](https://github.com/ant-design/ant-design/pull/42534/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L126-R126))

### CODE REVIEW

**Comment by yoyo837** [comment]
看上去大很多

**Comment by MadCcc** [comment]
只改了个属性名，应该是其他地方大了吧？

**Comment by yoyo837** [comment]
changelog 需要包含所有minor的修改， 这里需要补3.6.0的

**Comment by yoyo837** [comment]
> 只改了个属性名，应该是其他地方大了吧？

那，因为3.6.0的改动而大的？

**Comment by kiner-tang** [comment]
看了一下，好像 3.6.0 只有这一个更改：
- https://github.com/react-component/collapse/pull/312

需要把这个更改的 changelog 加进去吗

**Comment by yoyo837** [comment]
> 看了一下，好像 3.6.0 只有这一个更改：
> 
> * [feat: support items & add deprecated warning react-component/collapse#312](https://github.com/react-component/collapse/pull/312)
> 
> 需要把这个更改的 changelog 加进去吗

按之前的规矩，是要的

**Comment by MadCcc** [comment]
这个不能在 master 上了，得在 feature 搞了

**Comment by kiner-tang** [comment]
这个先关掉，重新提一个合到 feature:
- https://github.com/ant-design/ant-design/pull/42592

**Pull request closed without merging**
