### PR TITLE
fix(tree): add missing props and typings

### PR DESCRIPTION
**Pull request by panjiesw**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

* [x] Update TypeScript definition for the component.

Description:

Add missing props and typings for Tree and TreeNode component

- type `TreeNode` in `Tree` static property
- add missing `icon` prop in TreeNode
- add missing `showIcon` prop in Tree

### CODE REVIEW

**Comment by yesmeck** [comment]
Has been fixed in https://github.com/ant-design/ant-design/commit/a5e2020908b71c9ce380c1ea9b578e2365e671d7, thanks for your contributions.

**Comment by panjiesw** [comment]
@yesmeck Great!

Sorry for asking this, but is that going to 3.4.2 version? Any rough estimate to when it'll be released?

**Comment by yesmeck** [comment]
This weekend according to our release schedule.

**Comment by panjiesw** [comment]
Fantastic!
You people keep doing wonder with this lib, thanks!

**Pull request closed without merging**
