### PR TITLE
fix(notification): config prefixCls unsupported

### PR DESCRIPTION
**Pull request by tdida**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fix notification config prefixCls unsupported       |
| 🇨🇳 Chinese |   修复通知提醒框 config prefixCls 配置无效       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
Maybe should move to `feature` branch！

**Comment by tdida** [comment]
@yoyo837 `message` 是支持 `prefixCls` 的，而 `notification`无效，也可以算是 `Bug` 吧

**Comment by afc163** [comment]
严格点好了。

**Comment by afc163** [comment]
@tdida ping

**Comment by afc163** [comment]
1. conflicted
2. send this PR to feature branch

**Comment by tdida** [comment]
@afc163 ok

**Pull request closed without merging**
