### PR TITLE
fix disabled Upload could delete uploaded files

### PR DESCRIPTION
**Pull request by duhongjun**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by yesmeck** [comment]
Add a test please, thanks.

**Comment by valleykid** [comment]
Please add unit tests for this bugfix.

**Comment by dengfuping** [comment]
@duhongjun What's the scenario of this PR? It's strange that you cannot delete the uploaded file. And if you really want to implement the feature, you should hide the remove icon to disable this behavior by showRemoveIcon prop.

**Comment by duhongjun** [comment]
@dengfuping  Well... I think when the component is read only(disabled), the uploaded file should not  
be removed, and that is what i need ...

**Comment by dengfuping** [comment]
Close the PR because of #8677.

**Pull request closed without merging**
