### PR TITLE
feat: Pagination support `disabled` prop

### LINKED ISSUE #15986: 分页 Pagination组件 支持disable
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
页面上有操作时希望能暂时禁止分页操作

### What does the proposed API look like?
disable={true}

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

close #15986 

### 💡 Solution

Update `rc-pagination`

### 📝 Changelog

Pagination support `disabled` prop

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/pagination/index.en-US.md](https://github.com/ant-design/ant-design/blob/pagination-disabled/components/pagination/index.en-US.md)
[View rendered components/pagination/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/pagination-disabled/components/pagination/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
https://deploy-preview-16493--ant-design.netlify.com/components/pagination/#components-pagination-demo-total

https://ant.design/components/pagination/#components-pagination-demo-mini

箭头 disabled 的样式有点问题。

**Comment by zombieJ** [comment]
> 箭头 disabled 的样式有点问题。

内部按钮的 disabled className 也叫 `ant-pagination-disabled`，郁闷……

`rc-pagination` 看来需要调整一下 `className`。

**Comment by zombieJ** [comment]
Update. Please check again.

Disabled shapshot:
屏幕快照 2019-05-09 下午4 11 49

**Comment by afc163** [comment]
来个 disabled 的例子吧。

**Comment by afc163** [comment]
图片

这样好了，或者找下设计师。

**Comment by zombieJ** [comment]
看看怎么样： https://deploy-preview-16493--ant-design.netlify.com/components/pagination/#components-pagination-demo-changer

**Comment by afc163** [comment]
字色改成：`color: rgba(0,0,0, .25);` 吧。

**Review by afc163 — APPROVED** [review]

**Pull request merged**
