### PR TITLE
feat(ConfigProvider): attach DisableContext to ConfigProvider

### PR DESCRIPTION
**Pull request by xliez**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/39545

### 💡 Background and solution

目前自定义表单组件中要获取父级 Form 组件的禁用状态的话，需要从dist代码中获取 DisabledContext ，希望能将这个 API 导出以方便使用。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      attach DisableContext to ConfigProvider for accessing the API easily     |
| 🇨🇳 Chinese |     将 DisableContext 挂到 ConfigProvider 以方便调用     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
Feature branch plz.

**Comment by xliez** [comment]
> Feature branch plz.

got it

**Comment by li-jia-nan** [comment]
master 分支的 diff 带过来了

**Comment by xliez** [comment]
> master 分支的 diff 带过来了

feature 分支不同步 master 改动吗？如果不同步的话，我重新改下

**Comment by li-jia-nan** [comment]
> > master 分支的 diff 带过来了
> 
> feature 分支不同步 master 改动吗？如果不同步的话，我重新改下

改一下吧，feature 不在这里同步，后面会走批量合并

**Comment by yoyo837** [comment]
Commits should be clean.

**Comment by xliez** [comment]
unnecessary commit from master
close for a new source branch

**Pull request closed without merging**
