### PR TITLE
docs: avoid unnecessary re-render when toggle debug

### LINKED ISSUE #42173: 点击 debug 按钮就让所有 demo 都 rerender 了
May-06-2023 11-47-34

- 重现链接：https://ant.design/components/form-cn
- 预期：只影响 debug: true 的 demo。
- 现在：不仅整个页面 rerender 了，非 debug 的 demo 内部也 rerender 了。感觉非常卡。

### PR DESCRIPTION
**Pull request by PeachScript**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

Depend on https://github.com/umijs/dumi/pull/1650
Close #42173

### 💡 Background and solution

Question: all demos will be re-render when toggle debug button, since `DumiDemoGrid` does not response props change and antd must use `key` to force re-render all demos, but this behavior leads slower rendering

Solution: wait for dumi fix and remove useless `key` prop

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | --        |
| 🇨🇳 Chinese | --        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 0f4f76f</samp>

Refactored `DumiDemoGrid` component to avoid unnecessary re-rendering and improve performance. Removed `key` prop from `.dumi/theme/builtins/DemoWrapper/index.tsx`.

### <samp>🤖 Generated by Copilot at 0f4f76f</samp>

* Refactored the `DumiDemoGrid` component to avoid unnecessary re-rendering and improve performance ([link](https://github.com/ant-design/ant-design/pull/42255/files?diff=unified&w=0#diff-e250ab9968952b8b565c98a89135c6b333a4dfaa67406881265a78f047a21cf6L78-R78))
* Added a `useEffect` hook to update the `expanded` state of the demo grid when the `expandAll` prop changes ([link](https://github.com/ant-design/ant-design/pull/42255/files?diff=unified&w=0#diff-e250ab9968952b8b565c98a89135c6b333a4dfaa67406881265a78f047a21cf6L78-R78))
* Wrapped the `DumiDemoGrid` component with `React.memo` to prevent re-rendering when the props are shallowly equal ([link](https://github.com/ant-design/ant-design/pull/42255/files?diff=unified&w=0#diff-e250ab9968952b8b565c98a89135c6b333a4dfaa67406881265a78f047a21cf6L78-R78))
* Added a `showDebug` prop to the `DumiDemoGrid` component to control the visibility of the debug button ([link](https://github.com/ant-design/ant-design/pull/42255/files?diff=unified&w=0#diff-e250ab9968952b8b565c98a89135c6b333a4dfaa67406881265a78f047a21cf6L78-R78))
* Added a `useEffect` hook to update the `debug` state of the demo grid when the `showDebug` prop changes ([link](https://github.com/ant-design/ant-design/pull/42255/files?diff=unified&w=0#diff-e250ab9968952b8b565c98a89135c6b333a4dfaa67406881265a78f047a21cf6L78-R78))

### CODE REVIEW

**Comment by afc163** [comment]
现在非 debug demo 也还会 rerender。

**Comment by PeachScript** [comment]
> 现在非 debug demo 也还会 rerender。

我这里看只有 debug demo rerender 了：
Kapture 2023-05-12 at 13 34 42

对一下操作步骤是不是一致的：
1. Chrome 打开预览链接：https://preview-42255-ant-design.surge.sh/components/button-cn
2. 开启 devtool 里的 Paint flashing
3. 切换调试开关

**Comment by afc163** [comment]
得用 https://react.dev/learn/react-developer-tools 看。

截屏2023-05-12 下午5 11 59

**Comment by PeachScript** [comment]
> 得用 https://react.dev/learn/react-developer-tools 看。

get，我再看下 ❤️

**Comment by MadCcc** [comment]
Kapture 2023-05-22 at 10 07 59
现在还是会重新渲染整个 Content

原因应该是右边的 Anchor 在 `Context.tsx` 中，下面的 debug 按钮在 `DemoWrapper.tsx` 中，所以存了一个 context 在 `Context.tsx` 去控制 debug demo 显隐，会导致点击 debug 按钮时整个 Context rerender

**Comment by PeachScript** [comment]
@MadCcc 👍 整个 Context re-render 是指整个页面的组件都重新渲染过了么，且因为组件有 memo 所以 re-render 实际上没带来消耗？看速度确实是比改之前要快的

**Comment by zombieJ** [comment]
这个算是好了吗？

**Comment by PeachScript** [comment]
> 这个算是好了吗？

还没好，和闲夕聊了下 demo 要套个 memo，这两天搞下

**Comment by afc163** [comment]
这个搞完了么

**Comment by afc163** [comment]
这个搞完了么

**Comment by PeachScript** [comment]
确认完工， @MadCcc 再帮忙 review 下预览链接

**Comment by afc163** [comment]
切“展开全部代码”还会有渲染问题。

**Review by MadCcc — APPROVED** [review]

**Comment by PeachScript** [comment]
> 切“展开全部代码”还会有渲染问题。

这个应该是预期内的，展开全部代码会修改所有 demo 预览器的 props，所以 demo 预览器会发生 re-render 以响应源代码区域的切换，但 demo 区域仍然是 memo 掉的，不会 re-render

**Pull request merged**
