### PR TITLE
fix: checkbox should have line-height

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Checkbox that label not aligned with checkbox.         |
| 🇨🇳 Chinese |  修复 Checkbox 组件 label 不对齐的问题。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
> 修复 Checkbox 组件 wrapper 层没有 line-height 的问题。

这个不是问题吧，具体问题是啥？

**Comment by MadCcc** [comment]
> > 修复 Checkbox 组件 wrapper 层没有 line-height 的问题。
> 
> 这个不是问题吧，具体问题是啥？

其实就是少 line-height 了，单独打开 demo 就看到高度不对了

**Comment by afc163** [comment]
那就是修复 Checkbox 不对齐的问题。

**Review by li-jia-nan — APPROVED** [review]

**Comment by MadCcc** [comment]
image
这么看以前的确实有问题

**Pull request merged**
