### PR TITLE
style(tree-select): missing outer border in treeNode focus state

### LINKED ISSUE #45265: TreeSelect 选中项聚焦边框缺失
### Reproduction link

[https://ant.design/components/tree-select-cn#tree-select-demo-basic](https://ant.design/components/tree-select-cn#tree-select-demo-basic)

### Steps to reproduce

1. 点击输入框，展开下拉框，任意选中一项；
2. 再次点击输入框，查看选中项边框。

image

### What is expected?

选中项聚焦边框不缺失

### What is actually happening?

选中项聚焦边框缺失

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.0.0 |
| System | macOS 12.2.1 |
| Browser | Chrome 108.0.5359.124 |

### PR DESCRIPTION
**Pull request by Yuiai01**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/45265

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix missing outer border in treeNode focus state          |
| 🇨🇳 Chinese |  解决 treeNode focus 状态下外边框缺失         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at b1b2b5c</samp>

This pull request enhances the style of the `tree-select` component by passing a parameter to the style functions in `components/tree/style/index.ts` and `components/tree-select/style/index.ts`. This parameter controls the padding of the tree nodes depending on the component type.

### <samp>🤖 Generated by Copilot at b1b2b5c</samp>

*  Add `isTreeSelect` parameter to `genBaseStyle` function to adjust tree node padding ([link](https://github.com/ant-design/ant-design/pull/45267/files?diff=unified&w=0#diff-c01ae53de3785d9ccea6872587f1ebcf51ff86fd62a8570034d932e7c94baaf3R32), [link](https://github.com/ant-design/ant-design/pull/45267/files?diff=unified&w=0#diff-a96220c0f9da1159b455aa953a94877f481fb369b795771cca99d3910d880010L95-R99), [link](https://github.com/ant-design/ant-design/pull/45267/files?diff=unified&w=0#diff-a96220c0f9da1159b455aa953a94877f481fb369b795771cca99d3910d880010L164-R168), [link](https://github.com/ant-design/ant-design/pull/45267/files?diff=unified&w=0#diff-a96220c0f9da1159b455aa953a94877f481fb369b795771cca99d3910d880010R497), [link](https://github.com/ant-design/ant-design/pull/45267/files?diff=unified&w=0#diff-a96220c0f9da1159b455aa953a94877f481fb369b795771cca99d3910d880010L507-R512))
*  Pass `isTreeSelect` value from `tree-select/style/index.ts` to `tree/style/index.ts` ([link](https://github.com/ant-design/ant-design/pull/45267/files?diff=unified&w=0#diff-c01ae53de3785d9ccea6872587f1ebcf51ff86fd62a8570034d932e7c94baaf3R32), [link](https://github.com/ant-design/ant-design/pull/45267/files?diff=unified&w=0#diff-a96220c0f9da1159b455aa953a94877f481fb369b795771cca99d3910d880010R497), [link](https://github.com/ant-design/ant-design/pull/45267/files?diff=unified&w=0#diff-a96220c0f9da1159b455aa953a94877f481fb369b795771cca99d3910d880010L507-R512))

### CODE REVIEW

**Comment by afc163** [comment]
lint 挂了

**Comment by Yuiai01** [comment]
> lint 挂了

好，我改一下

**Comment by MadCcc** [comment]
这个问题没这么简单，上下的 outline 也会被 virtual list 遮住

**Comment by MadCcc** [comment]
横向应该调整 TreeSelect 的 padding

**Comment by Yuiai01** [comment]
> 这个问题没这么简单，上下的 outline 也会被 virtual list 遮住

好吧，闲夕大佬这个有 demo 或者相关的 issue 吗？

**Comment by Yuiai01** [comment]
> 横向应该调整 TreeSelect 的 padding

好

**Comment by Yuiai01** [comment]
link `virtual-list` 加上 `offset` 的修复结果如下

https://github.com/ant-design/ant-design/assets/112228030/fed8723b-f53a-45a5-bd08-3936c66d0ed9

**Review by afc163 — APPROVED** [review]

**Comment by Yuiai01** [comment]
@afc163 偏右大佬这个 pr 还需要在等等，我晚点把改动提交上来。

**Comment by afc163** [comment]
切草稿或加 `WIP`。

**Comment by Yuiai01** [comment]
> 切草稿或加 `WIP`。

好，受教了。

**Comment by afc163** [comment]
冲突了

**Comment by afc163** [comment]
ping

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/46608

**Pull request closed without merging**
