### PR TITLE
fix: timeline content style

### LINKED ISSUE #21048: bug: timeline 组件 rtl 模式下展示问题
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/timeline-cn/#components-timeline-demo-alternate](https://next.ant.design/components/timeline-cn/#components-timeline-demo-alternate)

### Steps to reproduce
- 打开链接
- 选择 RTL 模式
- 观察交替模式的右侧内容样式

### What is expected?
样式正确

### What is actually happening?
样式有误

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | The latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by xrkffgg**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/21048

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Improved Timeline component style in RTL mode |
| 🇨🇳 Chinese |  完善 Timeline 组件 RTL 模式下样式         |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
你的预览切换不了RTL，报错了。

**Comment by yoyo837** [comment]
image

像丢了一截，好奇怪。

**Comment by xrkffgg** [comment]
我这边预览可以切换 RTL，没看到报错

**Comment by yoyo837** [comment]
可能是我缓存。

**Review by yoyo837 — APPROVED** [review]

**Review by MrHeer — APPROVED** [review]

**Pull request merged**
