### PR TITLE
Update index.less

### PR DESCRIPTION
**Pull request by internet5**
空数据时，修复column return多级数据无法隐藏元素的问题

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
先让我们知道你要修复的是什么。

**Comment by internet5** [comment]
https://codepen.io/internet5/pen/dVbyRR?editors=0010
这种情况

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/33a71eb8fbef939ad9f017dc281a37cffa953054 这里应该修复了。

**Comment by internet5** [comment]
这个没修复啊，我用不是最新版本吗，有这段代码啊，那段代码 css >td>*，表示只能控制到td下面的一级，再下面就不能控制了，我发的列子里面不是明显没被隐藏吗

**Comment by afc163** [comment]
看下提交时间，主干上已修复，未发布。

**Pull request closed without merging**
