### PR TITLE
fix: Input inline allowClear style

### LINKED ISSUE #22562: Form inline模式 Input allowClear 宽度闪烁
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/daiyichutubiao-ant-design-demo-0q1us)

### Steps to reproduce
输入任意字符

### What is expected?
宽度不变

### What is actually happening?
input宽度会增加清除小图标的宽度

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13 |
| System | mac13 |
| Browser | chrome 80 |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #22562

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Input inline with `allowClear` shaking when trigger clear icon.       |
| 🇨🇳 Chinese |    修复 Input 设置 `allowClear` 内联展示时，触发清除按钮样式抖动的问题。     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by shaodahong** [comment]
还是有这个问题 https://github.com/ant-design/ant-design/pull/22574#issuecomment-603609415

**Comment by zombieJ** [comment]
唔，placeholder 的确是没什么好办法。

**Comment by shaodahong** [comment]
嗯，我也没想到，确实有点棘手

**Comment by zombieJ** [comment]
那只能搞个假的 `placeholder` 了。

**Comment by afc163** [comment]
input 搞加 placeholder 没必要啊。

**Review by shaodahong — APPROVED** [review]
先这样吧感觉，placeholder 的优先级不是很高，可以放一放

**Comment by shaodahong** [comment]
假的 placeholder 也有一些兼容性问题，太拼了

**Comment by zombieJ** [comment]
👌 那先这样吧，有 issue 再来搞。

**Pull request merged**
