### PR TITLE
docs: fix contributing docs

### PR DESCRIPTION
**Pull request by cjmafei**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

-----
[View rendered docs/react/contributing.en-US.md](https://github.com/cjmafei/ant-design/blob/mf/fix-contribute-docs/docs/react/contributing.en-US.md)
[View rendered docs/react/contributing.zh-CN.md](https://github.com/cjmafei/ant-design/blob/mf/fix-contribute-docs/docs/react/contributing.zh-CN.md)

### CODE REVIEW

**Comment by yesmeck** [comment]
看走眼了。。。原来写的没错。

**Comment by cjmafei** [comment]
原来写的我跑不了，改掉之后可以啊，是我哪里操作不当吗 @yesmeck

**Comment by yesmeck** [comment]
跑不了是报什么错？

**Comment by cjmafei** [comment]
WX20200117-143320

**Comment by yoyo837** [comment]
`npm test --watch components/input`

**Comment by yoyo837** [comment]
改掉watch不了，revert吧

**Comment by cjmafei** [comment]
npm test -- --watch dropdown-button.test.js 这样就没问题

**Comment by yesmeck** [comment]
@cjmafei 这个错跟命令本身没关系

**Pull request merged**
