### PR TITLE
docs: Update components cover

### LINKED ISSUE #24629: Overview in site
缩略图中使用的 组件样式非现有样式。

- border-radius 为 4px

---

如果不碍事，直接关了吧。

### PR DESCRIPTION
**Pull request by arvinxx**
#24629

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #24629
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/affix/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/affix/index.en-US.md)
[View rendered components/affix/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/affix/index.zh-CN.md)
[View rendered components/alert/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/alert/index.en-US.md)
[View rendered components/alert/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/alert/index.zh-CN.md)
[View rendered components/anchor/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/anchor/index.en-US.md)
[View rendered components/anchor/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/anchor/index.zh-CN.md)
[View rendered components/auto-complete/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/auto-complete/index.en-US.md)
[View rendered components/auto-complete/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/auto-complete/index.zh-CN.md)
[View rendered components/back-top/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/back-top/index.en-US.md)
[View rendered components/back-top/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/back-top/index.zh-CN.md)
[View rendered components/button/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/button/index.en-US.md)
[View rendered components/button/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/button/index.zh-CN.md)
[View rendered components/card/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/card/index.en-US.md)
[View rendered components/cascader/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/cascader/index.en-US.md)
[View rendered components/cascader/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/cascader/index.zh-CN.md)
[View rendered components/checkbox/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/checkbox/index.en-US.md)
[View rendered components/checkbox/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/checkbox/index.zh-CN.md)
[View rendered components/comment/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/comment/index.en-US.md)
[View rendered components/comment/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/comment/index.zh-CN.md)
[View rendered components/date-picker/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/date-picker/index.en-US.md)
[View rendered components/date-picker/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/date-picker/index.zh-CN.md)
[View rendered components/dropdown/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/dropdown/index.en-US.md)
[View rendered components/dropdown/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/dropdown/index.zh-CN.md)
[View rendered components/empty/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/empty/index.en-US.md)
[View rendered components/empty/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/empty/index.zh-CN.md)
[View rendered components/form/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/form/index.en-US.md)
[View rendered components/form/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/form/index.zh-CN.md)
[View rendered components/input-number/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/input-number/index.en-US.md)
[View rendered components/input-number/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/input-number/index.zh-CN.md)
[View rendered components/input/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs/components-cover/components/input/index.en-US.md)

### CODE REVIEW

**Comment by afc163** [comment]
👍

**Comment by afc163** [comment]
还有很多组件的圆角没改，比如

image

**Comment by arvinxx** [comment]
> 还有很多组件的圆角没改，比如
> 
> image

已改。 现在应该没剩了

**Comment by ycjcl868** [comment]
看起来上传用了 Bigfish UI 的 CDN

**Comment by arvinxx** [comment]
> 看起来图片上传用了 Bigfish UI 的 CDN

是的

**Pull request merged**
