### PR TITLE
feat(checkbox): adjust size based on font-size

### PR DESCRIPTION
**Pull request by int64ago**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

#7368

peek 2017-08-29 10-56

### CODE REVIEW

**Comment by afc163** [comment]
I think it is ok that just add `@checkbox-size` variable for custom needs like we discussed in #7368. The size of checkbox changes with font size is not appropriated for our design pricinple.

**Comment by benjycui** [comment]
ping~ @int64ago

**Comment by int64ago** [comment]
I don't think it's ok to add `@checkbox-size`, adjusting `font-size` && `before/after` pseudo by `@checkbox-size` may make a mess for the code

**Comment by int64ago** [comment]
BTW, size changing with font size has already been applied in some components, see [here](https://github.com/ant-design/ant-design/blob/master/components/progress/style/index.less)

**Comment by afc163** [comment]
It could have some effects if we put standalone Checkbox in other text, which could be not expected.

```jsx
<div style={{ fontSize: 24 }}>
  文字文字
  <Checkbox />  // The size of Checkbox will be affect by the `div`
</div>
```

**Comment by benjycui** [comment]
ping @int64ago

**Comment by int64ago** [comment]
@benjycui I have no idea now, closed :-)

**Comment by reverocean** [comment]
@afc163 It doesn't work for me

**Comment by MarisolH** [comment]
it doesn't work for me with <CheckboxGroup/> :/

**Comment by duchicong** [comment]
i use css to increase radio and checkbox size
```
.ant-radio-inner {
  width: 20px;
  height: 20px;

  &::after {
    width: 12px;
    height: 12px;
  }
}

.ant-checkbox-inner {
  width: 20px;
  height: 20px;

  &::after {
    width: 8px;
    height: 12px;
  }
}
.ant-radio,
.ant-checkbox {
  font-size: 20px;
}
```

**Pull request closed without merging**
