### PR TITLE
fix(steps): fix steps style

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

ref: #39088

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix steps style      |
| 🇨🇳 Chinese |     修复 Steps 组件样式     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片
改完之后反而歪了。

**Comment by afc163** [comment]
https://app.argos-ci.com/ant-design/ant-design/builds/3365/29968817 居然没测出来，不合理

**Comment by Wxh16144** [comment]
`vertical` 模式下没改到位，就关注图标去了。待会儿我补充一下

**Comment by zombieJ** [comment]
> 好像会漏 demo， @zombieJ @MadCcc @ant-design/ant-design-collaborators 这个得有人来看看。

因为基线只有一个，它比较是 v5 的 Demo 全移走了，加了 v4 Demo：
截屏2022-11-30 21 35 30

**Comment by zombieJ** [comment]
我这边看起来也是改完了反而歪了：
截屏2022-11-30 21 36 55

截屏2022-11-30 21 36 42

**Review by MadCcc — APPROVED** [review]

**Comment by afc163** [comment]
@zombieJ 不对，就是会跳 demo。

截屏2022-12-04 17 49 17

**Pull request merged**
