### PR TITLE
chore: replace "ant-" with `${defaultPrefixCls}`

### PR DESCRIPTION
**Pull request by li-jia-nan**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: replace "ant-" with ${defaultPrefixCls} |
| 🇨🇳 Chinese | 把 "ant-" 替换成 ${defaultPrefixCls} |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
> 修复 Radio 和 Checkbox 点击波纹效果的 classname 不会跟随 CP 的问题

这个问题的表象是什么？波纹效果会丢失么？

**Comment by li-jia-nan** [comment]
> 这个问题的表象是什么？波纹效果会丢失么？

不会丢失，就是 classname 不会跟随 CP：

```tsx
<ConfigProvider prefixCls="aaaa">
  <Checkbox  />
/ConfigProvider>
```

比如这个 `Checkbox` 预期的 classname 应该是 `aaaa-checkbox aaaa-wave-target`，实际上得到的是 `aaaa-checkbox ant-wave-target`

目前还没有 issue，我看到这个问题就顺手修了

**Review by afc163 — DISMISSED** [review]

**Comment by afc163** [comment]
覆盖率掉了

**Comment by li-jia-nan** [comment]
> 覆盖率掉了

我先回滚了，试了一下，这个有点问题，因为 波纹是通过 ReactDom.Render 渲染出来的，是一个新的 react 实例，拿不到 CP 上下文，所以没办法实现

**Review by afc163 — APPROVED** [review]

**Pull request merged**
