### PR TITLE
chore: bump rc-dialog version to 9.1.0

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

- ref #40852

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | feat(Modal): add onOpenChange prop |
| 🇨🇳 Chinese | 新增 onOpenChange 属性 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
`rc-image` 先更新吧

**Comment by li-jia-nan** [comment]
懂了，怪不得失败

**Comment by MadCcc** [comment]
直接让 https://github.com/ant-design/ant-design/pull/40852 更新吧

**Comment by li-jia-nan** [comment]
看到了，原来都有 PR

- https://github.com/react-component/image/pull/200

**Comment by li-jia-nan** [comment]
这个我关了

**Pull request closed without merging**
