### PR TITLE
-

### PR DESCRIPTION
**Pull request by sayuri-gi**
[[English Template / 英文模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)]

### 🤔 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 💡 需求背景和解决方案
添加了僧伽羅語

### 📝 更新日志

| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 | Added sinhalese language |
| 🇨🇳 中文 | 添加了僧伽羅語 |

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

### CODE REVIEW

**Comment by yoyo837** [comment]
Commits should be clean.

**Comment by MadCcc** [comment]
Base feature?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/36128#issuecomment-1159984288

I am considering remove other language README but Chinese and English.

**Comment by MadCcc** [comment]
> [#36128 (comment)](https://github.com/ant-design/ant-design/pull/36128#issuecomment-1159984288)
> 
> I am considering remove other language README but Chinese and English.

这是国际化相关的吧

**Comment by sayuri-gi** [comment]
> Make this PR based feature branch or make your own branch based on master

@MadCcc this PR already based on `feature` branch and that's why this contains,
image

@afc163 If has any problem then let me know

**Comment by yoyo837** [comment]
Make this PR based feature branch and rebase it again.

**Comment by sayuri-gi** [comment]
> Make this PR based feature branch and rebase it again.

Ohh, i don't understand ;/

>@MadCcc  Make this PR based feature branch or make your own branch based on master

As he said, @yoyo837 if create own branch based on master branch and submit new PR to this repository, is it all right? otherwise i don't understand what you trying say..

**Comment by afc163** [comment]
We should send this PR to feature branch.

**Comment by sayuri-gi** [comment]
> We should send this PR to feature branch.

**Pull request closed without merging**
