### PR TITLE
fix: PaginationProps ts error

### PR DESCRIPTION
**Pull request by cwjTerrace**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/32878

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   fix Pagination ts error   |
| 🇨🇳 Chinese |     修复Pagination编译时ts报错      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by jtheberge — APPROVED** [review]
thank you for the quick address!

**Comment by cwjTerrace** [comment]
@zombieJ 这个能看下吗 函数重载的问题 现在我father-build编译tsc校验通不过了

**Comment by afc163** [comment]
给个重现。

**Comment by cwjTerrace** [comment]
image
image
itemRender类型定义了2遍 这个问题已经很明显了

**Comment by cwjTerrace** [comment]
一个type是string 一个 type 是 type: 'page' | 'prev' | 'next' | 'jump-prev' | 'jump-next'

**Comment by afc163** [comment]
给重现的好处是：

1. 方便写测试用例
2. 明确场景和根源，也许有更好的修复方式

**Comment by cwjTerrace** [comment]
https://github.com/cwjTerrace/antd-4.17.0
执行npm run build报错
image

**Comment by JounQin** [comment]
是否应该改 `rc-pagination` 的类型定义然后把 `antd` 里的 `itemRender` 移除？

**Comment by afc163** [comment]
@JounQin 这样更好 👍

**Comment by JounQin** [comment]
@afc163 See https://github.com/react-component/pagination/pull/356

**Pull request closed without merging**
