### PR TITLE
Translate layout specification

### LINKED ISSUE #3964: English docs for layout
Can you provide the English version of the [layout ](https://ant.design/docs/spec/layout) docs, they are so nice in mobile devices but I don't understand it!

### PR DESCRIPTION
**Pull request by GrayChoi**
Close: #3964

---

First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by GrayChoi** [comment]
#3964

**Comment by GrayChoi** [comment]
Done.

**Comment by afc163** [comment]
@visvadw @waywardmonkeys @manV @kvetoslavnovak Could you help us to review this?

**Review by afc163 — APPROVED** [review]

**Comment by visvadw** [comment]
Sure, I'll take a look for a quick review.

**Pull request merged**
