### PR TITLE
[v5] feat: add uz_UZ locale

### PR DESCRIPTION
**Pull request by nodkz**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Add uz_UZ locale  |
| 🇨🇳 Chinese |   添加 uz_UZ 语言环境   |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
feature branch

**Comment by yoyo837** [comment]
Please send PR to `feature` branch, and rebase upstream.

**Comment by afc163** [comment]
@nodkz ping

**Comment by nodkz** [comment]
Sorry gor the delay

I'll do it tomorrow.

**Comment by nodkz** [comment]
@afc163 Some minor changes were introduced in v5:feature branch, so recreated locale from scratch in new PR https://github.com/ant-design/ant-design/pull/39556

**Pull request closed without merging**
