### PR TITLE
fix: tree switch bg height

### LINKED ISSUE #50255: ```Tree```: draggable and expandable icons are not vertically aligned
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/vitejs-vite-5hykus?file=src%2FApp.tsx)

### Steps to reproduce

Render the `Tree` component and use the `titleRender` property to render any element that exceeds the normal height of the Tree row.
Screenshot 2024-08-05 at 16 00 02

### What is expected?

The draggable and expandable icons should be vertically aligned.

### What is actually happening?

Draggable and expandable icons are not vertically aligned.

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix #50255

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Tree switcher position not ping at top when title break the line.      |
| 🇨🇳 Chinese |     修复 Tree 展开按钮在标题折行时没有顶上对齐的问题。     |

### CODE REVIEW

**Comment by crazyair** [comment]
像这个，就可以写 debug demo，截图，避免后续出现

**Comment by crazyair** [comment]
image

换行的会不会有问题

**Comment by zombieJ** [comment]
> 像这个，就可以写 debug demo，截图，避免后续出现

现在看也是这样子的，它是 hover 才能发现区别

**Comment by crazyair** [comment]
> > 像这个，就可以写 debug demo，截图，避免后续出现
> 
> 现在看也是这样子的，它是 hover 才能发现区别

这个 demo 不需要 hover 也能展示，就用这个 demo 加个 debug，防止后续出现
image

**Review by afc163 — DISMISSED** [review]

**Comment by afc163** [comment]
不对，diff 有问题。

**Comment by crazyair** [comment]
> 不对，diff 有问题。

刚想说

**Comment by zombieJ** [comment]
> 不对，diff 有问题。

现在知道为什么需要拉长了

**Comment by zombieJ** [comment]
switch 本身需要划线，所以给 switch 加个伪类来实现 hover 包包的效果。

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
