### PR TITLE
Fix typescript compile error

### PR DESCRIPTION
**Pull request by ztplz**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?
https://github.com/ant-design/ant-design/issues/16805

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
我感觉其他的也会有类似问题  只不过暂时没人提

**Comment by afc163** [comment]
描述一下什么问题。

**Comment by ztplz** [comment]
image

**Comment by zy410419243** [comment]
似乎修过了 https://github.com/ant-design/ant-design/issues/16805

**Comment by ztplz** [comment]
@zombieJ  ci挂了

**Comment by ztplz** [comment]
@zy410419243 不是一样的 下面还有个 我们直接
image
这样用typeof编译的时候挂了

**Pull request merged**
