### PR TITLE
Adding both RTL and LTR support

### PR DESCRIPTION
**Pull request by sepiddd**
### 🤔 This is a 

- [x] New feature
- [ ] Site / document update
- [ ] Bug fix
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

1. We had an issue with RTL direction for ant design. After that, we decided to change the source code in order to have this feature.
2. I've created a mixins file(direction.less) that contains lots of helpful mixins which handle the directions with variables. Also, I've added 3 variables to enhance the workflow to default.less file.

`@dir: 'rtl';`
`@main-website-align: 'right';`
`@main-website-idir-align: 'left';`

If you change the values of the variables, you will have your indeed direction.

### 📝 Changelog

There is no need to change anything on the user side.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc not needed
- [x] Demo is updated
- [x] TypeScript definition not needed
- [x] Changelog not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
Please check #19380, is it completely duplicated?

**Comment by sepiddd** [comment]
Hi,

They are almost the same.

**Comment by sepiddd** [comment]
> Please check #19380, is it completely duplicated?

Maybe they are almost the same, but I've handled it by `less` mixins, not by `ConfigProvider`.

**Comment by afc163** [comment]
Duplicate of #19380

**Comment by yoyo837** [comment]
Thx for your PR; it should be noted that the guy has been working hard for a long time with this in #19380.

**Comment by sepiddd** [comment]
> Thx for your PR. it should be noted that the guy has been working hard for a long time with this in #19380.

I understand it and I didn't know that anyone was working on this issue. It was my challenge for about 3 years and I have fixed it temporarily by building and replaced `dist, lib` and `es` in `node_modules` folders every time to use them fine. Now, what should we do?

**Comment by yoyo837** [comment]
You should let us know as soon as possible that you are working on it. Now, unless the Owner supports your `css` solution and abandons the `ConfigProvider` solution, we can only turn off your PR and sincerely thank you. Or the `ConfigProvider` solution fails and eventually returns to your solution in the end.

**Comment by yoyo837** [comment]
Whether this PR is accepted or not, it should be change target branch to 4.0-prepare, just like #19380.

**Pull request closed without merging**
