### PR TITLE
Timeline with fragment

### PR DESCRIPTION
**Pull request by etherreals**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

If you wrap a last < Timeline.Item > with the < Fragment >, it won't add 'last class name' to the last item, because the last item is the < Fragment > and it will show a line after the last element (see attached screenshot)
https://codesandbox.io/s/priceless-bush-btnl4
img

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by abenhamdine** [comment]
why would wrap a Timeline.Item within a fragment ?

**Comment by Kapiroska** [comment]
> why would wrap a Timeline.Item within a Fragment ?

Why not?
Project which I work with has some bunch of timelines with conditions in last items
I have to render them as array of Timeline.Item and pass key prop in each item because I can't use Fragment

**Comment by afc163** [comment]
ci broken

**Comment by Kapiroska** [comment]
I have no clue why it's broken
The tests are passed on local
Could you help me with it?

**Comment by afc163** [comment]
conflicted

**Comment by afc163** [comment]
ping @Kapiroska

**Comment by afc163** [comment]
ping @Kapiroska

**Comment by afc163** [comment]
close for no response

**Pull request closed without merging**
