### PR TITLE
 feat: Alert added `iconType` to support custom icon

### PR DESCRIPTION
**Pull request by minwe**

### CODE REVIEW

**Comment by benjycui** [comment]
Please clean your PR, thanks.

**Review by afc163 — CHANGES_REQUESTED** [review]
Mixed up other commits

**Comment by yesmeck** [comment]
Ping @minwe

**Comment by minwe** [comment]
@yesmeck What should I do?

**Comment by yesmeck** [comment]
Clean your commits.

**Comment by minwe** [comment]
@yesmeck done.

**Pull request merged**
