### PR TITLE
feat: add Irish(ga_IE) locale for 3.x

### PR DESCRIPTION
**Pull request by AbhijeetGaware**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
image

**Comment by fireairforce** [comment]
ci又挂了，要不rebase一下？

**Comment by yoyo837** [comment]
> ci又挂了，要不rebase一下？

他这个完成后是需要更新snap的。

**Comment by AbhijeetGaware** [comment]
> The Ci is failed,maybe you need to `rebase`?

@yoyo837  okay.

**Comment by AbhijeetGaware** [comment]
> > ci又挂了，要不rebase一下？
> 
> 他这个完成后是需要更新snap的。

@yoyo837  will you tell me please  i updated 3 files still its showing unsuccessful

**Comment by AbhijeetGaware** [comment]
Screenshot 2020-06-07 at 2 52 43 PM

**Comment by afc163** [comment]
1.  Need a proper PR title.
2. fill the PR content.
3. Fix ci.

**Comment by yoyo837** [comment]
remove node_modules and package-lock.json or yarn.lock, reinstall it

then, run

npm run test — -u

**Comment by AbhijeetGaware** [comment]
> npm run test — -u

i removed node_Modules and package-lock.json and fired npm run test
Screenshot 2020-06-07 at 5 16 45 PM

**Comment by afc163** [comment]
Please use **space** in PR title.

**Comment by yoyo837** [comment]
npm run test -- -u

**Comment by AbhijeetGaware** [comment]
> `npm run test -- -u`

okay @yoyo837

**Comment by AbhijeetGaware** [comment]
> `npm run test -- -u`

i  fired this command and one file is modified before showing error 4 now only 1 will you tell me please what will be the next about ci error  thanks

**Comment by AbhijeetGaware** [comment]
image

**Comment by yoyo837** [comment]
Please rebase from upstream.

**Comment by AbhijeetGaware** [comment]
> Please rebase from upstream.

i tried rebase but nothing is changing  will you provide me steps.
Screenshot 2020-06-08 at 4 52 59 PM

**Comment by yoyo837** [comment]
Show me your `git remote -v` first.

**Comment by AbhijeetGaware** [comment]
@yoyo837   git log currant branch showing like this...
Screenshot 2020-06-08 at 4 56 12 PM

**Comment by AbhijeetGaware** [comment]
> Show me your `git remote -v` first.

okay wait please

**Comment by AbhijeetGaware** [comment]
Screenshot 2020-06-08 at 4 58 42 PM

**Comment by yoyo837** [comment]
1. checkout `3.x-stable`
2. `git fetch upstream`
3. `git rebase upstream/3.x-stable`
4. `git push --force`     // base branch
5. checkout `addLocale3.xga_IE`;
6. `git rebase 3.x-stable`
7. `git push --force`     // current workspace branch

**Comment by AbhijeetGaware** [comment]
> 1. checkout `3.x-stable`
> 2. `git fetch upstream`
> 3. `git rebase upstream/3.x-stable`
> 4. `git push --force`     // base branch
> 5. checkout `addLocale3.xga_IE`;
> 6. `git rebase 3.x-stable`
> 7. `git push --force`     // current workspace branch

Thank You

**Comment by AbhijeetGaware** [comment]
@yoyo837 its showing same error again 😒

**Comment by yoyo837** [comment]
Some different results.
```
npm antd-3.26.17.tgz
{ [Error: EACCES: permission denied, mkdir '/tmp/output/antd']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/tmp/output/antd' }
Done in 1780.89s.
```
@afc163 Need help.

**Comment by afc163** [comment]
closed in #24849

**Comment by AbhijeetGaware** [comment]
> closed in #24849

Thank you so much @afc163  & @yoyo837  where i can see 3.x version added in locale ? in antd-design/releases or ☺️

**Comment by AbhijeetGaware** [comment]
@afc163  will you tell me please how much time it will take to release new 3.x-version ???

**Comment by yoyo837** [comment]
> @afc163 will you tell me please how much time it will take to release new 3.x-version ???

May be on this weekend.

**Comment by AbhijeetGaware** [comment]
@yoyo837 Thanks.

**Comment by AbhijeetGaware** [comment]
@yoyo837 could you tell me please today when  can i see the release 3.x-version ? Thanks

**Comment by yoyo837** [comment]
I can't, you can watching github releases.

**Comment by AbhijeetGaware** [comment]
> I can't, you can watching github releases.

Okay Thanks 😌

**Pull request closed without merging**
