### PR TITLE
Fix InputProps supports data attributes

### PR DESCRIPTION
**Pull request by GitKou**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Ts Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/34409

### 💡 Background and solution

1. A ts-error occurs when add data-* attributes in a  InputProps type object as below:
image
image
2. add  data-* attributes support for InputProps, and convert the index.test.js to index.test.tsx for ts type test

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Define data-* attribute in InputProps object is now allowed        |
| 🇨🇳 Chinese | 现在允许在inputProps的对象中定义data-*属性         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️
image

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by mellis481** [comment]
@afc163 This PR added a new **required** property to the Input component's props interface, correct?  If so, this would be a breaking change, but was just released in a patch.

**Comment by MadCcc** [comment]
> @afc163 This PR added a new **required** property to the Input component's props interface, correct? If so, this would be a breaking change, but was just released in a patch.

It's not required, you can ignore prop with "data-" prefix.

**Comment by ramen-curator** [comment]
image
@GitKou How can I fix it?
when I update to 4.19.2, it's showing a error like this image. 

version:
typescript: 3.9.10
antd:4.19.2

tsconfig:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "outDir": "./dist",
    "declaration": true,
    "jsx": "react"
  },
  "include": [
    "types",
    "src"
  ]
}
```

**Comment by GitKou** [comment]
> image @GitKou How can I fix it? when I update to 4.19.2, it's showing a error like this image.
> 
> version: typescript: 3.9.10 antd:4.19.2
> 
> tsconfig:
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es5",
>     "lib": [
>       "dom",
>       "dom.iterable",
>       "esnext"
>     ],
>     "allowJs": true,
>     "skipLibCheck": true,
>     "esModuleInterop": true,
>     "allowSyntheticDefaultImports": true,
>     "strict": false,
>     "forceConsistentCasingInFileNames": true,
>     "module": "esnext",
>     "moduleResolution": "node",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true,
>     "outDir": "./dist",
>     "declaration": true,
>     "jsx": "react"
>   },
>   "include": [
>     "types",
>     "src"
>   ]
> }
> ```

Sorry, I can't reproduce your error. 

But I recommend you to try updating your TypeScript version. Only since v4.4 supports index signatures that include pattern template literals, as implemented in [microsoft/TypeScript#44512](https://github.com/microsoft/TypeScript/pull/44512). 

And I don't think type checking for node_modules is necessary, maybe you should add `"exclude": ["node_modules" ...]"` in your  `tsconfig.json`

**Comment by ramen-curator** [comment]
> Sorry, I can't reproduce your error.
> 
> But I recommend you to try updating your TypeScript version. Only since v4.4 supports index signatures that include pattern template literals, as implemented in [microsoft/TypeScript#44512](https://github.com/microsoft/TypeScript/pull/44512).
> 
> And I don't think type checking for node_modules is necessary, maybe you should add `"exclude": ["node_modules" ...]"` in your `tsconfig.json`

Thank you so much for your suggestion!

**Comment by ylb0423** [comment]
Maybe you can try update react-script

**Comment by ylb0423** [comment]
Maybe you can try updating react-script

**Pull request merged**
