### PR TITLE
test: add test coverage

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | test: add test coverage |
| 🇨🇳 Chinese | test: add test coverage |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
好像没变

**Comment by li-jia-nan** [comment]
> 好像没变

这个有点奇怪，我看了一下之前的 test 代码，那个 if 应该是已经测到了的，我再研究一下

**Comment by li-jia-nan** [comment]
> 好像没变

QQ20221013-164540@2x
QQ20221013-164528@2x
QQ20221013-164558@2x

可恶啊，本地都打印出来了，明明走进这个分支了，不知道为啥跑完 CI 还是红的

**Comment by li-jia-nan** [comment]
> 好像没变

QQ20221013-174428@2x
QQ20221013-174444@2x

下面那个 if 也是一样的情况，本地明明走进这个分支了，跑完 CI 还是红的，神奇～

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
