### PR TITLE
style(slider): extend the width of rail

### PR DESCRIPTION
**Pull request by MuxinFeng**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

[issue](https://github.com/ant-design/ant-design/issues/40288)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Expand the length of the track, mainly by adding the length of dot      |
| 🇨🇳 Chinese |   扩大轨道的长度，主要是加上了 dot 的长度        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
I don't think this is the best solution. Maybe make dot clickable is better.

**Comment by MuxinFeng** [comment]
I think the slide event only acts on `rail`, and `mark` is just used to expand the style

**Comment by MuxinFeng** [comment]
I think the slide event only acts on `rail`, and `mark` is just used to expand the style.

**Comment by MuxinFeng** [comment]
fix by https://github.com/ant-design/ant-design/pull/40679

**Pull request closed without merging**
