### PR TITLE
Tabsbugfix

### PR DESCRIPTION
**Pull request by oldturkey**
if tabs type ="editable-card",if children has falsy value ,we will get error message,so we should fix it in tabs.
https://codesandbox.io/s/lively-glade-jmg5s here is error info

### CODE REVIEW

**Comment by oldturkey** [comment]
@afc163 上次说的pr~

**Review by zombieJ — COMMENTED** [review]
Use isValidate instead.  And test case.

**Comment by oldturkey** [comment]
> Use isValidate instead. And test case.

改动没有效果么？

**Comment by oldturkey** [comment]
> Use isValidate instead. And test case.

inValidate？

**Comment by oldturkey** [comment]
> Use isValidate instead. And test case.

i test it in this project demo，
That's all right.

**Comment by oldturkey** [comment]
i test it in this project demo，
That's all right. @zombieJ

**Comment by zombieJ** [comment]
Use `React.isValidElement(child)` instead of `if (child)` directly.

**Comment by oldturkey** [comment]
> Use `React.isValidElement(child)` instead of `if (child)` directly.

ok，thank you，get new knowledge

**Pull request closed without merging**
