### PR TITLE
docs: fix the wrong way to import react-dnd-html5-backend

### PR DESCRIPTION
**Pull request by njzydark**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix the problem that the table drag and drop demo and the draggable tabs demo fail to run |
| 🇨🇳 Chinese | 修复表格拖拽demo和可拖拽标签demo运行失败的问题 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/table/demo/drag-sorting.md](https://github.com/njzydark/ant-design/blob/patch-1/components/table/demo/drag-sorting.md)

### CODE REVIEW

**Comment by afc163** [comment]
3.x docs use old `react-dnd-html5-backend` version, it will break.

**Comment by njzydark** [comment]
> 3.x docs use old `react-dnd-html5-backend` version, it will break.

The codesandbox demo run Failed

**Comment by afc163** [comment]
You should upgrade `react-dnd-html5-backend` and `react-dnd` version too.

**Comment by njzydark** [comment]
> You should upgrade `react-dnd-html5-backend` and `react-dnd` version too, ci broken now.

updated

**Pull request merged**
