### PR TITLE
Allow breadcrumb component in PageHeader

### PR DESCRIPTION
**Pull request by gepd**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/24217

### 💡 Background and solution

Currently you can only pass breadcrumb properties to the PageHeader component, but not the component itself. This will allow to have both options

### 📝 Changelog

PageHeader accept a `<Breadcrumb />` component  as prop

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | allow to pass a `<Breadcrumb />` component in the `breadcrumb` prop |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
push -f

**Comment by gepd** [comment]
@yoyo837 can you help me?
I have filled the change log in the PR and I've a change in the type of  the ´breadcrumb´ prop, how shoud I push that change to this PR?

**Comment by yoyo837** [comment]
Rebase again, and push -f

**Comment by yoyo837** [comment]
I can't reopen this, pls open a new one.

**Comment by gepd** [comment]
Thanks I'll open a new one
Does the error `The path .github/ or scripts/ is only maintained by team members.` is because something I did wrong?

**Pull request closed without merging**
