### PR TITLE
chore: merge master into feature

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [x] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: merge master into feature |
| 🇨🇳 Chinese | chore: merge master into feature |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
> `./dist/antd.min.js`	330.63 KB (-1.64 KB 🔽)
> `./dist/antd-with-locales.min.js`	376.45 KB (-1.66 KB 🔽)

？？？

**Comment by yoyo837** [comment]
rollback 的那个吧

**Comment by li-jia-nan** [comment]
> rollback 的那个吧

哦哦，那没问题

**Review by yoyo837 — APPROVED** [review]

**Review by crazyair — APPROVED** [review]

**Comment by yoyo837** [comment]
image diff 符合预期 https://github.com/ant-design/ant-design/pull/46748#issuecomment-1874034681

**Pull request merged**
