### PR TITLE
Add Vietnamese localization support

### PR DESCRIPTION
**Pull request by pnghai**
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you propose PR to correct branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by benjycui** [comment]
Oops...... you should not mix others' commits into your PR.

**Comment by pnghai** [comment]
@benjycui I'm very sorry. I'm confused. As I've already commit to master branch, should I change request to master branch? Or should I revert and work on feature 2.10 branch?

**Comment by afc163** [comment]
You should checkout from and PR to `feature-2.10`.

**Comment by benjycui** [comment]
It's fine to PR to master, for we will publish a minor version this week.

**Comment by pnghai** [comment]
@benjycui Thank you very much.

**Pull request merged**
