### PR TITLE
docs: improve api type docs

### PR DESCRIPTION
**Pull request by hengkx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   improve api type docs.        |
| 🇨🇳 Chinese |   优化api类型定义。        |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/alert/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/alert/index.en-US.md)
[View rendered components/alert/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/alert/index.zh-CN.md)
[View rendered components/anchor/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/anchor/index.en-US.md)
[View rendered components/anchor/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/anchor/index.zh-CN.md)
[View rendered components/breadcrumb/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/breadcrumb/index.en-US.md)
[View rendered components/breadcrumb/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/breadcrumb/index.zh-CN.md)
[View rendered components/card/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/card/index.en-US.md)
[View rendered components/card/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/card/index.zh-CN.md)
[View rendered components/collapse/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/collapse/index.en-US.md)
[View rendered components/collapse/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/collapse/index.zh-CN.md)
[View rendered components/comment/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/comment/index.en-US.md)
[View rendered components/comment/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/comment/index.zh-CN.md)
[View rendered components/descriptions/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/descriptions/index.en-US.md)
[View rendered components/descriptions/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/descriptions/index.zh-CN.md)
[View rendered components/drawer/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/drawer/index.en-US.md)
[View rendered components/drawer/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/drawer/index.zh-CN.md)
[View rendered components/empty/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/empty/index.en-US.md)
[View rendered components/empty/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/empty/index.zh-CN.md)
[View rendered components/form/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/form/index.en-US.md)
[View rendered components/form/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/form/index.zh-CN.md)
[View rendered components/input/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/input/index.en-US.md)
[View rendered components/input/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/input/index.zh-CN.md)
[View rendered components/layout/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/layout/index.en-US.md)
[View rendered components/layout/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/layout/index.zh-CN.md)
[View rendered components/list/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/list/index.en-US.md)
[View rendered components/list/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/list/index.zh-CN.md)
[View rendered components/menu/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/menu/index.en-US.md)
[View rendered components/menu/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/menu/index.zh-CN.md)
[View rendered components/message/index.en-US.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/message/index.en-US.md)
[View rendered components/message/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/improve-docs/components/message/index.zh-CN.md)

### CODE REVIEW

**Comment by hengkx** [comment]
image
 这个东西 怎么 让他 重新检测

**Comment by hengkx** [comment]
https://github.com/zeke/semantic-pull-requests/issues/108 
Temporarily not supported.

**Comment by hengkx** [comment]
@xrkffgg  
image 这个有问题

**Review by xrkffgg — APPROVED** [review]

**Comment by xrkffgg** [comment]
> image
> 这个东西 怎么 让他 重新检测

再 commit 一下，或者 force 一下，commit 信息规范就不会报错

**Comment by yoyo837** [comment]
> @xrkffgg
> image 这个有问题

昨天有人改过，rebase一下

**Comment by hengkx** [comment]
rebase应该 没有 还没有解决，我拉去 最新分支 改的

**Comment by yoyo837** [comment]
嗷，在这 #27033

**Comment by yoyo837** [comment]
commit 也需要像PR title一样 语义

**Comment by hengkx** [comment]
最终 合过去了 就是 一条记录😅。。。。。。

**Pull request merged**
