### PR TITLE
refactor: picker trigger version

### LINKED ISSUE #38548: SSR style conflict will makes DatePicker dropdown flick in Firefox
### Reproduction link

[https://preview-38540-ant-design.surge.sh/~demos/components-date-picker-demo-range-picker/](https://preview-38540-ant-design.surge.sh/~demos/components-date-picker-demo-range-picker/)

Multiple `@keyframe` with same name will makes animation not work as expect in Firefox. The dumi plugin extracts the `<style />` as css file which makes parse issue. We should provide a static way for handle this in `@ant-design/cssinjs`.

### Steps to reproduce

Open week range picker.

### What is expected?

No flick

### What is actually happening?

Flick

| Environment | Info |
| --- | --- |
| antd | 5.0.0-beta.2 |
| React | latest |
| System | IOS |
| Browser | Firefox |

### LINKED ISSUE #38686: Date picker is laggy
### Reproduction link

[https://ant.design/components/date-picker](https://ant.design/components/date-picker)

### Steps to reproduce

Click on any date picker, especially the range picker there is a huge lag in the dropdown

### What is expected?

should be smooth like v4

### What is actually happening?

animation lag

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | web |
| Browser | chrome |

### LINKED ISSUE #40104: Datepicker. TreeSelect, Select等 slideUpIn  slideUpOut动画 在safari下聚焦，失焦动画问题、收起时闪烁，感观上多次播放，展开收起动画；
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

safari下，直接访问官网 日期组件, treeselect,select等组件，点击展示，收起

### What is expected?

修复动画效果

### What is actually happening?

动画闪烁

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2 |
| System | mac |
| Browser | safari 16.1 |

---
safari全系版本，

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/38686
close https://github.com/ant-design/ant-design/issues/40104
close https://github.com/ant-design/ant-design/issues/38548

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
范围日期选择器，点击 end date 时，面板会漂移

**Review by li-jia-nan — APPROVED** [review]

**Comment by yoyo837** [comment]
最近项目推的挺快啊. minor 全上 master 了 😋

**Comment by li-jia-nan** [comment]
ci 挂的看的我着急，直接切分支去帮忙更新 snap 了😋

**Comment by afc163** [comment]
changelog 请好好写下。

**Comment by afc163** [comment]
漏了个 https://github.com/ant-design/ant-design/issues/39222

**Pull request merged**
