### PR TITLE
add `lib/**/style/*` as sideEffects

### LINKED ISSUE #10190: 3.4.2 "sideEffects: false" option causes site to render improperly
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.2

### Environment
webpack 4.6.0

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
With 3.4.2 I notice antd components CSS doesn't load on my production site. If I edit node_modules/antd/package.json and remove the line "sideEffects: false" it goes back to normal.

My build makes use of babel-plugin-import, MiniCssExtractPlugin, less-loader to build the css

The development site with hot-reloading works fine, but when i build the production site it looks like no antd css loads at all

excerpt from webpack.prod.js
```
{
        test: /\.(css|less)$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          {
            loader: 'less-loader',
            options: {
              modifyVars: antdTheme,
              javascriptEnabled: true,
            },
          },
        ],
      },
```

with 3.4.1 a "yarn build" will produce a vendors.js and vendors.css, but with 3.4.2 the vendors.css does not get generated at all

### What is expected?
The production build worked in 3.4.1 and also works if i remove "sideEffects: false" from node_modules/antd/package.json

### What is actually happening?
unknown

---

### PR DESCRIPTION
**Pull request by whtsky**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

fix #10190

### CODE REVIEW

**Comment by Kingwl** [comment]
it's very helpful to me!

**Comment by mcdyzg** [comment]
@yutingzhao1991 babel-plugin-import 改为
```
['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }]
```
确实能解决，3.4.4还会不会改了这个问题？
还是说以后都指定`libraryDirectory: 'es'`了。

**Comment by yesmeck** [comment]
@mcdyzg 会改，不过  webpack 3 以上建议用 es 目录，可以有 tree shaking.

**Comment by mcdyzg** [comment]
@yesmeck 已经使用babel-plugin-import按需加载单独组件了，换成`libraryDirectory: 'es'`还会再对子组件tree-shaking一次吗？

**Comment by yesmeck** [comment]
会

**Pull request merged**
