### PR TITLE
sort imports

### PR DESCRIPTION
**Pull request by ztplz**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [x] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

1. Describe the source of requirement, like related issue link.
https://github.com/ant-design/ant-design/issues/14895

2. Describe the problem and the scenario.

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description

2. Chinese description (optional)

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
用sort import自动排的

**Comment by ztplz** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-416688000

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design-pro/issues/2090
https://github.com/ant-design/ant-design-pro/issues/2114

**Comment by zombieJ** [comment]
文件好多，加个 lint script 提交了自动排？

**Comment by ztplz** [comment]
把那个warning禁了也行  其实没什么影响的

**Comment by afc163** [comment]
规律是啥？

**Comment by ztplz** [comment]
用的eslint的默认规律 
https://github.com/amatiasq/vsc-sort-imports

**Comment by afc163** [comment]
和 https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/order.md 好像不太一样。

**Comment by ztplz** [comment]
不如过滤下warning？
image
我看很多人都是直接把这个warning过滤了  这个warning其实没什么影响 只是个warning而已

**Comment by zombieJ** [comment]
@ztplz ，是现在这个自动排完的 order 和 eslint 的 order 不一样。eslint 里相对路径是放外部依赖后面的。

**Comment by ztplz** [comment]
那就不对了  把warn都过滤了怎么样 https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250  大家都是把warn都filter了

**Comment by ztplz** [comment]
在antd-tool里面清除相关warn了

**Pull request closed without merging**
