### PR TITLE
feat(table): support close fn to close filter dropdown only

### LINKED ISSUE #37665: 能在Table的自定义筛选（FilterDropdown）里把关闭筛选的函数也给导出到props吗？
### What problem does this feature solve?

columns应该就一次处理，然后传递给Table的时候这里业务一般都会将Table加工复用，也就是我在A页面用了加工的Table，如果要操作colums上的属性的话需要再源头传递一个回调函数让深层的filterDropdown组件来触发close，而这个close的逻辑又要来操作colunms上的显隐属性（filterDropdownOpen），我觉得在filterDropdown函数传递的props上可以添加一个closeDropdown，就像你们代码里的triggerVisible函数一样，解决了不用操作columns上的filterDropdownOpen属性。可通过FilterDropdown的子节点来关闭。

组件层级如下 Pgae/MyTable/Filter

### What does the proposed API look like?

filterDropdown函数再多传递一个关闭菜单的选项，亦或者是clearFilters函数多传递个params内部处理关闭
image
image

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [X] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- close #37665 
- close #37724
- close #37784

### 💡 Background and solution

Provide a method `close` to close dropdown will not confirm.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Table `filterDropdown` add `close` in argument to close filter dropdown only.    |
| 🇨🇳 Chinese |   Table `filterDropdown` 新增一个 close 参数对象用于关闭筛选菜单。        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
ci broken

**Comment by kiner-tang** [comment]
> ci broken

This does not seem to be an error caused by this PR. It also exist in feature.

image

**Comment by afc163** [comment]
rebase 一下 feature 分支

**Comment by kiner-tang** [comment]
> rebase 一下 feature 分支

ok

**Review by afc163 — APPROVED** [review]

**Pull request merged**
