### PR TITLE
fix(menu): css side effects caused by extra prop

### PR DESCRIPTION
**Pull request by coding-ice**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [x] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution
起因是：`ant-menu-title-content -> display: inline-flex` （原本的 `flex: auto` 失效）, 此时 flex container的大小由子元素决定，恰好子元素又是用户自定义的，第一个元素设置为`auto`可不可行（多少都有点副作用，要么把新加的item-extra 改为float: right），（原来的a：flexGrow： 1 写错了）

Feat PR：https://github.com/ant-design/ant-design/pull/50431/files#diff-c25247b807ec2f52c363c570643f96ea7485c69baf56241c13bb617fb7e5abc0R638

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Side effects caused by the flex element |
| 🇨🇳 Chinese |   flex 元素引发的副作用        |

### CODE REVIEW

**Comment by afc163** [comment]
有问题重现么？

**Comment by coding-ice** [comment]
https://stackblitz.com/edit/vitejs-vite-pvdlfh?file=src%2FApp.tsx

**Comment by afc163** [comment]
@coding-ice 有关于 antd Menu/Dropdown 的重现么？

**Comment by coding-ice** [comment]
> @coding-ice 有关于 antd Menu/Dropdown 的重现么？

https://stackblitz.com/edit/react-12p1dj?file=demo.tsx

**Comment by afc163** [comment]
如果用户自定义样式，因为你不知道可能如何自定义，你没办法保证毫无影响的。

这一个修改本身可能也会引发其他用户自定义样式被 break。

**Comment by coding-ice** [comment]
新加的item-extra 改为float: right 应该可行，不会影响原来的

**Comment by afc163** [comment]
我倒是发现另外一个问题，折叠动画过程中，右边内容会直接贴到左边。

Sep-11-2024 11-40-20

**Comment by afc163** [comment]
> 新加的item-extra 改为float: right 应该可行，不会影响原来的

这种和用户自定义样式冲突导致的问题，没办法完美修复的，我不建议修。

**Comment by coding-ice** [comment]
好的，那我这个先 `close` 了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50794#issuecomment-2342556680

这个问题可以看看。

**Pull request closed without merging**
