### PR TITLE
style: notification text add word-wrap

### PR DESCRIPTION
**Pull request by littleee**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

before
ex1
after
ex2

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Notification wrap long words     |
| 🇨🇳 Chinese | 长单词自动换行，使其不溢出弹框          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by hengkx** [comment]
pleace add changelog

**Comment by littleee** [comment]
> pleace add changelog

done

**Comment by hengkx** [comment]
check ci

**Comment by littleee** [comment]
> check ci

ci passed

**Review by hengkx — APPROVED** [review]

**Pull request merged**
