### PR TITLE
fix(Upload):  should support `name` prop drilling 

### LINKED ISSUE #50643: The Upload component's name attribute isn't reflecting on the input tag.
### Reproduction link

[https://codepen.io/macinjoke/pen/rNErrPb?editors=1010](https://codepen.io/macinjoke/pen/rNErrPb?editors=1010)

### Steps to reproduce

View input tags in the developer tools.

### What is expected?

The input tag has a name attribute.

### What is actually happening?

Input tags do not have a name attribute.

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18 |
| System | macOS 13.6.9 |
| Browser | chrome 127.0.6533.120 |

---
The minimal reproduction is a copy of the Upload sample on Ant Design official page.
This is a Dragger sample, but other Upload components will not have a name attribute as well.

### PR DESCRIPTION
**Pull request by Wxh16144**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [x] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

fix: #50643

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    `<Upload />` support  'name' prop  drilling     |
| 🇨🇳 Chinese |    上传组件支持 `name` prop 透传      |

### CODE REVIEW

**Comment by Wxh16144** [comment]
要作为 feature 么？ @afc163

**Comment by afc163** [comment]
对，作为 feature。

**Comment by Wxh16144** [comment]
> 对，作为 feature。

就这个 pr 改目标分支吧，等一波 ci 看看

**Comment by Wxh16144** [comment]
> 对，作为 feature。

name 本来就支持，不用作为 feature ，当作一个 bug 修复，我在这里解释了一下 https://github.com/react-component/upload/pull/576#issuecomment-2330694825

**Review by afc163 — APPROVED** [review]

**Pull request merged**
