### PR TITLE
fix(typography): Fix code tag overflow truncation style error

### LINKED ISSUE #40261: Typography.Text code ellipsis 丢失右边框
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/sheng-lue-hao-antd-5-1-5-forked-1gog5y?file=/demo.tsx)

### Steps to reproduce

开启 ellipsis Switch

### What is expected?

Typography.Text code 有完整的边框
image

### What is actually happening?

Typography.Text code 丢失右边框
image

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | macOS 12.4 |
| Browser | 108.0.5359.98 |

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix code tag overflow truncation style error      |
| 🇨🇳 Chinese |     修复 code 标签溢出截断样式问题      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://app.argos-ci.com/ant-design/ant-design/builds/5707/36837382 看看是不是符合预期

**Comment by Wxh16144** [comment]
> https://app.argos-ci.com/ant-design/ant-design/builds/5707/36837382 看看是不是符合预期

看起来又很多变动， 我先 rebase 一下 master。重新跑一下 CI

**Comment by Wxh16144** [comment]
看起来确实修复问题导致其他地方错误了，影响范围挺大的，我重新检查一下...

**Comment by Wxh16144** [comment]
在不改变 dom 结构的情况下，我好像解决不了这个问题。 需要帮助...😢

**Comment by Wxh16144** [comment]
请移步 #41005

**Pull request closed without merging**
