### PR TITLE
feat(typings): props and defaultProps consistency

### LINKED ISSUE #19871: Make props and defaultProps typings consistent
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In Collapse (for example) `expandIconPosition` has type `ExpandIconPosition` [here](https://github.com/ant-design/ant-design/blob/master/components/collapse/Collapse.tsx#L23)

But in defaultProps this props has value `'left'` [here](https://github.com/ant-design/ant-design/blob/master/components/collapse/Collapse.tsx#L43). This will outputs as string in the generated d.ts file.

This fails when used with styled-components for example

```typescript
import { Collapse } from 'antd';
import { CollapseProps } from 'antd/lib/collapse';
import styled from 'styled-components';

const StyledCollapse = styled<React.ComponentType<CollapseProps>>(Collapse); // Error defaultProps.expandIconPosition of type string is not compatible with ExpandIconPosition
```

### What does the proposed API look like?
Before

```typescript
static defaultProps = {
    bordered: true,
    openAnimation: { ...animation, appear() {} },
    expandIconPosition: 'left',
  };
```

After
```typescript
static defaultProps: Partial<CollapseProps> = {
    bordered: true,
    openAnimation: { ...animation, appear() {} },
    expandIconPosition: 'left',
  };
```

### PR DESCRIPTION
**Pull request by paulsouche**
### 🤔 This is a ...

- [X] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [X] TypeScript definition update
- [X] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close #19871

Props and defaultProps where inconsistents

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Review by yoyo837 — APPROVED** [review]
LGTM, should double check.

**Comment by afc163** [comment]
I think we should update this in 4.0-prepare, otherwise will cause a lot of conlicts.

**Comment by yoyo837** [comment]
@paulsouche Please checkout from the `4.0-prepare` branch and send a new PR for this?

**Comment by paulsouche** [comment]
Done #19995

**Pull request closed without merging**
