### PR TITLE
Fix button size style

### PR DESCRIPTION
**Pull request by crazyair**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

https://github.com/ant-design/ant-design/issues/47053

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    `Button` size style reduce weight       |
| 🇨🇳 Chinese |   `Button` size 样式降低权重       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
diff 差的有点多。

**Comment by crazyair** [comment]
> diff 差的有点多。

之前一直没跑成功，我看看，尽量没 diff

**Comment by crazyair** [comment]
image
这不应该影响到这个啊？

**Comment by crazyair** [comment]
diff 没问题了吧？

**Comment by MadCcc** [comment]
看起来改制后的 Transfer 和 v4 是一致的

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
