### PR TITLE
fix(Upload): action buttons focus style leave after click it

### PR DESCRIPTION
**Pull request by zbw-zbw**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
点击某文件的下载按钮后，鼠标移出该文件，仍展示下载按钮
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fixed an issue where the download button of a file was still displayed when the mouse moved out of the file after clicking on it      |
| 🇨🇳 Chinese |    修复点击某文件的下载按钮后，鼠标移出该文件，仍展示下载按钮的问题       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 843c490</samp>

Simplify the CSS selector for the upload list action button to only apply to picture mode. This improves the visual consistency and accessibility of the upload component.

### <samp>🤖 Generated by Copilot at 843c490</samp>

*  Simplify the action button selector for the upload list in picture mode ([link](https://github.com/ant-design/ant-design/pull/44594/files?diff=unified&w=0#diff-4292b1d3091a5dada24be824e64547feee97955fd1dce04d59a8866c35cdfccaL54-R54)) and remove unnecessary styles for other modes in `components/upload/style/list.ts`

### CODE REVIEW

**Comment by afc163** [comment]
这应该是预期行为，否则键盘操作没办法导航上去，具体见 issue：https://github.com/ant-design/ant-design/pull/24615

**Comment by zbw-zbw** [comment]
> 这应该是预期行为，否则键盘操作没办法导航上去，具体见 issue：#24615

懂了，但感觉这个问题也是个 bug 吧，体验不是很好，看看有没有办法优化下
image

**Comment by afc163** [comment]
有重现链接么？

**Comment by zbw-zbw** [comment]
> 有重现链接么？

antd官网就能复现

**Comment by afc163** [comment]
确实有点奇怪，我看看。。

**Comment by zbw-zbw** [comment]
> 确实有点奇怪，我看看。。

我更新了，麻烦看下

**Comment by afc163** [comment]
把 :focus 改成 :focus-visible 就好。

**Comment by zbw-zbw** [comment]
> 把 :focus 改成 :focus-visible 就好。

done！这种解决方案比我的好多了哈哈哈，学到了
image

**Review by afc163 — APPROVED** [review]

**Pull request merged**
