### PR TITLE
chore: use translate3d for performance optimization

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [x] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

在浏览器进行图形渲染的时候，`translate3D` 可以调用GPU进行3D加速，略微提升性能，`translate` 因为是 2D 移动，不能调用GPU加速

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: use translate3d for performance optimization |
| 🇨🇳 Chinese |chore: 使用 translate3d 代替 translateX、translateY |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
会有多大性能提升？

**Review by eidn122 — APPROVED** [review]

**Comment by LuciNyan** [comment]
> 消息准确么？会有多大性能提升？

The key to `translateZ` and will-change working is to create a new composition layer for the element, which is suitable for scenarios where the element changes position frequently (by `translate`) or its background elements are frequently re-layout. But even then, the performance gain is minimal and sometimes harmful. Theoretically, it would make sense on older phones with low CPU resources

**Comment by li-jia-nan** [comment]
> 消息准确么？会有多大性能提升？

大概看了一下相关文献，主要是针对功能较弱的设备上有一定提升，在现代浏览器中提升是比较小的：

- [https://blog.teamtreehouse.com/increase-your-sites-performance-with-hardware-accelerated-css](https://blog.teamtreehouse.com/increase-your-sites-performance-with-hardware-accelerated-css)

- [https://www.smashingmagazine.com/2012/06/play-with-hardware-accelerated-css](https://www.smashingmagazine.com/2012/06/play-with-hardware-accelerated-css)

- [https://www.oreilly.com/content/animating-movement-with-translate3d](https://www.oreilly.com/content/animating-movement-with-translate3d)

**Comment by li-jia-nan** [comment]
组件部分回滚了，只留了官网

**Review by afc163 — APPROVED** [review]

**Pull request merged**
