### PR TITLE
fix: submenu popupClassName and className chaos

### PR DESCRIPTION
**Pull request by jljsj33**
### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese | className 与 popupClassName 混乱， |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

className 应该是 item li 的样式，不应该带到 popupMenu 上

### CODE REVIEW

**Comment by jljsj33** [comment]
@yesmeck 解释下这个 popupClassName 为什么去合 className ？

**Comment by jljsj33** [comment]
这鬼东西还有个 bug ，，，props 更改 className 后，selected 样式消失，

**Comment by jljsj33** [comment]
有没有反应的啊，，谁埋的坑，出来冒个泡。。。

**Comment by yesmeck** [comment]
就是当时写错了吧

**Review by yesmeck — APPROVED** [review]

**Review by afc163 — CHANGES_REQUESTED** [review]
给个问题重现

**Pull request merged**
