### PR TITLE
fix(select): omit getRawInputElement

### PR DESCRIPTION
**Pull request by aoilti**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
What problem this PR want to resolve?

**Comment by aoilti** [comment]
> What the problem does this PR resolve?

https://github.com/ant-design/ant-design/issues/31491 this one

**Comment by afc163** [comment]
Could you provide a reproduce without formly and add a test case?

**Comment by aoilti** [comment]
> Could you provide a reproduce without formly and add a test case?

Sorry，I think a lot of cases are inappropriate, so I can only put one formily。`getRawInputElement` is `rc-select` private properties, This case is a type derivation error caused by not omit `getRawInputElement`. Is it unnecessary to test?

**Comment by afc163** [comment]
It is better to have a test case in case we miss other private property.

**Comment by aoilti** [comment]
> It is better to have a test case in case we miss other private property.

I can try it, but there is no guarantee that it will do well

**Pull request merged**
