### PR TITLE
Fix package.json import for webpack@5 compatibility

### PR DESCRIPTION
**Pull request by irudoy**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#22642

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
会不会改成required(‘../../package.json’).version 好一些？

**Comment by zhangwilling** [comment]
这个也合入3.x-stable 的分支，发布3.x的兼容版吧。（我这边有个老项目，暂时不太好迁移 4 ）

**Comment by yoyo837** [comment]
已经改为#23957的形式了

**Comment by zhangwilling** [comment]
这是 merge 进 master （4.x） 了吧，看了下 3.x-stable 的分支没有记录, 3.26.18 的包也没改。

我这边用 patch-package 临时解决了，有空就发一个 fix 版吧。

**Pull request merged**
