### PR TITLE
add moment dependecy in the package.json

### PR DESCRIPTION
**Pull request by im6**
under babel-plugin-import support, datapicker will report error without this

### CODE REVIEW

**Comment by benjycui** [comment]
Could you post error messages here? For DatePicker is based on rc-calendar which had added `moment` to dependencies.

**Comment by jinouwuque** [comment]
antd/lib/date-picker/RangePicker.js
antd/lib/date-picker/createPicker.js
these two are using moment.

2016-09-28 22:37 GMT-04:00 Benjy Cui <notifications@github.com>:

**Comment by jinouwuque** [comment]
plugins: [
    'transform-runtime',
    ['import', {
        libraryName: 'antd',
        libraryDirectory: "lib",
        style: true
    }]
]


this is my plugins in webpack.

It works perfect without babel-import-plugin.

But if I use import-plugin, it will complain like "cannot resolve
module moment in blablabla"

I believe you could replicate the error msg by deleting moment from
antd/node_modules by using the above babel config.

I am not sure if it's plugin's problem or ant-design.


2016-09-28 22:41 GMT-04:00 ee2win <ee2win@gmail.com>:

**Comment by benjycui** [comment]
I try your config in my project, it works fine without errors. Which version of npm are you using?

**Comment by jinouwuque** [comment]
npm: 2.15.9
node: 4.5.0

initially i just use "npm i antd -D"



2016-09-29 3:00 GMT-04:00 Benjy Cui <notifications@github.com>:

**Comment by yiminghe** [comment]
right, antd depends on moment now, antd should list moment inside deps

**Pull request merged**
