### PR TITLE
fix #15192

### LINKED ISSUE #15192: The argument file.status of Upload onRemove is always 'removed'
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/6zj7wn07k)

### Steps to reproduce
click the upload button, select a file, click ok, wait upload complete then delete the file and see the output of the console.

### What is expected?
error

### What is actually happening?
removed

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.3 |
| System | all |
| Browser | all |

---
Usually we clear the resource in the onRemove callback. for example request the server to delete the uploaded file (Which may be not exist because of upload error). So if `file.status` shows the last status, it will help us to decide what should do in the onRemove callback. On the other hand, only when `onRemove` return true, the status should become 'removed'.

### PR DESCRIPTION
**Pull request by ngolin**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

Usually we clear the resource in the `onRemove` callback. for example request the server to delete the uploaded file (Which may be not exist because of upload error). So if file.status shows the last status, it will help us to decide what should do in the `onRemove` callback. On the other hand, only when `onRemove` return `true`, the status should become 'removed'.

close #15192

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

Change the `status` of the file after `onRemove` returned.

### 📝 Changelog description

> Describe changes from user side, and list all potential break changes or other risks.

1. English description

2. Chinese description (optional)

No potential break changes or other risks.

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
- [ ] Need test case.
- [ ] meaningful commit message and PR title would be nice.

**Comment by ngolin** [comment]
> * [ ]  Need test case.
> * [ ]  Meaningful commit message and PR title would be nice, not just `fix #xxx`

Thanks.

**Comment by afc163** [comment]
@ngolin

**Comment by ngolin** [comment]
> @ngolin

Oh, I am not sure how to apply test case. Can I just close this PR?

**Comment by ztplz** [comment]
@ngolin  You can do it just like other test do.

**Comment by afc163** [comment]
ping @ngolin

**Pull request closed without merging**
