### PR TITLE
fix: Form with forwardRef typescript

### LINKED ISSUE #16229: Pull #16126 break the current code
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/84zk9696y8)

### Steps to reproduce
Test是用由forwardRef得到的可以传递ref的函数组件，TestClass是一般的ClassComponent

### What is expected?
`Form.create()(Test)`不会报错
`Form.create()(TestClass)`能接受wrappedComponentRef属性，或者更进一步，直接支持使用ref

### What is actually happening?
`Form.create()(Test)` 会导致typescript报错，说是不能接受Test
`Form.create()(TestClass)`不会报错，但返回的新组件不能接受wrappedComponentRef属性

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | 16.8.3 |
| System | all |
| Browser | all |

---
在那个pull合并前的版本是没问题的

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

fix #16229

### 💡 Solution

Update typescript definition

### 📝 Changelog

Fix Form with forwardRef typescript definition.

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by DiamondYuan** [comment]
这个是不是没有发版本？

**Comment by zombieJ** [comment]
还没发

**Comment by hsulei** [comment]
近期会发吗？

**Comment by zombieJ** [comment]
每周末发版本

**Comment by afc163** [comment]
close #16284

**Pull request merged**
