### PR TITLE
fix(float-button): marginBottom is invalid after the href is added

### LINKED ISSUE #44700: 5.8.6 FloatButton.Group 中 FloatButton 一旦使用 href 方式会导致 按钮挤在一起
### Reproduction link

[https://codepen.io/ssiMo-Mo/pen/jOXywJW?editors=001](https://codepen.io/ssiMo-Mo/pen/jOXywJW?editors=001)

### Steps to reproduce

<FloatButton.Group shape="circle" style={{ right: 40 }}>
                <FloatButton
                    tooltip="GitHub 仓库"
                    href="https://xxxxxxxxxxx"
                    target="_blank"
                    icon={<GithubIcon />}
                />

                <FloatButton
                    tooltip="切换主题"
                    onClick={() => changeThemeModel(!isDark)}
                    icon={
                        isDark ? (
                            <Icon style={{ fontSize: 18 }} component={Light} />
                        ) : (
                            <Icon style={{ fontSize: 18 }} component={Dark} />
                        )
                    }
                />
                <FloatButton.BackTop tooltip="回到顶部" visibilityHeight={500} />
            </FloatButton.Group>

### What is expected?

使用  href 浮动按钮正常显示

### What is actually happening?

使用  href 浮动按钮显示错误 挤在了一起

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | chrome 116.0.5845.179 |

### PR DESCRIPTION
**Pull request by Yuiai01**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/44700
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix marginBottom is invalid after the href is added        |
| 🇨🇳 Chinese |  解决添加 href 后 marginBottom 无效         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at d27be10</samp>

Fix floating button visibility issue by adding `display: 'block'` to its style. Modify `components/float-button/style/index.ts` to apply the fix.

### <samp>🤖 Generated by Copilot at d27be10</samp>

*  Add `display: 'block'` to `sharedFloatButtonStyle` to fix floating button visibility issue (#32879) ([link](https://github.com/ant-design/ant-design/pull/44707/files?diff=unified&w=0#diff-fc14ffe666c4ac5e79188e926f924116e9e8a9c57e2717b2a490d878b09e72d9R223))

### CODE REVIEW

**Review by MadCcc — APPROVED** [review]

**Comment by afc163** [comment]
要补个 image test

**Comment by Yuiai01** [comment]
> 要补个 image test

done

**Comment by li-jia-nan** [comment]
- #44587

是这里改出问题了吧

**Comment by Yuiai01** [comment]
> * [chore(float-button):  remove unused css code #44587](https://github.com/ant-design/ant-design/pull/44587)
> 
> 是这里改出问题了吧

对，当时可能没看出来

**Comment by Yuiai01** [comment]
> > * [chore(float-button):  remove unused css code #44587](https://github.com/ant-design/ant-design/pull/44587)
> > 
> > 是这里改出问题了吧
> 
> 对，当时应该没看出来

**Comment by li-jia-nan** [comment]
> 对，当时应该没看出来

这里加个注释吧，防止以后误删

**Comment by afc163** [comment]
argos 没变？

**Comment by Yuiai01** [comment]
> argos 没变？

之前的 demo 是没有加 `href` 因此没有问题，问题解决后，这里加上 `href` 后应该是和之前保持一致。

**Comment by Yuiai01** [comment]
> > 对，当时应该没看出来
> 
> 这里加个注释吧，防止以后误删

好

**Comment by Yuiai01** [comment]
> argos 没变？argos 应该要变的，否则以后改坏看不出来。

这里修复过后，加上 `href` 后的 argos 是和之前保持一致的。另外一组 `FloatButton.Group` 没有加 `href` ，之后改出问题的话，两组出现的不同表现，感觉应该能判断出来。

**Pull request merged**
