### PR TITLE
fix(collapse): add a11y test for demo and improve focus style

### LINKED ISSUE #32792: How to change tabindex in Collapse.Panel header?
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What is actually happening?
I can't change tabindex here:
<div class="ant-collapse-header" role="button" tabindex="0" aria-expanded="true"></div>

Component "Collapse".

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 6.14.15 |
| System | 10 |
| Browser | all |

### PR DESCRIPTION
**Pull request by aojunhao123**
### 🤔 This is a ...

- [x] ✅ Test Case
- [x] 💄 Component style improvement

### 🔗 Related Issues
close https://github.com/ant-design/ant-design/issues/32792

#### Background

- Collapse组件缺少无障碍性(a11y)测试用例
- 当前的focus样式可能影响组件的无障碍性体验

#### Solution

1. 为Collapse组件添加了无障碍性测试，确保组件的demo符合无障碍标准
2. 移除了不必要的focus outline: none样式，以改善键盘导航体验

### Before
Export-1732893030293

### After
Export-1732893161913

### 📝 Change Log

| Language | Changelog |
| --- | --- |
| 🇺🇸 English | - Add accessibility test for Collapse component demos<br>- Improve focus style for better keyboard navigation experience |
| 🇨🇳 Chinese | - 为 Collapse 组件 demo 添加无障碍性测试<br>- 优化焦点样式以提供更好的键盘导航体验 |

### CODE REVIEW

**Comment by aojunhao123** [comment]
@afc163 大佬有空看看

**Comment by aojunhao123** [comment]
QQ_1732892229978
顺便拷打一下豆酱为啥要把focus的样式给去掉😏难道是有什么深意🤔

**Comment by aojunhao123** [comment]
ci有点问题，来个大佬修一下（

**Comment by thinkasany** [comment]
> ci有点问题，来个大佬修一下（

ci：年轻人早点睡觉，少熬夜
睡不着的话可以参考这个止血先跑一跑，不知道能不能合。
image

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
