### PR TITLE
feat(ConfigProvider): add form scrollToFirstError

### LINKED ISSUE #39483: ConfigProvider 添加 form 的 scrollToFirstError 配置
### What problem does this feature solve?

比如在 ant-design-pro 中，每次都需要配置 scrollToFirstError 距离顶部的偏移量，否则会被顶部 Header 栏遮挡。

### What does the proposed API look like?

form: {{  scrollToFirstError: ... }}

### PR DESCRIPTION
**Pull request by linxianxi**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #39483
close #39505

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    ConfigProvider supports form scrollToFirstError  |
| 🇨🇳 Chinese |  ConfigProvider 新增 form scrollToFirstError         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by linxianxi** [comment]
我看 #39505 将问题复杂化了，就自己提了。

**Comment by afc163** [comment]
冲突了

**Comment by linxianxi** [comment]
> 冲突了

已解决

**Comment by afc163** [comment]
图片

**Comment by linxianxi** [comment]
> 图片

快合吧，不然过几天等下又冲突了...

**Comment by linxianxi** [comment]
@afc163 @zombieJ 合一下，解决好几次冲突了

**Review by yoyo837 — APPROVED** [review]

**Pull request merged**
