### PR TITLE
feat: `Input`、`TextArea`、`Mentions` support onClear prop

### PR DESCRIPTION
**Pull request by li-jia-nan**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

- Use a developer-oriented tone and narrative style.
- Describe the user's first-hand experience of the issue and its impact on developers, rather than your solution approach.
- Refer to: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | 1. feat: `Input`、`TextArea`、`Mentions` support `onClear` prop <br /> 2. Prevent long press of enter |
| 🇨🇳 Chinese | 1. `Input`、`TextArea`、`Mentions` 组件支持 `onClear` 回调，便于区分点击 x 清除和手动清除这两个行为 <br />2. 防止长按回车键 |

### CODE REVIEW

**Comment by afc163** [comment]
How about https://github.com/ant-design/ant-design/issues/16862#issuecomment-507616942

**Comment by li-jia-nan** [comment]
> How about [#16862 (comment)](https://github.com/ant-design/ant-design/issues/16862#issuecomment-507616942)

跟 @MadCcc 讨论了一下，这个可以和 `onChange` 一起触发，只是想单独有一个 `onClear` 回调，用来区分两种清除的行为，虽然 onChange 可以实现，但是逻辑不太一样，所以还是支持了（Select 组件也支持）

**Comment by li-jia-nan** [comment]
- https://github.com/react-component/input-number/pull/656
- https://github.com/react-component/textarea/pull/60
- https://github.com/react-component/mentions/pull/265
- https://github.com/react-component/input/pull/71

**Comment by li-jia-nan** [comment]
wait: 

- https://github.com/react-component/textarea/pull/62

**Comment by li-jia-nan** [comment]
@SocketSecurity ignore npm/fsevents@1.2.13
@SocketSecurity ignore npm/sharp@0.33.4

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
