### PR TITLE
input in antd

### PR DESCRIPTION
**Pull request by karthik-1120**
please add autoFocus field to input boxes in antd theme

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by karthik-1120** [comment]
please add autoFocus feature to input fields in antd theme

**Comment by afc163** [comment]
What problem this PR will resolve?

**Comment by karthik-1120** [comment]
AutoFocus feature is missing in Antd Input. so it will be resolved on that
PR and please test that once.

**Comment by afc163** [comment]
`autoFocus` works: https://codesandbox.io/s/hopeful-meitner-ekkwo?file=/index.js

**Pull request closed without merging**
