### PR TITLE
fix: table cellPaddingBlock token bug

### LINKED ISSUE #45024: table 组件 token: cellPaddingBlock 无效
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/zu-jian-chi-cun-antd-5-9-2-forked-ggsg97?file=/demo.tsx:198-214)

### Steps to reproduce

```tsx
import "./index.css";
import { ConfigProvider, Table } from "antd";

const App: React.FC = () => {
  return (
    <ConfigProvider
      theme={{
        components: {
          Table: {
            cellPaddingBlock: 0,
            cellPaddingBlockMD: 0,
            cellPaddingBlockSM: 0,
            cellPaddingInline: 0
          }
        }
      }}
    >
      <Table
        columns={[
          { title: "Name", dataIndex: "name" },
          { title: "Age", dataIndex: "age" }
        ]}
        dataSource={[
          { key: "1", name: "John Brown", age: 32 },
          { key: "2", name: "Jim Green", age: 42 },
          { key: "3", name: "Joe Black", age: 32 }
        ]}
      />
    </ConfigProvider>
  );
};

export default App;
```

### What is expected?

通过 ConfigProvider 设置表格上下边距（cellPaddingBlock）有效效

### What is actually happening?

通过 ConfigProvider 设置表格上下边距（cellPaddingBlock）无效

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.0.0 |
| System | windows |
| Browser | edge 114.0.1823.37 |

### PR DESCRIPTION
**Pull request by poyiding**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/45024

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix table cellPaddingBlock token bug      |
| 🇨🇳 Chinese |     修复 table 组件  设置 cellPaddingBlock  token 无效bug   |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 3763f19</samp>

Refactored table content padding for large screens in `components/table/style/index.ts`. This change enhances the visual appearance and alignment of table cells.

### <samp>🤖 Generated by Copilot at 3763f19</samp>

*  Remove `paddingContentVerticalLG` variable and use `tablePaddingVertical` instead for table content padding on large screens ([link](https://github.com/ant-design/ant-design/pull/45040/files?diff=unified&w=0#diff-a9612177ff7fc2e50de3a66777bcee3c89711d02a709c61366efbc3b838a8e6cL248), [link](https://github.com/ant-design/ant-design/pull/45040/files?diff=unified&w=0#diff-a9612177ff7fc2e50de3a66777bcee3c89711d02a709c61366efbc3b838a8e6cL282-R281))

### CODE REVIEW

**Comment by MadCcc** [comment]
看起来对 compact 主题影响比较大，但应该是合理的

**Review by MadCcc — APPROVED** [review]

**Comment by zyk2891** [comment]
这个bug解决了吗

**Comment by poyiding** [comment]
> 这个bug解决了吗

上面 changelog 不是写了在5.9.3 已经fix 了，不看changelog吗

**Comment by zyk2891** [comment]
嗯 看到了 更新版本就解决了

**Pull request merged**
