### PR TITLE
fix: Button loading switch animation

### LINKED ISSUE #23070: Button icon with loading animation weird
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-grucr?file=/index.js)

### Steps to reproduce

Kapture 2020-04-09 at 10 36 21

Kapture 2020-04-09 at 10 37 11

### What is expected?
animation normal

### What is actually happening?
animation weird

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.0 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #23070
close #23080

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |fix Button `icon` with `loading` animation|
| 🇨🇳 Chinese | 修复 Button `icon` 结合 `loading`  的动画|

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/button/demo/loading.md](https://github.com/ant-design/ant-design/blob/button-ani/components/button/demo/loading.md)

### CODE REVIEW

**Comment by shaodahong** [comment]
Kapture 2020-04-10 at 0 02 01

感觉有点硬直，不够滑

**Comment by zombieJ** [comment]
> Kapture 2020-04-10 at 0 02 01
> 
> 感觉有点硬直，不够滑

👌 明天再调一调

**Comment by shaodahong** [comment]
Kapture 2020-04-10 at 0 04 27

嗯，这个更明显

**Comment by zombieJ** [comment]
调了一下感觉 v3 的 loading 也很违和，速度从 0.3 改成了 0.5。再体验体验

**Comment by shaodahong** [comment]
`.5` 有点长，慢了点感觉好点了

**Comment by afc163** [comment]
0.5s 感觉有点拖沓。

**Review by shaodahong — APPROVED** [review]
LGTM

**Comment by afc163** [comment]
image

半透明没了。

**Pull request merged**
