### PR TITLE
docs: add v4 theme guide

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
https://github.com/ant-design/ant-design/issues/43827
1. v4 迁移 v5 文档添加了 v4 主题包示例
2. 首页主题切换新增 v4 主题包
3. 更新的 tag 颜色改为了蓝色

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      -     |
| 🇨🇳 Chinese |    -       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at a06b295</samp>

This pull request adds support for the V4 theme package in Ant Design V5, which allows users to customize the appearance of their components. It also improves the theme editor and the documentation pages for the theme feature. It updates some dependencies and colors to match the new design system.

### <samp>🤖 Generated by Copilot at a06b295</samp>

*  Add support for switching between different themes, including the new V4 theme, in the `Theme` component ([link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedR11-R12), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedR29), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedR41), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedR283-R285), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL305-R319), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL330-R344), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedR418), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL478-R503), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL487-R512))
*  Add the V4 theme option and image to the `ThemePicker` component ([link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dR12), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dR23), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dR30))
*  Change the tag color for the `processing` status in the `useMenu` hook to match the new design system ([link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-97b7cacb6d4bd1445cc4d73ae072d3aac76d65d4c10eb29328c6cc8aef1d6649L51-R51))
*  Add the `@ant-design/compatible` dependency to the `package.json` file to install the compatible package for the V4 theme ([link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R162))
*  Add a section about using the V4 theme package to the `migration-v5.zh-CN.md` document and mark it as updated ([link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-be1faf3d418140212756aac28b89919752b536ca91a6125cb0ae3ddd761efd72R7), [link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-be1faf3d418140212756aac28b89919752b536ca91a6125cb0ae3ddd761efd72R276-R307))
*  Comment out the `console.log` statement in the `TokenChecker` component to avoid cluttering the console output ([link](https://github.com/ant-design/ant-design/pull/44078/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL43-R47))

### CODE REVIEW

**Comment by crazyair** [comment]
如果一个项目没有装`@ant-design/compatible`怎么用 v4 主题。

这个要恢复 v4 主题的意思是，用 v5 的 token 配置出 v4 的样子。

**Comment by MadCcc** [comment]
> 如果一个项目没有装`@ant-design/compatible`怎么用 v4 主题。
> 
> 这个要恢复 v4 主题的意思是，用 v5 的 token 配置出 v4 的样子。

可以看下兼容包里的实现，就是 v5 的 token

**Comment by afc163** [comment]
> 可以看下兼容包里的实现，就是 v5 的 token。不嫌麻烦可以整个拷贝过来

@MadCcc 可以 export 出来给用户单独用。

**Comment by MadCcc** [comment]
> @MadCcc 可以 export 出来给用户单独用。或者单独维护一个 npm 包。

@afc163 现在就是整个 export 出来的，可以参照代码示例。

**Review by kiner-tang — APPROVED** [review]

**Pull request merged**
