### PR TITLE
Add onFilter property to Table that gives access to the filtered dataSource

### PR DESCRIPTION
**Pull request by tijp**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

_Oops, new PR. I forgot to create a new branch so the previous PR had some mixed commits. Sorry for that, I'm still learning PR's._

Sometimes it's desirable to receive the filtered dataSource when the filters change in the `Table` component. For example when you want to display the number of rows in your table.

Issue for this feature #10298

This PR adds an `onFilter` prop to the `Table` component. When the filters change, the `onFilter` callback will be called with the `filteredDataSource` and `filters` properties.

````
<Table
  columns={columns}
  dataSource={data}

  onFilter={(filteredDataSource, activeFilters) => {

    // Now you can do whatever you want with the filtered dataSource

    this.setState({ numberOfRowsInTable: filteredDataSource.length });
  }}
/>
````

### CODE REVIEW

**Comment by afc163** [comment]
I think it is better to add `filteredDataSource` as `onChange`'s arguments.

**Comment by tijp** [comment]
I agree it would be a cleaner approach. I'll change it so the `filteredDataSource` is added to the `onChange` arguments.

**Comment by tijp** [comment]
I moved the filteredDataSource to the `onChange` arguments. It's working fine for sort changes. However when I change the filter I receive the <b>unfiltered datasource</b> in the `onChange` arguments.

After looking around I found that the filters get removed in the `handleFilter` method. When removing this part of code it works fine and I receive the <b>filtered datasource</b>. Also the tests stay green.

Why do the filters get removed from the state in the `handleFilter` method, and can I safely remove that piece of code?

https://github.com/ant-design/ant-design/blob/5ab265a00985967f35749f5ab5cccfdcd733dfe9/components/table/Table.tsx#L416-L422

**Comment by usamanazar** [comment]
this is prop is not available in 3.8.1v ?

**Pull request closed without merging**
