### PR TITLE
fix: improve inner pagination padding

### PR DESCRIPTION
**Pull request by qmhc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

None.

### 💡 Background and solution

Before:

image

image

After:

image

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | improve inner pagination padding |
| 🇨🇳 Chinese | 改进内部分页器的内边距 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — DISMISSED** [review]

**Comment by MadCcc** [comment]
image
这个mei dui qi de g没对齐的感觉

**Comment by li-jia-nan** [comment]
确实

**Comment by qmhc** [comment]
> image 这个没对齐的感觉

是的，这个在改之前也发现的，但是应该是 Pagination 的问题，所以不包含在这个 PR 里面。

**Comment by li-jia-nan** [comment]
before:
image

after:
image

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
