### PR TITLE
fix: some description here

### PR DESCRIPTION
**Pull request by BlueLanM**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at e9a1209</samp>

Simplified the Chinese description of the basic usage of the `Segmented` component in `components/segmented/demo/basic.md` to match the English version.

### <samp>🤖 Generated by Copilot at e9a1209</samp>

*  Simplify the Chinese description of the basic usage of the segmented component ([link](https://github.com/ant-design/ant-design/pull/42313/files?diff=unified&w=0#diff-65c31c7fc668d049cf38ffb9e98a4ecdf5cd8bbe765c0dedb9309ef1aa5f2f00L3-R3))

### CODE REVIEW

**Comment by BlueLanM** [comment]
加了一个Button新样式
image

**Comment by yoyo837** [comment]
这个怕是要团队的设计师看看吧, 不一定同意加

**Comment by li-jia-nan** [comment]
这个要发 feature 分支了，并且需要给设计师看，建议先提一个 RFC，如果 RFC 通过了再提交 PR

**Comment by BlueLanM** [comment]
噢噢明白了明白了，我只是想试着加一个样式看一下

**Comment by BlueLanM** [comment]
> PR title是不是有点描述不准确?

**Pull request closed without merging**
