### PR TITLE
fix: add visibility:hidden to selector:after

### PR DESCRIPTION
**Pull request by tchen-l**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/issues/17334

### 💡 Background and solution
在某些情况下，Select会显示字母A；给`-selector:after`加上了`visibility:hidden;`样式

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     In some cases, Select will display the letter A      |
| 🇨🇳 Chinese |      在某些情况下，Select会显示字母A     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 435cbec</samp>

Fix flickering bug in multiple select component by hiding input element. Change `visibility` property in `components/select/style/multiple.tsx`.

### <samp>🤖 Generated by Copilot at 435cbec</samp>

* Fix the flickering effect of the multiple select component by adding `visibility: 'hidden'` to the input element style ([link](https://github.com/ant-design/ant-design/pull/42651/files?diff=unified&w=0#diff-bdbff67724f9cb38a989e08057fac4b1dbbffcb715ecb8597db624ffd72f3ab5R75))

### CODE REVIEW

**Comment by afc163** [comment]
还需要发一个 PR 到 4.x-stable 分钟，你遇到的问题是 4.x 的，也需要修一下。

**Comment by 895433995** [comment]
> 还需要发一个 PR 到 4.x-stable 分钟，你遇到的问题是 4.x 的，也需要修一下。

好的

**Review by afc163 — APPROVED** [review]

**Comment by rawbin-** [comment]
大佬们，这个昨天我们也发现了，为啥是昨天出现呢，以前重来没发现过。

**Comment by afc163** [comment]
静态文件的编码问题，看看是不是变成 GB*** 或是其他非 UTF 的編碼了。

**Comment by rawbin-** [comment]
按理说编码这种八百年不会动的

**Pull request merged**
