### PR TITLE
fix: rlt style of columns

### PR DESCRIPTION
**Pull request by TrueMoein**
This fix should exist in rtl styles.

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix the rtl style of Col.         |
| 🇨🇳 Chinese |  修复 Col RTL 样式。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by xrkffgg** [comment]
Why did you remove it? Could you provide a example

**Comment by TrueMoein** [comment]
> Why did you remove it? Could you provide a example

Hi, in the original style we have ( `max-width: 100%` ) and it's fine. but in RTL `width: 100%` added recently and it's broke the grid.

**Comment by xrkffgg** [comment]
I add this because https://ant.design/components/list/#components-list-demo-resposive

If don't have `widht: 100%`, it will be

image

Maybe should add this only in List Component

**Comment by TrueMoein** [comment]
Yes, thats right. I capture this columns screenshot with and without this style in the original document of antd right now.

chrome-capture

**Comment by TrueMoein** [comment]
Dear @xrkffgg 

Maybe we don't need ` float: right;` style anymore. `flex` and main `direction: rlt;` handle it for us.
try it. then you can remove whole:

```
.@{ant-prefix}-col {
  &&-rtl {
    float: right;
    width: 100%;
  }
}
```

It's fixed the issue for List Components too.

**Pull request merged**
