### PR TITLE
 feat: InputNumber support addon 

### LINKED ISSUE #14284: Allow prefix/suffix and addonBefore/addonAfter on InputNumber just like Input component
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I was working on a custom input that formats the entered data into monetary value.

Something like: `9876.12` => `9,876.12` and also wanted to add a `$` prefix into the input without being part of the input value.

I noticed we can do that with the `Input` component but in order to format the entered value to the format I wanted I realized it was not going to be as easy as `InputNumber` with `formatter` and `parser` props.

I ended up wrapping up an `InputNumber` into another component which accepts all the same props as `InputNumber` plus the `prefix` option and made it look exactly as `Input`.

The render method looks something like

```jsx
render() {
  const { prefix, ...inputNumberProps } = this.props;

  return (
    <span className="my-custom-component">
      <span className="prefix">{prefix}</span>
      <InputNumber {...inputNumberProps} />
    </span>
  );
}
```

I think it would be useful if `InputNumber` accepts a `prefix` prop for cases like this.

### What does the proposed API look like?
The use and result should be exactly as `Input`.

`<InputNumber prefix="$" />`

`<InputNumber prefix={<span>$</span>} />`

### PR DESCRIPTION
**Pull request by Austaras**
### 🤔 This is a ...

- [x] New feature

I have no actual idea how to implement suffix icon and there's no reference, so maybe later

### 🔗 Related issue link

partially fix #14284 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      add `addonBefore` and `addonAfter` to InputNumber    |
| 🇨🇳 Chinese |    InputNumber 增加   `addonBefore` 和 `addonAfter` 属性支持   |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Austaras** [comment]
@afc163 could you take some time review this?

**Comment by Austaras** [comment]
updated for ci

**Comment by Austaras** [comment]
The failed test is also failed in original repo's feature branch

**Comment by FreeFrags** [comment]
Was going to make an issue for this too! Thank you for adding this feature, lets hope it gets merged soon!

**Comment by simonelnahas** [comment]
Thanks for putting in the work @Austaras ! Glad to see someone finally fixing this.

Thank you for creating the `AddonBefore`/`AddonAfter`.

From what i can see you are still missing to replicate the prefix and postfix behaviour.
Like this: 
image

**Comment by Austaras** [comment]
@simonelnahas I'd like to, but there's neither reference implementation nor prototype for input number with pre/postfix, and I have no idea how to deal with the position of arrows of input number and prefix, so I'll leave it to others.

**Comment by simonelnahas** [comment]
Okay as long as we keep the issue open then. Then this PR will not close #14284

**Comment by Austaras** [comment]
I have rebased on feature and all tests seem to pass, @afc163 can we get this merged?

**Comment by mlshvdv** [comment]
Need this feature! Looks nice!

**Review by afc163 — APPROVED** [review]

**Pull request merged**
