### PR TITLE
fix(message): call onClose after removeNotice

### LINKED ISSUE #38524: message.loading 当duration设置为0时，手动关闭无法触发onclose
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-0o3hz8?file=/index.js)

### Steps to reproduce

点击按钮

### What is expected?

控制台打印need log close msg与message close

### What is actually happening?

只打印了need log close msg

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 18.2 |
| System | window 11 |
| Browser | electron |

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- fix: #38524 

### 💡 Background and solution

should call onClose after removeNotice

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | should call onClose after removeNotice |
| 🇨🇳 Chinese | 移除消息后应该调用一下`onClose`方法 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by kiner-tang** [comment]
It seem that the CI Broken is not cause by this pr
image

**Comment by kiner-tang** [comment]
Can someone review this pr for me? @afc163

**Comment by kiner-tang** [comment]
> Can someone review this pr for me? @afc163

没有人帮忙review一下这个pr么？@afc163

**Comment by yoyo837** [comment]
提交到4.x-stable分支吧

**Comment by kiner-tang** [comment]
> 提交到4.x-stable分支吧

ok

**Comment by yoyo837** [comment]
Move to #38669

**Pull request closed without merging**
