### PR TITLE
added onBlur & onFocus functions to properties

### PR DESCRIPTION
**Pull request by pbrink231**
These can be called just like onChange as a property in the autocomplete but are not documented right now.

First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by yesmeck** [comment]
AutoComplete 的属性不是 Select 超集。

**Comment by yutingzhao1991** [comment]
那这个 MR 里面的 onBlur 和 onFocus 呢？ 我看这两个是在 SelectProps 里面定义的，而不是 AbstractSelectProps。

**Comment by yesmeck** [comment]
交集的部分可以提到 AbstractSelectProps 里。

**Comment by amiram** [comment]
@pbrink231  onBlur and onFocus are not compiled with typescript. If AutoComplete props are extending AbstractSelectProps, then onBlur and onFocus are not part of it. Are you sure it is working?

**Pull request merged**
