### PR TITLE
fix ant-picker-range-arrow style

### PR DESCRIPTION
**Pull request by ztwqy6688o**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix ant-picker-range-arrow style  |
| 🇨🇳 Chinese |  修复 ant-picker-range-arrow 样式  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
图片

没有重现问题。

**Comment by ztwqy6688o** [comment]
上面的截图是官网效果，是可以复现的

**Comment by afc163** [comment]
@ztwqy6688o 你的浏览器版本是多少？

**Comment by afc163** [comment]
1. 建议升级到最新 Chrome 版本
2. 我们还是应该做一个向下兼容，不支持的 clip-path 的浏览器也能看。可以跟踪 https://github.com/ant-design/ant-design/issues/35010

@MadCcc

**Comment by ztwqy6688o** [comment]
我的版本是86.0.4240.198，因为客户用的是360、搜狗浏览器这种浏览器，所以需要对低版本做兼容。

**Pull request closed without merging**
