### PR TITLE
fix: reduce bundle size

### PR DESCRIPTION
**Pull request by yoyo837**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
Same as #42502

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   ConfigProvider: 🐞 Repair ConfigProvider importFormProvider, error import something useless from 'rc - field - form` . https://github.com/ant-design/ant-design/issues/42499        |
| 🇨🇳 Chinese |   ConfigProvider: 🐞 修复 ConfigProvider 引入FormProvider时，错误引入 'rc-field-form' 其他的无关依赖。https://github.com/ant-design/ant-design/issues/42499        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at d39bb14</samp>

Refactor `FormProvider` import to use `FormContext` module. This improves the bundle size by avoiding importing the whole `rc-field-form` package.

### <samp>🤖 Generated by Copilot at d39bb14</samp>

* Update the import path of `FormProvider` to use `FormContext` module instead of default export ([link](https://github.com/ant-design/ant-design/pull/42507/files?diff=unified&w=0#diff-0a9895a32672ec55a084aa7165fc8666008942903b8e51e30b662e9e1ecffb56L3-R3)). This reduces the bundle size by avoiding importing the whole `rc-field-form` package. This change is part of the refactoring for issue #30311 and pull request #30312.

### CODE REVIEW

**Comment by li-jia-nan** [comment]
怎么还大了

**Review by li-jia-nan — APPROVED** [review]

**Comment by afc163** [comment]
不对劲

**Comment by yoyo837** [comment]
不清楚为什么先关

**Comment by BanShan-Alec** [comment]
有意思的问题😶‍🌫️，我这边本地初步排查了一下，可能与 mini化 js 有关。

我分别对两个分支的打包产物的大小进行对比，发现[yoyo837-patch-1](https://github.com/ant-design/ant-design/tree/yoyo837-patch-1)的打包产物size比`master`小，但经过min化后，size却比`master`的要大。

v5 打包 0

v5 打包 3

使用 source-map-explorer 分别进行分析依赖的体积，没发现什么异常

v5 打包 2

v5 打包 1

**Comment by BanShan-Alec** [comment]
当然这可能与我的本地环境可能有关，需要进一步排查 @yoyo837

**Comment by yoyo837** [comment]
> 有意思的问题😶‍🌫️，我这边本地初步排查了一下，可能与 mini化 js 有关。
> 
> 我分别对两个分支的打包产物的大小进行对比，发现[yoyo837-patch-1](https://github.com/ant-design/ant-design/tree/yoyo837-patch-1)的打包产物size比`master`小，但经过min化后，size却比`master`的要大。
> 
> v5 打包 0
> 
> v5 打包 3
> 
> 使用 source-map-explorer 分别进行分析依赖的体积，没发现什么异常
> 
> v5 打包 2
> 
> v5 打包 1

有意思的结论，有诉求了再继续讨论吧

**Comment by yoyo837** [comment]
Move to #42604

**Pull request closed without merging**
