### PR TITLE
fix: fix cycle-deps

### LINKED ISSUE #41444: vite打包时报模块相互依赖
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

使用vite@4.2.1打包antd@5.3.2版本的代码

### What is expected?

模块间的引用关系正常，打包不报异常

### What is actually happening?

模块间发生了相互依赖导致打包弹出异常信息

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | 19045.2728 |
| Browser | 111.0.1661.51 |

---
Export "genPresetColor" of module "node_modules/antd/es/style/presetColor.js" was reexported through module "node_modules/antd/es/style/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/antd/es/tag/style/index.js" to point directly to the exporting module or reconfigure 
"output.manualChunks" to ensure these modules end up in the same chunk.

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/41444

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix cycling dependecies of `genPresetColor`.        |
| 🇨🇳 Chinese |    修复内部 `genPresetColor` 循环依赖问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
ci 里能检查出来么？

**Comment by yoyo837** [comment]
> ci 里能检查出来么？

eslint其实就可以, 但总感觉antd的lint配的有问题

**Comment by MadCcc** [comment]
循环依赖只有 vite 或者 webpack 打包的时候检查的出来。这里是因为 esm 的 import 有循环，但是实际引用的方法的源文件是没有循环依赖的，所以 webpack 打包检查不出来。vite 在 dev 还是 esm 所以会有问题。
这个倒是可以加一个 vite 的项目打包检查。

**Comment by MadCcc** [comment]
> > ci 里能检查出来么？
> 
> eslint其实就可以, 但总感觉antd的lint配的有问题

没启用这个规则

**Review by PeachScript — APPROVED** [review]
+1

**Comment by Wxh16144** [comment]
> 这个倒是可以加一个 vite 的项目打包检查

像 [mock-project-build](https://github.com/ant-design/ant-design/blob/86b26e69351341b6364630c037628c15c2b8cb2d/.github/workflows/mock-project-build.yml) 这个一样么?

**Pull request merged**
