### PR TITLE
fix: options missing id

### LINKED ISSUE #44505: Form表单报错Incorrect use of <label for=FORM_ELEMENT>
### Reproduction link

[https://ant-design.antgroup.com/components/form-cn](https://ant-design.antgroup.com/components/form-cn)

### Steps to reproduce

官网Form表单页面打开控制台即可复现
进入Form组件页面, 打开控制台, 点击报错数字即可展示详情
image

### What is expected?

控制台无报错

### What is actually happening?

一堆Form报错问题

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | react |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #44505

### 💡 Background and solution

补了一下文档 label for，发现可以优化一下 options

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Checkbox.Group & Radio.Group `options` add missing `id` props.     |
| 🇨🇳 Chinese |     Checkbox.Group 与 Radio.Group 的 `options` 添加 `id` 属性支持。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at e9df555</samp>

This pull request improves the accessibility and code style of the theme picker and the checkbox and radio groups by adding and passing `id` props to the components. It also adds test cases and formats the test files for the `Checkbox.Group` and `Radio.Group` components. It modifies the `ThemePicker.tsx`, `ColorPicker.tsx`, `RadiusPicker.tsx`, and `index.tsx` files to use the `id` props and link the labels with the inputs.

### <samp>🤖 Generated by Copilot at e9df555</samp>

*  Add `id` prop to `Checkbox.Group`, `Radio.Group`, `ThemePicker`, `ThemeColorPicker`, and `RadiusPicker` components to improve accessibility ([link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-d3e984f0984d6a44c780ab883b2f78b2df8029b1ce515d879e60879bb425fa63R19), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-d3e984f0984d6a44c780ab883b2f78b2df8029b1ce515d879e60879bb425fa63R128), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-85547b1be5fa04a65a8ea1ce2c7f454ee66c4bb75c4453f7491f0c2c0f651996R272-R278), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-94794a2156476ac265df2274830a3c700b50b66ef4bf24f7558ab3c2885f7749R82), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-3bde68ef6e79970a3dd6e92cf661a4eb62e1bec50dbbb33c49833837e4f5e8cdR256-R262), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-bb71d3e7437a45c3978afff7a00abefa4e0c15a401677f1a732c773f7027d36eR38), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-bb71d3e7437a45c3978afff7a00abefa4e0c15a401677f1a732c773f7027d36eL69-R70), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-bb71d3e7437a45c3978afff7a00abefa4e0c15a401677f1a732c773f7027d36eR99), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-9acb0fe7a2ae211f88fcb1122ef6f12b644b1ee22e33c47bded7cce09b8e7009L2-R10), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-9acb0fe7a2ae211f88fcb1122ef6f12b644b1ee22e33c47bded7cce09b8e7009R20), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dL36-R84), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dL85-R92), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dL97-R104), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL537-R550))
*  Refactor `Radio.Group` component in `.dumi/pages/index/components/Theme/index.tsx` to use `options` prop instead of `Radio` children ([link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL537-R550))
*  Reorder import statements in `ThemePicker.tsx` and `Group.tsx` ([link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dL1-R5), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-d3e984f0984d6a44c780ab883b2f78b2df8029b1ce515d879e60879bb425fa63L1-R8))
*  Add empty lines at the beginning of `group.test.tsx` files ([link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-85547b1be5fa04a65a8ea1ce2c7f454ee66c4bb75c4453f7491f0c2c0f651996R2), [link](https://github.com/ant-design/ant-design/pull/45287/files?diff=unified&w=0#diff-3bde68ef6e79970a3dd6e92cf661a4eb62e1bec50dbbb33c49833837e4f5e8cdR3))

### CODE REVIEW

**Review by MadCcc — APPROVED** [review]

**Comment by aide-cloud** [comment]
感觉没有完全解决, 除了PR里面修复的组件, input、select等组件也有同样问题, 希望统一处理一次

**Comment by wangyingjie123** [comment]
并没有完全解决，radioGroup还是有问题

**Comment by noahge0923** [comment]
radioGroup依旧存在问题。

**Comment by yoyo837** [comment]
@wangyingjie123 @noahge0923 帮忙来个复现开个新issue？

**Pull request merged**
