### PR TITLE
fix: wireframe style for popconfirm

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
Before: 
image
After:
image

去掉了 Popover 的 `_overlay`，Popconfirm 改用 `content`。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Popconfirm style when `wireframe` is `true`.     |
| 🇨🇳 Chinese |       修复 Popconfirm 组件线框化后的样式。    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
搞个各组件 purerender 的通用测试，测一下 snapshot 和 argos-ci

**Comment by MadCcc** [comment]
> 搞个各组件 purerender 的通用测试，测一下 snapshot 和 argos-ci

可以的，之前 pureRender 全都跳过了

**Comment by afc163** [comment]
这样能解决各种弹层组件没有 E2E 相关测试的老大难问题。

**Comment by MadCcc** [comment]
看了下 pureRender argos 已经测了

**Comment by afc163** [comment]
wireframe 和 pureRender 有啥区别？

**Comment by MadCcc** [comment]
> wireframe 和 pureRender 有啥区别？

wireframe 是线框化 token，对 v4 的线框风格还原

**Review by afc163 — APPROVED** [review]

**Pull request merged**
