### PR TITLE
fix: add NODE_ENV for warning

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

虽然 `warning` 方法内部也判断了 `NODE_ENV`，不会在生产打印出来，但是外面还是可以加一下，这样 webpack 编译的时候就跳过这个 `fucntion` 了

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix: add NODE_ENV for warning |
| 🇨🇳 Chinese |          - |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 1d200e2</samp>

Suppress icon warning in production mode. The file `components/icon/index.ts` was modified to only show a warning message in development mode, as part of a pull request to optimize the ant-design library.

### <samp>🤖 Generated by Copilot at 1d200e2</samp>

*  Prevent warning from being displayed in production mode by adding `NODE_ENV` check ([link](https://github.com/ant-design/ant-design/pull/43574/files?diff=unified&w=0#diff-306957aacaa8a543378e2bd85a70d01ae797167fe88fe2d17b9c6ddc99ee17ccL4-R6))

### CODE REVIEW

**Comment by li-jia-nan** [comment]
微信图片_20230715144559

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
主要是能省一点体积。

**Comment by afc163** [comment]
诶，居然没反应出来？

图片

**Comment by li-jia-nan** [comment]
> 诶，居然没反应出来？

可能是改动太小了吧

**Pull request merged**
