### PR TITLE
fix: Space missing in button

### LINKED ISSUE #15342: Button removing space when using interpolation in the children
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/jvolkl16p3)

### Steps to reproduce
Use JSX interpolation in Button children together with normal string

### What is expected?
Space should be preserved just like when there is no interpolation

### What is actually happening?
Space does not show because extra spans are created

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | windows |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

fix #15342

### 💡 Solution

Merge text if can be a string

### 📝 Changelog

Fix Button missing space with mixed content.

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by ztplz — APPROVED** [review]

**Comment by afc163** [comment]
有点复杂，试试给 https://github.com/ant-design/ant-design/pull/16551/files#diff-9683e91e4b3d7b109ea643fa8944bd78R61 这里的 span 一个  `white-space: pre;` 如何？

**Comment by zombieJ** [comment]
> 有点复杂，试...

这样遇到带换行的会有点怪异：
```jsx
const a = `
Hello
World
`;

<Button type="primary" className="aaa">{a}</Button>
```

屏幕快照 2019-05-13 下午5 51 51

**Comment by afc163** [comment]
把换行符替换掉如何？

**Comment by zombieJ** [comment]
> 把换行符替换掉如何？

那其实和我这个方案差不多了，都是要改 children ……

```jsx
<Button>
  {`
111
`}
  {`
222
`}
</Button>
```

**Comment by ztplz** [comment]
就这么改吧  貌似没有什么好的办法

**Review by afc163 — APPROVED** [review]

**Comment by jinxin0112** [comment]
不想要这个空格，怎么去掉

**Comment by jinxin0112** [comment]
看了实现，让子元素不唯一能够去掉空格，感觉很 hack

**Comment by afc163** [comment]
@jinxin0112 ConfigProvider

**Pull request merged**
