### PR TITLE
Feature antd 3.0/spinning indicator

### PR DESCRIPTION
**Pull request by kossel**
Added `indicator` props to `Spin` component as discussed in #7950. re-submitting since I messed up with the rebase...

### CODE REVIEW

**Comment by kossel** [comment]
I did everything again, my PR is aligned to antd-3.0 branch, I ran `npm run test` on my branch locally and shows all tests passed, however CI keep saying the snapshots don't match for Calendar component. any idea?

**Comment by jljsj33** [comment]
感觉没啥意义，，如果不用这设计，，只要个旋转的动画，为什么要用 spin 组件？？直接用你 indicator 的内容加个 antRotate 不是更简单？

**Comment by kossel** [comment]
This gives the flexibility to the developer to put other styles of loading animation such like, loading dots, loading bard or animation that many not include a "rotation" animation. Making it into Spin component makes the developers can still take the advantages of other props such as `delay`, `loading`. `tip` etc without having to rewrite a completely the same features in another component (that's what we are doing).

btw, I don't know why npm run test pass in local branch, but not in CI

**Comment by afc163** [comment]
It conflict, try to resolve it.

**Comment by kossel** [comment]
I solved the conflicts, but CI is still broken, I had to run `npm run test -- -u` to update snapshot for the new props, but it also updated calendar's snapshot, what should I do? @afc163

**Comment by benjycui** [comment]
@kossel just rebase, thanks.

**Comment by kossel** [comment]
rebased and solved conflict, still some snapshots don't match

**Comment by benjycui** [comment]
Don't commit any snapshots except `components/spin/__tests__/__snapshots__/demo.test.js.snap`

**Comment by kossel** [comment]
Yes sir!

**Comment by jaspersorrio** [comment]
Wow this is a great PR! This means I can now customize the table spinner too!

**Pull request merged**
