### PR TITLE
docs(picker): support custom format

### PR DESCRIPTION
**Pull request by kerm1it**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | DatePicker support custom format.          |
| 🇨🇳 Chinese | 日期选择器支持自定义格式化。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/date-picker/demo/format.md](https://github.com/ant-design/ant-design/blob/docs-picker/components/date-picker/demo/format.md)
[View rendered components/date-picker/index.en-US.md](https://github.com/ant-design/ant-design/blob/docs-picker/components/date-picker/index.en-US.md)
[View rendered components/date-picker/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/docs-picker/components/date-picker/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
feature 分支吧。

**Comment by afc163** [comment]
不是 upload。

**Comment by Kermit-Xuan** [comment]
我看之前的 PR 是在 master 更新的？

**Comment by afc163** [comment]
那个也合并回 feature 了，还是统一放 feature 吧。

**Comment by Kermit-Xuan** [comment]
https://github.com/ant-design/ant-design/pull/26845

已经更新了，我就说本地怎么已经有分支了。

**Comment by afc163** [comment]
哦，我都忘了。

**Comment by Kermit-Xuan** [comment]
是因为这次要合并到 master，master 上还没更新呢，到时候发 minor 版本就好了。

**Pull request closed without merging**
