### PR TITLE
docs(ConfigProvider): update ConfigProvider demo

### PR DESCRIPTION
**Pull request by notverysalty**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |        update ConfigProvider demo    |
| 🇨🇳 Chinese |       更新 ConfigProvider 案例     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
感觉 220px 还是有点挤，要不干脆改成 240px？

**Comment by afc163** [comment]
不给宽度，默认应该就行。

**Comment by notverysalty** [comment]
> 不给宽度，默认应该就行。

是的，刚刚试了一下，谢谢大佬😂

**Comment by notverysalty** [comment]
> 感觉 220px 还是有点挤，要不干脆改成 240px？

改成默认宽度了😂

**Review by li-jia-nan — APPROVED** [review]

**Pull request merged**
