### PR TITLE
Document argument order swap in sorter function.

### PR DESCRIPTION
**Pull request by JesperWe**
First of all, thanks for your contribution! :-)

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you propose PR to correct branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by yesmeck** [comment]
I'v add a link to MDN. :)

**Comment by JesperWe** [comment]
I saw that. I just wanted it to mention the argument swapping because I did implement that myself at first, and then it was always sorting in the same direction because you swapped the args once and I swapped them back again :-D

**Comment by yesmeck** [comment]
@JesperWe I reverted your change, because you don't need care about the order of the arguments.

**Comment by JesperWe** [comment]
Well, my point was that "you don't need to care" is non-intuitive because normally you do...

**Comment by yesmeck** [comment]
Actually, the order of compare function's arguments is not sequential.  Different browsers have different sorting algorithm.

http://stackoverflow.com/questions/234683/javascript-array-sort-implementation

**Comment by JesperWe** [comment]
That's not the point I was trying to document. The sorter takes two arguments (a,b) and compare them. Normally for ascending sort you return 1 if `a > b`, and for descending you return 1 if `a < b`.

Now Ant Design Table will give you the first row as `a` and the following row as `b` for ascending sort, and the opposite for descending. This way the compare function does **not** need to know if it is doing ascending or descending, which is very smart and good. 

But it is not the way Array.sort() usually works. Usually you need to know which way you are sorting **in the compare function**, and change your return value accordingly.

**Comment by JesperWe** [comment]
...or maybe you are not swapping the arguments, but just changing the sign of the return value, which has exactly the same effect :-) !

**Comment by yesmeck** [comment]
> you are not swapping the arguments, but just changing the sign of the return value

Yes, your are right now.

**Pull request merged**
