### PR TITLE
fix: message invalid when contextPopupContainer update

### PR DESCRIPTION
**Pull request by zuolung**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#33781

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    message is invalid when the contextPopupContainer is destroyed and recreated    |
| 🇨🇳 Chinese |   当 contextPopupContainer销毁后重新创建,message去效      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Could you add a test case？

**Comment by zuolung** [comment]
test case refer https://codesandbox.io/s/antd-reproduction-template-forked-oz34r?file=/index.js:899-958

**Comment by afc163** [comment]
ci 没过

**Comment by zuolung** [comment]
[rc-notification commit the pr to solve it and add test.](https://github.com/react-component/notification/pull/190)

**Pull request closed without merging**
