### PR TITLE
fix(dumi): use important when setting code style

### PR DESCRIPTION
**Pull request by LuciNyan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Similar to this issue: #38680

### 💡 Background and solution

The ones provided by the prism override the styles we set manually.

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Mandatory styling via `!important` to prevent styles from being overwritten by prism     |
| 🇨🇳 Chinese |      通过 !important 强制设置样式以防止样式被 prism 覆盖     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
@PeachScript 看看，这个会不会影响别的地方。

**Review by PeachScript — CHANGES_REQUESTED** [review]
这个在 antd 里解不合适，shadow 本身是非预期的，有时间的话可以给 dumi 提交 PR：https://github.com/umijs/dumi/blob/master/src/client/theme-default/builtins/SourceCode/index.less#L19

另外尽量用提升优先级的方式修复而不是 `!important`

**Comment by LuciNyan** [comment]
> 这个在 antd 里解不合适，shadow 本身是非预期的，有时间的话可以给 dumi 提交 PR：https://github.com/umijs/dumi/blob/master/src/client/theme-default/builtins/SourceCode/index.less#L19
> 
> 另外尽量用提升优先级的方式修复而不是 `!important`

Thanks for your suggesting!

**Comment by PeachScript** [comment]
> Thanks for your suggesting!

不客气，那 PR 先 close 了，有兴趣的话该可以在上面 dumi 仓库的源代码链接处进行修复

**Pull request closed without merging**
