### PR TITLE
feat: add fr_CA locale

### PR DESCRIPTION
**Pull request by liufenghua808**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #29717
close #29727

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fr_CA       |
| 🇨🇳 Chinese |      法语（加拿大）     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by liufenghua808** [comment]
At least 1 approving review is required by reviewers with write access请问这是需要一位审批审批之后才能提merge吗？

**Comment by yoyo837** [comment]
为何关闭？等CI通过

**Comment by liufenghua808** [comment]
本地 第一次执行 npm test -- -u 全部通过，为什么再次执行会有一个没通过呢，会有下面的log:
 Expected number of calls: >= 1
 Received number of calls:    0

**Comment by liufenghua808** [comment]
本地刚又执行的 npm test -- -u 命令如下：

Test Suites: 206 passed, 206 total
Tests:       5 skipped, 2481 passed, 2486 total
Snapshots:   1391 passed, 1391 total
Time:        369.115 s
Ran all test suites.

**Comment by yoyo837** [comment]
删除lock文件和node_modules, 重新安装后再跑

**Comment by liufenghua808** [comment]
> 删除lock文件和node_modules, 重新安装后再跑

> 这是按照您的建议操作后重跑的结果：

**Comment by liufenghua808** [comment]
麻烦再给看下接下来如何处理呢？本地测试能过呀？还有其他必须做的吗？

**Comment by yoyo837** [comment]
落后3个提交，rebase 下上游feature分支。

**Comment by liufenghua808** [comment]
> 落后3个提交，rebase 下上游feature分支。
> 本地code和远程feature分支最新code已经是一样了，您说的rebase指什么？我理解的就是rebase到和现在feature分支 code 同步就行

**Pull request closed without merging**
