### PR TITLE
docs(Layout): 固定头部的 demo 改为使用 `sticky`

### PR DESCRIPTION
**Pull request by ZCY-G**
使用 `sticky` 可以避免其他组件位移。

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
话说Demo需不需要支持IE呢 🤔

**Comment by ZZZCNY** [comment]
> 话说Demo需不需要支持IE呢 🤔

我认为没什么必要，React 18 和 Ant Design 5 不是都不支持吗

**Comment by yoyo837** [comment]
> > 话说Demo需不需要支持IE呢 🤔
> 
> 我认为没什么必要，React 18 和 Ant Design 5 不是都不支持吗

master 还是 4.x

**Comment by afc163** [comment]
我觉得问题不大，不过要更新一下 snapshot

**Pull request closed without merging**
