### PR TITLE
test: argos-ci test

### PR DESCRIPTION
**Pull request by shaodahong**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/button/demo/basic.md](https://github.com/shaodahong/ant-design/blob/test-argos/components/button/demo/basic.md)

### CODE REVIEW

**Comment by shaodahong** [comment]
Report to https://developercommunity.visualstudio.com/content/problem/1233968/pr-not-trigger-push-pipeline.html

**Comment by shaodahong** [comment]
应该可以了，对 fork 仓库生效，并且 check status 也会显示如常

**Comment by afc163** [comment]
日期是个问题，每天第一个 ci 都会挂，需要把日期 mock 掉。

**Pull request merged**
