### PR TITLE
feat: Form support multiple layout

### PR DESCRIPTION
**Pull request by crazyair**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Form support multiple layout     |
| 🇨🇳 Chinese |     Form 支持多种布局      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by crazyair** [comment]
咨询了设计，设计上不会出现一个表单多种布局的场景，如果是 Steps 表单，也只会是一个 step 一个布局，那可以受控 Form 的 layout，切换 step 修改 layout。

关联的 2 个 issue，不清楚还有没有强烈的需求，或者能提供业务中的表单示例

**Comment by afc163** [comment]
https://procomponents.ant.design/components/form#proform-demo-base 这里大多数是这种表单。

**Comment by crazyair** [comment]
> https://procomponents.ant.design/components/form#proform-demo-base 这里大多数是这种表单。

设计说，水平布局有局限，更推荐垂直布局

**Comment by afc163** [comment]
> 咨询了设计，设计上不会出现一个表单多种布局的场景

这个在业务中很常见的。

https://new-issue.ant.design/
https://getbootstrap.com/docs/4.0/components/forms/#custom-styles

图片

**Comment by crazyair** [comment]
这个最多是 labelCol wrapperCol 不一致

**Comment by crazyair** [comment]
> 这个看不出来是混合布局，给一个更贴近真实业务里的案例？

这样可以吗
image

**Comment by crazyair** [comment]
https://github.com/ant-design/ant-design/pull/47591

**Pull request closed without merging**
