### PR TITLE
refator: update rc-dialog to remove `rc-animate`

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Refactor Dialog. It will remove all dom element when closed.        |
| 🇨🇳 Chinese |   重构 Dialog 组件，现在关闭时将完全清理相关 Dom 节点。       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
重构 5 小时，修复测试 2 天。每个直接在 `document.body` 上额外渲染的 React Instance 都是伤不起的天使！😭

**Review by chenshuai2144 — APPROVED** [review]

**Review by afc163 — COMMENTED** [review]
效果看着不错。

**Review by afc163 — APPROVED** [review]

**Review by shaodahong — APPROVED** [review]
只有单元测试，碰到 dom 和动画只能 hack ，😅

**Comment by zombieJ** [comment]
@shaodahong 这个合完了，你的 image 也升级一下依赖哈~~

**Comment by shaodahong** [comment]
> @shaodahong 这个合完了，你的 image 也升级一下依赖哈~~

https://github.com/ant-design/ant-design/pull/26915

已经升了……

**Pull request merged**
