### PR TITLE
refactor: migrate lifecycle method

### PR DESCRIPTION
**Pull request by orzyyyy**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?
Related to https://github.com/ant-design/ant-design/issues/9792

### CODE REVIEW

**Comment by afc163** [comment]
This pull request **introduces 1 alert** when merging 4dc533c2023d32fbe2e07e0b13a1157bb2803ec7 into dd435afadb45c0bb62908ded76f8c12da7dd4d41 - [view on LGTM.com](https://lgtm.com/projects/g/ant-design/ant-design/rev/pr-cb728e2a84d5c07c2b3aea180e9824c9e79b130a)

**new alerts:**

* 1 for Potentially inconsistent state update

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by afc163** [comment]
This pull request **introduces 2 alerts** when merging 4601144f3fcdca90aba4267f57f70df6756e1052 into dd435afadb45c0bb62908ded76f8c12da7dd4d41 - [view on LGTM.com](https://lgtm.com/projects/g/ant-design/ant-design/rev/pr-2c71c19835be2ccf7df3ccec71840edca4ca2a6a)

**new alerts:**

* 2 for Potentially inconsistent state update

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by zombieJ** [comment]
Affix 先别搞，PR 重构做了：#15150

**Comment by zy410419243** [comment]
👌

**Comment by afc163** [comment]
This pull request **introduces 2 alerts** when merging 7642cbf18d92b8868bbea4ec42f4ba7ed3d5dde5 into dd435afadb45c0bb62908ded76f8c12da7dd4d41 - [view on LGTM.com](https://lgtm.com/projects/g/ant-design/ant-design/rev/pr-793b76bee3b50c586abdf379024bf8f7d0316d35)

**new alerts:**

* 2 for Potentially inconsistent state update

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by afc163** [comment]
优化了一下代码：#15286

**Pull request merged**
