### PR TITLE
Kurdish translation

### PR DESCRIPTION
**Pull request by ahalimkara**
Kurdish translation (Kurmancî) for Kurdistan Region of Iraq

### CODE REVIEW

**Comment by yesmeck** [comment]
Hello @ahalimkara `rc-calendar@9.5.0` has released includes Kurdish.

**Comment by ahalimkara** [comment]
@yesmeck Thank you! I have updated files.

**Comment by yesmeck** [comment]
Could you add Kurdish  to test ? See https://github.com/ant-design/ant-design/blob/master/components/locale-provider/__tests__/index.test.js#L41

**Comment by ahalimkara** [comment]
I have added, but it seems there is a conflict with zhCN, how can I resolve?

**Comment by yesmeck** [comment]
You need rebase to `feature-3.2` branch.

**Comment by ahalimkara** [comment]
@yesmeck please check #9064

**Pull request closed without merging**
