### PR TITLE
fix: TimePicker compatible kk:mm format

### PR DESCRIPTION
**Pull request by cooljser**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/38141

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | time-picker compatible kk:mm format |
| 🇨🇳 Chinese | 日期组件兼容 kk:mm 格式 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
加个用例

**Comment by afc163** [comment]
用例挂了

**Comment by lbarakidouji** [comment]
我在本地跑了一下，使用 kk:mm 可以显示出时间哪一列选择，但是没有 24 这个选项

**Comment by afc163** [comment]
冲突了，重新修一下？

**Comment by afc163** [comment]
ping

**Pull request closed without merging**
