### PR TITLE
feat: Azerbaijani translation

### PR DESCRIPTION
**Pull request by orkhan-huseyn**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

Azerbaijani locales were missing.

### 📝 Changelog

Added locales for Azerbaijani translation.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
`rc-picker` should be upgrade in `package.json`

**Comment by yoyo837** [comment]
Just only `rc-picker` Please.

**Comment by orkhan-huseyn** [comment]
What about `rc-pagination`?

**Comment by yoyo837** [comment]
Sorry, should include it, exclude that unrelated to this features.

**Pull request merged**
