### PR TITLE
style: Improve style z-order to fix some errors

### LINKED ISSUE #51420: 5.21.6 Tree.DirectoryTree点击复选框不触发onCheck
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/ji-ben-antd-5-21-5-forked-ws37c5)

### Steps to reproduce

5.21.5可选中：https://codesandbox.io/p/sandbox/ji-ben-antd-5-21-5-forked-3yx29c

5.21.6无法选中：https://codesandbox.io/p/sandbox/ji-ben-antd-5-21-5-forked-ws37c5

### What is expected?

点击复选框触发onCheck

### What is actually happening?

点击复选框不触发onCheck

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18 |
| System | macos |
| Browser | chrome |

### LINKED ISSUE #51430: Tree.DirectoryTree Expand/Collapse unexpectedly triggered onSelect callback
### Steps to reproduce

https://github.com/user-attachments/assets/165ea04c-c571-4ef3-81da-4078f02373b1

### What is expected?

不确定？ 之前的版本 比如 5.13.0 是不会触发。。

### What is actually happening?

点击 展开/收起 操作触发了 onSelect

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.2.0 |
| System | OSX |
| Browser | chrome 129.0.6668.101 |

### PR DESCRIPTION
**Pull request by Wxh16144**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [x] 🐞 Bug fix
- [x] 💄 Component style improvement

### 🔗 Related Issues

reason: https://github.com/ant-design/ant-design/pull/51210#issuecomment-2449051375

fix: #51420
fix: #51430

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

1. 普通 tree 展开图标存在一个右边距: see: https://ant-design-5-22-1.surge.sh/~demos/tree-demo-dynamic
image

     
2. checkbox  的垂直居中方式代码貌似有冗余，进行了删除 see：https://github.com/ant-design/ant-design/pull/51448/commits/6aec2f84627a4c978746860788f56ed8302c7986

3. 修复 #51420 ， #51430 问题（原因是层级不够，[修复方式](https://github.com/ant-design/ant-design/pull/51448/commits/714d2177eca73baed1954dbbedfac2ee66afef78)

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Tree.DirectoryTree: Improve style z-order to fix some errors      |
| 🇨🇳 Chinese |     Tree.DirectoryTree 改进样式层级以修复一些错误      |

### CODE REVIEW

**Comment by afc163** [comment]
lint 挂了

**Comment by Wxh16144** [comment]
> 更新一下代码，顺手测试一下 #51633 是否正常工作

ok 的

image

**Comment by Wxh16144** [comment]
> ready~, see: https://preview-51448-ant-design.surge.sh/~demos/tree-demo-directory-debug

ready again.

**Comment by afc163** [comment]
图片

这样会比较难看。

**Comment by Wxh16144** [comment]
> 这样会比较难看。

ok, 我再看看之前的样式是怎么样的～

**Review by afc163 — APPROVED** [review]

**Pull request merged**
