### PR TITLE
fix(Table): improve the order of merging inline styles in table header column

### LINKED ISSUE #51763: Table columns 支持设置 header column 的 align
### What problem does this feature solve?

Table columns 支持设置 header column 的 align。现在设置 align: 'right'，不仅仅是内容，header 也会 align right。想实现 header 居中，内容 align right

### What does the proposed API look like?

```js
{
  titleAlign: 'center'
}
```

### PR DESCRIPTION
**Pull request by Wxh16144**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [x] ❓ Other (about what?)

### 🔗 Related Issues

resolve #51763

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     improve the order of merging inline styles in table header column      |
| 🇨🇳 Chinese |     升级 rc-table, 改进 table header column 内联样式合并顺序      |

### CODE REVIEW

**Comment by zombieJ** [comment]
写一下 changelog

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
changelog 写一下？

**Comment by Wxh16144** [comment]
> changelog 写一下？

ready～，合并的时候看看 title 是否需要改一下 type. 方便 changelog 体现

**Comment by afc163** [comment]
改

**Comment by afc163** [comment]
feat 还是 fix？看上去不是新特性？

**Comment by Wxh16144** [comment]
> feat 还是 fix？看上去不是新特性？

fix 吧，改了合并顺序

**Pull request merged**
