### PR TITLE
style: fix Menu submenu margin

### PR DESCRIPTION
**Pull request by JarvisArt**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Menu SubMenu margin style. |
| 🇨🇳 Chinese | 修复 Menu SubMenu 间距问题。 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
有啥问题，描述一下？

**Comment by JarvisArt** [comment]
paddingBottom: 0.02,这个样式是为了修复v4中submenu的8px，而v5的margin为4px，所以不需要了
menu 例子看了一遍，submenu margin都正常了

image

image

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
https://app.argos-ci.com/ant-design/ant-design/builds/2891 看看 diff 是不是预期的。

**Comment by afc163** [comment]
看了一下是对的。

**Comment by JarvisArt** [comment]
menu 还存在不少问题，展开submenu会抖动、submenu

> 看了一下是对的。

是的

**Comment by afc163** [comment]
> menu 还存在不少问题，展开submenu会抖动、submenu

一个个修！

**Pull request merged**
