### PR TITLE
fix: menu a color for #25412

### LINKED ISSUE #25412: The selected style of the menu component submenu item is abnormal
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/shousuoshizicaidanxiangxuanzhongseyichang-b9ejd)

QQ截图20200703151119

### Steps to reproduce
1. Open the reproduction link
2. Zoom out the preview view
3. View omitted submenu items

### What is expected?
Only the selected menu item is highlighted

### What is actually happening?
All submenu items containing the `a` label are highlighted

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.x |
| System | windows 10 |
| Browser | last |

### PR DESCRIPTION
**Pull request by kaysonwu**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix #25412

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix `Menu.Item` use `a` tag color style issue.   |
| 🇨🇳 Chinese |   修复 `Menu.Item` 中内嵌的 `a` 标签颜色样式问题 |

Fix the color problem of a label when Menu.Item is selected

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
title、 changelog写一下

**Comment by kaysonwu** [comment]
title, changelog 写在什么地方？

**Comment by yoyo837** [comment]
image PR 的title 

和模版里的📝 Changelog

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/23830 的问题会重现么？

**Comment by kaysonwu** [comment]
不会影响，这个是针对子菜单拥有 a 标签的样式修复。不过，子菜单子级 a 高亮是否有必要存在，因为 `.ant-menu-item-selected` 类选择器会修饰了， 有必要的话 应该是把 这个 a 样式删除掉

**Comment by afc163** [comment]
image

**Comment by afc163** [comment]
image

**Comment by kaysonwu** [comment]
```less
&-vertical-right &-submenu-selected {
  a {
     color: @menu-highlight-color;
  }
}
```

上面的代码，因为上次的更新，实际上已经被下面的代码给覆盖了，所以删除上面的 a 才是最优的选择

```
&-selected a {
  color: @menu-highlight-color;
 }
```

**Comment by kaysonwu** [comment]
删除  `a` 选择器后，修复 #25412 

```less
&-vertical-left &-submenu-selected,
  &-vertical-right &-submenu-selected {
    a {
       color: @menu-highlight-color;
  }
}
```

微信图片_20200703202508

附上对 #23830 的测试结果：

cccccc

**Pull request merged**
