### PR TITLE
test: rename js => ts

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | test: rename js => ts |
| 🇨🇳 Chinese | test: rename js => ts |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
是个CI failed 是不是和https://github.com/ant-design/ant-design/pull/37856 有关.

**Comment by li-jia-nan** [comment]
> 是个CI failed 是不是和#37856 有关.

是的，不过还没确定，本地不能复现，我还在尝试

**Comment by afc163** [comment]
ci broken

**Comment by afc163** [comment]
还是挂的

**Comment by li-jia-nan** [comment]
> 还是挂的

- @zombieJ #37864 请求大佬支援 orz

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/37864 这两个应该放在同一个 PR 里吧。

**Comment by li-jia-nan** [comment]
> #37864 这两个应该放在同一个 PR 里吧。

因为不确定这个问题是 #37864 导致的，所以就分开提了，如果是其它原因的话，那么这两个 pr 就是无关的

**Comment by afc163** [comment]
notification 测试用例本身有问题，master 上通过是因为没跑全：https://github.com/ant-design/ant-design/actions/runs/3208787833/jobs/5244981260

**Pull request closed without merging**
