### PR TITLE
fix(#23019): display defaultValue when no matched options

### LINKED ISSUE #23019: 建议Cascader级联选择组件默认值不在选项中时可以显示默认值
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Cascader级联选择组件默认值不在选项中时现在是显示空白，用户体验不是很好，希望可以和Select选择器组件类似处理，可以查看以下链接里的效果

[https://codepen.io/piscdongqq/pen/BaoBRVY](https://codepen.io/piscdongqq/pen/BaoBRVY)

### What does the proposed API look like?
Cascader级联选择组件默认值不在选项中时可以显示默认值

### PR DESCRIPTION
**Pull request by kerm1it**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close [#23019](https://github.com/ant-design/ant-design/issues/23019)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | display defaultValue instead of empty string when no matched options |
| 🇨🇳 Chinese | 当默认值没有匹配任何选项时展示默认值而不是空字符串 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
有些代码被代码格式化自动修改。

**Comment by Kermit-Xuan** [comment]
@afc163 好像modal那失败了，是调整了什么吗？

**Comment by afc163** [comment]
rebase master

**Comment by afc163** [comment]
image

Could you fix coverage?

**Comment by Kermit-Xuan** [comment]
> image
> 
> Could you fix coverage?

之前在这个测试用例其实已经覆盖了，但是就是没有执行，然而在本地就会执行。
``` js
it('should select item immediately when searching and pressing down arrow key', () => {
    const wrapper = mount(<Cascader options={options} showSearch={{ filter }} />);
    wrapper.find('input').simulate('click');
    wrapper.find('input').simulate('change', { target: { value: 'a' } });
    expect(wrapper.find('.ant-cascader-menu-item').length).toBe(2);
    expect(wrapper.find('.ant-cascader-menu-item-active').length).toBe(0);
    wrapper.find('input').simulate('keyDown', {
      keyCode: KeyCode.DOWN,
    });
    expect(wrapper.find('.ant-cascader-menu-item-active').length).toBe(1);
  });
```

这是之前的PR[#22216](https://github.com/ant-design/ant-design/pull/22216)

**Review by afc163 — APPROVED** [review]

**Pull request merged**
