### PR TITLE
Feature card

### PR DESCRIPTION
**Pull request by emersonlaurentino**
solving the issue #6654

### CODE REVIEW

**Comment by afc163** [comment]
This mixed more unrelated commits.

**Comment by emersonlaurentino** [comment]
@afc163 this happened because I switched to branch `feature-3.8.0`, for master, it goes to the correct modifications.

**Comment by afc163** [comment]
You should fork from `feature-3.8.0` and send PR to it.

**Comment by afc163** [comment]
https://anavarre.net/how-to-rebase-a-github-pull-request/
https://stackoverflow.com/questions/17182624/contributing-to-project-on-github-how-to-rebase-my-pull-request-on-top-of-mast
https://help.github.com/articles/about-pull-request-merges/

**Pull request closed without merging**
