### PR TITLE
doc(table): add demo of rowScope

### PR DESCRIPTION
**Pull request by MuxinFeng**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

[](https://github.com/ant-design/ant-design/issues/39688)

### 📝 Changelog

https://github.com/ant-design/ant-design/issues/39688

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
搞一个 codesandbox 链接放在 API 表格里的 rowScope 那里即可

**Comment by MuxinFeng** [comment]
> 搞一个 codesandbox 链接放在 API 表格里的 rowScope 那里即可

done

**Comment by afc163** [comment]
图片

样式感觉有点问题。

**Comment by MuxinFeng** [comment]
> 图片
> 
> 样式感觉有点问题。

边框无了，感觉目前并没有对 rowscope 有很好的支持，感觉可以转个 issue

**Pull request closed without merging**
