### PR TITLE
chore: 🆙 upgrade jest 25

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

https://jestjs.io/blog/2020/01/21/jest-25

Jest 升级了 jsdom，现在 document.activeElement 貌似不准确了，@zombieJ 有空看看。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     none      |
| 🇨🇳 Chinese |    none       |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
感觉像是个 bug：
```jsx
const wrapper = mount(<input autoFocus />);
console.log('=>', document.activeElement); // null
```

**Comment by afc163** [comment]
https://github.com/jsdom/jsdom/issues/2723
https://github.com/jsdom/jsdom/issues/2586

**Comment by zombieJ** [comment]
https://github.com/jsdom/jsdom/issues/2586#issuecomment-561871527

**Comment by afc163** [comment]
1. `document.activeElement` 只有 attach 到 dom 树上的才会生效：https://github.com/jsdom/jsdom/issues/2723#issuecomment-580163361
2. 意外发现了 Rate 一个遗留多年的 bug：https://github.com/react-component/rate/commit/9aeef32e7f389df2df791654c39e4e164ae79c06

**Pull request merged**
