### PR TITLE
refactor: more cache

### LINKED ISSUE #45296: antd5版本的tree组件虚拟列表滚动性能下降了
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/xu-ni-gun-dong-antd-5-10-0-forked-9ssy97?file=/demo.tsx)

### Steps to reproduce

codepen项目内分别用antd4和antd5版本的tree渲染3000个节点的列表，分别查看滚动时页面的帧率

### What is expected?

antd5版本的tree在大数据量的虚拟列表滚动帧率正常

### What is actually happening?

目前antd4版本的tree性能正常帧率稳定在30以上
antd5版本的tree在滚动时帧率只有20左右，最低会掉到15

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.0.0 |
| System | - |
| Browser | - |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #45296

### 💡 Background and solution

在组件渲染时都会经过 CSS-in-JS 的 flatten token 逻辑，原实现为 `useMemo` 缓存，但是对于重新创建的 Node 而言，memo 总是会重新生成。而对于 CSS-in-JS 而言，相同 token 一定出相同的 flatten key，所以在跨组件之间可以复用

#### v4

截屏2023-10-12 17 49 39

#### Before

截屏2023-10-12 17 55 46

#### After

截屏2023-10-12 17 49 34

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Optimize CSS-in-JS Design Token cache matching.     |
| 🇨🇳 Chinese |    优化 CSS-in-JS Design Token 缓存命中性能。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 2142bb3</samp>

The pull request enhances the design token system of the `ConfigProvider` component and its related hooks and types. It introduces a new `override` prop that allows users to specify both alias tokens and component-specific tokens in one object. It also improves the code readability and consistency by refactoring some imports and types.

### <samp>🤖 Generated by Copilot at 2142bb3</samp>

*  Add `override` prop to `DesignTokenProviderProps` and `defaultConfig` to support customizing design tokens and component-specific tokens ([link](https://github.com/ant-design/ant-design/pull/45302/files?diff=unified&w=0#diff-370b4f9c1f0527f049eb25b9235949218c2bb02e7c22c734d6ee7f068a4476d5L14-R28), [link](https://github.com/ant-design/ant-design/pull/45302/files?diff=unified&w=0#diff-c71eb91865998661d8139ee89317ebd253b704a1fae92b80254b164c05c67e8cL60-R61), [link](https://github.com/ant-design/ant-design/pull/45302/files?diff=unified&w=0#diff-c71eb91865998661d8139ee89317ebd253b704a1fae92b80254b164c05c67e8cL76-R72))
*  Simplify `token` prop in `ConfigProvider` by extracting `mergedToken` constant and passing it to `override` prop ([link](https://github.com/ant-design/ant-design/pull/45302/files?diff=unified&w=0#diff-0a9895a32672ec55a084aa7165fc8666008942903b8e51e30b662e9e1ecffb56L550-R564))
*  Reorder imports in `index.tsx` and `useToken.ts` to group related modules and follow alphabetical order ([link](https://github.com/ant-design/ant-design/pull/45302/files?diff=unified&w=0#diff-0a9895a32672ec55a084aa7165fc8666008942903b8e51e30b662e9e1ecffb56L27-R31), [link](https://github.com/ant-design/ant-design/pull/45302/files?diff=unified&w=0#diff-c71eb91865998661d8139ee89317ebd253b704a1fae92b80254b164c05c67e8cL1-R8))

### CODE REVIEW

**Review by kiner-tang — COMMENTED** [review]
没看出是怎么优化缓存命中性能的，@zombieJ ，可以解释一下实现思路吗？

**Comment by afc163** [comment]
有没有可测的 ci 性能数据？

**Comment by zombieJ** [comment]
> 有没有可测的 ci 性能数据？

CPU 时间片是不稳定的，~10ms 的变化机器卡一卡就会超。

**Comment by crazyair** [comment]
> > 有没有可测的 ci 性能数据？
> 
> CPU 时间片是不稳定的，~10ms 的变化机器卡一卡就会超。

如果要加测试，可以加组件加载卸载，token 执行次数

**Comment by zombieJ** [comment]
> 如果要加测试，可以加组件加载卸载，token 执行次数

这样要给 token 对象合成加钩子，打包的时候会留脏的空函数。不太建议为了测试，加这个损耗。

**Review by li-jia-nan — APPROVED** [review]

**Review by kiner-tang — APPROVED** [review]

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
