### PR TITLE
fix: WaterMark blink when scale of window

### LINKED ISSUE #46765: Watermark 组件重复渲染问题
### Reproduction link

[https://ant.design/components/watermark-cn#watermark-demo-custom](https://ant.design/components/watermark-cn#watermark-demo-custom)

### Steps to reproduce

尝试更改 Watermark 组件包裹元素内容

### What is expected?

不应该进行大量的重复渲染 (CPU占用率增大)

https://github.com/ant-design/ant-design/assets/48341368/be2a14e9-9654-4fc6-8968-21c5e349155e

### What is actually happening?

重复渲染(计算)

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Google Chrome Version 120.0.6099.130 (Official Build) (64-bit) |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #46765

### 💡 Background and solution

浏览器特定缩放场景下，会触发 observer，然后导致重绘，重绘再次触发 observer，循环往复。但是重绘内容却是相同的，加一个 update 检测，判断一下内容是否相同，相同就不额外更新了。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |        Fix WaterMark sometime repeat re-render when browser set scale.   |
| 🇨🇳 Chinese |      修复 WaterMark 在特定屏幕缩放下会不断重复渲染的问题。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by crazyair — DISMISSED** [review]

**Review by yoyo837 — DISMISSED** [review]

**Review by afc163 — DISMISSED** [review]

**Comment by li-jia-nan** [comment]
CI 挂了

**Comment by afc163** [comment]
snapshot 挂了

**Comment by zombieJ** [comment]
发现有问题，这个这么一改 mutate 就没效果了。

**Review by afc163 — APPROVED** [review]

**Review by yoyo837 — APPROVED** [review]

**Comment by m430** [comment]
@zombieJ 这个问题在最新版本5.20.0中依然存在，在Modal或者Drawer出现的时候Watermark会重复渲染一次，渲染的区域就是Modal或者Drawer弹出的区域。

**Pull request merged**
