### PR TITLE
fix: Notification hooks

### LINKED ISSUE #24334: Infinite render with useNotification hook and useEffect
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://stackblitz.com/edit/react-qma1ir](http://stackblitz.com/edit/react-qma1ir)

### Steps to reproduce
1. Add the 'api' variable to the dependency array on line 28.
2. You'll see that the code inside the useEffect code infinitely renders because the 'api' variable itself changes on every render.

The reason we need to add 'api' to the useEffect hook is because React complains about exhaustive dependencies.

### What is expected?
'api' should not changes on every render

### What is actually happening?
'api' changes on every render, and because it's listed in the dependency array of the useEffect hook, it runs the useEffect callback every time it changes. Hence infinite loop/render.

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | Latest version |
| System | Windows |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #24334

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Adjust `useNotification` api instance to be same instance for each render.      |
| 🇨🇳 Chinese |    调整 `useNotification` api 实例在每次渲染时都返回相同实例。    |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
image

**Comment by afc163** [comment]
这个 changelog 写的不好，没有从用户角度出发。

**Comment by zombieJ** [comment]
嗯，我写的时候也很纠结。不知道怎么写更好些。

**Comment by afc163** [comment]
试着写了一下：https://github.com/ant-design/ant-design/pull/24410#discussion_r429513845

**Pull request merged**
