### PR TITLE
fix: Menu collapsed jumping

### LINKED ISSUE #21301: Menu导航菜单在切换Item时出现延迟和卡顿以及展开和收缩时出现抖动。
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/menu-cn/#components-menu-demo-inline-collapsed](https://next.ant.design/components/menu-cn/#components-menu-demo-inline-collapsed)

### Steps to reproduce
1，使用 `create umi` 新建包含 antd 4.x.x 版本的 Ant design pro 项目，运行后会发现左侧 Menu 组件 

     * 在切换 Item 时出现点击后 "选中背景颜色" 延迟。

     * "选中背景颜色"在移动时的动画卡顿的情况。

     * 在有二级菜单情况下展开和收缩时会出现抖动。

2，"重现链接" 中也有相同问题。

### What is expected?
期望下次更新时修复此问题。

### What is actually happening?
同上"重现步骤"中的问题。

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | ^16.8.6 |
| System | Windows 10 Pro version 1909 |
| Browser | 【Chrome 80.0.3987.87】 & 【Edge 80.0.361.48】 |

---
左侧 Menu 为经常使用的组件，出现此问题大大降低体验感。

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #21301

### 💡 Background and solution

Revert #21109

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Menu collapsed with jumpy padding. |
| 🇨🇳 Chinese | 修复 Menu 收缩二级菜单时的内边距跳跃问题。  |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
close #21209 too.

**Comment by yoyo837** [comment]
@afc163 请问下，官网渲染 demo 组件用的是右上角版本还是master代码？

**Comment by afc163** [comment]
右上角显示什么就是什么版本。

**Comment by afc163** [comment]
next.ant.design 现在是手动部署，版本不一定。可以找 @zombieJ 触发。

**Comment by yoyo837** [comment]
不干预就是右上角版本？我看现在next里当前修复已经生效了。但是并没有发rc5.

**Comment by afc163** [comment]
那就是 master 的某一个 commit。

**Pull request merged**
