### PR TITLE
Replace momentjs with DayJS (#26759)

### PR DESCRIPTION
**Pull request by Fcmam5**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

I replaced all Moment.js occurrences, and I removed `docs/react/replace-moment.en-US.md` and `docs/react/replace-moment.zh-CN.md` as it might not be needed.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Replaced Moment.js by Day.js |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/calendar/demo/select.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/calendar/demo/select.md)
[View rendered components/calendar/index.en-US.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/calendar/index.en-US.md)
[View rendered components/calendar/index.zh-CN.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/calendar/index.zh-CN.md)
[View rendered components/comment/demo/basic.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/comment/demo/basic.md)
[View rendered components/comment/demo/editor.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/comment/demo/editor.md)
[View rendered components/comment/demo/list.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/comment/demo/list.md)
[View rendered components/config-provider/demo/locale.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/config-provider/demo/locale.md)
[View rendered components/config-provider/index.en-US.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/config-provider/index.en-US.md)
[View rendered components/config-provider/index.zh-CN.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/config-provider/index.zh-CN.md)
[View rendered components/date-picker/demo/disabled-date.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/date-picker/demo/disabled-date.md)
[View rendered components/date-picker/demo/disabled.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/date-picker/demo/disabled.md)
[View rendered components/date-picker/demo/format.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/date-picker/demo/format.md)
[View rendered components/date-picker/demo/presetted-ranges.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/date-picker/demo/presetted-ranges.md)
[View rendered components/date-picker/index.en-US.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/date-picker/index.en-US.md)
[View rendered components/date-picker/index.zh-CN.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/date-picker/index.zh-CN.md)
[View rendered components/form/demo/time-related-controls.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/form/demo/time-related-controls.md)
[View rendered components/modal/demo/dark.md](https://github.com/Fcmam5/ant-design/blob/replace-momentjs-with-dayjs/components/modal/demo/dark.md)

### CODE REVIEW

**Comment by sowka1995** [comment]
Very nice! I am waiting for this to be merged :) Moment.js is now Legacy Code so Dayjs is one of the best option to switch and DayJS is immutable

**Comment by zombieJ** [comment]
Thanks for PR. Since it is a breaking change. We may not apply in v4 currently.

ref https://github.com/ant-design/ant-design/issues/26759#issuecomment-694747449

**Comment by zombieJ** [comment]
@sowka1995,
Pls ref doc to replace MomentJS customize: https://ant.design/docs/react/replace-moment

**Comment by sgb-io** [comment]
Nice work @Fcmam5. I think the only breakage is the dependency change itself? I scanned this changeset and don't see any breaking changes beyond that.

**Pull request closed without merging**
