### PR TITLE
Starting sort order with 'ascend', then 'descend', then undefined.

### PR DESCRIPTION
**Pull request by OvestLabs**
When using a `Table` component, the sort order is always jumping to descending on the first click. This pull request modifies this to ensure the first click is ascending.

Column 1st click: `undefined` => `'ascend'`
Column 2nd click: `'ascend'` => `'descend'`
Column 3rd click: `'descend'` => `undefined`
...

I have never seen table sorting that starts with descending order. So, it's fair to claim this as a standard (none => ascend => descend => none)

**Note:** lint was broken on master. You will find several `let` => `const` changes to appease the hook.

### CODE REVIEW

**Comment by OvestLabs** [comment]
Lint was already broken on files I didn't touch.

**Comment by ztplz** [comment]
@OvestLabs  You should pull the latest code.

**Comment by OvestLabs** [comment]
> @OvestLabs You should pull the latest code.

I already have the latest code... as of this message.

**Comment by OvestLabs** [comment]
@ztplz I rebased onto master.

**Comment by OvestLabs** [comment]
Looks like modifications were made to the lint rules and now the existing `Table.tsx` has dozens of "Missing trailing comma" errors. Wouldn't this mean lint is broken on master?

**Comment by ztplz** [comment]
@afc163

**Pull request merged**
