### PR TITLE
fix(Select): export SelectInterface to avoid ts error

### PR DESCRIPTION
**Pull request by pddpd**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

When we use Select, its related type comes from antd Select, but it does not export SelectInterface. This may lead to [errors](https://github.com/microsoft/TypeScript/issues/9944) such as TS4029.
The solution is very simple, we just need to export the SelectInterface.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Export the SelectInterface of Select |
| 🇨🇳 Chinese | 导出 Select 的 SelectInterface 接口 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
是不是可以用 typeof Select 来获取？

**Comment by pddpd** [comment]
> 是不是可以用 typeof Select 来获取？

试了下，`type SelectInterface = typeof Select;` 可以拿到

**Comment by afc163** [comment]
这样这个 PR 没必要了，加了后面就不好动了。

**Comment by pddpd** [comment]
已经 merge 了，是不是得再来个 PR 去掉这个更改？
（最开始不导出`SelectInterface`是有什么考虑吗

**Comment by afc163** [comment]
回滚吧，能少一个 API 就少一个，SelectInterface 这个命名挺怪的。

**Pull request merged**
