### PR TITLE
feat: Typography.Text Pass event to onCopy.

### PR DESCRIPTION
**Pull request by yzwxk**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | onCopy: function(event) |
| 🇨🇳 Chinese | onCopy: function(event) |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Why do you need this event, what does it for?

**Comment by conviva-zyang** [comment]
> Why do you need this event, what does it for?

Because you guys do `e?.preventDefault() e?.stopPropagation();` by default. We can't catch this click event. Some of our business logic needs to track this `shift + click` from **event.shiftKey**.

**Comment by afc163** [comment]
How about `<Typography copyable onClick={e => { e.stopPropagation(); }} />`?

**Comment by conviva-zyang** [comment]
> How about `<Typography copyable onClick={e => { e.stopPropagation(); }} />`?

@afc163 Sorry  I'm not sure I got your point, my simple code looks like below.  Use `onClick` It does not distinguish whether the click is from text or the copy icon. Although it can be distinguished by the target. But that's so sad.  : (

BTW I think clicking on the icon to make a copy, it is a user action, there should be a way for developers to get to this original event. 

`<Paragraph
        copyable={{
          onCopy: (e) => {
          // Some business logic that needs to distinguish whether the user is clicking directly by clicking, or holding shift
            if (e?.shiftKey) {
              // User use shift + click to copy
              console.log("shift + click");
            } else {
              // just click icon to copy
              console.log("click");
            }
          }
        }}
        onClick={(e) => {
          console.log(e);
          e.stopPropagation();
        }}
      >
        Copy text.
      </Paragraph>
      `

**Comment by yzwxk** [comment]
@afc163  New PR https://github.com/ant-design/ant-design/pull/34522

**Comment by yzwxk** [comment]
> feature branch please~

@afc163 New PR https://github.com/ant-design/ant-design/pull/34522

**Pull request closed without merging**
