### PR TITLE
fix: image prefix

### PR DESCRIPTION
**Pull request by crazyair**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by zombieJ — APPROVED** [review]

**Comment by afc163** [comment]
掉了一行测试覆盖

**Comment by crazyair** [comment]
> 掉了一行测试覆盖

哪里

**Comment by crazyair** [comment]
> 掉了一行测试覆盖

哪里

**Comment by afc163** [comment]
https://codecov.io/gh/ant-design/ant-design/src/d9ec17a1a731475e4b21335268c0b081cd350a37/components/image/PreviewGroup.tsx

**Comment by crazyair** [comment]
> https://codecov.io/gh/ant-design/ant-design/src/d9ec17a1a731475e4b21335268c0b081cd350a37/components/image/PreviewGroup.tsx

`preview === false ` 我加下

**Pull request merged**
