### PR TITLE
chore: make Timeline.Item a bit lighter, drop unneeded omit.js and defaultProps

### PR DESCRIPTION
**Pull request by eugene-matvejev**
…d defaultProps

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Bundle size optimization
- [x] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by eugene-matvejev** [comment]
similar idea as https://github.com/ant-design/ant-design/pull/27807 + omit.js can be replaced with destructoring

**Comment by eugene-matvejev** [comment]
how to see what is wrong in argos build?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/27961/checks?check_run_id=1443140971

image

cc @shaodahong

**Comment by shaodahong** [comment]
> https://github.com/ant-design/ant-design/pull/27961/checks?check_run_id=1443140971
> 

Known issue, waiting fix

**Comment by eugene-matvejev** [comment]
@afc163 as @shaodahong mentioned it is a know issue, can this pull request now be merged or do you have any other concerns?

**Pull request merged**
