### PR TITLE
demo: update demo code

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | type: export Tab type |
| 🇨🇳 Chinese | type: export Tab type |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
ts 报错有重现么？

**Comment by li-jia-nan** [comment]
没有报错，是新增导出了一个类型，这个类型之前只能从 rc 里面拿

**Comment by afc163** [comment]
为啥需要导出这个，用处是啥

**Comment by li-jia-nan** [comment]
> 为啥需要导出这个，用处是啥

在业务场景中使用Tabs组件的时候，可能会遇到 items 数组特别大的情况
```tsx
import React from 'react';
import { Tabs } from 'antd';

const App: React.FC = () => {
  return (
    <Tabs
      items={[
        { key: '1', label: 1 },
        { key: '2', label: 2 },
        { key: '3', label: 3 },
      ]}
    />
  );
};

export default App;
```
这时候我往往习惯把 items 单独拿出去封装起来，这个时候就需要良好的类型提示了：

```ts
import type { Tab } from 'rc-tabs/lib/interface';

const tabTtems: Tab[] = [
  { key: '1', label: 1 },
  { key: '2', label: 2 },
  { key: '3', label: 3 },
];

export default tabTtems;
```

**Comment by afc163** [comment]
我感觉 `TabsProps['items']` 很够了，也足够清晰。

**Comment by li-jia-nan** [comment]
> 我感觉 `TabsProps['items']` 很够了，也足够清晰。

OK，那我 close 了

**Review by afc163 — APPROVED** [review]

**Pull request merged**
