### PR TITLE
Uploadlist custom component

### PR DESCRIPTION
**Pull request by Trufinol**
Adds option for using custom component for displaying a list of uploaded files.

### CODE REVIEW

**Comment by Trufinol** [comment]
Travis error logs are not related to actual pull request. How can we solve this particular build failure?

**Comment by yesmeck** [comment]
I'd prefer to add an `itemRender` prop for using custom item component.

**Comment by Trufinol** [comment]
@yesmeck , would you then pass all of the uploadList props like `listType`,
`onPreview`, `onRemove` etc. in custom render function?

**Comment by yesmeck** [comment]
Yes.

**Comment by menberg** [comment]
What is the proposed solution for this?

**Comment by yesmeck** [comment]
@Trufinol Could you rebase it to `feature-3.8.0`?

**Comment by zomars** [comment]
Thank you! I was going to ask for this specific functionality. Is this PR ready to merge?

**Comment by Trufinol** [comment]
Yep, hopefully =)

**Comment by afc163** [comment]
Travis ci is broken.

**Comment by yesmeck** [comment]
It looks you misunderstand my propose, I say `itemRender`, it means a function for custom file item rendering, not for the file list.

**Comment by afc163** [comment]
Please update code by following comments and send this to branch `feature`.

**Comment by menberg** [comment]
Is there something we can do to help with this feature?

**Comment by afc163** [comment]
Too many conflict, @Trufinol you can send another PR to feature branch.

**Pull request closed without merging**
