### PR TITLE
Add fa_IR locale

### PR DESCRIPTION
**Pull request by mkermani144**

### CODE REVIEW

**Comment by afc163** [comment]
Could you send this to `feature-2.13`?

**Comment by benjycui** [comment]
Oops.... You should remove others' commits from your PR

**Review by afc163 — CHANGES_REQUESTED** [review]
Mix up other commits

**Comment by mkermani144** [comment]
What should I exactly do? I'm a bit confused 😕 
@afc163 @benjycui

**Comment by afc163** [comment]
You should fork and modify from `feature-2.13`. This PR contains commits from `master`.

**Comment by mkermani144** [comment]
What if I merge `feature-2.13` to my fork `master`?

**Comment by benjycui** [comment]
> What if I merge feature-2.13 to my fork master?

Please learn git and GitHub first.

Ref: http://makeapullrequest.com/

**Comment by mkermani144** [comment]
@benjycui Thank you for your advice, but I know enough Git and GitHub :)

I thought @afc163 asked me to change PR __base__ branch from `master` to `feature-2.13`:
> Could you send this to feature-2.13?

This PR should be closed in favor of another one from `feature-2.13` to `master`.

**Comment by afc163** [comment]
Please make sure your PR is clean.

**Comment by afc163** [comment]
#6878

**Pull request closed without merging**
