### PR TITLE
fix:  Invalid regular expression for particular ellipsis content

### PR DESCRIPTION
**Pull request by ttys026**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] Bug fix

### 🔗 Related issue link

#27381 #27382 

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Test case needed.

**Comment by afc163** [comment]
Please rebase master.

**Comment by zombieJ** [comment]
来个测试用例？

**Comment by ttys026** [comment]
ui test failed due to socket hang. Could not upload to argos-ci.
Logs:
https://dev.azure.com/ant-design/ant-design/_build/results?buildId=11613&view=logs&j=0de1d1ec-4277-5734-6195-58a87ebaacee&t=692cebb7-9ccc-59c8-d38e-fc1e7fd97650&l=25

**Comment by zombieJ** [comment]
Restart ci job

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
