### PR TITLE
Rewrite the MenuItem to handle ref for react 16

### PR DESCRIPTION
**Pull request by ghost**
in react 16 ，you can't give ref to a stateless component .so I rewrite the MenuItem code to handle ref

### CODE REVIEW

**Comment by afc163** [comment]
close #8029

**Comment by weishijun14** [comment]
是要等下一个版本才会有修复么

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/releases/tag/2.13.8

**Comment by weishijun14** [comment]
```
Warning: Stateless function components cannot be given refs. 
Attempts to access this ref will fail.
    in modal
    in Unknown (created by Form(WrappedComponent))
    in Form(WrappedComponent) (created by Factory)

```

```
import React from 'react'
import PropTypes from 'prop-types'
import { Form, Input, InputNumber, Radio, Modal, Select } from 'antd'

const FormItem = Form.Item
const Option = Select.Option;
const { TextArea } = Input;

const formItemLayout = {
  labelCol: {
    span: 6,
  },
  wrapperCol: {
    span: 14,
  },
}

//此处没大写 因为antd重名组件
const modal = ({
  item = {},
  onOk,
  modalType,
  form: {
    getFieldDecorator,
    validateFields,
    getFieldsValue,
  },
  ...modalProps
}) => {

  const children = [{
    key: '0',
    name: '设备'
  }, {
    key: '1',
    name: '打印机'
  }, {
    key: '2',
    name: '二维码'
  }, {
    key: '3',
    name: '指示灯'
  }];

  const handleOk = () => {
   ...
  }

  const modalOpts = {
    ...modalProps,
    onOk: handleOk,
  }

  const handleMultiChange = (value) => {

  }

  return (
    <Modal {...modalOpts}>
      {/* <Form> */}
        {/* <FormItem label="厂家名称" hasFeedback {...formItemLayout} style={{display:'none'}}>
          {
            getFieldDecorator('mid', {
              initialValue: item.mid,
            })(
              <Input placeholder="mid"/>
            )
          }
        </FormItem>
        <FormItem label="厂家名称" hasFeedback {...formItemLayout}>
          {
            getFieldDecorator('mname', {
              initialValue: item.mname,
              rules: [{ required: true, message: '此项为必填！'}]
            })(
              <Input placeholder="请填写厂家名称"/>
            )
          }
        </FormItem>
        {
          modalType === 'create' ? (
            <FormItem label="状态" hasFeedback {...formItemLayout}>
              {
                getFieldDecorator('state', {
                  initialValue: item.state ,
                  rules: [{ required: true, message: '此项为必填！' }]
                })(
                  <Select placeholder="请选择状态">
                    <Option value="0">启用</Option>
                    <Option value="1">禁用</Option>
                  </Select>
                )
              }
            </FormItem>
          ) : null
        } */}
        {/* <FormItem label="生产类型" hasFeedback {...formItemLayout}>
          {
            getFieldDecorator('mtype', {
              initialValue: item.mtype ? item.mtype.split(',') : item.mtype,
            })(
              <Select
                mode="multiple"
                size="large"
                placeholder="选择生产类型（多选）"
                onChange={ handleMultiChange }
              >
                {
                  children.map((item) => {
                    return (
                      <Option key={item.key}>{ item.name }</Option>
                    )
                  })
                }
              </Select>
            )
          }
        </FormItem> */}
        {/* <FormItem label="备注" hasFeedback {...formItemLayout}>
          {
            getFieldDecorator('remark', {
              initialValue: item.remark
            })(
              <TextArea rows={4} placeholder="请填写备注信息"/>
            )
          }
        </FormItem> */}
        {/*<FormItem label="新增人" {...formItemLayout}>*/}
          {/*<Input placeholder="请填写新增人"/>*/}
        {/*</FormItem>*/}
      {/* </Form> */}
    </Modal>
  )
}

modal.propTypes = {

}

export default Form.create()(modal)
```

even all Commented， just remain <Modal>,  still Warning created by Form....

**Comment by vgeyi** [comment]
your modal component is stateless component,so when wrap with the form react give you the warning.you can turn it to class component to avoid the ref warning

**Comment by weishijun14** [comment]
ok ，i`ll try ~ thx~

**Pull request merged**
