### PR TITLE
chore: bump rc-util

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

ref https://github.com/ant-design/ant-design/pull/30651#issuecomment-847016368
ref react-component/table@9cbf0db

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
错是从 https://github.com/react-component/table/commit/9cbf0db6a85098e83dc1066612661adcc4e50d8e 里报出来的。

**Comment by zombieJ** [comment]
https://preview-30658-ant-design.surge.sh/components/table-cn/#components-table-demo-virtual-list

**Comment by afc163** [comment]
是 preview 构建的缓存？

**Comment by zombieJ** [comment]
`rc-table` 用了 `rc-util` 的 `getTargetScrollbarSize` 里面用了 `getComputedStyle` 获取 `-webkit` scrollbar style，虚拟滚动里 ref 到的不是真实的 dom 节点导致报错了。

**Pull request merged**
