### PR TITLE
Fix import of tomorrow style for highlightjs.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This fixes an error when running `npm test`:

```
ERROR in ./scripts/demo.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../site/static/tomorrow.less in /Users/bruce/Development/workbench/ant-design/scripts
 @ ./scripts/demo.js 51:0-39
```

Just needed to use the correct path.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
@benjycui This is what I mentioned on Gitter.

**Comment by benjycui** [comment]
`demo.js` is deprecated, just ignore it.

**Comment by benjycui** [comment]
Removed, see: https://github.com/ant-design/ant-design/commit/35ad4017dd2f23db1f2775644feb7bc90670a44e

**Comment by benjycui** [comment]
Actually, there are still lots of files should be removed for the old website is deprecated. But I am busy for other tasks now, so.. later.

**Pull request closed without merging**
