### PR TITLE
Upload add props openFileDialogOnClick docs

### PR DESCRIPTION
**Pull request by hengkx**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for branch `feature`.
* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by hengkx** [comment]
#12174

**Comment by afc163** [comment]
https://github.com/react-component/upload/pull/125

**Comment by afc163** [comment]
1. feature branch
2. could you add TypeScript definition?

**Comment by hengkx** [comment]
done.
Operation error. There are many other files modified by other people. 
@afc163 Do you have any good suggestions?

**Comment by afc163** [comment]
You shoud checkout from feature branch and add your commits.

**Comment by hengkx** [comment]
@afc163 Thanks.new pr #12347

**Pull request closed without merging**
