### PR TITLE
docs: correct maxTagTextLength description in Select.

### PR DESCRIPTION
**Pull request by cwj0417**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     correct maxTagTextLength description in Select.      |
| 🇨🇳 Chinese |     修复select组件中`maxTagTextLength `的描述     |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/select/index.en-US.md](https://github.com/cwj0417/ant-design/blob/patch-1/components/select/index.en-US.md)

### CODE REVIEW

**Comment by 97Yates05** [comment]
虽然我英语不咋地，，不过确定这解决我的问题了吗。。

**Comment by yoyo837** [comment]
https://codesandbox.io/s/restless-surf-jj4f6?file=/index.js 正常工作哦，你的啥问题

**Comment by 97Yates05** [comment]
maxTagTextLength={2}为啥是2呢，最大显示的 tag 文本长度，2px?

**Comment by yoyo837** [comment]
两个字符，maxTagTextLength的意思时tag上的文字超出多少溢出

**Comment by 97Yates05** [comment]
...明白了，感谢

**Comment by promotion-xu** [comment]
有没有超出5字符就不允许输入的方法，就像Input 的 maxLength一样

**Pull request merged**
