### PR TITLE
chore: unified import method

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: unified import method |
| 🇨🇳 Chinese | 统一导入方式 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at a59d641</samp>

This pull request refactors and improves the code style of several TypeScript components in the `.dumi` folder of the ant-design repository. It mainly changes the import of React from `import * as React from 'react'` to `import React from 'react'` and reorders and groups the imports according to a convention. It also uses function expressions and default exports for consistency and readability.

### <samp>🤖 Generated by Copilot at a59d641</samp>

*  Simplify React imports to follow recommended syntax and avoid potential issues ([link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-95b57e790d12ddcb423ec654dc087aded0dbaeed1a650497e6e5e9ff54dcd8caL2-R2), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-8224af725d22f9ec09fdfbfddab99d82b2438b8fb9c4897afb52fba55d43a29fL4-R4), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-6a484b82d5234dc2b8c7c367190b951e79e2d45ebe10433597c11365aee1c877L1-R7), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-935d4f3f1f1185da224c9f1168ce1e28a667f4374033983d472a1b1923a14a7eL1-R2), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-844617f9965e63398da7daa55eb25905d69615fd3e95c4953b8f486661b93d0aL1-R5), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-4c11221c660085e5da367fdd831869ee2e881df16898d0b44439d647b134eea6L1-R1), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-a0e54c8709f9bb05620ed26294aecfdbd07627aa7abb084e87ccc5a580530c71L1-R5), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dL3-R3), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-5137c94c78aea4423103cc7e7309ec68b1d233d0dae3b03750694ea29c3206cfL1-R1), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-51d36d0662438e162135ad6713e967a78491b32e953192265b2ecc71c9800e26L1-R1), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-a8655a9d98be8464dc030b48766ada804b1a4542cf5e50fcd8c1e3f9c8ffc7acL1-R1), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-cfd6f597c784ca5d28af27e596e853bda8ed1e3101281f58583dc7d352035a15L1-R1), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-1373441d0f65c4cb1581b1495c0a8b1aa8e28184a5cff63c9fafb33173099187L1-R1), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-fa3c6ee46e636904af27493b0063d0972a6701406710d1fb076425e904184d19L2-R2), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-16fa19cd7384aaec1f2aa2733ad3a35affb9541febf0bd5aaa779eb0c7d9890aL2-R2), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-03bd0125ab5555283674cdd82fa23e9bf7636f8059e6a57e5e62cf532f7d1c21L1-R2), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-a1a8af1a50735a6e8772319517303fa26cee992b515a53fa605c4196de05fe55L4-R4), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-cbdf3f0fb3c19022e80fcb7b1dc7f77f8170966bd90db7efc1edb005b193bbe7L2-R2), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-53bd73168010c1286c5c8d20c1103fca6b29a22492f6b670daca190169fc4776L3-R3))
* Reorder and group imports alphabetically by module name and type in several files ([link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-6a484b82d5234dc2b8c7c367190b951e79e2d45ebe10433597c11365aee1c877L1-R7), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-844617f9965e63398da7daa55eb25905d69615fd3e95c4953b8f486661b93d0aL1-R5), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL21-R35), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-a0e54c8709f9bb05620ed26294aecfdbd07627aa7abb084e87ccc5a580530c71L1-R5))
* Remove unused imports of React and TinyColor from `.dumi/pages/index/components/Theme/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL1-L3))
* Add missing imports of TinyColor, css, and React to `.dumi/pages/index/components/Theme/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedR7-R8), [link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedL21-R35))
* Convert `Recommends` component from a function declaration to a function expression in `.dumi/pages/index/components/RecommendsOld.tsx` ([link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-844617f9965e63398da7daa55eb25905d69615fd3e95c4953b8f486661b93d0aL80-R80))
* Export `Recommends` component as a default export at the end of `.dumi/pages/index/components/RecommendsOld.tsx` instead of using a named export at the beginning ([link](https://github.com/ant-design/ant-design/pull/42149/files?diff=unified&w=0#diff-844617f9965e63398da7daa55eb25905d69615fd3e95c4953b8f486661b93d0aL104-R106))

### CODE REVIEW

**Comment by yoyo837** [comment]
image

还有

**Comment by li-jia-nan** [comment]
> 还有

https://github.com/ant-design/ant-design/pull/42149/commits/b52c04bc368b0533e7c6bb8e5bdaa0b77b125a3e

**Comment by li-jia-nan** [comment]
求+1

**Review by MadCcc — APPROVED** [review]

**Comment by afc163** [comment]
体积为啥上升了？

**Comment by yoyo837** [comment]
import 那里字符变长了

**Pull request merged**
