### PR TITLE
perf(progress): reduce cpu usage

### LINKED ISSUE #31124: [Progress] high CPU usage
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/progress-cn/](https://ant.design/components/progress-cn/)

### Steps to reproduce
1. open the performance monitor
2. check CPU usage

### What is expected?
low CPU usage

### What is actually happening?
high CPU usage

image

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | ^16.9.44 |
| System | Mac OS |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by stygian-desolator**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [x] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #31124

### 💡 Background and solution

pls check this demo, the animation of progress has been replaced and you will see that the CPU usage has dropped to 0.1%.

https://stackblitz.com/edit/react-h7yrh3?file=index.css

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Optimize Progress  animation CPU usage.      |
| 🇨🇳 Chinese |     优化 Progress 动画性能，显著降低 CPU 使用率。     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by vthinkxie — APPROVED** [review]
lgtm

**Comment by afc163** [comment]
```diff
- pref
+ perf
```

**Comment by stygian-desolator** [comment]
It looks like some test cases are failing, I'll check them later.

**Pull request merged**
