### PR TITLE
chore: update table drag demo

### LINKED ISSUE #39905: v5.1.1 Table Drag sorting 提示线又出问题了
### Reproduction link

[https://ant.design/components/table#components-table-demo-drag-sorting](https://ant.design/components/table#components-table-demo-drag-sorting)

### Steps to reproduce

官网的demo是正常的，点击codesandbox生成出来的demo提示线有问题

### What is expected?

正常

### What is actually happening?

不正常

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.0.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/39905

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  --         |
| 🇨🇳 Chinese |  --         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
@ant-design/ant-design-collaborators

**Comment by crazyair** [comment]
为什么要加 important

**Comment by afc163** [comment]
优先级始终不够，如果不加 !important 这里就要写很长的很复杂 selector，不如简单点用 !important，也不会有啥副作用。

**Comment by crazyair** [comment]
demo 不是 shadow 的吗

**Comment by afc163** [comment]
shadow ？

**Comment by crazyair** [comment]
现在线上没问题啊
image

**Comment by afc163** [comment]
codesandbox 里优先级不够

**Comment by crazyair** [comment]
image
文档站的 #components-table-demo-drag-sorting 到 demo 里就没了，干脆 Table 加个 className ，然后加在 tr.drop-over-xx 前面

**Comment by afc163** [comment]
加 className 也是一样的，优先级不够，除非去还原完整的 selector 链条。

**Comment by crazyair** [comment]
https://codesandbox.io/s/tuo-zhuai-pai-xu-antd-5-1-2-forked-w4j53q?file=/demo.tsx

**Comment by afc163** [comment]
这样反而搞复杂了，而且以后 table 样式结构如果变了，或者有 fixed header 或 columns，又会有问题。

**Review by crazyair — APPROVED** [review]
LGTM

**Comment by afc163** [comment]
其实最好是用 style 属性内联进去。

**Comment by crazyair** [comment]
row 里添加 context，再在 cell 获取是否 drag，然后给 td 加 style

**Pull request merged**
