### PR TITLE
fix: adjust Upload isImageUrl logic

### PR DESCRIPTION
**Pull request by linxianxi**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [] Other (about what?)

### 💡 Background and solution

小程序上传得到的图片类型为 "image"，没有斜杆，导致在 pc 端的 antd 缩略图不能预览

### 📝 Changelog

- Use a developer-oriented tone and narrative style.
- Describe the user's first-hand experience of the issue and its impact on developers, rather than your solution approach.
- Refer to: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     adjust Upload isImage logic      |
| 🇨🇳 Chinese |    修改 Upload isImageUrl 逻辑       |

### CODE REVIEW

**Comment by afc163** [comment]
小程序用 antd？

**Comment by linxianxi** [comment]
> 小程序用 antd？

小程序上传 fileType 到数据库，pc 端用 antd 展示。

**Comment by li-jia-nan** [comment]
用 includes 可以吗？

**Review by li-jia-nan — APPROVED** [review]

**Comment by afc163** [comment]
> 小程序上传 fileType 到数据库，pc 端用 antd 展示。

这是不规范的，不应该因为其他环境对 fileType 的识别不准确改变渲染逻辑。

而且 PC 浏览器对 fileType 的识别也不是 100% 准确的，因此我建议还是按 minetypes 的规则来。

**Pull request closed without merging**
