### PR TITLE
fix: 较小的@form-item-margin-bottom时表单验证信息切换时表单项抖动

### PR DESCRIPTION
**Pull request by yoyo837**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
`@form-item-margin-bottom = 20px` 会造成 `padding-top = -2px`, 无效，此时应该改用`margin-top`

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |       |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
image

image

**Comment by zombieJ** [comment]
能给个 codesandbox 不？

**Comment by yoyo837** [comment]
https://codesandbox.io/s/wk04r016q8 模版能修改变量吗？

**Comment by zombieJ** [comment]
import less 文件试试

**Comment by yoyo837** [comment]
不能import less

**Comment by zombieJ** [comment]
那截个 gif 吧，我好理解一下

**Comment by yoyo837** [comment]
Feb-11-2020 18-01-45

**Comment by yoyo837** [comment]
[Feb-11-2020 18-06-08.mp4.zip](https://github.com/ant-design/ant-design/files/4185050/Feb-11-2020.18-06-08.mp4.zip)

**Comment by zombieJ** [comment]
CI 挂了，rebase 一下

**Comment by yoyo837** [comment]
还是 这个鬼。
image

**Comment by yoyo837** [comment]
是我语法有问题么 🤔

**Comment by afc163** [comment]
image

**Comment by x1mrdonut1x** [comment]
@yoyo837 @zombieJ I found this issue while trying to solve a problem when setting 
`@form-item-margin-bottom: 0px`

image
image

I feel like `margin-top` shouldn't be updated when the value is < 0?

**Comment by yoyo837** [comment]
I will check it again later.

**Comment by yoyo837** [comment]
@zombieJ 暂时没想到什么比较完美防止抖动的方法，因为`@form-item-margin-bottom` 按理说他可以修改为任何可大可小的值。先改为如果`@form-item-margin-bottom=0`则直接隐藏如何？

**Pull request merged**
