### PR TITLE
style: adjust mentions readonly cursor

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Adjusts Mentions `readOnly` mouse style to native style.  |
| 🇨🇳 Chinese | 调整 Mentions `readOnly` 鼠标样式为原生样式。|
### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
这个和原生 input 样式走就行，没必要改。

**Comment by xrkffgg** [comment]
http://localhost:8001/components/mentions-cn/#components-mentions-demo-readonly  Mentions 的 readOnly 样式改了

**Comment by xrkffgg** [comment]
@afc163  Mentions 的 readOnly 要动吗？现在是用的 default

**Comment by afc163** [comment]
可以改回来，readOnly 也可以复制文本的，应该用 text。

**Pull request merged**
