### PR TITLE
fix: RangerPicker style

### LINKED ISSUE #17123: RangePicker 中 input 的 line-height 不正确
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/input/style/mixin.less#L54](https://github.com/ant-design/ant-design/blob/master/components/input/style/mixin.less#L54)
https://ant.design/components/date-picker-cn/

### Steps to reproduce
最新版中 .ant-input 的 [line-height 默认值为 32px](https://github.com/ant-design/ant-design/blob/master/components/input/style/mixin.less#L54)，在 RangePicker 中该 line-height 会导致 span.ant-calendar-picker-input.ant-input 元素垂直方向未对齐。

### What is expected?
span.ant-calendar-picker-input.ant-input  的 line-height 为 1.5

### What is actually happening?
span.ant-calendar-picker-input.ant-input  的 line-height 为  32px

| Environment | Info |
|---|---|
| antd | 3.19.4 |
| React | 16.8.4 |
| System | OSX 10.14.3 |
| Browser | Chrome 74.0.3729.169 |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

屏幕快照 2019-06-17 上午9 45 04

close #17124
close #17123

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix RangerPicker input style not align     |
| 🇨🇳 Chinese |     修复 RangerPicker 输入框内容没有对齐的问题     |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
rebase after https://github.com/ant-design/ant-design/pull/17128 merged

**Comment by lcx-seima** [comment]
我看 commit 只改了 `ant-calendar-range-picker-input`，`ant-calendar-range-picker-separator` 也改了吧？

**Comment by beMySun** [comment]
Still not working in 3.19.5.

image

`3.18.1` is Good.


image

**Comment by afc163** [comment]
确实，separator 还在下面。

**Comment by wangjianio** [comment]
修复之前先用 3.19.3 吧，最近发版有点频繁啊

**Comment by ZhiGang-Fang** [comment]
www

赶脚还是寻在问题

**Comment by jackple** [comment]
@afc163 
重要的是跟其他form组件不对齐了, 这个影响比3.19.5的修复的内容更大
image

**Comment by billwing** [comment]
@jackple 我也在看这个问题，刚还原到1.19.3了😂

**Comment by zombieJ** [comment]
@jackple @billwing 这个 fix 已经 revert 了。`3.19.6` 还有这个问题吗？

**Comment by billwing** [comment]
@zombieJ 刚更新到3.19.6，没有发现这个问题🤝

**Comment by jackple** [comment]
@zombieJ 我尝试升级后看到这样就回滚了, 稍候我再看看

**Pull request merged**
