### PR TITLE
fix: 类型“FormListFieldData”上不存在属性“fieldKey”。(#35883)

### LINKED ISSUE #35883: 类型“FormListFieldData”上不存在属性“fieldKey”。
### Reproduction link

[https://www.baidu.com/](https://www.baidu.com/)

### Steps to reproduce

类型“FormListFieldData”上不存在属性“fieldKey”。

### What is expected?

类型 FormListFieldData 包含 fieldKey

### What is actually happening?

类型“FormListFieldData”上不存在属性“fieldKey”。

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 17.0.2 |
| System | mac 12.1 |
| Browser | chrome |

---
antd@4.17.0 移除了FormListFieldData中的fieldKey 老项目未锁定antd版本  重新install后报错

### PR DESCRIPTION
**Pull request by nanianlisao**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/35883

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix that property 'fieldKey' does not exist on type 'FormListFieldData' in FormList。      |
| 🇨🇳 Chinese |    修复FormList中类型“FormListFieldData”上不存在属性“fieldKey”。       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
有上下文吗

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/32689 目的就是去掉 `fieldKey`，自动加上的

**Comment by nanianlisao** [comment]
> #32689 目的就是去掉 `fieldKey`，自动加上的
image
对于业务使用来说，fields中是含有fieldKey的
image

**Comment by MadCcc** [comment]
changelog 填一下

**Comment by xrkffgg** [comment]
@nanianlisao PR 里的 changelog，填一下

**Comment by pfdgithub** [comment]
`antd@>=4.18.0 <4.21.0` 全部受到影响

**Pull request merged**
