### PR TITLE
fix(Table): fix sticky table header shadow style error

### LINKED ISSUE #40132: Table: Sticky table header overlapped shadow at right hand side
### Reproduction link

[https://codepen.io/edc-pl/pen/qByrmEX](https://codepen.io/edc-pl/pen/qByrmEX)

### Steps to reproduce

1. Make sure no `fixed: 'right',` at last columns, and have `fixed: 'left',` at first column only
2. Set `sticky={true}` at Table
3. You will see shadow do not overlap the table header at right hand side

### What is expected?

The table header should be overlapped by the right shadow

### What is actually happening?

The right shadow is overlapped by table header

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 16.13.1 |
| System | Windows 10 22H2 19045.2364 |
| Browser | Chrome 109.0.5414.74 |

---
In antd4, the table header is overlapped by the right shadow. But in antd5, it didn't. Please see this codepen link (https://codepen.io/edc-pl/pen/wvxJdvN) with antd4 to compare the shadow appearance at right hand side of the table.

The shadow style affected by these css style

- antd4:
```
.ant-table .ant-table-container::after {
  z-index: calc(calc(2 + 1) + 1);
}
```
- antd5:
```
.ant-table-wrapper .ant-table-container::after {
  z-index: 2;
}
```

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #40132 

**Beforer**
image

**After**
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix sticky table header shadow style error     |
| 🇨🇳 Chinese |      修复粘性表头阴影样式错误     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
看看效果？

**Comment by Wxh16144** [comment]
> 看看效果？

PR 描述已更新

**Comment by kiner-tang** [comment]
没太看出前后的差异

**Comment by Wxh16144** [comment]
> 没太看出前后的差异

注意右上角表头阴影，修复的是这个问题

**Comment by kiner-tang** [comment]
> > 没太看出前后的差异
> 
> 注意右上角表头阴影，修复的是这个问题

哦，修复后是多出这一节阴影是么
image

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
