### PR TITLE
fix: notification style width

### LINKED ISSUE #45678: Notification API style not respected since version 5.10.3 (5.10.2 is still working correctly)
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/ant-design-notification-css-issue-96ky5l?file=/src/index.js)

### Steps to reproduce

import { useEffect } from "react";
import "./styles.css";
import { notification } from "antd";

export default App = () => {
  const [api, contextHolder] = notification.useNotification();

  useEffect(() => {
    const openNotification = () => {
      api.open({
        message: "Test messsage",
        type: "info",
        description:
          "This is a long description witch not respect the style 800px description.",
        className: "custom-class",
        style: { width: "600px" },
        placement: "bottomLeft",
        duration: 0,
        key: 1
      });
    };
    openNotification();
  }, []);

  return <span>{contextHolder}</span>;
};

### What is expected?

The style is not using the 600px, but it keeps the 384px

### What is actually happening?

The style is not using the 600px, but it keeps the 384px

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.2.0 |
| System | ReactJS |
| Browser | Chromium |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/45678

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Notification that `style.width` not work.        |
| 🇨🇳 Chinese |     修复 Notification 组件设置 `style.width` 无效的问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at d6914e4</samp>

This pull request adds a new feature to the notification component, allowing it to use a pure panel style. It also introduces a theme system using alias tokens and refactors the style generation functions. It updates the test and demo files accordingly.

### <samp>🤖 Generated by Copilot at d6914e4</samp>

*  Add a new feature of pure panel style for the notification component ([link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-8b66e26e1dc3ab97c7faf1e4f2d015c5b42d580fce0dd4c3043b7253bcdb83ccR14), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-8b66e26e1dc3ab97c7faf1e4f2d015c5b42d580fce0dd4c3043b7253bcdb83ccR103), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-cda3e92a534cf8b3f7539418f8e3d0e1ea4eeb84b1fbd303c43af9084685909dR1-R20))
*  Refactor the style generation functions to use the theme system and extract the common style for the notice element ([link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-1b72cd8f976d21d83517b2c963a0b9a9bb6670e5d004ed4a7b0dd2edad3fc965L4-R4), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-1b72cd8f976d21d83517b2c963a0b9a9bb6670e5d004ed4a7b0dd2edad3fc965L36-R36), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-1b72cd8f976d21d83517b2c963a0b9a9bb6670e5d004ed4a7b0dd2edad3fc965L52-L53), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-1b72cd8f976d21d83517b2c963a0b9a9bb6670e5d004ed4a7b0dd2edad3fc965L63-R62), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-1b72cd8f976d21d83517b2c963a0b9a9bb6670e5d004ed4a7b0dd2edad3fc965R71-R72), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-1b72cd8f976d21d83517b2c963a0b9a9bb6670e5d004ed4a7b0dd2edad3fc965L175-R185), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-1b72cd8f976d21d83517b2c963a0b9a9bb6670e5d004ed4a7b0dd2edad3fc965L239-R284), [link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-1b72cd8f976d21d83517b2c963a0b9a9bb6670e5d004ed4a7b0dd2edad3fc965L279-R292))
*  Remove the redundant width property from the stack style function in `components/notification/style/stack.ts` ([link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-afcb3078a4ca46e4c23d5a6292b9d6bddc597e289711b77fc319bad238d5b85fL91))
*  Add a test case to check the style.width prop can override the default width of the notification component in `components/notification/__tests__/index.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-ed8976c7e832d9befa4199cc192b025c91cb3ff525a3649834d7545fdd89f690R352-R369))
*  Add the style prop to the demo code in `components/notification/demo/basic.tsx` to show how to customize the notification component ([link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-d59d1752076873d64b9180b5fa4b4f1d317a292dc58d85b0052e0385c32e89cfR12))
*  Add an empty line to separate the test cases in `components/notification/__tests__/index.test.tsx` for readability ([link](https://github.com/ant-design/ant-design/pull/45681/files?diff=unified&w=0#diff-ed8976c7e832d9befa4199cc192b025c91cb3ff525a3649834d7545fdd89f690R316))

### CODE REVIEW

**Review by kiner-tang — APPROVED** [review]

**Comment by li-jia-nan** [comment]
size-limit 又挂了，上周刚加了1kb

**Comment by kiner-tang** [comment]
> size-limit 又挂了，上周刚加了1kb

一直增加体重，是时候瘦一下身了

**Comment by MadCcc** [comment]
多加个文件就大 200b

**Comment by jovana** [comment]
Thanks for fixing this!

**Pull request merged**
