### PR TITLE
fix: remove strokeWidth limit

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix: remove strokeWidth limit |
| 🇨🇳 Chinese | fix: 移除 strokeWidth 限制，修复了 progress 的改动影响到了其它组件的问题 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
changelog 会不会太抽象了点? 为啥remove写一下?

**Comment by li-jia-nan** [comment]
我补充一下

**Comment by afc163** [comment]
啥问题？

**Comment by MadCcc** [comment]
demo 要不要改？这个 snapshot 变了吧

**Comment by MadCcc** [comment]
> 啥问题？

Steps 用了 Progress，最小宽度限制让 Steps 样式不对了

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
