### PR TITLE
Add locale ca_ES (Catalan)

### PR DESCRIPTION
**Pull request by aaronplanell**
Hello,

I added the local for ca_ES (Catalan). Therefore, this fork only have four new files:
```
components/calendar/locale/ca_ES.tsx
components/date-picker/locale/ca_ES.tsx
components/locale-provider/ca_ES.tsx
components/time-picker/locale/ca_ES.tsx
```

Previously to this fork, I updated to other projects:
- rc-calendar: https://github.com/react-component/calendar/pull/213
- rc-pagination: https://github.com/react-component/pagination/pull/59

Finally, I run:
```
antd-tools run ts-lint
antd-tools run compile
```

Everything it's OK. Waiting for your fork :smile:

### CODE REVIEW

**Comment by benjycui** [comment]
........oops

**Comment by aaronplanell** [comment]
I had two conflicts:
a) The `./components/locale-provider/__tests__/index.test.js`. It has another new language (nl_NL). I merged it.
b) The `./components/table/Table.tsx`. I keep the [original one](https://github.com/ant-design/ant-design/blob/feature-2.8/components/table/Table.tsx) of the branch `feature-2.8`.

**Comment by afc163** [comment]
image

**Comment by afc163** [comment]
And you should checkout `feature-2.8` and modify code in it.

**Comment by aaronplanell** [comment]
OK @afc163 & @yesmeck . I think that the best solution is: 
1) Close and discard this pull to feature-2.8.
2) Close and discard the pull 4927 to master.
3) Checkout the branch feature-2.8.
4) Add the ca_ES files to locale.
5) Modify the test file for locale.
6) Push and fork.

What do you think about it?

**Comment by afc163** [comment]
Yep, that will work.

**Comment by afc163** [comment]
BTW, I am big fan of FC Barcelona. :soccer:

**Comment by aaronplanell** [comment]
Hehehe. Me too!!! These days are sad for all the fans of the FCB. Three days ago we lost 4-0 in Paris vs. PSG. It's very very complicated continue playing the Champions :cry:

**Pull request closed without merging**
