### PR TITLE
docs: update Modal.method docs

### PR DESCRIPTION
**Pull request by nanwy**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/45930

### 💡 Background and solution
image
接上一个PR，https://github.com/ant-design/ant-design/pull/45932 ，在上个PR中说道，在使用Ant Design的Modal组件时，我遇到了一些奇怪的问题。我希望在使用Modal的静态方法时能够渲染关闭图标，因为文档只提到了closeIcon属性，没有提到closable属性，以致于我只知道传递closeIcon，但无论如何传递都无法渲染关闭图标。我查看了源码后发现，closable默认false，也就是静态方法默认不展示关闭图标。在5.7.0版本的文档中，移除了closable属性的描述，且closeIcon的默认值是CloseOutlined，按文档描述来说应该是会默认渲染关闭图标的。因此，我认为这可能是一个逻辑上的遗漏实现，并提了一个PR，https://github.com/ant-design/ant-design/pull/45932 来修复，但是成员告诉我，静态方法提供的信息是经过设计的，用户需要自行确认是否启用右上角的关闭图标和点击背景关闭功能。所以提了本PR来修正Modal.method的描述，来确保描述和方法实际的表现一致。
image
### 📝 Changelog
更新了Modal静态方法属性的描述

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      updated the docs of the attributes for the Modal method.     |
| 🇨🇳 Chinese |    更新了Modal静态方法属性的描述     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at db04b4c</samp>

Update the Chinese documentation of `Modal.method()` to include the new `closeIcon` and `closable` props. These props allow users to customize the appearance and behavior of the modal close button.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at db04b4c</samp>

* Add `closeIcon` and `closable` props to `Modal.method()` to customize and control the close button of the modal ([link](https://github.com/ant-design/ant-design/pull/45948/files?diff=unified&w=0#diff-7a204621cc9425007680c097ad01151df377979692bbc09eb2796025b85043f3L107-R108),                           F27L

### CODE REVIEW

**Comment by afc163** [comment]
@kianfang 这个之前是不是统一过？

**Review by afc163 — APPROVED** [review]

**Comment by kianfang** [comment]
> @kianfang 这个之前是不是统一过？

@afc163 多久前，我貌似都没印象了

**Comment by afc163** [comment]
@kiner-tang @ 错人了。。

**Comment by crazyair** [comment]
https://github.com/ant-design/ant-design/pull/47730/files 默认值要改成 true？

**Comment by nanwy** [comment]
> https://github.com/ant-design/ant-design/pull/47730/files 默认值要改成 true？

看源码 closable = false，closable配置的仍然是false，而且修改文档为什么只改中文文档。

**Pull request merged**
