### PR TITLE
downgrade warning to 3.0.0

### LINKED ISSUE #10667: Can't build Ant Design 3.5.4 with uglify-js
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
N/A

### Reproduction link
[https://github.com/whtsky/antd-build-error](https://github.com/whtsky/antd-build-error)

### Steps to reproduce
yarn build

### What is expected?
build success

### What is actually happening?

```
ERROR in Encountered an error while minifying bundle.js:
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
  40098 |
  40099 | if (__DEV__) {
> 40100 |   function printWarning(format, args) {
        |  ^
  40101 |     var len = arguments.length;
  40102 |     args = new Array(len > 2 ? len - 2 : 0);
  40103 |     for (var key = 2; key < len; key  ) {
```

---
Related: https://github.com/BerkeleyTrue/warning/issues/25

downgrade `warning` to 3.x should solve this

### PR DESCRIPTION
**Pull request by whtsky**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

close #10667 

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by afc163** [comment]
@zombieJ Maybe we need to release a hot-fix version.

**Comment by yoyo837** [comment]
No release to v3.5.5 to NPM yet

**Comment by yoyo837** [comment]
`warning` released V4.0.1 now.

**Comment by afc163** [comment]
We can reverse it now.

**Pull request merged**
