### PR TITLE
fix: select ref typescript typo

### LINKED ISSUE #27474: How to type SelectRef after upgrading to 4.7
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/determined-heisenberg-gfr3x?file=/src/App.tsx)

### Steps to reproduce
Running the code (as in the sandbox) with version 4.6.6 worked just fine. After upgrading to v4.7.3 I can't properly type a ref for the Select component.
TS complains: `2749: 'Select' refers to a value, but is being used as a type here. Did you mean 'typeof Select'? `

### What is expected?
A way to type a ref to Select

### What is actually happening?
With the actual exported interfaces couldn't properly type a ref to a Select component. The way used in the sandbox code example worked just fine in versions 4.6*

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13 |
| System | Archlinux 5.5.13-arch1-1 |
| Browser | Chromium Version 80.0.3987.149 |

### PR DESCRIPTION
**Pull request by hengkx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close #27474

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix Select ref props typescript typo.        |
| 🇨🇳 Chinese |  修复Select ref  属性 typescript 错误。        |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by ycjcl868 — APPROVED** [review]

**Comment by zombieJ** [comment]
为啥是 HTMLInputElement，它 Ref 的就是 Select 呀。 。 。

**Comment by zombieJ** [comment]
看起来直接定义一个 focus 和 blur 应该就可以了：https://github.com/react-component/select/blob/7ca11a86d61b6b3db493a82bb08cd53ed138dd4d/src/Select.tsx#L73

**Comment by hengkx** [comment]
写 这个吗 https://github.com/react-component/select/blob/7ca11a86d6/src/Selector/index.tsx#L45 看着 也麻烦的

**Comment by zombieJ** [comment]
对，只要这两个。之前是 class，现在不需要了。

**Pull request merged**
