### PR TITLE
修复了下拉菜单placeholder溢出的问题

### PR DESCRIPTION
**Pull request by yeliex**
修复了下拉菜单placeholder溢出的问题
- [x] Make sure you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
- [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
- [x] Rebase before creating a PR to keep commit history clear.
- [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by afc163** [comment]
Need demo for this problem

**Comment by yeliex** [comment]
@afc163 只需要修改官网中的示例就可以 将placeholder 的内容增加

**Comment by afc163** [comment]
你最好非常具体的描述下问题，这样说我是看不懂的。https://github.com/ant-design/ant-design/blob/master/.github/ISSUE_TEMPLATE.md 有重现的演示就更好了。

**Comment by yeliex** [comment]
@afc163 [http://codepen.io/yeliex/pen/JKvWNJ](http://codepen.io/yeliex/pen/JKvWNJ)

**Comment by afc163** [comment]
:+1:

发到 1.x-stable 分支上吧。

**Comment by yeliex** [comment]
@afc163 #2480

**Pull request closed without merging**
