### PR TITLE
chore: merge master into feature

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [x] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | master merge into feature |
| 🇨🇳 Chinese | master merge into feature |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
5.2.0 发完再合

**Comment by yoyo837** [comment]
@SocketSecurity ignore @swc/core@1.3.34
@SocketSecurity ignore core-js-pure@3.27.2
@SocketSecurity ignore jest@29.4.2
@SocketSecurity ignore jest-cli@29.4.2

**Comment by yoyo837** [comment]
这个还有要等的吗? 搞过去吧

**Comment by li-jia-nan** [comment]
怎么搞？手动merge吗？

**Comment by li-jia-nan** [comment]
CI 好像挂了

**Comment by yoyo837** [comment]
咋没看见红色的是哪个呢

**Comment by li-jia-nan** [comment]
我也没看见，我只看到 CodeQL 跑了一天一夜了

**Pull request closed without merging**
