### PR TITLE
fix: Table customize filterDropdown with Menu should not block default selectable

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Table customize `filterDropdown` with Menu should not block default `selectable`.      |
| 🇨🇳 Chinese |     修复 Table 自定义 `filterDropdown` 中使用 Menu 会被修改默认 `selectable` 的问题。     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
不应该是默认 selectable 么？

**Comment by zombieJ** [comment]
> 不应该是默认 selectable 么？

对，但是现在改造成 context 后会因为 dropdown 变成默认不 `selectable` 的。所以 Table 里再返回去。

**Review by afc163 — APPROVED** [review]

**Comment by zombieJ** [comment]
Typography 的问题开新的 PR 修一下，这个先合了~

**Comment by afc163** [comment]
覆盖率是不是掉了？

**Comment by yuxuan** [comment]
> 应该是 Dropdown 下一直都是默认就是不 selectable 的

如果menu是multiple的情况下，默认应该是selectable的吧，这样的话，用户需要手动再添加一下selectable了

**Pull request merged**
