### PR TITLE
style: fix Table header radius when has fixed header and columns

### LINKED ISSUE #39115: table 固定列，表格无数据时，右侧边框不显示
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-0-2-forked-tpcu4s?file=/demo.tsx)

### Steps to reproduce

无

### What is expected?

表格右侧显示边框

### What is actually happening?

表格右侧无边框

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | react@18.2.0 |
| System | macOS 13 |
| Browser | chrome 107.0.5304.110 |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/39115#issuecomment-1362314574

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Table header radius missing when has fixed header and columns.        |
| 🇨🇳 Chinese | 修复 Table 列头的圆角丢失问题。          |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
这个是里面滚动的 header 漏出来了吧

**Comment by MadCcc** [comment]
image
这样改好像没用，昨天试了一下可能只有 overflow 可以解

**Comment by afc163** [comment]
https://ant.design/components/table-cn#components-table-demo-fixed-columns-header 这个例子的修了。

https://ant.design/components/table-cn#components-table-demo-fixed-columns 固定列的没修。

**Comment by MadCcc** [comment]
> https://ant.design/components/table-cn#components-table-demo-fixed-columns-header 这个例子的修了。

这个例子还是有问题的

**Comment by MadCcc** [comment]
> https://ant.design/components/table-cn#components-table-demo-fixed-columns-header 这个例子的修了。

这个例子好像还是有问题

**Comment by afc163** [comment]
确实。

**Comment by afc163** [comment]
现在好了

**Comment by afc163** [comment]
来个 +1

**Review by li-jia-nan — APPROVED** [review]

**Pull request merged**
