### PR TITLE
修改时间选择框样式错误问题

### PR DESCRIPTION
**Pull request by jinyaqiao1102**
修改了在IE11下面时间选择框样式错误的问题

### CODE REVIEW

**Comment by jinyaqiao1102** [comment]
image

**Comment by jinyaqiao1102** [comment]
https://github.com/ant-design/ant-design/issues/12598

**Comment by jinyaqiao1102** [comment]
修改了这个问题[https://github.com/ant-design/ant-design/issues/12598](url)

**Comment by afc163** [comment]
commit message should be written in English, maybe next time~

**Comment by jinyaqiao1102** [comment]
OK

**Pull request merged**
