### PR TITLE
fix: eslint-plugin-react 7.28.0 => 7.31.5

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 📝 Changelog
fix: close eslint-plugin check

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
[https://github.com/jsx-eslint/eslint-plugin-react/issues/3388](https://github.com/jsx-eslint/eslint-plugin-react/issues/3388)

**Comment by li-jia-nan** [comment]
> [jsx-eslint/eslint-plugin-react#3388](https://github.com/jsx-eslint/eslint-plugin-react/issues/3388)

#3388

**Comment by MadCcc** [comment]
semver 是 `^` 不需要修改。看起来最新的还是不行。

**Comment by li-jia-nan** [comment]
> semver 是 `^` 不需要修改。看起来最新的还是不行。

Invalid property `onError` found on tag ``
Invalid property `fill` found on tag `<g />`

这两个属性还有问题，我去那边 issues 补充了，等作者再发一版吧

**Pull request closed without merging**
