### PR TITLE
chore: remove lodash/debounce

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [x] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: remove lodash/debounce |
| 🇨🇳 Chinese | chore: remove lodash/debounce |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
`should cancel debounce function when unmount` 这个用例失败了.

**Comment by yoyo837** [comment]
把它用例的 `lodash/debounce` 也换掉吧?

**Review by yoyo837 — APPROVED** [review]

**Comment by li-jia-nan** [comment]
> 把它用例的 `lodash/debounce` 也换掉吧?

done

**Comment by MadCcc** [comment]
怎么包体积还变大了

**Comment by li-jia-nan** [comment]
rc-align 和 react-slick 里面的 lodash 还没干掉

**Pull request merged**
