### PR TITLE
Feat/44477

### PR DESCRIPTION
**Pull request by CYBYOB**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 2d1d987</samp>

This pull request adds a hide code button to the documentation site, refactors the `Badge` and `ColorPicker` components, adds a vertical swipe feature to the `Carousel` component, and updates the changelog and tests. It also improves the import order and code quality of several files.

### <samp>🤖 Generated by Copilot at 2d1d987</samp>

*  Refactor the `useStyle` function to use a closure for the `direction` value from the `ConfigContext` ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-45c8f0859db0c8abbf7a64e88161d5a8d4ffdb66c650e697a073e30dc7f8a5beL26-R83), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-54c90701ed595205ea2cd4286b1cd0ee8b2f01f77a23088e0108feda7af2d65fR70-R94), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-14f85870e2c911caa9b080f35767efa029c02b5ecf4118b487c75145b7554f09L1-R8), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-1158da0914c171fa74b4fa496bef7272ca0776317fb5e222bebdf11477b191fbL3-R7))
* Add a hide code button to the code preview component of the documentation site, using the `UpOutlined` icon and the `app.demo.code.hide.simplify` key for internationalization ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-54c90701ed595205ea2cd4286b1cd0ee8b2f01f77a23088e0108feda7af2d65fR1-R2), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-54c90701ed595205ea2cd4286b1cd0ee8b2f01f77a23088e0108feda7af2d65fL6-R18), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-54c90701ed595205ea2cd4286b1cd0ee8b2f01f77a23088e0108feda7af2d65fL512-R548), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-77dff52935aad07ad5a5a47203c59f4d583e74034fd4695d189bd0c632b86e4bR34), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-b823a78cf4beb8e8ede2c847a6fdfab8b61870bf9deffb35ec6fb7133384e281R34))
* Use JSX syntax instead of `React.createElement` for the `pre` and `code` elements in the `toReactComponent` function ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-086f3227db976462d986107d6240e5fa7cba6d817b889ff580ea55b386950a9dL20-R29))
* Add the `position: absolute` style to the `block` class for the background block of the preview banner ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-9ac0f4a6f5f6e7f8ca9a08ba42c07109b6705731c89c6b1af5daf7e2e9d5850dR46))
* Add the `disabled` prop to the `App` component and its unit test, using the `SmileOutlined` icon ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-52400589dcfd21bced4d2c624c0fbb235acac6ec308f1cf4c3fa37fcc8e80cf8R1), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-52400589dcfd21bced4d2c624c0fbb235acac6ec308f1cf4c3fa37fcc8e80cf8R185-R210))
* Remove the `size` prop from the `Badge` component documentation and code, as it is no longer supported ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-c8fdf756230cf3ebcb4f347ba42136a13694db1ab8c7f95bb30bbfa27fa2ca82L51-R51), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-46d43a0f65a205837cc26cbbec241f700f5a5a74712c02922f11584de845bed4L52-R52))
* Remove the `4.5.0+` version from the `Badge.Ribbon` component documentation, as it is available in all versions ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-c8fdf756230cf3ebcb4f347ba42136a13694db1ab8c7f95bb30bbfa27fa2ca82L57-R57), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-46d43a0f65a205837cc26cbbec241f700f5a5a74712c02922f11584de845bed4L58-R58))
* Extract the `Badge.Ribbon` style to a separate file, using the `prepareToken` and `genRibbonStyle` functions ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-b8c8d1867c9fbda6cf6dad3121f976971c2934a5a5ff1b47aa3984aa0c472809L64), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-b8c8d1867c9fbda6cf6dad3121f976971c2934a5a5ff1b47aa3984aa0c472809L70-R72), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-b8c8d1867c9fbda6cf6dad3121f976971c2934a5a5ff1b47aa3984aa0c472809L85-L91), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-b8c8d1867c9fbda6cf6dad3121f976971c2934a5a5ff1b47aa3984aa0c472809L289-R284), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-b8c8d1867c9fbda6cf6dad3121f976971c2934a5a5ff1b47aa3984aa0c472809R324-R329), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-f9aa8c4ebe6351c36a1004f178a76f580b5fbd0e80e4d41068c3fd06656759b0R1-R78))
* Add the `verticalSwiping` prop to the `SlickCarousel` component, enabling the vertical swiping feature for the `Carousel` component ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-1158da0914c171fa74b4fa496bef7272ca0776317fb5e222bebdf11477b191fbR120))
* Add the `React` import to the `Cascader` and `CodePreviewer` components, and move it to the top of the import list ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-54c90701ed595205ea2cd4286b1cd0ee8b2f01f77a23088e0108feda7af2d65fR1-R2), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804R3), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804L18-R30))
* Use the `export type` syntax to export the `BaseOptionType` and `DefaultOptionType` types from the `Cascader` component ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804L43-R44))
* Add the `disabled` condition to the `onOpenChange` prop of the `Popover` component in the `ColorPickerPanel` component, preventing opening the color picker popup when disabled ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fL232-R231))
* Rename the `ColorPicker` component to `ColorPickerPanel` and move it to a separate file ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fL3))
* Add a test case for the `ColorPicker` component when it is disabled by a button ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-aa06460351e8630f305cf6509e8137984e0f167ab2560da22874033189234fb4R523-R559))
* Use the `useResetIconStyle` import instead of the `useStyle` import to reset the icon style for the `ConfigProvider` component, and move it from the `antd-style` library to the `theme/internal` folder ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-ebba68a5163d0d338dcfda4e41b43d85a68024c0da3745cb20f1fb08189a1943L1-R2))
* Add the `5.8.5` section to the `CHANGELOG` files, documenting the changes and fixes in the latest version of the `antd` library ([link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-e961ad288c43a2feb2d56b696e10c0b670d652dbb17c76c9aa0452d45157977cR19-R36), [link](https://github.com/ant-design/ant-design/pull/44478/files?diff=unified&w=0#diff-1224d5ca5233fdeba67ba2e2dc6fa3e615905253f35dc132c4b4b86f51f9eab4R19-R36))

### CODE REVIEW

**Comment by MadCcc** [comment]
rebase 一下 feature，现在 PR 里带有无关 commit

**Comment by CYBYOB** [comment]
> rebase 一下 feature，现在 PR 里带有无关 commit

好的，我看下

**Comment by yoyo837** [comment]
@github-actions What are you doing? 😨

**Comment by yoyo837** [comment]
@CYBYOB 看上去和你rebase操作有关, 实际此PR没有修改内容被合并.

**Comment by yoyo837** [comment]
新开PR吧

**Comment by CYBYOB** [comment]
> 新开PR吧

嗯嗯，在操作了~
本来我打算直接往master提PR的。

**Pull request merged**
