### PR TITLE
style(💄): optimize Skeleton color

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

| ❌ before | ✅ after |
| --- | --- |
| image | image |

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Optimize Skeleton color to fit dark background. |
| 🇨🇳 Chinese | 优化 Skeleton 默认色彩使其能放置在暗色背景中。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://preview-27836-ant-design.surge.sh/components/skeleton-cn/?theme=dark

image

暗色主题下有点问题，`background: rgba(0,0,0,0.8);` 这个颜色不知道从哪来的。

**Comment by afc163** [comment]
呃，https://github.com/chenshuai2144/antd-pro-merge-less/blob/deb93f66957b0474392af59bb7a6af6fa0ca7324/index.js#L38

@chenshuai2144

**Comment by afc163** [comment]
见鬼了，这个 `rgba(0,0,0,0.8)` 还在。

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/e3a013f6cf3602bf510e431146516a7117dcc850/components/style/themes/dark.less#L412

**Comment by xrkffgg** [comment]
确实见鬼了。。。。

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design-dark-theme/blob/1671d6d6bb0563a1acde31b4b0bffbfc9783b39d/index.ts#L45

也许因为这个

**Comment by xrkffgg** [comment]
antd-pro-merge-less  引的

"@ant-design/dark-theme": "^2.0.2",

**Comment by afc163** [comment]
发现了，@ant-design/dark-theme 和 antd-pro-merge-less 里面挺乱的，我试着去掉这俩。

**Comment by afc163** [comment]
先合并，代码本身没问题，theme 生成的问题我另起 PR。

**Pull request merged**
