### PR TITLE
Add sortColumn to title render

### LINKED ISSUE #19007: Table Title render function does not have enough information about the current column that is sorted
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/embed/elastic-banach-9ztse)

### Steps to reproduce
Open the codesandbox console and click sort on name, observe the log message.

"ascend/descend, but no column name 
Object {filters: Object, sortOrder: null}"

### What is expected?
The object should contain the "dataIndex" of the currently sorted column/columns

### What is actually happening?
DataIndex is not available to the title render function so the ascending/descending information cannot be used to render a header for a specific column.

### Other
This has already been mentioned here a couple of times: https://github.com/ant-design/ant-design/issues/11246#issuecomment-430943407

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | Mac OS X Mojave |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by swillis12**
Fixes #19007

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [X] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design/ant-design/issues/19007

Title render function is missing information about exactly which column is currently sorted. This is limiting when trying to render a custom sorter.

### 💡 Background and solution

Solution is to send the `sortColumn` that is stored in the table state. This way the user can infer which column is currently sorted while implementing the `title` render function.

### 📝 Changelog

Title render function argument object now contains a new key, `sortColumn`.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered components/table/index.en-US.md](https://github.com/swillis12/ant-design/blob/issues/19007/components/table/index.en-US.md)
[View rendered components/table/index.zh-CN.md](https://github.com/swillis12/ant-design/blob/issues/19007/components/table/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
feature branch please~

**Comment by swillis12** [comment]
> feature branch please~

@afc163 I changed the base branch to `feature`, let me know if I need to do anything else on my end.

**Comment by afc163** [comment]
You need to checkout from feature then send PR to it.

**Comment by swillis12** [comment]
I have done this incorrectly, let me open a new PR

**Comment by swillis12** [comment]
New PR on feature branch here: https://github.com/ant-design/ant-design/pull/19012

**Pull request closed without merging**
