### PR TITLE
feat(transfer): add searchValue prop

### PR DESCRIPTION
**Pull request by huangkairan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#32663

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    tranfer add searchValue prop       |
| 🇨🇳 Chinese |    穿梭框增加searchValue属性       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
检查一下 ci 。

**Comment by huangkairan** [comment]
> 检查一下 ci 。

好的

**Comment by huangkairan** [comment]
@afc163 @zombieJ 
image

**Comment by afc163** [comment]
searchValue 要做成受控的，需要配合 onSearch 来修改。

**Review by afc163 — CHANGES_REQUESTED** [review]
searchValue 要做成受控的，需要配合 onSearch 来修改。

API 改成这样吧。

```jsx
showSearch={{
  value,
  onChange,
}}
```

**Comment by huangkairan** [comment]
> searchValue 要做成受控的，需要配合 onSearch 来修改。
> 
> API 改成这样吧。
> 
> ```js
> showSearch={{
>   value,
>   onChange,
> }}
> ```

好的，年前有点忙没怎么跟进，近期会处理一下哈

**Comment by afc163** [comment]
trace #34460

**Pull request closed without merging**
