### PR TITLE
bugfixs: icon style is incorrect in button group

### PR DESCRIPTION
**Pull request by xueqingxiao**

### CODE REVIEW

**Comment by xueqingxiao** [comment]
In my code:
screen shot 2016-06-28 at 3 46 54 pm

My dom tree:
screen shot 2016-06-28 at 6 17 08 pm

Official demo dom tree:
screen shot 2016-06-28 at 4 00 10 pm

My box model of 'icon down':
screen shot 2016-06-28 at 4 01 39 pm

Official demo model of 'icon down':
screen shot 2016-06-28 at 4 01 21 pm

**Comment by afc163** [comment]
Need reproduce:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by xueqingxiao** [comment]
if set the line-height as 1.5 or remove line height, in my demo. Dropdown.Button will be normal. otherwise, it's looks like pic 1. but I don't know why. @afc163

**Comment by xueqingxiao** [comment]
@afc163 I'm trying to reproduce this, but I can't in codepen. I will close this pr & just override style in my code. THX

**Pull request closed without merging**
