### PR TITLE
feat: Added Irish(ga_IE) locale (add for patch older version 3.26.17)

### PR DESCRIPTION
**Pull request by AbhijeetGaware**
Reverts ant-design/ant-design#24609
when Upgraded  newer version antd(4.3.1) all DatePicker UI is changed we are using older version(3.26.17) we need to Patch locale for irish(ga_IE) for 3.26.17 

-----
[View rendered docs/react/i18n.en-US.md](https://github.com/AbhijeetGaware/ant-design/blob/revert-24609-AbhijeetGaware-abhiAddLanguage29052020/docs/react/i18n.en-US.md)
[View rendered docs/react/i18n.zh-CN.md](https://github.com/AbhijeetGaware/ant-design/blob/revert-24609-AbhijeetGaware-abhiAddLanguage29052020/docs/react/i18n.zh-CN.md)

### CODE REVIEW

**Comment by yoyo837** [comment]
Pls don’t revert it, just add patch for old version.

**Comment by yoyo837** [comment]
Welcome for PR again.

**Comment by AbhijeetGaware** [comment]
> Pls don’t revert it, just add patch for old version.

**Comment by AbhijeetGaware** [comment]
> Welcome for PR again.

@yoyo837 okay thank you

**Comment by yoyo837** [comment]
Branch: 3.x-stable

**Comment by AbhijeetGaware** [comment]
https://github.com/ant-design/ant-design/pull/24769

**Comment by yoyo837** [comment]
1. send PR to https://github.com/react-component/pagination/tree/1.x-stable
2. send PR to https://github.com/react-component/calendar/tree/9.x
3. send PR to https://github.com/ant-design/ant-design/tree/3.x-stable

**Pull request closed without merging**
