### PR TITLE
test: js => ts

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog
test: js => ts

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by zongjiancai** [comment]
合并

**Comment by li-jia-nan** [comment]
有个很奇怪的 eslint error，不知道怎么解决，在 eslint config 里面加了 `'react/no-unknown-property': 1`，这个需要确认一下

**Comment by afc163** [comment]
具体啥问题，截个图？

**Comment by li-jia-nan** [comment]
> 具体啥问题，截个图？

9AB1890E-1381-4fc1-893D-91A35F7E90EC

找到原因了，和 #37269 这个pr有关系，把ts版本回退到 4.7.2 就可以了

**Comment by afc163** [comment]
https://github.com/jsx-eslint/eslint-plugin-react/issues/3384

**Comment by afc163** [comment]
我看作者已经修复了相关问题，本地更新一下版本？https://github.com/jsx-eslint/eslint-plugin-react/commits/master

**Comment by li-jia-nan** [comment]
> 我看作者已经修复了相关问题，本地更新一下版本？https://github.com/jsx-eslint/eslint-plugin-react/commits/master

可以了，`eslint-plugin-react` 升级到最新版是没问题的

> 我看作者已经修复了相关问题，本地更新一下版本？https://github.com/jsx-eslint/eslint-plugin-react/commits/master

最新版 7.13.4 依然不行

**Comment by li-jia-nan** [comment]
> 我看作者已经修复了相关问题，本地更新一下版本？https://github.com/jsx-eslint/eslint-plugin-react/commits/master

最新版 7.13.4 依然不行

**Comment by li-jia-nan** [comment]
> 我看作者已经修复了相关问题，本地更新一下版本？https://github.com/jsx-eslint/eslint-plugin-react/commits/master

我把 eslint config 先还原了

**Comment by li-jia-nan** [comment]
- #37383 ci 报错通过这个 pr 解决

**Pull request closed without merging**
