### PR TITLE
feat: Malayalam(ml_IN) translation

### PR DESCRIPTION
**Pull request by khjabir**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
Malayalam (ML_IN) locales were missing.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Added Malayalam (ml_IN) locale |
| 🇨🇳 Chinese | 添加马拉雅拉姆语 (ml_IN) 语言环境 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
1. `components/locale-provider/__tests__/config.test.js` add test case.
2. Add it in to `i18n.en-US.md` and `i18n.zh-CN.md`.

**Comment by khjabir** [comment]
> 1. `components/locale-provider/__tests__/config.test.js` add test case.
> 2. Add it in to `i18n.en-US.md` and `i18n.zh-CN.md`.

@yoyo837 Done

**Comment by yoyo837** [comment]
CI failed.

**Comment by khjabir** [comment]
> CI failed.

@yoyo837 
Are you sure it is failed because of changes in this commit?
I couldn't find any breaking changes. Please enlighten me.

**Comment by yoyo837** [comment]
run: `npm test -- -u` and push all changes.

**Comment by yoyo837** [comment]
It looks like you still need to do:
1. rebase upstream
2. remove `node_modules` and `package-lock.json`(or `yarn.loc`)
3. reinstall
4. run: `npm test -- -u` and push all changes

**Comment by yoyo837** [comment]
@afc163 这 bundlesize 不像是这个PR搞的.

**Review by afc163 — APPROVED** [review]

**Pull request merged**
