### PR TITLE
Fix 5322

### PR DESCRIPTION
**Pull request by keqingrong**
Refactor preSuffix to affix

### CODE REVIEW

**Comment by keqingrong** [comment]
The first time is so hard...  I might need help 💔

**Comment by yesmeck** [comment]
1. `git checkout master`
1. `git pull origin master`
1. `git checkout fix-5322`
1. `git rebase master`
1. `npm test -- -u`
1. `git add .`
1. `git rebase --continue`
1. `git push your-own-remote fix-5322 -f`

**Comment by keqingrong** [comment]
@yesmeck It works. Thank you so much!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5322

**Pull request merged**
