### PR TITLE
fix: Typography copyable tooltips

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design/ant-design/pull/25953#issuecomment-674480396

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Typography `copyable.tooltips` cannot accept `['', '']`. |
| 🇨🇳 Chinese | 修复 Typography `copyable.tooltips` 属性不支持 `['', '']` 的问题。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by xrkffgg — APPROVED** [review]

**Comment by llwslc** [comment]
这个我那天做了一下,  如果以 `''` 代表不显示, 那就和以前不兼容了吧, 如果以前有人以 `['', 'you clicked!!']`定制 tooltips, 升级以后现象不一致了.

**Comment by afc163** [comment]
`['', 'you clicked!!']` 预期就应该是第一个不显示。

**Comment by llwslc** [comment]
哦, 但以前不是, 改完之后应该算不兼容了吧...

**Comment by llwslc** [comment]
哦, 是算bug修复了吗?

**Comment by afc163** [comment]
是 bug 修复，`<Tooltip title="" />` 应该就是不展示。

**Comment by llwslc** [comment]
copyable.tooltips 属性如果支持 `['', '']`, 那设置 `false` 隐藏 tooltip 是不是没必要了?

**Comment by afc163** [comment]
留着吧，算是个语法糖。

**Pull request merged**
