### PR TITLE
feat: ColorPicker Implement onChangeComplete API

### PR DESCRIPTION
**Pull request by RedJue**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Implement `onChangeComplete` API      |
| 🇨🇳 Chinese |    实现 `onChangeComplete` API       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at afa13fc</samp>

This pull request adds a new `onChangeComplete` prop to the `ColorPicker` component, which allows users to handle the final color value after picking a color. It also adds a test case and updates the documentation for the new prop.

### <samp>🤖 Generated by Copilot at afa13fc</samp>

*  Add `onChangeComplete` prop to `ColorPicker` component, which is a callback function that is invoked when the user finishes picking a color from the color picker panel ([link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fL33-R33), [link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR58), [link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR89), [link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR164))
*  Pass `onChangeComplete` prop to `useColorPicker` hook, which handles the color picker logic and calls the prop with the new color value ([link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR89), [link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR164))
*  Document `onChangeComplete` prop in `index.en-US.md` and `index.zh-CN.md` files, which are the English and Chinese documentation files for the `ColorPicker` component ([link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-819859f3d30fc8ec12a8ef1b55ac1d75b4b1d600eb1cee989efd5af57255b560R61), [link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-9d1ff106a032e484c8f982279c4e1295d23f69904a26e020e99310c446e93249R62))
*  Test `onChangeComplete` prop in `index.test.tsx` file, which is the test file for the `ColorPicker` component. The test case uses a spy function and a jest mock function to simulate the color picker panel and the prop, and expects the prop to be called with the correct color value ([link](https://github.com/ant-design/ant-design/pull/43370/files?diff=unified&w=0#diff-aa06460351e8630f305cf6509e8137984e0f167ab2560da22874033189234fb4R400-R414))

### CODE REVIEW

**Review by kiner-tang — APPROVED** [review]

**Comment by afc163** [comment]
有相关背景讨论么？

**Comment by MadCcc** [comment]
> 有相关背景讨论么？

惰性回调，只有鼠标松开时才会触发

**Comment by MadCcc** [comment]
来个 demo 演示一下？

**Comment by RedJue** [comment]
> 有相关背景讨论么？
同步其他颜色选择器库类似的 API ，方便用户过度平替，https://casesandberg.github.io/react-color/#api-onChangeComplete

**Comment by RedJue** [comment]
> 来个 demo 演示一下？

嗯嗯 我加一个

**Review by li-jia-nan — APPROVED** [review]

**Review by Wxh16144 — APPROVED** [review]
还有一个 argos 需要 review 一下

**Comment by MadCcc** [comment]
加个受控的例子看下么，受控情况下 trigger 的颜色应该和受控值一致

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
