### PR TITLE
ci: ignore prerelease site deploy

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 💡 Background and solution
发布版本不包含 `-` 时，进行网站部署

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |       -    |
| 🇨🇳 Chinese |      -     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by xrkffgg** [comment]
title 包含 release 触发 校验，无视之

**Comment by afc163** [comment]
prerelease 这种词不应该触发吧，检测条件可以改成 ` release ` 或者 ` releases `。

**Comment by xrkffgg** [comment]
OK，我测试下 这个 contains 对空格有处理么

**Comment by xrkffgg** [comment]
> prerelease 这种词不应该触发吧，检测条件可以改成 `" release "` 或者 `" releases "`。

这个我另优化吧

**Pull request merged**
