### PR TITLE
fix: upgrade rc-tooltip lint fail

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Ref: https://github.com/ant-design/ant-design/pull/19179#issuecomment-545787006

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
`+ rc-tooltip@4.0.0-alpha.1`

**Comment by shaodahong** [comment]
wait to [upgrade `rc-trigger` finish](https://github.com/ant-design/ant-design/issues/19169), because of use `rc-trigger` typescript type

**Comment by zombieJ** [comment]
`+ rc-trigger@4.0.0-alpha.6`

**Comment by shaodahong** [comment]
https://github.com/ant-design/ant-design/blob/4cae32842fc8d376fad6891b8327752a8d9b51c1/components/menu/__tests__/index.test.js#L323

@zombieJ 
this test is too werid, `inline` mode but expect `vertical`?

```jsx
expect(
  wrapper
    .find('.ant-menu-submenu')
    .at(0)
    .hasClass('ant-menu-submenu-vertical'),
).toBe(true);
```

**Comment by zombieJ** [comment]
`inlineCollapsed`  is this case: https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed

**Comment by shaodahong** [comment]
> `inlineCollapsed` is this case: https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed

yep, but class is `ant-menu-submenu-inline`

**Comment by shaodahong** [comment]
> https://github.com/ant-design/ant-design/blob/4cae32842fc8d376fad6891b8327752a8d9b51c1/components/menu/__tests__/index.test.js#L323
> 
> this test is too weird, `inline` mode but expect `vertical`?
> 
> ```js-jsx
> expect(
>   wrapper
>     .find('.ant-menu-submenu')
>     .at(0)
>     .hasClass('ant-menu-submenu-vertical'),
> ).toBe(true);
> ```

may check below test, but I don't know why in this test to expect
https://github.com/ant-design/ant-design/blob/4cae32842fc8d376fad6891b8327752a8d9b51c1/components/menu/__tests__/index.test.js#L19

**Comment by zombieJ** [comment]
`rc-menu` has complex logic and some dirty code which may hard to understand about className, but it should keep these className since Menu with mixed status like inline & collapsed will both have inline & popup related className. And menu style file both use then to handle some mixed style.

**Comment by shaodahong** [comment]
@chenshuai2144 `rc-calendar` 10.0.0-alpha.1 version cause typescript lint fail https://circleci.com/gh/ant-design/ant-design/136908?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link, can you resolve it? thanks

**Pull request merged**
