### PR TITLE
doc: split demos

### LINKED ISSUE #17396: Split Result Demo
我还是坚持把 Result demo 分开。

https://github.com/ant-design/ant-design/pull/17244#discussion_r298832459

### PR DESCRIPTION
**Pull request by chenshuai2144**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

 #17396

### 💡 Solution

close #17396

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/result/demo/403.md](https://github.com/ant-design/ant-design/blob/split-result-demo/components/result/demo/403.md)
[View rendered components/result/demo/404.md](https://github.com/ant-design/ant-design/blob/split-result-demo/components/result/demo/404.md)
[View rendered components/result/demo/500.md](https://github.com/ant-design/ant-design/blob/split-result-demo/components/result/demo/500.md)
[View rendered components/result/demo/basic.md](https://github.com/ant-design/ant-design/blob/split-result-demo/components/result/demo/basic.md)
[View rendered components/result/demo/complex.md](https://github.com/ant-design/ant-design/blob/split-result-demo/components/result/demo/complex.md)
[View rendered components/result/demo/customIcon.md](https://github.com/ant-design/ant-design/blob/split-result-demo/components/result/demo/customIcon.md)

### CODE REVIEW

**Comment by afc163** [comment]
Thaw => unlock

**Comment by afc163** [comment]
一不做二不休，都打平了吧。

图片

**Comment by afc163** [comment]
图片

这个地方加粗有点奇怪，视觉重点不应该盖过上面的主标题。

**Comment by afc163** [comment]
图片

上面是原来的，图标颜色也不太对。

**Comment by chenshuai2144** [comment]
我们的 text 竟然没有纯黑的字。

**Comment by afc163** [comment]
40x 系列放在四个基本状态后面，success 的放在前面。

**Pull request merged**
