### PR TITLE
fix: Autocomplete children cannot use InputNumber

### LINKED ISSUE #37470: autocomplete set InputNumber children,it will be error when I input anything
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/bu-qu-fen-da-xiao-xie-antd-4-23-0-forked-nv86yp?file=/demo.js)

### Steps to reproduce

1. open https://codesandbox.io/s/bu-qu-fen-da-xiao-xie-antd-4-23-0-forked-nv86yp?file=/demo.js
2. input anything in InputNumber
3. error 🥵

### What is expected?

I want to input something and select options

### What is actually happening?

if I input , having error in console

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 16.14.0 |
| System | mac os monterey 12.2.1 |
| Browser | 104.0.5112.101 |

### PR DESCRIPTION
**Pull request by kev5n**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix: [autocomplete set InputNumber children,it will be error when I input anything](https://github.com/ant-design/ant-design/issues/37470)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix: Autocomplete children cannot use InputNumber|
| 🇨🇳 Chinese |修复 Autocomplete在自定义输入框使用InputNumber报错问题|

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
Please provide a test case.

**Comment by kev5n** [comment]
> 请提供一个测试用例。

Inputnumber test has been added

**Comment by afc163** [comment]
Conflicting

**Comment by li-jia-nan** [comment]
Hi @kev5n 

Thank you for your contribution!

We noticed that this PR hasn't been updated in a while. To keep the project active and maintainable, we'll be closing this PR for now.

If you'd like to proceed with these changes, please feel free to open a new PR.

Thanks again for your contribution!

**Pull request closed without merging**
