### PR TITLE
feat: Fix empty href and Add disabled option for breadcrumb route

### PR DESCRIPTION
**Pull request by AliRezaBeigy**
fix empty href and add disabled option for breadcrumb route

###  This is a ...

- [x] New feature
- [x] Bug fix
- [x] Enhancement feature

### 💡 Background and solution

the problem raised when developer need to have a disabled item in breadcrumb
when developer try to pass empty string to path, the a tag with empty href rendered that link to the current browser uri path
so i add an option to have disabled route
image

### 📝 Changelog

disabled option in Route to have disabled breadcrumb item
pass empty path not render an a tag with empty href

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [x] TypeScript definition is not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
feature branch please~

**Comment by AliRezaBeigy** [comment]
@afc163 done.

**Comment by afc163** [comment]
Please rebase feature to fix ci.

**Comment by afc163** [comment]
ping @AliRezaBeigy

**Comment by AliRezaBeigy** [comment]
I think i should create new pull request 😬

**Pull request closed without merging**
