### PR TITLE
fix: devWarning valid mistake for successPercent (progress.tsx)

### PR DESCRIPTION
**Pull request by c6po**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

1. Describe the problem and the scenario.
We are website in prod using antd, and we see a warning when using the Progress component about successPercent depreciation, but this props is not being used.
2. GIF or snapshot should be provided if includes UI/interactive modification.

3. How to fix the problem, and list final API implementation and usage sample if that is an new feature.
It's just little mistake on devWarning()

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by fireairforce** [comment]
It seems that i have fixed this bug in https://github.com/ant-design/ant-design/pull/25356/files#diff-a71668206e75e86863880131001b74a7R137 
Maybe you need to update your code in the master branch.

**Comment by hengkx** [comment]
https://github.com/react-component/util/blob/master/src/warning.ts#L28
一般不是`true`执行吗 怎么写了个`false`执行...

**Review by hengkx — APPROVED** [review]

**Comment by fireairforce** [comment]
> https://github.com/react-component/util/blob/master/src/warning.ts#L28

这个我已经修改了= =，这个pr 重复了。。。。代码没更新

**Review by fireairforce — CHANGES_REQUESTED** [review]
pr is duplicated

**Comment by hengkx** [comment]
没理解

**Comment by fireairforce** [comment]
就是他提交的这个pr实际上我在另外一个pr里面已经修复了 https://github.com/ant-design/ant-design/pull/25356。。。

**Comment by hengkx** [comment]
是合完 又做了 修改？

**Comment by fireairforce** [comment]
应该是他那边的代码没有更新。。。我去看了下他fork过来的repo的master分支,确实是没更新我已经合并的那次pr。。。

**Comment by hengkx** [comment]
那这个应该合进去吧

**Comment by afc163** [comment]
master 上已经是正确的了：https://github.com/ant-design/ant-design/blob/master/components/progress/progress.tsx#L137

**Comment by vvoynier** [comment]
Thanks for the fix @fireairforce !

**Pull request closed without merging**
