### PR TITLE
chore: revert locked React version

### PR DESCRIPTION
**Pull request by li-jia-nan**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | revert: revert locked React version |
| 🇨🇳 Chinese | revert: revert locked React version |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
@SocketSecurity ignore npm/@ant-design/tools@18.0.2
@SocketSecurity ignore npm/@biomejs/biome@1.7.1

**Review by cesar18pena — APPROVED** [review]

**Comment by afc163** [comment]
还差什么？

**Comment by li-jia-nan** [comment]
> 还差什么？

闲夕大佬说 `findDOMNode is deprecated` 的警告别忽略，很多用例就是测这个的

这样的话 React 版本就要锁在 18.2.0 了，所以我不确定这个 PR 能不能合

**Comment by yoyo837** [comment]
Close by #48958

**Pull request closed without merging**
