### PR TITLE
docs: docs upgrade

### PR DESCRIPTION
**Pull request by yoyo837**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

https://github.com/ant-design/ant-design/issues/18336#issuecomment-522504314

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |       docs upgrade    |
| 🇨🇳 Chinese |      更新文档     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/config-provider/demo/locale.md](https://github.com/ant-design/ant-design/blob/es2lib/components/config-provider/demo/locale.md)
[View rendered components/config-provider/index.en-US.md](https://github.com/ant-design/ant-design/blob/es2lib/components/config-provider/index.en-US.md)
[View rendered components/config-provider/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/es2lib/components/config-provider/index.zh-CN.md)
[View rendered components/date-picker/index.en-US.md](https://github.com/ant-design/ant-design/blob/es2lib/components/date-picker/index.en-US.md)
[View rendered components/date-picker/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/es2lib/components/date-picker/index.zh-CN.md)
[View rendered docs/react/getting-started.zh-CN.md](https://github.com/ant-design/ant-design/blob/es2lib/docs/react/getting-started.zh-CN.md)
[View rendered docs/react/i18n.en-US.md](https://github.com/ant-design/ant-design/blob/es2lib/docs/react/i18n.en-US.md)
[View rendered docs/react/i18n.zh-CN.md](https://github.com/ant-design/ant-design/blob/es2lib/docs/react/i18n.zh-CN.md)

### CODE REVIEW

**Comment by hengkx** [comment]
这个是为什么由 es 改为了 lib

**Comment by yoyo837** [comment]
> 这个是为什么由 es 改为了 lib

找不到原来的链接引用了，依稀记得有这么个事儿。

**Comment by xrkffgg** [comment]
PR 上面有个链接

**Comment by yoyo837** [comment]
> PR 上面有个链接

不是指这个，是更早的时候的事

**Comment by hengkx** [comment]
是pro那边的吗？ 我也有点 印象 但是 忘了 为什么

**Pull request merged**
