### PR TITLE
chore: upgrade size-limit

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: upgrade size-limit |
| 🇨🇳 Chinese |          - |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 10460e0</samp>

Increased the size limits for `antd.min.js` and `antd-with-locales.min.js` in `package.json` to allow new features and fixes for React 17, `Image` component, and accessibility and performance.

### <samp>🤖 Generated by Copilot at 10460e0</samp>

* Increase size limits for bundled files `antd.min.js` and `antd-with-locales.min.js` to accommodate new features and fixes ([link](https://github.com/ant-design/ant-design/pull/43344/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L315-R319))

### CODE REVIEW

**Comment by yoyo837** [comment]
什么编号需要加大

**Comment by li-jia-nan** [comment]
image

**Comment by yoyo837** [comment]
建议下次直接贴图或者讲一下原因, 免得疑惑

**Comment by li-jia-nan** [comment]
> 建议下次直接贴图或者讲一下原因, Changelog 也是空的, 私聊也看不见, 免得疑惑

因为 #43342 这个 PR 中 size limit 挂了，所以去找闲夕沟通了一下，于是有了这个 PR

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
