### PR TITLE
feat(date-picker): support custom format

### PR DESCRIPTION
**Pull request by kerm1it**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | DatePicker support custom format. |
| 🇨🇳 Chinese | 日期选择器支持自定义格式化。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/date-picker/demo/format.md](https://github.com/ant-design/ant-design/blob/feat-picker-custom-format/components/date-picker/demo/format.md)
[View rendered components/date-picker/index.en-US.md](https://github.com/ant-design/ant-design/blob/feat-picker-custom-format/components/date-picker/index.en-US.md)
[View rendered components/date-picker/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/feat-picker-custom-format/components/date-picker/index.zh-CN.md)

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
@zombieJ 是不是 trigger 导致的问题？

我看是 tooltip 和 popconfirm 的 用例失败了。

**Comment by zombieJ** [comment]
我 feature 合一下 master

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/26851

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
