### PR TITLE
fix: Reset the last selection key

### LINKED ISSUE #34678: First Shift+Click to select row after deselect all is getting a bulk selection
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/j6uoxe)

### Steps to reproduce

1) Shift click to select row 3, then press shift click to select row 6 (it will bulk selection of 4 rows)
2) Click on select all checkbox in the column header (it will select all rows)
3) Then, click to deselect all (it will deselect all rows)
4) Try to initiate a new bulk selection by shift click to select row 1

### What is expected?

It should start bulk selection again by initiating the range selection.

### What is actually happening?

It is keeping somehow the last event click and continue the range selection.

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17.0.2 |
| System | iOS latest |
| Browser | Google chrome latest |

### PR DESCRIPTION
**Pull request by Dunqing**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix: #34678

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   reset the last selection key when deselect  or bulk operations  |
| 🇨🇳 Chinese |  取消选择或批量操作时重置上一次选择的key  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Could you add a test case?

**Comment by 1247748612** [comment]
> Could you add a test case?

done

**Comment by MadCcc** [comment]
test case 删掉点空行吧

**Comment by MadCcc** [comment]
这个 codeFactor 好严格。。

**Comment by Dunqing** [comment]
> 这个 codeFactor 好严格。。

确实有些大了 要拆分吗

**Review by ErciliaR — APPROVED** [review]

**Comment by MadCcc** [comment]
拆个 test case 看看？

**Comment by Dunqing** [comment]
> 拆个 test case 看看？

通过了，不用改了😂
现在这个文件行数已经1600+，我提PR的时候才超1000。

**Comment by afc163** [comment]
>  现在这个文件行数已经1600+，我提PR的时候才超1000。

早晚得拆。

**Comment by Dunqing** [comment]
> 早晚得拆。

等迁移到testling-libary时再拆吧，不在这个PR改

**Comment by Dunqing** [comment]
> > 早晚得拆。
> 
> 等迁移到testling-libary时再拆吧，不在这个PR改

刚发现已经迁移过去了

**Comment by Dunqing** [comment]
done

**Pull request merged**
