### PR TITLE
Accessibility fix: aria-label cannot be used with role="presentation".

### LINKED ISSUE #40412: Accessibility: Table sort icons with role="presentation" must not have aria-labels
### Reproduction link

[https://ant.design/~demos/components-table-demo-head](https://ant.design/~demos/components-table-demo-head)

### Steps to reproduce

Open the example and inspect the source code with dev tools. You will see the next code for table column sorter icons:
```
<span role="presentation" aria-label="caret-up" class="anticon anticon-caret-up ant-table-column-sorter-up">...</span>
<span role="presentation" aria-label="caret-down" class="anticon anticon-caret-down ant-table-column-sorter-down active">...</span> 
```
Analyze the page accessibility with Lighthouse or Axe accessibility plugin. 

### What is expected?

Element with role="none" or role="presentation" must not have one of the following characteristics:
- A global ARIA attribute.

Error description: [Deque university](https://dequeuniversity.com/rules/axe/4.2/presentation-role-conflict).

### What is actually happening?

The accessibility error: Each ARIA `role` supports a specific subset of `aria-*` attributes. Mismatching these invalidates the `aria-*` attributes. Aria-label attribute cannot be used with role "null".
Error description: [Deque university](https://dequeuniversity.com/rules/axe/4.4/aria-allowed-attr?utm_source=lighthouse&utm_medium=devtools).
Impact: serious.

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.0.0 |
| System | Windows 10 |
| Browser | Chrome 109.0.5414.119 |

---
Proposed solution: remove aria-label for the sort icons

### PR DESCRIPTION
**Pull request by Ke1sy**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/40412

Ref: UIEN-3276
### 💡 Background and solution

Table column sorter icons have a serious accessibility issue 
Elements with role="presentation" must not have aria-label attribute.
``` 
<span role="presentation" aria-label="caret-up" class="anticon anticon-caret-up ant-table-column-sorter-up">...</span>
<span role="presentation" aria-label="caret-down" class="anticon anticon-caret-down ant-table-column-sorter-down active">...</span> 
```
`Presentation` role declares that an element is being used only for presentation and therefore does not have any accessibility semantics.
Solution: aria-label attribute is removed for these icons.
### 📝 Changelog

Accessibility fix: aria-labels are removed from table sort icons 

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     ☑️   |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by mellis481** [comment]
@afc163 Is something wrong w/ the `test-argos-ci-workflow` step? It doesn't seem like anything in this PR would have broken the workflow.

**Review by Wxh16144 — APPROVED** [review]

**Comment by MadCcc** [comment]
Could we move `role="presentation"` to the wrapper?

**Comment by Ke1sy** [comment]
> aria-label

@MadCcc we use `role="presentation" ` to override the `role="img"` that is set to the icon, aria-label of the images is announced by default when we focus the table header "Age caret-up caret-down  column header  sorted descending  row 1  Age caret-up caret-down  column 2". 
We cannot move `role="presentation"` on wrapper because it still will be announced, by we can use `aria-hidden="true"` to hide  its children from the accessibility tree.
Should I make this change?

**Comment by Ke1sy** [comment]
@MadCcc I moved the aria attributes to the wrapper. Could you please review it?

**Comment by afc163** [comment]
@mellis481 Any suggestion about this change?

**Comment by mellis481** [comment]
@afc163 Hiding the wrapper seems fine to me because:
1. the caret is not focusable.
2. we're relying on `aria-sort` on the `<th>` to announce the sort direction, not the icon `aria-label`.

So, in conclusion, the solution is to:
1. apply `aria-hidden="true"` to the `-column-sorter-inner` element so the caret won't be announced at all.
2. remove `role="presentation"` on the icon so a11y tools won't complain about it having an `aria-label` and the icon can continue to have an `aria-label`.

CC: @Ke1sy @MadCcc

**Review by afc163 — APPROVED** [review]

**Pull request merged**
