### PR TITLE
chore: upgrade rc-tooltip to 4.1.0(#19536)

### LINKED ISSUE #19536: Tooltip 组件隐藏后，希望能删除 DOM 节点
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

## 现状
Tooltip 展示时会向 DOM 中插入一个 div 节点，以及一些子节点。但是隐藏时并没有删除这个节点。当页面中有很多个 Tooltip 实例时，每展示一个就会向 DOM 中插入一组节点，越来越多。
如图所示：

## 预期
希望 Tooltip 在隐藏后，能够删除对应的 DOM 节点。或者，提供一个配置项，支持用户选择是否要清理 DOM 节点。
好处：
1. 页面 DOM 结构更干净。
2. 尽管多数时候可能影响不大，但是回收 DOM 节点，减少内存占用，是一种比较常见的最佳实践。

### What does the proposed API look like?
参考 Ant Modal 组件的 `destroyOnClose`，可以增加一个 `destroyOnHide` 参数。
e.g. 
```jsx
<Tooltip title="hover text" destroyOnHide>text</Tooltip>
```

### PR DESCRIPTION
**Pull request by kerm1it**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix [#19536](https://github.com/ant-design/ant-design/issues/19536)

### 📝 Changelog

upgrade `rc-tooltip` 4.1.0, `destroyTooltipOnHide` prop support `{ keepParent?: boolean}` to destroy parent container of tooltip instead of only itself when closing

更新`rc-tooltip@4.1.0`, `destroyTooltipOnHide` 支持`{ keepParent?: boolean}`,可以删除tooltip的父级容器而不是只删除本身。

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
发到 feature 分支再补充一下文档吧。

**Comment by Kermit-Xuan** [comment]
OK,使用补充到antd的tooltip组件中是吧？

**Comment by afc163** [comment]
对

**Comment by Kermit-Xuan** [comment]
@afc163  已经发了PR，更新了API文档，添加了个使用demo。

**Pull request merged**
