### PR TITLE
Fix form types and add type test

### PR DESCRIPTION
**Pull request by yesmeck**
Refer to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/913d4de374d9950d60d59b164ee54988142bad6c/types/react-redux/index.d.ts#L38

### CODE REVIEW

**Comment by afc163** [comment]
What is the benefits?

**Comment by yesmeck** [comment]
You can try compile the test file using the original type.

**Comment by afc163** [comment]
```
components/form/__tests__/type.test.tsx(38,24): error TS2339: Property 'name' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<{}, ComponentState>> & Readonly<{ childr...'.
```

**Comment by afc163** [comment]
rebase

**Comment by yesmeck** [comment]
😳这个覆盖率。。。

**Comment by afc163** [comment]
没道理。

**Comment by mitchelldemler** [comment]
This is a breaking change for me.

I am using @types/react 15.0.24 (upgrading breaks my build when importing antd components)

How I am currently implementing FormComponentProps:
```
import * as React from 'react';
import { Form } from 'antd';
import { FormComponentProps } from 'antd/lib/form/Form';

export interface IOwnProps {
    prop1: string;
    prop2: string;
}

export class LoginFormComponent extends React.Component<IOwnProps & FormComponentProps, {}> {
    public render() {
        return (
            <Form />
        );
    }
}

export default Form.create<IOwnProps>({})(LoginFormComponent);
```

When upgrading to antd 2.12.7 I get 'Property 'form' is missing in type...' when consuming the Form:

```
<LoginForm prop1="aaaa" prop2="bbbb" />
```

**Comment by yesmeck** [comment]
@miaojiuchen Try `interface IOwnProps extends FormComponentProps`.

**Comment by mitchelldemler** [comment]
Same error. I will try upgrade my project to use latest types. Can you confirm what version of react types you are using?

**Comment by yesmeck** [comment]
Oh. `export default Form.create<IOwnProps>({})(LoginFormComponent);`

You don't need pass `IOwnProps` to `Form.create`.

**Comment by mitchelldemler** [comment]
No luck :(

**Comment by yesmeck** [comment]
I'm using `@types/react@15.6.1`

**Comment by rdvojmoc** [comment]
I get same error as @mitchelldemler when trying to consume my form:
```
import { Row, Col, Spin, Card, Badge, Button, Input, Form } from 'antd'
import { FormComponentProps } from 'antd/lib/form';

interface IContainerProps extends FormComponentProps {
    container: ContainerViewModel;
}
 class ContainerDetail extends React.Component<IContainerProps, any> {
    public render() {
        return <Card>
        <Spin >
            <Form layout="horizontal">
                <Form.Item label="Name:">
                     <Input defaultValue={this.props.container.Name} />
                </Form.Item>
                <Form.Item label="Description:">
                    {this.props.form.getFieldDecorator('', { initialValue: this.props.container.Description })}
                    (
                        <Input />
                    )
                </Form.Item>
            </Form>
        </Spin>
    </Card>;
    }
}

export default Form.create<IContainerProps>()(ContainerDetail);
```

When I try to consume ContainerDetail form:
`<ContainerDetail container={this.props.container}/>;`

Error thrown:
`Property 'form' is missing in type '{ container: ContainerViewModel; }'.`

Libraries used:
```
"typescript": "2.4.1",
"antd": "^3.1.0",
"@types/react": "16.0.34"
"react": "16.2.0",
```

**Pull request merged**
