### PR TITLE
*up rc-menu

### PR DESCRIPTION
**Pull request by plandem**
fixed bug with SubMenu

### CODE REVIEW

**Comment by afc163** [comment]
It is not a bug, `~5.0.1` is basicly same as `~0.5.9`.

**Comment by afc163** [comment]
But still thanks for contributing.

**Comment by plandem** [comment]
@afc163: well, I started to get error about **openKeys** for undefined. Error vanished after  manually upgrade to rc-menu 5.0.9. 

I have antd 2.6.4.

**Comment by afc163** [comment]
You don't have to manually upgrade rc-menu. Just remove node_modules and reinstall antd@2.6.4 and `rc-menu@~5.0.1` will make sure you install 5.0.9.

image

**Comment by plandem** [comment]
then I had some weird issue, because I did npm update and had antd 2.6.4, but my local version of rc-menu was 5.0.1

**Comment by afc163** [comment]
try

```
npm cache clean
rm -rf node_modules
npm install
```

**Pull request merged**
