### PR TITLE
feat: Menu.Item Tooltip props

### PR DESCRIPTION
**Pull request by shanehofstetter**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

* Add tooltipProps to Menu.Item API to allow customization of the tooltip displayed on collapsed menu items

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Add tooltipProps to MenuItem properties |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/menu/index.en-US.md](https://github.com/shanehofstetter/ant-design/blob/feature-menu-item-tooltip-props/components/menu/index.en-US.md)
[View rendered components/menu/index.zh-CN.md](https://github.com/shanehofstetter/ant-design/blob/feature-menu-item-tooltip-props/components/menu/index.zh-CN.md)

### CODE REVIEW

**Comment by afc163** [comment]
What the exact requirement that you need this prop?

**Comment by shanehofstetter** [comment]
@afc163 Specifically I want to change the `trigger` mode of the tooltip, but I'm sure there are other use-cases as well.

**Comment by afc163** [comment]
You need `trigger: 'click'` for Tooltip? Is it odd to show tooltip and trigger router change at the same time?

**Comment by afc163** [comment]
Closing for no more response.

**Pull request closed without merging**
