### PR TITLE
merge feature into master

### PR DESCRIPTION
**Pull request by chenshuai2144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at bddcd17</samp>

This pull request adds new features and improvements to the `Alert` and `Avatar` components, such as component token customization and responsive sizing. It also updates some imports and tests to reflect the latest changes in the `rc-util` package and the `Space` component. It removes some unused files and functions, and enhances the documentation theme and examples.

### <samp>🤖 Generated by Copilot at bddcd17</samp>

*  Add a new demo for the `Alert` component that shows how to customize the component token using the `ConfigProvider` component and the `theme` prop ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-fb7d7806f2618ee8e3d4c642dab76e85e5ee4fc652c257e7c6c25413174ba69cR1-R7), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-ec0f90ae6a022e3df672e490b07e4420fcc821f6424a64d43739504a9ee94ca0R1-R28), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-174ea1bf94f8ca33176522ecbdb934fbd907e6b53ae9307d94f4154fd774f561R34), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-4493184779df5fd085712110fe4651b2cc37c39a689940232ca00af631d8544fR35))
*  Update the `Alert` component style to use the component token from the `ConfigProvider` component, and add some new properties to the `ComponentToken` interface that allow the user to adjust the padding and icon size of the `Alert` component ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-bbbc7b2eb93de110b862d8d30e7a416dab4e3868f9229c53edabbee04363f6baL2-R27), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-bbbc7b2eb93de110b862d8d30e7a416dab4e3868f9229c53edabbee04363f6baL38-R59), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-bbbc7b2eb93de110b862d8d30e7a416dab4e3868f9229c53edabbee04363f6baL53-R68), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-bbbc7b2eb93de110b862d8d30e7a416dab4e3868f9229c53edabbee04363f6baL78-R93), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-bbbc7b2eb93de110b862d8d30e7a416dab4e3868f9229c53edabbee04363f6baL100-R119), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-bbbc7b2eb93de110b862d8d30e7a416dab4e3868f9229c53edabbee04363f6baR132), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-bbbc7b2eb93de110b862d8d30e7a416dab4e3868f9229c53edabbee04363f6baL232-R259))
*  Update the `Avatar` component to use the `useSize` hook and the `componentSize` prop from the `ConfigProvider` component, and remove the default value of the `size` prop ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-a9110968bd15226a58d0270285b7d34c0c37c415a6e5ca231c84fb3fb82ef9efR13), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-a9110968bd15226a58d0270285b7d34c0c37c415a6e5ca231c84fb3fb82ef9efL96-R97), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-a9110968bd15226a58d0270285b7d34c0c37c415a6e5ca231c84fb3fb82ef9efL109-R110), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-ed0541927f27afd8572abefb310376dc0621835f8e150544987f7dfd44f6f2a8L11-R11))
*  Add a new test case for the `Avatar` component that checks the `componentSize` prop of the `ConfigProvider` component ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-fa94f4208bc139f7a0daaa5b065e8212d2d2b56cdff66e3326c2b256f4911af7R7), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-fa94f4208bc139f7a0daaa5b065e8212d2d2b56cdff66e3326c2b256f4911af7R209-R223))
*  Add a new prop `rootClassName` to the `Ribbon` component that allows the user to customize the class name of the root element of the `Ribbon` component ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-14f85870e2c911caa9b080f35767efa029c02b5ecf4118b487c75145b7554f09R20), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-14f85870e2c911caa9b080f35767efa029c02b5ecf4118b487c75145b7554f09R32), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-14f85870e2c911caa9b080f35767efa029c02b5ecf4118b487c75145b7554f09L52-R54))
*  Add a new prop `expandIcon` to the `Collapse` component in the example page, and set it to `false` to disable the default arrow icon ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-fb37d7abd9dddd9f2a8c076bfd9eea2336873f1051d1f37dceaca099206a4aedR486))
*  Update the import of `useEvent` from `rc-util` in `components/alert/WaveEffect.ts` and `components/anchor/Anchor.tsx`, as the `rc-util` package has been updated to export the hooks directly ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-fc6a9164144f215671163f6b1501060f193dd221f446d3dd8ec76bc19499bdd7L2-R2), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-353746edad3f07acb175d7e32c64972b87359b5a0dc4e14e4d3f1133b61e48a8L2-R2))
*  Add a new function `matchScreen` to `components/_util/responsiveObserver.ts`, which takes a `screens` object and a `screenSizes` object, and returns the value of the first matching breakpoint in the `screenSizes` object ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-1cd1627a602528d79cb6ef420545e6efe1b84829291921f70f2b92486c98a6acR128-R138))
*  Remove the function `detectFlexGapSupported` from `components/_util/styleChecker.ts`, as it is no longer needed after the refactor of the `Space` component to use CSS grid instead of flexbox ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-fe8f24d3deab77dc6673d14a10012f8b5fcc44e939c75da39a45cccfc5a32937L7-L41))
*  Add a new TypeScript file `components/auto-complete/__tests__/demo.test.tsx`, which contains the code to test the `AutoComplete` component demos using the `demoTest` and `rootPropsTest` functions from the shared test utils ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-554e207b7b7d95e5e2a1668b26f9fc91991fbe997fdb6caf3f7c72e35669b025R1-R15))
*  Update the `extendTest` and `demoTest` function calls in `components/alert/__tests__/demo-extend.test.ts` and `components/alert/__tests__/demo.test.ts`, and add a new file name `component-token.tsx` to the `skip` option, as this file is a new demo that does not need to be tested by the extend test or the demo test ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-9ec45ba5c8b621a47971fc92accd03ce8f3d80a5112dd461c45b60ae9bac4377L3-R3), [link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-40826e5ec3946bd3e1f4f4aaefb3e86db8b704cb2af9fb2684e0537814432f87L3-R3))
*  Add some CSS properties to the `code` element in `.dumi/theme/common/styles/Markdown.tsx`, to center it and add some margin when it is used as a block element ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-6d4081217418af981e22c0fd474410c584b0d3c238609e557164b0ebd07c9ab4R29-R30))
*  Move the import of `React` to the top of the file in `.dumi/theme/common/styles/Markdown.tsx`, following the convention of importing React first ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-6d4081217418af981e22c0fd474410c584b0d3c238609e557164b0ebd07c9ab4L1-R3))
*  Add an empty line to the beginning of `components/_util/responsiveObserver.ts`, following the convention of leaving a blank line after the file header comment ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-1cd1627a602528d79cb6ef420545e6efe1b84829291921f70f2b92486c98a6acR2))
*  Delete the file `components/_util/hooks/useFlexGapSupport.ts`, as it is no longer needed after the refactor of the `Space` component to use CSS grid instead of flexbox ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-3c9bcc08d5ca09497ef0b2445e641c8a7ade26d9a292638462c633b9485c67d0))
*  Delete the file `components/auto-complete/__tests__/demo.test.ts`, as it is replaced by the new TypeScript file `components/auto-complete/__tests__/demo.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/44676/files?diff=unified&w=0#diff-7e2dd295d05640af165540ce935d8987a459747cabb50bf40139fdbacdf1ef93))

### CODE REVIEW

**Comment by kiner-tang** [comment]
居然还有冲突

**Comment by li-jia-nan** [comment]
要发 minor 了吗？

**Comment by chenshuai2144** [comment]
> 要发 minor 了吗？

是的，我先来修复下冲突

**Comment by yoyo837** [comment]
看上去就是import的地方需要整理一下即可

**Comment by yoyo837** [comment]
#44679 已经合并了 commit 都过去了, 这个PR按理说会自己空了, 或者变成小量change吧, 咋还有那么多

**Comment by yoyo837** [comment]
> #44679 已经合并了 commit 都过去了, 这个PR按理说会自己空了, 或者变成小量change吧, 咋还有那么多

 #44679 也squash了?

**Pull request closed without merging**
