### PR TITLE
docs: improve  preview interaction

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

首页主题预览，选择主题和主色支持键盘交互选择。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      --     |
| 🇨🇳 Chinese |       --    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MadCcc** [comment]
加上 tabIndex 就可以了

**Comment by Wxh16144** [comment]
> 加上 tabIndex 就可以了
> 
> 

我尝试过，貌似并不能实现

**Comment by Wxh16144** [comment]
sorry, 我好像 force-push 了...

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
冲突了

**Comment by Wxh16144** [comment]
> 冲突了

已解决

**Pull request merged**
