### PR TITLE
Make contributing easier

### PR DESCRIPTION
**Pull request by svenefftinge**
### This is a ...
 - [x] Other: Proposal

### What's the background?

This PR simplifies contributions and playing around with the ant-design code base, by adding support for Gitpod a free online dev environment for GitHub with good Typescript support.
I configured it so that it automatically runs
```
npm install
npm start
```
Also port 8001 is exposed and the website will be opened in a preview (see below).

You can use Gitpod for code reviews as well. Just go to a PR and prefix the URL with 'https://gitpod.io/#'. A workspace with the PR changes will be started and open in a code review mode (you can comment and submit reviews within in the IDE)

To get an idea of how Gitpod feels, please try this snapshot:

[Open in Gitpod](https://gitpod.io#snapshot/82201d39-c4e8-4804-a1f4-220ac7d4c3b0)

screenshot 2019-01-13 at 12 58 56

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ztplz** [comment]
LGTM, but it should be used for a while to test if it is useful. I will try to use it and give some feedback.

**Comment by ztplz** [comment]
image
@svenefftinge When I run `npm run start`, it shows `Invalid Host header`. If I miss something?

**Comment by svenefftinge** [comment]
Hi @ztplz, 
you need to set the env variable `DISABLE_HOST_CHECK=true`.
I added it to the start task of the `.gitpod.yml` (see [here](https://github.com/ant-design/ant-design/pull/14307/files#diff-4e0c28ccf9ba5766935eb3f7e564693dR5)).

After merging this PR it will work fine. You can try by opening a gitpod workspace on my fork:

https://gitpod.io/#https://github.com/svenefftinge/ant-design

Does that help?

**Comment by zombieJ** [comment]
Cool. When I edit the file, console print the update info but page not refresh. Could help to config this?

**Comment by svenefftinge** [comment]
> Cool. When I edit the file, console print the update info but page not refresh. Could help to config this?

Yes, I will look into it ASAP.

**Comment by svenefftinge** [comment]
The reload works now, too. Thanks for the feedback.

**Comment by zombieJ** [comment]
hi @svenefftinge, thanks for quick response. Additional question, how to manually open the `preview` window? It  displays randomly...

**Pull request merged**
