### PR TITLE
feat: layout support css variable theme

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [X] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

- #45618

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | layout support css variable theme |
| 🇨🇳 Chinese | 布局支持 css 变量主题 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 3982373</samp>

This pull request refactors the layout component to use CSS variables for theming. It introduces a new `useCSSVar` hook that registers and updates the CSS variables based on the component token. It also simplifies the component style by using a common utility function to generate the token.

### <samp>🤖 Generated by Copilot at 3982373</samp>

*  Import and use `useCSSVar` hook to register and update CSS variables for layout component ([link](https://github.com/ant-design/ant-design/pull/45794/files?diff=unified&w=0#diff-f22153e3f63b1ae5f7b6d84d7ecbd52b795c4ccd564a452021da1205d7c17658R9), [link](https://github.com/ant-design/ant-design/pull/45794/files?diff=unified&w=0#diff-f22153e3f63b1ae5f7b6d84d7ecbd52b795c4ccd564a452021da1205d7c17658R88), [link](https://github.com/ant-design/ant-design/pull/45794/files?diff=unified&w=0#diff-f22153e3f63b1ae5f7b6d84d7ecbd52b795c4ccd564a452021da1205d7c17658L113-R115), [link](https://github.com/ant-design/ant-design/pull/45794/files?diff=unified&w=0#diff-b5f79793df080d44b38da08e11f3c271c9b704c856bb97d3923f94f8a15bdcacR1-R4))
*  Export `prepareComponentToken` function to return default token for layout component with additional properties ([link](https://github.com/ant-design/ant-design/pull/45794/files?diff=unified&w=0#diff-2dfadcf4cb6e7f95c8edf70cc3750abd37a1f8996c4301a40eefb94dd78c118eL4-R4), [link](https://github.com/ant-design/ant-design/pull/45794/files?diff=unified&w=0#diff-2dfadcf4cb6e7f95c8edf70cc3750abd37a1f8996c4301a40eefb94dd78c118eL280-R323))
*  Pass `prepareComponentToken` function as argument to `genComponentStyleHook` function to generate custom hook for applying layout style ([link](https://github.com/ant-design/ant-design/pull/45794/files?diff=unified&w=0#diff-2dfadcf4cb6e7f95c8edf70cc3750abd37a1f8996c4301a40eefb94dd78c118eL280-R323))

### CODE REVIEW

**Comment by MadCcc** [comment]
image
有两处错误

**Comment by MadCcc** [comment]
image
image

**Comment by kiner-tang** [comment]
> image image

我改一下

**Comment by kiner-tang** [comment]
> > image image
> 
> 我改一下

done

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
