### PR TITLE
fix(SubMenu): popupStyle not working

### LINKED ISSUE #47826: Dropdown items 过多时可以添加滚动条么
注意到 Dropdown 的 item 是用 Menu 实现的，但是内容过多时，能否和 Cascader 一样，可以固定弹出高度，出现滚动条？

image

出现滚动条（类似这种效果）： 

image

### PR DESCRIPTION
**Pull request by Wxh16144**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix: https://github.com/ant-design/ant-design/issues/47826#issuecomment-2360737237

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

`<Dropdown />`的 items 是用 `<Menu />` 组件实现的， 在尝试解决 #47826 反馈的问题时，期望通过设置 popup 的样式添加固定高度。

但是 TS 类型定义中有 `popupStyle` ，并且 Rc 也是支持这个属性， 在 #45498 迭代中意外破坏了这次 props 透传...

更多请看有关 pr/issue 链接...

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix the issue of `<Menu />` `popupStyle` not working on `<SubMenu />`.      |
| 🇨🇳 Chinese |    修复 Menu popupStyle 在 SubMenu 上失效的问题      |

@race-of-sloths include

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
@race-of-sloths please include this.

**Comment by race-of-sloths** [comment]
@afc163 Thank you for calling!
    
@Wxh16144 Thank you for the contribution! Join [Race of Sloths](https://race-of-sloths.com) by simply mentioning me in your comment/PRs description and start collecting Sloth Points through contributions to open source projects.

<details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/Wxh16144)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by afc163** [comment]
@race-of-sloths score 5

**Comment by race-of-sloths** [comment]
@afc163 Thank you for calling!
    
@Wxh16144 Thank you for the contribution! Join [Race of Sloths](https://race-of-sloths.com) by simply mentioning me in your comment/PRs description and start collecting Sloth Points through contributions to open source projects.

<details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/Wxh16144)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by afc163** [comment]
@race-of-sloths invite @Wxh16144

**Comment by afc163** [comment]
@race-of-sloths score 5

**Comment by afc163** [comment]
changelog 可以写『修复了 Menu `popupStyle` 在 SubMenu 上失效的问题。』

**Comment by afc163** [comment]
@akorchyn We are trying all of bot commands to see what could it be. What an interesting project!

**Comment by akorchyn** [comment]
Enjoy. By the way, we will have a small Octoberfest-inspired event this October.
You might be curious. This project should have received an official invitation this week, but you have been faster, haha. 
[https://github.com/NEAR-DevHub/race-of-sloths/wiki/RoSctober-Official-Rules](Rules)

**Pull request merged**
