### PR TITLE
Add3.xga ie

### PR DESCRIPTION
**Pull request by AbhijeetGaware**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

-----
[View rendered CHANGELOG.en-US.md](https://github.com/AbhijeetGaware/ant-design/blob/Add3.xga_IE/CHANGELOG.en-US.md)
[View rendered CHANGELOG.zh-CN.md](https://github.com/AbhijeetGaware/ant-design/blob/Add3.xga_IE/CHANGELOG.zh-CN.md)
[View rendered README.md](https://github.com/AbhijeetGaware/ant-design/blob/Add3.xga_IE/README.md)
[View rendered components/card/index.en-US.md](https://github.com/AbhijeetGaware/ant-design/blob/Add3.xga_IE/components/card/index.en-US.md)
[View rendered components/card/index.zh-CN.md](https://github.com/AbhijeetGaware/ant-design/blob/Add3.xga_IE/components/card/index.zh-CN.md)
[View rendered components/date-picker/index.en-US.md](https://github.com/AbhijeetGaware/ant-design/blob/Add3.xga_IE/components/date-picker/index.en-US.md)
[View rendered components/date-picker/index.zh-CN.md](https://github.com/AbhijeetGaware/ant-design/blob/Add3.xga_IE/components/date-picker/index.zh-CN.md)

### CODE REVIEW

**Comment by yoyo837** [comment]
Commits should be clean.

Please checkout to `3.x-table` before change anything.

**Comment by AbhijeetGaware** [comment]
> Commits should be clean.
> 
> Please checkout to `3.x-table` before change anything.

@yoyo837  okay

**Comment by AbhijeetGaware** [comment]
> Commits should be clean.
> 
> Please checkout to `3.x-table` before change anything.

i have to again publish it 
Screenshot 2020-06-06 at 3 23 56 PM

**Comment by yoyo837** [comment]
Where is your new PR?

**Comment by AbhijeetGaware** [comment]
> Where is your new PR?

okay i have to raise again Thanks.

**Pull request closed without merging**
