### PR TITLE
docs: v5 site upgrade

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

preview：https://preview-38328-ant-design.surge.sh/

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    -       |
| 🇨🇳 Chinese |    -       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by li-jia-nan** [comment]
中间这一块在13寸显示器上宽度超了

QQ20221102-113206@2x

**Comment by zombieJ** [comment]
> 中间这一块在13寸显示器上宽度超了

这一条是故意超出去的~

**Comment by afc163** [comment]
- [ ] 切换组件菜单时，右侧内容只有标题，然后才出内容。最好能直接都出来。从组件切换到首页也有类似的问题。
- [ ] 左上角有个奇怪的 Menu。
   图片
- [ ] 右侧锚点样式建议和现在的 antd 官网对齐。
   图片
- [ ] 锚点和内容互相遮挡覆盖。
   图片
- [ ] ConfigProvider 页面应该是单行演示：https://preview-38328-ant-design.surge.sh/components/config-provider-cn#components-config-provider-demo-theme
- [ ] Table 样式没了，和设计师一起搞个新的更好看更好用的表格风格吧。
     图片
- [ ] 导航栏缺边框和阴影。
   图片
- [ ] 右下角的主题切换器建议重新搞搞了，不要再用 configprovider 的例子了。

**Comment by afc163** [comment]
首页动画确实太高了。

**Comment by MadCcc** [comment]
@SocketSecurity ignore @swc/core@1.3.14

**Review by MadCcc — APPROVED** [review]

**Pull request merged**
