### PR TITLE
Fix/translate chinese to english

### PR DESCRIPTION
**Pull request by linkfang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

Background: AntD is a great UI library and I would like to recommend it to a lot of people here in Canada. So, it would be even better to use English comments and example code for EN version. This is kind of the biggest barrier for me to recommend it. (Even though I have been doing so.)

Solution: For all comments and example code I found that are using Chinese, I translated them to English.

### 📝 Changelog

None

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Translated Chinese to English for comments and example code  |
| 🇨🇳 Chinese | 把注释和示例代码中的中文翻译成了英文 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 8a07add</samp>

Translated comments and labels from Chinese to English in some demo files for `Tag`, `Tree`, and `Form` components. Added more explanations for some style and functionality features.

### <samp>🤖 Generated by Copilot at 8a07add</samp>

*  Translate comments from Chinese to English in four demo files to improve readability and accessibility for non-Chinese speakers ([link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-fa631f0975adbbd64a4abb6788c8a5022ccc512ed23b9a64eee553cae49ee018L14-R18), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-da1e896a0ae36c36774dc6cfe29b3962bcc94535aba58940d767bc55c75501c5L28-R28), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-da1e896a0ae36c36774dc6cfe29b3962bcc94535aba58940d767bc55c75501c5L35-R35), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-c8bf3ef37df124ca5ee82d706df5431dcdce979d9ac42de5340d4317c6827a95L43-R43), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-c8bf3ef37df124ca5ee82d706df5431dcdce979d9ac42de5340d4317c6827a95L82-R82), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-c8bf3ef37df124ca5ee82d706df5431dcdce979d9ac42de5340d4317c6827a95L92-R92), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-d8db7449755df23491e9c7e57ab066b083eddb5666606a8ce6ce72edbcd7b8c7L39-R39), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-d8db7449755df23491e9c7e57ab066b083eddb5666606a8ce6ce72edbcd7b8c7L77-R77), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-d8db7449755df23491e9c7e57ab066b083eddb5666606a8ce6ce72edbcd7b8c7L87-R87))
*  Explain the logic and purpose of some style and state properties when dragging and dropping tags and tree nodes in `draggable.tsx` and `drag-debug.tsx` ([link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-da1e896a0ae36c36774dc6cfe29b3962bcc94535aba58940d767bc55c75501c5L35-R35), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-c8bf3ef37df124ca5ee82d706df5431dcdce979d9ac42de5340d4317c6827a95L43-R43), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-c8bf3ef37df124ca5ee82d706df5431dcdce979d9ac42de5340d4317c6827a95L82-R82), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-c8bf3ef37df124ca5ee82d706df5431dcdce979d9ac42de5340d4317c6827a95L92-R92), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-d8db7449755df23491e9c7e57ab066b083eddb5666606a8ce6ce72edbcd7b8c7L39-R39), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-d8db7449755df23491e9c7e57ab066b083eddb5666606a8ce6ce72edbcd7b8c7L77-R77), [link](https://github.com/ant-design/ant-design/pull/43234/files?diff=unified&w=0#diff-d8db7449755df23491e9c7e57ab066b083eddb5666606a8ce6ce72edbcd7b8c7L87-R87))

### CODE REVIEW

**Comment by li-jia-nan** [comment]
update snap pls

**Comment by linkfang** [comment]
> update snap pls

Sorry, what did you mean by snap? 😊

**Comment by yoyo837** [comment]
> > update snap pls
> 
> Sorry, what did you mean by snap? 😊

The `jest` snapshot.

**Comment by linkfang** [comment]
I did run `npm test -- -u` to update the jest snapshots. But there are still failed tests (calendar related ones). 

However I didn't even touch calendar related demo code. Should I revert the changes made by `npm test -- -u` for calendar related files and try again?

**Comment by li-jia-nan** [comment]
You can update snapshot only the files you modified, instead of updating all snapshot, like this:

```base
npm run test:update components/form
```

**Review by li-jia-nan — APPROVED** [review]

**Pull request merged**
