### PR TITLE
fix: Drawer content overflow when placement is top or bottom

### LINKED ISSUE #19454: Drawer: overflowed content cannot be hidden when placement is top
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/mystifying-voice-zoc96)

### Steps to reproduce
Click the open button and click on the mask

drawer-issue

### What is expected?
Hide overflowed the content

### What is actually happening?
Not hide overflowed the content

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | * |
| System | * |
| Browser | * |

### PR DESCRIPTION
**Pull request by shaodahong**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Fixed #19454 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Drawer content overflow when `placement` prop is `top` or `bottom`    |
| 🇨🇳 Chinese | 修复 Drawer 当 `placement` 属性为 `top` 或 `bottom` 时内容溢出   |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by jljsj33** [comment]
https://github.com/react-component/drawer/blob/master/assets/index.less#L31

参照 rc-drawer 加在 content 里吧；

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/blob/fe199acd2fe41ffb3c0cad3e7df8d3c34f803fba/components/drawer/style/drawer.less#L140

**Comment by shaodahong** [comment]
@jljsj33 有一点很怪异, 如果可以滚动, 我滚动一段距离关闭再重新打开, 滚动距离还是上次的, 这个是不是应该优化

**Review by jljsj33 — APPROVED** [review]

**Comment by jljsj33** [comment]
不用忧化，， antd 有关闭后清除子级内容的。。。

**Comment by yoyo837** [comment]
hello, rebase

**Pull request merged**
