### PR TITLE
feat: control Drawer close button placement

### PR DESCRIPTION
**Pull request by Enigama**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution
It would be nice to have option to control close button in drawer, now it's possible only by adding extra css. So solution is simple, add `closePlacement` prop to a drawer, property can have: `left` default or `right` value.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Add property to a Drawer to control close button placement        |
| 🇨🇳 Chinese |     在抽屜中新增屬性以控制關閉按鈕的位置      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Enigama** [comment]
@li-jia-nan can we merge it or something?

**Comment by yoyo837** [comment]
Rebase again please.

**Comment by Enigama** [comment]
@yoyo837 H'm I sync my fork

**Comment by Enigama** [comment]
@yoyo837 Have I done something wrong?

**Comment by Enigama** [comment]
I'll create a new one, i merged main into feature.

**Comment by zombieJ** [comment]
Sorry for delay. In my opinion, there shouldn't be too many configurations for `xxxPlacement` props, as their implementation can become overly fragmented. A better approach would be to use semantic `classNames` to allow developers to customize styles themselves. e.g. to do like Modal:

```tsx
<Drawer classNames={{ header: 'my-header' }} />
```

```less
.my-header button {
  order: 1;
}
```

**Comment by Enigama** [comment]
> Sorry for delay. In my opinion, there shouldn't be too many configurations for `xxxPlacement` props, as their implementation can become overly fragmented. A better approach would be to use semantic `classNames` to allow developers to customize styles themselves. e.g.:
> 
> 
> 
> ```tsx
> 
> <Drawer classNames={{ header: 'my-header' }} />
> 
> ```
> 
> 
> 
> ```less
> 
> .my-header button {
> 
>   order: 1;
> 
> }
> 
> ```
> 
> 
> 
> online demo: https://stackblitz.com/edit/react-csca2w?file=demo.tsx,index.css
> 
> 
> 
> In addition, you can use ConfigProvider to handle all the drawer:
> 
> 
> 
> ```tsx
> 
> <ConfigProvider drawer={{ classNames: { header: 'my-header' } }} />
> 
> ```

Thanks for example with config provider didn't think in that way. Also example with 'order:1' won't help when extra prop, so solution for it is use 'position: absolute' and move to right corner

**Pull request closed without merging**
