### PR TITLE
docs: Update date picker range picker documentation

### PR DESCRIPTION
**Pull request by Kim-Wing-Fung**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/react-component/picker/releases/tag/v1.12.0

### 💡 Background and solution

rc-picker component v-1.12.0 has updated functionality which requires documentation update for Ant Design DatePicker component.

### 📝 Changelog

Documentation update, no code changes.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/date-picker/index.en-US.md](https://github.com/Kim-Wing-Fung/ant-design/blob/update-date-picker-range-picker-documentation/components/date-picker/index.en-US.md)
[View rendered components/date-picker/index.zh-CN.md](https://github.com/Kim-Wing-Fung/ant-design/blob/update-date-picker-range-picker-documentation/components/date-picker/index.zh-CN.md)

### CODE REVIEW

**Comment by Kim-Wing-Fung** [comment]
@zombieJ This is the update to the Ant Design documentation to match the changes for rc-picker@1.12.0

**Comment by afc163** [comment]
1. send this to feature branch
2. upgrade rc-picker to latest version.
3. add TypeScript definition if needed.

**Comment by zombieJ** [comment]
ping @Kim-Wing-Fung

**Comment by yoyo837** [comment]
@afc163 @zombieJ 个人认为这个PR可以接受，因为文档更新的内容在rc-picker是1.10.x, antd这边4.4.0就有了。

**Pull request closed without merging**
