### PR TITLE
chore: unique Empty text color

### LINKED ISSUE #49407: Can renderEmpty consume the theme context?
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/react-2ygwmw?file=demo.tsx)

### Steps to reproduce

View theme configuration for demo.

### What is expected?

Custom `renderEmpty` can consume the theme context.

### What is actually happening?

Custom `renderEmpty` failed to consume the theme context.

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3.1 |
| System | macOS 14.4.1 - arm64 Apple M2 Pro |
| Browser | Chrome: 126.0.6478.62 |

---
My understanding is that the function method, renderEmpty, is only going to be called when the component is rendered, right, and isn't it able to consume the theme context at that point? Or will there be any limitations or workarounds to be done.

### PR DESCRIPTION
**Pull request by zombieJ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #49407

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |        Fix Empty sometime not take `colorTextDescription` as description text color.       |
| 🇨🇳 Chinese |   修复 Empty 部分样式下，描述的 `colorTextDescription` 不生效的问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — DISMISSED** [review]

**Comment by crazyair** [comment]
image

**Comment by afc163** [comment]
这样会导致 https://ant.design/components/empty#empty-demo-customize 这个 demo 会看上去很奇怪。

**Comment by afc163** [comment]
https://camo.githubusercontent.com/b66747b79ed34d57dff947a8d1585435f38afbfbf8b22b664954943591793872/68747470733a2f2f616e74642d76697375616c2d646966662e6f73732d636e2d7368616e676861692e616c6979756e63732e636f6d2f70722d34393430382f76697375616c52656772657373696f6e5265706f72742f696d616765732f63757272656e742f656d7074792d637573746f6d697a652e636f6d706163742e706e673f7265663d3736653036363065

**Comment by zombieJ** [comment]
> 这样会导致 https://ant.design/components/empty#empty-demo-customize 这个 demo 会看上去很奇怪。

现在的 color 不是跟着 description 走的，而是有的地方用了 colorText 有的用 colorDescText。所以其他例子写这种组合也是这个样子的：
截屏2024-06-14 11 26 05

```tsx
<Empty image={Empty.PRESENTED_IMAGE_SIMPLE}
    description={
      <span>
        Customize <a href="#API">Description</a>
      </span>
    }
 />;
```

**Comment by afc163** [comment]
那这个 demo 要改掉，不然看着很奇怪。

**Review by afc163 — APPROVED** [review]

**Pull request merged**
