### PR TITLE
fix: Invalid memoized context value in LocaleProvider

### PR DESCRIPTION
**Pull request by mrwd2009**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
No related issue.

### 💡 Background and solution

In order to make use of cache ability from `memoize-one` library, we must store the wrapped function in a variable.

In `LocaleProvider` component, we have created a new wrapped function from `memoize-one` during each rendering phase.
That won't return same object reference even though `locale` property is not changed.  So all child components subscribed `LocaleContext` will render again if `LocaleProvider` in parent components is rendering. 

I have created an online [demo](https://codesandbox.io/s/naughty-bouman-779gc?file=/src/App.js) to test this problem.
If you click 'Click' button, the rendering counts are same. But the expected result is "Child Rendering Count" should always be 1.
image

### 📝 Changelog
No breaking change.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix ConfigProvider and Anchor rerender unexpectedly.          |
| 🇨🇳 Chinese | 修复 ConfigProvider 和 Anchor 的渲染函数多次运行的问题。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by mrwd2009** [comment]
@afc163 The Lint error has been fixed.

**Comment by afc163** [comment]
Could you help to fix Anchor too?

https://github.com/ant-design/ant-design/search?q=memoizeOne

**Comment by mrwd2009** [comment]
Got it, I will check it later.

**Comment by mrwd2009** [comment]
Same problem has been fixed in Anchor component.

**Pull request merged**
